### ISSUE TITLE
Getting 404 on uploaded images

### ISSUE THREAD

**Issue by alexalnaib** [Azure/api-management-developer-portal#1000]
We have a few instances of API Management which are all working fine with the migration script except one of them is getting 404 on our uploaded images. We aren't using a custom storage account to store them, just the media Storage Account managed by API Management.

Using scripts.v2 as well.

![image](https://user-images.githubusercontent.com/30583851/97500503-93e5bc80-19d4-11eb-9b2a-035368a2ab39.png)

![image](https://user-images.githubusercontent.com/30583851/97500552-ae1f9a80-19d4-11eb-8616-573e00a5835b.png)

**Comment by azaslonov** [comment]
Hi @alexalnaib, you're saying it's just one specific media file, the rest copied fine?

**Comment by alexalnaib** [comment]
Hi @azaslonov thanks for the quick reply.

It's all of our uploaded images. Though it seems that the issue is now gone for some reason so you can close this ticket.

Cheers,
Alex

**Comment by azaslonov** [comment]
Ok, great, glad you were able to overcome this. Thanks.
