### ISSUE TITLE
local envionment setup guide

### ISSUE THREAD

**Issue by GPRepo** [Azure/api-management-developer-portal#1002]
Hi, I'm able to compile the code sucessfully. But local host stays in black page. I understand there is apim url configuration to run this project. Is any documentation available with detail steps . How to configure,run and see the output locall browser.

Thanks.

**Comment by azaslonov** [comment]
Hi @GPRepo, 
Sorry, not sure I understand this: "But local host stays in black page."

The documentation describing the steps is here: https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal

Hope that helps.

**Comment by GPRepo** [comment]
My localhost url loading blank page while executing the command npm start. Anyhow thanks for sharing the steps to work on self hosting.Its helpful.Thank you.

**Comment by mikebudzynski** [comment]
Please, request assistance from Azure Support - they will be able to identify your problem and address it.
