### ISSUE TITLE
Can't publish our developer portals

### ISSUE THREAD

**Issue by LockTar** [Azure/api-management-developer-portal#1005]
## Bug description

Can't publish developer portal changes. Changes are saved but can't publish them.

## Reproduction steps

1. Go to the Azure portal.
2. Click on portal overview in the menu of APIM
3. Click publish
4. Refresh page after few seconds and the old date is there again. No publish is done. Even after days. Also publishing from the developer portal admin menu isn't working as well. The message says successfully scheduled publish but nothing happens.

## Expected behavior

My changes should be visible

## Is your portal managed or self-hosted?

Managed

## API Management service name

saint-apim-dev
saint-apim-tst
saint-apim-acc
saint-apim-prd

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome, Microsoft Edge
 - Version: latest (86)

## Additional context

![image](https://user-images.githubusercontent.com/1568453/97578464-1e3c1980-19f1-11eb-9b63-05861e663402.png)

**Comment by azaslonov** [comment]
Hi @LockTar, I think we found the issue, we're working on the fix.
On a side note, can you please confirm that you're using migration scripts with those services?

**Comment by LockTar** [comment]
Hi @azaslonov, Sounds great! 
Yes I can confirm that. We are using the migration scripts to deploy to the other environments. We adjust the dev environment and then run a pipeline to migrate all the changes to the other environments.

**Comment by LockTar** [comment]
Hi @azaslonov,
Any idea when this is fixed? I want to update the sign in page with some simple text.
Reason is that you can't login (Azure AD) with the "old" Microsoft Edge browser. The new Chromium based Edge or Google Chrome browser works fine. We get a lot of questions about this... Did you know about this bug? I saw some issues closed about sign in. I hoped this was fixed and that was the reason I wanted to update/publish the developer portal in the first place...

**Comment by azaslonov** [comment]
Hi @LockTar, it has been fixed in this repo, but the release to the managed version will start on 11/6.

Regarding AAD and "old" Edge, I believe you're talking about version 85 and below. I tried just now, looks to be working. Can you please collect Network traces and send us to apimportalfeedback@microsoft.com?

**Comment by Radamonas** [comment]
Any news on this? I haven't seen release note about it yet.

**Comment by azaslonov** [comment]
Hi @Radamonas, the release is in progress, it should reach all the regions in a few days.

**Comment by SherwoodCH** [comment]
Hi @azaslonov, do you know when it is available in europe-west? We really should publish the latest changes on our dev portal.

**Comment by azaslonov** [comment]
Hi @SherwoodCH, West Europe will be updated on 11/12 around 1PM PST.

**Comment by azaslonov** [comment]
Hi everyone. All public cloud regions updated, so closing the issue. Thank you all for your patience.
Please feel free to follow up shall you still experiencing the issue.
