### ISSUE TITLE
Notification templates - display of the image of the company logo not possible

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1006]
## Bug description / expected behavior

On the notification templates page in the APIM portal, using an image html tag with a reference to a png image in a public blob storage does not work. 

I tried to add the following html line:
**<img src="https://_xyz_.blob.core.windows.net/publicmedia/logo.png" alt="$OrganizationName logo>**

But after adding this line, I was not able to save the notification template anymore as the html validity check failed according to the save message that appears in the upper right corner on this page.
 
Opening an html file with the copied html text in the Chrome browser shows that the image can be correctly displayed!

For us our corporate identity is very important and we must design emails according to our company´s look & feel.

Therefore, I request to allow the image tag in the notification templates according to the html 5 standard.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Chrome (latest)

**Comment by azaslonov** [comment]
Hi @AnRei123, in your example I see a missing closing quote:
`<img src="https://xyz.blob.core.windows.net/publicmedia/logo.png" alt="$OrganizationName logo>`

I believe it should be like this:
`<img src="https://xyz.blob.core.windows.net/publicmedia/logo.png" alt="$OrganizationName logo" />`

I tried it and was able to save.

**Comment by AnRei123** [comment]
You are right, Thank you very much!! Now it worked also for the email notifications.

**Comment by AnRei123** [comment]
One additional question: In my email notification for the subscription requests, I also provide a link to the profile page in the DevPortal the following: 
"You can access your profile page using the link below: 
devportal-xyz.test.xyz.xyz.com/profile"
When clicking this link in the email notification, the browser opens and for a one second the profile page is displayed. But then the browser shows the Sign-in page. After signing in, the home page instead of the profile page is shown. 
If you clicked the link once and signed-in and click a second time on the link from the e-mail, the browser correctly displays the profile page. Is this still an open issue (bug) or is there any setting/configuration for the APIM environment wrong? Would be great if deep links would also correctly work from email notifications by clicking the referenced link to the DevPortal sub page only once.
