### ISSUE TITLE
Some Images in Pages just disappeared

### ISSUE THREAD

**Issue by RudyWKM** [Azure/api-management-developer-portal#1010]
Environment: Managed

Some Images referenced on the portal pages have disappeared: their reference is in the code, the images are even showing in the designer view but not as a user (in the browser console, we get 404s for missing images **/content/<imagefilename>.jpg|png**).
When I click on an (visible) image from within the designer view, all thumbnails from the media library are like transparent images ("checker boards").

We have 2 environments, and it happens on both:
env1: "PortalVersion":"202010291247","CodeVersion":"20201022233821","Version":"0.16.1085.0"
env2: "PortalVersion":"202010291248","CodeVersion":"20201022233821","Version":"0.14.1072.0"

The 2 portals were republished yesterday but I cannot say if the images were already missing before republishing. I mean they were visible at one point, but I don't know if the action of republishing yesterday made the images disappear.

**Comment by azaslonov** [comment]
Hi RudyWKM, I believe you have used a migration script recently? If yes, we know of the issue and working on the fix, which will be included in next week's release.

**Comment by sbenji77** [comment]
Hello azaslonov,
I have had the same problem since I migrated my site.
I can no longer add images either, which is a constraint because we have to deliver the site this week.
Do you know the day of this fix please?

Benjamin

**Comment by azaslonov** [comment]
We are planning to start rolling out today. It will take a few days to reach all the regions.

**Comment by mikebudzynski** [comment]
The rollout of the managed version will start on Monday next week. If you're using a self-hosted portal, the release is already available in the repository.

**Comment by sbenji77** [comment]
Hi, 
my instances are selfhosted but I still can't push images on any of the instances. is there a manipulation to perform please?

**Comment by mikebudzynski** [comment]
Have you upgraded your portals and scripts to the latest release 2.5.3?

**Comment by azaslonov** [comment]
The public cloud has been upgraded. For managed portals, please just re-publish. For self-hosted, pull the latest changes from master.
