### ISSUE TITLE
How to customize a single page content?

### ISSUE THREAD

**Issue by Nazarah** [Azure/api-management-developer-portal#1013]
Hi,
I am trying to use CMS functionality of Developer Portal.
For a single page, how can I do the following?

1. Adding a **table of contents** with section hyperlinked section headers (e.g. _clicking on header navigates the user to that specific section_)

2. **Code blocks** with options to copy added code snippets

3. Is there any possibility to use  `id` of a section/header within a text hyperlink to refer to a section on the same page? (e.g. _https://developerportal.com/guides/guide1/#login-to-sandbox_)

**Comment by azaslonov** [comment]
Hi @Nazarah, 

1. The Table of contents can be done with a Menu widget with "vertical" layout, and section headings can be shown by ticking the respective checkbox:
![image](https://user-images.githubusercontent.com/2320302/98185167-f6e9be80-1ec0-11eb-92e8-70bb2edbd6ba.png)

2. Code block currently don't have Copy button, but it certainly makes sense to add it. I have created work item for tracking: https://github.com/paperbits/paperbits-demo/issues/169

3. Yes, the Hyperlink selector allows to chose anchors for page headings. For instance:
![image](https://user-images.githubusercontent.com/2320302/98185674-f4d42f80-1ec1-11eb-9103-30c99062d00e.png)

Hope that helps.
