### ISSUE TITLE
Notification templates - some standard html tags are not supported

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1018]
## Bug description / Expected behavior

Currently, it seems that the two following tags are not supported for the APIM notification templates:
- &nbsp ;  (non-breaking-space-tag - empty space w/o allowing a line break)
- &sup1 ; (numbers for footnotes that are referenced in the content)

Our company already provides validated html notification templates that work with several messaging services very well.
I am not aware on any suitable alternatives for the two html tags for the required functions.

_Currently, when entering  and saving one of these html tags in the notification template field, an error message is shown in the upper right corner stating that the html script is invalid._

**Please, support the usage of these two standard html tags** to facilitate adapting our corporate notification templates.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Chrome (latest)

**Comment by mikebudzynski** [comment]
@AnRei123 - thanks for reporting the issue. I created an internal work item for us and will now close the issue here, since it's not related to the developer portal code.
