### ISSUE TITLE
Display the name of truncated API operations

### ISSUE THREAD

**Issue by mikebudzynski** [Azure/api-management-developer-portal#1019]
1. Implement a tooltip on hover to show the full operation name.
2. Add a widget configuration option to wrap words to new lines (off by default).

![image](https://user-images.githubusercontent.com/40186513/98162512-57afd180-1e96-11eb-974f-d4297244ba2a.png)

**Comment by AnRei123** [comment]
1) I like the proposal with the _tooltips on hover_ to show the full operation name. 
2a) Our developers need also be able to _navigate based on the displayed path names._ The path names are very hidden currently below the summary and description of an operation and the API version details. Mostly, you need to scroll down to see the path. 
2b) Even the widget configuration to directly jump to the top of the operation description is not really helpful as the description of the API version might also be required in some cases. 
2b) So, especially in the published version, _a switch between the summary view and the path view must be available for all user to use on the fly w/o a special configuration in the editing mode.
3) To additionally provide a setting in the web widget in editor mode to show the operation summaries in several lines by breaking the lengthy summary names, would ,of course, also be helpful. _A slider that allows to increase the width of the list of operations would be more helpful_ in combination with the tooltip. If we break the lengthy names of of the operation summary in  several lines, this might lead to very lengthy list of operations and might make it hard again to orientate.
