### ISSUE TITLE
Notification templates - $DevPortalUrl placeholder not linking to the new DevPortal (sporadic and repeating issue)

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1021]
## Bug description

This week, I updated again the notification templates for several instances. I tested a lot the last days. On some days the link target had been correctly resolved for the variable $DevPortalUrl across several instances. But suddenly this week, the URL placeholder has been replaced again with the wrong URL to the legacy portal! 
And, of course, the referenced sub pages could therefore not be found by the browser! Please fix this issue permanently. I already received complaints in the last weeks about this wrong behavior and wondered as during my tests the behavior seemed to be ok. But now the bad behavior is back again!
When our customers receive the notifications with the outdated URLs, they perceive it as very poor and unprofessional! Please help to fix it soon and permanently.

For one instance, I just published the DevPortal again. After publishing, the DevPortal URLs in the notifications are ok again. That is really a weird behavior. It seemed that publishing might solve the issue even it is VERY weird. BUT it does not. The next day, it did not work again!

Instead of the DevPortal URL, the placeholder is substituted by the Gateway URL when sending. If you click on the Gateway URL link, you will be directed to the legacy portal pages.

Please fix this issue as soon as possible. For us, it is VERY important that the partner only see the new portal and not the old one. The old portal pages are not maintained anymore and contain wrong information and wrong branding!!!

## Expected behavior
When using the placeholder $DevPortalUrl in notification templates and when sending the notification always the correct URL to the new portal is generated without the need of publishing the portal again after making changes to the notification templates.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Chrome (latest)

**Comment by azaslonov** [comment]
Hi @AnRei123, that is super weird. Do you use some kind of delegation, or it's a regular managed version setup? Portal itself doesn't send emails, so the issue might be somewhere else.

In any case, the simplest fix would be to replace `$DevPortalUrl` variable with the actual portal URL. Otherwise, we would need a reproducible state and more details (like what notification, what/when action happened, the content of email itself) to investigate it further.

**Comment by azaslonov** [comment]
Resolved the issue offline. Closing.

**Comment by AnRei123** [comment]
Please reopen this ticket. After your latest update, the issue occurred again.

**Comment by pacharanero** [comment]
I have also noticed the links in the emails direct to the Legacy Developer Portal not the new one. This is a super annoying bug and it is hard to see where (if possible) I can change the URL in the APIM control panel.

**Comment by mikebudzynski** [comment]
@pacharanero,

1. Could you clarify which email flows are impacted? For example, are those the emails that are sent to users after they sign up in the developer portal or are they the emails sent when you invite users in the Azure portal?
2. Which variable do your email templates contain? Is it $DevPortalUrl?

**Comment by baskialdensys** [comment]
New subscription activated - template. 
<a href="http://$DevPortalUrl/products/$ProdId">
$DevPortalUrl $ProdId

anywhere $DevPortalUrl used the link shows up as 'http://{' in the actual email.

**Comment by schuettecarsten** [comment]
> anywhere $DevPortalUrl used, the link shows up as 'http://{' in the actual email.

@baskialdensys @azaslonov 
Same problem here, workaround is to replace the DevPortalUrl directly in the email template.

**Comment by baskialdensys** [comment]
Thanks, [schuettecarsten], $DevPortalUrl was working fine for long time. I'm not sure what changed in API management template engine?

**Comment by manjzu** [comment]
for us, $DevPortalUrl seems to not work for "Developer welcome letter" otherwise, for other templates it is showing correctly with custom domain host name.

any workarounds other than hard coding host name as we need to apply fix in various environments.

**Comment by baskialdensys** [comment]
No workarounds; I'm disappointed that the API template team has not addressed this simple issue.
