### ISSUE TITLE
Identify release version of developer portal.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#1022]
## Bug description
Hi there,  every week microsoft is releasing new releases for developer portal. we went for production 3 months back and we are not sure which release is there in production. to include latest release, we must publish the developer portal so that new changes can be included in production as well. my question is, if we have something that can tell us what release version developer portal has, so that based on that we will get to know whether we publish the developer portal or not. as we can see portal published date in portal overview of azure portal.
![image](https://user-images.githubusercontent.com/30490543/98348305-8ff21400-203e-11eb-8c75-b97f94387789.png)

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @shashiguru, first of all, soon we're rolling out automatic codebase updates, so you won't have to re-publish it anymore. For the time being, you can use `/internal-status-0123456789abcdef` to see if your codebase version is higher than your published portal version, and trigger publishing, if you'd like to:

`{ ..., "PortalVersion":"202010022302", "CodeVersion":"20201022233821", ... }.`

Hope that helps.

**Comment by shashiguru** [comment]
@azaslonov where can i find this information? i mean "{ ..., "PortalVersion":"202010022302", "CodeVersion":"20201022233821", ... }." information.

**Comment by shashiguru** [comment]
Hey @azaslonov, could you please tell me what is the "Version" refers in below details.
 {"Status":200,"PortalVersion":"202010281234","CodeVersion":"20201022233821","Version":"0.14.1072.0","RoleNumber":"Proxy.Host.WebRole_IN_0"}
