### ISSUE TITLE
Translation in developer portal

### ISSUE THREAD

**Issue by remyagrai** [Azure/api-management-developer-portal#1026]
Is it able to include translation of portal using javascript

**Comment by mikebudzynski** [comment]
Yes, you can inject custom JS libraries in the self-hosted portals.

**Comment by remyagrai** [comment]
But How can I get the translated version of data.json, How to edit these content

**Comment by azaslonov** [comment]
Hi @remyagrai, could you please describe your scenario end to end, what and how you want it to be?

**Comment by remyagrai** [comment]
Actually i need  a translation for Api portal , For eg:
![image](https://user-images.githubusercontent.com/59555210/100192591-b273a080-2f0b-11eb-8d5c-f73fe969d01e.png)
I want to insert a translation button here, select chinese we want to tranlsate the page like that, For that i need to know how to translate the content of page, Is these any specific option to enable translation in api portal?

**Comment by remyagrai** [comment]
how to change the Welcome to contoso from code?

**Comment by mikebudzynski** [comment]
This functionality is not yet available in the developer portal; see #137. You can inject custom libraries that will translate the text on-the-fly in the self-hosted portal.
