### ISSUE TITLE
Improve error handling in migrate.v3 script and auto publish?

### ISSUE THREAD

**Issue by LockTar** [Azure/api-management-developer-portal#1032]
## Bug description

Error handling in migrate v3 script is missing. I'm trying to automate my developer portal environments in an Azure Pipeline. When calling the migrate script I only see "Exporting..." and then errors:

```
TypeError: Cannot read property 'map' of undefined
    at ImporterExporter.getContentTypes (D:\a\1\src\scripts.v3\utils.js:138:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ImporterExporter.captureContent (D:\a\1\src\scripts.v3\utils.js:241:30)
    at async ImporterExporter.export (D:\a\1\src\scripts.v3\utils.js:307:9)
    at async migrate (D:\a\1\src\scripts.v3\migrate.js:72:5)
```

Reason is not enough permissions of the service endpoint in Azure Pipelines. 

Auto publish isn't working for v3 right? So you manually need to call publish in the Azure portal? Any ETA when this is fixed?

## Reproduction steps

1. Call migrate script in Azure Pipeline from an `AzureCLI@2` task with source (in example) dev and destination tst.
2. Set the task to the service endpoint connected to you tst subscription.
2. See error

## Expected behavior

A clear error that there is not given that exporting fails because not enough permissions. I was expecting a 401 result.
Update documentation that migrate v3 needs permissions on both APIM instances. Sounds logical but because of the strange error it was searching for the real reason.

Possible workaround: migrate in multiple Azure Pipeline tasks steps but not ideally. So in example a step for exporting and a step for cleaning/importing.

## Is your portal managed or self-hosted?

Managed

## API Management service name

saint-apim-xxx (xxx is environment dev, tst etc)

## Environment

 - Operating system: Windows 10
 - Browser: Edge
 - Version: Latest

## Additional context

Every API Management portal live in separate Azure subscription. An Azure Pipeline service endpoint can only be connected to 1 subscription.

When using the tst service endpoint
![image](https://user-images.githubusercontent.com/1568453/99266554-2a164100-2823-11eb-9ffd-44aaca18cd0c.png)

When using the dev service endpoint
![image](https://user-images.githubusercontent.com/1568453/99266663-4ade9680-2823-11eb-9ed1-889aabe986c5.png)

**Comment by LockTar** [comment]
@azaslonov pr looks great. Any idea when auto publishing will be done?

**Comment by azaslonov** [comment]
We need to release a new publishing endpoint in the management API (hopefully in the next 4 weeks), then we'll just uncomment the request in migrate.js script.

**Comment by mikebudzynski** [comment]
See this issue for tracking: https://github.com/Azure/api-management-developer-portal/issues/1039
