### ISSUE TITLE
Can't confirm new account on self-hosted portal

### ISSUE THREAD

**Issue by hugbro** [Azure/api-management-developer-portal#1034]
## Bug description

When self-hosting the portal a user is unable to confirm account. 

The developer tools in Firefox show that a request to the management api fails with a 400 error (blocked by CORS policy).

## Reproduction steps

1. Go to the homepage
2. Click on 'Sign Up'
3. Fill in and create an account.
4. Open link in email
5. Browser shows the signup page again.

## Expected behavior

User gets a message with the confirmation of his account.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[release `2.5.3`](https://github.com/Azure/api-management-developer-portal/releases/tag/2.5.3), [commit `afa75bd9d558d4f41ec98d75d2fb30104e659caf`](https://github.com/Azure/api-management-developer-portal/commit/afa75bd9d558d4f41ec98d75d2fb30104e659caf)

## Environment

 - Operating system: Windows
 - Browser: Firefox
 - Version: 82.0.3

## Additional context

The `New developer account confirmation` template is configured as:
`https://[storageaccountname].z15.web.core.windows.net/signup?$ConfirmQuery`

Besides that, i've already configured the CORS policies in storage account as mentioned in wiki section of self hosting the portal.

CORS error when trying to activate accounts:

![image](https://user-images.githubusercontent.com/20343825/99309288-f4c81e00-2837-11eb-9d22-3ee9ac500088.png)

**Comment by mikebudzynski** [comment]
@hugbro Can you please share your service name here or via an email to apimportalfeedback@microsoft.com?

**Comment by hugbro** [comment]
> 
> 
> @hugbro Can you please share your service name here or via an email to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com)?

Service name: hwkstg-apim

Thanks.

**Comment by mikebudzynski** [comment]
Thanks, we'll look into the issue.

**Comment by hugbro** [comment]
Just complementing it, I tested other versions and the most recent one that worked was 2.4.2.

**Comment by mikebudzynski** [comment]
This issue is affecting self-hosted portals. The fix is already committed in the master branch and will soon be published with the 2.5.5 release.

**Comment by cyc4** [comment]
Hello @mikebudzynski mikebudzynski
My customer cannot update their code base currently since their production environment will freeze for a while.
Is there any other workaround suggested without updating to latest release(2.5.5). Such as updating templates as a workaround? 
Thank you.
