### ISSUE TITLE
Migration scripts.v2/migrate.js not working for certain instances.

### ISSUE THREAD

**Issue by ChristopherEquinor** [Azure/api-management-developer-portal#1035]
## Bug description

We have 4 APIM environments; sandbox, dev, test and production. When using scripts.v2/migrate.js migrating from sandbox to dev, everything works except two images not displaying in dev. When migrating from dev to test, absolutely nothing is migrated; no images, no styling, nothing. 

When migrating from dev to test, the script returns no errors, and runs as expected. 

## Reproduction steps

1. Use scripts.v2/migrate.js with appropriate parameters. 
2. Script returns no errors.
3. Navigate to destination developer portal.
4. Nothing is migrated from source.

## Expected behavior

Source developer portal is copied to the destination developer portal. 

## Is your portal managed or self-hosted?

Managed

## API Management service name

Migrating from omniaapimdev to omniaapimtest

## Environment

 - Browser: Chrome version 86 on windows 10
 - Script environment: GitHub actions, ubuntu-latest

## Additional context
![image](https://user-images.githubusercontent.com/44460490/99368756-d3a91100-28bb-11eb-9522-d5c82079b829.png)

* Sandbox, dev and test were all updated(published) on the 16.11.2020.
* All instances run in North Europe.
* scripts.v2/migrate.js version is from 17.11.2020

Like mentioned further up, when migrating from sandbox to dev, everything works except two images. It's only when migrating from dev to test that nothing is copied.

**Comment by mikebudzynski** [comment]
@ChristopherEquinor Most likely, your script configuration is incorrect. We're working on better error reporting in the script; in the meantime, you can debug it to see where the problems are.

**Comment by azaslonov** [comment]
Hi @ChristopherEquinor, I have made some fixes and added better error messaging. Please pull the latest and give it a try.

**Comment by ChristopherEquinor** [comment]
Hi @azaslonov. I can confirm it was an issue due to incorrect parameter values on my part. 

However, even after I used the latest commit, I didn't get any error messages when using incorrect values for parameters **--sourceKey** or **--publishEndpoint**.

**Comment by marcin-dudek** [comment]
I had exactly same issue. I was able to fix it by enabling CORS (Portal overview -> Enable CORS). 
Not sure I missed it in documentation or it is not present there (in this case will be happy to contribute, just let me know where is best place to put it).
