### ISSUE TITLE
Highlight the mandatory query parameters and headers in tryout

### ISSUE THREAD

**Issue by sarah-h123** [Azure/api-management-developer-portal#1037]
##  Bug description
In the legacy dev portal when you trying out an API you get directly a clear picture in red box for the mandatory query parameters and headers that need to be filled in before tying it out. That is not the case in the new dev portal

**Example from Legacy dev portal:**
 ![image](https://user-images.githubusercontent.com/74613127/99415156-d0cc1180-28f7-11eb-90f5-51fdee362e50.png)

 
**Example from new dev portal:**
 ![image](https://user-images.githubusercontent.com/74613127/99415196-daee1000-28f7-11eb-8fac-9b0c7e590acd.png)

In the new dev portal. You will only get informed once you have try the API once 
 
![image](https://user-images.githubusercontent.com/74613127/99415584-3fa96a80-28f8-11eb-8a4d-575761ead5aa.png)

## Expected behaviour

Would be nice to have these  highlighted from the beginning  in the new dev portal 

## Reproduction steps

1. Go to the developer portal 
2. Choose an API 
3. tryout

## Is your portal managed or self-hosted?
Managed

**Comment by mikebudzynski** [comment]
Thanks for bringing this up!
