### ISSUE TITLE
HTML code injection

### ISSUE THREAD

**Issue by sbenji77** [Azure/api-management-developer-portal#1041]
## Bug description

Hi, When you try to insert an html tag, for example with toggle code, the tags are displayed in front after publishing it.

## Reproduction steps

1. Go to 'Developper portal'
2. Use text editor and select your tag
3. Click on 'Toggle code'
4. Publish and we can see the code in clear text in front

## Expected behavior

We would like to be able to insert small HTML snippets for example.

## Is your portal managed or self-hosted?

Self-hosted

On admin page
![image](https://user-images.githubusercontent.com/14352856/99588305-a6a74c00-29ea-11eb-9582-cc54542ffb77.png)

On front page 
![image](https://user-images.githubusercontent.com/14352856/99589635-91cbb800-29ec-11eb-9e7f-8732f24a5e07.png)

Thank you for your Help
Cordialy

**Comment by azaslonov** [comment]
Hi @sbenji77, I actually just tried it, looks like it renders fine: 
![image](https://user-images.githubusercontent.com/2320302/99602798-f1a76c00-29b6-11eb-8597-03a97e5a2997.png)

Unless you want it to be rendered as:

- test1
- test2

If that's what you mean, then we don't support HTML injection into the page.

**Comment by sbenji77** [comment]
It's a pity that it doesn't work because to customize some pages it would be a great simplification. Even the H tags at home don't work. Isn't this code toggle tool made for adding code? 
![image](https://user-images.githubusercontent.com/14352856/99651362-c8d6b380-2a56-11eb-873a-071fd78f925c.png)
On front
![image](https://user-images.githubusercontent.com/14352856/99651691-3be02a00-2a57-11eb-8f1b-38b2f80674e1.png)

Benjamin

**Comment by mikebudzynski** [comment]
We have plans to create a widget that will allow HTML code injection. I will mark this Issue as a feature request to track the progress.

**Comment by sbenji77** [comment]
Hello,

I would like to be able to add a modal, a slider, an anchor. I'm also looking for the possibility to put a search field in the pages as well but it's mainly for customisation.

Cordialy

**Comment by AnRei123** [comment]
Hi, 

I would be also interested for the widget with the html code injection for the following use cases:
- create table and table styles
- allow to display of user-specific content based on the attached user groups. BUT the users should only be able to see information on APIs according to the assigned access groups in the APIM management.
- list and re-use change log content for API versions with breaking changes to allow the user to have an overview of all breaking changes along the timeline. As the changelog content already consist of html code injection, this is a prerequisite for a re-use. We would do the content generation for this widget outside of the DevPortal before deploying to another environment. But all our portals are managed.

**Comment by AdeZwart** [comment]
I would also love to see some possibilities to inject HTML code. Mainly to add a small table to a page.

**Comment by mikebudzynski** [comment]
Referencing #931

**Comment by mikebudzynski** [comment]
Thanks for sharing all the feedback. If you're facing any other challenges that an HTML code injection widget would solve - please, post them in this thread.

**Comment by AnRei123** [comment]
Add-on - options enabled by html snippets:
- Add customized buttons
- Support dynamic contents (e.g. lists, display tenant/customer-specific information) and API calls with information on the logged in user
- Support form and configurations fields for registering and configuration workflows. Allow users to enter individual contents.
- Get rid of maintaining/updating central menu elements separately for each template page by having centralized menu items (more sophisticated, dynamic and with better UX), if possible without too much efforts and too many workarounds and compromises.
- Centralized search and search field. Still hoping that this feature will be offered by standard widgets for the managed approach.

**Comment by mikebudzynski** [comment]
Thanks for the feedback so far. We're now working on the problem space research and we need your feedback on the below points **for each scenario you'd like to use HTML code injection widget**. We appreciate all answers - please, post them in this thread or directly to apimportalfeedback@microsoft.com with the issue number #1041 in the subject.

1. Can you briefly describe the scenario you'd like to use the HTML code injection widget for?
1. Do you need to reuse the custom code across the portal?
1. Do you need to reuse the media files from the portal in the custom HTML code?
1. Do you need to reuse styling from the styling guide in the custom HTML code?
1. Do you need to reuse CSS styling across several instances of custom HTML code?
1. Do you need client-server validation? For example, server validation if an entity submitted through a custom HTML form already exists.
1. Do you need user authentication? For example, if an external service can be reached only by a user logged into the portal.
1. Do you need authorization? For example, if the external service can be reached only by a logged-in user with a given claim.
1. Do you need another authentication to secure the communication with the server? For example, a non-user-specific token.
1. Do you need to authenticate users inside the custom HTML code with authentication other than OpenID Connect? For example, username and password.

**Comment by AnRei123** [comment]
1.	Can you briefly describe the scenario you'd like to use the HTML code injection widget for?
              _AR: _use cases in future might be for example:
               - adding own buttons with a dedicated behavior such as a dedicated download button including icons.
               - adding viewports for external application snippets 
               - simplify external authoring support and markdown migration/synchronization.
               - support individualized table and list formats 
               - allow embedding forms to simplify request processes
               - Embedding dynamic and/or user-specific data/diagrams.
               - Embedding customer forums
               - Use special formats and designs_  
2.	Do you need to reuse the custom code across the portal?
             _AR: Haven´t thought about the advantages of this option yet. Might be._
3.	Do you need to reuse the media files from the portal in the custom HTML code?
             AR: yes, we would not like to manage the images externally.
4.	Do you need to reuse styling from the styling guide in the custom HTML code?
             _AR: per default yes. Should be possible to change the styling on demand._
5.	Do you need to reuse CSS styling across several instances of custom HTML code?
             _AR: yes, we currently already do for adding deprecation notes in the API descriptions. Here we refer to external stylesheets. But it would be good if everything would be at one place to keep the overview._
6.	Do you need client-server validation? For example, server validation if an entity submitted through a custom HTML form already exists.
               _AR: yes, we might need to be able to do such kind of validations._
7.	Do you need user authentication? For example, if an external service can be reached only by a user logged into the portal.
               _AR: yes, user authentication should be managed centrally by the portal._
8.	Do you need authorization? For example, if the external service can be reached only by a logged-in user with a given claim.
                _AR: yes authorization to access/view dedicated data should be managed by the portal._
9.	Do you need another authentication to secure the communication with the server? For example, a non-user-specific token.
               _AR: not sure yet, Might be to access dedicated Azure and non-azure services._
10.	Do you need to authenticate users inside the custom HTML code with authentication other than OpenID Connect? For example, username and password.
               _AR: not thought about this yet, Currently, there is nothing like this planned._

AR:_Remarks:
For the markdown scenario it would be great if the the html code snippets could have dedicated place holders to allow developers to provide the markdown files as media files/packages that can be easily uploaded/updated or replaced in the media folder and that are automatically converted and replaced in the code snippet if the media file is correctly linked._

**Comment by AnRei123** [comment]
Here an additional remark regarding question (7) above:
7. Do you need user authentication? For example, if an external service can be reached only by a user logged into the portal.
_AR: yes, user authentication should be managed centrally by the portal.
AR: It be also possible to login to another intranet service. Today I newly discussed such an upcoming and required use case with one of my colleagues. Here we like to embed external html sub pages that should be accessible by dedicated user groups. And that page might have an own sign-in mechanism. Not 100% clear at the current time what exactly will be required._

**Comment by sbenji77** [comment]
Hi,

Our needs

###     Can you briefly describe the scenario you'd like to use the HTML code injection widget for?**
1 - To make a table, a slider, insert a video iframe. To be able to adjust block sizes, for example min-height.
In this last point for example a simple page without much content will put a white frame if the background is of a different colour

###     Do you need to reuse the custom code across the portal? For example, on a few pages.**
2 - Not for everyone but if we can make short code to reuse it could be nice

###     Do you need to reuse the media files from the portal in the custom HTML code?
3 - Yes for platforms other than youtube 

### Do you need to reuse styling from the styling guide in the custom HTML code?
4- Yes in several instances 
### 
6 - 10 Not for the moment 





    Do you need to reuse styling from the portal's styling guide in the custom HTML code?
    Do you need to reuse CSS styling across several instances of custom HTML code?
    Do you need client-server validation? For example, server validation if an entity submitted through a custom HTML form already exists.
    Do you need user authentication? For example, if an external service can be reached only by a user logged into the portal.
    Do you need authorization? For example, if the external service can be reached only by a logged-in user with a given claim.
    Do you need another authentication to secure the communication with the server? For example, a non-user-specific token.
    Do you need to authenticate users inside the custom HTML code with authentication other than OpenID Connect? For example, username and password.


Benjamin

**Comment by sbenji77** [comment]
Hi @mikebudzynski 

I can see that you have made progress in the project to implement the functionality. Do you have a visual of the deployment for us users please?  

We would like to be able to integrate a Calendly calendar for our users to make appointments with us. This is easily done with an Iframe but as not possible at the moment. 

Benjamin from Cdiscount

**Comment by mikebudzynski** [comment]
@sbenji77, we're working on a new widget that will allow you to inject custom HTML code in an iframe. Here's a draft version of the widget, we're still making improvements:

![image](https://user-images.githubusercontent.com/40186513/143139967-7f6e3d90-081f-489a-8aaa-d17ac09b2044.png)

**Comment by JMach1** [comment]
New widget was implemented and is ready to use. You can learn more about it [here](https://docs.microsoft.com/en-us/azure/api-management/developer-portal-faq#how-do-i-add-custom-html-to-my-developer-portal).
