### ISSUE TITLE
generatedSample is not always present when loading the API details page. 

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#1043]
This is a random problem about 20% of the time. We noticed that they JSON sample block can be missing from the API details page, after capturing the network traffic to the APIM rest APIs, we saw the generatedSample is not always present in the response. 

![image](https://user-images.githubusercontent.com/65634611/99614804-19a2c980-29cf-11eb-8241-b4743ab42964.png)

## Bug description

The JSON sample block is missing

![image](https://user-images.githubusercontent.com/65634611/99615120-b36a7680-29cf-11eb-9495-70888e14d2cc.png)

## Reproduction steps

1. Go to and API detail view
2. Review the JSON Sample section 
3. Repeat hitting refresh (F5) on the page
4. Occasionally the sample is missing 

## Expected behavior
This is what we see about 80% of the time
![image](https://user-images.githubusercontent.com/65634611/99614993-83bb6e80-29cf-11eb-9cc5-1533c450bbb1.png)

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.4.3

## Environment

 - Operating system: Windows 10
 - Browser: Edge Chromium

**Comment by azaslonov** [comment]
Hi @VWACBrick, `generateSample` property is being generated during the import of API (e.g. Swagger), and only when `sample` property is missing.

**Comment by VWACBrick** [comment]
@azaslonov let me add some more details

- The swagger was loaded weeks ago
- Bring up the same API operation
- Hit F5 on the browser multiple times
- Sometimes you see the sample, and some times you don't. 

I would expect to either see the generatedSample prop there 100% of the time or not at all. Seeing it appear randomly without any settings changes or swagger loads in the admin portal in between

We are only deployed to one region and have limited access to one Tenant. 

Thank you

**Comment by mikebudzynski** [comment]
@VWACBrick We closed the issue by accident; we will investigate the problem. Do you know if the response of HTTP call always includes samples in the payload?

**Comment by VWACBrick** [comment]
@mikebudzynski, when we ran tests using Postman in a loop, we could see anywhere between 40%-60% of the time the generated sample was missing from the response. 

We opened an Azure SR ticket (2011190010002558) with a network trace using the Microsoft Try It tool on the API. 
[https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apioperation/get](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apioperation/get)

**Comment by azaslonov** [comment]
This issue has been fixed in the backend and deployed.
