### ISSUE TITLE
User unable to sign-up or sign-in on Firefox

### ISSUE THREAD

**Issue by hansukyang** [Azure/api-management-developer-portal#1046]
## Bug description

User unable to sign-up or sign-in. It seems like this is limited to Firefox as I'm able to test that this behaviour doesn't occur in Chrome. In terms of signing in, after pressing the 'Sign-in' button, the page reverts to home page and the top drop down menu briefly flashes 'Profile' as if successfully logged in but immediately reverts back to the page for unlogged in user, without displaying any error. When signing up, the page stays on the same sign-up page with a new CAPTCHA displayed.

## Reproduction steps

1. Sign-up via https://oikolab.com (on Firefox)

## Expected behavior

Able to sign-up or sign-in. 

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Firefox

**Comment by mikebudzynski** [comment]
@hansukyang Sign in on Firefox is working for us. Can you:

1. Provide the browser version
1. Check for errors in the developer tools (F12) - console and network
1. Copy HAR files for failed requests?

**Comment by hansukyang** [comment]
Thanks for the prompt response. I've added the HAR files for the failed request. The Firefox browser version is 83 (64-bit) and the console and network part of browser are also attached. This one is copied from Ubuntu OS (18.04) although I get sign-in error is seen in both Windows 10 and Ubuntu OS.

![image](https://user-images.githubusercontent.com/11863789/100033084-643f9e00-2e34-11eb-9ef9-4b8ca3dae47b.png)

![image](https://user-images.githubusercontent.com/11863789/100033004-378b8680-2e34-11eb-8902-8c2dccfa9e95.png)

[oikolab.com_Archive [20-11-24 09-02-04].zip](https://github.com/Azure/api-management-developer-portal/files/5586716/oikolab.com_Archive.20-11-24.09-02-04.zip)

**Comment by azaslonov** [comment]
This issue has been fixed in the managed version in one of the previous releases.
