### ISSUE TITLE
API details widget: Add subscription key to the request header by default - if subscription is required

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1047]
## Background information

Most of our APIs require a subscription of the associated API product. When sending a request for an API with required subscription, the subscription key as well as an application or user access token have to be added to the header of our API s for authorization purposes.

## Bug description

In the new DevPortal, on the top of the Try it panel, there is a section called Authorization that includes the subscription key for the associated API product. 

![NewDevPortal_TryItPanel_AuthorizationSection](https://user-images.githubusercontent.com/58981351/99967338-fe9dd400-2d97-11eb-8d3d-a27ee9355774.PNG)

Here my observations on this subscription key in the new portal:
- Isn´t it very confusing for the DevPortal user that the section with the subscription key form field on the Try it panel is called authorization when we have an additional authorization entry in the Request header required for passing user or application access tokens?
- Currently, in the value input field for the Subscription field on the Try it panel, the term "Subscription key" is written. It looks like that you would need to enter the subscription key manually. 
- This subscription form field is always visible, irrespective of the logged in user has actually subscribed to the associated API product or not. Shouldn't it be only visible if subscription is required?
- For requests send w/o the DevPortal, the subscription key has to be additionally passed through the request header. But this information is missing in the widget on the API details page. Shouldn´t the subscription key be automatically added to the request header section of the widget for the API details page when the associated API product requires subscription?
- If you add in the Azure APIM portal, the subscription key manually to the request header, the subscription key is correctly displayed on the widget of the API details page. BUT it is displayed twice on the Try it panel. Once, it is displayed on top in the Authorization section and a second time it is displayed as an entry of the request headers.
Not sure if the second form entry for the subscription key would be automatically filled out by the Try it panel in this case.

![NewDevPortal_ApiDetailsPageAndTryItPanel_HeaderSection - Kopie](https://user-images.githubusercontent.com/58981351/99968197-22ade500-2d99-11eb-9bb1-f9ca0bbcacac.PNG)

Isn´t the current behavior very weird?

I looked up, how the subscription key was implemented in the legacy portal and found that it hasn´t been automatically displayed if you haven´t added it manually via the request header. So it appeared only one time in the Try it section.

![LegacyPortal_TryItPanel_inHeaderSection](https://user-images.githubusercontent.com/58981351/99968484-78828d00-2d99-11eb-8446-d4bcfe5b449c.PNG)

## Expected behavior

- Remove the current Authorization section with the Subscription key form field on the Try it panel by default.
- Automatically add the subscription key to the request header as the first entry in the widget with the **API details page** AND on the Try it panel - if subscription is required for the associated API product.
- Ensure on the Try it panel, that the value for the Subscription key field is automatically entered for test purpose and indicate this behavior by displaying asterisks characters in the input form field.
- Also indicate on the Try it panel if the logged in user hasn´t subscribed yet to the associated API product. In this case, link the associated API products that require subscription in the Try it panel next to the Subscription key form field to easily jump to the API product details page to do the subscription.
- If subscription is required, in the widget for the **API details page**, in the request header section, add a standard description phrase for the required subscription key like the following: "For getting a valid subscription key for the associated API product, see Your profile page." and enable a link to the profile page.

If the currently logged-in user has subscribed to the API product, the current look and behavior of the **Try-it panel** would be ok.

![TryItPanel_SubscriptionKeyIfSubscribed](https://user-images.githubusercontent.com/58981351/100197002-fe1d4e80-2ef9-11eb-895b-4162fb5f182f.PNG)

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Chrome (latest version)

**Comment by mikebudzynski** [comment]
@AnRei123 Thanks for bringing this up.

Note that the subscription key dropdown should include keys to select if a user is subscribed to a Product, which contains the API.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
