### ISSUE TITLE
Unclear step for setting up the self hosted portal

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#1049]
## Bug description
Step 2 in the instructions for setting up the self hosted has become unclear. When I set it up last spring I had no problems but now I have trouble understanding some parts.

First, for the file ./src/config.design.json it says in step 2.1:

> Replace <service-name> in "managementApiUrl": "https://<service-name>.management.azure-api.net/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/<service-name>" with the name of your API Management instance. For example: https://contoso-api.management.azure-api.net/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/contoso-api.

but that line in the original file looks like:
"managementApiUrl": "https://<service-name>.management.azure-api.net",

Should it be "https://contoso-api.management.azure-api.net" or "https://contoso-api.management.azure-api.net/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/contoso-api"? 

Also, I assume if you are using a custom domain you should replace contoso-api.management.azure-api.net with your custom domain. Related to that, if it is the long version that should be used is it still the instance name that should be used as the last word?

Second, in step 2.3 it says:
> Replace \<service-name> in "backendUrl": "https://\<service-name>.management.azure-api.net" with the name of your API Management instance. For example: https://contoso-api.management.azure-api.net.

In the original file that line looks like: 
 "backendUrl": "https://\<service-name>.developer.azure-api.net",

Should it be  "https://\<service-name>.management.azure-api.net" or  "https://\<service-name>.developer.azure-api.net"? Also, if you are using custom domains, does that matter?

## Expected behavior

I expected the documentation to state what to put in the config files even if I am using custom domains.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release `2.5.4`, commit 468e9f7e877ee0deab1dffe45ba6b1d04ff39d7e

**Comment by mikebudzynski** [comment]
1. Both short and long links you mentioned will work. We recommend using the longer form.
2. Yes, if you have a custom domain, you should use it instead of the default domain provided by APIM. You should be able to not specify the service instance name (for example, try "contoso" or "x" instead).
3. The backend URL should point to the `.developer` address - this is portal's backend, not the management endpoint. If you configure a custom domain for the developer portal, you should use it instead of the default `.developer` URL provided by APIM.

We will work on making the instructions clearer.

**Comment by ErikMogensen** [comment]
Thank you Mike,

A third issue, for the file File ./src/config.runtime.json in the step 2 it says:
> 2. Replace <service-name> in "backendUrl": "https://\<service-name>.developer.azure-api.net" with the name of your API Management instance.  

That should be:
Replace <service-name> in "backendUrl": "https://\<service-name>.developer.azure-api.net" with the name of your **developer portal's backend**.

then?

**Comment by mikebudzynski** [comment]
It should say:
> Replace `<service name>` in "backendUrl": "https://<service-name>.developer.azure-api.net" with the name of your API Management instance. If you have a custom domain configured for the developer portal, use it instead.

**Comment by ErikMogensen** [comment]
Yes of course. I mixed up. Thanks!
