### ISSUE TITLE
Confusing API dropdowns styling

### ISSUE THREAD

**Issue by LucyWengCSS** [Azure/api-management-developer-portal#105]
**Describe the bug**
In the page for OpenAPI specification, the contents do not display correctly, and the headings of the definitions are not readable. There are numerous headings and sections which should not be displayed in the customer's opinion. 

**Expected behavior**
Could you please help to modify the layout of the page and change the definition headings to be more readable?

Thank you very much.
**Screenshots**
![image](https://user-images.githubusercontent.com/48007485/61072441-e3058800-a445-11e9-85db-39e295df344b.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome

**Comment by mikebudzynski** [comment]
Thanks @LucyWengCSS for opening this Issue. From what I understand the problem is with how dropdowns are displayed and that they look misformatted.

> There are numerous headings and sections which should not be displayed in the customer's opinion.

Could you please elaborate on this? Which sections shouldn't be displayed?

**Comment by LucyWengCSS** [comment]
Hi @mikebudzynski, thanks so much for your kind reply. The screenshots below show the headings which are not easy to understand. May I ask if we have any plan or workarounds to change them?

![image](https://user-images.githubusercontent.com/48007485/61844092-d286f000-aed0-11e9-8701-d94333f7cebc.png)
![image](https://user-images.githubusercontent.com/48007485/61844107-dadf2b00-aed0-11e9-8658-4c6c86f3a0cb.png)

**Comment by mikebudzynski** [comment]
@LucyWengCSS 

1. Name of a Schema Objects (definition) is defined through your OpenAPI specification file. If you want to change it, you need to modify the information in your API Management instance. The developer portal only displays the name that you specified.
2. We will improve the dropdowns, thanks for pointing that out.

**Comment by mikebudzynski** [comment]
Merge to https://github.com/Azure/api-management-developer-portal/issues/186
