### ISSUE TITLE
Lack of "Secure" Flag on HTTP Session Cookie

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#1051]
Description:
The web application sets user session cookies over HTTPS but fails to set the Secure cookie flag on these authentication tokens.
This kind of attack is fairly complex, but many steps can be automated with off-the-shelf tools. Note that the server does not need to have port 80 open for this attack to function. 

Recommendations Remediation: 
Ensure that the application, web server, and/or front-end load balancer set the secure flag on all cookies delivered over HTTPS.
The application's Set-Cookie headers for session cookies should read something like:
Set-Cookie: SESSION=...; httpOnly; secure
Web applications implemented in .NET can often be secured by setting the appropriate cookie flags in the web.config file, as shown:
<httpCookies requireSSL="true" httpOnlyCookies="true"/>

Background Information:
By default, web browsers will send HTTP cookies over both HTTP and HTTPS, no matter which protocol was used to initially set them. Websites can optionally specify that particular cookies are to be sent only over secure channels by setting the cookie with the "secure" flag. If a site fails to set this flag, an attacker could force a browser to leak a session cookie over an insecure channel. One example would be through the following steps:
1) An attacker gains access to view and modifies unencrypted traffic between a user and the application.
2) A user logs into the vulnerable HTTPS web application at https://vulnerable.site/ and is assigned a session cookie.
3) The user's browser, at some point during the login session, makes a request to any non-HTTPS web page.(This could include webmail sites, search engines, or even background requests made automatically by the web browser for software updates.)
4) Attacker replaces the HTTP response with a simple HTTP redirect. The redirect points to: http://vulnerable.site/
5) The user's browser, upon generating a new request for this URL, automatically includes the user's session cookie in the HTTP headers.
6) The attacker observes the session cookie over the unencrypted link and subsequently hijacks the user's application login session.

**Comment by azaslonov** [comment]
Makes sense. We'll fix that.

**Comment by mikebudzynski** [comment]
We already implemented and fix and plan to deploy it as part of the general API Management service release. You can monitor GitHub for new releases: https://aka.ms/apim/releases

**Comment by azaslonov** [comment]
Most of the public services were upgraded. The issue should be gone.
