### ISSUE TITLE
Self-Registration Functionality Allows Account Enumeration

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#1052]
Description:
When testing for valid login, error codes reveal the existence of valid usernames.

Recommendations Remediation: 
Ensure that the application returns consistent generic error messages in response to the invalid account name, password, or other user credentials entered during the login process. 

Background:
Often, web applications reveal a username's existence on the system, either as a consequence of misconfiguration or as a design decision. For example, when incorrect credentials are submitted, a message is sometimes returned stating that either the username is present on the system or the provided password is wrong. The information obtained can be used by an attacker to gain a list of users on the system. This information can be used to attack the web application, for example, through a brute-force or password-guessing attack. Credential stuffing using publicly available lists of usernames would also make this attack more feasible. 

During the sign-up process, if an email address that is already associated with an account is submitted, the server reveals the existence of that user account. 

![image](https://user-images.githubusercontent.com/66616951/100079453-ae437680-2e6a-11eb-8e34-b5939a98297c.png)

**Comment by azaslonov** [comment]
Hi @dhandapanitrimble, thanks for the feedback, but a generic message like "Invalid account name" would lead to questions like "why is it invalid?", and there's no good answer for that.

Just having a user email doesn't mean it is easily hacked. Also, if you'd like to protect your users better, you can switch to, i.e. AAD B2C and allow them to set up 2-factor authentication.

Besides that, it looks to be common practice:
![image](https://user-images.githubusercontent.com/2320302/100151250-cbba1580-2e55-11eb-869f-6d59b08ee8ff.png)
