### ISSUE TITLE
Backing-up Portal content throws error while downloading blobs

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1053]
## Bug description

When creating a backup of the DevPortal an Error message is displayed, saying that it was "Unable to complete export" and that there is no such file or directory open. It states the correct path but with a wrong appendix. (More info in the Screenshots) This is triggered in the capture.js file. But the problem occurs in utils.js at the "downloadBlobs" function.

This Issue leads to missing images in the media folder. Every image up to "MediaLibrary/$$$ORCHARD$$$.$$$" will be downloaded but then it fails and the script ends.

I am using the newest files (Today 5 days old for both capture.js and utils.js)
When using the same scripts for an older backup-Version on a different Portal it works fine (also added to the screenshots).

If needed my colleague or I can provide the Instance names.

## Reproduction steps

I'm still working on it. If I can reproduce it I will edit this Issue.

## Is your portal managed or self-hosted?

Managed

## Additional context
The logs displayed are the extension and the blob name

Instance where download is not working correctly:
![downloadBlobsIssue01](https://user-images.githubusercontent.com/58420097/100083772-29486500-2e4a-11eb-9f74-5ecc33097b19.png)
Instance where download works fine (with older backup-Version):
![downloadBlobsIssue02](https://user-images.githubusercontent.com/58420097/100083777-2a799200-2e4a-11eb-9b6c-2497e218f7e1.png)

**Comment by azaslonov** [comment]
Hi @ZarTrox, looks like you have the legacy portal artifacts. We'll fix the script to take this into account.

**Comment by ZarTrox** [comment]
Hi @azaslonov , thanks for the answer. When do you think will this be fixed? Is it possible to be done until Tuesday eob.?

**Comment by ZarTrox** [comment]
Hi, me again, is there an update on this topic?

**Comment by azaslonov** [comment]
Yes, merged the fix.

**Comment by ZarTrox** [comment]
Today I tried to test the new utils.js file. The download worked perfectly fine. Thank you. But now when I try to upload the data.json and the media files it throws the Error

> Error: Unable to upload media files. options.blobHTTPHeaders.blobContentType with value "false" must be of type string. at uploadBlobs (*PathToScript*\utils.js:168:15)

The script creates a folder(MediaLibrary) with the mentioned §§§Orchard§§§.§§§.false
---
![image](https://user-images.githubusercontent.com/58420097/100726485-4985a000-33c5-11eb-8bd8-af08c8ba902f.png)
---
![image](https://user-images.githubusercontent.com/58420097/100726508-50acae00-33c5-11eb-8dc7-7d9a6314e01e.png)
---
Since only the download function has been changed maybe the upload needs to be adjusted as well.
Thanks in advance for your time.

**Comment by azaslonov** [comment]
Sure, I'll take a look.

**Comment by AnRei123** [comment]
I am still not able to upload the dat to the DevPortals. Is there already an updated utils.js available that fixes the issue? Or any other fix or workaround. **On Tuesday I need to deploy the latest portal contents** to the production environments. Could you provide a fix by Monday eob?

**Comment by azaslonov** [comment]
Sorry for the troubles folks, fixed in #1076. Just pull the latest changes when it's merged.

**Comment by AnRei123** [comment]
Thank you very much. With the following update it worked. Now, download and upload are both functioning.
https://github.com/Azure/api-management-developer-portal/blob/master/scripts.v2/utils.js
