### ISSUE TITLE
[Question] Way to remove permalink [managed]

### ISSUE THREAD

**Issue by SteppingRazor** [Azure/api-management-developer-portal#1055]
I am using managed version of new developer portal. I was wondering if there is a way to remove or change defined permalinks.
For example `/signup`. I can remove all the button that will redirect user to signup page but if the user type the route in the browser https://developer-portal-url/signup he will be redirected to the signup page.

Is there a way to remove this route link or better yet redirect user to another page?

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @SteppingRazor, you can remove it using REST API. The resource you need (in the default setup) is 
`DELETE /contentTypes/page/contentItems/0145411a-2c82-325a-4390-76cff184530b`
