### ISSUE TITLE
API details widget: Description much too close to API header items - most texts are too compact

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1056]
## Bug description

Currently the texts and items are displayed much too compact in the API details widget. Especially, the distance (1) between the API header section and the first sentence of the API description is much too compact. The distance (2) between the header and the major description in the Operation details widget is ok. 

![CurrentState](https://user-images.githubusercontent.com/58981351/100111149-16478c00-2e6e-11eb-998f-5d5486b6b64f.PNG)

Especially, if you have several paragraphs for the API description it looks so bad and unprofessional that people complaint.

![IssueWithLongerDescriptionsAndLists](https://user-images.githubusercontent.com/58981351/100111896-e947a900-2e6e-11eb-9603-2422cfe130de.PNG)

And if you try to do a workaround by adding a html line break tag in front of the description, you have solved the issue in the API details widget, but you messed up the visualization in the List of API widget.

![RequestedState](https://user-images.githubusercontent.com/58981351/100112054-185e1a80-2e6f-11eb-9bb2-62c733e8c998.PNG)

![WorkAroundNotPossible](https://user-images.githubusercontent.com/58981351/100111487-6f172480-2e6e-11eb-86f1-4271a03c016d.PNG)

## Expected behavior

Please extend the distance between the header section and the description in the API details widget and keep the line distances in the list of APIs widget as they are.

![RequestedState](https://user-images.githubusercontent.com/58981351/100112312-62470080-2e6f-11eb-8d21-3140fcb11020.PNG)

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Chrome (latest)

**Comment by azaslonov** [comment]
Technically this can be solved through global text styles, but I agree there could be more widget customization options for this case. We'll see what we can do.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
