### ISSUE TITLE
The Generate script in Scripts.V2 does not work when setting up the self hosted portal for the first time 

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#1057]
## Bug description

Looks like the generate script in Scripts.V2 does not work when trying to set up the self hosted portal for the first time. 

## Reproduction steps

1. Follow the instructions in the wiki for setting up the portal.
2. In the last part of step 3 you enter generate.bat in the Scripts.V2 folder. Then the script throws an error.
3. The error seems to be that it cannot find the data.json file. 

I managed to get it working by adding the directory dist/snapshot/media to the project root folder and then copy the data.json file to the snapshot directory.

## Expected behavior

Expected the generate script to finish without error.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release `2.5.4`, commit 468e9f7e877ee0deab1dffe45ba6b1d04ff39d7e

**Comment by azaslonov** [comment]
Hi Erik, thanks for the feedback.
I think that Step 3 is not required anymore, because on Step 4 (npm start) the portal itself does the content provisioning.
@mikebudzynski thoughts?

**Comment by mikebudzynski** [comment]
I removed the content generation step from the self-hosted setup wiki. Let us know if it still doesn't work @ErikMogensen
