### ISSUE TITLE
Setup login to Developer Portal with IdentityServer

### ISSUE THREAD

**Issue by AjaySewradj** [Azure/api-management-developer-portal#1060]
I want to be able to connect my existing IdentityServer to the Developer Portal.
A click on the login button should redirect the user to the login screen from the IdentityServer.

I want to be able to setup a Open ID Connect Identity Provider, but I can't figure out how to do that for the Developer Portal.
This is pretty straightforward for any webapp.

Things I've already tried:
- Setup an Azure AD B2C with the IdentityServer as an upstream provider => Works but is not ideal, we already have a perfectly fine IdentityServer, with another upstream AD
- Delegation => Also works but is another indirect way of logging in, which is also not ideal

**Comment by azaslonov** [comment]
Hi Ajay, in general, I agree with you. However, AAD B2C allows you to connect your own Identity Server: https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-generic-openid-connect

Hope that helps.
