### ISSUE TITLE
[Question] What is CodeVersion and Version

### ISSUE THREAD

**Issue by SteppingRazor** [Azure/api-management-developer-portal#1061]
Hello, by going to `https://developer-portal-url/internal-status-0123456789abcdef` I can get some information about version running on managed developer portal. Something like this:

`{"Status":200,"PortalVersion":"202011251132","CodeVersion":"20201109183502","Version":"0.16.1100.0"}`

I know every time I publish developer portal, `PortalVersion` gets updated. But what are the other two fields (`CodeVersion` and `Version`)? What do they mean and how can I connect this version with the releases you guys put [here](https://github.com/Azure/api-management-developer-portal/releases). Is it the same thing?

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @SteppingRazor, the `CodeVersion` is basically a version of the designer and publisher. When the code version is higher then your published version, then you may want to re-publish to pick up changes/fixes, if you expect any. However, this process will become automatic soon.

The correlation between releases and this version is not a direct one, but we plan to include that release version into the status as well at some point.

Hope that helps.
