### ISSUE TITLE
Duplicate content sent for Office 365 Management API

### ISSUE THREAD

**Issue by Victor-Ness** [Azure/api-management-developer-portal#1063]
## Bug description

We use the Office 365 Management API to receive webhook notifications for new Audit content. Whenever new content is available, we receive a notification with a link to the content so we can go and download it. On November 21 (UTC), we received a file containing events for November 16. The file was timestamped for 11/21 
`20201121063048785077405$20201121063218791111944$audit_azureactivedirectory$Audit_AzureActiveDirectory$na0030$na0030`
but had events from 5 days prior. Additionally, these events had already been received by us back on the 16th. Is there a known issue causing old/duplicate event content to be sent in notifications?

## Reproduction steps

Problem has no reoccurred

## Expected behavior

Event content should not be sent more than once, 5 days after the event occurred

## Is your portal managed or self-hosted?

Managed / Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

Office 365 Management API

## Additional context

Add any other context about the problem here, including screenshots.
Sample event contained in the file for 11/21
```
{
    "CreationTime": "2020-11-16T13:52:10",
    "Id": "22222222-3333-4444-5555-666666666666",
    "Operation": "UserLoggedIn",
    "OrganizationId": "11111111-2222-3333-4444-555555555555",
    "RecordType": 15,
    "ResultStatus": "Succeeded",
    "UserKey": "redacted@redacted.com",
    "UserType": 0,
    "Version": 1,
    "Workload": "AzureActiveDirectory",
    "ClientIP": "11.222.333.444",
    "ObjectId": "00000003-0000-0ff1-ce00-000000000000",
    "UserId": "redacted@redacted.com",
    "AzureActiveDirectoryEventType": 1,
    "ExtendedProperties": [
      {
        "Name": "UserAgent",
        "Value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
      },
      {
        "Name": "RequestType",
        "Value": "OAuth2:Authorize"
      },
      {
        "Name": "ResultStatusDetail",
        "Value": "Redirect"
      },
      {
        "Name": "KeepMeSignedIn",
        "Value": "false"
      }
    ],
    "ModifiedProperties": [],
    "Actor": [
      {
        "ID": "11111111-2222-3333-4444-555555555555",
        "Type": 0
      },
      {
        "ID": "redacted@redacted.com",
        "Type": 5
      }
    ],
    "ActorContextId": "24f85f24-158a-44b9-bb80-8e516a8f42e4",
    "ActorIpAddress": "11.222.333.444",
    "InterSystemsId": "df8a19a2-e814-48f2-afc1-78e663d1eea3",
    "IntraSystemId": "7e615ffe-54a0-45ed-952f-ca22040c5300",
    "SupportTicketId": "",
    "Target": [
      {
        "ID": "00000003-0000-0ff1-ce00-000000000000",
        "Type": 0
      }
    ],
    "TargetContextId": "24f85f24-158a-44b9-bb80-8e516a8f42e4",
    "ApplicationId": "08e18876-6177-487e-b8b5-cf950c1e598c"
  }
```

**Comment by azaslonov** [comment]
Hi Victor, looks like it's the wrong repository for this question. This project is specifically for Azure API Management Developer portal. I'm sure MS Support will be able to help you out.
