### ISSUE TITLE
(wiki) Issue related to Self-Hosted Portal

### ISSUE THREAD

**Issue by simedbn** [Azure/api-management-developer-portal#1064]
**Description**

I want to use the Self-Hosted version of the portal but i still not understand why i need to do the Step 3 :

https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-3-provision-the-default-template

i undestand by self-hosted version  that it's a seprated version deployed to an isolated azure storage (static website) but why some Portal Data need to be stored in the APIM as described here : 

![image](https://user-images.githubusercontent.com/15849678/100654068-96c42c00-3349-11eb-9edb-6c33080cf1f3.png)

Why the Portal Data is not part of the Storage account ?

Thank you in advance

**Comment by azaslonov** [comment]
Hi @simedbn, the portal data consists of 2 things: Media files (images, fonts, etc.) and the Content (pages, layouts, etc.). Media is being stored in Azure Blob Storage and Content gets stored in Azure SQL DB.

Step 3 provisions the default template (media and content) which you may modify, if needed. (also in the future the will more templates, so you'll be able to pick which one you'd like to start with). However, when you start the designer locally for the first time, the provisioning executes automatically.

Hope that helps.
