### ISSUE TITLE
(OAS3) Developer Portal doesn’t show all nested properties of the schema with reference

### ISSUE THREAD

**Issue by konsta2106** [Azure/api-management-developer-portal#1074]
## Bug description

Developer Portal is not willing to display all properties of the model schema. Looks like it happens when schema has nested object with nested property that uses reference.

## Reproduction steps

1. Go to 'xxx.developer.azure-api.net'
2. Navigate to desired API and desired endpoint
3. Scroll down to 'definitions of required model/schema'
How spec looks in Stoplight GUI and from yaml point of view:
![Screenshot 2020-12-03 at 12 50 23](https://user-images.githubusercontent.com/54150208/101001110-5e9a3480-3567-11eb-9d13-009c8fc7f149.png)
![Screenshot 2020-12-03 at 12 50 58](https://user-images.githubusercontent.com/54150208/101001179-75408b80-3567-11eb-92f9-433ca3e0e0d7.png)

And in Developer portal i can only see visibility.visibleTo, visibility.type is not visible

![Screenshot 2020-12-03 at 12 51 13](https://user-images.githubusercontent.com/54150208/101001259-90ab9680-3567-11eb-8df5-e62b9454c25b.png)

## Expected behavior 

By all means i would be able to see all properties needed by the schema

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

--

## API Management service name

Contoso

## Environment

 - Operating system: MacOS
 - Browser: Chrome

**Comment by jsorohova** [comment]
Hello @konsta2106 , can you please check if this is still reproducible? We fixed an array displaying but I would like to double-check this issue with you. Thank you.

**Comment by konsta2106** [comment]
Hi Elena.

Yes, I can confirm that this is fixed. Also, I’m very excited to see when this PR (https://github.com/Azure/api-management-developer-portal/pull/1601) will be closed.

From: Elena Shorohova ***@***.***>
Date: Thursday, 20. January 2022 at 19.16
To: Azure/api-management-developer-portal ***@***.***>
Cc: Konstantin Komovits ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/api-management-developer-portal] (OAS3) Developer Portal doesn’t show all nested properties of the schema with reference (#1074)

Hello @konsta2106<https://github.com/konsta2106> , can you please check if this is still reproducible? We fixed an array displaying but I would like to double-check this issue with you. Thank you.

**Comment by jsorohova** [comment]
Thank you. I will close this issue now.

Regarding the PR, it is planned to be out next release.
