### ISSUE TITLE
How to handle the caching so that any changes we do and publishing we can see the recent changes, without manual forceful refresh the browser cache

### ISSUE THREAD

**Issue by venkateshnamb** [Azure/api-management-developer-portal#1081]
**How to handle the caching so that any changes we do and publishing we can see the recent changes, without manual forceful refresh the browser cache**

## Bug description
How to handle the caching so that any changes we do and publishing we can see the recent changes, without manual forceful refresh the browser

After we edit and publish the changes to storage account, until unless if we forcefully(CTRL+F5) refresh the browser, the new changes are not displaying

Is there is any way to handle the cache with out hard refresh

## Expected behavior

With out hard refresh we are supposed to see the changes deployed in the storage account recently

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[release `2.4.3`]

## Environment
 - Chrome, Edge

**Comment by azaslonov** [comment]
Hi @venkateshnamb, right, there are some caching issues. We'll fix this.

**Comment by azaslonov** [comment]
Please use #939 for tracking. Closing this one.
