### ISSUE TITLE
Intermittent Signin Knockout Unable to Process Binding JS Exception

### ISSUE THREAD

**Issue by MTGCSharpGuy** [Azure/api-management-developer-portal#1084]
Occasionally, when loading the Signin or Signup page, I get the following exception via the Dev Tools Console:

`theme.js:formatted:5270 Uncaught Error: Unable to process binding "component: function(){return a}"
Message: Component 'validation-summary': Unknown viewModel value: [object Object]
    at theme.js:formatted:5270
    at c (theme.js:formatted:5338)
    at Object.loadViewModel (theme.js:formatted:5339)
    at Object.e [as oc] (theme.js:formatted:5186)
    at theme.js:formatted:5238
    at f (theme.js:formatted:5266)
    at b (theme.js:formatted:5237)
    at theme.js:formatted:5298
    at f (theme.js:formatted:5266)
    at Object.loadComponent (theme.js:formatted:5297)`

Latest commit for the user-signin.ts file is acc7ec4659e982a61fde6e71bd55622b12e9fc85.

Below is a screenshot. Any help is greatly appreciated!

![MSPBSigningKnockoutBug](https://user-images.githubusercontent.com/18424434/101815006-c1458000-3ad3-11eb-835e-4462f8f504f7.png)

**Comment by azaslonov** [comment]
Hi @MTGCSharpGuy, is this managed version or you self-host it? If managed can you please send your service name to apimportalfeedback@microsoft.com?

I'll try to repro meanwhile.

**Comment by MTGCSharpGuy** [comment]
> 
> 
> Hi @MTGCSharpGuy, is this managed version or you self-host it? If managed can you please send your service name to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com)?
> 
> I'll try to repro meanwhile.

Hi, It's self-hosted. it doesn't happen all the time... takes some time to get it to reproduce. Thanks.

**Comment by MTGCSharpGuy** [comment]
@azaslonov , Hi, Any progress, just checking in, thanks.

**Comment by azaslonov** [comment]
Hi, no I was never able to repro. Since its self hosted,, can you please build the project in development mode and publish it. This way we'll see the full stack at least, and you'll be able to put a breakpoint.

**Comment by MTGCSharpGuy** [comment]
> 
> 
> Hi, no I was never able to repro. Since its self hosted,, can you please build the project in development mode and publish it. This way we'll see the full stack at least, and you'll be able to put a breakpoint.

OK, will do, thanks...

**Comment by azaslonov** [comment]
Closing since agreed to follow up offline. If you haven't received any communications from us, please send us an email one more time in case it got lost.
