### ISSUE TITLE
Multiple APIM connections

### ISSUE THREAD

**Issue by divya21098** [Azure/api-management-developer-portal#1087]
Is it possible to connect self hosted developer portal with multiple api management instances. 
If this is possible then how will it be done ? Can we have multiple management rest apis cofigured with developer portal?

**Comment by azaslonov** [comment]
Hi @divya21098, we don't support that currently, but you may want to keep an eye on [this project](https://github.com/microsoft/API-Catalog), which is also a developer portal but detached from APIM services.
