### ISSUE TITLE
try It section on Azure Hosted Portal is just showing the spinner and has a Theme.js Error

### ISSUE THREAD

**Issue by EwenStewartAtTally** [Azure/api-management-developer-portal#1089]
## Bug description
   

When using the TRY It Feature - the portal is just showing the 3 dots for the loading section 
 
![image](https://user-images.githubusercontent.com/45586744/102004322-b86add80-3d63-11eb-93e3-a9af5b4e7d39.png)

In the debug  tools I can see 
Uncaught (in promise) TypeError: Cannot read property 'substr' of undefined
    at theme.js:formatted:64051
    at Array.forEach (<anonymous>)
    at theme.js:formatted:64049
    at Array.forEach (<anonymous>)
    at OperationConsole.<anonymous> (theme.js:formatted:64047)
    at Generator.next (<anonymous>)
    at fulfilled (theme.js:formatted:63894)

  ## Reproduction steps

1. Go to 'API detail pge'
2. Click on 'try it '
3.  See 3 dots 
4. See error in  console 

## Expected behavior

Actual try it section  ( was there a few days ago ) 

## Is your portal managed or self-hosted?

Managed  

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name
TallyAPI  

## Environment
 
Australian South East Region

**Comment by azaslonov** [comment]
Please send us your service name to apimportalfeedback@microsoft.com and mention the number of this issue.. We'll take it from there. Thanks.

**Comment by EwenStewartAtTally** [comment]
seems to have fixed itself  - must be some sort of azure deployment issue
