### ISSUE TITLE
Not able to see Publisher Portal on APIM instance

### ISSUE THREAD

**Issue by swetachotalia** [Azure/api-management-developer-portal#1090]
From today, we are not able to see Publisher Portal on APIM instance. Previously it was visible as Legacy on Portal Overview page. Need to know other way to access Legacy Publisher portal till we migrate to new version of portal.

**Comment by azaslonov** [comment]
Hi @swetachotalia,

You can get to legacy portal through the Developer portal section:

![image](https://user-images.githubusercontent.com/2320302/102124594-58287a00-3dfd-11eb-8bc0-49006f0f1ef0.png)

Then get to publisher portal through Manage menu item:

![image](https://user-images.githubusercontent.com/2320302/102124740-81490a80-3dfd-11eb-8feb-6d41be1d5308.png)

Hope that helps/
