### ISSUE TITLE
Operation details panel no longer renders in the portal

### ISSUE THREAD

**Issue by ebowdenqa** [Azure/api-management-developer-portal#1091]
## Bug description

Details for API operations no longer render in the developer portal at developer.aq-fes.com.

## Reproduction steps

1. Open your browser to https://developer.aq-fes.com/api-details#api=aq-products-api&operation=ProductsAPI_GetProductData
2. Observe that the operation details do not render
3. Open browser developer tools
4. Observe that the page is calling https://aq-api.management.azure-api.net/apis/aq-products-api/hostnames?api-version=2020-12-01  This does not appear to be a valid url and results in a javascript exception.

## Expected behavior

Operation details should appear.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

aq-api

## Environment

 - Azure APIM developer portal
 - Affects Chrome, Edge, Firefox
 - Update:  We configure our portal in a dev integration environment (svc aq-api-dev), promote that to QA (svc aq-api-qa) and then to production (aq-api).

**Comment by ebowdenqa** [comment]
I added  anote beneath the Environment section to explain how we promote apim developer portal configuration across environments.  Could this result in an incompatibility of some sort, where the portal configuration, which originated from aq-api-dev, is not compatible with the apim service at aq-api.  This has been working well for ~9 months, but perhaps an incompatibility has been introduced recently (where a developer portal configuration for APIM svc A won't necessarily work for APIM svc B).

**Comment by azaslonov** [comment]
Thanks, investigating...

**Comment by azaslonov** [comment]
Ok, looks like the portal has been published a long time ago 07/31 12:50. Just please re-publish it, the issue should be gone.

On a side note, in one of the next releases, the re-publishing will be happening automatically, when new bits are out, so this won't be a problem anymore.

Closing for now. Please feel free to re-open if re-publishing doesn't help.
