### ISSUE TITLE
Migrate.js in scripts.v2

### ISSUE THREAD

**Issue by divya21098** [Azure/api-management-developer-portal#1092]
after NPM install, navigated to Scripts.v2 and ran the below command

node migrate --sourceEndpoint from.management.azure-api.net --destEndpoint to.management.azure-api.net --publishEndpoint to.developer.azure-api.net --sourceToken "SharedAccessSignature integration&2020..." --destToken "SharedAccessSignature integration&2020..."
![image](https://user-images.githubusercontent.com/27778618/102181449-9478da80-3ed0-11eb-8f25-4ce9ac829552.png)
I am getting TLS unauthorized warning and unable to publish comment on running the script

**Comment by azaslonov** [comment]
Hi @divya21098, 

Probably you don't have access to your source or dest endpoints. Can you please just try to ping them from the same machine?
`ping from.management.azure-api.net`
`ping to.management.azure-api.net`

Meanwhile, we'll improve the error message for this case.

**Comment by divya21098** [comment]
Hey the script shows done but content does not get published even in designer

**Comment by divya21098** [comment]
The content got published for managed portal but in self hosted will content from source bob get uploaded to destination blob ?

**Comment by mikebudzynski** [comment]
Yes, it should get uploaded if you configure the script correctly. Please, open an Azure support request if you need further assistance.
