### ISSUE TITLE
Missing API version in the request URL with version query parameter "version"

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1093]
## Bug description / expected behavior

If you do not configure the "Version query parameter" field, the new DevPortal shows the version info with a slash directly between the URL prefix of the API version and the path name for the operation: /2/<operation path name.

For our APIs, we make use of the key value "Version query parameter" field. This is also reflected in the APIM portal and in the legacy DevPortal. But it is not anymore reflected in the new Developer portal. This is very bad as the API consumer do not immediately see  the version in the path and how the version should be added in the request URL!!!

**APIM Portal view:**

In the "Version query parameter" field, the example is displayed correctly even for our configuration!!!
But the field is only displayed if imported as part of the imported Swagger file. You are not able to edit the value for this field and you are not able to add it throught the GUI if it is missing. 

![APIM-portal_version-query-parameter](https://user-images.githubusercontent.com/58981351/102202271-6ba01780-3ec7-11eb-8458-8ef98d4a15a1.PNG)

**New DevPortal view (published version):**
The version information is completely missing in the request URL on the operation details widget for the current settings!!!

![DevPortal_API-details-page_version-missing](https://user-images.githubusercontent.com/58981351/102202297-7195f880-3ec7-11eb-9833-061441341bc0.PNG)

But the version info should be displayed as shown above in the APIM portal.

**LegacyPortal (editor version):**

In the legacy portal, the version information was properly displayed as configured!! 

![LegacyPortal_API-details_version-displayed](https://user-images.githubusercontent.com/58981351/102202314-765aac80-3ec7-11eb-9d3f-408ee47ad690.PNG)

With the new DevPortal, the version is not displayed anymore with our current settings.
Without the complete request URL, an API consumer cannot correctly use our APIs!!! 

Therefore, please add the version info to the displayed request URL in the new DevPortal as you did for the legacy portal.
Please provide a solution as soon as possible as our API consumers are very confused by this new and wrong behavior!
Many thanks in advance.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: latest

**Comment by azaslonov** [comment]
Hi @AnRei123, thanks, we'll fix this.
