### ISSUE TITLE
Checking Developer portal availability

### ISSUE THREAD

**Issue by maheshkumagali** [Azure/api-management-developer-portal#1095]
We customized the new developer portal (https://github.com/Azure/api-management-developer-portal).
Is there any way to check availability of the new developer portal with any URL? we are planning to have an availability test in app insights and we need to know which URL to hit for knowing the availability.
We need similar way of checking APIN gateways health status using the link: 
https://<APIM URL>/internal-status-0123456789abcdef

When we tried using the same approach for New Developer portal using below link, we are getting a message "This is a health test page" but we are seeing 404 response code.
https://<Dev PortalURL>/internal-status-0123456789abcdef

![image](https://user-images.githubusercontent.com/13291957/102236750-e003a680-3f19-11eb-8b88-32c36eeef811.png)

**Comment by maheshkumagali** [comment]
@azaslonov can you please help on this? Thanks in advance!

**Comment by azaslonov** [comment]
Hi @maheshkumagali, this URL should work actually, like here:
https://alzasloneuap05.developer.azure-api.net/internal-status-0123456789abcdef

So, a few questions:
- is this the new developer portal?
- is this a self-hosted portal?
- do you have any proxy in front of it?
- did you add a page with that specific "/internal-status-0123456789abcdef"?

**Comment by maheshkumagali** [comment]
is this the new developer portal? - _Yes_
is this a self-hosted portal? - _Yes_ 
do you have any proxy in front of it? - _No_
did you add a page with that specific "/internal-status-0123456789abcdef"? - _No Alex. We did not create any specific page with that route._

**Comment by azaslonov** [comment]
Hi @maheshkumagali, please send us your service name to apimportalfeedback@microsoft.com and mention this issue, we'll take it from there. Thanks.
