### ISSUE TITLE
Npm install issue

### ISSUE THREAD

**Issue by divya21098** [Azure/api-management-developer-portal#1096]
Bug description

I cloned the repo and tried to run npm install. I got a tls warning along with node install.js failes

Reproduction steps
![image](https://user-images.githubusercontent.com/27778618/102333603-a8493d00-3fb3-11eb-8ff0-9bac28fe61f8.png)

Expected behavior
I had tried before and it had worked perfectly

Is your portal managed or self-hosted?
Self-hosted

Release tag 
release `2.5.6`

**Comment by azaslonov** [comment]
Hi @divya21098, looks like a temporary download issue.  Just in case, you can remove `node_modules` folder and try again.

**Comment by divya21098** [comment]
I removed node modules by command: rm -rf node_modules package-lock.json .
I installed puppeteer by command: npm i puppeteer and ran npm install again,the error was resolved .
On npm start the code compiles successfully but on local host page is reloading and directs to /signout.

What is causing this? Is there a bug in node modules ?

**Comment by azaslonov** [comment]
Might be a bug, might be an intermittent issue. Happens sometimes.

I'm closing the issue since you've got it resolved. Thanks for the confirmation.
