### ISSUE TITLE
Graphs in Reports page is not working properly - Developer Portal

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#1099]
When we move the cursor in Reports page graphs it used to show the Total/Successful/Failed requests, Bandwith details and response time details based on the time frame.
Currently, this functionality is not working.

## Reproduction steps

1. Login into the Developer portal
2. Check Reports page

Managed portal

![image](https://user-images.githubusercontent.com/66616951/102579185-fc722f80-4121-11eb-8992-fec5426bf0f6.png)

**Comment by mikebudzynski** [comment]
@dhandapanitrimble Thanks for reporting the issue, I was able to reproduce the problem.

**Comment by apreshchandra** [comment]
Hello Mike, is there a timeline on this issue? We have a managed APIM instance and we'd like to show the User of our portal to be able to see Reports.

**Comment by mikebudzynski** [comment]
@apreshchandra Can you confirm that the user you're logged in as in the developer portal has made API calls with a product subscription key in the timeframe you're looking at?

**Comment by apreshchandra** [comment]
thank you for your reply. I can confirm that API calls were made. A few resulted in 200OK, a few in 500.

**Comment by apreshchandra** [comment]
![image](https://user-images.githubusercontent.com/3713329/109293955-86d9bc80-7852-11eb-8c34-ebbc2c23a615.png)

Other data points like API calls, API response times are also blank. Any suggestions are very welcome!
