### ISSUE TITLE
How to self-host developer portal on consumption tier?

### ISSUE THREAD

**Issue by Tieno** [Azure/api-management-developer-portal#110]
The guide on https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-at step 2: Configure talks about 

 "Enable the direct REST API access to your API Management instance. Copy the generated token and place it in the "managementApiAccessToken": "SharedAccessSignature ..." 

Except this doesn't seem to be possible with the consumption tier.  Is there an other way to self host the developer portal with the consumption tier?

**Comment by mikebudzynski** [comment]
No, the developer portal is not supported in the Consumption tier. You can find the full feature comparison at http://aka.ms/apimfeatures

**Comment by sschutten** [comment]
This makes me sad. Azure Functions v2 dropped support for the Swagger/OpenAPI specification page in favor of API Management, so I need to spin up an expensive API Management instance for documenting a few consumption plan Azure Functions. Please review this request.

**Comment by mikebudzynski** [comment]
Functions didn't provide a developer portal either. If you want to export an OpenAPI specification, you can do it through the Azure portal, ARM API, or an SDK (for example, PowerShell). Feature requests can be posted at https://aka.ms/apimwish
