### ISSUE TITLE
Styles: Support different margin-top settings for standard paragraphs (p) and list paragraphs (ul, ol)

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1101]
## Bug description

1) Currently, I can only change the margin-top of the ul tag by changing the margin-top settings for standard text paragraphs on the styles sheet in the editing mode of the Developer Portal. It seems that the values are in synch. But it looks so weird and strange if there is there is so much space between an introduction sentence with a colon and the followed list object. It is hard to see that the list belongs to the previous sentence that often functions like a list title.

p + ul {
  margin-top: 1em;
}

I am not able to find how to configure a different margin-top value for the standard text paragraphs and the lists (ul, ol).

With my current margin-top settings for paragraphs, my lists look like the following.

a) In articles on standard text widgets

>![NormalPage_article_listView](https://user-images.githubusercontent.com/58981351/102912999-69692a80-447e-11eb-9b50-595eb54d6a19.PNG)

b) In the API details or operation details widget.

>![ApiDetailsWidget_description_listView](https://user-images.githubusercontent.com/58981351/102913022-7423bf80-447e-11eb-8cfb-dbeb8260e717.PNG)

2) It is also very weird that the margin value between the single list items seem to be different for the standard text widget and the details view.

## Expected behavior

1) Allow different margin-top style settings for normal paragraphs and for lists (ol, ul) such as the following.

p {
  margin-top: 1em;
}

ul + ol {
  margin-top: -0,5em;
}

I need to be able to configure the distance between an introduction sentence with a colon and the first list item much smaller than the standard distance between two paragraphs! Here an example how the text with the lists should be displayed on each widget by configuring the central style sheets on the styles page accordingly:

>![Example](https://user-images.githubusercontent.com/58981351/102913057-856ccc00-447e-11eb-876e-1ee804421b53.PNG)

2) I also prefer the distance between the single list item in the details widgets. I would also like to have the same distance for lists in the standard text widget. Why does this differ? I would also like to be able to centrally configure the distance between the list items from the styles sheet in the same way for all kinds of widgets.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: latest

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
