### ISSUE TITLE
Enable the Navigation to link to sections

### ISSUE THREAD

**Issue by nealsimmons74** [Azure/api-management-developer-portal#1102]
Currently i am writing in page navigation, however using the navigation tool provided it does not allow you to link to a section within a page only the main page. It displays the section anchors for you to choose but does not link to them.

**Comment by mikebudzynski** [comment]
Thanks for reporting the issue, I was able to reproduce it.

**Comment by azaslonov** [comment]
Implemented. Coming in next release.

**Comment by azaslonov** [comment]
It was fixed some time ago. Please feel free to re-open shall you need further assistance.
