### ISSUE TITLE
CORS is not working when Access-Control-Request-Header contains a , (comma)

### ISSUE THREAD

**Issue by handersendk** [Azure/api-management-developer-portal#1105]
## Bug description
CORS is not working when Access-Control-Request-Header contains a , (comma) in the header value. 

## Reproduction steps
Open Fiddler Composer and enter this request. 

```
OPTIONS https://apim-fleeingdragon-dev.azure-api.net/bugreport/health HTTP/1.1
Host: apim-fleeingdragon-dev.azure-api.net
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization,ocp-apim-subscription-key
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, br
Accept-Language: da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7
```

## Expected behavior
I expect the response to contain these headers. 
```
Access-Control-Allow-Headers: ocp-apim-subscription-key
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Methods: GET
```

## Is your portal managed or self-hosted?
Managed

## API Management service name
apim-fleeingdragon-dev

## Environment
 - Windows 10
 - Fiddler v5.0.20194.41348 for .NET 4.6.1

## Additional context
No subscription is required to call the API. 

This request works. It properly returns the Access-Control-Allow-Origin headers. 
![billede](https://user-images.githubusercontent.com/10637563/103284972-12fb6f00-49dd-11eb-9fff-f2a6604f017d.png)

This request fails as it does not return any Access-Control-Allow-Origin headers causing the browser to cancel the request. 
![billede](https://user-images.githubusercontent.com/10637563/103284936-f2cbb000-49dc-11eb-8b07-ca643aa00be9.png)

Note I am using Nuxt with Auth-next module which modifies Axios behavior by adding the authorization to the headers.

**Comment by handersendk** [comment]
It appears to be valid syntax to specify multiple headers seperated by , . 

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers)

**Comment by mikebudzynski** [comment]
@handersendk Thanks for reporting the issue. This repository is limited to the developer portal, I suggest that you open an Azure support request.
