### ISSUE TITLE
Collapsible menu content alignment bug

### ISSUE THREAD

**Issue by adamstruck** [Azure/api-management-developer-portal#1107]
While customizing the menu for smaller factors I set the "content alignment".  Now the menu items are always shown regardless of device size.  So now for smaller forms, the menu is shown and the menu button is clickable. When this button is pressed the menu disappears and then reappears. Additionally, while the button is "there" and can be clicked,  it is invisible (possibly related to https://github.com/Azure/api-management-developer-portal/issues/401). 

Is there a way to unset the content alignment? 

The affected portal is hosted by azure.

**Comment by azaslonov** [comment]
Hi Adam, do you have a reproduction somewhere? I'm failing to visualize it. If can't be shared publicly, can you please send a link to apimportalfeedback@microsoft.com?

**Comment by adamstruck** [comment]
Please visit https://acmeaom-dev.developer.azure-api.net/ to see the issue.  All that was changed was the "content alignment" for the collapsible menu. Once this property is set the navigation menus are visible regardless of screen size. The only fix I have found is to delete the collapsible menu and recreate it.

Also note the "invisible" button for expanding the navigation menu:

![image](https://user-images.githubusercontent.com/5560701/103595260-d84b7800-4eaf-11eb-9a70-7e77114baf99.png)

Playing around with the developer tools, I think that "icon-emb-menu-8" is supposed to be "icon-emb-list".

**Comment by azaslonov** [comment]
Hi Adam, yep, I reproduced the issue. We'll fix this.
