### ISSUE TITLE
HTTPS is not enforced in Developer Portal

### ISSUE THREAD

**Issue by lungosta** [Azure/api-management-developer-portal#1109]
I want to force HTTPS on the Developer Portal but there are no configuration settings for that.
By default, HTTPS is used by the browser but when I change it manually in the URL and switch to HTTP I don't have a redirection to HTTPS which is what I'm looking for.

Reproduction steps
Go to the developer portal
Change the HTTPS to HTTP and refresh.

**Comment by azaslonov** [comment]
Hi @lungosta, it is actually enforced (check this one for example http://alzasloneuap05.developer.azure-api.net/), unless you self-host the portal.

I'm closing the issue for now, if you think this is a problem with managed service, please raise this question with MS Support, they will help you out.
