### ISSUE TITLE
Editor mode session expiration

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1111]
## Bug description/Reproduction steps

After some time, about 15 to 20 minutes, the session of the DevPortal in **editor mode** already expires. To seriously work on pages and contents, a session would need to be at least be 2 hours. 

After the session has expired, an associated warning message pops up AND the content of the screen gets white. 
After the screen got white, you need to close and reopen the DevPortal in editor mode again. All changes that you haven´t explicitly saved in the last session are LOST!!!!!! As you cannot save every 5 minutes without being ineffective, this is a BIG mess.

![SessionExpired](https://user-images.githubusercontent.com/58981351/103993335-bd218680-5195-11eb-8243-2f069cd0b2bb.PNG)

This issue occurs already for some weeks and I hoped it would not again me who need to report this problem for the managed approach.

Could it be that you haven´t provided a fix for such issues already several times and such errors occur over time again and again. I am really tired to report this issue again and to request a longer timeout again. It is VERY annoying.

## Expected behavior

Please avoid any data loss and extend the session time to at least 2 hours to be able to seriously work on pages and contents w/o being permanently interrupted. This issue should be fixed for the managed DevPortal in editor mode as soon as possible. 

## Is your portal managed or self-hosted?

**Managed**

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: latest

**Comment by mikebudzynski** [comment]
@AnRei123, we're planning to release a fix for this problem with the next portal release (in a few weeks).

**Comment by azaslonov** [comment]
@AnRei123, turned out that we can push it in next week's release.

**Comment by AnRei123** [comment]
super, that´s great new. Many thanks in advance.

**Comment by AnRei123** [comment]
The issue occurs again since today.

**Comment by azaslonov** [comment]
Did it happen in 15-20 minutes? Basically, the expiration still can happen if the client cannot reach the backend when trying to refresh the token, i.e. when the service (developer SKU) is being rebooted.

**Comment by AnRei123** [comment]
Yes, it happens again after 15 to 20 minutes. Could you fix this issue again?

**Comment by azaslonov** [comment]
Reproduced indeed. Working on it...
