### ISSUE TITLE
Can't config to remove prefix external redis cache and some random prefix byte can't show in cache value

### ISSUE THREAD

**Issue by ThangLuuQuoc** [Azure/api-management-developer-portal#1118]
Please follow the link to clear for this issue
https://docs.microsoft.com/en-us/answers/questions/127711/possible-cache-set-value-issue-with-redis-and-api.html?childToView=232125#answer-232125

**Comment by mikebudzynski** [comment]
@ThangLuuQuoc, this item isn't related to developer portal. Please, request assistance from Azure support.
