### ISSUE TITLE
Tabs not working in displaying additional Representations

### ISSUE THREAD

**Issue by nealsimmons74** [Azure/api-management-developer-portal#1119]
## Bug description

When you have multiple representation, they are display in the portal to the user as Tabs allowing the user to switch between the to see the example payloads. This function work in the old version of the portal, however in the new version clicking the tab does not display the content of the tab.

## Expected behavior

When a user clicks on a tab the content of the tabs is displayed

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser: ALL

**Comment by nealsimmons74** [comment]
We  have Restful APIs, where i am adding the the callback response JSON as a representment example to the 202 which also has it own representment json
![image](https://user-images.githubusercontent.com/76526103/105330678-7aff3880-5bca-11eb-87d3-4ebe272f6e10.png)

when you go to the portal it displays the tabs to display the two json representments however you can't click on the second tab. In the old portal the tab link is unique, looking at the new portal HTML the tabs are using a radio button, but they both the same id therefore would not show the content of the other tabs.

![image](https://user-images.githubusercontent.com/76526103/105331053-e9dc9180-5bca-11eb-96fe-6e0efed1148a.png)
![image](https://user-images.githubusercontent.com/76526103/105331127-01b41580-5bcb-11eb-9d66-c7a2228900dc.png)

**Comment by mikebudzynski** [comment]
We'll investigate the issue.

**Comment by nealsimmons74** [comment]
Do you have a ETA when this fix will be visible in the hosted service?

**Comment by mikebudzynski** [comment]
@nealsimmons74 We'll start deployment this week, it can take 1-2 weeks for it to fully roll out. Once it is rolled out to your service, you'll need to republish your developer portal for the changes to apply in the published portal.
