### ISSUE TITLE
API Issue Widget

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#1121]
The API Management Rest API has support to add/update API Issues [https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apiissue](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apiissue)

However is there a widget to display this information in a custom page as the only one available is the History widget which displays the changelog?

**Comment by mikebudzynski** [comment]
This API operation has been deprecated alongside the legacy portal. We have plans to create a new widget for managing Issues, which most likely will integrate with GitHub.
