### ISSUE TITLE
Widget setting gets reset and is not applied

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1123]
## Bug description

When creating a new link with the Setting "Link opens in" set to "New Window" it resets most of the time. (See Gif) In the end it still opens in the same window.
On a side note: Sometimes it even resets the link target, but this is not reproduceable.

## Expected behavior

If something is set and saved it should not be reset.

## Is your portal managed or self-hosted?

Managed

## Additional context

![2021-01-19_09-47-50](https://user-images.githubusercontent.com/58420097/105010049-8b34dd80-5a3b-11eb-8887-c61a0389228a.gif)

**Comment by azaslonov** [comment]
Hi @ZarTrox, the option "Open in new window" works in the published portal only. Do you want it to open in a new window in design mode as well? If yes, what is expected behavior, another designer window?

**Comment by AnRei123** [comment]
Hi Alex, I wonder that you seem not to be able to reproduce the issue described above. 
For our environments, open in new window works VERY sporadically for only VERY VIEW images. For most of them 95% it does permanently not work even after reconfiguring the setting. This behavior has been tested for our environments in the published mode several times for the same link after correcting the lost settings again and publishing again and again. 
If you download the data.json file, you can see that the setting is mostly not reflected there! Even after setting the flag "Open in new window" again and gain. It is therefore very disgusting, especially for external links, portal users loose the focus of the portal and will walk away to external contents. Here it is very essential for us that links to external web contents would always open a new browser tab or new broswser window. But there are also other link examples where we do like to open the target not on the same browser tab card.
In the video above, we did not publish the portal as the GUI does not remember the setting in the GUI after refreshing the page. Even if you save the page and download the data.json file, you can see that the "_blank" value is not added according to the previous configuration in the GUI.

**Comment by azaslonov** [comment]
Hi Angelika (@AnRei123), I found a few cases today indeed, fixed some of them and working on the others. I won't be able to push it in the ongoing release, but will do it for the next one.

**Comment by azaslonov** [comment]
Fixed all cases, releasing soon.
