### ISSUE TITLE
Developer portal demo

### ISSUE THREAD

**Issue by wi5nia** [Azure/api-management-developer-portal#1124]
Hi

do you have some code or a running demo of a very customized developer portal? Need for showcase purposes.

**Comment by azaslonov** [comment]
Hi @wi5nia, yes, here's a couple of dev portals:
https://developers.cemexgo.com/
https://sbx-developer.bentley.com/

...and a couple of others built with the same engine:
https://hostmeapp.com/
https://restik-1.papersites.io/
