### ISSUE TITLE
CORS proxy for the interactive console

### ISSUE THREAD

**Issue by francismijares** [Azure/api-management-developer-portal#1125]
Will hosting our new developer portal in the same domain as APIM resolve CORS issues? (e.g. will not require CORS policies) 

We already have a lot of APIs deployed that do not have the <base> policy set and it will be difficult to enforce a CORS policy unless all APIs have added the <base> element. 

Looking for an alternate solution for deploying the self-hosted developer portal so that it can be used for all our existing APIs.

**Comment by azaslonov** [comment]
Hi @francismijares, just using a custom hostname won't resolve the CORS issue. Also, you don't need to define CORS policy on every API, you can define a global (All APIs-level) policy instead.

Another thing that we're shipping in one of the next releases is the CORS proxy that will be part of the portal backend. Switching to would allow you not to define CORS policy at all.

**Comment by azaslonov** [comment]
Released everywhere in the public cloud. Please you new "Use CORS proxy" option in the "Operation details" widget editor to enable it.

**Comment by koamano** [comment]
Hi, thank you so much for working on this and getting this released.  Francis and I have been trying to use the new CORS Proxy but haven't been able to successfully get it to work. 

We chose the "Use CORS proxy" option and published it to our self hosted portal. We can see that it is trying to route "try it" requests to what we have set as the backendUrl value in our config files but I don't think we are using the right values for that. We've tried using our custom domain of our self hosted dev portal. 

When using the custom domain of our self hosted dev portal, we get "405 The resource doesn't support specified Http Verb."

Can you please advise where we can find the "portal's backend endpoint" or if there are additional configurations we are missing? Thanks!

**Comment by azaslonov** [comment]
Hi @koamano, you should be able to point it to your APIM service, just use "backendUrl" setting in your runtime.config.json:
```
{
    "environment": "runtime",
    "managementApiUrl": "https://yourservice.management.azure-api.net",
    "backendUrl": "https://yourservice.developer.azure-api.net"
}
```

We'll add proper documentation for this feature soon.
