### ISSUE TITLE
Does the self hosted portal version support the visual editor in the same way the hosted version does? 

### ISSUE THREAD

**Issue by rvila7** [Azure/api-management-developer-portal#1128]
Hello and thank you in advance for your support. 

I have a self hosted portal and would like to edit the content with the visual editor in the self hosted endpoint in the Azure Storage Account. I can't seem to be able to activate the admin UI in the self hosted url to edit the content. Is this possible? Or am I only able to edit the content in the visual editor locally?

I still am able to access the hosted developer portal, and it lets me edit the content visually but those changes are not reflected in the self hosted url. is this expected behaviour? 

Let me know If I need to provide more detail or if my questions were not understood. 

Thanks

**Comment by azaslonov** [comment]
Hi @rvila7, managed version of the portal has a backend that does some of the additional things like authentication, routing, etc. At some point, we're going to open source it as well, but for now what you can do is host the designer in separate blob storage, using `/signin-sso` resource for authentication (some details are [here](https://github.com/Azure/api-management-developer-portal/wiki/Single-Sign-On-%28SSO%29-authentication)). We understand it's not a super convenient way, and we're working on making it better.

Hope that helps. I'm closing the issue for now, but please feel free to post follow-up questions.
