### ISSUE TITLE
Newline character not rendered in APIM Dev Portal

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#1131]
Adding a newline character '\n' in the description field of the API specification as shown below does not get rendered as a newline in the Dev Portal.

Below is the raw text format of the description field. with the newline character highlighted.
![image](https://user-images.githubusercontent.com/62035456/106063647-65a38480-615d-11eb-8713-5191ad2b6885.png)

In the APIM Management portal it is shown correctly.
![image](https://user-images.githubusercontent.com/62035456/106063939-e498bd00-615d-11eb-9aae-ecd38dae617f.png)

However in the APIM Developer Portal it is not rendered correctly. I would expect the highlighted text to be on a new line.
![image](https://user-images.githubusercontent.com/62035456/106064098-26c1fe80-615e-11eb-8da6-ec0c28720d82.png)

**Comment by azaslonov** [comment]
Hi @watson20201, this field accepts Markdown/HTML (which of course we failed to mention in UI), so for the new line, you can try out methods [described here](https://gist.github.com/shaunlebron/746476e6e7a4d698b373).

Hope that helps.
