### ISSUE TITLE
Publish not working anymore after export/import of developer portal

### ISSUE THREAD

**Issue by mbogaard-nutreco** [Azure/api-management-developer-portal#1134]
We're trying to export/import the Developer Portal from our development environment into an acceptance environment. This way we can do the needed changes in 1 environment and move everything nicely via pipelines to a next phase. Although this is not directly supported in the Developer Portal, there are several tools available for this purpose. I've looked at a few (see below) but all of them seem to have the same problem. The initial export/import into another environment works fine, but after an import we're not able to publish anything anymore. Although the 'publish' functionality looks to work, nothing is exported. We tried both the publish options from the admin environment of the developer portal and the Azure portal. Any clues why this happens? Is this a bug?

Tools tried:
[Tools mentioned in this repo](https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services)
[Jake Scotts Go tools](https://github.com/jake-scott/apim-tools)
[Janne Matilla scripts](https://github.com/JanneMattila/329-azure-api-management-developer-portal)

**Comment by azaslonov** [comment]
Hi @mbogaard-nutreco, can you please your service name(s) to apimportalfeedback@microsoft.com (and mention this issue, we'll take it from there.
