### ISSUE TITLE
api-management gitignore + backends ARM

### ISSUE THREAD

**Issue by verschaevesiebe** [Azure/api-management-developer-portal#1135]
Hi 👋🏽 

We have a client where we have 3 environments (DEV, TST, PROD).
All API Management resources are using the Standard Tier. (Git repository support)

We noticed that whenever we add a .gitignore file to the repository we are not getting it back when pulling nor are the files we ignored delete from the repository.

The reason why we want to apply this is that we want to sync the Backends over the 3 different RG environments.
We have an ARM template for each env deploying the API resource and are currently using the Named Values option to refer to Logic App callback URLs (These are also deployed through ARM linked template so we have the dynamic callback URL per logic App).  

We would like to transfer the use of named values and policies to the **Backend** tab in APIM but every time we initiate a user-snapshot from the portal the **Backend folder** is filled with the logic apps URL predefined. So whenever we move the DEV repository to the TEST environment and push the configuration we end up with backends from DEV on the TEST APIM resource.

Essentially we try to exclude the backends folder from the GIT Repo so that we can deploy the backends through ARM ourselves including the dynamic callback logic app URLs.

If there is another way to keep the Backends synced to the ARM then I would love to hear about it.
Currently, when deploying through arm the backends get overwritten by the GIT repository.

If you need any additional information feel free to ask !

**Comment by azaslonov** [comment]
Hi @verschaevesiebe, since this is question is not related to the developer portal project, I have to refer you to MS Support, they will help you with this.
