### ISSUE TITLE
Error when trying to edit API Management Service Developer Portal.  We get the error when navigating to edit the portal "Oops, something went wrong. We are unable to complete your operation this time. Please try again."

### ISSUE THREAD

**Issue by PerMBlomqvist** [Azure/api-management-developer-portal#1136]
## Bug description
Error when trying to edit API Management Service Developer Portal.  We get the error when navigating to edit the portal "Oops, something went wrong. We are unable to complete your operation this time. Please try again."

This worked fine for several weeks but started failing consistently  recently (past 1-2 weeks).

Failure happens every time and we have tried various users with Admin and Owner rights.

## Reproduction steps
1: In Azure API Management Service.  Navigate to Portal Overview.
2: Click Developer Portal button/link.
3: This open up another browser tab and attempts to open the Portal Authoring/Edit UI.  We can see the floating toolbars but then get the spinner and the "Oops, something went wrong....." message.

Getting these errors in Chrome Dev tools:
Uncaught (in promise) TypeError: permalinkResolver.getHyperlinkFromContract is not a function
    at exports.PermalinkResolver.<anonymous> (paperbits.js:2)
    at Generator.next (<anonymous>)
    at paperbits.js:2
    at new Promise (<anonymous>)
    at __awaiter (paperbits.js:2)
    at exports.PermalinkResolver.getHyperlinkFromContract (paperbits.js:2)
    at exports.ButtonModelBinder.<anonymous> (paperbits.js:2)
    at Generator.next (<anonymous>)
    at paperbits.js:2
    at new Promise (<anonymous>)
<img width="1268" alt="APIM error" src="https://user-images.githubusercontent.com/46333679/106301480-63a0fa80-621d-11eb-9d06-046a9ac7ed50.png">

## Expected behavior
System should open dev portal in edit mode.

## Is your portal managed or self-hosted?
Managed

## API Management service name
https://prod-safe-affinity-apimanagement.management.azure-api.net

## Environment
Windows 10, Chrome.

## Additional context

Add any other context about the problem here, including screenshots.
See screen shot with Chrome Devtools turned on.

**Comment by azaslonov** [comment]
Hi @PerMBlomqvist, yeah, this is known issue, it was fixed already, the release is coming some time next week.
