### ISSUE TITLE
ApimDelegation callbacks with ChangePassword, ChangeProfile, SignOut operation don't contain returnUrl, therefore it's unclear how to calculate HMAC and validate sig for them

### ISSUE THREAD

**Issue by xakpc** [Azure/api-management-developer-portal#1138]
I presume this is a bug in either codebase or a mismatch in the documentation. I spent several hours trying to get to the root of that, but failed - I'm not that familiar with knockout and paperback, unfortunately.

## Bug description

I use delegation to manage users and subscriptions myself (by AAD B2C and Paddle if it's matters). For security reasons you are advised to verify that the request is coming from Azure API Management:

- Compute an HMAC-SHA512 hash of a string based on the `returnUrl` and salt query parameters (example code provided below):
- `HMAC( salt + '\n' + returnUrl )`
- Compare the above-computed hash to the value of the sig query parameter. If the two hashes match, move on to the next step, otherwise deny the request.

The problem here that ChangePassword, ChangeProfile, SignOut operations don't include `returnUrl` parameter in the callback

## Reproduction steps

1. Enable Delegation of your AAM
2. Implement ApimDelegation endpoint to handle callbacks (like [this](https://github.com/API-chat/ApiChat.Web/blob/4b88321d00116259d74de2ca55c624dc36ebeb43/ApiChat.Web.Auth/Pages/ApimDelegation.cshtml.cs#L67))
3. Login under user account, press Sign Out
4. Ensure that no returnUrl in callback
5. Ensure that generated hash does not match

## Expected behavior

I expect either to get `returnUrl` and use it in the hash generation or the proper formula for hash generation

## Is your portal managed or self-hosted?

Managed

## API Management service name

api-chat

## Environment

 - Operating system: Win10
 - Browser: Chrome
 - Version: 88.0.4324.104

## Additional context

This are logs of related HTTP requests:

When the user click **Change Profile** button, note `returnUrl` in the cookies
``` PS
Invoke-WebRequest -Uri "https://developers.api.chat/delegation-changeProfile?userId=ba761ab4-0644-4fb1-9426-6d1760312269" -Headers @{
"Upgrade-Insecure-Requests"="1"
  "User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"
  "Accept"="text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
  "Sec-Fetch-Site"="same-origin"
  "Sec-Fetch-Mode"="navigate"
  "Sec-Fetch-User"="?1"
  "Sec-Fetch-Dest"="document"
  "Referer"="https://developers.api.chat/profile"
  "Accept-Encoding"="gzip, deflate, br"
  "Accept-Language"="ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"
  "Cookie"="usr=d9fe953e-b331-4cc4-97ee-9b60b849b338; _ga=GA1.2.2102634476.1602069810; ai_user=...; _gid=... ai_session=dYDSy|1612182936496|1612182968640.87; auth=...; returnUrl=/profile"
}
```
The generated response does not contain `returnUrl` and computed hash based on docs does not match sig parameter

```
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://localhost:44302/apimdelegation?userId=ba761ab4-0644-4fb1-9426-6d1760312269&operation=ChangeProfile&salt=ZzgykTAQHHzUzOHtnBol8QX1QeWlQUxBFZc2ZfGyaP0%3D&sig=fft2nGGdA2i3a8M5mIwd740GSYgxdcsE9AgR8ZhdqLS5pGCEqpR7IP5y2wO2XGS%2F%2BjgkskHLnPDGqbDmElS2PQ%3D%3D
Vary: Accept
X-Powered-By: Express
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000;includeSubDomains;
Date: Mon, 01 Feb 2021 12:46:31 GMT
Content-Length: 586
```

I tried to calculate hash differently - but no luck

- `HMAC( salt + '\n' + null )`
- `HMAC( salt + '\n' + "" )`
- `HMAC( salt + '\n' + "/" )`
- `HMAC( salt + '\n' + "/profile" )`
- `HMAC( salt )`

I tried to locate server-side hash generation which would solved the problem immediately, but couldn't find it.

**Comment by ygrik** [comment]
Hi @xakpc 

Regarding our documentation 
https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-setup-delegation#-delegating-developer-sign-in-and-sign-up

The **returnUrl** parameter is used only for **SignIn** and **SignUp**
HMAC(salt + '\n' + returnUrl)

For **CloseAccount**, **ChangeProfile**, **ChangePassword**, **SignOut** the **userId** is used in signature
HMAC(salt + '\n' + userId)

Please let me know if need more details.
