### ISSUE TITLE
Question: Is there a simple way to redirect customers from the deprecated portal to the new portal

### ISSUE THREAD

**Issue by nealsimmons74** [Azure/api-management-developer-portal#1140]
Using the hosted service is there a simple way to redirect customer from
*.portal.azure-api.net to *.developer.azure-api.net

I have changed all the email notifications to point to the new portal, which will prevent new users going to the old site, however existing user can still access the site.

Suggestions welcome

**Comment by azaslonov** [comment]
Hi @nealsimmons74, unfortunately, there is no way I can think of. If you had a custom hostname, you could do some re-routing, but with .portal.azure-api, I don't think so, sorry.
