### ISSUE TITLE
Use Authorization Code Flow with PKCE instead of Implicit Flow

### ISSUE THREAD

**Issue by RodrigoGroener** [Azure/api-management-developer-portal#1142]
Currently authentication to Azure Active Directory is done with "adal-vanilla". It's only supports OAuth implicit flow.
Would it be possible to switch to "msal-browser" (MSAL v2) to use the authorization code flow with PKCE?

referencing last change of authentication 
#302 
#298

**Comment by saikiran-karumuri-by** [comment]
We are also looking for same feature. Any idea when it will be available?

**Comment by mikebudzynski** [comment]
We don't have an ETA yet, please track this issue for updates.

**Comment by arvind1234** [comment]
@mikebudzynski Friendly bump, are there any further updates on adding support for PKCE flow? On a security review and we have been asked to look at ways to turn off implicit grant flow and that wouldn't be possible until APIM portal starts supporting auth code + PKCE.

**Comment by mikebudzynski** [comment]
Merging the duplicate #1146 into this issue.
