### ISSUE TITLE
Support for Use Authorization Code Flow with PKCE instead of Implicit Flow - interactive console

### ISSUE THREAD

**Issue by saikiran-karumuri-by** [Azure/api-management-developer-portal#1146]
Hello Team, Is there any support for Authorization Code Flow with PKCE instead of Implicit Flow - interactive console ??

**Comment by azaslonov** [comment]
Hi @saikiran-karumuri-by, there is no support for PKCE currently, but we're planning to add it. I don't have ETA right now though.

**Comment by mikebudzynski** [comment]
Closing this issue as a duplicate of #1142
