### ISSUE TITLE
Different call limits for different API keys on Azure API Manager

### ISSUE THREAD

**Issue by mathewjustin** [Azure/api-management-developer-portal#1154]
Hi Team,
   I have a use case where I need to monetize one of my existing API for different customers. Based on the plan they choose they will be able to access this API on different limits. Say a premium customer can call my api once in every minute and a customer on my Basic plan can call the API once in 10 minutes.

I am looking for a way to have different rate limits for different API keys. Basically a Map of API key and corresponding rate limit I need to configure. So that same API can be accessible by different different clients, and each of them will be having their own rate limits.

Is there any ways to achieve this via APIM?

https://stackoverflow.com/questions/66242731/different-call-limits-for-different-api-keys-on-azure-api-manager

**Comment by gfchaves** [comment]
If you create different products and for each defines different rate [limits by using policy expression](https://docs.microsoft.com/en-us/azure/api-management/api-management-access-restriction-policies), does this accomplish what you need?

**Comment by mathewjustin** [comment]
I have tried keeping some expression to obtains the calls like the below 

  <rate-limit-by-key calls="@{
     return Int32.Parse(context.Subscription.Name.Split('-')[1]);
}" renewal-period="15" counter-key="@(context.Subscription.Id)" />

Here I have attached -[number of calls] in the Subscription name itself to split and use it. But unfortunately calls attribute on rate-limit-by-key and quota-by-key does not support policy expressions. 

https://stackoverflow.com/a/43195940/8804776

**Comment by azaslonov** [comment]
Hi @mathewjustin, I think you could [Control flow](https://docs.microsoft.com/en-us/azure/api-management/api-management-advanced-policies#choose ) policies for this case. Here each `when` statement could match one of your products.

**Comment by mikebudzynski** [comment]
@mathewjustin You can also apply the rate-limit policy on the Product scope. If you need further assistance, please contact Azure support; I will close this issue because it doesn't relate to the developer portal.
