### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1155]
## Bug description

For a few days everything seems to be taking very long to load. Trying to login or even just navigating through the Devportal. Is there currently a problem with the servers? And if so are there any plans when it will be fixed?

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @ZarTrox, I tried one of your services (which is on Dev SKU I believe), looks pretty decent. Please feel free to email me specific service names, we can take a look closer.
