### ISSUE TITLE
Guest user verification failed

### ISSUE THREAD

**Issue by giovannaalves** [Azure/api-management-developer-portal#1157]
## Bug description
When the user is invited to connect to the portal, he is directed to a page not found, which prevents him from registering his password and using the portal.

The link sent to the user's email is as follows:
https://mysite/confirm-v2/identities/basic/invite?userid=userId&identity=identity&ticketid=ticketid&ticket=ticket
It is generated from the "$ConfirmQuery" parameter in the notification configuration of Invite User mail.

Should it be another url?
I tryied to use only singup url, but it doesn't work too..

## Reproduction steps

1. Invite a user to the portal
2. User receives the email and clicks the link
3. The 404 page is displayed

## Expected behavior
User should be able to set a password and activate the account.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release 2.5.7

**Comment by ygrik** [comment]
Hi @giovannaalves 
Thank you for submitting this issue. 
Regarding our wiki https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-8-change-api-management-notification-templates
You should change the notification template with URL https://mysite/signup?$ConfirmQuery

Now, this is the bug and the url does not work for self-hosted. The fix will be provided later.

**Comment by giovannaalves** [comment]
Hi @ygrik
Ok, I will wait the next release.
Thank you so much!

**Comment by giovannaalves** [comment]
> Hi @giovannaalves
> Thank you for submitting this issue.
> Regarding our wiki https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-8-change-api-management-notification-templates
> You should change the notification template with URL https://mysite/signup?$ConfirmQuery
> 
> Now, this is the bug and the url does not work for self-hosted. The fix will be provided later.

Hi @ygrik 
Ok, I will wait the next release.
Thank you so much.
