### ISSUE TITLE
Migrate Developer Portal - fonts are not transported correctly

### ISSUE THREAD

**Issue by LSchuster** [Azure/api-management-developer-portal#1165]
## Bug description

We transport our API Management Developer Portal via the migrate feature thorugh the different stages, everything seems to work, but when we upload a different font to the page and set this font the regular style, the correlation between the added font and the .ttf file seems to be lost, after we transport the Portal to the next stage.

I noticed that if we .capture the content the fonts in the font folder are appended with another file extension "ca13e624-77a8-3801-4039-4c64aa375b07.ttf.ttf" for example.

Instead of .migrate i tried to use .capture remove this additional file extension and than call .generate but this is also not applying the font correctly.

We are using Version 2.6.0, but i also tried older versions.

## Reproduction steps

1. Go to the first Developer Portal in Admin Mode and upload a font and apply it to the "regular" style to apply it everywhere.
2. Save and publish the site.
3. Execute .migrate to deploy the Portal to the second Developer Portal
4. Go to the second Developer Portal: the style should look good, the font definition is also present, but it is not associated with the .ttf file.

## Expected behavior

If i execute .migrate i would expect the fonts to also be migrated correctly

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @LSchuster, thanks for reporting the issue, we'll fix this.

**Comment by mikebudzynski** [comment]
Fixed with #1295

**Comment by ericfran** [comment]
Hi,
using migrate.bat command to copy a Apim portal to another but some font doesn't seem correct.

source APIM Fonts
![image](https://user-images.githubusercontent.com/71752480/123975725-da554600-d9bd-11eb-8943-dfa609b016ed.png)


target after migrate.bat
![image](https://user-images.githubusercontent.com/71752480/123975887-fce75f00-d9bd-11eb-8274-44e7576f0413.png)


not the correct font style :-(

Regards,
Eric
