### ISSUE TITLE
Will capture.js and generate.js work to transfer content between different APIM instances?

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#1166]
I want to be able to save the content of a developer portal to disk (and then put it in an Azure DevOps repo). Later I want to retrieve that information and use it to populate another developer portal (belonging to another instance of API Management). 

However, I noticed that the downloaded data.json of some older developer portals contains some items with a  "downloadUrl" with a value starting with a blob storage url that seems to be the internal blob storage of the source APIM instance. I haven't seen that on newer APIM instances though. Since that probably will be a problem after having copied data to another developer portal, at least if the original API Management instance is deleted, I wonder:

1. Will it be possible to use the capture.js and generate.js files that are in Scripts.V2 and Scripts.V3 to successfully transfer portal content from one portal to another? 
2. Is it possible to use Scripts.V2\capture.js to save to disk and then use Scripts.V3\generate.js to populate a developer portal? 
3. As above but using Scripts.V3\capture.js and then Scripts.V2\generate.js.

## Is your portal managed or self-hosted?

Both

**Comment by azaslonov** [comment]
Hi Erik, right in older versions we had that `downloadUrl` attached to media files metadata, but now this URL gets always re-calculated during content publishing to avoid issues related to migration or SAS token expiration, and now only source key matters, unless external media file is referenced.

So for #1 and #2, - yes scripts v2 and v3 are safe to use for capturing and restoring snapshots.
For #3 - also yes, they use the same storage format.

**Comment by azaslonov** [comment]
Closing for now since the answer is provided. Please feel free to re-open shall you have follow-up questions.
