### ISSUE TITLE
Article and Aside arrangement with smaller screen resolutions

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1168]
## Bug description

When reducing the viewport size the "Article" & "Aside" elements from the Section seem to get rearranged with the "Aside" element always first. In our Use case where we use the "Aside" element primarily for Annotations/Links etc. this feels odd since in my understanding the main information should be stored in the "Article". If the "Aside" element is put before the "Article" it stands out of context.

## Reproduction steps

See gif

## Expected behavior

- If this is intended behavior then an option to change the arrangement when using a smaller device would be useful (which can be set as default for all other Sections).
- A description where the behavior is stated (If I have not overlooked it)
- Change sequence if not intended

## Is your portal managed or self-hosted?

Managed

## Additional context

![2021-03-01_09-33-37](https://user-images.githubusercontent.com/58420097/109479289-83c11500-7a7a-11eb-8e09-8dcb0cb60d1b.gif)

**Comment by azaslonov** [comment]
Hi @ZarTrox, thanks. I agree, it should go below. Let me fix the template in the next release. Just in case, only newly added sections will have the new layout, all the existing ones will stay as is.

**Comment by ZarTrox** [comment]
As you have mentioned in other tickets, you are currently working on a new grid-approach. While this is really good news this issue unfortunately still persists.

I don't know when the release of the grid feature is scheduled but until then a solution to this issue would be great.

And when the grid-approach is implemented then it is necessary that the portal automatically converts all current settings correctly to the new design for all screen resolutions. Changing the settings for every section on every page for each of the resolutions would be fatal.

Thank you.
---
@AnRei123

**Comment by AnRei123** [comment]
We use the longer left column of the above referenced two-column section template to add our major page contents. In the right column, we optionally provide a list of links that refer to related articles in the DevPortal or to external web pages.  For smaller resolutions, the link list is provided on top followed by the content. With the normal read direction from top to down it appears to the reader like the link list is belonging to the paragraph above and not below. That is definitely irritating the API consumers. We use the two-column section template for a lot of pages and paragraphs to ensure the right alignment of the referenced links with the text in the right paragraph.
For us it is very important that irrespective of your offered solution that we do not need to modify each section/block individually to change the sort order on paragraph level. 
**Could you take care that the sort order is centrally been corrected after bug fixing and that we do not need to add additional efforts on each section/block separately?** The right sort order should be automatically fixed for all screen resolutions where the page width does not allow to display the two columns next to each other.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
