### ISSUE TITLE
Interactive Console OAuth2 Auth: 404 with self-hosted portal

### ISSUE THREAD

**Issue by patst** [Azure/api-management-developer-portal#1170]
We are struggling to get the interactive console in the developer portal running for our OAuth2 secured APIs.

* we configured an OAuth2 service in the API-Management instance 
* configured an API to use the OAuth2 service
* have an self-hosted portal with a custom domain behind an Azure Application Gateway
* deployed the self-hosted gateway to a storage account in the `$web` container as described in the Wiki

When we open the interactive console, we are redirected in a new window to the AAD to give our consent to use the APIs AAD application. 
After that we are getting redirected to something like:

```
https://<portal-hostname>/signin-oauth/implicit/callback#access_token=ey-<LONG_TOKEN>
&token_type=Bearer&expires_in=3599
&scope=<app-id>%2fUser.Read+<app-id>%2f.default
&state=071e290a-56ef-ba38-7335-428fa490bcbf
&session_state=9c11d1ac-52a4-4e35-9573-763fc02e05d9
```

But this page does not exist in our self-hosted portal. Instead a 404 page is getting displayed.

 Do we need to register a special handling of the `signin-oauth/implicit/callback` route? Or is there an error in our publishing step?
It was working with the managed portal.

Any advice would be appreciated!

**UPDATE **:
I managed to get it working by manually creating file in the blob storage at `$web/signin-oauth/implicit/callback/index.html` which looks like this:

```
<!DOCTYPE html>
<html>

<head>
    <title>Authentication</title>

    <script type="text/javascript">
        function closeWindow() {
            if (opener) {
                opener.postMessage({ uri: window.location.hash }, "*");
            }
            self.close();
        }
        closeWindow();
    </script>
</head>

<body>
    <h1>
        You have successfully authenticated.
    </h1>
    <button onclick="closeWindow()">Close</button>
</body>

</html>
```

Why is this page missing in our default self-hosted portal deployment?

**Comment by azaslonov** [comment]
Hi @patst, right, this endpoint is part of the portal's backend, and of course, if you self-host it without one, ther will be no such a handler. The `implicit` flow is the only one that doesn't require access to secrets on the backend side, that's why simple file replacement worked for you.

However, there is an option that we currently have called `backendUrl`. So if you specify it in your `config.runtime.json` file, pointing to your service, i.e. `https://developer.[servicename].azure-api.net`, then you'll be able to use embedded OAuth handlers (and not only for implicit flow).

**Comment by patst** [comment]
@azaslonov  thanks for your reply and the clarification.

It would be great to be aware of this limitations/ circumstances when starting to self host the portal. With the current documentation I had the impression I am getting the same features when using the self-hosted portal.

For others having the same challenge:
Now we use an Azure function to implement the auth code backend feature.

**Comment by mikebudzynski** [comment]
@patst, have you tried the backendUrl configuration option that @azaslonov mentioned? It would your self-hosted portal to the API Management's backend and you'd be able to use our OAuth functionality.

**Comment by patst** [comment]
@mikebudzynski yes I did try that, but we have a custom domain for the self-hosted portal the old domain seems to be no longer available. The DNS name cannot be resolved:

`nslookup <apim-name>.developer.azure-api.net`

=> *** UnKnown can't find apimname.developer.azure-api.net: Non-existent domain

`nslookup developer.<apim-namez.azure-api.net`

=> *** UnKnown can't find developer.apim-name.azure-api.net: Non-existent domain

We are using a API-Management deployed in a private vnet and a custom dns server configuration. (The custom DNS server delegates to a private Azure DNS Zone)

**Comment by mikebudzynski** [comment]
The `backendUrl` configuration option should also work with a custom domain, which is specified for the developer portal (so also its backend) in the API Management service.
