### ISSUE TITLE
Performance Test Dev Portal

### ISSUE THREAD

**Issue by campifoo** [Azure/api-management-developer-portal#1171]
We have a customer that is performance testing the dev portal and is getting 429 response.  Too many requests.  Is this a limitation on the Management API?  Is there a way to increase the number?

**Comment by mikebudzynski** [comment]
@campifoo Were the tests run against the deprecated (legacy) portal or the new portal? What's the workload that it's failing for?

**Comment by campifoo** [comment]
It runs against the new portal.  The https://xxx.management.xxxx.com/subscriptions/xxx/resourcegroups/xxx/providers/MIcrosoft.ApiManagement/service/xxx/apis/provider-directory.......  REST api that is the first one to return 429 response.

**Comment by azaslonov** [comment]
Hi @campifoo, Ok that explains it, both new and legacy portals hardly depend on Management API, which indeed has throttling and which depends on the SKU/capacity of service and other factors. Therefore, the only suggestion I have is to scale up, but please feel free to follow up with MS Support on this topic, they might be able to better assist you.
