### ISSUE TITLE
Standard DevOps CI/CD

### ISSUE THREAD

**Issue by afj88** [Azure/api-management-developer-portal#1173]
First things first, thanks for your work! This product is amazing!

I've setup CI/CD as explained here https://docs.microsoft.com/en-us/azure/api-management/devops-api-development-templates (more or less).

I'd like to include developer portal publish in my release pipeline and I've read that you're working on it - GREAT!

I'd also like to try to edit the developer portal UI on a local environment and publish it to an existing instance of API Management; in that way I could save the portal UI in git repository. Do I have to always keep a published version of my developer portal UI in order to avoid losing my work (using the migration between instances approach) ?

Thaks in advance!
Alex

**Comment by mikebudzynski** [comment]
@afj88, currently there are two options to source control developer portal content:

1. First, make the changes in the administrative interface of either a managed or a self-hosted portal (they will be saved to your API Management service). Then, run the `capture` script from the scripts folder to export the content of your portal from the API Management service.
2. Use ARM templates and/or [the content types and content items REST API](https://docs.microsoft.com/rest/api/apimanagement/2019-12-01/contenttypes) for managing content of your developer portal.

As of today:

1. The developer portal doesn't integrate with the built-in git repository, which contains service configuration.
2. It's not possible to save content changes to the local filesystem.
