### ISSUE TITLE
New Development Portal of Azure APIM does not list APIs/Products when accessed from Internet.

### ISSUE THREAD

**Issue by gaurav-p-sood** [Azure/api-management-developer-portal#1175]
Hi Team

Need some guidance here. I recently moved my custom domain to point to new Dev Portal of APIM instead of legacy dev portal. I'm able to browse the portal from internet using the custom domain but when tried to list products/apis it says no APIs found. 

This wasn't the case with legacy portal. I was able to successfully list and test APIs using legacy portal. 

My APIM is hosted in internal VNET guarded by an App Gateway. Here is the link to my APIM portal.

https://www.biztalkers.in

I have followed implemented all the rules in a NSG listed here 

[When an API Management service instance is hosted in a VNET, the ports in the following table are used.](https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet)

I know the management API is called by Dev portal to get information about products/apis but some how the new DEV portal is unable to make the call to the APIM's management API where as Legacy portal never had issue. 

Please help me out. 

Regards
-Gaurav

**Comment by mikebudzynski** [comment]
The new developer portal requires connectivity to the management endpoint, the legacy portal didn't. There are also a few WAF rules you might need to disable: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-integrate-internal-vnet-appgateway#exposing-the-developer-portal-externally-through-application-gateway Please, open an Azure support request for further assistance.

**Comment by gaurav-p-sood** [comment]
I've a standard tier on application gateway and DO NOT have WAF implemented. Can you please reopen the issue? 

Regards
Gaurav

**Comment by mikebudzynski** [comment]
@gaurav-p-sood WAF could only be one reason for failure. I suggest that you reach out to Azure support, they will be able to troubleshoot your network configuration and find the problem.

**Comment by gaurav-p-sood** [comment]
Sadly I do not have a support plan. Might be a dumb question but if there is no WAF in play how can that be an issue? 

Regards
Gaurav

**Comment by gfchaves** [comment]
@gaurav-p-sood probably you could have another resource in place that can be a blocker. Check for your available [support plan](https://azure.microsoft.com/en-us/support/plans/) or even the technical communities that can help you out.

**Comment by gaurav-p-sood** [comment]
Hi Gfchaves 

Thank you for your reply. I figured out that the APIM management URL wasnt getting authenticated and hence I was not able to list down the APIs . It was a certificate issue which is now sorted . Thank you so much for the help. 

Regards
Gaurav
