### ISSUE TITLE
Support links on the same page - support jumping to anchor points are missing

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1176]
## Bug description

Currently when inserting a link pointing to the same page the whole page first is reloaded.

This is a problem for the following two use cases:
1. On the API details and on the API product details page, linking to a subchapter would lead to empty widgets. Because if you reload the page the API context is lost.
2. For longer pages with a lot of media it can be time consuming to reload the page. Also on a glossary page switching between glossary entry references should be quicker than it is today.

## Expected behavior

Instead the page should just jump/scroll to an anchor such as header (e.g. header 1) without reloading the whole page. Especially, add an option to easily jump to the top or the bottom of the page without reloading again.

For API details and API product details pages allow jumping to dedicated areas of the same page without losing the widget content.

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
Sorry for the late reply. I meant in the published Portal. "Normal" links from one page to another one work fine but if I say the link on page 1 should point to page 1 heading 2 then the whole page reloads.

**Comment by azaslonov** [comment]
Fixed in the last release. If the anchor element is on the same page as the link pointing to it, the page doesn't get reloaded anymore, it just jumps to the anchor.

**Comment by AnRei123** [comment]
If you add a link to the top of the API details page to navigate to the end of the page with the "API: Products (table)" widget, you are now able to see the list of the parent API products.
**But,** after clicking the "down" link on the API details page, the list of operations and the operation details do not contain any content anymore!
![ApiDetailsPage_NavigateToAnchor](https://user-images.githubusercontent.com/58981351/115844539-38930500-a420-11eb-8dc9-4315660b4a69.PNG)

**Comment by AnRei123** [comment]
We have a lot of lengthy pages with a TOC link list next to the header to facilitate jumping to sub topics. For the reading/published mode (except of the API details page) its does properly work now.
**BUT in the designer/editor mode it does not work at all** !!!!!!!!!!!!!!
As an editor, I need to be able to quickly jump directly to dedicated sub topics to get at least a little speed. With the new anchor mechanism implemented this shouldn´t be a big thing to fix at all, isn´t it? Currently, it is really a pity. You need a lot of mouse meters to do updates and write new articles.

**Comment by azaslonov** [comment]
Got it. With the "Go down" link case, this is because API-related widgets also use the hash part of the URL for identifying APIs and Operations. I'll need to think how we can solve this.

The jumping to anchor in designer - I actually fixed it recently, coming in next release :)

**Comment by AnRei123** [comment]
**And also links on the same page, do currently not work at all in the designer/editor mode!!!**
This is also an issue that slows me down very much when editing on lengthy pages. For example, on our glossary, I provide several cross links to related glossary items. But in the designer/editor mode, it is currently not possible to directly navigate to the link target on the same page. Instead, you need to scroll a lot to actually find a single cross reference item.
Is this issue also covered by your upcoming fix with the next release?

**Comment by azaslonov** [comment]
Yep, we're starting the new release rollout today.
