### ISSUE TITLE
"API: products (dropdown)" widget missing

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1177]
## Bug description/proposed behavior

Currently there are only two API: product widgets:
- API: products
- API: products (tiles)

A "API: products (dropdown)" widget is missing.

The missing widget should perfectly compliment the view of the already existing widget "List of products".
![image](https://user-images.githubusercontent.com/58420097/110300449-289d9e00-7ff7-11eb-84fa-b5ed900995f9.png)

The missing "API: products (dropdown)" widget should be directly placed together with the shown widget in the screenshot. The reference to the parent API products should be accessible from the context of the API description in the header section of the API details page.
For this use case tiles or tables are not suitable.

Remarks: as a temporary solution, we added the "API: products (table)" widget to the end of the API details page below the details of the operations. The table is hard to access, the user has to scroll a lot. A link on the same page to the bottom is currently not supported with the current hyperlink implementation. If we link to the table at the end of the page, the page is newly loaded and the table is empty. For details refer to ticket #1176 

It is urgent that either the link restriction or this ticket will be resolved as soon as possible to provide an acceptable developer experience.

From the API details page, only a list with references to associated parent APIs is required and a prominent search field and detailed descriptions of the API product. To maintain readability and to not overwhelm the reader with Information only the meaningful name should be displayed in the list.

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
@ZarTrox, that's an omission from our side - thanks for reporting it.
