### ISSUE TITLE
Configuring links on images to image elements - not working as expected

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1179]
## Bug description/expected behavior

Currently, we would like to add references on images to themselves to allow the user to open the image in a higher resolution when clicking on the image - either in the same or in an additional browser tab.

**Case 1:**

Current behavior:
1. Add an image widget and select an image in the editor mode.
2. Configure the image widget by selecting a hyperlink from the image gallery.
The link information is correctly displayed in the "link to" field.
![image](https://user-images.githubusercontent.com/58420097/110452031-10945000-80c5-11eb-80ea-9908aa61811f.png)
3. Click save
4. Refresh the page in editor mode.
5. Open the configuration dialogue of the image widget again.
The link information disappeared from the "link to" field.
6. Publish DevPortal.
7. Open DevPortal in reading mode.
8. Navigate to the page and click on the image.
Image is downloaded from the browser.

Expected behavior:
- After configuring the image link, the link information is still visible in configuration dialogue after refreshing the page.
- Depending on the configuration, when clicking on the image, the image is zoomed out or opened on the same page or in a new browser tab card.

In this context, see also ticket #1123.

**Case 2:**

Current behavior:
1. Add an image widget and select an image in the editor mode.
2. Keep the "link to" field empty.
3. Click save.
4. Publish DevPortal.
5. Open DevPortal in reading mode.
6. Navigate to the page and click on the image.
Image is NOT downloaded from the browser.

Expected behavior:
- Works as expected.

---

As a current work around for the cases that are described above, the user has to open the context menu for the image to "Open image in new tab". Please refer to the expected behavior for the first case above. Could you please fix the issues to ensure that clicking on an image works as expected and does not download the image.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Chrome
 - Version: 88

**Comment by azaslonov** [comment]
Hi @ZarTrox, there is a "Popup" feature in development (ETA April), which will also open up the "Lightbox" feature for showing images in higher resolution (just like you described). However, we can also add an option to specify "download" vs "open" action (as soon as next release) for images and video files. Which one would you prefer (lightbox or action option)?

**Comment by AnRei123** [comment]
Hi Alex, 
many thanks for your question above. Here my answers and further questions.

1a) the "Lightbox" feature sounds very promising. Need to see how it will be finally implemented and how this works for the user. A pop-up would do.
1b) It would be great if the maximal resolution to display could be restricted for dedicated images with a low image resolution in max px or max percent. How do you plan to calculate the max. size of the image in the pop-up window? Do you consider the file size? Or how do you plan to do this?
2) Download of images or videos is currently not required from our side. It is more the opposite that it would be great if there would be a configuration option that prevents downloading images or videos via the context menu items in the browser to protect our intellectual properties. But I know that if someone likes to copy the image, he/she can do. So no actions required here from our side.
3) Would be good if the features that are offered in the GUI of configuration window for images would finally work as expected acc. to the functions that are displayed in an intuitive and robust way.

I am looking forward to view the new "lightbox" feature as soon as possible.

**Comment by azaslonov** [comment]
Hi Angelika (@AnRei123),

1a) I knew you'll like it :)

1b) These are good pointers to think about. Initially, I thought of the popup/lightbox as a separate piece of content, no matter how it gets triggered (picture, button, or anything else). So, that content could just have a separate, higher resolution image in it. This gives you full flexibility, but maybe we can come up with something to reduce the number of clicks to configure it, we'll see.

2) Understood. So, we'll just add the option I mentioned (next release).

3) Yep, found broken cases and working on the fixes (release after next one).

**Comment by azaslonov** [comment]
Update: Popups concept is ready and coming in the next release. Meanwhile, the "Download" option is now available for media files:

![image](https://user-images.githubusercontent.com/2320302/114276922-ac272200-99dd-11eb-84d9-90eea60df7da.png)

**Comment by AnRei123** [comment]
Looks good. Thank you very much. But there are still some new issues in the designer mode as of last Friday.

# Observations in the in the editor mode

 The images are not displayed anymore on the pages, nor as a preview in the media gallery as depicted in the following screenshots.
1)
![Image_place_holder_icon_on_page](https://user-images.githubusercontent.com/58981351/114345918-dd7d2a80-9b62-11eb-94f0-5efb98b99f2a.PNG)
2)
![Image-widget-empty](https://user-images.githubusercontent.com/58981351/114345933-e66dfc00-9b62-11eb-9742-3c70c375cb4a.PNG)
3)
![Media-gallery-no-preview](https://user-images.githubusercontent.com/58981351/114345939-e968ec80-9b62-11eb-880e-e564a18fe184.PNG)
---
- It seems that not only one instance is affected. I just looked it up for two of our instances. Both show these issues.
- In the editor mode, it seems that the information is lost which image should be displayed within an image widget.
- But even if you reconfigure the image widget, the image is not displayed on the editor page and in the dialogs, there is no preview of the image.
- With the current issue, your are not able to add new images and to check in editor mode if the size fits on the page.

#Observations in the published mode
- The images are properly displayed as originally configured.
- The corrected and new functions seem to work.
- For the setting "Open in the same window", I miss the light box that can be closed or at least a close icon or button.  To go back with the current implementation, you need to use the back button of the browser window instead. This is not very comfortable. But it the configurations seem to work now according to their meaning. Also the new download option, seems to work as expected.

**Comment by azaslonov** [comment]
Hi @AnRei123, I tried to reproduce it on one of your services, but could. It might be temporary (known browse cache issues), but if it's not, please send us the names of affected services.

The lightbox is not there yet. First we'll roll out the support for popups (next release), then the lightbox will follow as an extension feature on top of it (probably a release or two after that).

**Comment by AnRei123** [comment]
Today, the images are correctly displayed again in my editor environment.

**Comment by azaslonov** [comment]
I think we're good to close this particular item. I remember about image lightboxes though :)
