### ISSUE TITLE
Additional "API: details" widget configurations

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1180]
## Feature request

Currently on the API details page the API detail description is shown in complete length

But if the description is very lengthy then the text takes the focus and a big part of the screen from the API operations away. While the description is an important part of the API it is not always necessary, especially if you visit the API details page of an API multiple times or browse through the operations.
While the API operation details feature "Automatically scroll to operation name" is applicable for browsing the operations but scrolling to the operation every time without presenting the description for first time users at least once is not suitable.

To ensure that the description is visible but not "in the way" the "API: details" widget configuration should look like this :
- Link to API changelog page (currently present)
- Collapse after number of lines: [Number]
- Extend all lines for first operation [Check box]

---

Collapse after number of lines:
The editor should be able to set a maximum amount of lines in the editor mode of the DevPortal which are displayed in the published version of the DevPortal when the text is collapsed.

If the description is collapsed the string "show more"/"more" should be shown (see first image) to manually show the complete description.
If the description is extended the string "show less"/"hide" should be shown (see second image) to manually collapse the description.

In the first image the maximum amount of lines would be set to "6".

---

Extend all lines for first operation:
The API description should be extended on the first operation of an API if this option is checked.
It is crucial for the users to notice the description the first time they visit an API. Since the users are directed to the first operation when opening an API the description should be extended.

In this case it should look like the second image with extended text on the first operation.
If one switches to any other operation it should collapse automatically and look like the first image.

## Images

First image:
![Overview-Operation02](https://user-images.githubusercontent.com/58420097/110464018-eb0e4300-80d2-11eb-8b30-4b16c6f7791e.png)

---

Second image:
![Overview-Operation01](https://user-images.githubusercontent.com/58420097/110462536-1e4fd280-80d1-11eb-801c-af153530fbfe.png)

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
