### ISSUE TITLE
Graph display on the reports page of the Developer Portal

### ISSUE THREAD

**Issue by to-ogawa** [Azure/api-management-developer-portal#1182]
## Description
There seems to be a difference in the behavior of the graph display in the API Management's Developer Portal reports page.

## Reproduction steps
1. Go to 'The reports page of the Developer Portal'

## Conditions of occurrence
1. If there is no data to be displayed in the graph area.

## Differences that occur (browser is the latest version of Chrom)
1) Only the frame of the graph is displayed, not the graph inside.
![121020526000108_3](https://user-images.githubusercontent.com/77475347/110731635-09587800-8266-11eb-9c20-b27952e36c9d.png)
2) The frame of the graph itself is not displayed.
![121020526000108_2](https://user-images.githubusercontent.com/77475347/110731649-12494980-8266-11eb-8768-674b1dfe2c8b.png)
The above two patterns seem to exist.

There are many factors, and we have not been able to narrow down a clear cause of the outbreak.
We are not certain which is the correct behavior, but we think it is better to have a constant graph representation when there is no data, and we would like to see this improved.

**Comment by khigashi1021** [comment]
@mikebudzynski, My customer and I are also facing same issue. Do you have any plan to fix it?
