### ISSUE TITLE
Error on mouse hover on graph area of reports page in Developer Portal

### ISSUE THREAD

**Issue by to-ogawa** [Azure/api-management-developer-portal#1183]
## Description
An error occurs when hovering the mouse over the graph area displayed in the API Management's Developer Portal reports page.

## Reproduction steps
1. Go to 'The reports page of the Developer Portal'
2. Hovering the mouse over the graph area

## Errors that occur
1) A JavaScript error will be output to the console.
   Error Description [Uncaught TypeError: d3.mouse is not a function]
2) This is not a harmful error, however, a black rectangle will appear in the lower left corner of the graph.
![121020526000108_1](https://user-images.githubusercontent.com/77475347/110732165-f72b0980-8266-11eb-80f9-e278513510f3.png)

※ Browser is the latest version of Chrom

The above two cases do not seem to cause any actual damage to the displayed graph information itself, but we would like to see this improved.

**Comment by azaslonov** [comment]
Hi @to-ogawa, thanks for reporting the issue, we'll fix this.
