### ISSUE TITLE
The API page Menu is not in alignment when we resize the web page 

### ISSUE THREAD

**Issue by dmancine9** [Azure/api-management-developer-portal#1184]
The API page Menu are not in alignment when we resize the web page to half of the window.

Steps to reproduce:
1. Login to SIT Developer Portal
2. Navigate to the API page
3. Resize the webpage to hlf of the window
4. Verify the content in the page

Expected: The page should adjust the content as per the selected size

Actual:
![APIs_Misaligned](https://user-images.githubusercontent.com/80485059/110845265-69581a00-8278-11eb-9e42-906720b54295.PNG)

**Comment by azaslonov** [comment]
Hi @dmancine9, thanks for reporting the issue, we'll fix this.

**Comment by azaslonov** [comment]
Fixed in the previous release (please re-publish if you haven't done so yet). Please feel free to re-open shall you still can repro it.
