### ISSUE TITLE
Republishing portal (for new version) broke images

### ISSUE THREAD

**Issue by adamstruck** [Azure/api-management-developer-portal#1186]
Republishing my portal (to update to latest version) resulted in broken image links and javascript errors in console.

## Is your portal managed or self-hosted?

Managed

## API Management service name

acmeaom-dev

## Environment

 - Operating system: macOS
 - Browser: Google Chrome, Safari

## Additional context

![image](https://user-images.githubusercontent.com/5560701/110976853-48de9d00-8316-11eb-9a72-ec18df628bf0.png)

Console errors:
```
(anonymous) @ theme.js:2
(anonymous) @ theme.js:2
__awaiter @ theme.js:2
trackError @ theme.js:2
handlerError @ theme.js:2
error (async)
exports.UnhandledErrorHandler @ theme.js:2
exports.resolveInstance @ theme.js:2
(anonymous) @ theme.js:2
(anonymous) @ theme.js:2
(anonymous) @ theme.js:2
exports.resolve @ theme.js:2
(anonymous) @ theme.js:2
Container._get @ theme.js:2
Container.getAll @ theme.js:2
Collection @ theme.js:2
exports.resolveInstance @ theme.js:2
(anonymous) @ theme.js:2
exports.resolve @ theme.js:2
(anonymous) @ theme.js:2
Container._get @ theme.js:2
Container.get @ theme.js:2
resolve @ theme.js:2
(anonymous) @ theme.js:2
```

Pulling in data from a backup didn't fix the issue, nor did deleting the affected images in the admin UI and re-uploading them. Any ideas?

**Comment by adamstruck** [comment]
Note: everything looks fine in the admin UI while editing the site.

**Comment by azaslonov** [comment]
Hi Adam, nope, no ideas. I just sent you an email with follow-up questions, since this looks like a service-specific thing.
