### ISSUE TITLE
Menu isn't visible in mobile browsers

### ISSUE THREAD

**Issue by VickiFu** [Azure/api-management-developer-portal#1187]
Hi API management prod team,
I know that people should mostly use dev portal from desktop and web browser. What I noticed that when you login to dev portal with your phone browser. You cannot see sandwich menu Icons to browser your product or API detail. Please add that menu icon and menu for the mobile browser.
Thanks

**Comment by azaslonov** [comment]
Hi @VickiFu, yes, known issue, we're working on it.

**Comment by ArkimeraMattias** [comment]
Any update on this issue?

**Comment by chaosity-io** [comment]
Hey Guys,

can someone look at this issue again. I am using managed API gateway portal and menu for mobile doesn't show anything. I suppose the managed portal must use the latest code. But I still see the issue. If it is fixed in the tag 2.25.0 and it is not pushed to the production please let me know. Otherwise please fix the issue.

**Comment by malincrist** [comment]
Hi @chaosity-io , the issue has been fixed and is part of release 2.25 which was not deployed yet in all the regions for managed portals. Please wait a few more days for the deployment to reach all stages.

**Comment by malincrist** [comment]
@chaosity-io , just to confirm, do you not see the hamburger icon at all or is it black and not visible over the background?

**Comment by chaosity-io** [comment]
I see the button but when I click on it in the mobile version of the
websites it shows me a white screen and no navigation icons/buttons are
visible.

**Comment by malincrist** [comment]
From what I understand, this issue was opened because the hamburger menu was not visible at all, not that the opened menu doesn't show the text. I saw that you opened a different issue #2394  and have answered there to your question.

**Comment by chaosity-io** [comment]
Yes I opened the ticket.

I already reset my content a couple of times and the white screen persists.

Is there a fix for mobile version of the menu in 2.25?
