### ISSUE TITLE
Nested dictionary not displaying in 'Table view' for definition schema on developer portal

### ISSUE THREAD

**Issue by sykesjd** [Azure/api-management-developer-portal#1191]
## Bug description

In the event a dictionary field (i.e. an `object` type property with only `additionalProperties` specified, per [this specification](https://swagger.io/docs/specification/data-models/dictionaries/)) is present in a definition schema for an API as a field on a nested object or array (i.e. not as a top-level property of the schema object), the property will be missing from the 'Table view' for the schema on the developer portal for the APIM instance. The property can be viewed if 'Raw schema view' is selected, only 'Table view' presents the problem.

## Reproduction steps

1. Under an APIM instance in Azure Portal, go to 'APIs'.
2. Select an API from the left side bar of the resulting pane.
3. Select 'Definitions'.
4. Select '+ Add definition'.
5. Give the definition any name.
6. Paste the sample definition below into the 'Payload' field.
7. Select 'Create definition'.
8. Select 'Operations'.
9. Select '+ Add operation'.
10. Give the operation any name, verb, and URL.
11. Add a definition for a request body or response body using the definition created in steps 4-7.
12. Select 'Save'.
13. In a new tab, navigate to the API Details page for the API in the APIM instance's developer portal.
14. Select the new API endpoint.
15. Scroll down to the table view for the definition schema.

Sample definition:
```
{
    "type": "object",
    "properties": {
        "SomeProperty": {
            "type": "string",
            "description": "Standard property"
        },
        "AdditionalDetails": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            },
            "description": "Additional properties"
        },
        "SomeObject": {
            "type": "object",
             "properties": {
                 "SomeNestedProperty": {
                     "type": "string",
                     "description": "Standard nested property"
                 },
                 "AdditionalObjectDetails": {
                     "type": "object",
                     "additionalProperties": {
                         "type": "string"
                     },
                     "description": "Additional object properties"
                 }
             }
        },
        "Items": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "SomeItemProperty": {
                        "type": "string",
                        "description": "Standard array item property"
                    },
                    "AdditionalItemDetails": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        },
                        "description": "Additional array item properties"
                    }
                }
            }
        }
    }
}
```

## Expected behavior

The following properties are listed in the Table view:
- `SomeProperty`
- `AdditionalDetails`
- `SomeObject.SomeNestedProperty`
- `SomeObject.AdditionalObjectDetails`
- `Items[].SomeItemProperty`
- `Items[].AdditionalItemDetails`

## Actual behavior

The following properties are listed in the Table view:
- `SomeProperty`
- `AdditionalDetails`
- `SomeObject.SomeNestedProperty`
- `Items[].SomeItemProperty`

Both `SomeObject.AdditionalObjectDetails` and `Items[].AdditionalItemDetails` are missing from the Table view (note that `AdditionalDetails` is _not_ missing).

## Is your portal managed or self-hosted?

Managed

## API Management service name

`qa-resku-rga-apim`
Offending definition is `AddItemsToBoxOperation` for "Add Items to Box" endpoint
Custom domain for portal: https://qa-rga-docs.reskureturns.com/

## Environment

 - Operating system: Windows 10 (latest)
 - Browser: Google Chrome, Microsoft Edge
 - Version: 89, 89 (respectively)

**Comment by azaslonov** [comment]
Hi @sykesjd, thanks for reporting the issue, we'll try to repro and fix.

**Comment by Radamonas** [comment]
We noticed this behavior as well.
