### ISSUE TITLE
Developer portal doesn't respect open api schema title property

### ISSUE THREAD

**Issue by t-higgs-qa** [Azure/api-management-developer-portal#1192]
## Bug description

Currently, the azure dev portal displays unfriendly names for request objects which are not generated from references types when generated from OpenAPI specs.

## Reproduction steps
Generate an API using OpenAPI similar to the following (truncated for brevity):
```
"requestBody": {
  "description": "An example request",
  "content": {
    "application/json": {
      "schema": {
        "title": "MyRequestSchemaTitle",
        "type": "array",
        "items": {
          "enum": [
            "First",
            "Second",
            "Third",
            "Fourth"
          ],
          "type": "string"
        }
      }
  },
```

Then the resulting definition is created in the apim:
![image](https://user-images.githubusercontent.com/58445030/111539845-5e036380-873c-11eb-97bd-800a2f30bd8d.png)
Finally the following is output in the developer portal:
![image](https://user-images.githubusercontent.com/58445030/111540425-22b56480-873d-11eb-9bc4-7cc48607915b.png)

## Expected behavior

I would expect the title property of the schema definition to be respected resulting in a better experience for consumers of the developer portal. The current implementation outputs a name which is confusing to our clients. 

## Is your portal managed or self-hosted?

Managed

## API Management service name

dev-apim-qes-w

## Environment
N/A

**Comment by azaslonov** [comment]
@VitaliyKurokhtin, @harunrst, I assume this is API import issue?

**Comment by VitaliyKurokhtin** [comment]
Yes, at the moment import disregards title. We'll need to fix it, meanwhile customer is free to alter schema object name after import.

**Comment by cosminstirbu** [comment]
We're interested in a fix for this issue as well.

**Comment by VitaliyKurokhtin** [comment]
@azaslonov import should retain schema as is, so likely not

**Comment by cblakley4** [comment]
Interested in a Fix for this as well.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
