### ISSUE TITLE
Creating or importing api definition with openapi format does not respect custom SubscriptionKey headers

### ISSUE THREAD

**Issue by bszopa-mdg** [Azure/api-management-developer-portal#1194]
Creating or importing API from json file in openapi format ignores value provided in "components/securitySchemes/apiKeyHeader/name" is ignored and always defaults to Ocp-Apim-Subscription-Key.
After creating SubscriptionKey header still can be properly changed via azure portal or Set-AzApiManagementApi powershell call.

Behaviour is same for both independently created jsons and files that are result of Export API OpenAPI vs (JSON) function on azure portal API Management service page. 
Behaviour is same for both creating/importing api via azure portal or creating api via powershell and ARM template deployment.

Example reproduction steps:
1. Import api using json file attached to this issue
[HelloThere.openapi+json.json.zip](https://github.com/Azure/api-management-developer-portal/files/6172310/HelloThere.openapi%2Bjson.json.zip)
2. Manually change SubscriptionKey header to some other value than "Ocp-Apim-Subscription-Key" via azure portal
![image](https://user-images.githubusercontent.com/75282096/111803509-663fd800-88cf-11eb-8aff-34609aaf0ed5.png)
3. Export api using OpenAPI v3 (json) format
4. Reimport api using file created in step 3.

Expected behaviour:
SubscriptionKey header has value set in step 2. 

Actual behaviour:
SubscriptionKey header has value "Ocp-Apim-Subscription-Key"

**Comment by mikebudzynski** [comment]
@bszopa-mdg, the imported OpenAPI file describes configuration of the backend API, not the API that will be exposed through API Management. In particular, security information would be understood by API Management as security for communicating with the backend service. In future, we may provide extension properties to express API Management's configuration in the OpenAPI file, but we don't have this improvement on the immediate roadmap. You can programmatically access the header setting using the REST API or ARM templates.
