### ISSUE TITLE
Activating text field for editing often not possible

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1198]
## Bug description [sporadic issue - not reproducible]

We frequently edit content on several pages and require fluently working editing capabilities of the DevPortal.

Often, when we switch between different pages and click on several text fields to activate the edit mode by clicking once or double-click, the editing mode is not activated - even after several trials. Instead, multiple error messages are displayed and often the text-field is moved to another location on the same page. 

We also observed that in some of these cases the text format panel is not completely displayed. Only parts of it, like in the following image shown.
![image](https://user-images.githubusercontent.com/58420097/112131481-e3b66180-8bc9-11eb-8308-5454c0f97660.png)

The issues happens to different elements over time and is not dedicated to specific elements (after looking into the JSON it was the same as other sections on the same and on other pages).

## Expected behavior

After clicking the second time on a text field the editing mode of the text field is activate and the text format panel completely appears.

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
@AnRei123 fyi

**Comment by ZarTrox** [comment]
![image](https://user-images.githubusercontent.com/58420097/113257606-2283a000-92cb-11eb-9be0-96b11a7abc06.png)

Is this enough?

**Comment by azaslonov** [comment]
Hi @ZarTrox, yes, thank you. This issue has been fixed in the ongoing release.

**Comment by azaslonov** [comment]
@ZarTrox, the issue should be gone now. Can you please confirm?

Closing for now, please re-open if it still appears.
