### ISSUE TITLE
Error Publishing wasn’t - Please ensure that Authorization header contains valid token.

### ISSUE THREAD

**Issue by aizefler** [Azure/api-management-developer-portal#1204]
## Bug description

We are unable to publish the Developer Portal content within Azure APIM Instace DEV. We received the error in the Azure Notifications status "Publishing wasn't scheduled - Please ensure that Authorization header contains valid token.".

For knowledge we went back to a backup and after that it was no longer possible.

## Reproduction steps

1. Go to APIM instance Azure Portal
2. Click on 'Portal overview'
3. Click on  'Publish'
4. See error "Publishing wasn't scheduled - Please ensure that Authorization header contains valid token."

## Expected behavior

A configuration has been made in the AAD identity provider for login to the Developer Portal, after publication, we hope it will be possible to login to the Portal.

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-ahs-dev-eastus-001

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome]
 - Version: 89.0.4389.90

## Additional context

![image](https://user-images.githubusercontent.com/2823190/112509111-ed2cfe80-8d6e-11eb-8fd4-830ba0416b1f.png)

**Comment by azaslonov** [comment]
Hi @aizefler, yes, this is a known issue, the fix is underway. To work this around you can publish from the developer portal itself.

**Comment by aizefler** [comment]
Hi, @azaslonov, even though we are publishing from the ADMIN Portal, we can't log in and no error message is displayed and we don't know what it could be.

For this reason, we decided to change the identity provider and publish to the Azure Portal itself.

**Comment by azaslonov** [comment]
@aizefler, can you please send me your service name(s) to apimportalfeedback@microsoft.com, I'll speed up the hotfix for you.

**Comment by aizefler** [comment]
Hi @azaslonov, as it is the DEV environment, we have finalized the provisioning of a new instance.

If the problem happens again, I will send you an email.

**Comment by azaslonov** [comment]
Ok, sounds good.

**Comment by azaslonov** [comment]
The fix has been deployed everywhere in public cloud.
