### ISSUE TITLE
Migration script for portal (scripts.v3) - Permission

### ISSUE THREAD

**Issue by rafael-teixeira** [Azure/api-management-developer-portal#1206]
Hi everyone,

I am trying to run the script (scripts.v3) to migrate APIM portal content from one subscription to another. In this way, I've created an az service principal with "Reader" role in APIM (source) and an az sp with "Contributor" role for APIM (destination) but it is falling with following message:

```
node ./migrate --sourceSubscriptionId "" --sourceResourceGroupName "" --sourceServiceName "" --sourceTenantid "" --sourceServiceprincipal "" --sourceSecret "" --destSubscriptionId "" --destResourceGroupName "" --destServiceName "" --destTenantid "" --destServiceprincipal "" --destSecret ""
Exporting...
Unable to complete migration. Unable to complete export. Unable to download media files. Looks like you are not allowed to perform this operation. Please check with your administrator.
```

I've checked and it's falling to run the following line of the code (post to get sastoken?):

```
utils.js:345
    async getStorageSasUrl() {
        **const response = await this.httpClient.sendRequest("POST", `/portalSettings/mediaContent/listSecrets`);**
        return response.containerSasUrl;
    }
```

Please, does anyone know which are the roles and scopes (permissions) required to run that migration considering the least privileged concept under the services principals (source and dest)?

**Comment by mikebudzynski** [comment]
This script requires access to this endpoint to get storage secrets for saving media files. To use the least-privilege approach, you can create a custom role: https://docs.microsoft.com/en-us/azure/api-management/api-management-role-based-access-control#custom-roles

**Comment by thomasvdb** [comment]
Is it possible to add this to the documentation as it's not really clear at the moment which roles are expected?
https://learn.microsoft.com/en-us/azure/api-management/automate-portal-deployments
