### ISSUE TITLE
How to customise the widget text color

### ISSUE THREAD

**Issue by arrowhead237** [Azure/api-management-developer-portal#1210]
Hi Team,

I am trying to customize the default managed developer portal pages. As part of it, I am trying to change the font color of the text inside the widgets like "Search APIs" (Placeholder), "Search Products" (Placeholder) etc.

I have edited the "Regular" font color under typography in the styles section but this hasn't changed the text color mentioned above. I also am trying to customise the labels / text on the User: Reports page under API Response times. Currently the text is like a dark grey / black.

Thanks

**Comment by mikebudzynski** [comment]
Currently, it's not possible to customize elements inside widgets. I have created an aggregate Issue for such feature requests: #1213

For now, the workaround is to use the self-hosted developer portal.
