### ISSUE TITLE
OpenApi Export definition dropdown not loading: getResourceName throws error when being called by getApisInVersionSet

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#1211]
## Bug description

OpenApi Export definition dropdown and api description are not loading in de details page.

## Reproduction steps

1. Get on the self-hosted 2.7.1 version.
2. Make sure you have at least 2 api's in APIM, each with a seperate version set
3. Open the API at the APIM portal
4. See there is no option to download the OpenApi definition, only the 3 loading dots.
5. When commenting out the `throw new Error("Could not parse ID.");`, in `Utils.ts`, it works just fine. But i'm not sure if this is fixing the issue at the source. 

## Expected behavior

At least some exception handling so that the option to download the OpenApi definition again.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.7.1

## API Management service name

...

## Environment

 - Operating system: Windows
 - Browser: Chrome or Edge
 - Version: 89

## Additional context

Trace:

![image](https://user-images.githubusercontent.com/4255748/112834551-69d61a80-9098-11eb-9f86-94b950e55b1d.png)

**Comment by jsorohova** [comment]
Hello @erwinkramer, thank you for reporting the bug. In order for us to fix it, could you please confirm that the bug still persists and if so, could you please also provide more details for the step 4? Thank you.

**Comment by erwinkramer** [comment]
Hi @jsorohova I'm on an 2.11.x release of the dev portal and I see no issues anymore. I'll close this. Thanks for the reminder.
