### ISSUE TITLE
Link in the confirmation email doesn't work when using delegation

### ISSUE THREAD

**Issue by CoumbaNDI** [Azure/api-management-developer-portal#1214]
We have been using the delegation for a while to connect to the api management and never had any problem but
we have been made aware last week by our users that when they click on the confirmation link of the email after registering that they don't have access to the APIM.
On the back we can see that the state of the users is still pending and not active.

## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. Go to 'developers.xxx.fr'
2. Click on 'Sign up'
3. Sign up
4. Go the adress email and click on the confirmation link " https://developers.xx.fr/confirm-v2/identities/basic/signup?userid=3daf5709-8f3f-4fd7-8334-7ab8558c6a22&identity=xx.xx%40fr.org&ticketid=6061bfc925eff105a0eec3f9&ticket=7c43a903c53641f6aa5789bce6355b79
5. You get send back the same email and it's an infinite loop

On the back we can see that the state is still pending. I've been using the API to modify it from pending to active
## Expected behavior

1. Go to 'developers.xxx.fr'
2. Click on 'Sign up'
3. Sign up
4. Go the adress email and click on the confirmation link " https://developers.xx.fr/confirm-v2/identities/basic/signup?userid=3daf5709-8f3f-4fd7-8334-7ab8558c6a22&identity=xx.xx%40fr.org&ticketid=6061bfc925eff105a0eec3f9&ticket=7c43a903c53641f6aa5789bce6355b79"
5. Get redirected to 'developers.xxx.fr' with a active profile

## Is your portal managed or self-hosted?

Managed

**Comment by ygrik** [comment]
@CoumbaNDI 
could you please provide details on how you create a user, traces from the browser, and your APIM service name to apimportalfeedback@microsoft.com

**Comment by ygrik** [comment]
@CoumbaNDI I found the issue and working on hotfix. 
As a workaround I recommend creating a user with Active status and without notification parameter.
