### ISSUE TITLE
Customize API: List Background

### ISSUE THREAD

**Issue by arrowhead237** [Azure/api-management-developer-portal#1218]
Hi Team,

I am trying to customize the default managed developer portal pages. I have currently made the page background black. When I select the APIs List page and then select an API eg "Authentication" I get taken to API definition and changelog page. When I select "Try it" a window pops up from the right hand side that is currently white. Am I able to customise the background color of this? If so, where would I be able to do this? I have attached a screenshot to show what I am meaning. 

![Untitled-1](https://user-images.githubusercontent.com/81563887/113153750-b0ae4680-9237-11eb-9472-a7ec7eacaa79.png)

Thanks

**Comment by mikebudzynski** [comment]
It's currently not possible to customize the background of the interactive console. We have an improvement planned to resolve this issue: #1213 For now, as a mitigation you can use the self-hosted portal and modify the background in the code.

**Comment by azaslonov** [comment]
Let's track this issue under #1213. Closing this one.
