### ISSUE TITLE
Community: "Issues" functionality not available

### ISSUE THREAD

**Issue by mikebudzynski** [Azure/api-management-developer-portal#122]
If you have questions, comments, or concerns related to *Issues* not being available in the new portal, please post them here.

**Comment by mikebudzynski** [comment]
Related: https://github.com/MicrosoftDocs/azure-docs/issues/38481

**Comment by joeystdio** [comment]
In the new Developer Portal delegation doesn't seem to work anymore. The sign-in and sign-up buttons will always show the built-in pages and not redirect.

**Comment by mikebudzynski** [comment]
@joeystdio Did it stop working or has it never worked? Could you open a separate issue with reproduction steps for tracking?

**Comment by ygrik** [comment]
@joeystdio did you publish portal after saving delegation settings in Azure portal?

**Comment by joeystdio** [comment]
@mikebudzynski actually I've never seen it working correctly. 

@ygrik Indeed when publishing the portal after changing the delegation settings it's somewhat working. But what actually happens is that you first see the built-in register page followed by a  redirect to the delegation URL.

**Comment by ygrik** [comment]
@joeystdio 
yes, this is the designed flow. The built-in register page load and check is the delegation enabled and redirect to the delegationURL

**Comment by joeystdio** [comment]
> @joeystdio
> yes, this is the designed flow. The built-in register page load and check is the delegation enabled and redirect to the delegation URL

Wow, that's pretty ugly. Why not the same redirect as in the old developer portal? Why show a page first.

**Comment by ygrik** [comment]
@joeystdio
We are working to move this logic to the backend in the nearest future.

**Comment by mikebudzynski** [comment]
Thanks for your feedback @joeystdio 

I'll be removing the comments from this thread because they are completely unrelated to this Issue. Please continue the conversation in #326

**Comment by joeystdio** [comment]
@mikebudzynski Thanks for moving the comments to a new issue. The fact that there is functionality no longer working as before sounded to me like "functionality not available".

**Comment by dfjones91** [comment]
Will "issues" be added as a widget for the new developer api? My company is using the old one and want to continue using it in the new one

**Comment by mikebudzynski** [comment]
> Will "issues" be added as a widget for the new developer api? My company is using the old one and want to continue using it in the new one

We don't have immediate plans to add a widget for Issues in the new portal. Could you please describe how and why you use Issues and if you've considered third party services for managing issues / tickets?

**Comment by lucaszacutti** [comment]
Regionalization/Multi language: we are implementing a self hosted portal and we are not sure what approach follow in order to not go in an opposite approach from a future out-of-the-box implementation.

**Comment by azaslonov** [comment]
Multi-language content is a planned feature and coming at some point in April. No specific date though.

**Comment by mikebudzynski** [comment]
Archiving the issue due to lack of activity
