### ISSUE TITLE
Template parameters appended into query in apim dev portal

### ISSUE THREAD

**Issue by brdjukic** [Azure/api-management-developer-portal#1221]
## Bug description

Dev portal UI correctly displays path parameter in 'Template parameters' list, but when it's filled out, the value is not placed into the path placeholder of the Request URL, but instead it gets appended as a query parameter.

![image](https://user-images.githubusercontent.com/50868342/113285280-13ace580-92eb-11eb-92b8-6104f460ed51.png)

## Expected behavior

The correct result in Request URL should be:
.../installations/123

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: latest

**Comment by azaslonov** [comment]
Hi @brdjukic, thanks for reporting the issue, we'll fix this.

**Comment by azaslonov** [comment]
We have scheduled a work item for the Azure portal team, ETA is around 3 weeks.
I'm closing this issue because it's not related to the Developer portal project.
