### ISSUE TITLE
Subscription Key in "Try It" should be masked by default

### ISSUE THREAD

**Issue by ankrause** [Azure/api-management-developer-portal#1224]
I didn't see an existing issue for this, which is surprising so apologies if I missed it -

In the new developer portal's "Try It" pane for an API, the subscription key is shown in plain text for both the headers section as well as the "HTTP request" section. These (IMO) should be masked by default.

This is also a degradation of functionality from the deprecated portal which does mask the subscription key in both locations by default.

I also didn't see a setting that would allow me to change this functionality in the new portal, again sorry if I missed it, but a quick search didn't turn up anything obvious.

**Comment by azaslonov** [comment]
Hi @ankrause, yes, I agree. We'll fix this.

**Comment by ankrause** [comment]
This was resolved by #1436
