### ISSUE TITLE
Scripts v2/v3 documentation

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1226]
Hi!

Currently there are two different scripts folders. Scripts.v2 and Scripts.v3. I didn't find a description/documentation and [https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services](https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services) does not discuss Scripts.v3.

Naturally one would think that v3 is newer and is apparently ARM-based (I'm not proficient in this approach) but the two versions seem to co-exist.

Is there a way to identify which version of the scripts one should use?
Is there any other distinguishable difference? 
Is there any documentation on which one is suited for which situation, the scope of the scripts or prerequisites needed?
And will they both remain functionally in foreseeable future or will one get deprecated?

Thank you in advance!

**Comment by mikebudzynski** [comment]
> Is there a way to identify which version of the scripts one should use?

We're working on documentation.

>  Is there any other distinguishable difference?

No. v3 are using ARM instead of direct access API. v3 doesn't yet support automated publishing of the managed developer portal (coming soon).

>  Is there any documentation on which one is suited for which situation, the scope of the scripts or prerequisites needed?

We recommend using v3, since the ARM approach is more secure.

> And will they both remain functionally in foreseeable future or will one get deprecated?

We will be maintaining v3 only going forward, but they both will continue to work with the existing API versions.

**Comment by AnRei123** [comment]
Hi Mike, for v3, do you still support the possibility to download, upload and publish the content and media files in three separated steps? This would be very important to us for the following reasons:
1) We like to archive the files in our repository before deploying to other environments.
2) We automatically modify some content in the data.json to get environment-specific contents (variant management) before we deploy it to other environments. 
I wonder if you still support these use cases with the current v3 scripts. Do you?
