### ISSUE TITLE
Hyperlink Injection due to No Special character restriction on Name fields while signing up in the developer portal

### ISSUE THREAD

**Issue by CosminLazar** [Azure/api-management-developer-portal#1228]
## Bug description

Hi, I noticed that while signing up at the developer portal there is no restriction for the name field, Any special character or URL , as well as scripts are accepted in this field. Through html and javascript is sent as plaintext, However links are hyperlinked in the  email templates.

An attacker can use victims email on sign up page , where he gives URL's in the first and last name fields. So, When it arrives to victim the URL will be hyperlinked , on clicking it victim may get redirected to a malicious site.

## Reproduction steps

1. Go to any developer portal signup page.
2. Enter your email , password
3. In the first name field give http://www.evilsite.com.
4. When the confirmation mail arrives for activating account the URL will be hyperlinked.

## Expected behavior

The url supplied in the firstName and made available in the notification template via the $DevFirstName should not be hyperlinked.

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-bilinfo-prod

## Environment

Environment agnostic

**Comment by azaslonov** [comment]
Fixed on the backend, awaiting deployment.
