### ISSUE TITLE
Deployment strategy - questions

### ISSUE THREAD

**Issue by kaylakirzinger** [Azure/api-management-developer-portal#123]
What is the recommended approach for deploying the development portal? We are having the following issues (in general for APIM deployment):

- git repo includes swagger json (not reference to swagger json) so it overwrites pipeline changes. i.e. if we save to repo, deploy API code, and then deploy repo back to APIM, all swagger changes are overwritten

- as such, can't use the repo to deploy the developer portal (or will overwrite changes from pipeline). 

- the only solution I can see is to save to repo, update swagger json manually to what was deployed, then re-deploy in each environment?

What is the suggested approach to deploy portal changes through environments?

**Comment by mikebudzynski** [comment]
@kaylakirzinger 

**Regarding general API Management deployments**

What do you mean by pipeline? What swagger changes are overwritten? Would using the tools from our dev-ops resource kit help? You can find them at http://aka.ms/apimdevops

It would be helpful, if you could give us an example.

**Regarding developer portal deployments**

We're still working on finalizing our story on the portal dev-ops and evaluating if we can align the process with the dev-ops resource kit available at the link above.

For now, you can script the deployments and migrations between environments using APIs, which are described [in the wiki section](https://github.com/Azure/api-management-developer-portal/wiki/Content-management-REST-API).

We also prepared [a sample script](https://github.com/Azure/api-management-developer-portal/blob/master/scripts/migrate.bat) to help you get started. We'll be documenting it soon - Issue #124 for reference.

**Comment by kaylakirzinger** [comment]
Thank you for the sample script, much appreciated. 

If I can deploy the portal without deploying the entire APIM instance we should be fine.

I think your tools should help - we were using home-grown deployment pipeline steps that were not working correctly apparently. 

Thanks!

**Comment by mikebudzynski** [comment]
Regarding portal-specific DevOps - we have just extended our documentation: https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services and provided more comments in the script to make it easier to understand.

**Comment by molinch** [comment]
@mikebudzynski it seems like new portal templates aren't saved to Azure git
Is it normal?

**Comment by mikebudzynski** [comment]
Yes, they are not part of the DevOps repository or ARM templates.

**Comment by TravisLRiffle** [comment]
Have you finished your deployment strategy?  We want to create a standard Azure devops build and release pipeline around this and I'm looking for guidance on the best approach for this.

**Comment by SSanjeevi** [comment]
@mikebudzynski  Same question - Have you finished your deployment strategy? We want to create a standard Azure devops build and release pipeline around this

**Comment by mikebudzynski** [comment]
We currently recommend using `scripts/migrate.js` for DevOps; there are detailed instructions inline in the script and in the Wiki section of the repository.

In the coming months, we are planning to move the administrative plane of the portal to ARM (Azure Resource Manager). No ETA at this moment.
