### ISSUE TITLE
Original response status message is not returned

### ISSUE THREAD

**Issue by martinsamanek** [Azure/api-management-developer-portal#1235]
## Bug description

Response status message in the console is set based on status code instead of real message in response 

## Reproduction steps

1. Go to developer portal
2. Click on APIs and select an API
3. Try it and send a request
4. Check response

## Expected behavior

If a status message is provided within the status code, it should be visible

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.7.1

## API Management service name

apimoridev

## Environment

Environment agnostic

## Additional context

Current behavior:
![image](https://user-images.githubusercontent.com/43401497/114054247-fa2e0f80-988f-11eb-8083-b910d6074457.png)

Deprecated portal behavior:
![image](https://user-images.githubusercontent.com/43401497/114054364-192ca180-9890-11eb-85ab-ad8310afcbcc.png)

https://github.com/Azure/api-management-developer-portal/blob/276ccd376915213620f20dd931cbedb2b0b551f6/src/components/operations/operation-details/ko/runtime/operation-console.ts#L516
I tried to use `response.statusText` but it seems to be empty.

**Comment by azaslonov** [comment]
Makes sense. We'll fix this.
