### ISSUE TITLE
Username and Password identity provider allows hyperlinks in name fields

### ISSUE THREAD

**Issue by velsietis** [Azure/api-management-developer-portal#1243]
## Bug description

The sign up form can be hijacked to send out malicious links in the invitation email.

## Reproduction steps

1. In identities ensure "Username and Password" is selected
2. Go to  `/signup` in the developer portal
3. For First Name enter: `user, please verify yourself here: https://malicious.link`
4. For Email enter the intended recipient of the malicious link
5. The recipient receives an email with the first line "Dear user, please verify yourself here: https://malicious.link"

## Expected behavior

That hyperlinks in the name fields will fail validation on the server side and the sign up request will be rejected with an explanatory error message

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

9f8cc5

## Environment

 - Operating system: Windows 10
 - Browser: Edge (Chromium)
 - Version: 89

**Comment by azaslonov** [comment]
Thanks for reporting the issue, we'll fix this.

**Comment by mikebudzynski** [comment]
Cross-referencing #1228

**Comment by azaslonov** [comment]
Fixed on the backend, awaiting deployment.
