### ISSUE TITLE
Blurry text in images after re-sizing

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1244]
## Bug description

Currently when inserting images containing text, no matter the size of the image, the text will get blurry quickly while adapting the size of said image.

This does not happen when resizing outside of the portal e.g. PowerPoint:

https://user-images.githubusercontent.com/58420097/114531629-5dcb8a80-9c4c-11eb-8d5e-ea84a13f433e.mp4

As you can see here the text is easily readable.

On the other side this is the resolution in the Portal. 
Even though it is just a screenshot I hope my point in visible:
![Comparison](https://user-images.githubusercontent.com/58420097/114532403-1a255080-9c4d-11eb-89d7-b9c2088b2194.png)

The Screenshot was taken from the published DevPortal and put next to the other image in PowerPoint.

## Expected behavior

Text is still readable even if you adapt the size of an image.

## Is your portal managed or self-hosted?

Managed

----
@AnRei123

**Comment by azaslonov** [comment]
Hi @ZarTrox, unfortunately, we cannot control things like this, it is browser rendering implementation, which obviously different from PowerPoint. What I would recommend is to use a bigger-resolution picture and force it into a smaller size using Picture Editor settings. If you open the F12 console in your browser and type `window.devicePixelRatio`, you'll see what ratio you may want to keep between the uploaded picture and in-browser picture. Also, when you upload the picture right from the Picture Editor it will try to set this ratio automatically for you.

Hope that helps.
