### ISSUE TITLE
V3 : Migrate: Publish portal 

### ISSUE THREAD

**Issue by geiyer** [Azure/api-management-developer-portal#1246]
## Bug Description

I was able to use Ver#3 Migration Script with my own step to "Publish" using the portalRevision endpoint. I noticed that with this [commit] 
(https://github.com/Azure/api-management-developer-portal/commit/6211dbd4ee7c443cf7d621be7ea88227a67758bb)
my job started failing. 

I do see the following error message in my pipeline:

_Unable to schedule website publishing. Could not complete request to https://management.azure.com/subscriptions/<subscriptionid>/resourceGroups/<resourcegroup>/providers/Microsoft.ApiManagement/service/<apimservice>/portalRevisions/20210413134542?api-version=2020-06-01-preview. Status: 202 Accepted_

I notice that I do get back a 202 and notice that the dev portal content does get published. However, it breaks the build. 

## Expected behavior

The AZ devops build should not fail. 
 
## Is your portal managed or self-hosted?

Managed 

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
Fixed in #1242.
