### ISSUE TITLE
Implement rendering of top-level "allOf" definition as a combination of properties of enumerated definitions

### ISSUE THREAD

**Issue by azaslonov** [Azure/api-management-developer-portal#1248]
We should be able to properly render "allOf" combination in API documentation, so that schema like:
```
SomeObject:
   allOf:
      $ref: '#/components/schemas/SomeChildObject'
      type: object
      properties:
         propertyA:
           type: string
         propertyB:
            type: string

SomeChildObject 
   type: object
   properties:
      propertyX:
         type: string
```

Would be rendered as if we had object like:
```
SomeObject 
   type: object
   properties:
      propertyA:
         type: string
      propertyB:
         type: string
      propertyX:
         type: string
```

![image](https://user-images.githubusercontent.com/2320302/114634037-8f594b80-9c76-11eb-9144-69e4d6d0edf4.png)

**Comment by cosminstirbu** [comment]
@jsorohova - I've noticed you've closed this issue (and the related bug https://github.com/Azure/api-management-developer-portal/issues/1366) . However, it seems that it is still reproducing.

Have the changes actually been deployed?

**Comment by cosminstirbu** [comment]
This is how it looks on our end (disregard Tenant-tenant-Analyze-syncPostRequest which is tracked via https://github.com/Azure/api-management-developer-portal/issues/1192)
![Screenshot 2022-03-15 at 15 25 42](https://user-images.githubusercontent.com/7135690/158387493-cf815c5a-6bd6-4bac-a561-89ce504c3a08.png)

**Comment by cosminstirbu** [comment]
Is there a private way to do that?

**Comment by jsorohova** [comment]
You can email me at jsorohova@microsoft.com
