### ISSUE TITLE
Page-level access rights 

### ISSUE THREAD

**Issue by Norgaard13** [Azure/api-management-developer-portal#1251]
First things first, thanks for your work. This product is great

I have added the developer portal to support the description of the code-generated API management setup. 

Within the API management setup i can restrict access to the services for users and/or user groups.  As an example, Users A only have access to API Services 1,2,3, whereas User B only have access to API Services 3,4,5
This works great. 

**The question is: ** 

Is it possible to restrict the same users/user groups to browse only certain Portal Content pages? 
For example, if we have a page A and want to give access to User A only to see that page. 

Example 

Front-page - 	accessible for all users 
  |- Page A - 	accessible only for user A / group A
  |- Page B - 	accessible only for user B / group B
  |- Page B - 	accessible only for user A+B / group A+B

If not, is there any short-terms plan for supporitng this? 
Or, possible to implement through a custom role-based accees widget on an Azure self- or cloud hosted setup?? 

_PS. It seems that there are access rigths is somewhat supported though the by "logged in user" navigation elementrs. As an exmaple the navigation restricts the topmenu access to logged in users, however, the page it-self it still accessible to any user by typing in the URL directly https://xyx.developer.azure-api.net/reports. So the page does not comply to the access rights._

**Comment by Norgaard13** [comment]
_PPS. The example of the "loged in user" the navigation hides the /reports page, which cannot be seen in the topmenu, unless the user is logged in. So the nagivation is access enabled. However, it is still possible to access the page by typing the URL directly, e.g. 
https://xyx.developer.azure-api.net/reports._

**Comment by mikebudzynski** [comment]
Currently, we don't support page-level access controls, but this feature is on our roadmap. Referencing #1247 and #533.

**Comment by blyefd** [comment]
> Currently, we don't support page-level access controls, but this feature is on our roadmap. I will close this issue as a duplicate of #1247 and #533.

I dont see this as exactly the same as #1247 and #553.  Those deal with authenticated /anonymous whereas this is dealing with groups and products.
