### ISSUE TITLE
How to customize product subscription widgets

### ISSUE THREAD

**Issue by TarekMansour** [Azure/api-management-developer-portal#1253]
Hi Team,

I am trying to customize the default managed developer portal pages. I want to remove the text box and the subscribe button from product details page.

![image](https://user-images.githubusercontent.com/24205064/114988138-e2f1b200-9e8d-11eb-9f59-088c60630984.png)

I can not remove it in edit mode, maybe I miss something to do! Could you please challenge me with you ideas?

Thanks.

**Comment by azaslonov** [comment]
Hi @TarekMansour, you can select the widget and click on the "trash" button to delete it.

![image](https://user-images.githubusercontent.com/2320302/115284262-4df6ef00-a101-11eb-897c-7df22768f19f.png)

**Comment by TarekMansour** [comment]
@azaslonov when I'm on Authenticated mode, the subscribe form is not displayed to me!

![image](https://user-images.githubusercontent.com/24205064/115395629-fda08f80-a1db-11eb-8913-c79f00a158df.png)
