### ISSUE TITLE
Date time formats

### ISSUE THREAD

**Issue by ncroad** [Azure/api-management-developer-portal#1254]
In various places in the "new" Developer Portal where dates are rendered (e.g. the Profile page - subscription created, profile created), the dates are formatted with a US Date format (e.g. MM/dd/yyyy). See screenshot below.

We require the ability to control the date format and have it rendered in the standard date format for our country, i.e. dd/MM/yyyy.

Are we missing something, or can we please have this capability added? 

![Developer Portal - Date format issue](https://user-images.githubusercontent.com/82792767/115180447-b2c63f80-a129-11eb-90fd-65322d2233d2.png)

**Comment by azaslonov** [comment]
Hi @ncroad, local formats for dates and other contents will be supported as part of multi-language support: work item #137, please use it for tracking.

@mikebudzynski, do you want to comment on timelines?

**Comment by mikebudzynski** [comment]
> @mikebudzynski, do you want to comment on timelines?

Most likely in 2022.
