### ISSUE TITLE
Collapse menu-widget items

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1255]
## Bug description

Currently it is not possible to collapse menu items in the DevPortal.

On the official Microsoft documentation page the side-menu is able to collapse all menu items containing children.
![image](https://user-images.githubusercontent.com/58420097/115207003-7a0f7180-a0fb-11eb-8930-5445be34e21d.png)

In our DevPortal we have a lot of content and documentation. Our menu-widgets are lengthy and contain sub-menus.
This is how our menus would look like in context. This is a shortened example.

![image](https://user-images.githubusercontent.com/58420097/115207461-e9856100-a0fb-11eb-832b-173b2f220a7d.png)

It is unacceptable for the user to navigate with a complex and oversized navigation.
Therefore it is necessary to have a setting for menu widgets to collapse items. This should be able by default with a setting to define the navigation level after which the lower level items get collapsed and for the user manually by left clicking on an arrow (see Microsoft documentation).

For example if the default level is set to "0", then nothing should be collapsed.
If it is set to "1", then everything after "Fruits" & "More fruits" should be collapsed.
If it is set to "2", then in this case everything below "Banana" should be collapsed (not "Mango" or "Other").

## Is your portal managed or self-hosted?

Managed

---

@AnRei123

**Comment by AnRei123** [comment]
Thanks Zartrox for bringing up this issue. To collapse menus as of a dedicated navigation hierarchic level, a configuration option for the menu widget is missing. It need to be possible to decide for each menu item independently, as of which navigation level the headers should be collapsed by default when entering the page.

**Comment by azaslonov** [comment]
@ZarTrox, @AnRei123, makes sense, let me add this option.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
