### ISSUE TITLE
Unable to download images from blob storage

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1256]
## Bug description

For a few days I have been unable to download/upload images from/to the DevPortal.
But the data.json download/upload works perfectly fine.

I get an error message:

```
Error: Unable to download media files. request to https://[...] failed, reason: tunneling socket could not be established, cause=read ECONNRESET
    at downloadBlobs ([...]\utils.js:147:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

[...] = private data

My colleague can download/upload but after comparing files we weren't able to find the root cause.
What I found is that ECONNRESET apparently means that there is a connection Issues to the server/blob storage.
Does anyone have an Idea what could be the cause?

Many thanks in advance.

**Comment by ZarTrox** [comment]
Hi @azaslonov, the last few days I ve been in contact with our IT-support and they couldn't identify an issue on my side. If you cannot assist me/don't know where the issue could stem from, then what would your proposal be how I should proceed? Where/who at MS Support should I ask for help first?

**Comment by mikebudzynski** [comment]
@ZarTrox, can you send us the support case id to apimportalfeedback@microsoft.com?
