### ISSUE TITLE
Images not displaying on published version of the site

### ISSUE THREAD

**Issue by arrowhead237** [Azure/api-management-developer-portal#1257]
Good Afternoon,

I have placed images on the homepage of the api dev portal and they are visible when using the builder for the site (Screenshot provided)

![Screenshot 2021-04-19 154031](https://user-images.githubusercontent.com/81563887/115245998-c8396a80-a125-11eb-856b-948843f03313.png)

But once I publish the page, the images aren't visible (Screenshot provided)

![Screenshot 2021-04-19 154324](https://user-images.githubusercontent.com/81563887/115246270-06cf2500-a126-11eb-8504-f998d76b9877.png)

I have tried publishing twice from the backend of the portal, as well as on the frontend and the images aren't displaying. If I log into the dev version of the portal the images have been saved and can be viewed, they just don't seem to be visible on the live version of the site

**Comment by azaslonov** [comment]
Hi @arrowhead237, yep, there is a known issue with the backend, the hotfix is rolling out, but if you want to speed it up for your service, please send us your service name to apimportalfeedback@microsoft.com.

**Comment by azaslonov** [comment]
The hotfix has been applied to most of the services in the public cloud. If you still encounter the issue, please send us your service name(s) to apimportalfeedback@microsoft.com.

Closing for now.
