### ISSUE TITLE
CAPTCHA on self-hosted portal - CORS error (after following Wiki instructions)

### ISSUE THREAD

**Issue by velsietis** [Azure/api-management-developer-portal#1258]
## Bug description

Unable to sign in to a self-hosted portal with CAPTCHA enabled, even after following the [wiki instructions](https://github.com/Azure/api-management-developer-portal/wiki/Enable-CAPTCHA)

It is a CORS issue as described in #1054 (but occurs even with a custom domain on the managed portal).

## Reproduction steps
As per the wiki instructions to [enable CAPTCHA](https://github.com/Azure/api-management-developer-portal/wiki/Enable-CAPTCHA)...
1. _Self-host_ the portal at `https://portal.example.com`
2. In Azure API Management, set up a custom domain for the _managed_ portal at `https://api.example.com`
3. Publish the self-hosted portal with the following settings
   - `"useHipCaptcha" : true` 
   - `"backendUrl": "https://api.example.com"`
4. Visit the self-hosted portal at `https://portal.example.com` and try to sign up
5. A CORS error is returned when attempting to validate the CAPTCHA

## Expected behavior

The user should be able to sign in 

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

da8ac015e8865c2fcc159cf1391b6386ad498b8c

## Environment

 - Operating system: Windows 10
 - Browser: Edge (Chromium)
 - Version: 89

**Comment by azaslonov** [comment]
Thanks, @velsietis, we'll take a look.

**Comment by dfendrich13** [comment]
I am having this same issue as well.

Another thing that I think is related is the confirmation endpoints for user sign ups (email confirmations) point to the 'Developer Portal' endpoint configured within APIM. If the user clicks the link in those emails, they are then navigating within the managed portal instead of the self hosted portal.

**Comment by azaslonov** [comment]
Hi @velsietis, @dfendrich13, we're planning to return "*" in CORS headers for Captcha resources specifically (it doesn't seem to be a problem in this case), later on we'll probably add respective configuration options for CORS.

Regarding emails, @dfendrich13, you should be able to change the target hostnames in the URL in your email templates leaving the "query" part unchanged.

**Comment by dfendrich13** [comment]
@azaslonov I did try to change the email template, but the page wasn't found. I suspected this was because the confirmation endpoint doesn't exist for the self hosted portal.

**Comment by azaslonov** [comment]
Yes, you're right, the confirmation endpoint needs to be implemented in the case of a self-hosted portal. For instance, you could use Azure Functions to do that. Alternatively, you can configure Basic authentication with AAD B2C, which works using implicit flow not requiring the backend.

**Comment by dfendrich13** [comment]
Thank you @azaslonov, I was able to go the Azure Function route to get the confirmation email working.

**Comment by velsietis** [comment]
> Yes, you're right, the confirmation endpoint needs to be implemented in the case of a self-hosted portal. For instance, you could use Azure Functions to do that. Alternatively, you can configure Basic authentication with AAD B2C, which works using implicit flow not requiring the backend.

@azaslonov - now I'm confused... I thought that after #1258 was resolved that the confirmation endpoint worked fine for self-hosted portal. The [docs][1] don't say anything about using Azure Functions to get it to work:

[1]:https://docs.microsoft.com/en-gb/azure/api-management/developer-portal-self-host#step-8-change-api-management-notification-templates

**Comment by hugofdsantos** [comment]
Any news here? I'm with the same problem. CORS error on captcha validate request.

**Comment by azaslonov** [comment]
@hugofdsantos, yes, recently we have exposed CORS settings for the developer portal's backend and respective UI in Azure portal is coming in next 3-4 weeks. This should address your issue.

**Comment by azaslonov** [comment]
CORS settings UI and [documentation](https://docs.microsoft.com/en-us/azure/api-management/developer-portal-self-host#configure-cors-settings-for-developer-portal-backend) out. Closing the issue.

![image](https://user-images.githubusercontent.com/2320302/174387660-da9a608d-8135-4b28-9fca-34a2feaf704a.png)
