### ISSUE TITLE
Path parameters description getting changed

### ISSUE THREAD

**Issue by t-higgs-qa** [Azure/api-management-developer-portal#1265]
## Bug description

Currently the dev portal adds a suffix to path parameters which is overriding our desired description.

## Reproduction steps

1. Create an open API spec which includes a path parameter:
```json
"/some/route/{myPathVariable}": {
      "get": {
        "parameters": [
          {
            "name": "myPathVariable",
            "in": "path",
            "description": "myPathVariable: my path variable with a specific description",
            "required": true,
            "schema": {
              "maximum": 2147483647,
              "minimum": 1,
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
           }
        }
    }
}
```
2. Upload that to the apim as a new endpoint
3. View the OpenAPI specification for the new endpoint and notice that it now includes "Format - int32" in the description, even though the description should be "myPathVariable: my path variable with a specific description"
```json
{
    "/some/route/{myPathVariable}": {
        "get": {
          "parameters": [
                {
                    "name": "myPathVariable",
                    "in": "path",
                    "description": "Format - int32. myPathVariable: my path variable with a specific description",
                    "required": true,
                    "schema": {
                        "maximum": 2147483647,
                        "minimum": 1,
                        "type": "integer",
                        "format": "int32"
                    }
                }
            ],
            "responses": {
              "200": {
                "description": "Success"
               }
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/58445030/115615067-12e8ed00-a2b4-11eb-8428-b2e687d63ac3.png)

## Expected behavior

When our open api specification includes descriptions, those descriptions should be used as is, without being changed. 

## Is your portal managed or self-hosted?

Managed

## API Management service name

dev-apim-qes-w

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by mikebudzynski** [comment]
@t-higgs-qa, thanks for reporting the issue. We will fix the logic in the OpenAPI import process. As a workaround, you can remove the prepended information manually.

**Comment by t-higgs-qa** [comment]
While I agree that is an option, this occurs on any template path that is an integer which is many of our API's so that is quite a few manual changes that would get overridden any time we update from our openapi spec generators, which we use swagger.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
