### ISSUE TITLE
Left Aside element/frame not selectable after web widgets have been added

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1268]
## Bug description

Since the last week, the Left aside element is not configurable in our two column block/section layout. When you create the block from the scratch it is selectable. But after you added one or two text widgets, you are not able either to find, select or edit the Aside frame/element in the left column anymore.

![LeftAsideElementNotConfigurable](https://user-images.githubusercontent.com/58981351/115717954-f9f73f00-a37a-11eb-8599-59062ed4b536.png)

As a workaround, you need to configure the left Aside element/frame either before you add a web widget inside or you need to first need to remove all elements to be able to select the Aside element at a later point of time again.

## Expected behavior

Irrespective, how many and what kind of widgets are inside an Aside element/frame, it need to be possible to find, select and configure the Aside element at any time during editing.

**Comment by azaslonov** [comment]
Hi @AnRei123, there is a button here that allows you to switch the selection to the parent element:
![image](https://user-images.githubusercontent.com/2320302/115786525-ccf45d80-a375-11eb-85e2-863371ca9f82.png)

Hope that helps.

**Comment by AnRei123** [comment]
Yes, thanks, this helps. :-)
 I missed that you added this option as I only observed that the blocks behaved differently in how to access the section frame.
