### ISSUE TITLE
All APIs and Products Visible

### ISSUE THREAD

**Issue by campifoo** [Azure/api-management-developer-portal#1275]
We migrated our APIs to stand alone portal but now all APIs and Products are visible in the developer portal.  It does not appear to show only published products and APIs.  How do we correct this?

**Comment by azaslonov** [comment]
Hi @campifoo, just check how User > Group > Product > API are connected, starting with what groups included in what product. Another thing to check, if an API requires a subscription (in API settings).

**Comment by campifoo** [comment]
Thank you for responding.  It turned out to be we did the config runtime json file incorrectly.
