### ISSUE TITLE
Try It Code Sample Templates for C# and PHP are not populating headers

### ISSUE THREAD

**Issue by speedyps** [Azure/api-management-developer-portal#1276]
## Bug description

When using the Developer Portal Try It, and viewing the code samples, the examples for C# and PHP do not show the headers being added.

## Reproduction steps

1. Create an API call which has header information
2. Find API call in developer portal
3. Click Try It
4. Set Headers
5. Below the headers, check the HTTP sample - headers included in code
![image](https://user-images.githubusercontent.com/40074438/116185937-b8013b00-a776-11eb-91e1-462b5691c572.png)
6. Select C# (or PHP) no header values are added to the samples
![image](https://user-images.githubusercontent.com/40074438/116186185-38c03700-a777-11eb-8050-cadc6adef73d.png)

## Expected behavior

Defined headers should be added to all code samples.

## Is your portal managed or self-hosted?

Managed

## API Management service name

siss-api-apim-ae-stg

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome, Microsoft Edge (Chromium), Firefox
 - Version: Latest of all the above

**Comment by mikebudzynski** [comment]
Related to #1284
