### ISSUE TITLE
Revise code samples

### ISSUE THREAD

**Issue by mikebudzynski** [Azure/api-management-developer-portal#1284]
The scope is to refresh to built-in code samples and make sure they all generate the correct information.

**Comment by madhancock** [comment]
Any progress on this? I see it's been labeled P1 and given it has associated bugs that will no doubt confuse some developers can anyone give an update on when it might be addressed?

We're using the managed version but if it's relatively straight forward to get this repo running on local I could possibly look at fixing some of the samples.

**Comment by mikebudzynski** [comment]
@madhancock, this item is a high-priority issue on our roadmap, but at this moment it's unclear whether we will be able to address it by the end of the year. The scope of the improvement is to:

- Revise the languages that we provide the code samples for (for example, Objective C is of little value and we don't provide samples for Swift)
- Update the existing code samples (for example, the Python sample uses an outdated Python version)
- Review the code samples for completeness and fix the issues across all supported languages (for example, C# code sample incorrectly renders the query parameters in the URL `var uri = "https://contoso.azure-api.net/petstore/pet/findByTags?tags=testparameter?" + queryString;` and the Python sample doesn't render them at all)

Any community contribution is greatly appreciated.

**Comment by madhancock** [comment]
@mikebudzynski I would suggest the following changes:

- **HTTP & Curl** - These are both very useful, review and update if necessary.
- **C#** - review for errors. I've fixed some issues for this in #1421 - I could also correct that query parameter issue if you're happy for me to push an update to that PR or I can review C# in full in a separate PR?
- **Java** - review and update.
- **JavaScript** - Consider splitting this into _JavaScript_ and _JavaScript (JQuery)_, with the former being pure JavaScript using the `fetch` API. Alternatively, do away with the current JQuery/Ajax sample completely. These could be under the same option in the UI, but as with the Python examples - there is a risk a developer copies both examples without paying attention to the comments.
- **PHP** - Replace with example that uses Guzzle, which is a very common library used for HTTP in PHP.
- **Python and Ruby** - Review and update.
- **Objective-C** - Replace with Swift example.

There may be other languages that are worth adding. Golang for example... but I think adding entirely new samples would be better scoped under a different issue with the exception of Swift given that's essentially a replacement for Obj-C.

Anyhow, let me know what you think and I can see about getting these done.

As a side note, do you have a public roadmap for this project?

**Comment by erwinkramer** [comment]
@mikebudzynski  With release 2.11.2, the example field isn't added by default to the 'Try It' body, this is always empty now. This should be added again.

**Comment by mikebudzynski** [comment]
@erwinkramer, thanks for reporting the issue. We're now investigating it.

**Comment by azaslonov** [comment]
Fixed request body propagation in #1451

**Comment by erwinkramer** [comment]
> Fixed request body propagation in #1451

Thanks. That works.
