### ISSUE TITLE
Subscription Key formatted as a Guid with dashes do not validate

### ISSUE THREAD

**Issue by snap608** [Azure/api-management-developer-portal#1290]
## Bug description

The subscription key is clearly a Guid without the dashes. If I pass the Guid without the dashes the validation of the subscription passes. If I keep the dashes the validation fails. Not sure if this is by design. But I would think the validation should be valid for both scenarios.

I.e. `fae9383b-aa0f-4b5a-b59d-424bb9a0bae7` vs. `fae9383baa0f4b5ab59d424bb9a0bae7`

In our case the subscription key is used by our customers where their framework parse / detect as Guid and send the Guid with dashes.

## Expected behavior

Subscription key should validate for both with and without dashes.

## Is your portal managed or self-hosted?

Managed

_PS: Sorry if this is the wrong place to submit this, could not find any other place. :)_

**Comment by mikebudzynski** [comment]
@snap608, the subscription key is a string, not a GUID, and client applications need to use the string formatting. Even though API Management automatically generates GUIDs, the subscription key can be any string: https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/subscription/createorupdate
