### ISSUE TITLE
[Urgent] Elements disappearing

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1293]
## Bug description

Since the new update elements are not shown for smaller screen sizes (currently only observed in collapsible panels).
This affects also already deployed instances where customers already have access. In this example the navigation/menu in the header is affected.

Normal size:
![image](https://user-images.githubusercontent.com/58420097/116852313-616f8300-abf4-11eb-993f-40affbc42436.png)

Small size:
![image](https://user-images.githubusercontent.com/58420097/116852356-76e4ad00-abf4-11eb-9369-baa3773f0187.png)

The collapsible panel widget can still be seen in the editor menu even though it is really thin and does not contain the previous elements anymore.

---
@AnRei123

**Comment by azaslonov** [comment]
@ZarTrox, that's the whole point of the "Collapsible panel" widget - to "collapse" on "small" and "extra small" screens. That's not new behavior. If you don't want this behavior, just move your elements of it and delete it completely.

On a side note, there is another visibility setting coming soon that will allow you to show/hide elements depending on specific screen size.
