### ISSUE TITLE
Risk of data loss: Page content is not completely backed up and not completely published anymore!!!!!!

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1299]
## Bug description

Today, I published my portal contents to create review PDFs and realized that the contents of two pages did not appear in the puplished mode - even after clearing the cache!!! 
I was able to navigate to the pages and to see the template parts such as the header and the navigation tree on the left. But all page-specific contents had been empty!!!
The contents of these two corrupted are only visible in editor/designer mode of my source portal environment where I do the technical writing. 
Thus, I did a backup of the portal contents and checked whether the content of the two affected pages was correctly backed-up. BUT, the page content was not reflected in the backed up data.json!!!

I am afraid about data loss now!!! And I am currently not able to review or deploy he portal contents. And I don´t know if I should continue updating the other pages as long as I do not know if this issue can be fixed.

I did nearly every days a back up of the portal for such cases, but the last valid backup where the page content is correctly reflected was **on April 24th. On April 25th,** I did no backup. And as of April 26th, the page content and all my updates are not reflecting anymore in my backup files!!

Since this time, I did not realized that there was already an issue in the published mode. So I wasn´t aware and continued working on the corrupted and other pages.

I have now clue what happened on April 24th till 25th that removed the page contents from the data.json.

## Reproduction steps

1. Publish the portal
2. Navigate to the affected pages. The page navigation (template) is visible, but the page contents are empty.
3. Do a backup of the portal contents
4. Search for the title of the affected page. There is a page entry in the data.json, but there the referenced document content is not part of the downloaded data.json

To fix the issue within the portal, I tried the following:
1) I created copies of the pages and checked how the copied pages behave after publishing and backup. Same issue occurred for copied pages. Same behavior.
2) Tried to copy the sections from the corrupted pages and paste it on a new page. BUT the copied sections/blocks are not reflected in the "Saved" tab of the "Add section" library. And at the moment, I saved sections/blocks to the library all my previously saved sections/blocks disappeared from the "Saved" tab of the "Add section" library!!!
So I am also not able to continue using my building blocks for creating and updating other pages!!

## Expected behavior

1) The contents for the two affected pages does not only appear in the editor/designer mode, but also in the published mode and in the backups.
2) If there is a problem with page contents in the backend of the portal, the portal in editor mode throws out a warning message and explains what to do. Thus, the portal backend validates if for each page item also a document item exists. If not is able to correct the issue from the backend.
3) Saving blocks/sections to the library must always work in a reliable way - even in such cases to be able to safeguard content of corrupted pages.

## Is your portal managed or self-hosted?

Managed / Self-hosted

## Additional context

**@Alex/Mike:** I will send you the data.json with some details about the page IDs and the name of my source environments per email. Could you fix the issue till Monday? I urgently need to prepare a content review and I am not able to create scrollable screenshots or PDFs from pages displayed in editor/designer mode!

**Comment by azaslonov** [comment]
Closing, since we're following up offline.

**Comment by AnRei123** [comment]
The above described issue happened again!!!!

Created new page with contents, but document content (contentTypes/document/) is not reflecting in the backed up data.json! Did not receive any error message during upload. Therefore, did not recognize for days that the content is not backed up. Even when creating new pages on the affected instance, no document content  (contentTypes/document/) is reflecting in the backed up data.json for the newly created test page. Uploaded the inconsistent data.json to another instance to test if document content is reflecting in the data.json for new pages created after the upload on the new instance. Yes, here, for the new pages, after downloading the data.json, the new page content is reflecting in the data.json.
Believe me that I carefully saved the contents in the GUI hundred times (tried to copy it) and backed up the data. BUT NOTHING helped. Even saving the Sections/blocks is not possible anymore if this error occurs!!!!
The saved block entries are only reflecting in the data.json and not in the GUI. But even in the data.json, there is no content available for the saved block entries!!!!
----------
To continue my work on the affected environment, I performed the following steps to fix the issues:
1) Created a PDF as a backup for the texts of the missing page contents in the data.json
2) Executed a reset of the affected instance where the content of newly added pages is not reflecting in the data.json anymore.
3) Fixed the inconsistency in the data.json by adding dummy contents for the page entry in the data.json.
4) Uploaded the data.json with the dummy contents for the missing page contents.
5) Reworked the whole page contents according to the saved backup.PDF including styles and hyperlinks!!!!!!!!!!!
6) Continue authoring content and adding new page contents from the GUI of the affected instance is possible again.

Why do I need to do such kind of useless work - that kind of WASTE????????????????. Please fix the issue in your application as soon as possible. As you haven´t provided a fix for this issue, we have to create a script to validate the data.json after each backup to recognize the issue earlier.  Again, a lot of wasted time for nothing than managing the "managed" (!!!) infrastructure. Sorry, but this is not how I expect that a "managed" approach works. I need to be able to focus on creating new contents and not to troubleshoot and workaround every one or two weeks. This feels like "green banana" and putting the burden to the user - even I know it is hard to find the root cause. It suddenly occurs, And it seem to occur suddenly when creating new pages and pasting saved blocks/sections.
