### ISSUE TITLE
CORS - Not working on endpoints that has path variable, throws 404 Resource Not Found

### ISSUE THREAD

**Issue by arvic-loveria** [Azure/api-management-developer-portal#1304]
I'm having issues in CORS policy wherein every request has been accepted except those request that have path variables. How can I handle this in APIM?

I setup the CORS policy using below configuration.

```
<policies>
    <inbound>
        <cors>
            <allowed-origins>
                <origin>*</origin>
            </allowed-origins>
            <allowed-methods>
                <method>GET</method>
                <method>POST</method>
                <method>PUT</method>
            </allowed-methods>
            <allowed-headers>
                <header>*</header>
            </allowed-headers>
            <expose-headers>
                <header>*</header>
            </expose-headers>
        </cors>
    </inbound>
    <backend>
        <forward-request />
    </backend>
    <outbound>
    </outbound>
    <on-error />
</policies>
```
When a request has path variable, it throws 404 Resource not found exception like below which triggers the CORS error in console browser.

![image](https://user-images.githubusercontent.com/60765484/117970805-ad8c9700-b35b-11eb-9d80-17243289c1ac.png)

In my APIM, the path is like this.
![image](https://user-images.githubusercontent.com/60765484/117974013-a6678800-b35f-11eb-89e4-b9314b1edda1.png)

**Comment by azaslonov** [comment]
Hi @arvic-loveria, looks like you have a generic question, not really related to the Developer portal. MS Support should assist you better with this.

Anyways, is CORS policy defined on the global (All APIs) level? If not, I would recommend doing so to ensure that the scope is not the issue here. Otherwise, the setup looks fine to me.
