### ISSUE TITLE
Unable to customize the sigup page in azure developer portal

### ISSUE THREAD

**Issue by rajakushwah** [Azure/api-management-developer-portal#1306]
Issue - unable to add/rename the custom field on the signup page

Steps followed -  I have referred the documentation [https://docs.microsoft.com/en-us/azure/api-management/api-management-developer-portal-templates] to add the custom field in the signup page but the code changes are not reflecting on the portal.

1. Logged in as admin
2. Changed the code in Pages>SignUp

![image](https://user-images.githubusercontent.com/39225004/118436284-33169b00-b6fe-11eb-80c6-c2598175043c.png)

3. Saved the changes and published
![image](https://user-images.githubusercontent.com/39225004/118436532-999bb900-b6fe-11eb-995a-575eb235e534.png)

**Comment by mikebudzynski** [comment]
@rajakushwah, the templates are used by deprecated developer portal - not the new one from your screenshot. At this moment, it's not possible to rename the fields of the built-in widgets without self-hosting the portal.
