### ISSUE TITLE
Self Hosted Portal Guest user verification failed (same as 1157)

### ISSUE THREAD

**Issue by mounarshisantra** [Azure/api-management-developer-portal#1308]
## Bug description

When the user is invited to connect to the portal, he is directed to a page not found, which prevents him from registering his password and using the portal.

The link sent to the user's email is as follows:
https://mysite/confirm-v2/identities/basic/invite?userid=userId&identity=identity&ticketid=ticketid&ticket=ticket
It is generated from the "$ConfirmQuery" parameter in the notification configuration of Invite User mail.

If we try to use `signup` instead as a workaround  (https://mysite/signup?userid=userId&identity=identity&ticketid=ticketid&ticket=ticket)
the user is signed in to the home page without being allowed to set the password. The `Reset Password` workflow has to be triggered to allow the user to set the password and then they are able to sign in.

## Reproduction steps

1. Invite a user to the portal
2. User receives the email and clicks the link
3. The 404 page is displayed although the Network tab shows 200 responses.

## Expected behavior

User should be able to set a password and activate the account.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release 2.9.0

## Environment

 - Operating system: Windows
 - Browser: Chrome, Firefox
 - Version: latest

## Additional context

Network tab screenshot after the `invite` url is pasted in the browser

![image](https://user-images.githubusercontent.com/56808451/118578467-8ad10700-b7cf-11eb-880f-81d0e37d4dfd.png)

**Comment by azaslonov** [comment]
Hi @mounarshisantra, since you're using self-hosted portal, you need to update your email template of the user invitation. In the template, instead of `$ConfirmUrl`, you'll need to specify your URL of your self-hosted portal and `$ConfirmQuery` variable.

![image](https://user-images.githubusercontent.com/2320302/118894592-63566900-b8b9-11eb-96e9-f7a74db16205.png)

Hope that helps.

**Comment by mounarshisantra** [comment]
hello @azaslonov , we are using `$ConfirmQuery` variable and facing this issue.  this is the invite url in our template looks like at the moment, in line with  what has been suggested in the documentaation.
![image](https://user-images.githubusercontent.com/56808451/118896870-9138bd80-b94c-11eb-8725-535d181e1751.png)

**Comment by azaslonov** [comment]
Right sorry, that will not work without the backend at all, at least in the current implementation. So, there are a couple of things I can suggest:
1. Implement your own endpoint for the invitation process, i.e. using Azure Functions.
2. Switch to AAD B2C authentication, which also supports basic authentication and has its own invitation mechanism.

**Comment by mikebudzynski** [comment]
@mpowers-3c, at this moment this scenario isn't supported in the self-hosted portals. Could you please open a separate GitHub issue for it?
