### ISSUE TITLE
Pages window behavior (UX improvements to increase the speed of the content designers)

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1311]
## Bug description / Expected behavior

1) With the current implementation, in the Pages dialog, you have no clue how many pages are displayed in the list with or without entering a search string.

![Snag_2b02d744](https://user-images.githubusercontent.com/58981351/118671629-efa05780-b7f7-11eb-959a-180ddb8fe318.png)

To get a better orientation on the actual pages that are listed with and without an entered search string, metrics should be displayed such as "50 of 122 pages" is displayed to see how many pages are listed in the window. 

![Snag_2b01fcd2](https://user-images.githubusercontent.com/58981351/118671492-ce3f6b80-b7f7-11eb-8393-563f45112b98.png)

2) Currently it is really hard and makes a lot of extra efforts to keep the name of an entry in the Pages window in sync with the actual name of the page. If you do not keep them in sync, you lose the overview and you are not able to run meaningful searches.

To save editorial efforts, there should be an option like checkmark on the page details that can be checked in the case that you like to have the header 1 of the page content automatically be reflected as the name of a page in the list of the Pages window.  

Thus, if the title on a page is changed, this could be automatically reflected in the list of pages.

3) Currently, if you do not keep the title on the page and the name of the page in the Names window manually in sync, you do very hard to find the right page entry in the pages list. 
a) In such cases, you would like to search for the permalink of a page in the Pages window. But this is currently not supported. Currently, you would need to select every list entry in the list of pages to find the renamed page again - in the worst case scenario.
b) If you are editing a page and you open the Pages window, currently you need to search the displayed page even it is already opened. The expected behavior would be either that the opened page should be highlighted and displayed on top of the list by default or that there is a button that allows you to quickly navigate to the currently opened page.

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
