### ISSUE TITLE
QUESTION: Documentation on authenticating a APIM user.

### ISSUE THREAD

**Issue by BobbyCGD** [Azure/api-management-developer-portal#1312]
Hi,

While I was looking into delegating user sign in and sign up I thought about using the API Management API to manage the users. Since I should call the API to create a user in APIM for sign up i thought, "Why not also verify if the user exists and authenticate them as well?" I figured out how to:

1. Check a user exists on APIM
2. Authenticate a user via Username & Password against APIM

but.. and here is my question. For the 2nd point I went through the Developer portal source code and saw you are making a call to an operation for which there is no reference documentation. You send the Username & Password as base64 to {management_api_base_url}/identity . This raises a concern if I can use this operation reliably or should I find a different way of authenticating a user? Can you please advise if this operation isn't documented on purpose or it simply got missed when the reference documentation was written?

**Comment by EwanNoble** [comment]
Hi @mikebudzynski , is there an update to the ETA on this now we're 6 months down the line?

**Comment by mikebudzynski** [comment]
We're going to start working on the new endpoint in December. It will take several months for it to be fully released.
