### ISSUE TITLE
OpenAPI v3 Invalid Export: Component schema object missing in Components/schemas when used as $ref in query parameter schema

### ISSUE THREAD

**Issue by kristina-kovacikova-acn** [Azure/api-management-developer-portal#1314]
## Bug description
We are creating new API in dev portal from OpenAPI v3 schema definition. 

We are using same component schema object as $ref in query parameter and at the same time in some other component schema object as a property. When we download the schema referenced schema object is missing in components/schemas.

here is the path with query param with referenced schema object ( the problem is "recycled" query param)
```
'/products/{productId}/variants/':
    get:
      summary: get-product-variant
      operationId: get-product-variant
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: recycled
          schema:
            $ref: '#/components/schemas/recycledComponent'
```

here it is the schema object itself defined and used as property in another schema object
```
components:
  schemas:
    recycledComponent:    # this schema is not exported from the portal at all
      type: boolean
      example: true

    ProductVariant:
      type: object
      properties:
        productId:
          $ref: '#/components/schemas/productId'
        productVariantId:
          $ref: '#/components/schemas/productVariantId'
        recycled:
          $ref: '#/components/schemas/recycledComponent'  # here we are getting the error when schema is downloaded
        color:
          $ref: '#/components/schemas/color'
        name:
          $ref: '#/components/schemas/name'
```

After the schema is imported in API management - APIs and then downloaded from dev portal or from API management - APIs, referenced schema object is missing and error "$refs must reference a valid location in the document" is thrown (which makes sense because the referenced item is missing even though it was defined in the schema that was used to create API and we can see it in the portal in definitions)

Below is part of the exported schema [exported schema](https://github.com/Azure/api-management-developer-portal/files/6515917/test-api-export.txt) where you can see that recycledComponent is missing
![image](https://user-images.githubusercontent.com/19620938/118976922-e1784580-b975-11eb-8f71-5a77e1ef9ba0.png)

However with minor workaround and using oneOf in query param to wrap the $ref everything works as expected, object is referenced in both query param and the other schema object without any issues, and the recycledComponent object itself in present in the components/schema

```
 - name: recycled
          in: path
          required: false
          schema:
               $ref: '#/components/schemas/recycledComponent' # DOESN'T WORK recycledComponent is omitted from the components/schemas
 - name: recycled
          in: path
          required: false
          schema:
             oneOf:
               - $ref: '#/components/schemas/recycledComponent'  # DOES WORK

```

Also everything works as expected if schema is referenced in the array so it is wrapped inside items property. 
**From our observations it works everytime, except when the $ref is direct child of the query param`s schema property.** 

## Reproduction steps

1. Go to API Management 
2. Click on APIs - create new API - from Open API
3. Import [test-api-import.txt](https://github.com/Azure/api-management-developer-portal/files/6515872/test-api-import.txt)` as yaml
4. Click on the newly created API and click export
5. The exported schema will be invalid and you can see "$refs must reference a valid location in the document" error when opened for instance in Swagger editor

## Expected behavior

I should be able to use $ref in query parameter schema, where $ref is first child of the schema property and I should be able to reference the same object in multiple schemas and the referenced schema object should be exported in components/schemas
```
 - name: recycled
          in: path
          required: false
          schema:
               $ref: '#/components/schemas/recycledComponent'
```

**Comment by mikebudzynski** [comment]
@kristina-kovacikova-acn, we have already implemented a fix for this issue. It will roll out in or around July with the next regular API Management service release.
