### ISSUE TITLE
Please suggest a way to customize(Add/rename a filed) to the signup page

### ISSUE THREAD

**Issue by rajakushwah** [Azure/api-management-developer-portal#1316]
The signup page is not editable and also I am unable to add any custom field to the signup page so please suggest me a way to add/rename the fields.

![Untitled](https://user-images.githubusercontent.com/39225004/119124922-d3e2be80-ba4e-11eb-9088-cc1e66c34d1b.png)

**Comment by BobbyCGD** [comment]
@rajakushwah From experience, the sign up and sign in pages are reserved and hardcoded. You will have to edit the widget code to change the labels. Have a look at src -> components -> users for the respective components. You can read through the documentation here to understand the structure and purpose of each folder/file. Here is a link :) https://docs.microsoft.com/en-us/azure/api-management/developer-portal-implement-widgets

**Comment by azaslonov** [comment]
Hi @rajakushwah, unfortunately, the Management API doesn't support additional fields, so even if you change the UI, there will be nowhere to push new data.  For cases like this, we recommend going with [Sign-in Delegation](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-setup-delegation#-delegating-developer-sign-in-and-sign-up) feature that would allow you to connect to your own user store and persist additional data.
