### ISSUE TITLE
Unable to publish developer portal to an internal network (using Azure DNS Private Zone)

### ISSUE THREAD

**Issue by graemefoster** [Azure/api-management-developer-portal#1319]
Hi,

I've published an api management service to an internal vnet. I'm using private-zone to map the dns records required.
Everything seems to work OK apart from I cannot publish the developer portal.

I'm using private zone to host my dns records. My api management is on a default host (myapim.azure-api.net).
The publish button tries to send a request to 'apimanagement-cors-proxy-prd.azure-api.net' which is where my problem starts. 

I've tried mapping an entry to my private dns zone for 'apimanagement-cors-proxy-prd'. However when I hit the publish button, whatever runs on 'apimanagement-cors-proxy-prd' tries to resolve my internal Api management IP address. That's on my private zone so the call fails with 'Publishing wasn't scheduled. The remote name could not be resolved.'

Is this a bug or is it developer error? The api management documentation calls out using a private dns zone as an option here (https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-internal-vnet) "Configuring an Azure DNS private zone and linking it to the virtual network API Management service is deployed into is the recommended option".

Thanks for any help,

Graeme

**Comment by azaslonov** [comment]
Hi @graemefoster, that will be fixed in one of the next Azure portal extension releases. Instead of `apimanagement-cors-proxy-prd` it will call to ARM endpoint, just like any other portal requests.

As a workaround, you can try to publish from the designer itself:

![image](https://user-images.githubusercontent.com/2320302/119422194-5f5d8900-bcb5-11eb-908b-dc2f068bc530.png)

Hope that helps.

**Comment by mikebudzynski** [comment]
@graemefoster You can also use the new portal revisions feature:

![image](https://user-images.githubusercontent.com/40186513/119541033-f7ee1a80-bd42-11eb-920a-e07b50e8ffb2.png)

**Comment by graemefoster** [comment]
Thanks all.
