### ISSUE TITLE
+ Add Page is giving console errors and it isn't generating properly

### ISSUE THREAD

**Issue by Ledger94** [Azure/api-management-developer-portal#1323]
## Bug description

When creating a new page a message "oops, something went wrong" pops up and the page isn't correctly generated.

## Reproduction steps

1. Go to portal page (designer)
2. Click on Pages in left side pane
3. Click + Add Page
4. Oops, something went wrong, and a console errors are generated.
5.  ajax.ts:157 GET https://iapemea.management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/IAPEMEA/contentTypes/block/contentItems/new-page-template?api-version=2019-12-01 404 (Not Found)
6. paperbits.js:2 Uncaught (in promise) Error: Content not found for block with key blocks/new-page-template
3. Check out the new page that is generated and you can't edit it.

## Expected behavior

A new page to be properly generated.

## Is your portal managed or self-hosted?

Managed

## API Management service name

IAPEMEA

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 90.0.4430.212

**Comment by azaslonov** [comment]
Hi @Ledger94, if there is no added content that you want to keep, can you please try to reset the portal? 

![image](https://user-images.githubusercontent.com/2320302/119421404-78fdd100-bcb3-11eb-9ba5-f81d0209b71b.png)

**Comment by Ledger94** [comment]
I'm getting this pop up. When selection Reset content.
![image](https://user-images.githubusercontent.com/84686660/120084324-44b45700-c09d-11eb-8b34-2d179a60b8d8.png)

Here are a much of errors coming up on the console, when opening the homepage.
![image](https://user-images.githubusercontent.com/84686660/120084344-69103380-c09d-11eb-8623-b1436fe2acee.png)

**Comment by AnRei123** [comment]
We faced similar issues the last week and it even reoccurred after a while again. Today, clearing the browser cache helped to fix the issue for a while. The same issue occurred in the normal Chrome browser as well as in incognito mode of the browser. After clearing the cache, adding pages was possible again w/o error messages in the normal browser and in incognito mode.
Adding pages seems to be a problem currently in several directions.

**Comment by azaslonov** [comment]
This issue has been resolved in one of the previous releases, hence closing it. Please feel free to re-open shall you still encounter it.
