### ISSUE TITLE
Issues with resetting the portal contents through the GUI 

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1325]
## Bug description / Expected behavior

Today, I tried to reset two of our DevPortal instances. But through the GUI it was not possible:

Resetting the portal contents through GUI threw the following error message and was not successful:
![Unable-to-reset-website](https://user-images.githubusercontent.com/58981351/119461038-9aa49a00-bd3f-11eb-8382-4a5875c47ef3.png)

Resetting the portal contents should be possible at any time or it should be communicated when the service will be available again.

Remarks: Clearing the portal contents through the scripts was successful.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
@AnRei123, I can't repro this on my services, also don't see anything related in our logs. Can you please try to peek into F12 console errors if you still can repro, or better send us the service name so that we could try it from here?

**Comment by AnRei123** [comment]
I am also not able anymore to reproduce the issue. After restarting my PC on Monday, resetting the DevPortal of an instance via GUI was possible again.
