### ISSUE TITLE
Editing mode: Repeating onboarding popup windows "Did you know?"

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1326]
## Bug description / Expected behavior

Great that you facilitate the onboarding for new DevPortal contributors and content designers by providing some help such as the following:

![didYouKnowWindow](https://user-images.githubusercontent.com/58981351/119480328-d6e0f600-bd51-11eb-96e4-2380da8cf837.PNG)

Even after clicking the "Got it" button same information appears again and again.

Don´t bother experienced users by popping up the same help without asking again and again. After I have read the information and after I clicked the "Got it" button, the same information should not appear a second time again for me (even after clearing the browser cache - what is often required to proceed - should not trigger to show up same information again and again).

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
If you click "Got it", the event will be saved in the local storage, specific to the domain and browser, and you won't see the message again, unless you clear your local storage. Can you confirm you still see the pop-up in the same service and you don't clear the local storage?

**Comment by AnRei123** [comment]
Often I need to clear my browser cache and then the messages pop up again. But this should not be the case. When I said "Got it", irrespective of the browser cache, I do not like to see the messages again. They are irritating me and forcing me again and again to click the "Got it" button. Even after clearing the browser cache, the same messages should not appear again. Is there a chance to disable this help function? Or to configure that I am only interested in help infos about new features?

**Comment by mikebudzynski** [comment]
@AnRei123, at this moment there's no way to disable the prompts and we'll mark this item as a feature request. If you need to clear the cache only, you can do so without clearing the local storage, which would prevent the prompts from popping up.

**Comment by AnRei123** [comment]
The "Did you now?" messages also pop up again after a reset of the portal via the GUI. Due to issues with the managed portal, we sometimes need to fix issues in the data.json and recover our backups by uploading them again. Before uploading, cleaning up the data is required. Don´t show up the messages again and again. This is very much bothering, especially if you try to troubleshoot issues in your environments already or need to perform workarounds due to missing bug fixes on your end!

**Comment by AnRei123** [comment]
This morning I got again the same onboarding pop up messages. Clicking them again and again **feels very annoying**. Sorry, but I need to tell you even you have already planned to fix the issue.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
