### ISSUE TITLE
Question: SSO for a mix of managed and self-hosted portal supported?

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1329]
Effort and time-wise it is not possible with the current portal approach to type in all our documentation in the managed developer portal by software release. For contents that quickly need to be added by software release, especially for new services, we need a quick and simple solution to automatically generate a website from tagged markdown topics in the Azure DevOps environment. In this case, we would need a dependency from the external website to the sign-in page of the managed portal to protect the external web pages the same way as the pages of the managed portal
Means that a user who has access to a dedicated DevPortal instance could sign in in the DevPortal instance and then also access the external webpages.

Question: Is a single sign-on for a managed portal and self-hosted web pages already supported? If not, are there any other ways to achieve this in Azure?

## Is your portal managed or self-hosted?

Managed, but we like to offer additionally a self hosted web sites for quickly and easily adding newer contents in markdown format from team-specific projects within Azure DevOps.

**Comment by BobbyCGD** [comment]
You might be able to conjure something with Azure Front Door...

**Comment by mikebudzynski** [comment]
@AnRei123, this scenario isn't supported because API Management uses a separate user entity that's specific to the API Management service. You can possibly achieve this with authentication delegation: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-setup-delegation
