### ISSUE TITLE
API Management open API spec import results in schema mismatch at response

### ISSUE THREAD

**Issue by iammelvin** [Azure/api-management-developer-portal#1332]
## Reproduction steps

1. Go to azure APIM portal and import a new spec with swagger json 
2.  You see all the operations but few methods are having mismatch with the actual swagger json file 

For instance my original swagger definition has a response like below

 ```
"responses": {
      "200": {
        "description": "Success",
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/MsgTemplateDto"
              }
            }
          }
        }
      }
```
But the same response after importing in APIM is showing like

```
"responses": {
                "200": {
                    "description": "Success",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ApiApiNameGetTemplateBySearch-SearchText-searchText-Parameter-parameter-Get200ApplicationJsonResponse"
                            }
                        }
                    }
                }
            }

```
## Expected behavior

Expecting the same schema in response after importing similar to the original swagger json file

```
"responses": {
      "200": {
        "description": "Success",
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/MsgTemplateDto"
              }
            }
          }
        }
      }
```

## Is your portal managed or self-hosted?

Azure portal in cloud

## API Management service name

[Notification]

## Environment

 - Operating system: Windows
 - Browser: [Edge]

## Additional context

I tried calling the APIM endpoint from a javascript client but am I getting 404 resource not found error because of the schema mismatch in response of my APIM API Operation. But when I import the same swagger file in postman I don't get any errors or mismatch in schema. Need help in resolving the same,Thanks.

**Comment by mikebudzynski** [comment]
@iammelvin, API Management abstracts inline schemas into object definitions. If you'd prefer to have more control over the schema names, you can create a schema for your array object and reference it with "$ref" in the content representation, just the way API Management changed your original API definition.

**Comment by iammelvin** [comment]
Is OData function parameters supported directly or I have to do some workaround ?
