### ISSUE TITLE
login credentials and email insufficiently protected during the transmission to the server

### ISSUE THREAD

**Issue by andychenglivibank** [Azure/api-management-developer-portal#1334]
Hi Azure,

**Feature Request.**
 
Here is detail concern
 
We noted the login credentials and email were not sufficiently protected during the transmission to the server. The affected functions included the following:

1) Signup
2) Change password
3) Primary Key and Secondary Key for API

![image](https://user-images.githubusercontent.com/81301115/120459979-464a8b80-c3cb-11eb-80f2-4fb648a44cfb.png)

![image](https://user-images.githubusercontent.com/81301115/120460011-4cd90300-c3cb-11eb-9dc2-1457a2edac23.png)

![image](https://user-images.githubusercontent.com/81301115/120460030-52cee400-c3cb-11eb-915a-3bab857c34d1.png)

![image](https://user-images.githubusercontent.com/81301115/120460049-582c2e80-c3cb-11eb-99f1-7ab321d51e31.png)

This increases the risks for attackers to gain access to the user credentials and perform unauthorized actions on behalf of the users.

Could Azure team make a feature flag to massage the data during transmission.

Thanks

Andy

**Comment by azaslonov** [comment]
Hi @andychenglivibank, the data transmission is supposed to go through HTTPs channel which employs asymmetric encryption. If there is something else you would like to see in place, please provide respective resources on the topic or feel free to contact MS Support.
