### ISSUE TITLE
Azure API Management OData api operation returning 404 not found in response

### ISSUE THREAD

**Issue by iammelvin** [Azure/api-management-developer-portal#1335]
## Bug description

I have Odata endpoints in my swagger definition and its imported to APIM via azure portal. But when tried to call the Odata endpoint from a client I get 404 Not found error but the operation is available in APIM portal.

## Reproduction steps

For instance I have an Odata endpoint which is similar like below

    [EnableQuery(AllowedQueryOptions = AllowedQueryOptions.All, PageSize = 20)]
    [MapToApiVersion(v1)]
    [ODataRoute("GetBySearchParameters(SearchText={searchText}, Parameter={parameter})")]
    public IQueryable<XXXDto> GetBySearchParameters([FromODataUri] string searchText, [FromODataUri] string parameter)
    {
        return XXX.Get(searchText, parameter);
    }`

The above method after imported to APIM has an url as mentioned below

`/api/Messaging/MessagingTemplate/GetBySearchParameters(SearchText={searchText}, Parameter={parameter}) - GET`

DataType of searchText and Parameter are string and are available as template parameter in APIM portal.

I am making a call now to my APIM endpoint from a javascript client as below

`{{baseAPIMUrl}}/api/Messaging/MessagingTemplate/GetBySearchParameters(SearchText='search', Parameter='10,20')`

But I am getting the below error response

` configuration (0.004 ms)
    {
    "message": "Unable to identify Api or Operation for this request. Responding to the caller with 404 Resource Not Found."
    }`

Need help on how to match my request to the OdataRoute mentioned above.

## Expected behavior

200 ok response

## Is your portal managed or self-hosted?

Azure portal

## API Management service name

[Notification]

## Environment

 - Operating system: [Windows]
 - Browser: [Edge]

**Comment by mikebudzynski** [comment]
@iammelvin, this repository is specific to the new developer portal only. Please, contact Azure support for assistance.
