### ISSUE TITLE
Unable to send request error when integrating developer portal with AAD B2C

### ISSUE THREAD

**Issue by sagara-iw** [Azure/api-management-developer-portal#1336]
## Bug description

I've been following [this tutorial ](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad-b2c ) to integrate the API-M developer portal with the Azure AAD B2C, but I'm getting the following error after the signup process is completed at the AAD B2C and when it returns to the developer portal. Please refer to the following screenshot. 

` "Server error. Unable to send request. Please try again later."  `

![Screen Shot 2021-06-03 at 11 33 10 AM](https://user-images.githubusercontent.com/84750236/120567760-94f93380-c466-11eb-8a9f-1bb66e0f7fb5.png)

## Reproduction steps

Follow this [this tutorial ](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad-b2c ) without any customizations. Note that in AAD B2C I've tried registering the application using both **App Registration** and **(Legacy) Applications** UIs but ended up with the same error. 

## Is your portal managed or self-hosted?

Managed 

Note that, I can see a new user created in the AAD B2C tenant and the following IDToken in the redirected URL.
 
<img width="550" alt="Screen Shot 2021-06-03 at 12 00 01 PM" src="https://user-images.githubusercontent.com/84750236/120568084-4e580900-c467-11eb-913e-f3eb3ab6c985.png">

Also, I have a user signup policy configured as per the tutorial. 

<img width="1610" alt="Screen Shot 2021-06-03 at 11 55 10 AM" src="https://user-images.githubusercontent.com/84750236/120568122-6039ac00-c467-11eb-9519-802c46ee60e5.png">

On a separate note, the above tutorial still refers to the deprecated AAD B2C UIs which are scheduled to be removed at the end of this month so it would be better to update the tutorial.

**Comment by mikebudzynski** [comment]
@sagara-iw, please reach out to Azure support for assistance.

**Comment by sagara-iw** [comment]
Just for the records, this issue disappeared once the API-M service was upgraded to the latest version by Azure.
