### ISSUE TITLE
Show non-product subscriptions in user's profile page

### ISSUE THREAD

**Issue by smpilo** [Azure/api-management-developer-portal#134]
**Is your feature request related to a problem? Please describe.**
When attaching a user to an api-specific subscription, the only way to get the subscription key is through the azure portal. Shouldn't the subscriptions show up in the user's profile?

**Describe the solution you'd like**
I'd like to see a subscription that is not attached to a product show up in the user's profile.

**Comment by mikebudzynski** [comment]
@smpilo Thanks for opening this Issue. We'll follow up once we triage/repro it.

**Comment by mikebudzynski** [comment]
@smpilo Direct API subscriptions are indeed not shown in user's profile - in both the new and the old developer portals. Thanks for raising this issue.
