### ISSUE TITLE
API list page and details page tags on expanding UI alignment border issue

### ISSUE THREAD

**Issue by SSanjeevi** [Azure/api-management-developer-portal#1342]
## Bug description
API list page and details page tags on expanding UI alignment border issue - as highlighted in red in image attached

## Reproduction steps

Consider having many tags of apis around 15.

1. Go to 'API details page or API list page'
2. Click on 'tags'
3. you will see border, alignment, and content going beyond the border.
4. See error screenshot

## Expected behavior

A clear alignment and look and feel of UX.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Google Chrome, edge
 - Version: latest

## Additional context

Add any other context about the problem here, including screenshots.
<img width="304" alt="dev portal issue filtered" src="https://user-images.githubusercontent.com/24915474/121996758-d07cf180-cdc6-11eb-8177-85540ef4b417.png">

**Comment by mikebudzynski** [comment]
@SSanjeevi, looks like this issue was resolved by the commit above. Let me know if you still run into it.
