### ISSUE TITLE
Self-hosted developer portal not maintaining AAD session between browser tabs

### ISSUE THREAD

**Issue by ghost** [Azure/api-management-developer-portal#1347]
Hello,
We have cloned this repo and followed instructions for self-hosting developer portal. And we currently have this issue with AAD sign in:

Steps to reproduce:
- Open Developer Portal
- Sign In using Azure AD
  -  User is signed in
  -  User can keep clicking through pages and continue to be signed in.
- Open a new browser tab in the same browser window (Chrome 79.0.3945.117)
- Navigate to Developer Portal URL from the new tab
  - User isn't signed in 

Expectation:
As log as user signed in once, they should be signed on in all browsing sessions in the same window.

**Comment by mikebudzynski** [comment]
@AElharouny, thanks for reporting the issue. A mental note to the development team: we could implement a global handler in the portal that will check for the user session and redirect to the auth flow.

**Comment by azaslonov** [comment]
It seems that we can't preserve the session between browser tabs (in secure way) because of browser limitations: it doesn't keep the state of `sessionStorage`, and since it's a self-hosted portal, the HTTP-only session cookie is not also possible. Hence, closing the issue.
