### ISSUE TITLE
Show legal text by default on the developer portal

### ISSUE THREAD

**Issue by kye** [Azure/api-management-developer-portal#1348]
The APIM admin portal allows admins to enter legal text on the Product Settings page. The text is hidden on the developer portal product page but is displayed by clicking “Show”. The Subscribe button is not enabled until the user clicks “I agree to the Terms of Use”.

Not showing the text by default, or forcing the user to click “Show” before enabling the Subscribe button creates legal problems for us. We can’t legally enforce the text since we are not certain the user has viewed the text.

**Comment by kye** [comment]
@mikebudzynski Hi. Would this improvement gain priority if I created a PR with the fix?

**Comment by mikebudzynski** [comment]
> Would this improvement gain priority if I created a PR with the fix?

@kye, absolutely. We will be happy to review the PR. If you decide to contribute this improvement, please make it configurable in the widget configuration and turned off by default, so it doesn't affect existing developer portal deployments.

**Comment by traviswhipps** [comment]
@mikebudzynski, hello. Please note we have create a pull request that contains the code for this fix (added functionality to show legal text by default on product page load #1414).

**Comment by kye** [comment]
@mikebudzynski - Hi. Any idea on when this update will be rolled out?

**Comment by mikebudzynski** [comment]
@azaslonov will soon review the PR (#1414). We will start a developer portal release by mid-September and it should roll out to all services within 1-2 weeks. Would those timelines work for you?

**Comment by mrcarlosdev** [comment]
Merged
