### ISSUE TITLE
Search bar in the portal

### ISSUE THREAD

**Issue by sbenji77** [Azure/api-management-developer-portal#1351]
Hello,

Do you have plans to make a search bar available on the developer portal? 
Our users are starting to get lost and it would be really appreciated.

Cordialy
Benjamin

**Comment by mikebudzynski** [comment]
@sbenji77, we have plans to:

- Support static search of content
- Improve searchability in the API Management specific widgets (i.e., APIs, Products, etc.)

At this moment we don't have an ETA. I am merging this issue with #1014
