### ISSUE TITLE
Cannot sign in to the portal using Azure AD 

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#1352]
## Bug description

Signing in to the developer portal using Azure AD does not work after publishing the portal running on the following versions:

"CodeVersion":"20210618223831",
"Version":"0.20.1219.0"

It worked before publishing. This happened to two APIM instances. It works fine to log in to the old portal. I used the Azure portal to publish an old version but it showed the same behavior.

## Reproduction steps

1. Configure the APIM instance to use AAD for login and remove the password login. 
2. Turn on "Require anonymous users to sign in"
3. Put a button for OAuth login on the sign in page
4. Using another browser or computer log in to the portal
5. The log in will be accepted but you are not signed in.

## Expected behavior

Expected to get access to the APIs and products.

## Is your portal managed or self-hosted?

Managed 

## API Management service name

Will send you the names of the two instances in an email.

## Additional context

The portals are populated and published using a pipeline. It removes the sign up page. On one of the instances I reset the content and then published it but it still showed the same behavior. I have created case 2106230050002370 for this.

**Comment by azaslonov** [comment]
Following up offline.

**Comment by ErikMogensen** [comment]
It is now working when using CodeVersion 20210628210326. However, it is not possible to log out.

**Comment by ErikMogensen** [comment]
After getting the latest update and the publishing it, it was possible to sign out.
