### ISSUE TITLE
Any new Portal Revision is published / marked as current

### ISSUE THREAD

**Issue by Berbe** [Azure/api-management-developer-portal#1354]
Currently [newly created portal revisions](https://docs.microsoft.com/en-us/rest/api/apimanagement/2021-01-01-preview/portal-revision/create-or-update) are automatically published.
This makes `isCurrent` property of the REST API `Create or Update` and the `Current publish` check box on a new revision created from the Web GUI useless.

Would it be possible to create revisions based on the _administrative_ view without publishing them?

**Comment by mikebudzynski** [comment]
I could reproduce the issue by creating a revision in the Azure portal.

**Comment by Berbe** [comment]
I am glad you indeed see this as an issue!
A (quite frightening, if you ask me) warning banner is displayed on the `Revisions` tab of the `Portal overview` page on the API Management Web GUI:
> Creating a new revision or changing revisions will automatically update the portal to the latest release version.

This banner presence underlines the fact it seems to have been a known issue for a while.

**Comment by mikebudzynski** [comment]
> A (quite frightening, if you ask me) warning banner is displayed on the Revisions tab of the Portal overview page on the API Management Web GUI:

Can you explain why you find this banner frightening? It's completely unrelated. The banner states that whenever you create a new revision or switch between revisions, your developer portal will be upgraded to the latest portal version - i.e., software version that powers the developer portal, not the content version.

**Comment by Berbe** [comment]
The way I understood it was it described what is actually happening: revision creation will also immediately publish it.
If the message is unrelated, that's fine, but would it be possible it also confused other people?

Anyway, if this is unrelated to the problem at hand, let's not get sidetracked here.

**Comment by mikebudzynski** [comment]
> The way I understood it was it described what is actually happening: revision creation will also immediately publish it.
If the message is unrelated, that's fine, but would it be possible it also confused other people?

We'll display a more explanatory message to avoid confusion.

**Comment by mikebudzynski** [comment]
Fixed with https://github.com/Azure/API-Management/releases/tag/release-service-2021-10
