### ISSUE TITLE
config.runtime.json is being ignored

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#1355]
## Bug description

`config.runtime.json` is being ignored during design time and after deployment.

For instance, it should show the API list based on the settings in that file. 

## Reproduction steps

1. Use self hosted version 2.10.0
2. Modify `config.runtime.json` to another instance. 
3. See that it's not having any effect. I still see the API list from the design instance. 

## Expected behavior

`config.runtime.json` having any effect during design time and after deployment. Like in 2.9.0 

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.10.0

## API Management service name

//

## Environment

Any

## Additional context

It used to work in 2.9.0

**Comment by azaslonov** [comment]
Hi @erwinkramer, can you please pull the latest version, the issue should be gone now.

**Comment by erwinkramer** [comment]
Hi @azaslonov, you mean it's fixed in https://github.com/Azure/api-management-developer-portal/commit/f5f94b945bc5374edb5ba3034526e094483449ef? I'd rather wait on a new release though...

**Comment by azaslonov** [comment]
Yep, that's the one.

**Comment by erwinkramer** [comment]
Thanks
