### ISSUE TITLE
Publishing with scripts_v3 failing

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1357]
## Bug description

Automatically publishing with scripts_v3 causes the publishing step to fail for **some** instances.

Failed publish overview instance 1:
![image](https://user-images.githubusercontent.com/58420097/123625863-7fcab700-d810-11eb-8aef-122324454881.png)

Working publish overview instance 2:
![image](https://user-images.githubusercontent.com/58420097/123625973-9a049500-d810-11eb-91a9-595a12c85207.png)

Both instances use a CommonDev subscription and different resource groups.

We are logged in with "az login".
It throws an error but since the subscription ID from the failing instance is listed below this, this should not be an the cause.
![image](https://user-images.githubusercontent.com/58420097/123626361-0ed7cf00-d811-11eb-851e-78d78fc686be.png)

## Reproduction steps

If the names of the affected instances is needed I can provide them via email.

## Expected behavior

Starting the publishing process from the scripts works as intended like in instance 2.
If it does fail a description why it failed is displayed in the "Portal Overview" - "Revisions" tab.

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
@ZarTrox, looks like this issue is specific to your service and there are no errors or reproduction steps. Could you contact Azure support?
