### ISSUE TITLE
Feature Request/Question - API usage metering by custom metric instead of per API call

### ISSUE THREAD

**Issue by hansukyang** [Azure/api-management-developer-portal#1358]
Would it be possible to track API usage by custom metric instead of API calls? I operate a weather data service through this platform and will be metering by how much data is being requested in each call - for instance, one month of weather data vs. 70 years of weather data volumes are very different but still logged as single API call at the moment. 

Not sure if this is something that can be accommodated in Azure API Management platform.

Thanks!

**Comment by mikebudzynski** [comment]
Absolutely, you can find more information on the observability options in API Management at: https://docs.microsoft.com/azure/api-management/observability 

If you have further questions, please reach out to Azure Support. This repository is dedicated to the developer portal only.
