### ISSUE TITLE
Publishing without using revisions

### ISSUE THREAD

**Issue by Berbe** [Azure/api-management-developer-portal#1363]
# Context
Since revisions seem to be bogus (#1354) and lack cleaning features (#1353), using them might not be wise at the moment.

# Question
The developer portal WebUI discloses a publishing ability in the shape of a `Publish` button displayed in the `API Management` > `Portal overview` page, `Overview` tab.
Is this actionable through the [API Management REST API](https://docs.microsoft.com/en-gb/rest/api/apimanagement/)? If positive, through which undocumented route?

**Comment by mikebudzynski** [comment]
The *Publish* button will soon use the Portal Revisions API to publish the developer portal. It currently uses a legacy, undocumented API endpoint, which will soon be removed.

**Comment by jvdenning-cf** [comment]
Was this change actioned? We're seeing now massive problems where saved changes aren't published. A capture shows the page's navigation item but the actual document is missing. APIM instance is a developer instance. Other developer instances not currently having this issue but they don't see as much content editing activity (just migrated to using an azure pipeline)

Publish (in dev portal or azure portal) appears to run and going to the page in the published portal (which is in anonymous/unauthenticated mode) does **not** generate a 404, just renders the layout but no content. No errors detectable in the browser dev tools aside from a 401 when trying to get "/token"

**Comment by mikebudzynski** [comment]
@jvdenning-cf, please, open an Azure support request to solve the issues in your service.
