### ISSUE TITLE
Table widget - buggy and unmatured UX

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1364]
## Bug description/ Expected behavior

1) Even if the height is not manually specified for a row, the height of the rows is not automatically adapted according to the amount of inserted text rows. Even if I insert only one or two rows of text through a text widget, the height of all rows is not reliably and automatically adapted -even after publishing. 
2) Alignment settings for each cell are buggy as they are not consistently applied. Even I selected left and top alignment for the cell content, the alignment of the cell content did not change - even after publishing.
3) Currently, it is not possible to edit the borders and padding within a cell after a text widget has been inserted. Even after inserting widgets such as a text widget into a cell modification of paddings and cell borders must be still possible.
4) Currently, paddings, cell borders and cell alignments must be set for each cell individually. This is far too much effort. There should be an option to apply these kinds of settings for a whole row or column.
5) Currently, it is not possible to exactly position where to add a row or column. It must be possible to define where a new column/row should be added or removed.
6) It shall be possible to define for all screen resolutions to define the proportion between the first column or row to the other columns or rows to avoid that scroll bars are displayed for dedicated rows or columns, which looks very unprofessional.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Yep, all bullet points make sense.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
