### ISSUE TITLE
An allOf schema does not render correctly.

### ISSUE THREAD

**Issue by Dietatko** [Azure/api-management-developer-portal#1366]
## Bug description

An API schema using allOf OpenAPi construct to model "inheritance" is successfully used but not correctly rendered in the developer portal. The "inherited" schema is not showing any details and "parent" schema is missing completly.

## Reproduction steps

1. Import API with single operation returning follwoing schema:
```
    GetDrivingEventsResponse:
      required:
        - coordinates
      type: object
      properties:
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/ContextualGeoCoordinate'
      additionalProperties: false
    ContextualGeoCoordinate:
      allOf:
        - $ref: '#/components/schemas/GeoCoordinate'
        - type: object
          properties:
            dateTime:
              type: string
              format: date-time
              description: Description.
            speed:
              type: number
              format: double
              description: Description.
              nullable: true
            heading:
              type: number
              format: double
              description: Description.
              nullable: true
            accuracy:
              type: number
              format: double
              description: Description.
              nullable: true
          additionalProperties: false
    GeoCoordinate:
      type: object
      properties:
        latitude:
          type: number
          format: double
          description: Description.
        longitude:
          type: number
          format: double
          description: Description.
        elevation:
          type: number
          format: double
          description: Description.
          nullable: true
      additionalProperties: false
```
2. Open developer portal.
3. Review operation response schema.
4. See:
![image](https://user-images.githubusercontent.com/9396759/124787239-a394a800-df48-11eb-9687-9951484ea313.png)

## Expected behavior

Properties of "parent" and "inherited" objects are visible. Either union of all properties or only inherited props and reference to parent schema having the parent props.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

The portal was republished on 24-JUN-2021.

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version: Version 91.0.4472.124 (Official Build) (64-bit)

## Additional context

I have seen issue #522 was fixed and hoped this will solve the problem. But the problem shows up with portal published on 24-JUN-2021.

Interesting is that Example is generated correctly:
![image](https://user-images.githubusercontent.com/9396759/124787547-d5a60a00-df48-11eb-9616-13b887ed2ac3.png)

**Comment by mikebudzynski** [comment]
Linking to #1248, which we will use for tracking the `allOf` support.
