### ISSUE TITLE
Can't sign out from portal

### ISSUE THREAD

**Issue by adamstruck** [Azure/api-management-developer-portal#1369]
## Bug description

Users cannot sign out of the developer portal.  The portal in question uses delegation. 

## Reproduction steps

1. Sign in
2. Click "Sign Out" & nothing happens (just a fetch of `config.json` and `config-apim.json` according to the network profiler)

## Expected behavior

A redirect to the configured delegation endpoint to sign out. 

## Is your portal managed or self-hosted?

Managed

**Comment by adamstruck** [comment]
I can trigger the delegated sign out action by manually navigating to `/signout` in the portal, but after being redirected back to the portal the user is still signed in. 

Clicking "Sign Out" in the navigation bar just adds `#signout` to the current path.

**Comment by azaslonov** [comment]
Hi Adam, the fix is being rolled out right now. ETA end of this week.

**Comment by azaslonov** [comment]
@adamstruck, can you please try to re-publish the portal and try the sign-out again? It should work now.

**Comment by ErikMogensen** [comment]
As mentioned in #1352 the sign out works for me now.

**Comment by adamstruck** [comment]
It is working now. Thanks!
