### ISSUE TITLE
Sign up page does not show other idp like AAD B2C

### ISSUE THREAD

**Issue by saikovvuri** [Azure/api-management-developer-portal#1373]
Hello - We have added azure AD b2c to the identities under "Developer Portal" .  When we browse to sign up page , we only see "username and password" option but no option to sign up using Azure AD B2C

This is however working correctly in the now (deprecated) developer portal

**Comment by mikebudzynski** [comment]
@saikovvuri, make sure you:

1. Republish the developer portal.
2. Have the "OAuth buttons" widget placed on the page.

If you need further assistance, please reach out to Azure support.
