### ISSUE TITLE
Publishing fails with scripts.v3 or from revisions tab

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1377]
## Bug description

Publishing a DevPortal instance with either the "scripts.v3" or with the "revisions" tab in the Azure Portal fails inconsistently.
There are multiple different scenarios:

1. Uploading a data.json. Publishing in the revisions tab
        1.1 Works most of the time. Cannot actively reproduce issue when fails.
2. Uploading the same data.json and publishing with the scripts.v3
        2.1 Publishing fails the first time. Repeating the whole uploading & publishing process (after the first publishing process is flagged as failed) it works once.

The issue probably does not stem from an invalid data.json, because it works sometimes and the manual publish with this version in the portal works.
On the other hand publishing a resetted portal works all of the time though. 

There are many more scenarios and if there are other ones that can be reproduced I will update it here.

In a conversation with the Microsoft support team they mentioned that "styles" were missing. 
Error message: "Error: Data doesn't contain styles."
But with the data.json used in my tests I checked carefully and it was present.
Other Errors provided by the support:
- Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

I closed this support ticket because at the time it worked again.

If there are questions regarding this topic please ask them. I am aware that this can be confusing if you have not experienced it yourself.

## Reproduction steps

1. Download valid data.json
2. Upload data.json
3. Go to "portal overview - revisions" in the APIM Portal
4. Click "+ Publish"
5. Check the publishing status after some time

or

1. Download valid data.json
2. Upload data.json
3. Publish with scripts.v3
5. Check the publishing status after some time
6. Try again from step 2

## Expected behavior

When publishing an DevPortal instance with a valid data.json the publishing process should be working. If there should be an issue then there should be without a question be atleast a hint to know what went wrong.

![image](https://user-images.githubusercontent.com/58420097/125753201-81e5debd-5308-4cb7-95f7-0dbb41df5733.png)
When hovering over it the hint may say e.g. "Invalid data.json", "Request failed" etc.

So when something fails that you are aware of what could be wrong and if it is on the users side and he has to investigate.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
@ZarTrox, I'll need to take a look at all the reset point, but "Error: Data doesn't contain styles." usually means that data is not present (or not fully present) in DB (I know the error message doesn't mean much to our support, we'll improve it). This might be related with the migration script failures. I'll try to play with the steps you provided.

**Comment by ZarTrox** [comment]
Hi @azaslonov, are there any news yet? Were you able to replicate this issue on your end? What could be our next steps? Thanks in advance!

**Comment by azaslonov** [comment]
@ZarTrox, I was never able to reproduce this. It doesn't seem like there is an issue with script.v3, at least not with the one in our repo. If you could send us (by email) your script, data.json and step, we could try to investigate further.

I'm closing this issue to follow up offline.
