### ISSUE TITLE
"Add subscription" button glitches

### ISSUE THREAD

**Issue by Nikkaannika** [Azure/api-management-developer-portal#138]
**Describe the bug**
I have added a widget for Add Subscription. When pressing it it moves to the right and shows a field containing the name of the subscription. If pressing it again the request for subscription is being sent.

Also, caption of button in edit portal mode is "Add Subscription" while it is only "Subscribe" on published page. Minor glitch, should text be configurable?

I also added a text to workaround this behaviour but there is no way to add a text with the same conditional as the button, i.e. the button is only showing if the user doesn't have the Product, while my help text shows in all circumstances. It would be nice to add a text to the button that would follow the same conditional states.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to products and add the Product:Subscribe form widget
2. Save and publish page
3. Visit page as a user not having a product. Open Network tab and monitor that.
4. Press button to subscribe. 
5. Notice how a field appears but nothing happens in network tab.
6. Press button again and notice PUT call in network tab.
7. Return to product page or refresh product page.
8. Button is no longer visible, but non-conditional help text still appears (new feature, nice but not needed when button bug is fixed)

**Expected behavior**
Pressing the button should send the subscription request straight away, not display a field.

**Screenshots**
![Screenshot 2019-08-26 at 11 03 38](https://user-images.githubusercontent.com/54313786/63679908-bc7f8e80-c7f2-11e9-87c3-8bcc36c7310f.png)
![Screenshot 2019-08-26 at 11 03 48](https://user-images.githubusercontent.com/54313786/63679922-c43f3300-c7f2-11e9-88fe-b32a115d5b22.png)
![Screenshot 2019-08-26 at 11 04 05](https://user-images.githubusercontent.com/54313786/63679937-cacdaa80-c7f2-11e9-8ab3-04f4b8b1dff3.png)

**Desktop (please complete the following information):**
 - OS: MaxOS Mojave
 - Browser Chrome, Firefox

**Comment by mikebudzynski** [comment]
This will be addressed as part of the product widgets redesign. Merging with #187
