### ISSUE TITLE
Accessibility, Section 508 Compliance: Browser zoom function causes overlap and text truncation

### ISSUE THREAD

**Issue by jdm4344** [Azure/api-management-developer-portal#1380]
## Bug description

Zooming greater than 125% with a browser’s built-in zoom function causes card widgets placed within a multi-article block to overlap. Zooming greater than 125% when viewing the Operation Details widget causes text on the list of endpoints to overlap and be truncated with ellipses. Zooming greater than 150% on the User: Subscriptions widget causes text to be truncated and overlap.

## Reproduction steps

Steps assume completion via the Developer Portal editor, but behavior is the same when following via the published portal.

Cards
1. Create a multi-article block or use the one provided in the default portal template
2. Add card widgets in each article section
3. Zoom >125% using built-in browser zoom functionality

Operation Details
1. Create an Operation Details widget or use the one provided in the default portal template
2. Zoom >125% using built-in browser zoom functionality

User: Subscriptions
1. Create a User: Subscriptions widget or use the one provided in the default portal template
2. Zoom >150% using built-in browser zoom functionality

## Expected behavior

Text can be zoomed to at least 200% of its original size without loss of content or functionality.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: MacOS 10.15.7 - Macbook Pro 15-inch, 2017 model
 - Browser: Google Chrome
 - Version: 91

## Additional context

Related Section 508 test step: https://section508coordinators.github.io/TrustedTester/resize.html#check-144-resize-text

150% zoom
<img width="1680" alt="Cards - Overlap" src="https://user-images.githubusercontent.com/31706474/125816187-72b40596-d671-4796-be80-80577d898822.png">

150% zoom
<img width="1553" alt="Operation Details - Overlap and Truncate" src="https://user-images.githubusercontent.com/31706474/125816543-4d80c072-b42b-409b-ab65-9c1a80a18e96.png">

>150% zoom
<img width="1553" alt="Profile - Overlap and Truncate" src="https://user-images.githubusercontent.com/31706474/125816660-6249f676-3b72-4654-8a63-d5c3b2e1f9b8.png">

**Comment by christopherwoodland** [comment]
Any updates on the triage of this issue?

Thanks

**Comment by christopherwoodland** [comment]
Any updates on the triage of this issue?

Thanks

**Comment by jdm4344** [comment]
Hi @Mielek, thanks for the PR with those fixes. Wanted to try to provide some more details to hopefully help with replicating the card overlap problem. 

## Updated Environment Details:
Operating system: MacOS Monterey 12.0.1 - Macbook Pro 15-inch, 2017 model
Screen resolution: 2880 × 1800
Browser: Google Chrome
Version: 96

Details for section in portal editor:
<img width="1680" alt="Section Details" src="https://user-images.githubusercontent.com/31706474/144496402-dce61d44-e147-4740-be25-57bfd4ea5a0f.png">

Details for card in portal editor: 
<img width="858" alt="Card Details" src="https://user-images.githubusercontent.com/31706474/144496493-f0c2ba84-e2cf-41cc-961b-f181df1f61ce.png">

Card sizing styling:
<img width="889" alt="Card Style-Sizing" src="https://user-images.githubusercontent.com/31706474/144496530-65e8523a-5a17-4252-853e-9276ae618622.png">

Published 0% zoom:
<img width="1680" alt="Published - 0% Zoom" src="https://user-images.githubusercontent.com/31706474/144496632-c80407fc-5c0b-4c20-8822-d8c620c23026.png">

Published 150% zoom:
<img width="1680" alt="Published - 150% Zoom" src="https://user-images.githubusercontent.com/31706474/144496667-fdfdf472-58c5-419e-9d5d-bba2d5e8c920.png">

Published 200% zoom:
<img width="1680" alt="Published - 200% Zoom" src="https://user-images.githubusercontent.com/31706474/144496682-d9b2960c-c8b9-44c3-b16a-8d03b5b21542.png">

**Comment by azaslonov** [comment]
@jdm4344, we have fixed the snippet for cards section in the library. So, if you re-create this section, the cards will behave properly on screen sizes:

![image](https://user-images.githubusercontent.com/2320302/145915658-7ad85d92-719d-4d2f-82a1-b63ce0ec7210.png)
