### ISSUE TITLE
Table view of a schema definition does not render $ref object when inside an array

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#1382]
When using a $ref to a common object when inside an array, the object does not render in Table view as shown below.

![image](https://user-images.githubusercontent.com/62035456/125892692-7c122428-6465-4772-9fbf-2297ae3a0419.png)

However the in the raw schema view, the schema is displayed correctly.

![image](https://user-images.githubusercontent.com/62035456/125893160-c3b161dd-0012-4b29-8ab1-1cc611fc6d7b.png)

**Comment by jsorohova** [comment]
Fixed in a scope of #1516
