### ISSUE TITLE
Import OpenAPI Specification exclusiveMinimum

### ISSUE THREAD

**Issue by carlos-rian** [Azure/api-management-developer-portal#1388]
The bug happens when updating an "API" via the OpenAPI specification or trying to create.

The "APIM" gives the error, however this error is not objective and clear. After a few tries I found that this error occurs when there are some "parameters" with a "schema" that have the argument "exclusiveMinimum".

When it is removed, you can try to import it and it will work.

Path to reproduce the error:
APIM > API > Add API > OpenAPI

With Bug:
https://github.com/carlos-rian/Azure-Apim-Portal-Bug/blob/main/openapi-bug.json

![image](https://user-images.githubusercontent.com/65134623/125988963-1367b7e4-a522-4ce1-b700-53b38e0e5341.png)

No bug:
https://github.com/carlos-rian/Azure-Apim-Portal-Bug/blob/main/openapi.json

![image](https://user-images.githubusercontent.com/65134623/125989273-12c959f4-69e9-41bd-9860-f2cd48dc26bd.png)

## Reproduction steps

1. Go to 'APIM'
2. Click on 'API'
3. Click on 'Add API'
4. Choice 'OpenAPI'
5. Select a file (openapi-bug.json)
6. Click on "Import"
7. See the erro.

![image](https://user-images.githubusercontent.com/65134623/125988783-c661fc59-bd41-40ba-8d48-c39e0add373f.png)

**Comment by adrianhall** [comment]
Hi @carlos-rian,

The `exclusiveMinimum` value is meant to be a true/false minimum.    For example, you could put:

```
{
    "type": number,
    "minimum": 0,
    "exclusiveMinimum": true,
    "maximum": 50
}
```

And it would be a floating-point number from 0-50, but excluding 0.  Can you retry your test setting the "exclusiveMinimum" according to the spec?

Ref: https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.5

Please let us know if this solves your issue.

**Comment by carlos-rian** [comment]
Hi @adrianhall,

Thanks.

FastAPI framework is generating wrong schema.

✌
