### ISSUE TITLE
APIM Administrator

### ISSUE THREAD

**Issue by gsuttie** [Azure/api-management-developer-portal#1389]
I click to launch the developer portal and wanting to log in as the Admin (ive just created the resource) and I don't get automatically logged in - how do i log on as the Admin.

I'm an MVP using my Azure subscription, I created the resources in my Azure subscription and following some videos and the getting started docs and it just doesn't work as it should. 

p.s. would it be possible to give some feedback via a call around APIM somehow?

**Comment by mikebudzynski** [comment]
@gsuttie, you should be able to open the portal in the administrative mode by clicking the developer portal button in the Azure portal:

![image](https://user-images.githubusercontent.com/40186513/126368133-e3b4537d-6149-4213-84cb-fe96f54dd32e.png)

If you have troubles with it, please contact Azure support.

We'd be happy to hear you feedback - please share it via email to apimportalfeedback@microsoft.com.
