### ISSUE TITLE
Programmatically created SAS Token not working in publish step

### ISSUE THREAD

**Issue by msteffl** [Azure/api-management-developer-portal#1403]
Hello,

During the publish step of the self hosted dev portal a SAS Token is required in the config.publish.json (described here: https://docs.microsoft.com/en-us/azure/api-management/developer-portal-self-host) 

when I use the manually created token over the azure portal, everything works fine. But when I try to use the programmatically created SAS token as described here [link](https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-authentication#ProgrammaticallyCreateToken) I do not get it work.

I tried both formats

1) SharedAccessSignature uid=53dd860e1b72ff0467030003&ex=2...
2) SharedAccessSignature integration&201808020500&aAs....

but without success. 1) is not accepted cause of wrong SAS token format and 2) I get an unauthorized error.

The reason why I want to use the programmatically created Token is that I want to automise the public step (CI/CD pipeline) so that I do not need to create every 30 days the SAS token manually.

So do you have any recommendations for this problem? Is there a way that the publish step accepts 1) as correct format? Or do you have the code for generation of 2) that will work within the publish step?

**Comment by mikebudzynski** [comment]
@msteffl:

1. We checked the documentation and the steps and the sample code appear to be correct.
2. You can use this endpoint to programmatically retrieve the keys to generate the token: https://docs.microsoft.com/en-us/rest/api/apimanagement/2021-01-01-preview/tenant-access/list-secrets
3. Here is a sample code for generating the token in JavaScript: https://github.com/Azure/api-management-developer-portal/blob/master/scripts.v2/migrate.js#L164-L172

If you need further assistance, please open an Azure support request.

**Comment by msteffl** [comment]
@mikebudzynski 

Thanks for response.

Generating key works as described. But the problem is not the generation, it is the format of the token which is not accepted by the build system. When I execute the publish step the SAS token within the "config.publish.json" gets parsed in the following method:

https://github.com/Azure/api-management-developer-portal/blob/c523c10a7ab07eb10842e8d909d62fd141bfd9bf/src/authentication/accessToken.ts#L39

And the regex do not match the format "uid=integration&ex=2021-07-30T09:14:31.2230000Z&sn=Zmt...." So it runs into the exception "SharedAccessSignature token format is not valid." So it is not possible to publish with this programmatically generated token.

**Comment by mikebudzynski** [comment]
@msteffl:

1. Are you referring to the developer portal publisher as the "build system", when saying that the format isn't accepted by the build system?
2. Can you alter your token generation logic to produce token in the other form, as per the note at the bottom of [this documentation page](https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-authentication)? For example, `SharedAccessSignature integration&201808020500&aAsTE43MAbKMkZ6q83Z732IbzesfsaPEU404oUjQ4ZLE9iIXLz+Jj9rEctxKYw43SioCfdLaDq7dT8RQuBKc0w==`.

**Comment by msteffl** [comment]
@mikebudzynski 

1.) Yes exactly. The error occurs during the developer portal publish step.

2.) I also tried this. To just format the token to the accepted format. But then I got a not authorized exception. Seems that the token is not valid then.

But in the meanwhile I talked to Azure Support and they give me a solution that works for me. Instead generating the token programmatically, you can use an other REST API to generate the SAS token directly.

https://docs.microsoft.com/en-us/rest/api/apimanagement/2021-01-01-preview/user/get-shared-access-token

Using this API with userid parameter "integration" will generate a token that is also accepted in the publish step of the developer portal. So problem is solved for me.

But may it would be good to mention explicitly in the documentation that the described way of programmatically created SAS tokens wont be accepted in the publish step.

**Comment by azaslonov** [comment]
Hi everyone, if you just don't want to generate the token, you can specify `sourceId`/`destId` (e.g. `integration`) and `sourceKey`/`destKey` (which is primary or secondary key) parameters in the `migrate.bat` file instead of `sourceToken`/`destToken`. 

Just in case: the token parsing logic you mention above is for dev portal itself and it has other overrides that can handle `uid=...` format. However, the migration script has its own [helper method](https://github.com/Azure/api-management-developer-portal/blob/master/scripts.v2/migrate.js#L164) for that purpose.
