### ISSUE TITLE
Format single words as code/formatted text

### ISSUE THREAD

**Issue by Nikkaannika** [Azure/api-management-developer-portal#141]
**Is your feature request related to a problem? Please describe.**
Names of parameters etc are often formatted as code to stick out. This can't be done now for a single word inside a textblock.

**Describe the solution you'd like**
I want to be able to format a word as "code" (i.e. terminal font or similar)

**Describe alternatives you've considered**
I can use bold but it makes the text look messy and it's not the common convention for this.

**Additional context**
This was possible in the old portal.

![Screenshot 2019-08-27 at 14 39 59](https://user-images.githubusercontent.com/54313786/63772042-946a5b00-c8d8-11e9-9306-46c53340db10.png)

**Comment by azaslonov** [comment]
Feature added.
