### ISSUE TITLE
Issues after publishing - pages are unprotected in incognito mode!!!

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1410]
## Bug description

As this is a security-relevant issue, I cannot offer to test this bug for further APIM services. The issue occurred for one of my test environments. And I do not know when this error occurred the first time. Suddenly, I recognized that signing in is not mandatorily required anymore to see the DevPortal pages that should be protected according to the current APIM configuration.
The issue occurs in both ways of publishing, from inside the DevPortal or outside via the APIM portal.

## Reproduction steps

1. Go to 'APIM service'/Portal overview.
2. Open the tab `Revisions´.
3. Click the "+ publish" button.
3. Enter the required data, select the current option and save.
4. Wait until publishing has been finalized.
5. Open an article with a deep link of the DevPortal articles in the browsers incognito mode (in this case Firefox) and see if entering a password is required.

Observations:
1) For the currently published DevPortal instance, no redirect to the Sign-in page happened !!
2) No password was required to log in!!!

## Expected behavior

As earlier, redirect to sign-in page and require password in incognito mode.

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
@AnRei123, we couldn't reproduce the issue in any of the several services we tried. Could you please open an Azure Support request and walk them through the issue?
