### ISSUE TITLE
It is impossible to get the reason why publish failed

### ISSUE THREAD

**Issue by makemefeelgr8** [Azure/api-management-developer-portal#1416]
I made a few changes to developer portal and tried to publish it. Next, I've navigated to Portal Overview / Revisions in Azure. Publish has been running for over 8 hours and then failed. All I can see is revision name and Status "Failed". I've tried to get more info by exploring logs or using API with no success.

So, publish failed and I have no way of telling why. Thus, it might be a good idea to add error messages or something, so that users could at least see what went wrong.

I can't believe there is no way of removing the failed version, cancelling the process if it hangs or even viewing error messages. Those look like the most basic features to me. Is APIM Developer portal still in alpha or something?

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
@makemefeelgr8, could you please open an Azure support request to investigate and resolve the problem?

Meanwhile, I will scope this issue to an improvement about providing error details.
