### ISSUE TITLE
Can't add most widgets to layouts in 2.11.0 (self-hosted developer portal)

### ISSUE THREAD

**Issue by mkimbro** [Azure/api-management-developer-portal#1417]
## Bug description

When running the self-hosted developer portal version 2.11.0 locally, the user can only add three widgets, button, table and text-block, to layouts. In 2.10.0, they were able to add any widget.

## Reproduction steps

1. Set up a new APIM instance in Azure and publish the portal (I did this with a clean instance to make sure it wasn't something I had introduced)
2. Get the source for 2.10.0 and configure to connect to the APIM instance in step 1
3. Execute npm run start
4. When the portal is loaded, attempt to edit the default layout
5. Add a widget to the layout - observe that the full catalog of widgets is available
![image](https://user-images.githubusercontent.com/1663502/130146881-6a233541-28e8-4798-88e4-ea11a9af5d75.png)
6. Get the source for 2.11.0 and configure as in previous steps
7. Repeat steps 4 and 5 to attempt to add a widget to the layout - observe that only three widgets are available
![image](https://user-images.githubusercontent.com/1663502/130147090-a3f62098-2218-4374-b9cf-dcb8cc5ce894.png)

## Expected behavior

All widgets should be able to be added.

## Is your portal managed or self-hosted?
Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release `2.11.0`, commit `db41fa30e1784feec69a6cd3adfc69495f67bbd9`

## API Management service name

apim-mk-prototyping

## Environment

 - Operating system: Windows 10
 - Browser: Edge
 - Version: Version 92.0.902.73 (Official build) (64-bit)

Reproduces in Chrome Version 92.0.4515.159 (Official Build) (64-bit) as well

## Additional context

This does not appear to reproduce when adding widgets to content pages.

This appears to be related to commit `a8dc8e8da5725826438f2eafb7f5bfa15485e1e1` updating the paperbits dependencies from 0.1.424 to 0.1.432. If change these back to 0.1.424 in release 2.11.0, the issue no longer reproduces, though it is unclear what other side effects doing so might introduce.

**Comment by mkimbro** [comment]
This appears to have been fixed in paperbits-core commit [9c22be89733b91d998608600a899fa50ff5b1b8e](https://github.com/paperbits/paperbits-core/commit/9c22be89733b91d998608600a899fa50ff5b1b8e) and in paperbits-core release 0.1.436.

**Comment by azaslonov** [comment]
Yup, just please upgrade libraries to 0.1.436+ to mitigate it quickly. We'll push updates to this repo shortly.
