### ISSUE TITLE
Copy button doesn't work

### ISSUE THREAD

**Issue by martinsamanek** [Azure/api-management-developer-portal#1426]
## Bug description

Copy button for copy code example doesn't work

![image](https://user-images.githubusercontent.com/43401497/131487905-9957481e-9c1d-4a91-bce1-aa247597fbb5.png)

## Reproduction steps

1. Go to the operation details page
2. Click on the Copy button
3. Paste content of your clipboard to Notepad
4. Clipboard doesn't contain the code

## Expected behaviour

Code is inserted to Notepad

## Is your portal managed or self-hosted?

Self-hosted (same behaviour also on managed)

## Release tag or commit SHA (if using self-hosted version)

2.11.0

## Environment

 - Operating system: Windows
 - Browser: Chrome
 - Version: 92.0.4515.159
- Tested also on Edge  92.0.902.84

**Comment by azaslonov** [comment]
Fixed in PR #1507.
