### ISSUE TITLE
API is not appearing on the API List on the Developer Portal website

### ISSUE THREAD

**Issue by exig0** [Azure/api-management-developer-portal#1427]
** Azure API Management Developer Portal issue **

Hi,

I added a new API in the Azure API Management Platform, and deleted the Echo API. When I want to edit the Developer Portal, it is appearing in the API List, but when I publish the website, it is not in the API List, and the published website (Contoso example), says "No APIs found". 

Any assistance will be much appreciated.

Thank you.

Igor

**Comment by mikebudzynski** [comment]
You probably haven't assigned the API to a Product and/or published the Product. Please, work with Azure support to troubleshoot the problem.
