### ISSUE TITLE
List of APIs or products appears suddenly empty (UX issue)

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1428]
If you keep your DevPortal session open for a longer period of time, it might be that the list of APIs and API products appears empty to the user.

## Bug description

 It seems that this might be the case if the AAD user session has been ended. But their is no indicator in the Developer Portal that the AAD user session ended as the articles are still accessible - only the APIs and products vanished.

Currently, the user has to know by chance that he/she need to logout manually and sign in again might fix the issue. But a lot of users have no clue how to troubleshoot this bug.

## Expected behavior

If the AAD user session has been ended, the DevPortal automatically should log out and redirect the user to the Sign-in page again.

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
@AnRei123, we will make sure the token is correctly refreshed in the published portal and that a proper error message is displayed if the session expires.
