### ISSUE TITLE
OAuth2 Client Credentials in developer portal - client secret not URL encoded when generating Basic auth header

### ISSUE THREAD

**Issue by ptdurrant** [Azure/api-management-developer-portal#1432]
## Bug description

Generating OAuth2 client_credentials in the developer portal was failing against an Azure AD OAuth2 endpoint. Tracing the request being sent by Azure API Management showed that it was using a Basic authentication header to pass the client ID and client secret from the backend config.

Double-checking ![Azure AD Client Credentials documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#get-a-token) confirmed that Basic auth is supported, and that it should conform to ![RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1). Reviewing what was sent against the RFC showed that the values were not being URL encoded when the header was generated, leading to an "invalid client secret" error from the Azure AD endpoint.

To confirm that this was the issue, I replaced the "client secret" value in the backend config with a URL encoded version of the secret and retested. This generated the correct Basic auth header, and was able to successfully obtain a bearer token from Azure AD.

## Reproduction steps

1. Configure an OAuth 2.0 server with client_credentials in Azure APIM, ensuring that the client secret contains a value which differs when URL encoded (mine had lots of punctuation courtesy of Azure AD).
![image](https://user-images.githubusercontent.com/6889548/131650806-d72ebd7e-ea4c-491b-b91a-0bcca3a22516.png)
2. Configure an API to use this server
3. View the API in the dev portal
4. Attempt to generate client credentials
5. Observe failure to generate due to invalid client secret
![image](https://user-images.githubusercontent.com/6889548/131651568-35cb937e-575e-4be0-b080-1a0d8088b1a7.png)

1. Replace the previous client secret with a URL encoded version
![image](https://user-images.githubusercontent.com/6889548/131651005-48124afa-acde-4ca8-acda-ca4cfdc2cd8c.png)
2. Attempt to generate client credentials
3. Success 🙂

## Expected behavior

Client ID and secret should be URL encoded when generating basic auth header, as per RFC6749

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
