### ISSUE TITLE
Support of deep links with hash keys for dedicated subchapters after redirect from sign-in

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1433]
## Bug description

Currently, deep links including hash keys for dedicated paragraphs on the target pages are cut of from the URL when redirected from the Sign-in page to the target page.

Some of our articles are little lengthy. For example, our glossary consists of several entries. If we like to reference a dedicated glossary entry from our Azure DevOps wiki, after sign-in to the DevPortal, the user is redirected to the top of the glossary article and lost its focus. 

## Expected behavior

Support deep links containing of hash key enriched URLs that are added in sources like a wiki page in Azure DevOps even in scenarios when the user needs to first sign-in the Developer Portal before being redirected to the dedicated subchapter of the target page. There should no need to scroll to find the right position on the target page that was referenced in the source.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
@AnRei123, can you please provide an example of such deep link, just to be on the same page?
