### ISSUE TITLE
OpenAPI 3.0.1 "examples" property is not getting visualized

### ISSUE THREAD

**Issue by TobiTh** [Azure/api-management-developer-portal#1438]
## Bug description

The OpenAPI 3.0.1 "examples" property is not getting visualized in the developer portal. Only the "example" property is currently being visualized.

## Reproduction steps

1. Import the following openapi.yaml in the api management:
``` yaml
openapi: 3.0.1
info:
  title: Example API
  description: Example API
  version: 1.0.0
servers:
  - url: https://example.com
    description: Generated server url
paths:
  /api/v1/entities/{entityId}:
    get:
      tags:
        - Entity
      summary: Endpoint for getting an entity by its id
      operationId: API#01
      parameters:
        - name: entityId
          in: path
          description: Id of the entity
          required: true
          schema:
            type: integer
          examples:
            Sample entityId:
              description: Sample entityId
              value: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
              examples:
                Response example:
                  description: Example response
                  value: |-
                    {
                      "success" : true
                    }
```
2. Open the developer portal and navigate to the operation

## Expected behavior

The examples that are defined in the api definition should be visualized

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 92.0.4515.159

## Additional context

Here is the api imported at https://editor.swagger.io/ (examples visible):
![image](https://user-images.githubusercontent.com/1315244/131980626-63b2dca6-2377-4777-b42b-41e1cf53b6f6.png)

Here is the api imported in the api management (no examples visible):
![image](https://user-images.githubusercontent.com/1315244/131980494-8d06a50b-d39b-4b93-bec2-0709727cc1f4.png)

**Comment by TobiTh** [comment]
Thank you for fixing this really quickly! When is it going to be released?

**Comment by azaslonov** [comment]
It should reach all the regions in a couple of weeks.
