### ISSUE TITLE
Support adding Google Global Site Tag (gtag) for managed portal

### ISSUE THREAD

**Issue by nosvalds** [Azure/api-management-developer-portal#1445]
Currently it's possible to add GTM container Ids to the managed developer portal following [these instructions](https://docs.microsoft.com/en-us/azure/api-management/developer-portal-integrate-google-tag-manager)

My marketing department would like to add a Global Site Tag (gtag) as well. The code snippet looks similar to GTM, but is different:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXXXX');
</script>
```

The plugin used by the managed portal https://github.com/paperbits/paperbits-gtm doesn't seem to support the Global Site Tag.

**Comment by azaslonov** [comment]
Hi @nosvalds, this is not something hard to add, but before doing it, can you please tell a bit more about what you're trying to achieve and what GTM doesn't allow you to do? I'm asking because GTM kind of covers everything GTAG goes: https://support.google.com/tagmanager/answer/7582054?hl=en

**Comment by nosvalds** [comment]
Apologies for the delay. We have actually moved away from GTAG now, so happy to close this issue.
