### ISSUE TITLE
Basic Auth Sign-Up - Registration With Duplicate Email Fails But Does Not Display An Error

### ISSUE THREAD

**Issue by jdm4344** [Azure/api-management-developer-portal#1448]
## Bug description

Using the Sign Up Form: Basic widget, if a user tries to create an account with an existing email address, the registration fails but no error message is displayed. The only outcome is the captcha image changes. 

## Reproduction steps

1. Create and confirm an account using basic authentication
2. Sign out of account
3. Return to page with Sign Up Form: Basic widget
4. Attempt to create a second account using the same email address as used by the first account
5. No visible error is displayed in the developer portal, potentially related error is printed to the browser's console

## Expected behavior

When attempting to create a new account using basic authentication with an email address that is already in-use, an error indicating this is displayed via the Sign Up Form: Basic widget or accompanying Validation Summary widget.

## Is your portal managed or self-hosted?

Managed

## Environment

Operating system: MacOS 10.15.7 - Macbook Pro 15-inch, 2017 model
Browser: Google Chrome
Version: 91

## Additional context

Sign Up Form: Basic widget after clicking Sign Up with an email that is already in use
![email-no-error](https://user-images.githubusercontent.com/31706474/132749585-e69aa505-6308-4276-bb86-5bd8795db941.png)

Potentially related error displayed in browser console after clicking Sign Up
![image](https://user-images.githubusercontent.com/31706474/132749750-1ea9b246-e4d3-4344-9abc-eca07d920a25.png)

**Comment by azaslonov** [comment]
This has been fixed in #1437. Managed version will get this by 8/15.
