### ISSUE TITLE
Unable to find documentation for configuring Azure AD and Azure AD B2C in self-hosted variant

### ISSUE THREAD

**Issue by michaelweidmann** [Azure/api-management-developer-portal#1450]
Hi all!

I'm currently trying to deploy a self-hosted version of the developer portal. So far everything works. Now I wanted to configure security (Azure AD and Azure AD B2C) for the developer portal and I am not able to find any documentation related to that topic.

I think I need to edit the `src/config.validate.json` file? If so how do I fill it out correctly?

Thanks,
Michael

**Comment by mikebudzynski** [comment]
@michaelweidmann, this documentation article lists the precise steps for enabling Azure AD B2C identity provider: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad-b2c Don't forget to republish your portal once you configure this option. If you have troubles configuring the portal, please reach out to Azure support.

**Comment by michaelweidmann** [comment]
First of all, thanks for your answer and sorry for reopening this issue.

I can't even manage to configure the Azure AD. As you see in the following picture I am trying to click to sign in via Azure AD but an error appears. I think that there is some configuration missing, but I wasn't able to find any documentation about that.

![grafik](https://user-images.githubusercontent.com/37302540/133338742-d884e6b9-7ab6-4617-8730-09279906679f.png)

I followed this article: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad and it works - but only for the managed variant and not for the self-hosted.

**Comment by mikebudzynski** [comment]
@michaelweidmann, have you republished your self-hosted portal after enabling the Azure AD B2C identity provider? If you did, please open an Azure support request - they will be able to help you troubleshoot the problem.
