### ISSUE TITLE
Question: Planned deadline for support of legacy portal and associated application mgmt. in APIM service

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1455]
## Problem

We do still have several applications (cloud and on-premise) that are still relying on the application management provided through the legacy Developer Portal and the APIM services in order to generate application tokens. For most of these applications, we would NOT be able to migrate to the new Developer Portal approach regarding the application management in 2022.

## Question

How long do you plan to continue supporting the legacy developer portal and associated application management through the APIM services? Can you officially confirm your support for the Legacy Developer Portal and Legacy Application Management Service until at least beginning of 2023 or later?

**Comment by AnRei123** [comment]
I just saw that there is already an announcement on the following Microsoft docs page:
https://docs.microsoft.com/en-us/azure/api-management/developer-portal-deprecated-migration

There is the following statement regarding the legacy Developer Portal: "You can continue to use it, as per usual, until its retirement in **October 2023**". As my question is already answered with this statement, I close this issue with this comment.

**Comment by mikebudzynski** [comment]
> "You can continue to use it, as per usual, until its retirement in October 2023"

@AnRei123, that is correct. The legacy developer portal will not be removed prior to October, 2023. 

However, could you elaborate how you use "applications" to generate tokens? Is it a manual process? Do you mean OAuth tokens? This "applications" functionality wasn't designed with that purpose in mind. We will soon start working on a self-serve OAuth applications functionality in the developer portal, where the portal users will be able to create and manage OAuth applications and subscribe to products with those applications.
