### ISSUE TITLE
Can't find blob storage connection string of a managed instance

### ISSUE THREAD

**Issue by Perspektyva** [Azure/api-management-developer-portal#146]
Hello,

I'm currently trying to pull the contents of the new dev portal (managed instance) into source control. I'm using migrate.bat and the capture bit works, but I'm stuck at media downloading - I don't know where to get the storage connection string. Ln3 @ migrate.bat directs to the full documentation, but I've looked at the docs here and the single [MS Doc](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal) and couldn't find anything. 

Where do I find the connection string? Also are there another ways to source control a managed instance of the new dev portal?

**Comment by mikebudzynski** [comment]
This documentation article explains how to retrieve the storage account for the managed version: https://github.com/Azure/api-management-developer-portal/wiki/Retrieve-managed-portal-storage-account

Let us know if you still have problems setting up the script.
