### ISSUE TITLE
Hamburger icon for smaller screen resolutions not working as intended

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1461]
## Bug description

In the DevPortal we are using multiple menu items which are stored in collapsible panels so that when users with smaller screen sizes, e.g. a smartphone, are using this Portal can navigate through the DevPortal with the hamburger Icon.
But when the hamburger icon appears, the Menu is just moved to a different location and does not disappear. See first image.

![image](https://user-images.githubusercontent.com/58420097/134154571-83ee0d86-4010-46ce-b4ff-2821530eed04.png)

Upon clicking on the hamburger icon the menu is correctly displayed. See second image.
![image](https://user-images.githubusercontent.com/58420097/134155841-5b62ab8a-c35a-44fb-a6ed-f5216586c377.png)

Our observation is that the menu which first didn't disappear changes position and is displayed correctly.
We are aware that the new grid approach is in development but since it may take some time until it is finished a solution/workaround for this old problem in the meantime should be present.

## Expected behavior

For smaller screenresolutions the hamburger icon should appear and the menu widget should completely disappear.
When clicking on the hamburger icon the menu widget should be displayed correctly and readable.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
This issue has been addressed in Paperbits libraries and will be integrated in next 3-4 weeks along with site heading snippet. This includes full hamburger button customizations, popup container controls, and more.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
