### ISSUE TITLE
Page doesn't render when editing pages in developer portal

### ISSUE THREAD

**Issue by hansukyang** [Azure/api-management-developer-portal#1462]
## Bug description

When trying to edit pages in developer portal, one of the pages don't render properly and even if I navigate away from the page other pages also stop rendering properly. This always happen with this particular page ('Sign Up') on my developer portal, always showing "Oops, something went wrong. We are unable to complete your request this time. Please try again later.'

## Expected behavior

I should be able to navigate to different pages and edit.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser: Firefox

## Additional context

![Screenshot from 2021-09-19 21-45-03](https://user-images.githubusercontent.com/11863789/134304327-72e36c29-6516-48f9-94f9-9b61286fbd3c.png)
.

**Comment by azaslonov** [comment]
Hi @hansukyang, please send us your service name to apimportalfeedback@microsoft.com. We'll take it from there.

**Comment by azaslonov** [comment]
As we spoke offline, there is an issue with third-party proxy, not a portal bug. We'll continue working with you guys offline to help resolving it, but I'm closing this github issue.
