### ISSUE TITLE
Import to APIM fails with "valid against no schemas from 'oneOf'" error

### ISSUE THREAD

**Issue by SDGhoshal** [Azure/api-management-developer-portal#1463]
My GET API receives collection of Enum as query parameters. My swagger works perfectly fine and below is how the parameter in swagger.json looks like:
{
            "type": "array",
            "name": "colors",
            "in": "query",
            "collectionFormat": "multi",
            "x-nullable": true,
            "items": {
              "$ref": "#/definitions/Color"
            },
            "enum": [
              "Blue",
              "Black",
              "Brown",
              "Pink",
              "Yellow"
            ]
}

But when I import my API to APIM, it throws error:  
[Code= ValidationError, Message= Parsing error(s): JSON is valid against no schemas from 'oneOf'. Path 'paths['/api/v1/<ControllerName>/Card'].get.parameters[0]', line 795, position 11., Target= representation]
[Code= ValidationError, Message= Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specificate https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json)., Target= representation]

If I change the API to expect a single Enum value, it works. Definitely there is an issue with how the schema is treating a collection of enum. Am I expecting something which should not be out of box here? Should there be a custom implementation here?

**Comment by mikebudzynski** [comment]
@SDGhoshal, the issue is specific to your OpenAPI file and it relates to the API import process in API Management, while this repository is only for the developer portal. Please, reach out to Azure support for assistance.

**Comment by VitaliyKurokhtin** [comment]
@SDGhoshal, the schema in sample is invalid, you should not mix array and enum inside same type. If you mean array of enums, "enum" should be placed inside "items". See online schema validator: https://www.jsonschemavalidator.net/
