### ISSUE TITLE
Creating custom widgets in React

### ISSUE THREAD

**Issue by phfrc** [Azure/api-management-developer-portal#1465]
Hello !

Awhile back, I tried to implement paperbits-react into the developer portal (self-hosted) but I was never able to get it working. There's not a lot of documentation about creating your own widgets with React inside the Azure APIM Developer Portal project. Is there any way to get some informations about this?

Thanking you in advance.

**Comment by azaslonov** [comment]
Hi @phfrc, there is no docs for this yet, but can you please take a look at an example `ClickCounter` widget implemented in React [here](https://github.com/paperbits/paperbits-demo/tree/master/src/components/click-counter/react). Feel free to ping me if this example is not clear.

**Comment by azaslonov** [comment]
Hi @phfrc, to include the component (assuming you do ClickCounter), you need to just copy the entire folder and add register modules respectively:

**apim.design.module.ts**
`injector.bindModule(new ClickCounterEditorModule());`

**apim.runtime.module.ts**
`injector.bindModule(new ClickCounterRuntimeModule());`

**apim.publish.module.ts**
`injector.bindModule(new ClickCounterModule());`

Hope that helps.

**Comment by azaslonov** [comment]
@phfrc, just added better example and simple steps here: https://github.com/paperbits/examples/tree/master/ui-frameworks/react/components
