### ISSUE TITLE
Collapsible panel - how does it work?

### ISSUE THREAD

**Issue by danielmartenssonbyggtjanst** [Azure/api-management-developer-portal#1491]
Hi, 

I'm trying to add a collapsible panel (widget) inside my developer portal (access through azure portal). 
I don't understand how it's suppose to work. 
It's just an empty area. I can not edit anything except min/max width. And add content to it. 
After saving and publishing. I'm heading to a new browser window and having a look at the result. But it's just text. 
No collapsible. I was expecting like a collapsible panel, with a toggle function, showing/hiding content.
Like bootstrap example: [Bootstrap collapse](https://getbootstrap.com/docs/4.0/components/collapse/)

In edit mode:
![collapsible-panel](https://user-images.githubusercontent.com/47531163/138262565-fe0957ad-d96c-43e1-9b24-f537e0e8acba.PNG)

In view mode:
![collapsible-panel-result](https://user-images.githubusercontent.com/47531163/138263535-2ab60d9d-ca63-498b-90cf-fbeb3c32a043.PNG)

Where can I find documentation or tutorial regarding Collapsible panel?

Thanks!

**Comment by azaslonov** [comment]
Hi @danielmartenssonbyggtjanst, yeah, the name of it is a bit misleading. This widget collapses into a hamburger on smaller views and used mostly for menus. The widget you're referring to is coming a bit later this year.

**Comment by ahmedsza** [comment]
I am also looking at this and also confused.. Did this other widget ever get released. Looking for something like a normal collapsible panel. I can do this with custom HTML code but a built in widget would be better..
