### ISSUE TITLE
Parsing error(s): Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path ''

### ISSUE THREAD

**Issue by JBac** [Azure/api-management-developer-portal#1508]
Hi,

Getting this error whenever I make any change to the 'Frontend' JSON in any of my APIs:

Parsing error(s): Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path ''

Even if I just change the title and click save, I get this error, for example, all I've done here is add a '2' to the title:

![image](https://user-images.githubusercontent.com/9397535/140055407-987367eb-1a2c-47ed-95ea-d9d1f66420de.png)

If I add a new API or API version using the OpenApi import tool it works fine, there just seems to be something wrong with the editor

**Comment by ArkimeraMattias** [comment]
We are experiencing the same issue. We can not update any API definitions without this error showing up.

A speedy resolution to this issue would be appreciated.

**Comment by VitaliyKurokhtin** [comment]
We're rolling out fix for the issue, should be resolved very soon.

**Comment by mikebudzynski** [comment]
I will now close this issue, in the light of the fix being rolled out and the issue not being related to the developer portal.
