### ISSUE TITLE
Collaborate and read-only self hosted 

### ISSUE THREAD

**Issue by danielmartenssonbyggtjanst** [Azure/api-management-developer-portal#1512]
Hi, 
I've a question regarding self hosting. If I want to host it in azure. Make it possible to collaborate for those who have access through the azure portal. But still only "readable" for those who don't.
What I can see now is that a token will always be returned in /src/components/app/app.ts line 38.
const token = await this.authenticator.getAccessTokenAsString();

It will always return the managementApiAccessToken that is configured in config.design / config.publish.

So what I did was, 

1. npm run build-designer
2. Using azure storage tool in vs code I "deployed to static website via azure storage.."
3. Picked my designer folder. and then target storage $web.
4. The visited my site. Loading with toolbars. But it loads in incognito as well. 
    Desired behaviour would be to only load the readable page.

What should I do to create desired behaviour?

**Comment by mikebudzynski** [comment]
@danielmartenssonbyggtjanst, please reach out to Azure support. They will be able to assist you with the setup of the self-hosted portal.
