### ISSUE TITLE
Configure the operation-details widget

### ISSUE THREAD

**Issue by cristianhosu** [Azure/api-management-developer-portal#152]
I had the need to remove the "try it" button from the operation-details widget.
Please add the possibility to remove that button and make this widget read-only.

This will allow the portal to behave like a simple API docs page

**Comment by mikebudzynski** [comment]
Thanks @cristianhosu, I merged your feature request with a collective thread on this topic. At this moment you can achieve that with a self-hosted version.

**Comment by cristianhosu** [comment]
I know you can, that is how i worked around this limitation. But out of the box, that try it functionality will not allow me to block unauthorized users from executing it. They will click try it, the endpoint will hit APIM which in turn will count for billing and the response will be probably 401/403 if properly configured. Having to pay extra just because i want to remove one little button seems a bit weird.

**Comment by mikebudzynski** [comment]
The call shouldn't count for billing - the pricing model is based on a monthly fee, not per API execution.
