### ISSUE TITLE
Query Parameter "No default" option defaults to first value in list of values if provided in the Try It sidebar

### ISSUE THREAD

**Issue by nosvalds** [Azure/api-management-developer-portal#1529]
## Bug description

If you have a query parameter where you set "No default" and provide other optional values, the "Try It" sidebar defaults to the next possible value under "No default", rather than starting as blank (without a default) as expected.

## Reproduction steps

1. Go to an API -> Operation -> Edit Frontend -> Query
2. Define a query parameter that has optional values, but select "No default"
![image](https://user-images.githubusercontent.com/60047271/141995324-2e4628a9-c7b0-4994-b556-19e5f7d5dfba.png)

3. Navigate to the API in the Developer Portal
4. Click on "Try It"
5. See that the first value under "No default" is defaulted into the query parameter
![image](https://user-images.githubusercontent.com/60047271/141995526-cc5120b8-9bca-4be0-93a1-382e95c04df1.png)

## Expected behavior

I would expect that the query parameter would default to blank in "Try It" and not be added to the request, with a similar dropdown where you can select one of the optional values if necessary.

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-iati-dev

## Environment

 - Operating system: iOS
 - Browser: Google Chrome
 - Version: Version 95.0.4638.69 (Official Build) (x86_64)

## Additional context

My organisation has developed an Apache Solr API that we are serving through the Managed developer Portal. 

This API has a number of query parameters that depend on other query parameters being set. The dependent query parameters have values that I'd like to document in APIM, but if I do so, they are set in the "Try It" sidebar. I would expect "No default" to just leave the query param blank (providing a dropdown for the appropriate values if needed). The effect of this is that if the User does not need those query parameters they have to manually remove all of them from "Try It" before they can form a valid request.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
