### ISSUE TITLE
Pagination to be implemented in all widgets - For better user experience

### ISSUE THREAD

**Issue by Varun270489** [Azure/api-management-developer-portal#1531]
As of today we only have basic pagination for navigation . Not all pages or total pages with page numbers are visible in all widgets.
This can be enhanced for better user experience

**Comment by Varun270489** [comment]
any expected delivery date ?

**Comment by mikebudzynski** [comment]
> any expected delivery date ?

No, we don't have an ETA to share at this time.

**Comment by Varun270489** [comment]
I implemented pagination for api list and product list widgets. I raised pull request , Please review.  
ChangeSet - 374f0ebc482e404af8ed1a4ca1ddf385e101df46 

Hope I am able to contribute.

**Comment by mikebudzynski** [comment]
@Varun270489, it would be easier for us to review if you open a PR in this repository. Could you please do that?

**Comment by Varun270489** [comment]
@mikebudzynski Thanks for the response. I made a better pagination with enhanced feature , please check change set 7a67a8618068b3556e32495f258ff6bb2687f78e

**Comment by mikebudzynski** [comment]
Thanks, we will review it shortly.

**Comment by azaslonov** [comment]
The PR was merged.
