### ISSUE TITLE
Identitysettings reference case sensitive for Linux

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#1537]
## Bug description

[IdentitySettings reference ](https://github.com/Azure/api-management-developer-portal/blob/master/src/contracts/IdentitySettings.ts) will fail because it's referenced as identitySettings (lowercase i). Casing differences are problematic on Linux machines, but not an issue on Windows machines. 

Renaming this file to `identitySettings.ts` solves it. 

## Reproduction steps

1. Run `npm run publish` on a linux machine on the self-hosted portal.

## Is your portal managed or self-hosted?
self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.12.0

**Comment by azaslonov** [comment]
Fixed in scope of another issue.

**Comment by erwinkramer** [comment]
@azaslonov fixed in next release?

**Comment by azaslonov** [comment]
In another branch. But let me just cherry-pick it right now: #1583

**Comment by erwinkramer** [comment]
Cool, thanks.
