### ISSUE TITLE
"Your developer portal has not been published yet." - But it has...

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#1538]
## Bug description

I have published our developer portal every other month for the past year. It's currently active and I am using it right now in another tab. But the Azure Portal is now telling me: "Your developer portal has not been published yet."

I'm worried that if I click `Publish` that it will reset my current portal to factory defaults. Can someone please comment on why it's confused and what will happen if I publish now? I'd like to publish the latest updates from Microsoft, the last time I published was in August or September.

Thanks

**Comment by mikebudzynski** [comment]
@krispenner, could you please reach out to Azure support for assistance and troubleshooting the issue? They will be able to analyze the problem and walk you through the publishing.
