### ISSUE TITLE
Operation: Details widget no longer renders HTML content

### ISSUE THREAD

**Issue by aaron-infomedia** [Azure/api-management-developer-portal#1540]
## Bug description

As title. Earlier versions of the Dev Portal would render HTML that was nested in the OpenAPI specification. For example, a table could be added into the description element and it would appear on the portal. This no longer works though the HTML is still in the OpenAPI specification.

Any text preceding an HTML tag renders without problem, but as soon as a tag is found, everything after that point in the description is ignored.

## Reproduction steps

1. Go to an API Management service and go to APIs
2. Click on an API and then choose an Operation
3. Open the Form-Based Editor and switch to the Request tab.
4. Add some text in the field, including some HTML, for example:

```
Description of the API
<h4>Parameter List</h4>
The following parameters must be added..... etc
```

5. Save the Operation
6. When viewing the operation on Dev Portal everything from the <h4> tag onwards will not show. Only "Description of the API" will appear.

## Expected behavior

The HTML should render.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

Portal was published on 23rd November 2021 @15:30 UTC+0 so will be using whatever version the Managed portal is using on that date.

## API Management service name

ims-uks-apimgr-frontend

## Environment

 - Tested in all Windows browsers.

## Additional context

Unfortunately I don't have a screenshot from how it used to appear, but the HTML used to render perfectly and enriched our documentation.

**Comment by mikebudzynski** [comment]
@aaron-infomedia, thanks for reporting the regression. We're already working on a fix.

**Comment by aaron-infomedia** [comment]
I should have mentioned that this is affecting the Description fields for the Method, Request and Response. Possibly other places too but these are the only ones we have used.

![image](https://user-images.githubusercontent.com/61697128/143854566-31277879-a051-4c99-9c2f-656875c4b106.png)

![image](https://user-images.githubusercontent.com/61697128/143854615-3018b354-680c-4a84-9a9e-b9c68ec99be5.png)

![image](https://user-images.githubusercontent.com/61697128/143854663-d48238fe-8598-4b2d-9f91-d36c04e493b2.png)

**Comment by aaron-infomedia** [comment]
Unfortunately this is still occurring in the current release (managed portal). I have republished as follows:

_Last published
Revision 202112071023 was created on 12/7/2021, 10:23:29 AM and published on 12/7/2021, 10:24:28 AM._
(Times in UTC+0)

Here is an example of one of the full Descriptions we have set:

```
This API method allows you to send an SMS message to an end user. Note that the Sandbox version of this API will not work end-to-end, ie. an SMS will not arrive on a handset.

<h3>Test Scenarios</h3>
To test various scenarios in the Sandbox environment, use the following values when making API requests. Any other combination of values will give a successful response.

<div role="table" class="table-preset table-preset-schema">
    <div class="d-contents" role="rowgroup">
        <div class="d-contents" role="row">
            <div role="cell" class="table-preset-head text-truncate">Input Field</div>
            <div role="cell" class="table-preset-head text-truncate">Input Value</div>
            <div role="cell" class="table-preset-head text-truncate">Status</div>
            <div role="cell" class="table-preset-head">User Friendly Message</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">username</div>
            <div role="cell" style="font-style: italic;">{blank}</div>
            <div role="cell">91</div>
            <div role="cell">There is no account specified for the username and password</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">md5Hash</div>
            <div role="cell" style="font-style: italic;">{blank}</div>
            <div role="cell">92</div>
            <div role="cell">The MD5 hash supplied was invalid</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">scheduleFor</div>
            <div role="cell" style="font-style: italic;">{blank}</div>
            <div role="cell">94</div>
            <div role="cell">The ScheduleFor DateTime is invalid</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">smsMessage</div>
            <div role="cell" style="font-style: italic;">{blank}</div>
            <div role="cell">100</div>
            <div role="cell">No SMSMessage supplied</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">msisdnList</div>
            <div role="cell" style="font-style: italic;">{missing}</div>
            <div role="cell">95</div>
            <div role="cell">No MSISDNDetails object supplied</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">msisdnList</div>
            <div role="cell" style="font-style: italic;">{empty}</div>
            <div role="cell">96</div>
            <div role="cell">No MSISDN(s) in MSISDNDetails object</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">msisdn</div>
            <div role="cell">123456</div>
            <div role="cell">97</div>
            <div role="cell">MSISDN missing country code prefix</div>
        </div>
        <div class="d-contents" role="row">
            <div role="cell">msisdn</div>
            <div role="cell">9876543210</div>
            <div role="cell">98</div>
            <div role="cell">MSISDN validation error</div>
        </div>
    </div>
</div>
```

Only the first sentence of the description is displayed on the portal:

![image](https://user-images.githubusercontent.com/61697128/145012861-af486b6b-e6d4-4d4f-a9db-285f362b3ae3.png)

The divs should be rendered above the "Request" header.

**Comment by azaslonov** [comment]
@aaron-infomedia, the release of the managed version is still in progress. It should reach all the regions in a few days.

**Comment by aaron-infomedia** [comment]
Hi @azaslonov

It seems the html is being brought in now, but all attributes are being stripped from the tags. Take a look at the screenshot below.

![image](https://user-images.githubusercontent.com/61697128/145185582-19202843-84f0-4846-9744-9cdf27ca51c5.png)

The source for this is:

```
<div role="table" class="table-preset table-preset-schema">
    <div class="d-contents" role="rowgroup">
        <div class="d-contents" role="row">
            <div role="cell" class="table-preset-head text-truncate">Input Field</div>
            <div role="cell" class="table-preset-head text-truncate">Input Value</div>
            <div role="cell" class="table-preset-head text-truncate">Status</div>
            <div role="cell" class="table-preset-head">User Friendly Message</div>
        </div>
```

All of the "role" and "class" attributes have been removed. The result is the content does not render properly:

![image](https://user-images.githubusercontent.com/61697128/145186010-3dd7c61c-d334-4700-a91c-774158471615.png)

With the attributes in place this should look like a table, similar to the following:

![image](https://user-images.githubusercontent.com/61697128/145186208-a928a942-ac0b-44dc-81f5-5378ea87827a.png)

**Comment by ArkimeraMattias** [comment]
Any update on this?

This bug is affecting our public development portal and our clients. We are using the Azure Managed Portal.

**Comment by jsorohova** [comment]
Hello @ArkimeraMattias, classes should work now in the managed version.

**Comment by aaron-infomedia** [comment]
@jsorohova - I can confirm that `role` and `class` attributes are working now, however `style` attributes are still being removed.

**Comment by ArkimeraMattias** [comment]
> Hello @ArkimeraMattias, classes should work now in the managed version.

> @jsorohova - I can confirm that `role` and `class` attributes are working now, however `style` attributes are still being removed.

Yes. We have identified the following `style` issues on our development portal within the Operation: Details panel.

```
<p>This is not rendered!</p>
```

```
<ul>
    <li>No</li>
    <li>list</li>
    <li>is</li>
    <li>rendered</li>
</ul>
```

Will this be fixed anytime soon?
