### ISSUE TITLE
Uncaught Promise error in reports page

### ISSUE THREAD

**Issue by restlessankyyy** [Azure/api-management-developer-portal#1543]
**Uncaught Promise error in reports page upon clicking on 90 days statistics**

## Bug description

In the user reports page, while filtering the stats for 90 days, we receive the below error.

`theme.js:51384 Cannot read properties of undefined (reading 'toUpperCase')
(anonymous) @ theme.js:51384
(anonymous) @ theme.js:51366
__awaiter @ theme.js:51362
trackError @ theme.js:51383
handlerPromiseRejection @ theme.js:186989
`

`theme.js:80108 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at update (theme.js:80108)
    at a.$.l (theme.js:8998)
    at Function.yd (theme.js:8974)
    at Function.zd (theme.js:8974)
    at Function.ha (theme.js:8973)
    at Function.Hc (theme.js:8973)
    at Function.notifySubscribers (theme.js:8957)
    at Function.xa (theme.js:8962)
    at Reports.c [as reportByCallsGeo] (theme.js:8961)
    at Reports.<anonymous> (theme.js:156047)`
## Reproduction steps

1. Go to 'Reports tab in developer portal'
2. Filter the results to 90days by clicking on the 90days button
3. Wait for the page to load the data.
4. Open the dev console in the browser to see the error.

## Screenshots

![Screenshot 2021-11-24 at 10 19 48](https://user-images.githubusercontent.com/23651587/143210092-552c8396-ceab-4f5e-b48e-ec16c0e2784b.png)

## Is your portal managed or self-hosted?

Managed / Self-hosted -- Experiencing in both the portals.

## Release tag or commit SHA (if using self-hosted version)

2.11.5

## API Management service name

[api-dev]

## Environment

 - Operating system: [Windows, MacOS]
 - Browser: [Brave]
 - Version: [Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)]

**Comment by restlessankyyy** [comment]
This bug is noticeable only if when we are using APIM with Application Gateway in a private/ internal virtual network. The reports page in APIM loads with all the graphs except Geo-location graphs. The Geo-location graphs try to map the Global IPs to the respective geo-location. However, in our case, the IP is internal {Private} which doesn't map to any of the global geo-locations.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
