### ISSUE TITLE
Api details widget - tags are always show as untagged 

### ISSUE THREAD

**Issue by sjvarun** [Azure/api-management-developer-portal#1547]
When we are in api details page , on the left side section we have tags information along with other api verbs
These tags information is always shown as "untagged" (screenshot 1) . Also the tags information is not available in Filter (screen shot 2) 

## Expected behavior

Tags details must be visible with option to filter tags in Filter . 

## Is your portal managed or self-hosted?

Both Managed & Self-hosted

## Environment

 - Operating system: Any
 - Browser: Any
 - Version: 2.12.0

![image](https://user-images.githubusercontent.com/17843040/143863648-ec7196e9-f79b-4b14-957a-e510b7433186.png)

![image](https://user-images.githubusercontent.com/17843040/143863852-4c45c55b-fb34-420f-938b-08354624336b.png)

**Comment by mikebudzynski** [comment]
@sjvarun, most likely you have not defined the tags or assigned the tags to API operations in the API Management service. The "Untagged" badge shows up, because none of your operations have tags and you have selected "Group by tags". Please, reach out to Azure support for assistance, if needed.
