### ISSUE TITLE
Top navigation menu is not clickable

### ISSUE THREAD

**Issue by margani** [Azure/api-management-developer-portal#1548]
## Bug description

Top navigation is fine in the home page but when I go to the API list page and click on it, nothing happens. It sees an element is blocking it.

## Reproduction steps

1. Click on "Explore APIs"
2. One of menu items on top, like Sign In or Sign Up

## Expected behavior

It should be clickable.

## Is your portal managed or self-hosted?

Managed

## API Management service name

inxn-a1-api

## Environment

 - Operating system: Ubuntu
 - Browser: Edge and Chrome
 - Version: Chrome 96, Edge 96

## Additional context

When I add styling to one of the navigation parent elements, like, z-index: 1, and height: 60px, then it's clickable. As APIM developer portal doesn't support custom CSS, how can I fix it, using the administrative interface?

![apim-dev-portal-top-navigation](https://user-images.githubusercontent.com/46093/143919049-054cd0a1-3c99-47f2-9e92-bbcc0434c935.gif)

**Comment by margani** [comment]
Is there any update on this?

**Comment by fluent123** [comment]
Hello, I have the same issue. Is there any updates or solution how it could be fixed via administrative tools?

**Comment by fluent123** [comment]
In my case the solution was to set "Stick to" to "None" for page content section on a layout view. 
![image](https://user-images.githubusercontent.com/32296738/234232452-b3d7c580-c108-422d-9515-64e6490b3d19.png)

**Comment by mrcarlosdev** [comment]
This issue was solved some time ago. Closing this. Please reopen if still facing this issue.
