### ISSUE TITLE
Could not add any new section or widget if everything is deleted from Default Layout

### ISSUE THREAD

**Issue by hkd801** [Azure/api-management-developer-portal#1550]
On the default Layout if we delete all existing sections and widgets, we are left with a blank CONTENT section.
Now we no longer have the '+' icon or Edit icon to add anything.

We do see a delete widget icon on top left corner of the CONTENT section, but clicking on this only give an error "Oops, something went wrong."

![Deveoper Portal Isssue](https://user-images.githubusercontent.com/72554816/144279359-ecaa40e2-51d7-44c4-afca-ef201ecf90df.png)
T

**Comment by azaslonov** [comment]
Fix for managed version is being rolled out.
