### ISSUE TITLE
Support adding client certificates when using the 'Test API' feature in the Developer portal

### ISSUE THREAD

**Issue by glav** [Azure/api-management-developer-portal#156]
**Is your feature request related to a problem? Please describe.**
We have a few customers who use client certificates as part of the authentication process to the API's managed by APIM. in APIM we have defined policies to check various aspects of incoming client certs such as thumbprint (for example). When trying to test API's using the developer portal for registered users, they are unable to execute any API functions as there is no provision to attach a client certificate using the developer portal, to satisfy the APIM policy.

**Describe the solution you'd like**
Minimum would be ability to associate client certificates with accounts which can then be used/passed along when making requests via the Developer portal. Ideal would be a method of registering extensions, that can augment requests being generated from the developer portal such that a 'Client certificate' extension could be registered, a 'some weird auth header extension' could be registered and allow external contributions to fulfil any odd request via the developer portal.

**Describe alternatives you've considered**
None really, apart from only being able to use the likes of Postman tooling to play with the API but have to flick between that and the dev portal to view the associated documentation, subscription keys etc.

**Additional context**

**Comment by mikebudzynski** [comment]
Closing this Issue, the feature request is available to upvote or comment on here: https://feedback.azure.com/forums/248703-api-management/suggestions/17047705-client-certificate-authentication-in-developer-co
