### ISSUE TITLE
HTML snippets not rendered on API operation description fields

### ISSUE THREAD

**Issue by quental** [Azure/api-management-developer-portal#1570]
## Bug description

We embed HTML snippets in API operation description fields to display rich content, such as tables. These snippets used to be interpreted perfectly and the content was rendered, but this is no longer the case: it seems like the HTML tags are stripped out and the content is being displayed as plain text.
While we're unable to pinpoint the exact version in which this started happening, we can say for sure that the latest portal version we saw this working correctly was 20210921113247 and the earliest version we saw the broken behavior was 202112010807. Updating to the latest version also doesn't solve it.

![image](https://user-images.githubusercontent.com/11029522/146096464-0bce6b2b-a9b5-4c5a-867a-608d0f359642.png)

## Expected behavior

HTML snippets are correctly rendered.

![image](https://user-images.githubusercontent.com/11029522/146096673-3e8a2c17-067a-4681-9c72-e041ddd7eae7.png)

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
@quental, this issue has been fixed in #1568. We're making a hotfix for managed version right now.

**Comment by quental** [comment]
> @quental, this issue has been fixed in #1568. We're making a hotfix for managed version right now.

Excellent! Thank you for the prompt reply.
Should I then expect an update to be available in a couple of hours?

**Comment by azaslonov** [comment]
Unfortunately, I'll take 2-3 days to reach every region.
