### ISSUE TITLE
Migration from MSAL v1 to MSal v2 in APIM

### ISSUE THREAD

**Issue by Megha86834** [Azure/api-management-developer-portal#1607]
Hello ,I am trying to migrate my APIM from MSAL v1 to MSAL v2 .
But the issue that I am facing is when I sign in using MSAL  v2 the page does not redirects to authenticated home page after successful sign in ,it goes back to sign in page. Please look into this issue urgently.

**Comment by mikebudzynski** [comment]
@Megha86834, what do you mean by "trying to migrate my APIM from MSAL v1 to MSAL v2"? Do you mean you're attempting to make changes to the code base in the self-hosted portal?

**Comment by Megha86834** [comment]
Hi Mike
yes I am making changes in the code base in the self hosted portal. I am migrating from MSAL v1 to MSAL v2 created a new sign in in widget for the same. When I sign in using "loginPopup"  it successfully logs in , also receive the desired response but it does not redirects to authenticated home page. Please help me with the same.
Thanks in adv.

**Comment by Megha86834** [comment]
/**
     * Handles the response from a popup or redirect. If response is null, will check if we have any accounts and attempt to sign in.
     * @param response 
     */
    private async handleResponse(response: AuthenticationResult | null) {

        if (response !== null) {
            this.account = response.account;

        } else {
            this.account = this.getAccount();
        }
        const isUserSignedIn = this.usersService.isUserSignedIn();

        if (isUserSignedIn) {
            this.usersService.navigateToHome();
            return;
        }

    }

    /**
     * Calls loginPopup or loginRedirect based on given signInType.
     * @param signInType 
     */
    public login(signInType: string): void {
        if (signInType === "loginPopup") {
            this.myMSALObj.loginPopup(this.loginRequest).then((resp: AuthenticationResult) => {
                this.myMSALObj.setActiveAccount(resp.account);
                console.log(resp.account);
                this.handleResponse(resp);
            }).catch(console.error);
        } else if (signInType === "loginRedirect") {
            this.myMSALObj.loginRedirect();
        }
    }

**Comment by mikebudzynski** [comment]
@Megha86834, we're not able to provide support for custom changes in the portal's codebase, so I will be closing this issue. Keep in mind that we do have plans to migrate to MSAL v2 in the future.

**Comment by keg7271** [comment]
@mikebudzynski your team could at least let us know why the id_token received by MSAL v2 isn't valid against the /Identity endpoint of the APIM management API.  To just say "not supported" is not appropriate in this case.

**Comment by mikebudzynski** [comment]
@keg7271, based on what @Megha86834 wrote above, I was under the impression that the token works:

> When I sign in using "loginPopup" it successfully logs in , also receive the desired response

Is that not the case?

**Comment by keg7271** [comment]
I believe she has used MSAL v2 to get the id_token for the but when using the id_token to exchange for the SAS from APIM it fails with invalid token.

-Keith
________________________________
