### ISSUE TITLE
Undocumented endpoints for blob access and self-hosted backend API

### ISSUE THREAD

**Issue by tdysko-star** [Azure/api-management-developer-portal#1615]
Hello, 
I got two questions about undocumented enpoints the developer portal code is using. 
**First**: 
I think that the only way to backup or migrate managed developer portal blob files is by using secret from undocumented endpoint hidden under _/portalSettings/mediaContent/listSecrets_.

I found out about it, just because I saw you used it in you migration code: 
https://github.com/Azure/api-management-developer-portal/blob/7177e34b30e3ff33ef925fe249d40254fe73a996/scripts.v3/utils.js#L391

I cannot see it here:
https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/portal-settings

So my question would be, if we can rely on that endpoint in our automation scripts? And also will this documentation be updated?
**Second**:
Do we have any documentation for endpoints under "https://<service-name>.developer.azure-api.net" domain?

It looks like with GET requests we get developer portal HTML content, and with  POST requests (as you call them here for example https://github.com/Azure/api-management-developer-portal/blob/5976c1ae027e3f5b0806ddad9f9524374ba9cc71/src/services/backendService.ts#L117) we got responses from some REST API.

So my second question is - do we have those endpoints documentation somewhere? I couldn't find any, am I missing something?
Right now it seems dangerous to use and modify self-hosted portal, if it uses undocumented APIs, so if there is really no docs, maybe it's worth creating them.

**Comment by mikebudzynski** [comment]
@[tdysko-star](https://github.com/tdysko-star), apologies for a delay in the response.

> if we can rely on that endpoint in our automation scripts? And also will this documentation be updated?

Although you can safely use the scripts that we publish in this GitHub repository, undocumented endpoints may change any time and shouldn't be relied on in custom implementations. @azaslonov, is there a documented endpoint for getting blob storage credentials?

> do we have those [developer portal backend] endpoints documentated somewhere?

Not at the moment. We're actively working on migrating all actions that are performed by published portals into the developer portal backend API. Once that work is complete, we will publish the full documentation and client SDK for the new endpoints.
