### ISSUE TITLE
The pagination UI is misleading from the usability point of view

### ISSUE THREAD

**Issue by danielmokaomv** [Azure/api-management-developer-portal#1628]
## Change request

This is actually not a bug, but a change request. Many of our portal users reported that they find the UI of the pagination not clear and misleading, for example at the APIs or Products page of the developer portal. Namely, when we look at the pagination UI component, at first it always shows number "1" (meaning it is the first page) and an arrow to navigate to the next page. The users can easily think that there is only one page of the given items. Usually it is not the convention to implement the UI of a pagination component. Most of the time a pagination is implemented in the way that it shows all the numbers (or the first ten) of the actual pages, in a clickable way, next to the navigation arrows.

Here is an image of it:

![image](https://user-images.githubusercontent.com/84009352/151553842-8607e756-62e1-4236-89fc-d2920b8eb950.png)

And here is an example image below about how a pagination UI component looks like, usually:
![image](https://user-images.githubusercontent.com/84009352/151553929-2d2c6159-fad0-4109-8c55-b73f27c27267.png)

We are of the opinion that this change request would improve the UX of the developer portal. Could you please consider this and change it to follow the convention of having such an pagination UI component? 

Thank you!

## Reproduction steps

1. Go to Products page
2. Go to the end of the products list
3. Look at the pagination UI component

## Expected behavior

By looking at the pagination component, the user can figure out easily how many pages are there, or the minimum number of pages.

## Actual behavior

By looking at the pagination component, the user can easily think that there is only one page of the given items.

**Comment by azaslonov** [comment]
Hi @danielmokaomv, this component has been reworked in #1544 and #1578. It will be out in managed version in a few days. It doesn't look exactly like that, but the approach is similar.
