### ISSUE TITLE
Graphql Interface integration breaks the build

### ISSUE THREAD

**Issue by restlessankyyy** [Azure/api-management-developer-portal#1634]
## Bug description

Graphql Interface integration breaks build #1634.

## Reproduction steps

1. After cloning and updating the config details, npm start fails with the below error. 

```
ERROR in /github/workspace/node_modules/graphql-language-service/node_modules/graphql-language-service-interface/src/getAutocompleteSuggestions.ts
246:6-10
[tsl] ERROR in /github/workspace/node_modules/graphql-language-service/node_modules/graphql-language-service-interface/src/getAutocompleteSuggestions.ts(246,7)
      TS2345: Argument of type '"Name" | "Document" | "OperationDefinition" | "VariableDefinition" | "Variable" | "SelectionSet" | "Field" | "Argument" | "FragmentSpread" | "InlineFragment" | "FragmentDefinition" | ... 52 more ... | "Type"' is not assignable to parameter of type '"NamedType" | "TypeCondition"'.
  Type '"Name"' is not assignable to type '"NamedType" | "TypeCondition"'.
ts-loader-default_ab4862433a94faea
```

[
<img width="1300" alt="error" src="https://user-images.githubusercontent.com/23651587/152023968-d81a604b-f314-44d4-a3af-8a5c89de4ddd.png">
](url)

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release `2.13`

## Environment

 - Node version: 16.x.x
 - Build Tool: Github Action

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by mikebudzynski** [comment]
@restlessankyyy, we're not able to reproduce this issue. You can try cleaning and reinstalling the dependencies. If the issue persists, please reach out to Azure support.
