### ISSUE TITLE
Response latency details Missing in new API developer portal

### ISSUE THREAD

**Issue by gcsenthil** [Azure/api-management-developer-portal#1636]
## Bug description

Response latency missing in new azure API developer portal

## Reproduction steps

1. Go to 'developer portral'
2. select service and then operation
3. Click on try button and send the request
4. Response has the following details, but missing the response latency

HTTP response
HTTP/1.1 200 OK

content-encoding: gzip
content-type: application/json; charset=utf-8
date: Wed, 02 Feb 2022 04:39:09 GMT
request-context: appId=cid-v1:24c01213-58f1-48f7-89f2-f3e563178aa4
transfer-encoding: chunked
vary: Accept-Encoding

## Expected behavior

The old developer portal contains these details to identify the execution time of the request

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by gcsenthil** [comment]
[
<img width="960" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31710889/152104580-ea8817b8-9137-4816-975f-45330292df67.png">
](url)

**Comment by gcsenthil** [comment]
<img width="481" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31710889/152104668-c59cf5fb-2221-4bf7-bb8d-5bde33be0f2b.png">

**Comment by gcsenthil** [comment]
> @gcsenthil, thank you for opening this issue. We will triage it within the next few business days.

thank you for taking action on my request.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
