### ISSUE TITLE
GraphQL Introspection query returns 403 Forbidden

### ISSUE THREAD

**Issue by RuiLoureiro** [Azure/api-management-developer-portal#1638]
## Bug description

When running an introspection query for a GraphQL API hosted on APIM, the response is `403 Forbidden`. Regular queries work.

This happens when using an external API client (I'm using Insomnia), it does not happen on the `Test` tab in the Azure Portal.
When querying my API directly (without going through APIM), the issue is no longer present.

## Reproduction steps

Run the following query using an external API client (I'm using Insomnia):

```graphql
{
    query IntrospectionQuery {
      __schema {
        queryType { name }
        mutationType { name }
        subscriptionType { name }
        types {
          ...FullType
        }
        directives {
          name
          description
          locations
          args {
            ...InputValue
          }
        }
      }
    }
}
```

The response is

```html
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
```

## Expected behavior

Expected to get a 200 OK

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: macOS 11.6
 - Insomnia v2021.7.2
<img width="1190" alt="Captura de ecrã 2022-02-03, às 13 27 10" src="https://user-images.githubusercontent.com/16242214/152351817-d4ca5a94-fe64-47a5-aa3e-9e5a0b5f459e.png">

**Comment by azaslonov** [comment]
@RuiLoureiro, seems like App Gateway blocks this request. I have to refer you to MS Support to resolve the issue. This GitHub repository dedicated to API Management Developer portal questions.
