### ISSUE TITLE
Text color of button not changing in Hover state

### ISSUE THREAD

**Issue by pselvanayagam** [Azure/api-management-developer-portal#1645]
When I am trying to change the text color of the button to any color in Hover state, it is always changes to "Text-black".
[
![Bug-Button](https://user-images.githubusercontent.com/99399953/153394589-d56af464-862c-4070-b74d-732fef4e8ccd.JPG)
](url)
## Reproduction steps:
1) Go to APIM Developer portal in edit mode.
2) Go to Styles-->Buttons
3) Edit the button, change the State to Hover and under the Typography, change the Text-color.

## Expected behavior:
The text color of the button should change to any color in Hover state.

## Is your portal managed or self-hosted?:
Managed Portal

**Comment by azaslonov** [comment]
@pselvanayagam, the issue has been fixed. Please feel free to re-open if you still encounter the issue.
