### ISSUE TITLE
API Portal is slow (API with 100+ methods) are there any ways to enhance performance

### ISSUE THREAD

**Issue by frankdewaelle** [Azure/api-management-developer-portal#1655]
API Portal is slow (API with 100+ methods) are there any ways to enhance performance

Check https://apipp.descartes.com/api-details#api=pixi (selfexplanatory)

**Comment by azaslonov** [comment]
@frankdewaelle, 100+ operations should not affect the performance, I guess something else is going on with your service. I have to send you to MS Support, so they could investigate it further.

**Comment by frankdewaelle** [comment]
The number of operations is 482, and the problems are with the "API Details" page
![401](https://user-images.githubusercontent.com/65818117/154329462-94ed96f3-bfe4-4636-ac73-138d1ce074ea.png)
