### ISSUE TITLE
APIM Dev Portal creates a schema (under the covers) that slows down loading API details

### ISSUE THREAD

**Issue by frankdewaelle** [Azure/api-management-developer-portal#1659]
Hi,

it seems that APIM is creating a schema file with all "definitions" (in my case 620d1f4b519e23080cd4e8c4) that takes ages to load.
And it is (trying to get it) loaded every time an operation is selected.
![schema2](https://user-images.githubusercontent.com/65818117/154531076-6b59eb98-a049-44dd-89ee-2814fd2e1b42.jpg)
![schema](https://user-images.githubusercontent.com/65818117/154531085-347d0e4b-05da-40bc-b160-4c4fe296bf29.jpg)

**Comment by frankdewaelle** [comment]
![image](https://user-images.githubusercontent.com/65818117/154663474-6d787364-305a-4821-9956-b45f1bf3f92d.png)

**Comment by frankdewaelle** [comment]
It is not really workable like this way. We cannot release this to customers.

**Comment by mikebudzynski** [comment]
> It is not really workable like this way. We cannot release this to customers.

Feedback taken, I agree that 1+ min load times are not acceptable. We need to evaluate our options for optimizations.

**Comment by azaslonov** [comment]
The issues has been addressed on the MAPI side, the fix is being rolled out.
