### ISSUE TITLE
No Error or Warning Displayed in Sign Up page when user has outstanding activation email

### ISSUE THREAD

**Issue by nosvalds** [Azure/api-management-developer-portal#1660]
## Bug description

When a user has used the Sign Up form, but hasn't received or clicked the activation link in the activation email. If they try to Sign Up again, there is no error displayed to the user in the Sign Up form. It just looks like the Captcha is broken to them.

## Reproduction steps

1. Go to Sign up form
2. Fill out fields
3. Click Sign Up
4. Don't click the activation link in the email received
5. Go to Sign up form
6. Fill out fields (with same email)
7. Click Sign Up
8. The Captcha Resets but no error message is shown, user thinks Captcha is wrong.

## Expected behavior

The user should be shown a message in the form that they have already tried to sign up with that email. Ideally it would also give them an option to Resend the email.

The message could display here like other form validations.
![image](https://user-images.githubusercontent.com/60047271/154659550-3f967a5e-64c5-454e-8b3c-0546a0adfd3c.png)

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-iati-PROD

## Environment

 - Operating system: MacOS
 - Browser: Firefox 97.0, Chrome 98.0.4758.102

## Additional context

You can see the POST request goes out and a 400 is returned with the validation info:
https://developer.iatistandard.org/signup [HTTP/2 400 Bad Request 1519ms]

```json
{"code":"ValidationError","message":"One or more fields contain incorrect values:","details":[{"code":"IdentifierAlreadyInUse","target":"email","message":"User with specified identity already exists"}]}
```

This just needs to be displayed in the front end.

Console:
![image](https://user-images.githubusercontent.com/60047271/154659910-319887df-bff5-4c6a-8124-db789b430b31.png)

**Comment by nosvalds** [comment]
Didn't see this ticket before: https://github.com/Azure/api-management-developer-portal/issues/1448

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
