### ISSUE TITLE
Try out - Does not load Subscription key & Add new parameter throws error 

### ISSUE THREAD

**Issue by Varun270489** [Azure/api-management-developer-portal#1662]
Try out - Does not load Subscription key & Add new parameter throws error  

## Bug description

API List -> Navigate to Operation details page and upon opening try out button - Screen does not load with Subscription keys event though products with subscription exists.

## Reproduction steps

1. Go to Api List -> Click on any API -> Opens operation detail s -> 
2. Click on Try out button -> Authorization & Subscription keys are present
3. But Subscription keys are not displayed for a product with subscription that the api is part of.
4. Also adding new parameters will display error "ApiId not added"

## Expected behavior

Subscription keys were visible in old release 

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

Release 2.13.0

## Additional context

Issue in release 2.13.0

**Comment by azaslonov** [comment]
Hi @Varun270489, can you please send your service name to apimportalfeedback@microsoft.com. We'll take it from there.
