### ISSUE TITLE
API Details Page: Redirection to API Details page after login, unable to redirect to specific endpoint details page

### ISSUE THREAD

**Issue by patidar-jaishree** [Azure/api-management-developer-portal#1672]
## Bug description

Redirection to API Details page after login, unable to redirect to specific endpoint details page.
URL - https://\<ServiceName\>.developer.azure-api.net/api-details#api=echo-api&operation=remove-resource
After Login redirects to - https://\<ServiceName\>.developer.azure-api.net/api-details
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/41952531/156112179-11653844-3ed5-4b7c-be0b-b6962d2aff39.png">

## Prerequisites

- API added to a Product which requires Subscription and have access control set to "Administrators, Developers"
- API Management service - Settings - Anonymous users - Redirect anonymous users to sign-in page - Checked

## Reproduction steps

1. Hit URL - 'https://\<ServiceName\>.developer.azure-api.net/api-details#api=echo-api&operation=remove-resource' 
2. User gets redirected to Sign-in Page with URL (https://\<ServiceName\>.developer.azure-api.net/signin?returnUrl=/api-details#api=echo-api&operation=remove-resource)
3. Login using valid credentials.
4. User gets redirected to API details page and selects echo-api from dropdown

## Expected behavior

It should redirects to the relevant API's detail page (ie https://\<ServiceName\>.developer.azure-api.net/api-details#api=echo-api&operation=remove-resource). 
Once it redirects to the right API details page, the title along with change log button should be visible
![image](https://user-images.githubusercontent.com/41952531/155969617-6332e628-3128-4b4f-83df-c9cb58179171.png)

## Actual behavior
Unable to redirect to specific api details page. (redirects to https://\<ServiceName\>.developer.azure-api.net/api-details)
![image](https://user-images.githubusercontent.com/41952531/155955461-c6ba4f58-3509-42c7-9848-313c73029172.png)

## Is your portal managed or self-hosted?

Managed 

## Additional context

There is a dropdown for APIs, On selecting an API UI is not displaying section for API Definition and Change logs section.
Note: On Refresh of page, getting the section displayed.

Missing Section:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/41952531/155955158-2e1cd9cc-192f-43cb-9252-7a492188b255.png">

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
