### ISSUE TITLE
CI/CD: Developer portal content synchronicity in different environments

### ISSUE THREAD

**Issue by phfrc** [Azure/api-management-developer-portal#1677]
## Bug description

Hey 😄

Working on a **self-hosted** version of the Azure Developer Portal, I've been trying to create a workflow to deploy the project on different testing environments. I'm relying on **Github Actions** for this.

My workflow logic [(main.yml)](https://github.com/BeMoTech/api-management-developer-portal/blob/develop/.github/workflows/main.yml) would be to:
- Generate /designer and /website folders with `npm run build` and `npm run publish`
- [Upload artifacts](https://github.com/actions/upload-artifact)
- [Download artifacts](https://github.com/actions/download-artifact)
- [Deploy to Azure Storage](https://github.com/TravisSpomer/deploy-to-azure-storage)

For each environment, we should have the designer as well as the runtime version of the portal.
With my current workflow, secrets are replaced in the build-[env] step for each environment. Although, the issue I'm facing is when modifications are made through the designer, they aren't included in the deployment from one environment to another. For instance, I'm able to see my custom widgets (in /community) in dev as well as UAT but the content that has been modified through the design in the dev environment isn't automatically deployed to UAT.

While looking for some answers, I was able to find:
- [Automate developer portal deployments](https://docs.microsoft.com/en-us/azure/api-management/automate-portal-deployments) talking about the scripts that are available in the source code. I'm having a hard time understanding if the migrate.js script would be an answer to this synchronicity issue. I've been seeing some answers for the managed portal but when it comes to the self-hosted, documentation / code comments are a bit contradictory. From what I gathered, I was thiking of calling the script from my workflow. Would you be able to point me in the right direction to deploy content as well?

Thanks in advance.

## Reproduction steps

1. Create a PR from a working branch to /develop
2. When approved, this PR will launch the workflow in Github Actions
3. When deployed, dev and UAT will have the right source code and configuration (config.json) but not the same content (UAT would have the default contoso portal in UAT)

## Expected behavior

When approved, the workflow would deploy to next the environment the source code as well as the content (paperbits modifications done through the designer). On all environments, the content as well as the source would be the same.

## Is your portal managed or self-hosted?

Self-hosted

**Comment by mikebudzynski** [comment]
> [Automate developer portal deployments](https://docs.microsoft.com/en-us/azure/api-management/automate-portal-deployments) talking about the scripts that are available in the source code. I'm having a hard time understanding if the migrate.js script would be an answer to this synchronicity issue. I've been seeing some answers for the managed portal but when it comes to the self-hosted, documentation / code comments are a bit contradictory. From what I gathered, I was thiking of calling the script from my workflow. Would you be able to point me in the right direction to deploy content as well?

Yes, you can use the `migrate.js` script to copy content (pages, styling, layouts etc.) from a source API Management service to a destination API Management service. After you execute the script, the content should appear in your destination portal's administrative panel. Publish your destination portal to have the content also reflected in your published portal. The script works for both managed and self-hosted portals, with the exception that the automated publishing doesn't work for the self-hosted portals.

If you need assistance with running this script, reach out to Azure support.
