### ISSUE TITLE
Is Oauth 2.0 ROPC implemented in the new developer portal?

### ISSUE THREAD

**Issue by Alejo677** [Azure/api-management-developer-portal#1678]
I’m try to implement a Oauth2 ROPC flow  in the new developer portal.

When I add my user and password I’m getting the next error in green:

 
![image](https://user-images.githubusercontent.com/46354569/156201095-02149d12-8fe7-4f04-8e97-f358442474de.png)

The next images show my configuration in the developer portal:
 
![image](https://user-images.githubusercontent.com/46354569/156201168-7bcdfa1f-2ed7-4a22-aef2-5a1b5624887e.png)

![image](https://user-images.githubusercontent.com/46354569/156201184-a43020a9-aa85-4a71-b268-1723021ac7c0.png)

My Client App Registrations have the next configuration:
 
![image](https://user-images.githubusercontent.com/46354569/156201236-680091ae-885b-4e18-9404-ab84877e63ba.png)

![image](https://user-images.githubusercontent.com/46354569/156201266-cca1b361-2f70-4c6c-81c6-916404a474d6.png)

![image](https://user-images.githubusercontent.com/46354569/156201285-c9897ecf-af81-4c4e-804a-e78c9779916c.png)

In the following article they state that it is not supported: 
"Disclaimer: The new developer portal currently does not support the ROPC type and being worked upon by the Engineering team."

https://techcommunity.microsoft.com/t5/azure-paas-blog/protect-api-s-using-oauth-2-0-in-apim/ba-p/2309538 

Could you confirm this or if I have something wrong in my configuration

Thanks

**Comment by mikebudzynski** [comment]
@Alejo677, ROPC is now supported in the developer portal. I suggest that you reach out to Azure support for assistance in configuring the ROPC flow.
