### ISSUE TITLE
Show blank page when access new portal within Internal VNet 

### ISSUE THREAD

**Issue by yull1860** [Azure/api-management-developer-portal#168]
follow the docs to deploy APIM to internal vnet , everything fine.

config hosts mapping to 5 ServiceEnd Point *.azure-api.net
Old admin/developer accessible without problem .
**new portal only show blank page** , from F12 trace can see loading config.json error with timeout
and it is refer to APIM public ip : 443 

![image](https://user-images.githubusercontent.com/17472445/65668570-87c25980-e074-11e9-99b4-5b4fb9f4cdc0.png)

![image](https://user-images.githubusercontent.com/17472445/65668689-bdffd900-e074-11e9-8211-6cd42b6129fd.png)
![image](https://user-images.githubusercontent.com/17472445/65668699-c526e700-e074-11e9-9632-be080920f0f9.png)

**Comment by mikebudzynski** [comment]
@yull1860 Thanks for opening this Issue. We have a task to enhance the documentation on configuration with VNET: https://github.com/Azure/api-management-developer-portal/issues/97 

In the meantime, @ygrik / @azaslonov - could you please assist?

**Comment by mikebudzynski** [comment]
@yull1860 - apologies for delay in the response. We have added an explanation in the Azure documentation: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal#what-do-i-need-to-configure-for-the-new-portal-to-work-in-my-api-management-service-in-vnet

Other articles also describe allowing the connectivity on new developer portal's endpoint.
