### ISSUE TITLE
SignIn&SignUp delegation accessToken

### ISSUE THREAD

**Issue by a2741890** [Azure/api-management-developer-portal#1682]
I am using Managed Dev Portal and delegating sign-in & sign-up
1. Click sign-in at home page and successfully logged in at delegated website and return to the home page. 
2. Got accessToken and returnUrl in Session storage. 
3. Click **Products** in developer portal, it seems to call sign-in again. 

If I write the code to let it sign in again to get SAS token...
4. Return to Dev portal with sso-signin and returnUrl
5. returnUrl will be _../.../products_ and cause the infinite loop

**I was wondering if calling sign-in again when clicking Products is a bug expected behaviour?** It seems that by redirecting to delegated website will kill the accessToken in session storage. Not sure if this is a bug.

Thank you in advance!

**Comment by mikebudzynski** [comment]
@[a2741890](https://github.com/a2741890), we couldn't reproduce the issue on our side. I suggest that you contact Azure support to troubleshoot the problem.
