### ISSUE TITLE
OpenAPI schema field `nullable` not imported correctly

### ISSUE THREAD

**Issue by knutwannheden** [Azure/api-management-developer-portal#1683]
## Bug description

We have APIs defined with OpenAPI which we are importing into the Azure API Management. When the APIs define schemas with `nullable: false` the schemas don't appear to be imported correctly and are rendered very strangely in the developer portal.

## Reproduction steps

1. Define an API using OpenAPI 3.0 with a schema having `nullable: false` (see example below)
2. Import API into Azure API Management
3. Open and inspect API in Developer Portal

## Expected behavior

The rendering of the schema in the table view as well as the raw schema view is very confusing. The table view would lead one to believe that the corresponding property is actually a structured object, whereas in the example it is just a UUID string.

## Is your portal managed or self-hosted?

Managed

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: Windows 10
 - Browser: Edge
 - Version: 98

## Additional context

1. OpenAPI schema (YAML format) 
![image](https://user-images.githubusercontent.com/408765/157229826-c761d35f-5b6d-420f-b932-c4a6ba6559f4.png)
2. Developer portal table view 
![image](https://user-images.githubusercontent.com/408765/157229625-560b62fd-52db-4bfa-99b9-ed4be06bff8a.png)
3. Developer portal raw schema view 
![image](https://user-images.githubusercontent.com/408765/157229517-ba6ddef2-7afd-4b01-8b77-6bd0ed91f23e.png)

Extract from OpenAPI schema:
```yaml
  /glu/test-order/orders:
    get:
      tags:
      - orders
      summary: Bestellung auflisten
      description: Gibt alle existierenden Bestellungen zurück.
      responses:
        "200":
          description: erfolgreich
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
...
    Order:
      required:
      - id
      type: object
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/UUID'
          - nullable: false
        handedOverToTransportCompany:
          type: boolean
        anrede:
          $ref: '#/components/schemas/FdtAnrede_art_97004'
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
```

**Comment by knutwannheden** [comment]
FWIW, when removing the `nullable: false` field the UI looks much better and as you can see the `id` property is also shown correctly: 
![image](https://user-images.githubusercontent.com/408765/157236523-8f4f585b-c7df-4330-b232-a45d04efdebb.png)

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
