### ISSUE TITLE
Authorization Details - Question/Feedback

### ISSUE THREAD

**Issue by madhancock** [Azure/api-management-developer-portal#1684]
A relatively recent section added to the portal is the Authorization section. This is causing problems with our implementation and it seems like the only solution for us is to remove the Try It functionality (by removing the auth method from the APIs).

When googling this issue I did find someone else that has a problem with it so here's a link to that just for reference/clarity: https://stackoverflow.com/questions/71074777/azure-apim-i-need-hide-section-authorization-in-portal-developer-operation-detai/71085462

Our issue is that we use Auth0 as one of our identity solutions, which in turn secures our backend endpoints. In APIM we have this set up as OAuth2.0 authentication via auth token. We have a client ID that represents the developers portal, and when a user clicks "Try it" in the portal and they select the identity provider they log in and boom - they have a token.

The above scenario is only valid for a developer wanting to try out the API endpoints via the portal in our scenario - the reason being that those developers will be writing M2M software, which uses client credentials flow. This flow is completely different to the one used for playing with the documentation tools.

Every customer has 1 or more client credentials. However, now - all of our documented APIs have an Authorization section - which lists only auth code authentication and displays a client ID that is associated with the developer portal and not the customers application/organisation.

This results in one of two scenarios, neither of which are desirable:

- The customer implements their M2M using a specific users credentials - which would of course be very bad for them when that user changes their password.
- The customer asks for the "client secret" and is then confused to find they actually need a totally different client ID/secret pair and grant type and auth URL to what's documented on the API portal.

There are a couple other smaller gripes:

1. Our OAuth flow for developer login goes direct to Auth0. However, for M2M they use a wrapper (which is actually APIM itself) on a different domain which has some M2M specific protections that are not available externally. So the two above scenarios are worse in our case as the wrong auth domain is provided. We could wrapper the entire identity implementation but we'd rather not.
2. This Authorization section isn't visible in the editor - so you only see it as a standard user. It came to my attention when helping clients with the problems it creates.

**Conclusion**

It seems the only solution for our situation is to remove endpoint auth from the portal. I've put this here to see if you've any thoughts on this.

**Comment by mikebudzynski** [comment]
@[madhancock](https://github.com/madhancock), thanks for describing the issue in detail. We've heard similar feedback about the new authorization section and we're now considering the options to solve your and other customers' issues.

1. Is it accurate to say that in your case the configured authorization server is specific to the test console only and not the actual API usage? When you assign an authorization server to an API in API Management, this server is included in the OpenAPI file that can be downloaded from the developer portal (currently OpenAPI v3 support is missing) and it is used for the token retrieval in the test console.
2. Would the following configuration options, both optional, solve your issue? Would you use both options or just the first one?
   - Assign an authorization server to an API for the purpose of the developer portal's test console only
   - Assign an authorization server, same or different, to an API to have it surfaced in the API reference pages and in the downloaded OpenAPI file but not in the test console
3. How severely is this issue affecting your developer portal? Does it require urgent mitigation or are you able to wait several weeks for a proper resolution?

**Comment by mikebudzynski** [comment]
We have temporarily removed the authorization server information from the API details widget. More information in the latest release notes: https://github.com/Azure/api-management-developer-portal/releases/tag/2.15.0
