### ISSUE TITLE
Development Portal is not using the latest AAD B2C identity config settings after updating in the identities blade

### ISSUE THREAD

**Issue by LeHaine** [Azure/api-management-developer-portal#1689]
## Bug description

We have an APIM instance that was initially set up to use a built in user flow in AAD B2C under the identities blade. When we update any of the policies field in the identity config, for our instance the sign-up and the sign-in policies, to a new custom policy from B2C, the sign in page of the development portal continues to use the old config settings. We see that happening by monitoring the network requests and we can see that the `/config-apim.json` file that is pulled down is still using the old settings. Even if we delete the identity config settings completely without adding a new B2C configuration it still pulls down the old settings. 

One thing to note is, when we do change the setting to the new policy, our login now breaks due to an **invalid token** as if it is using the internal policy internally and then using the old policy settings as the token.

## Expected behavior

We expected to see the new config settings be used.

## Is your portal managed or self-hosted?

Managed

## Additional context

**Initial settings:**
![image](https://user-images.githubusercontent.com/4951150/157863060-3655b76d-3778-40a6-9c4a-172a8eb0187a.png)

**Required settings:**
![image](https://user-images.githubusercontent.com/4951150/157863209-d20b74bf-2f41-43b1-b9b7-44b95f3dde75.png)

**/config-apim.json**
![image](https://user-images.githubusercontent.com/4951150/157863898-c7901569-bb2e-4e4a-911a-680014096260.png)

**Comment by mikebudzynski** [comment]
@LeHaine, have you republished your developer portal after changing the identity provider configuration?

**Comment by LeHaine** [comment]
@mikebudzynski I did not. I went ahead and republished and that worked. Wasn't aware that updating those values required a republish. But it all works now. Thanks for pointing that out.
