### ISSUE TITLE
Cannot upload or see any images loaded by others in Developer Portal media library

### ISSUE THREAD

**Issue by jkiseeva** [Azure/api-management-developer-portal#1690]
I have the managed version of the developer portal and having issues with being able to upload background images from my local machine to the media library of the portal. Please see screenshot below. None of the images uploaded by me or by my colleagues working on customizing the developer portal are visible to me, even after my colleagues have saved and published the portal. This happens whether or not I am using VPN. Furthermore, after waiting for a while for the image to upload, I get the "Oops something went wrong" error message. Would appreciate your help!

![image](https://user-images.githubusercontent.com/62075437/158262571-13c000f3-ca96-4506-bb9c-5293354b886f.png)

**Comment by mikebudzynski** [comment]
@[jkiseeva](https://github.com/jkiseeva), please reach out to Azure support. They will be able to investigate your configuration and trace the issue.
