### ISSUE TITLE
Error: Unable to complete publishing. Error: Unable to complete pages publishing. Error: Unable to publish page "Sign in"

### ISSUE THREAD

**Issue by AkshadaPramodKadam** [Azure/api-management-developer-portal#1696]
Bug description
I have cloned the latest release 2.14.0 and tried to build and publish and getting the following error

Expected behavior
npm run publish

Error: Unable to complete publishing. Error: Unable to complete pages publishing. Error: Unable to publish page "Sign in": Error: Unable to render page "Sign in - Microsoft Azure API Management - developer portal": Error: Unable to render page: Error
    at XMLHttpRequest.send (webpack://apim-developer-portal/./node_modules/xhr2/lib/xhr2.js?:282:19)
    at eval (webpack://apim-developer-portal/./node_modules/@paperbits/common/http/xmlHttpRequestClient.ts?:73:17)
    at new Promise (<anonymous>)
    at XmlHttpRequestClient.send (webpack://apim-developer-portal/./node_modules/@paperbits/common/http/xmlHttpRequestClient.ts?:37:16)

**Comment by mikebudzynski** [comment]
@[AkshadaPramodKadam](https://github.com/AkshadaPramodKadam), could you contact Azure support to get help with your issue? They will be able to investigate your configuration.

**Comment by mikebudzynski** [comment]
@[AkshadaPramodKadam](https://github.com/AkshadaPramodKadam), can you share the support ticket ID?

**Comment by AkshadaPramodKadam** [comment]
@mikebudzynski 
FYR
TrackingID#2203300040000966

**Comment by AkshadaPramodKadam** [comment]
@mikebudzynski FYR #2203300040000966

**Comment by AkshadaPramodKadam** [comment]
@mikebudzynski 
FYI

Delegation is enabled in our APIM settings, and the URL of delegation is accessible from the same machine where we were trying to publishing self-hosted developer portal.

Can you please let us know why is it not working with delegation implementation?
