### ISSUE TITLE
Can not change header or query parameter value in the Try it section when a predefined example value is set

### ISSUE THREAD

**Issue by ArkimeraMattias** [Azure/api-management-developer-portal#1707]
## Bug description

When creating a new operation with a header or query parameter you have two options when setting the example value. 

1. Leave it empty. This will make the user able to enter their own value later on in the _Try it_ section.
2. Enter one or more values. This will make the user unable to enter any other value in the _Try it_ section.

In case 2 the issue is that the text box is turned into a drop down list where you can only pick from existing values, not enter your own.

Previously, we could enter an example value and still allow the user to change it in the _Try it_ section. It really shouldn't be a limitation since you might want an example value but still allow the user to change it to their own value later on.

This was working fine up until December or January when a new version of the managed API Management was released.

## Reproduction steps

1. Create a new API and fill in the essentials
2. Add a new operation and fill in the essentials
4. Create a new header or query parameter and leave the example value empty
5. Create a new header or query parameter and enter an example value
6. Head over to the _Try it_ section of the portal and mark the differences in behavior

## Expected behavior

You should be able to change the header or query parameter value in the _Try it_ section no matter if there was an example or not.

## Environment

 - Operating system: Windows
 - Browser: Google Chrome, Edge, Firefox

## Additional context
![2022-03-30 163759](https://user-images.githubusercontent.com/32730983/160861865-80de3290-e4f9-4f71-b6f4-9e22eee01d7b.png)
![2022-03-30 163906](https://user-images.githubusercontent.com/32730983/160861874-fbfdd563-745a-4595-8e05-b05d2fd6b8f3.png)

**Comment by mikebudzynski** [comment]
@ArkimeraMattias, this behavior is by design. When you specify predefined values for a parameter, API Management treats that parameter as an enum (you can also see that in the OpenAPI file exported from API Management). Since it's an enum with a limited set of values, the developer portal's try-it console allows users to select one of those values only for ease of interaction.

**Comment by mikebudzynski** [comment]
You can specify parameters example using the OpenAPI's `example` property: https://spec.openapis.org/oas/latest.html#parameter-object

Setting examples for parameters isn't supported in the form-based design of the Azure portal interface, but you can do it manually by editing the OpenAPI file:

1. Go to APIs in your API Management service in the Azure portal.
2. Select your API.
3. Keep "All operations" selected.
4. Select the "pencil" icon in the "frontend" section.
5. Edit the OpenAPI file and save it.

**Comment by ArkimeraMattias** [comment]
It was not obvious to me that it worked in this way but it was quite easy to change once you explained it.

Thank you @mikebudzynski!
