### ISSUE TITLE
Can not publish any changes on the development portal

### ISSUE THREAD

**Issue by ArkimeraMattias** [Azure/api-management-developer-portal#1714]
## Bug description

We can no longer publish any changes made on the development portal. Last friday 1 april 2022 at 1:01:48 PM CET we made some changes and everything was published correctly. We tried publishing more changes at 2:44:02 PM CET but were not able to.. We still have not managed to publish any changes since.

When publishing and checking the Revisions page you can see that the new version is _Publishing_ for around 20 minutes. After that it says that the Revision _Failed_. During this period the site is really slow, but it is fine again once the publish has failed.

We have tried publishing from both Azure and the development portal interface.

We also can no longer make backups using the V2 scripts. When running capture.bat like we usually do nothing happens and the script runs forever. No timeout or anything.

## Reproduction steps

1. Make changes to the portal
2. Save changes
3. Publish changes
4. Under Portal overview -> Revisions you can see that the version is in the state of _publishing_
5. After ~20 minutes the version has the state _failed_
6. Check the developer portal and the changes has not been published

## Expected behavior

The changes should be published and the Revision version should say _Completed_

## Is your portal managed or self-hosted?

Managed

## API Management service name

azora-one

## Environment

My setup:
 - Operating system: Windows
 - Browser: Edge

## Additional context

If you enter a API details page and then enter another page you get this error in the console:
```
Unable to load operations: Error: Parameter "apiId" not specified.
(anonymous) @ theme.js:2
(anonymous) @ theme.js:2
__awaiter @ theme.js:2
trackError @ theme.js:2
handlerPromiseRejection @ theme.js:2
```

Last successful revision
![2022-04-05 082250](https://user-images.githubusercontent.com/32730983/161691718-5523ce60-0542-4e4f-b993-e2bc29aba015.png)

All failed revisions
![2022-04-05 082318](https://user-images.githubusercontent.com/32730983/161691726-8202fc08-4fc6-46c9-a9b5-46f483499b01.png)

Portal overview
![2022-04-05 083001](https://user-images.githubusercontent.com/32730983/161692668-82fdec55-cc8b-4378-9dab-2221437605cc.png)

Log file
[developer.azora.one-1649256591364.log](https://github.com/Azure/api-management-developer-portal/files/8428006/developer.azora.one-1649256591364.log)

**Comment by mikebudzynski** [comment]
@ArkimeraMattias, please contact Azure support - they will be able to investigate the logs and troubleshoot the problem.
