### ISSUE TITLE
Cannot add a url path like: .../{string}/{string}

### ISSUE THREAD

**Issue by brennfoster** [Azure/api-management-developer-portal#1716]
I have an API that has multiple operations with a route path like: /api/{string:id}/{string:id}. I am able to pass validation and create the API operations with this path, but when I try to hit the endpoint I get a 404 operation not found.

## Bug description

Getting a 404 not found on a route containing /{string}/{string}

## Expected behavior

I should be able to use this path. I can run the application locally and the route is mapped correctly. I can hit the application in Azure using this path. If I try to hit the path through API management, it fails.

## Is your portal managed or self-hosted?

Managed

## API Management service name

non-production-developer-portal

**Comment by mikebudzynski** [comment]
@brennfoster, this issue doesn't appear to be specific to the developer portal. Please, contact Azure support for assistance.
