### ISSUE TITLE
Developer portal: AAD Login - SPN permissions

### ISSUE THREAD

**Issue by johnlokerse** [Azure/api-management-developer-portal#1717]
I am using the APIM developer portal with AAD login. To get this to work the service requires a service principal with Directory.Read.All API permissions. It looks like the soon-to-be deprecated `Azure Active Directory Graph` is needed for this to work. I tried to use the `Microsoft Graph` permissions by itself, but I was not able to add AAD groups unless I added the `Azure Active Directory Graph` permissions. 

I was not able to find the correct permissions in the MSDocs. Can anyone confirm that these permissions are needed? If they are needed, what happens after the AAD Graph API becomes deprecated (June 2022)?

![image](https://user-images.githubusercontent.com/3514513/161905865-d5aec684-5c42-42b9-b2ae-7a436b4194e2.png)

**Comment by mikebudzynski** [comment]
@azaslonov

1. Do we support Microsoft Graph?
2. Are these required permissions correct?

**Comment by azaslonov** [comment]
@johnlokerse, this should be enough for creating accounts in APIM, using Graph API permissions:

![image](https://user-images.githubusercontent.com/2320302/162522280-c2b18006-ba6d-49e0-8ee1-951ab5ec1447.png)
Hope that helps.

@mikebudzynski, we need only particular claims to be present in the token, regardless if it's MS Graph or AAD Graph.

**Comment by johnlokerse** [comment]
@azaslonov I found an MSDocs page that states that the SPN also needs `Directory.Read.All` permissions to function properly: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad#add-an-external-azure-ad-group

I made a pull request to remove the AAD Graph API reference. Can you confirm if this is correct or not?  https://github.com/MicrosoftDocs/azure-docs/pull/91413
