### ISSUE TITLE
API operation widget - missing details in service API response

### ISSUE THREAD

**Issue by KannanKalisamy** [Azure/api-management-developer-portal#172]
**Expected behavior**

When i try to extend the operation detail component to include more detail.  i couldnt find the service api doesn't have much detail compared to pervious portal operation page

example : sampleurl

/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/{}/apis/{Operation}/operations/{operation}?api-version=2018-06-01-preview

Managed / Self-hosted

**Comment by mikebudzynski** [comment]
@KannanKalisamy What information do you need that the API doesn't return?

**Comment by KannanKalisamy** [comment]
@mikebudzynski  i tried to get the request url please see the attached screen shot from old portal

![image](https://user-images.githubusercontent.com/16281799/65927784-6a0f3e80-e43e-11e9-82e3-db90d1f6030e.png)

**Comment by azaslonov** [comment]
Hi @KannanKalisamy, that's fair, we'll add a helper method to generate sample URL. We'll also include it into default widget template.

Please use this issue for tracking.

**Comment by KannanKalisamy** [comment]
HI @azaslonov  Thanks and also few other attributes are missing in the operation detail response .
Example under the response object missing statusDescription. which will be used in the operation-detail template to show the response status code and status description,

![image](https://user-images.githubusercontent.com/16281799/66046009-36c8ce80-e568-11e9-8689-8dcb5ff3f8d4.png)

**Comment by azaslonov** [comment]
Hi @KannanKalisamy, understood, we'll add it as well.

**Comment by mikebudzynski** [comment]
@KannanKalisamy Thanks for letting us know. We're currently working on a new version of this widget, we appreciate every comment or suggestion.

**Comment by mikebudzynski** [comment]
The new API operation details widget will contain the helper method as well as response description. Merging with #186
