### ISSUE TITLE
APIM removes request body on GET operations

### ISSUE THREAD

**Issue by jonasanker** [Azure/api-management-developer-portal#1731]
## Bug description

When calling a `GET` API operation with a request body on APIM, the request body is not forwarded to the backend.

## Reproduction steps

1. Import an Open API specification with a `GET` operation, which takes a request body, to APIM
2. Call the API with a request body
3. There is no body in the request the backend receives from APIM

## Expected behaviour

API Management does not remove the request body

## Is your portal managed or self-hosted?

Managed

## API Management service name

The issue is present on several API Management instances

## Environment

N/A

## Additional context

From several discussions on StackOverflow [[Source]](https://stackoverflow.com/questions/62003235/azure-api-management-how-to-send-body-along-with-my-request), [[Source]](https://stackoverflow.com/questions/65827966/does-api-management-strip-the-request-body-from-get-requests) replies argue that the behaviour is intended and also in line with [RFC 7231](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.1). 

I can somewhat buy the argumentation but also believe that the chosen behaviour is an _opiniated_ behaviour. My biggest concern is therefore that the behaviour is "hidden":

1. APIM does not fail when importing the API and hence the behaviour is hidden and first visible when consuming the API
2. I can find no documentation on this behaviour, whether it is intended

**Comment by azaslonov** [comment]
@jonasanker, I agree this is more like opinionated behavior rather than specification-driven. Is there a business requirement on your side?

**Comment by jonasanker** [comment]
@azaslonov We have created a multi-tenant publishing flow on top of API management which allows API teams to autonomously publish their APIs to APIM. 

We have seen a few times that some of the teams have designed an API with GET operations which expected a payload. While we can agree this might not be an ideal design choice, the APIs were successfully imported to APIM and APIM's behaviour to remove a request body on a GET operation, was first discovered at runtime when the request did not come through to the backend as expected.

I think if the APIM takes a stand on this, it would be great if a Publisher is clearly notified that APIM will act differently than what the Open API spec declares.

**Comment by humbe76** [comment]
As far as I can read, RFC7231 from 2014 removed the parts stating GET requests should not have any body, and the "new" RFC only mentions that the body should not have semantic importance. https://www.rfc-editor.org/rfc/rfc7231#page-24

Dumping GET bodies by default is fine, but there should be a workaround for those having to use an API that was designed after 2014, whether or not someone else might disagree whether they used correct design decision.

Coding a REST API, POST on a resource may be already in use to add new instances. Seems like a good approach to use a GET request with body if you want to keep something potentially sensitive out of URI logs, or you are afraid URI size could grow above whatever your tech stack can handle.

**Comment by tank104** [comment]
There hasn't been an update to this in a while, and still looks like its unsupported.  Is that the case?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by prijeshramani** [comment]
I got the nice explanation - [link](https://www.baeldung.com/cs/http-get-with-body)
