### ISSUE TITLE
Spacing below the operation name changes depending on the length of the name

### ISSUE THREAD

**Issue by ghost** [Azure/api-management-developer-portal#1734]
## Bug description

In the _List of operation_ widget: When naming an operation something short, there is an extra space created below the operation name. When named something long, this space disappears.

Wrapping operation names is turned off but does not affect this behavior.

I have seen this behavior on other developer portals besides ours as well.

## Reproduction steps

1. Create operations with different operation name lengths
2. See the difference in spacing below the different operation names in the _List of operation_ widget

## Expected behavior

The spacing should not depend on the name of the operation.

## Is your portal managed or self-hosted?

Managed

## API Management service name

azora-one

## Environment

 - Browser: Edge, Google Chrome, Firefox

## Additional context

Example from our development portal. The operation Add a file has different spacing than other operations.

![bug](https://user-images.githubusercontent.com/32730983/164444829-67c2b8cb-8646-4c69-8690-c1a101bb902e.png)

Example that the spacing depends on the length of the operation name.

![portal-bug](https://user-images.githubusercontent.com/32730983/164444914-7cecea56-e2b8-4b73-84dd-0052e0a596b9.gif)

**Comment by smhbhdr** [comment]
I have also seen this issue regardless of the length. In some cases even though the the name is short, I still see an extra space in between.

![image](https://user-images.githubusercontent.com/17758668/164459586-48179621-22fb-421f-a645-efdeec65fd95.png)

In some cases, the height is set to 53.35 and in others it's set to 32.35

![image](https://user-images.githubusercontent.com/17758668/164459893-a66305f6-65d4-474e-b7d5-35c7417e19fb.png)

![image](https://user-images.githubusercontent.com/17758668/164459959-72195d26-4c56-4f4d-95a5-1680ad30e408.png)

**Comment by smhbhdr** [comment]
I have faced exactly the same issue on our development environment. As soon as I make the name shorter, the width of the element goes up to 53.35 while it's 32.35 when the text is longer.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
