### ISSUE TITLE
Developer Portal Instance not publishing

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1735]
## Bug description

We are trying to publish one of our DevPortal instances. It does nor work.

We tried using different ways of publishing the instance.
1. In the editor mode of the Devportal:
![image](https://user-images.githubusercontent.com/58420097/164452926-6d35c9c0-ae8c-489b-9487-b9f002be7806.png)

    Pressing the publish button creates a notification which states that the publishing process started.
    No error message is displayed.
    Even after >10min of waiting the changes still don't appear in the published version of the DevPortal.
2. In the "Portal overview" section in the Microsoft Azure Portal
![image](https://user-images.githubusercontent.com/58420097/164453091-35eb7250-bcc3-4938-818f-9ceee9f49be4.png)
    
    Pressing this "Publish" button causes the statement to change and display the current time as last published.
    Earlier today I pressed this button but it seems to have reverted to `Your developer portal has not been published yet.`

In other DevPortal instances this behavior could not be observed.
If there is no solution where we can do it ourselves please publish the instance for us.

@AnRei123 will provide further information via email if requested.

Find the root cause of this issue to avoid such issues in the future.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
@ZarTrox, please send the name of the service in question either to MS Support or to apimportalfeedback@microsoft.com.
