### ISSUE TITLE
Widgets only visible to authenticated users still show up for a short period for anonymous users

### ISSUE THREAD

**Issue by ghost** [Azure/api-management-developer-portal#1737]
## Bug description

When you have widgets on a page that are only visible to Authenticated uses, these widgets will still appear for a split second when refreshing the page as an Anonymous user.

## Reproduction steps

1. Create any widget on a page in the development portal
2. Set its visible to setting to Authenticated
3. Save changes
4. Publish portal
5. Go to the page without being signed in (anonymous)
6. Refresh the page and see the widget appear and disappear rapidly

## Expected behavior

These widgets should never appear to Anonymous users.

## Is your portal managed or self-hosted?

Managed

## API Management service name

azora-one

## Environment

 - Browser: Edge, Google Chrome

## Additional context

Here a button widget and a menu widget is only visible to Authenticated users. It still appears to Anonymous users.

![Animation](https://user-images.githubusercontent.com/32730983/164680279-eef528e2-633b-4880-95bb-53bcb7bdf634.gif)

Here is the settings for the button.

![image](https://user-images.githubusercontent.com/32730983/164680481-34f4eb79-b18f-4f53-ba97-014e7edbdccf.png)

**Comment by azaslonov** [comment]
@ArkimeraMattias, thanks, this is known issue, we're working on it.

**Comment by liamkinne** [comment]
Any updates on this? A feature like this shouldn't be broken for over 8 moths.

**Comment by azaslonov** [comment]
The fix has been deployed to all public regions. Thank you for patience.
