### ISSUE TITLE
[Feature Request] | HSTS, x-content-type and x-frame-options header missing

### ISSUE THREAD

**Issue by MayankBargali-MSFT** [Azure/api-management-developer-portal#1738]
When navigating to developer portal customer observe that the security scanner is complaining that the developer portal page has no HSTS, x-content-type and x-frame-options header. 

Original Issue: https://docs.microsoft.com/en-us/answers/questions/797311/index.html

Discussed internally and suggested creating the feature request here.

**Comment by azaslonov** [comment]
@MayankBargali-MSFT, we do generate all 3 headers actually for HTML pages:
![image](https://user-images.githubusercontent.com/2320302/165639987-7c1a944f-b4e7-4570-beb0-8887573b9ef4.png)
 
Are there other specific cases you want to be covered?
