### ISSUE TITLE
Error creating sections on layouts

### ISSUE THREAD

**Issue by yupikaiei** [Azure/api-management-developer-portal#1740]
## Bug description

On a forked version of the portal when I try to add any section to the Home Layout I get an error

## Reproduction steps

1. Go to Layouts on the side toolbar
2. Click on Home Layout
3. Click on add section before or after the content block
4. Choose any section
5. See error

## Expected behavior

Expected behaviour would be to have the section added to the layout and no errors

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.15.0`, commit `2c320d1d0f999b7f55ead33738dd1e293ecc4e94 `]

## API Management service name

[apim-mgmt-dev]

## Environment

 - Operating system: [OSX]
 - Browser: [Google Chrome]
 - Version: [100.0.4896.127]

## Additional context

Add any other context about the problem here, including screenshots.
<img width="1664" alt="Screenshot 2022-04-22 at 16 44 57" src="https://user-images.githubusercontent.com/20303918/164738068-e2326571-ab5e-4072-bfc7-b52bfe8e27fd.png">

**Comment by azaslonov** [comment]
@yupikaiei, I have to ask you to send us your service name to apimportalfeedback@microsoft.com. We'll take it from there.

**Comment by yupikaiei** [comment]
Hi!

Here's the service details:

Subscription ID: c47bfe3d-881a-4142-bf65-ec835858a67b

Resource group: MSC-RSG-CAPIM-DEV


Thank you


Best regards,
Magno Sousa
