### ISSUE TITLE
Container Apps not shown when adding new API

### ISSUE THREAD

**Issue by szavoda** [Azure/api-management-developer-portal#1744]
When attempting to add an Api via the Container App option and I "Browse" available container apps, no items show in the list.  This behavior was not seen a couple of weeks ago.  All items are in the same subscription.

To further experiment, I also deleted an API previously added using the same method and then tried to re-add it, but it too was not showing in the list of available Container Apps.

**Comment by azaslonov** [comment]
@szavoda, we know about this problem and working on it already (@ygrik to confirm). However, this is not related to Developer portal, so I have to close this issue here.
