### ISSUE TITLE
Operation-detail widget - Missing schema details

### ISSUE THREAD

**Issue by KannanKalisamy** [Azure/api-management-developer-portal#176]
Operation-detail widget missing response schema detail. When i tried to debug the page schema-detail components widget is not loading the schema detail.  I checked open api definition schema was loaded correctly in azure portal.

![image](https://user-images.githubusercontent.com/16281799/65955894-7de19180-e48c-11e9-87b7-75b7a9a03542.png)

**Comment by mikebudzynski** [comment]
Merging as this will be addressed with #186
