### ISSUE TITLE
'Description' from 'example' element in swagger is not rendered in Azure APIM Developer Portal

### ISSUE THREAD

**Issue by markbriggs-ms** [Azure/api-management-developer-portal#1761]
example of missing 'Description'

<img width="508" alt="image" src="https://user-images.githubusercontent.com/44032869/167402016-5f3b2d46-66dd-4419-a308-da2c00339507.png">

**Comment by azaslonov** [comment]
@JMach1, can you please confirm that the issue was fixed in #1856, and if yes, close this issue?

**Comment by JMach1** [comment]
No, the task you've mentioned was about another examples object. Created a work item for this issue, should be fixed in the next sprint.

**Comment by jsorohova** [comment]
Fixed. Closing the ticket.
