### ISSUE TITLE
API description and Operation details not working due to "Unchecked runtime.lastError "

### ISSUE THREAD

**Issue by markbriggs-ms** [Azure/api-management-developer-portal#1763]
API description and Operation details not working due to **"Unchecked runtime.lastError"**

In the products page, the details are not resolved
In the API details page, the API and operation description are not resolved

Shown values are "This...", "Calculates...",etc...

Example below:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/44032869/167408565-492ad255-9523-401b-86a1-bde6ee74815d.png">

**Comment by azaslonov** [comment]
@markbriggs-ms, I'm not sure what you mean by "Unchecked runtime.lastError". Can you please elaborate?

**Comment by markbriggs-ms** [comment]
error found in dev console 

<img width="611" alt="image" src="https://user-images.githubusercontent.com/44032869/167837636-525f547d-44e3-4cbf-80ae-5678d6634d22.png">

**Comment by markbriggs-ms** [comment]
this can be closed.  Issue was:

•	There is a conflict with a specific edge extension called "Video Download": Video Download - Microsoft Edge Addons
•	By disabling the extension, the issue isn't replicable

**Comment by azaslonov** [comment]
I see, thanks for confirmation. Closing.
