### ISSUE TITLE
Feature request: Edit request URL on API document page

### ISSUE THREAD

**Issue by yrngsk** [Azure/api-management-developer-portal#1765]
Would be nice if we could edit the request URL in "APIs" page. 
The API Management gateway URL is automatically displayed in "Request".
For example, if we use a reverse proxy in front of API Management, we may want to display reverse proxy domain name  as Request URL.

![image](https://user-images.githubusercontent.com/105411512/168007005-51b1d5dc-3646-4b51-b3eb-206fe17bf097.png)

**Comment by azaslonov** [comment]
@yrngsk, this seems like #1202, please use it for tracking. I'm closing this one to reduce duplication.
