### ISSUE TITLE
Captcha Audio option not comprehensible

### ISSUE THREAD

**Issue by markbriggs-ms** [Azure/api-management-developer-portal#1776]
Clicking on the audio option to hear the captcha sounded out is not comprehensible.  At times there seems to also be two voices audible at the same time making it impossible to understand.

Could this be improved?

**Comment by azaslonov** [comment]
@ygrik-ms, could you please comment on this?

**Comment by ygrik** [comment]
Hi @markbriggs-ms 
The audio option is distorted on purpose, making it hard to automate bots to recognize words.
