### ISSUE TITLE
Body is empty in the TryIt page

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#178]
Hi,
I have an API I want to test from the dev portal. I have defined the definition of the request/response and also examples of requests/responses.
But when I do a TryIt, the body of the request is empty.
In the previous dev portal, the body contains the sample of request coming from the definition of the API.

**Comment by azaslonov** [comment]
Hi @dgrospelier, yes, this coming soon.

**Comment by mikebudzynski** [comment]
Thanks @dgrospelier - I'm merging the Issue as it will be addressed as part of #186
