### ISSUE TITLE
same issue as #399 Footer does not show where it should.

### ISSUE THREAD

**Issue by cmljyothi** [Azure/api-management-developer-portal#1782]
Footer is not showing at the bottom of the page . Content goes below and further down the footer.

Same issue as #399.
Footer position is absolute.

It works fine locally but when deployed to Azure.

It is managed.

site url: uhb-fednet-tretool@azurewebsites.net

## Expected behavior

The footer should be beneath the content.

## Is your portal managed or self-hosted?

Managed / Self-hosted

Windows Operating system#
Browser : Chrome
## Additional context
 
![image](https://user-images.githubusercontent.com/37384044/170302597-55b5358d-4ec3-4e0f-b78b-89661432d165.png)

![image](https://user-images.githubusercontent.com/37384044/170302851-24651ba4-95e7-45fb-b8d3-7095eab85ccb.png)

**Comment by azaslonov** [comment]
Managed version is being rolled out.

**Comment by cmljyothi** [comment]
Many thanks. It works now. On 11 Jun 2022 23:09, Alexander Zaslonov ***@***.***> wrote:
Managed version is being rolled out.
