### ISSUE TITLE
mobile menu buttons not visible by default

### ISSUE THREAD

**Issue by vlad610** [Azure/api-management-developer-portal#1783]
## Bug description

In the default layout/configuration of the API Management developer portal, if you make the window narrow to get the mobile view, the menu buttons at the top change into a hamburger menu button. If you click on the hamburger menu button, a white section is expanded below which contains white navigation buttons. Being white on white, the buttons are not visible. This is very difficult to change using the admin user interface and is broken by default, causing mobile users not to be able to use the developer portal.

## Reproduction steps

1. Open the default developer portal and make the window narrow (or open it from a mobile device)
![image](https://user-images.githubusercontent.com/62948603/170431331-94a5d585-8d60-4f83-87c8-ec22c06dcd5f.png)
2. Click the hamburger menu button on top-right
3. Notice the menu items are white on white, not visible
![image](https://user-images.githubusercontent.com/62948603/170431375-ed62ea2c-2a2b-4819-ae09-5778f7730f01.png)

## Expected behavior

Menu items should be visible and formatted appropriately

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

n/a

## API Management service name

vlad2

## Environment

 - Operating system: Windows, Android
 - Browser: Google Chrome
 - Version: 101.0.4951.67

**Comment by azaslonov** [comment]
@vlad610, the fix is coming soon, please use #1461 for tracking. I'm closing this one as duplicate.

**Comment by chaosity-io** [comment]
Hey Guys, 

can someone look at this issue again. I am using managed API gateway portal and menu for mobile doesn't show anything. I suppose the managed portal must use the latest code. But I still see the  issue. If it is fixed in the tag 2.25.0 and it is not pushed to the production please let me know. Otherwise please fix the issue.
