### ISSUE TITLE
Can I check the deployed version of the managed developer portal

### ISSUE THREAD

**Issue by sebastianhutter** [Azure/api-management-developer-portal#1789]
We have multiple API management services deployed (dev, integration, production).
All three of them are using a managed developer portal (e.g. provided and managed by the APIM service itself).

It would be great to have a way to check the deployed version of the developer portal to ensure compatibility between the different environments.

Is it possible to retrieve the deployed version of the developer portal via an endpoint in the portal itself or via an API call in Azure RM?

**Comment by azaslonov** [comment]
@sebastianhutter, there is internal status endpoint which you can use to check versions: `https://[yourservicename].developer.azure-api.net/internal-status-0123456789abcdef`.
