### ISSUE TITLE
Sign-up for Product button is missing

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#179]
Hi,
In the current version of the dev portal, it is not possible for a developer to subscribe to a product or an API. It is very important to provide this feature because it is the main workflow to ask for API access for external developers.

**Comment by mikebudzynski** [comment]
@dgrospelier Could you please share the details and repro steps? The new portal has a subscribe functionality through the "Products" page in the default content. Note: it's not available to administrators, you need to publish the portal first.

**Comment by dgrospelier** [comment]
@mikebudzynski: I have just published the default portal, open the portal in a private browser session, signup as a new user, open the product page, open a product and then I can see that I have no subscription and there is no action button to ask for a subscription.

**Comment by mikebudzynski** [comment]
Could you please provide us with your API Management service name?

**Comment by dgrospelier** [comment]
thuasnedemo

**Comment by mikebudzynski** [comment]
@dgrospelier I allowed myself to sign up on your portal, since the Products page is currently restricted to logged in users. I can confirm the button to sign up for a product is missing in your developer portal, thank you for reporting the issue. We will investigate this as part of #187

**Comment by mikebudzynski** [comment]
@azaslonov - seems like you have more context on this?

**Comment by dgrospelier** [comment]
Ok thanks @mikebudzynski

**Comment by mikebudzynski** [comment]
Closing the inactive issue. We'll be rolling out new portal updates in the following days; please reopen if issue persists.

**Comment by techports** [comment]
Existing products are not available in products page in new developer's portal
API's are listing as teaser box. but unable to open and try it from new developer portal.
Any idea how to try api from new portal.
Thanks

**Comment by mikebudzynski** [comment]
@techports Which version of the portal are you using? Managed or self-hosted? If self-hosted, what's the release number? 

You shouldn't be seeing these problems. Have you followed this tutorial? http://aka.ms/apimdocs/customizeportal
