### ISSUE TITLE
Widget Error when Adding or Deleting a Section within Layouts

### ISSUE THREAD

**Issue by Ledger94** [Azure/api-management-developer-portal#1798]
## Bug description

An error is popping up when adding or deleting a section within layouts.

## Reproduction steps

1. Go to Layouts
2. Click on an existing layout
3. Try to Add a Section
4. See error within console: **Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'widgets')**
5. Delete a Section
6. See error within console: **Uncaught TypeError: Cannot read properties of undefined (reading 'widgets')**

## Expected behavior

Being able to add or delete a section within layouts without an error.

It is working as expected by self-hosting using version **2.14.0**.

## Is your portal managed or self-hosted?

Managed (2.16.0)

## API Management service name

apim-apip-dev-emea

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: 102

## Additional context

Screenshot of Console Error:
![image](https://user-images.githubusercontent.com/84686660/171869789-d6060b8c-65d4-4df1-a912-3f0295daa1c8.png)

**Comment by MrDThe** [comment]
Our team is also experiencing this specific issue. 

Some extra info from my analysis: when I spin up a new Azure API management resource with a clean, new developer portal, the issue does not occur.

**Comment by MrDThe** [comment]
@azaslonov, the issue still exists on our existing developer portal. When I reset the content of the developer portal it works, but then I will have to do all customizations again.

![image](https://user-images.githubusercontent.com/33259655/174263098-71c1ab83-16eb-4d0e-9491-823223efca53.png)

**Comment by azaslonov** [comment]
@MrDThe, it's not rolled out everywhere yet unfortunately, it should be done by end of this week.

**Comment by MrDThe** [comment]
> 

Ok, thanks.

Just curious; is there a spot where I can see if it is rolled out? For instance by checking a version number of a certain library or something..

**Comment by Ledger94** [comment]
This is resolved from my end as well.
