### ISSUE TITLE
HTTP Status Response unreadable font size

### ISSUE THREAD

**Issue by codefish06** [Azure/api-management-developer-portal#1810]
## Bug description

HTTP Status response section is not readable

## Reproduction steps

1. Go to APIS
2. Click one API
3. Click on one operation
4. click Try It
5. Scroll down
6. check HTTP Request section and see error

![Screen Shot 2022-06-08 at 21 16 05](https://user-images.githubusercontent.com/1611740/172625801-cf0b99e3-210e-4a72-9210-51fdf8425712.png)

## Expected behavior

Readable description on the section

## Is your portal managed or self-hosted?

Managed

## API Management service name

ipg

## Environment

 - Operating system: Mac OS
 - Browser: Google Chrome
 - Version: 102

**Comment by azaslonov** [comment]
@codefish06, this seems like a your customization issue, but you we can take a closer look if you send your service name to apimportalfeedback@microsoft.com.
