### ISSUE TITLE
Operation names styling goes over main window

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#1829]
## Bug description

Operation names styling goes over main window. 

## Reproduction steps

1. Go to an API on the developer portal which has a few long operation names
2. See follow styling:
![image](https://user-images.githubusercontent.com/4255748/174604091-6624860d-8b39-4414-ac74-538bd119c7a0.png)

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

b9f96a5b41d924dcd56df794859dd38748714003 (latest)

Did not happen on [2.16.0](https://github.com/Azure/api-management-developer-portal/releases/tag/2.16.0)

## API Management service name

Can provide if needed.

**Comment by azaslonov** [comment]
Working on the fix.

**Comment by jsorohova** [comment]
Hello @erwinkramer, could you please check if this is still reproducible? Thank you.

**Comment by ygrik** [comment]
fixed with PR #1839
