### ISSUE TITLE
All tables deleted since last release

### ISSUE THREAD

**Issue by aaron-infomedia** [Azure/api-management-developer-portal#1831]
## Bug description

All pages with Table widgets are no longer rendering the Table widget since the last release. Instead, large sections of whitespace appear in their place and pages also appear to have large "Article" widgets. This is happening despite not even publishing the portal. (last publish was 13th May).

This renders large portions of our documentation useless. This is also a client-facing portal, which damages our reputation. Please consider fixing with appropriate priority.

Example pages that are now broken:

https://developer.infomedia.co.uk/carrier-list
https://developer.infomedia.co.uk/header-enrichment
https://developer.infomedia.co.uk/mos
https://developer.infomedia.co.uk/webhooks

The issue can also be seen in the Edit mode, therefore not even republishing the portal will fix the issue.

## Reproduction steps

1. Go to pages linked above

## Expected behavior

The tables that took hours to build because of the fiddly UI should be visible again and should not require several more hours to rebuild

## Is your portal managed or self-hosted?

Managed

## API Management service name

ims-uks-apimgr-frontend

## Environment

 - Operating system: Windows 10 and 11
 - Browser: Chrome, Opera, Edge all tested
 - Version: Latest

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
Preparing the hot fix.

**Comment by azaslonov** [comment]
The rollout is ongoing.

**Comment by aaron-infomedia** [comment]
Can confirm the fix has been effective. Thank you.
