### ISSUE TITLE
Everytime I publish an API Using CI/CD the CORS on the portal disabled itself

### ISSUE THREAD

**Issue by CoumbaNDI** [Azure/api-management-developer-portal#1835]
Everytime I publish an API Using CI/CD the CORS on the portal disabled itself.

To promote an API from an environement to an other I use the Extractor to extract the API and then I use CICD to publish the API in the target enviroment.
I noticed that atfer each publication the button "enable cors" on the portal overview tab disbaled itself.

![corsii](https://user-images.githubusercontent.com/52564104/175271252-64a57668-44e0-4c92-a6b3-2901477965f8.png)

## Expected behavior

I would like the button not to disabled itself, because I have to manually enabled it after each deployment.
Is there something that I can deploy after each API deployment that would enable the cors ?

**Comment by azaslonov** [comment]
Hi @CoumbaNDI, are you talking about DevOps scripts from this repository or you have something of your own? In any case, this sounds like a good case for MS Support. Please reach out to them, they can help you debug this.
