### ISSUE TITLE
AllOf objects duplicated when rendering

### ISSUE THREAD

**Issue by i02coroj** [Azure/api-management-developer-portal#1841]
Hi. Here the issue I'm getting:

Brief description:
When using AllOf in a object (normally with more than one level of inheritance) properties get rendered twice (or even more depending on the number of levels).

Reproduction steps
Use AllOf with several levels of inheritance.
For intance next Yaml shows this structrue: Invoice --> ProgressionEntity --> Reference

`  invoice:
    allOf:
      - $ref: "#/components/schemas/progressionEntity"
    required:
      - currencyIsoCode
      - notificationDate
      - sections
      - subType
      - taxPointDate
      - type
    type: object
    properties:
      comments:
        $ref: "#/components/schemas/comments"
      currencyIsoCode:
        $ref: "#/components/schemas/currencyIsoCode"
      estimateReference:
        $ref: "#/components/schemas/reference"
      files:
        $ref: "#/components/schemas/files"
      notificationDate:
        $ref: "#/components/schemas/notificationDate"
      orderItemReference:
        $ref: "#/components/schemas/reference"
        description: Mandatory if estimateReference field is not filled.
      sections:
        type: array
        items:
          $ref: "#/components/schemas/section"
      subType:
        $ref: "#/components/schemas/invoiceSubType"
      taxPointDate:
        $ref: "#/components/schemas/taxPointDate"
      type:
        $ref: "#/components/schemas/invoiceType"
    additionalProperties: false
    
  progressionEntity:
    allOf:
      - $ref: "#/components/schemas/reference"
    type: object
    properties:
      progressionData:
        type: array
        items:
          $ref: "#/components/schemas/progressionData"
    additionalProperties: false

  reference:
    type: object
    required:
        - externalReference
    properties:
      externalReference:
          $ref: "#/components/schemas/externalReference"
      transportReference:
        $ref: "#/components/schemas/transportReference"
      gatewayReference:
        $ref: "#/components/schemas/gatewayReference"
    additionalProperties: false`

It shows up like this in Developer portal:
![image](https://user-images.githubusercontent.com/29977358/175975836-cc2c7fe5-5ed8-4deb-9d2b-3286ba043781.png)

Expected behavior
Properties don't get duplicated.

Is your portal managed or self-hosted?
Managed

Release tag or commit SHA (if using self-hosted version)
[e.g., release 2.0.0, commit c45da9778b70d369aba60fa2e63c191efe2b548f]

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
@jsorohova, could you please take a look and reply?

**Comment by i02coroj** [comment]
Hi.
We messed things up. It was happening in self-hosted mode. Just tried in the managed version and not seeing the issue. So will figure out what code change in our end produced it.
Sorry for wasting your time
