### ISSUE TITLE
Redirect after delegated signin shows page not found

### ISSUE THREAD

**Issue by bhmahler** [Azure/api-management-developer-portal#1844]
## Bug description

When logging in via delegated login when redirecting back to the developer portal signin-sso page as described in the documentation: 

When the user is successfully authenticated:

[Request a shared access token](https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/user/get-shared-access-token) via the API Management REST API.

Append a returnUrl query parameter to the SSO URL you received from the API call above. For example:

https://contoso.developer.azure-api.net/signin-sso?token=<URL-encoded token>&returnUrl=%2Freturn%2Furl

Redirect the user to the above-produced URL.

We are seeing a Page you're looking for doesn't exist message for a second when hitting that generated url, then the user is redirected and logged in.

## Reproduction steps

1. Sign in via delegated login
2. When redirected to the developer portal /signin-sso page you receive the "Page you're looking for doesn't exist" message for a second and then are redirected to the developer portal home.

## Expected behavior

Expected that no error message is shown and the signin-sso page redirects to developer portal home or configured redirect page.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: Google Chrome
 - Version: 102.0.5005.115 (Official Build) (64-bit)

**Comment by s8mathur** [comment]
Hi @azaslonov , could you please prioritize this fix? It's a serious regression that cripples any onboarding flows. Latest managed versions deployed (again) today are still showing this "Page Not found" behaviour with`sign-sso` even without the returnUrl.

**Comment by azaslonov** [comment]
All the service were updated, closing the issue.
