### ISSUE TITLE
Treating CORS in hash domain - Static Web App + API management

### ISSUE THREAD

**Issue by tassioFront** [Azure/api-management-developer-portal#1846]
Hi, everybody! 

**Context**
I have created a Static Web App (SWA) at the Portal Azure. Once I have done it I can use the [Preview Enviroments Pull Request](https://docs.microsoft.com/en-us/azure/static-web-apps/review-publish-pull-requests ) approach, which gives me a website with a given URL structure: 

domain.`PULL_REQUEST_NUMBER`.centralus.1.azurestaticapps.net.

`In other words, the URL is not fixed. `

**The problem**
At API Management Policies, I have configured CORS policies to define which domain can access our endpoints. But, as SWA creates a random URL, I don't know how to include it there. 

`See an example where I've tried to put a regex there - which would solve my problem: `

<img width="1089" alt="Screen Shot 2022-06-29 at 16 06 35" src="https://user-images.githubusercontent.com/47509510/176519481-3a8cc2c0-d0ef-4918-a8e3-439b1f000ff7.png">

**Solution**
Possibility to add random URLs at CORS policies. 

Any suggestion to solve it?

**Comment by azaslonov** [comment]
@tassioFront, can you use just star (*) in allowed origins then? We don't support regular expression or wildcards in this policy and I don't think we plan to (@VitaliyKurokhtin to confirm)

Also, this doesn't seem to be related to Developer portal project, so I have to close this issue. Please feel free to re-open if I'm mistaken.

**Comment by tassioFront** [comment]
Hi @azaslonov. Unfortunately, it doesn't work for us, once we control which domain can hit us. 

> Also , this doesn't seem to be related to Developer portal project, so I have to close this issue. Please feel free to re-open if I'm mistaken.

Sorry for my mistake. Which repository can I use to open this issue, please?

**Comment by VitaliyKurokhtin** [comment]
@tassioFront, you can use a little trick with policy expressions:

`<origin>@(context.Request.Headers.GetValueOrDefault("Origin"))</origin>`

This will behave as if you've specified "*", and of course inside that expression you can perform checks to make sure that passed origin has a certain suffix if you wish so.
