### ISSUE TITLE
OpenID Connect - Implicit working / AuthorizationCode => Oops. Something went wrong Error!?

### ISSUE THREAD

**Issue by iqmeta** [Azure/api-management-developer-portal#1853]
## Bug description

Hi, i can't get the Developer Portal fully working in Azure with the OpenID Connect. 
No clue how to find whats wrong. Nothing in the Logs.

The **implicit** Auth Flow against the following IDPs (AzureAD, AzureB2C, Auth0) 
is working, getting JWT Token in the UI. Which tells the config is correct (Secrets, Callback URLs, etc).

![image](https://user-images.githubusercontent.com/7533842/177771905-33d17929-e1e7-44c2-8982-79447cd27da1.png)

Trying the same with the **authorization_code** 

![image](https://user-images.githubusercontent.com/7533842/177771455-459e1c8e-79fd-4f70-a7ad-d768169de229.png)

ends always up after the succesfull login and this call in the popup window:

https://*********.azure-api.net/signin-oauth/code/callback/***********?state=****
&code=(JWT with Content {
  "kid": "cpimcore_09252015",
  "ver": "1.0",
  "zip": "Deflate",
  "ser": "1.0"
})

like this.

![image](https://user-images.githubusercontent.com/7533842/177771618-66d2b5ba-f7f6-4249-a45d-8c68e2ea1d7f.png)
{"code":500,"message":"Oops. Something went wrong. Please try again later."}

![image](https://user-images.githubusercontent.com/7533842/177775060-e8bfecfb-b2fd-47f1-beb0-1d6bbf707cbb.png)

## Reproduction steps

Setup OpenID Connect with API Management in Azure 

## Expected behavior

That it works or at least a correct error message. 
With Log Trace ID or what ever is wrong.
A way to find the problem or maybe bug.... Debug Instructions... any help.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @iqmeta, yup this is known issue, we're working on it.

**Comment by azaslonov** [comment]
The issue has been fixed in upcoming release. Will provide ETA a bit later.

**Comment by azaslonov** [comment]
@MrDThe, the release is in progress. I still cannot tell exact dates, but I would roughly account for 2 weeks from now. Also, if this is a pressing issue, please send us you service name to apimportalfeedback@microsoft.com, we'll see if we can deliver this faster to you.

**Comment by MrDThe** [comment]
> @MrDThe, the release is in progress. I still cannot tell exact dates, but I would roughly account for 2 weeks from now. Also, if this is a pressing issue, please send us you service name to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com), we'll see if we can deliver this faster to you.

Hi @azaslonov, it doesn't block our team so we will wait for the official release within a couple of weeks. Thanks for the quick update and keep up the good work!

**Comment by azaslonov** [comment]
All the services were updated, closing the issues.
