### ISSUE TITLE
API Documentation is not loading for SOAP APIs on Developer portal

### ISSUE THREAD

**Issue by GBhavin** [Azure/api-management-developer-portal#1865]
I have imported a SOAP API in APIM and i was trying to access that API from developer portal after Sign In and noticed that the API documentation is not getting loaded. While looking at the Console found that there is some code breaking.
In API Management that API is showing all the operations available.

Attaching the screenshot of console error.
<img width="955" alt="WSDL issue" src="https://user-images.githubusercontent.com/34337911/180149006-fe824c9d-002d-4f7b-aee9-2dea1839d502.png">

Expected behavior
It should load the documentation on Developer portal.

Developer Portal is not Self-hosted.

 - Operating system: Windows 11
 - Browser: Google Chrome, Firefox, Edge

**Comment by azaslonov** [comment]
@GBhavin, thanks for reporting the issues. Is it possible to share your API specification or service name? If yes, could you please send it to us to apimportalfeedback@microsoft.com.

cc: @jsorohova

**Comment by jsorohova** [comment]
Hello @GBhavin, same as Alexander, I kindly ask you to provide your API specification to us to apimportalfeedback@microsoft.com. If this is not possible, please, provide as much information as you can so we could reproduce the issue. Thank you.

**Comment by GBhavin** [comment]
@azaslonov @jsorohova Hey guys, sorry for late reply, i am sending the API specification file on apimportalfeedback@microsoft.com. Thank you so much.

**Comment by GBhavin** [comment]
@azaslonov @jsorohova Hey guys, any update?

**Comment by GBhavin** [comment]
Thank you so much for fixing this issue, really appreciate your affort.
