### ISSUE TITLE
Self-Hosted Gateway not recognizing Ocp-Apim-Subscription-Key header sent from Dev Portal

### ISSUE THREAD

**Issue by keg7271** [Azure/api-management-developer-portal#1878]
## Bug description

"Try It" feature in developer portal looks to correctly submit a request to a self-hosted gateway, but gets returned 401 "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API."  This is only happening when making requests through the "Try It" feature of the dev portal.  If I execute the exact same request using Postman it works as expected.  The other issue I see is that when I examine the request using browser developer tools, the request appears to be constructed correctly.  Examining the response in the browser developer tools I see a www-authenticate response header with the value AzureApiManagementKey realm="https://<sh-gatewayName>.ourdomain.com/ebs/customers",name="Ocp-Apim-Subscription-Key",type="header".

## Reproduction steps

1. Setup and configure a self-hosted gateway
2. Publish an API and configure it to use the self-hosted gateway
3. Configure the API to Require a Subscription
4. Use the developer portal to make a request, ensure to add the subscription key header.

## Expected behavior

I expect the error to not be returned, rather the gateway forward the request to the backend.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release 2.18.0

## API Management service name

apim-integrations-dev-ncus

## Environment

 - Windows 10
 - Google Chrome
 - Version: 103.0.5060.134

## Additional context

![image](https://user-images.githubusercontent.com/17765575/181516762-6d352cc4-3c5a-4374-bd63-5524fa4e0df9.png)
Screenshot showing request with Ocp-Apim-Subscription-Key header present.

![image](https://user-images.githubusercontent.com/17765575/181517129-6b9972ab-3a69-40f6-bc4d-468c1e3975a2.png)
Screenshot showing response.

**Comment by azaslonov** [comment]
@keg7271, could you please check a couple of things:
1. If managed version of the portal works with the same user, same subscription.
2. In API settings you have same header name that your self-hosted portal sends to API:
![image](https://user-images.githubusercontent.com/2320302/182493437-549d34c5-3a6a-48e1-9a36-9d344aab45ba.png)

**Comment by keg7271** [comment]
I have provided a response to the email address provided.
