### ISSUE TITLE
API Operation details - Tables not displayed correctly

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1880]
## Bug description

In the API Operation details widget some tables like the response table are not displayed correctly:
![image](https://user-images.githubusercontent.com/58420097/182307331-48ecc1e9-e7cf-4d9d-8c9f-5d9d14a2b2b5.png)

The column header and the table content are not formatted horizontally.

This issue can be found not only in the response table but also for the request body and more.
It does not only affect one API but multiple others as well. The issue is not only in the published DevPortal but can be seen as well in the editor mode of the DevPortal.

More than one DevPortal environment is affected.

The bug exists even after:
- Opening the DevPortal in Incognito
- Re-publishing the DevPortal

## Reproduction steps

- Bug cannot be reproduced

## Is your portal managed or self-hosted?

Managed

## Additional context

I can provide the APIM service name if necessary.

**Comment by ZarTrox** [comment]
Note:
On 2022-07-28 it still worked as intended.
On 2022-07-29 the issue was found.

**Comment by azaslonov** [comment]
@ZarTrox, I have opened one of your websites, and there all seems to be rendered properly. Could you please send us (by email) the service name, API and operation name. We'll take a closer look.

**Comment by azaslonov** [comment]
@ZarTrox, I'm closing this issue since we figured it out with you offline.
