### ISSUE TITLE
UI Looks Distorted when trying to Create a trigger in Azure data Factory under Advanced Option 

### ISSUE THREAD

**Issue by anupamalok** [Azure/api-management-developer-portal#1881]
## Bug description
In Azure Data factory while creating triggers with the tumbling window the UI looks distorted.

## Reproduction steps

1. Go to Azure Data Factory 
2. Click on Azure data studio 
3. On the Data Studio Click on Manage
4. Create a Trigger with a tumbling window
5. Under the advanced option the UI looks to be distorted 

## Expected behavior

A clear UI from which user can easily understand and select the dependent options 

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: MacOs 12.3.1
 - Browser:  Google Chrome
 - Version: 103.0.5060.134

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
@anupamalok, this is the repository for open-source Azure API Management developer portal. Please refer to Microsoft Support for Azure Data Factory questions.
