### ISSUE TITLE
Self Hosted Portal - New user login won t work  

### ISSUE THREAD

**Issue by sjvarun** [Azure/api-management-developer-portal#1885]
## Bug description

In Self hosted portal , when a new user tries to login via the Azure Active Directory - Portal returns a 401 error. 

## Reproduction steps

1. Go to Self Hosted portal 
2. Click on Sign in -> AAD 
3. Pop up appears and closes down
4. Upon Opening browser console , 401 - Un-auth error is seen 

## Expected behavior

This is not the case with managed portal , when a user does not exist in APIM upon signing in via the managed portal using AAD user gets created . Same behavior is expected from self hosted portal 

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release 2.17.0 

## API Management service name

HapiTestApim 

## Environment

 - Operating system: Windows
 - Browser: Chrome , Edge

**Comment by azaslonov** [comment]
@sjvarun, this issues has been fixed last week. Please take the latest bits under release [2.18.2](https://github.com/Azure/api-management-developer-portal/releases/tag/2.18.2) re-publish the portal.
