### ISSUE TITLE
Navigation - can't nest menu items

### ISSUE THREAD

**Issue by KannanKalisamy** [Azure/api-management-developer-portal#189]
**Describe the bug**
I tried to add a new menu item under main menu . there is no option to add child menu item under the main nav.  and also i couldnt create a new Navigration group menu.

can you please let me know how to add a child menu and also how to create a new nav menu group.
![image](https://user-images.githubusercontent.com/16281799/66186380-70fbb280-e6c5-11e9-9828-b956195b7727.png)

**Comment by mikebudzynski** [comment]
Thanks, @KannanKalisamy - we're aware of the problem and the bugfix is coming (most likely) next week.
