### ISSUE TITLE
Unable to see 2xx responses to PUT/POST requests

### ISSUE THREAD

**Issue by zulfi-ahmad** [Azure/api-management-developer-portal#1891]
We've had multiple instances of Microsoft-managed developer portals for the past two years.  As of a couple of weeks ago (sorry, I can't be any more precise than that), we've noticed that 2xx responses to PUT and POST requests don't display in any of our instances of the portal.  The browser consoles display the information pasted below.  4xx/5xx responses are correctly displayed.  2xx responses from GET requests are correctly displayed.

We've only changed the dev portals via the Azure-supplied WYSIWYG editor.  We've tried resetting the content of some of the dev portals via the editor, but the bug persists.

Browser console content:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at OperationConsole.<anonymous> (theme.js:2:4002382)
    at Generator.throw (<anonymous>)
    at rejected (theme.js:2:3988691)
 (anonymous) @ theme.js:2
 rejected @ theme.js:2
 Promise.then (async)
 step @ theme.js:2
 (anonymous) @ theme.js:2
 __awaiter @ theme.js:2
 sendRequest @ theme.js:2
 (anonymous) @ theme.js:2
 (anonymous) @ theme.js:2
 __awaiter @ theme.js:2
 validateAndSendRequest @ theme.js:2
 (anonymous) @ theme.js:2
 theme.js:2 
        
POST https://developer.sandbox3.orderdynamics.net/trace 404 (Not Found)
 (anonymous) @ theme.js:2
 send @ theme.js:2
 (anonymous) @ theme.js:2
 fulfilled @ theme.js:2
 Promise.then (async)
 step @ theme.js:2
 fulfilled @ theme.js:2
 Promise.then (async)
 step @ theme.js:2
 (anonymous) @ theme.js:2
 __awaiter @ theme.js:2
 traceEvent @ theme.js:2
 (anonymous) @ theme.js:2
 (anonymous) @ theme.js:2
 __awaiter @ theme.js:2
 trackError @ theme.js:2
 handlerPromiseRejection @ theme.js:2
```

## Reproduction steps

1. Go to the developer portal
2. Sign in using an User that has a valid Subscription
3. Navigate to a PUT or POST API method 
4. Click the "try it" button
5. Enter the appropriate data for the API method such that it should return a 2xx response
6. Click the "send" button

## Expected behavior

The HTTP response would be rendered, including the response status code, the response headers, and the response body.  Instead, nothing is display, but we do see the info in the browser console as pasted above.

## Is your portal managed or self-hosted?

Managed

## API Management service name

OD-API-MGMT-AZ1
OD-API-MGMT-AZ3
OD-API-MGMT-AZCA
OD-API-MGMT-AZPERF
OD-API-MGMT-QA
OD-API-MGMT-SANDBOX3
etc

## Environment

 - Operating system: Windows
 - Browser: Google Chrome, Safari, Firefox
 - Version: the most current versions of the aforementioned browsers

**Comment by azaslonov** [comment]
It turned out to be known issue, fixed as part of this PR #1879. We're getting ready a new release.

**Comment by zulfi-ahmad** [comment]
> It turned out to be known issue, fixed as part of this PR #1879. We're getting ready a new release.

Any estimate as to when the new release will be deployed?

**Comment by azaslonov** [comment]
@zulfi-ahmad, it's in progress, it should be complete by end of this week.

**Comment by mrcarlosdev** [comment]
@zulfi-ahmad, could you please let me know if this issue was solved in your end so I can close the issue? Thanks

**Comment by zulfi-ahmad** [comment]
Yes, this issue has been solved.

**Comment by f-alizada** [comment]
@mrcarlosdev FYI closing since it is resolved. 
@zulfi-ahmad Thank you for the updates!
