### ISSUE TITLE
Option to change notification templates to self-hosted Portal

### ISSUE THREAD

**Issue by Ledger94** [Azure/api-management-developer-portal#1903]
## Bug description

It doesn't seem possible to link notification templates to new portal when it is self-hosted in a storage account.

## Reproduction steps

1. Go to reset-password page
2. Enter your email
3. The sent email is associated with the managed portal.

## Expected behavior

Option to change the template notifications to the self-hosted storage account

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.17

## Additional context

Specifically, I'm asking to change these kind of links in the APIM notification templates to the self-hosted Portal.

![image](https://user-images.githubusercontent.com/84686660/184356347-2a6d2905-92d3-450e-b56c-ff508e25f9a8.png)

**Comment by azaslonov** [comment]
@harunrst, can we solve this with app type setting?  If yes, can you please advise what needs to be done?

**Comment by Ledger94** [comment]
@azaslonov @harunrst 
Has there been any update related to this or do you need any more info from me? I'm thinking to include this feature an update to the APIM resource might be needed. Either an update to **Notification templates: E-mail settings** or on **Portal settings**.

**Comment by harunrst** [comment]
Hi @Ledger94, 
Thanks for reaching out to us. If you are using only self-hosted, you can easily update the information as below.
On Azure Portal, please navigate to Notification Templates/Password change confirmation. Here as you sent us, you can update the $ConfirmUrl as below:

**<your_hostname>**/confirm-v2/password?$ConfirmQuery

![image](https://user-images.githubusercontent.com/26141403/189613169-93973c4e-c010-4b2e-b68d-7fa7f9f35c36.png)

But if you have more than one developer portal and require them to have different templates, we need to make a feature work for it. Can you clarify your situation?

Sorry for the late reply.

**Comment by Ledger94** [comment]
@harunrst 
I didn't realized that there was a way to just get the query without the URL so it should work for us. I am however still of the opinion that the ability to update the URL parameter would be useful feature for users that are self hosting or just the ability to create a custom parameters in the notification templates. This is however up to you and the development team of Portal. I appreciate the help and will go ahead and close the issue.
