### ISSUE TITLE
Search field - The magnifying glass icon truncates the first letter of an entered search string

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1907]
## Bug description

When I enter a string in the search the magnifying glass icon is overlapping the first letter of my search string. After typing a string into the search field, the first letter is truncated by the magnifying glass icon.

## Reproduction steps

![2022-08-15_14-34-23](https://user-images.githubusercontent.com/58981351/184635958-11ae50aa-072f-4fd8-b7c1-96b0d74842cd.gif)

## Expected behavior

There should be at about 10 pixel distance between the magnifying glass icon and the first letter of a string that is entered in the search field. In addition, the width of the search field should be extended by about 30%. It is current too small to enter longer strings.

## Is your portal managed or self-hosted?

Managed

**Comment by SenpuDev** [comment]
Trying to reproduce this bug, but it seems is already solved.

![image](https://github.com/Azure/api-management-developer-portal/assets/109302954/f86815b6-5d4a-4ee8-aae0-d46c05b9981a)
