### ISSUE TITLE
Missing configuration on "List of APIs" widget - Collapse version sets by default (UX issue)

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1908]
## Bug description / expected behavior

Currently, by default all versions of all APIs are listed in alphabetical sort order in the "List of APIs" widgets. As an API consumer, if I am looking for available APIs, I am not interested in all these detailed information. I would like to see only the list of the display names and descriptions of the API version sets with their descriptions. 
Only in case, I found a desired API, as an API consumer, I want to be able to either click on the display name of the version set to open the latest version of this API in the API details view or I want to extend the displayed version set to see the complete list of available API versions with their individual descriptions and an additional column with the comma separated list of associated API products.

![image](https://user-images.githubusercontent.com/58981351/184643053-71804878-bfb6-4e4a-85c9-7f8ffcaffb8a.png)

Remark: 
- It should be possible in the search filter to also filter for APIs that are applied to dedicated API products (multi-selection in a list of API products or search in API products should be possible.
- The search string should not only be applied to the API display names, but also to the associated API product names.
- But in the search result list, if "collapse version set by default" is configured for the web widget, only the display names of the version sets should be listed.
- As the associated API products for the different API version can be different, for the display name of the API version set, no list of API product names should be displayed in the "Products" column of the search result list.
- - It should be possible from the "Products", to directly navigate to the product details page of a displayed API product. This would provide the user more transparency about the bundles and their dependencies between the different API versions.
- A similar configuration would be required in the "Associated APIs" web widget that lists the associated APIs of an API product. Here it should be also possible to configure in the web widget to collapse the list of APIs by default by the display names of the API version set. If the list is extended, it should be also displayed the detailed information which are the parent API products for which API version. By doing this, a user could easily identify which API products do include the same API version and could decided to describe to a different API product.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
cc: @mikebudzynski

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
