### ISSUE TITLE
Error building developer portal locally

### ISSUE THREAD

**Issue by i02coroj** [Azure/api-management-developer-portal#1909]
## Bug description

Since a few days back I'm getting an error when trying to run the developer portal locally. It seems to be related to paperbits package but no clue why or when it actually started to happen:

![image](https://user-images.githubusercontent.com/29977358/184871484-383e6d4b-48f0-4bee-a95b-4dadbd609170.png)

## Reproduction steps

1. Pull latest version from master branch
2. Remove **node_modules** and **dist** folders (if they were there).
3. Update config files to point to my instance
4. Run `npm install` and `npm run publish` (it also happens with `npm start`)
5. See error attached

## Expected behavior

The build works correctly

## Is your portal managed or self-hosted?

Managed, but I don't think it's relevant here as my issue is locally.

**Comment by azaslonov** [comment]
@i02coroj, hmm, I can't reproduce this. Can you please try the following:
1. `git clean -xdf` - cleanup files not in the repo.
2. `npm i` - install packages again
3. `npm start` - start.

**Comment by azaslonov** [comment]
There is another issue I just discovered though, so I'm reverting the last upgrade for now in #1911.

**Comment by i02coroj** [comment]
After pulling latest version with the revert everything is working ok again both locally and in DevOps builds.
So I think there's definitely a breaking change in that new version of the paperbits package.

Thanks for the fix. Feel free to close the ticket.
Cheers.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
