### ISSUE TITLE
Signup : Invalid field 'appType' specified

### ISSUE THREAD

**Issue by senthilkumardhanapal2** [Azure/api-management-developer-portal#1928]
Getting an error as **_Invalid field 'appType' specified_** while doing signup in developer portal. its an managed version of APIM(**ptzio03wummmapim**)

URL : https://prepmmmtzinterop.developer.healthtranzformdev.com

we also checked the developer tools by checking correct appType is getting passed and its ok.

<img width="203" alt="appTypeStatic" src="https://user-images.githubusercontent.com/81538941/188272134-61bc0289-7c72-4224-9272-efaa3ad6328c.PNG">
<img width="690" alt="singuPError" src="https://user-images.githubusercontent.com/81538941/188272135-38edc5c2-e556-415a-ab5a-0c2547043a1d.PNG">
<img width="300" alt="appTypePossible" src="https://user-images.githubusercontent.com/81538941/188272136-b6b1e3b7-bb87-4423-8b21-928ce851d67c.PNG">

Can you please check what is the issue ?

**Comment by senthilkumardhanapal2** [comment]
request details


`POST https://prepmmmtzinterop.developer.healthtranzformdev.com/signup

{
   'challenge':{
      'testCaptchaRequest':{
         'challengeId':'f3944f19-47f7-4312-b106-aad6f314d5c3',
         'inputSolution':'WDYWL'
      },
      'azureRegion':'WestUS',
      'challengeType':'visual'
   },
   'signupData':{
      'email':'senthild4u@gmail.com',
      'firstName':'SENTHILKUMAR',
      'lastName':'DHANAPAL',
      'password':'Password123',
      'confirmation':'signup',
      'appType':'developerPortal'
   }
}


Error 

{
   'code':'ValidationError',
   'message':'One or more fields contain incorrect values:',
   'details':[
      {
         'code':'ValidationError',
         'target':'appType',
         'message':'Invalid field 'appType' specified'
      }
   ]
}
`

**Comment by patrick-king** [comment]
I am getting the same issue after creating a new APIM instance and deploying the portal on 9/2/2022. As a workaround, I was able to go to the legacy developer portal and sign up, then sign in on the new portal.

**Comment by TimoTalasmaa** [comment]
I am getting this, too. I have devs wanting to sign up but now they cannot.

**Comment by aaron-infomedia** [comment]
Same issue as well. Have also tried republishing the portal to see if would fix the issue, but no such luck.

Can workaround by using the Invite button under Resource > Users, but that relies on new users reporting the issue so you know who to send an invite to.

**Comment by SankareswariKarthikeyan** [comment]
With @patrick-king  workaround, able to bypass sigunup 400 badrequest "Invalid Apptype"  from legacy devportal.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/112868440/188438746-93b2b7f8-f009-4b44-bbb6-ac0ed454f421.png)

![image](https://user-images.githubusercontent.com/112868440/188439214-1cec78e6-d7c4-4d01-b370-a7cd12f651be.png)
 
Both API version failed with 400 bad request "Invalid Apptype"

**Comment by c-f-allen** [comment]
We are also encountering this issue on 2 separate APIM instances starting in the last 2 days.

**Comment by ryansan** [comment]
Same issue in our instance.

**Comment by chiboubexp** [comment]
We're having the same issue on our instance as well.

**Comment by pacharanero** [comment]
We are also experiencing this issue, first reported by a user attempting to sign up yesterday.
This prevents all new API users signing up. It is therefore a very high priority issue.

**Comment by azaslonov** [comment]
Apologies folks, the fix is on its way. We have a list of affected services, but it is taking time to roll out. If you'd like to prioritize your service, please send us service name to apimportalfeedback@microsoft.com.

**Comment by senthilkumardhanapal2** [comment]
@azaslonov sending email for quick fix on affected \PROD instances. alternatively can we revert to previous version of APIM instances which will avoid this until we have the fix ?

**Comment by azaslonov** [comment]
@senthilkumardhanapal2, yes, this is also an option, but we still need a service name from you, we won't be able to perform mass-reverting.

**Comment by senthilkumardhanapal2** [comment]
Alexander,

We need atleast in this below instances very quickly. Could you please help me with ETA ?

ptzio04wuapim
ptzio04wuhsnapim
ptzio04wuhznapim
ptzio04wumfcapim
ptzio04wumhcapim
ptzio04wummmapim
ptzio04wupfoapim
ptzio04wuprkapim
ptzio04wupsbapim
ptzio04wusamapim
ptzio04wutpsapim

Thanks,
Senthil.

**Comment by azaslonov** [comment]
@senthilkumardhanapal2, thanks, ETA would be roughly 6 hours.

**Comment by senthilkumardhanapal2** [comment]
Thank you Alexander. I will keep the customer with update as it will be resolved before EOD today. I really appreciate your help on this.

**Comment by Schuckknight** [comment]
@azaslonov Wondering if the issue here could be causing the one we are seeing as well. We have a self hosted portal but use the managed portal to confirm new developers emails by making a call to the below endpoint:
https://{HostName}/confirm-v2/identities/basic/signup?userid={UserID}&identity={Identity}&ticketid={TicketID}&ticket={Ticket}

This call has stopped working and is giving a 400 response with a message of "Please ensure that the request formed correctly". It has been working in production for a while and we have made no changes in that area. We have not published the managed developer portal either during this time, so the managed portal is on the same version as it was when this was working. Like others, making the call using the legacy developer portal's host name works.

**Comment by senthilkumardhanapal2** [comment]
@azaslonov is this resolved. do we have an ETA for this to be fixed ?

**Comment by senthilkumardhanapal2** [comment]
@azaslonov is this resolved. do we have an ETA for this to be fixed ?

**Comment by linus-persson** [comment]
Is the bug solved? I still get this error.

**Comment by SidharthMacherla** [comment]
@azaslonov , this issue is still not resolved. Please help.

**Comment by Danziga1** [comment]
![image](https://user-images.githubusercontent.com/52224476/193150012-fb53fa36-6abd-45b7-bf37-e6c50edd6b28.png)
I am having the same issue, app type provided is 'developerPortal' in the payload which should be accepted but it is still not working for signup.

**Comment by SidharthMacherla** [comment]
Hi @Danziga1 ,
    I have raised a support ticket with Microsoft and they firstly gave me a workaround link for the same and eventually resolved it on 28th Sep. Hope this information helps you.

**Comment by PreciousEddy** [comment]
Ca someone please help confirm if this issue is resolved cause I am still getting the same issue?

**Comment by PreciousEddy** [comment]
> Hi @Danziga1 , I have raised a support ticket with Microsoft and they firstly gave me a workaround link for the same and eventually resolved it on 28th Sep. Hope this information helps you.

Please what was the work around they gave?

**Comment by ratheeshps** [comment]
For time being, sign up with classic portal and use it in the developer portal for login :)

**Comment by senthilkumardhanapal2** [comment]
Team,
Below instances requires quick fix ? is this something you can do immediately ?

ptzio04wuapim
ptzio04wuhsnapim
ptzio04wuhznapim
ptzio04wumfcapim
ptzio04wumhcapim
ptzio04wummmapim
ptzio04wupfoapim
ptzio04wuprkapim
ptzio04wupsbapim
ptzio04wusamapim
ptzio04wutpsapim

Thanks,
Senthil.

**Comment by azaslonov** [comment]
@senthilkumardhanapal2, all the services from your list have been upgraded. Thanks you for patience.

**Comment by azaslonov** [comment]
All services where upgraded, closing the issue.
