### ISSUE TITLE
Issue: Login request when opening deep link despite active session

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1931]
## Bug description

Deep linking to a (api operation) page in the DevPortal requires extra steps like changing & decoding the URL to this format:
`https://{DevPortal environment base URL}/returnUrl=/api-gallery/details{URL decoded hash key path for the specific API version}` 

e.g. `https://devportal-sandbox.com/signin?returnUrl=/api-gallery/details%23api%3Dexample-api-v2`

This works in the sense that users who receive a link like this are forwarded to the specified page **after login in again**, even if there is an current active DevPortal window/session. This raised some questions in our team and does not seem like intended behavior.

## Reproduction steps

1. Open the site you want to reference to in the DevPortal.
2. Copy the URL
3. Decode the URL.
4. Keep DevPortal window open.
5. Paste link in new tab

![image](https://user-images.githubusercontent.com/58420097/188568184-910206f2-7ae8-4f2d-a361-e4d5ad4a1aaf.png)

7. Get forwarded to login page while active window is open
 
![image](https://user-images.githubusercontent.com/58420097/188568429-fbe847e5-2d66-475d-95fc-49477c3d0eef.png)

9. Login.
10. Get forwarded to the deep link specified page.

## Expected behavior

After pasting and entering the decoded deep link URL the user should be immediately forwarded to the specified page without logging in again if there is an active session. This should obviously not undermine any security measure.

## Is your portal managed or self-hosted?

Managed

**Comment by AnRei123** [comment]
I would also very much appreciate if DEVs in our teams would be able to simply copy the URL from the browser address bar without the need and efforts to decode it before providing the deep link in emails or chats to other colleagues or partners.

**Comment by AnRei123** [comment]
Alternatively, it would be at least an improvement if you would offer a copy deep link button on the API details page widget.

**Comment by AnRei123** [comment]
And it would be perfect, if you would also provide an option to always link to the first operation of the latest version of an API .

**Comment by azaslonov** [comment]
Hello folks, yes, it was just a bug in portal's backend, we have just fixed it. It'll go to nearest service release.
