### ISSUE TITLE
Misformated HTTP response body in dev portal when trying out API

### ISSUE THREAD

**Issue by Radamonas** [Azure/api-management-developer-portal#1936]
## Bug description

Response JSON is not formatted as JSON, but as a single line string:

![image](https://user-images.githubusercontent.com/17021450/189056595-b84e58b9-49e3-46ae-a4a3-4ff7ad3b2e50.png)

## Reproduction steps

1. Go to APIs
2. Click on any API we have
3. Select subscription and enter querying values
4. Hit SEND
5. Receive HTTP 200 response and misformatted response body

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Opera/Chrome
 - Version: 90.0.4480.84/105.0.5195.102

## Additional context

Previously HTTP section in DevPortal was parsing JSON without any issues. Similar issue was raised in [StackOverflow](https://stackoverflow.com/questions/73621844/output-of-the-json-not-formatted-in-apim-developer-portal)

**Comment by azaslonov** [comment]
This issues has been fixed in #1929. Managed portals will receive the update some time next week.

**Comment by nuwan600** [comment]
getting same issue again 
 
![image](https://user-images.githubusercontent.com/4129563/191411927-3160c635-c44c-48b0-8775-df2669cdece8.png)

**Comment by nuwan600** [comment]
plz have look @azaslonov

**Comment by azaslonov** [comment]
@nuwan600, the fix for this is being rolled out as we speak. It should be over in all regions by the end of the week.

**Comment by nuwan600** [comment]
thankx..

**Comment by Radamonas** [comment]
This can be closed as it was resolved.
