### ISSUE TITLE
Link in the confirmation email doesn't work return 400 status code when using delegation

### ISSUE THREAD

**Issue by marwenlandoulsi** [Azure/api-management-developer-portal#1939]
## Bug description

We have been using the delegation for a while to connect to the api management and never had any problem but
we have been made aware last week by our users that when they click on the confirmation link of the email after registering that they don't have access to the APIM.
On the back we can see that the state of the users is still pending and not active.

## Reproduction steps

1. Go to 'developers.xxx.fr'
2. Click on 'Sign up'
3. Sign up
4. Go the adress email and click on the confirmation link " https://developers.xx.fr/confirm-v2/identities/basic/signup?userid=3daf5709-8f3f-4fd7-8334-7ab8558c6a22&identity=xx.xx%40fr.org&ticketid=6061bfc925eff105a0eec3f9&ticket=7c43a903c53641f6aa5789bce6355b79
5. we have 400 status code with response : {
"code": "BadRequest",
"message": "Please ensure that the request formed correctly."
}

## Expected behavior

1. Go to 'developers.xxx.fr'
2. Click on 'Sign up'
3. Sign up
4. Go the adress email and click on the confirmation link " https://developers.xx.fr/confirm-v2/identities/basic/signup?userid=3daf5709-8f3f-4fd7-8334-7ab8558c6a22&identity=xx.xx%40fr.org&ticketid=6061bfc925eff105a0eec3f9&ticket=7c43a903c53641f6aa5789bce6355b79"
5. Get redirected to 'developers.xxx.fr' with a active profile

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
@marwenlandoulsi, could you please send us your service name to apimportalfeedback@microsoft.com? We have fixed an issue with similar symptoms and rolling it out now, but if you'd like to prioritize your instance, we would need the APIM service name.

**Comment by marwenlandoulsi** [comment]
@azaslonov, I sent the email with the requested information

**Comment by azaslonov** [comment]
@marwenlandoulsi, I'm closing this issue since we resolved it offline. Thanks for your patience.
