### ISSUE TITLE
Pages exposed although "Redirect anonymous users to sign-in page"

### ISSUE THREAD

**Issue by innoforce-dev** [Azure/api-management-developer-portal#1946]
## Bug description

We need to protect certain pages with descriptions from anonymous users. Thus we've activated the option "Redirect anonymous users to sign-in page" (in Developer portal > Identities > Settings). 
When I open a new incognito window navigate to one of my custom pages, e.g. /usage then I'm thrown back to the sign in page as expected. But once I was logged in, then sign out, I am able to navigate each page without restriction! 

## Reproduction steps

1. Setup "Redirect anonymous users to sign-in page" in your APIM instance
2. Create a custom page in the developer portal
3. Publish
4. Open the dev portal in a incognito window
5. Navigate to the custom page => redirected to sign in as expected
6. Sign in, navigate to custom page => displayed as expected
7. Sign out. Then navigate to custom page => displayed although it should not! 

## Expected behavior

Anonymous users should always be redirected to the sign in page if  "Redirect anonymous users to sign-in page" is activated.

## Is your portal managed or self-hosted?

Managed 

## API Management service name

[e.g., dghno-demo-api]

## Additional context
![2022-09-16_09-15-01](https://user-images.githubusercontent.com/20574773/190583392-a0feaa26-46d7-47ff-9325-550bacbc3cc1.png)
![2022-09-16_09-25-58](https://user-images.githubusercontent.com/20574773/190583406-a933303b-0a9a-4491-b5e6-4458680452ef.png)
![2022-09-16_09-38-04](https://user-images.githubusercontent.com/20574773/190583684-c6a8aa2b-c19c-4945-8032-a41f5da0e33d.png)

**Comment by maciejtreder** [comment]
Hello @innoforce-dev ,

Thank you for reporting that. I can confirm that I've reproduced this issue on production. The fix will be deployed with the upcoming release.
