### ISSUE TITLE
"Try it" feature causes unresponsive browser but completes after 5 minutes

### ISSUE THREAD

**Issue by dabuterbaugh** [Azure/api-management-developer-portal#1956]
## Reproduction steps:
- Sign in
- Navigate to Products
- Navigate to API
- Select API action
- Click "Try it"
- Under authorization, select authorization_code and enter my Auth0 credentials in the window.
- Click Send.  After about 10 seconds, Chrome displays
![image](https://user-images.githubusercontent.com/114241783/191985720-b67c03b7-055c-44b2-86c6-a486ee38ba5d.png)
- After about 5 minutes, the response does finally show.

The portal is Managed.

## API Management service name

ApiMgr-qa

## Environment

 - Operating system: Windows 10
 - Browser: Chrome, Edge
 - Version: 

## Additional context

We have determined that this only happens on larger responses.  Smaller responses work fine.

Chrome and Edge both exhibit the same issue.

Upon further analysis with Wireshark, I found that the larger responses do not return an HTTP content-length header because the response is streamed.  The last packet of the response does include the HTTP "End Stream" flag and I am able to see the JSON payload.  Wireshark also shows that the developer portal sends some HTTP keep alive messages until nearly 5 minutes later the API replies with an HTTP GOAWAY.  Shortly after, developer portal does a /trace request and the response is shown.

When using Chrome Debug Tools, I do not see the network response until after the 5 minute timeout.

I have confirmed through Postman and, using Chrome website https://resttesttest.com/ that the request works normally.

**Comment by ygrik** [comment]
Hi @dabuterbaugh 
Could you please provide traces for requests.

**Comment by dabuterbaugh** [comment]
We can no longer reproduce.  Closing issue.
