### ISSUE TITLE
APIM Developer Portal is not reachable in private VNet

### ISSUE THREAD

**Issue by svirchenko** [Azure/api-management-developer-portal#1963]
I'd like to use APIM Developer Portal inside private VNet to expose it only for internal users.

Right now I am getting an error "ERR_NAME_NOT_RESOLVED" when trying to open Dev Portal inside private VNet. Usually it means that the domain name cannot be resolved. In general, It looks like a DNS related issue.

Do we have any documentation how to resolve this issue?

![APIM](https://user-images.githubusercontent.com/113915129/193829662-7ccbcc89-3091-467d-abee-c69f4c58a42c.png)

**Comment by harunrst** [comment]
Hi @svirchenko , thanks for reaching us.

There is a [guide here](https://learn.microsoft.com/en-us/azure/api-management/developer-portal-faq#do-i-need-to-enable-additional-vnet-connectivity-for-the-managed-portal-dependencies) you can follow. It is most likely an issue with the DNS configuration.

Let me know if it helps :)
