### ISSUE TITLE
Configuration Endpoint does not resolve when using Custom Domains

### ISSUE THREAD

**Issue by davejhahn** [Azure/api-management-developer-portal#1967]
## Bug description

When using custom domain names, the DNS for the original Azure provided names no longer resolve (e.g. [instance].developer.azure-api.net).  

When deploying self-hosted gateways, since there is no custom domain option provided for [instance].configuration.azure-api.net, it is unable to connect and configure.

## Reproduction steps

1. Create APIM
2. Test Azure provided DNS for management, gateway, development portal & ensure they are working
3. Add custom domains for management, gateway, and development portal
4. Test & ensure custom domains work
5. Test original Azure provided names, they do not resolve, including [instance].configuration.azure-api.net

## Expected behavior

Either the original Azure provided DNS entries continue to work and the self-hosted gateway can resolve the Azure provided configuration endpoint or an option to create a custom domain for the configuration endpoint.

## Is your portal managed or self-hosted?

Managed

## Additional context

**Azure provided domains (DNS does not resolve):**
ping XXXXXXXX.developer.azure-api.net
Ping request could not find host XXXXXXX.developer.azure-api.net. Please check the name and try again.

ping XXXXXX.configuration.azure-api.net
Ping request could not find host XXXXXXX.configuration.azure-api.net. Please check the name and try again.

**Custom domains (works fine):**
ping XXXXXXXXXXXXXXXXXXXXXXXXX
Pinging XXXXXXXXXXXXXXXXXX [A.B.C.D] with 32 bytes of data:

I read about support of custom domains for the configuration endpoint [ConfigurationApiV2NotAvailable](https://learn.microsoft.com/en-us/azure/api-management/how-to-self-hosted-gateway-on-kubernetes-in-production#configuration-backup)], but it looks like it is not an option for v2.  I thought maybe if I forced the deployment to resolve to the correct IP with the Azure provided configuration DNS it might work, but even though it resolves, it returns an error message: 

[ConfigurationApiV2NotAvailable], message: The configuration V2 API is not reachable on https://XXXXXXX.configuration.azure-api.net/gateways/dapr/snapshot, source: ConfigurationApiClient

Added this to the deployment (using the manifests directly instead of the Helm chart):

```
    spec:  
      hostAliases:  
      - ip: "A.B.C.D"  
        hostnames:  
        - "XXXXXXXXXXXXX.configuration.azure-api.net"  

```

And when I exec into the pod that is failing, I can resolve the DNS to the proper IP via ping, it just seems that the APIM is not responding the configuration domain.

So really at this point, I'm not sure how resolve so that the Kubernetes deployment can access the APIM configuration endpoint.

**Comment by tomkerkhove** [comment]
Thank you for the report @davejhahn - Is this bug related to the developer portal in any way because it feels like it is not the case. Can you confirm this please?

Given this is mainly around custom domain names and self-hosted gateway, the recommendation is to open an Azure Support ticket.

With regards to the Configuration API v2; custom domain names are not supported for now indeed as documented on https://aka.ms/apim/shgw/migration/v2#known-limitations

**Comment by davejhahn** [comment]
I added an issue to the apim self-hosted gateway repository, so closing this since it is not related to the portal as you noted.

Thanks,

Dave

**Comment by tomkerkhove** [comment]
Thanks! The same suggestion applies though - It's best to open an Azure Support ticket.

For those interested: https://github.com/Azure/api-management-self-hosted-gateway/issues/164
