### ISSUE TITLE
API Management developer portal logout mechanism not revoking B2C token

### ISSUE THREAD

**Issue by chytanyapua** [Azure/api-management-developer-portal#1968]
## Bug description

In developer portal when B2C User is Sing-Out, Portal not revoking Token. After sign-out, user still able to make valid requests using same idToken/sharedAccessSignature Token value and get new access tokens from Azure B2C.

## Reproduction steps

1. Sign-out from portal.
2. User previous "auth" cookie as header make valid calls.
3. calling GET /token request. we can get token.
4. further using Authorization header you make different calls to portal and get data.

## Expected behavior

Logout functionality should allow users to manually log out of the application and should terminate their authenticated session upon logout, immediately removing all access to protected resources from that session, including established sessions for back-end APIs.

## Is your portal managed or self-hosted?

Managed.

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by harunrst** [comment]
Hi @chytanyapua ,
Thanks for reaching out. I confirm the issue and we will take a look to fix this. :)

**Comment by chytanyapua** [comment]
Hi @harunrst, This is identified as a security vulnerability. Could you please let us know, when we can except a fix for this?

Also, Could you please if there is any option/reference to fix this using custom widget by calling B2C logout endpoint?

**Comment by harunrst** [comment]
Hi @chytanyapua , 
We have started working on the fix, it will roll out in the first quarter of next year.
And about any workaround, unfortunately, no other way.

**Comment by andremarques023** [comment]
Is there any update on this?

**Comment by andremarques023** [comment]
Hi @harunrst,

Is there any update on this?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
