### ISSUE TITLE
API specifications - External CSS styles in widgets - Necessary styling not possible

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1972]
## Bug description

In our DevPortal environments we have some APIs that are or will be deprecated and will no longer be supported.
To warn our users and partners beforehand we implemented a template for our developers to add to their API specification.

This template references an icon and external css styles from a blob storage. The icon is added to the "deprecation note" but the styles are not applied and therefore the design is messed up.

Deprecation note without styles in the DevPortal:
![image](https://user-images.githubusercontent.com/58420097/196391901-ea741fdc-ce3d-47b5-bd58-202f810e10fa.png)

Deprecation note with styles in the DevPortal:
![image](https://user-images.githubusercontent.com/58420097/196406850-67ee23c5-b400-4503-ac40-2c552f5f1d1e.png)

The styles are necessary to highlight this note to make sure the users are aware of the upcoming deprecation.

These Issues talked about the same topic of external css styles not being applied:

- #1602 
- #1880 

It was mentioned that "_filtering of the HTML happens by design_". 

_"However, we do understand the problem you're trying to solve, and working on enabling styling of sub-components, so that you'd be able to style practically every element of "Operation details" and other widgets. This, I believe, should address most of the customization questions."_

Are there any upcoming changes or news regarding this statement?
And will it be possible to style elements from the API specification JSON file, or set a default for all widgets of this type, as styling the widgets for every API is a lot of effort.

As mentioned before the deprecation notes are added in the API specification JSON file and are handled by the responsible teams themselves. It would be essential to add a reliable and consistent feature to add external css styling in DevPortal widgets through the API specifications. Inline css would not be feasible to implement across all teams.

## Reproduction steps

1. Change any API specification code to reference an external .css file with styles
2. Update the API specification
3. See in the DevPortal that the styles are not applied (intended behavior)

## Expected behavior

Adding external css styling to e.g. the API description in the API specification should be reflected, without breaking other DevPortal styles,

## Is your portal managed or self-hosted?

Managed

--- 
@AnRei123

**Comment by malincrist** [comment]
As mentioned in the issues you provided, we do not support and do not plan to support external CSS.

>Are there any upcoming changes or news regarding this statement?
And will it be possible to style elements from the API specification JSON file, or set a default for all widgets of this type, as styling the widgets for every API is a lot of effort.

This feature is still under development, and we do not have an ETA at this moment. 
This feature will not provide the possibility to style elements from the API specification json file. 

It will provide the possibility to style internal elements of the widgets (such as text, buttons, combo boxes etc.): you will be able to style the description of the APIs but **that style will be applied for all the descriptions of all the APIs**, regardless of the template you provide.

>It is important for us to share such a notice and to share a roadmap to the users in the deprecation flag/note.
Also the deadline, when the API will be deprecated, needs to be present.

We understand this is important and we are working on the deprecation support: we will support this in Azure Portal and it will be automatically reflected in the Developer Portal. It should be out in a few months.

Regarding how to show deprecation details, you should be able to achieve this behavior by using a custom widget (and implement the logic there). [Here ](https://learn.microsoft.com/en-us/azure/api-management/developer-portal-extend-custom-functionality)you have more details about how to use it.

Hope this helps.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
