### ISSUE TITLE
Unable to run the migrate.js using destination parameters -- node : Unable to complete migration. Unable to complete cleanup. Unable to delete content. Unable to fetch content types. Looks like you are not allowed to perform this operation.

### ISSUE THREAD

**Issue by hammdo** [Azure/api-management-developer-portal#1976]
What permissions are necessary for the service principal in order to perform a clean/delete and import? Currently, we have:

Register app to create service principal, create secret

add role assignment with APIM READ access DELETE and WRITE access on the app

add the service principal as the contributor in APIM

We're failing with:

Cleaning up...
node : Unable to complete migration. Unable to complete cleanup. Unable to delete content. Unable to fetch content types. Looks like you are not allowed to perform this operation.
Please check with your administrator.
At F:\projects\Rogue-One\dev-portal\api-management-developer-portal\scripts.v3\DevPortalMigration.ps1:144 char:7

  node .\migrate --sourceSubscriptionId \`"$sourceSubscriptionId\ ...
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (Unable to compl... administrator.:String) [], RemoteException
FullyQualifiedErrorId : NativeCommandError

**Comment by hammdo** [comment]
I think I found what was needed.  We needed to make sure when running in powershell it called node in a  diagnostic process so when the az login was called, the environment was available.  What we were doing was calling node directly in powershell vs a 'shell execute'.
e.g.,

    $psi = new-object "Diagnostics.ProcessStartInfo"
    $psi.FileName = $program 
    $psi.Arguments = $argumentString

    $psi.CreateNoWindow = $true 
    $psi.UseShellExecute = $false 
    $psi.RedirectStandardOutput = $true 
    $psi.RedirectStandardError = $true 

    #write-host $psi.FileName
    #write-host $psi.Arguments

    #$proc = [Diagnostics.Process]::Start($psi)
    $proc = New-Object System.Diagnostics.Process 
    $proc.StartInfo = $psi

    $timer = [Diagnostics.Stopwatch]::StartNew()

    # Process starts here
    [void]$proc.Start()

    $proc.WaitForExit();  

    $timer.stop()
...

**Comment by jsorohova** [comment]
Hello @hammdo , did your findings resolve your issue?

**Comment by hammdo** [comment]
Yes, all good!

Sent from my iPad

On Nov 2, 2022, at 1:45 PM, Elena Shorohova ***@***.***> wrote:

﻿

Hello @hammdo<https://github.com/hammdo> , did your findings resolve your issue?

**Comment by jsorohova** [comment]
Thank you!
Closing the issue now.
