### ISSUE TITLE
API definitions (Schema) changes not visible in developer portal

### ISSUE THREAD

**Issue by w-van-eck** [Azure/api-management-developer-portal#1979]
Hi,
I have an issue where I make a change to an existing definition, want to review it in the developer portal, and the change is not there.

Worse is, I have deleted an existing definition, created a new one with the same name, but different structure, what then is visible in the portal is the old structure of the schema I just deleted.

I saved the latest situation to the git repository, cloned it, and I see that the schema is as expected including the changes I made.

I tried many different ways to get the expected results like publishing the latest version of the portal, deleting schemas with a different name.

I think it is just limited to the definitions, because when I make a change on at the method level, the changes are instantly visible in the dev portal.

I would love to help troubleshooting this, but I have no errors to go on.

**Comment by jsorohova** [comment]
Hello @w-van-eck, thank you for reporting the issue. 
Could you please provide more detailed steps to reproduce the issue? I am currently not able to reproduce it and I need more information from you to help you. 

If you need to share a sensitive information like your definitions specification files, you can send it to us to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com).

**Comment by w-van-eck** [comment]
Hi,

Say that I have this definition called “ProcessedCoupon” as shown below which is currently defined in APIM.

***@***.***

The Developer portal shows the matching definition as expected.. see below.

***@***.***


I add the “description” fields to the three properties “type”, “value”, and “quantity”..
***@***.***

There are no errors (red border around the schema field), I save it, it and it reports successful:
***@***.***

Going back to the developer portal, refresh the page and the definition is unchanged as shown below:
***@***.***

No matter what I do, clear cookies, close browser, save API Method where the definition is used in, switch between APIs etc.
Nothing happens… however, at some point hours later, the change make come to the portal. If I had done some other changes, I might see one change but not the other.

BUT…

A change at the method level, like changing the description or add a parameter or change a request type works instantly..

***@***.***

Description matching in the developer portal:
***@***.***
A change made to the description:
***@***.***

Instantly changed in the developer portal.
***@***.***

I am not sure when this behaviour started, never had this issue before but now it happens no matter which definition I change of any API.




Met vriendelijke groet, kind regards,

Wouter van Eck
Solution Architect
T +31 (0)13 711 5175<tel:+31%20(0)13%20711%205175>
E ***@***.******@***.***>
W boxplosive.nl<https://boxplosive.nl/>

[cid:boxplosive-website-teaser_878ba1ce-5cc1-4a62-8456-c7984b1ff804.png]<https://boxplosive.nl>

[cid:boxplosivelogo_855bf299-7db1-4fc5-b581-91b67c8f2b6f.png]<https://boxplosive.nl>
Boxplosive BV | Kraaivenstraat 25-59 | 5048 AB  Tilburg | The Netherlands
The information sent in this e-mail is only intended for the addressee(s). If you receive this e-mail in error, we kindly request that you do not use the content, contact Boxplosive and delete the e-mail. Boxplosive makes every effort to ensure that you receive this message fully, timely and virus-free. Publication, multiplication, distribution and / or provision of this information to third parties is only permitted after permission from Boxplosive.

**Comment by w-van-eck** [comment]
Hi All,

Is there any update on this issue?

**Comment by wvaneck** [comment]
Hi, that is good news.

**Comment by ygrik** [comment]
Hi @w-van-eck 
I see you mention that you did clear cookies, close browser
Did you try to clear the browser cache for the developer portal?

**Comment by ygrik** [comment]
Added [PR](https://github.com/Azure/api-management-developer-portal/pull/2065) to decrease the apis schema refresh timeout from 60 to 5 min
The logic is to show cached schema in UI and start reloading new schema if it older than 5 min.
