### ISSUE TITLE
CONTRIBUTIONS.md has dead link to contribution guidelines 

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/api-management-developer-portal#1985]
CONTRIBUTIONS.md has dead link to contribution guidelines :
https://github.com/Azure/api-management-developer-portal/blob/master/CONTRIBUTIONS.md

**Comment by harunrst** [comment]
Hey @tomkerkhove,
Thanks for reporting, we will take a look :)

**Comment by mikebudzynski** [comment]
Fixing with #1986 and #1987.
