### ISSUE TITLE
Text in text widget not selectable

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2013]
## Bug description

When working with a text widget it currently is not possible to select the text in a text widget.

Using different methods like double clicking or using the "edit text" button etc. to access the text have been unsuccessful.
Trying different methods on an previously existing and a new text widget:
![TextEditIssue](https://user-images.githubusercontent.com/58420097/203272660-f7df9254-73a1-4900-b7b0-38972597e9a8.gif)

For only one time it was possible to somehow highlight the text (typing, deleting etc. was not possible) and replace it with the content of the clipboard. It is not reproducible by me.

This issue also exists for my coworkers with different machines.
This issue occurred to me in the reset portal and a portal with content.
This issue exists across different portals we possess.

## Reproduction steps

1. Go to any page.
2. Add a new text widget.
3. Try to select any text in the new widget.

## Is your portal managed or self-hosted?

Managed

**Comment by jsorohova** [comment]
Hello @ZarTrox , thank you for reporting this issue. It is a known one and we are rolling out the fix very soon. Sorry for inconveniences.

**Comment by rossmcwattiecf** [comment]
> Hello @ZarTrox , thank you for reporting this issue. It is a known one and we are rolling out the fix very soon. Sorry for inconveniences.

When you say soon, what does that mean?  It's causing us a significant issue with us not being able to update content on our production portal.

**Comment by malincrist** [comment]
Hello @ZarTrox, the fix for this issue has been rolled out.
