### ISSUE TITLE
Deep links - Empty API displayed when session is expired or user logged out

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2026]
## Bug description

Recently the behavior of deep links changed (see #1931 ) so that the URL of e.g. an API details page with the operation could be copy pasted and the recipient can simply click the link and be forwarded.
If the recipient who clicked the link was not logged in the sign in page would open and after the login he would be forwarded to the specified page. This is intended and good behavior.

But there is an issue if a session expired and a (correct and working) deep link is clicked the API details page is displayed like this:
![image](https://user-images.githubusercontent.com/58420097/205278782-65ef2dae-cfa1-49ef-8fa1-929d0403166d.png)

## Reproduction steps

1. Clear cookies
2. Click deep link 1
-> Successful after login
3. Keep page open
5. Create deep link 2
7. Click deep link 2
-> Successful without login
9. Close window
10. Click deep link 2
-> Successful
11. Logout
12. Close window
13. Click deep link 2
-> **Empty API & no login required** See screenshot in [Bug description](#bug-description)
15. Refresh page with "Shift + F5" (normal refresh is not helping)
-> Successful after login

## Expected behavior

It is expected that if a session expired or the user is logged out of the DevPortal to be forwarded first to the sign in page and then to the target page. The issue that users see that an API is not existing should not be possible and should be avoided.

When not logged in/no active session exists:
- Forward to sign in page
- After login forward to target page

When logged in/active session exists:
- Immediately go to target page
- No hard refresh necessary to see the correct page

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Chrome
 - Version: Version 107.0.5304.123

**Comment by harunrst** [comment]
Hey @ZarTrox , thanks for reaching us. I could not reproduce the behavior, in all steps I successfully opened the page. Can you review the reproduction steps? Also, you can reach out to us via _apimportalfeedback@microsoft.com_ with your service name, so that we can investigate it better.

**Comment by ZarTrox** [comment]
Sent information per mail and also an follow up mail. Is this still in the scope to be worked on?

**Comment by harunrst** [comment]
Hey @ZarTrox , I am able to reproduce it. There is a weird situation happening. I will try to make sure that the fix will be implemented soon. Thanks for reaching us.

**Comment by ZarTrox** [comment]
Hi @harunrst, when the situation is resolved could you keep me posted in this ticket? Or will it be updated on release notes?

**Comment by ZarTrox** [comment]
Or is there an ETA already?

**Comment by ZarTrox** [comment]
@harunrst Reminder, that this issue has not yet been resolved for us.

**Comment by christophmantsch3302** [comment]
@harunrst @ZarTrox The problem still persists for us, do you have an expectation when the problem will be resolved?

**Comment by dannoz** [comment]
I am struggling with the same issue on the self hosted dev portal. #justsaying

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
