### ISSUE TITLE
Widget - Sign-In : OAuth button visibility issue 

### ISSUE THREAD

**Issue by sjvarun** [Azure/api-management-developer-portal#2028]
## Bug description

In new release of portal 2.21.0 " Sign-In : OAuth" widget button "Azure Active Directory" does not hide itself after authenticated . AAD Button visibility is set to Anonymous and after changing role to Authenticated , it does not hide itself . Same is true when login is successfully . Please see screen shot attached

## Reproduction steps

1. Go to managed portal 
2. Add widget Sign-In :OAuth , set its visibility to Anonymous 
3. Now change the Role from Anonymous to Authenticated or Login using AAD button
4. In both the above cases AAD button does not hide itself 

## Expected behavior

AAD button should hide itself after success full login , since its visibility is set to Anonymous.

## Is your portal managed or self-hosted?

Managed & Self Hosted Portal

## Release tag or commit SHA (if using self-hosted version)

2.21.0

## API Management service name

hapidevapim

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.
![image](https://user-images.githubusercontent.com/17843040/205573502-1ed225b1-a83e-4018-9792-2f132de22b7c.png)

**Comment by StacyCMay** [comment]
I am seeing this behaviour with all widgets that I want to only be visible given the state of the visitor (i.e. Anonymous vs. Authenticated). When I add a menu item that I only want visible if the user has been authenticated, it is also visible for anonymous users, and vice versa

**Comment by mazer-rakham** [comment]
This is also happening with Username/Password
Signed in:
![image](https://user-images.githubusercontent.com/11220261/206237406-db87a66a-1f50-40af-bac4-e8c85ded2f8b.png)



Signed Out:

![image](https://user-images.githubusercontent.com/11220261/206237497-8a39c11e-8cb9-461c-b374-02dc374f403e.png)

**Comment by mikebudzynski** [comment]
We couldn't reproduce the issue. Please contact Azure support to troubleshoot the problem.
