### ISSUE TITLE
grant type authorizationCodeWithPkce in developer portal puts an extra "/" at the end of authorize endpoint

### ISSUE THREAD

**Issue by zyofeng** [Azure/api-management-developer-portal#2030]
I have configured Oauth2 for developer portal using the api according to this change
https://github.com/Azure/api-management-developer-portal/pull/1945

I have both grant type configured as below:
![image](https://user-images.githubusercontent.com/23351416/206342977-8a642b2c-fb41-49a1-a06b-97424288f705.png)

and noticed that for authorizationCode, the redirection is correct
![image](https://user-images.githubusercontent.com/23351416/206343185-18fb4390-0bfc-496a-975f-f93e47ee77d6.png)

With pkce im getting this, note that the extra / after authorize, which doesn't exist in my configuration.
![image](https://user-images.githubusercontent.com/23351416/206343048-2c6c4bcc-cd55-44de-83f3-585ed68c3e5c.png)

These two should really be the same with the exception of query string having extra params in pkce.

**Comment by FrankPan1990** [comment]
Hi Team, I attached the position of source code and "/?" it is a little strange that we add a "/" here. 
https://github.com/Azure/api-management-developer-portal/blob/HEAD/src/services/oauthService.ts#L218
