### ISSUE TITLE
Error with displaying the API operation details on APIDetails page in private Firefox mode

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2031]
## Bug description

Currently when opening the APIDetails page of a DevPortal environment in the private Firefox browsing mode the operation details of some APIs are loading infinitely.

APIDetails page with an loading API operation details widget:
![image](https://user-images.githubusercontent.com/58420097/206389343-34bc9a57-8795-4cd3-9faf-c9bdeec56ff7.png)

Loading API operation details widget:
![ApiDetails](https://user-images.githubusercontent.com/58420097/206389486-cdff87bc-2b12-48ba-ad70-2483c07e21f2.gif)

When checking the console for errors the following message is displayed:
Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/58420097/206389807-4415481d-75a9-4998-90bc-dbd51e5c76c8.png)

The bug does not occur in all APIs but multiple are affected.
The issue is only visible in Firefox. Edge and Chrome are working as expected.

## Reproduction steps

1. Open private mode in Firefox
2. Sign in to a DevPortal environment
3. Select an API until the API contains the error
4. Check console

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser: Firefox
 - Version: All versions

**Comment by harunrst** [comment]
Hey @ZarTrox , it is not reproducible at the moment. Please confirm, if it is still the issue, could you share your service name for us to investigate?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
