### ISSUE TITLE
The REST API specification for ContentType & ContentItem are missing the 'in body' parameter for UpdateOrCreate

### ISSUE THREAD

**Issue by AdamCoulterOz** [Azure/api-management-developer-portal#2038]
## Bug description

I have created a detailed issue https://github.com/Azure/azure-rest-api-specs/issues/21849: API Management - ContentType & ContentItem - CreateOrUpdate - missing the 'in body' parameter specification 

## Reproduction steps

I've been attempting to use the `@azure/arm-apimanagement` nodejs library to do more fine-tuned automation with the developer portal configurations. This library is autogenerated from the resource type definitions. `ContentType` and `ContentItem` are missing the body request part in the `CreateOrUpdate` method parameter lists. This is both in the library and in the REST API documentation for those resource types.

For example, if you [run the "Try It" for this API](https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/content-item/create-or-update?tabs=HTTP), it doesn't give you a body field in the auto-generated REST HTTP request form. The body field is needed, but it doesn't give you that field. It's not populated in the OAS for this resource type. Which breaks all the library code generated from the REST API Specs also.

**Comment by malincrist** [comment]
Hello @AdamCoulterOz ,

As I can see in the issue you opened in the[ azure-rest-api-specs ](https://github.com/Azure/azure-rest-api-specs/issues/21849), they have fixed this issue.

As this is not related to developer portal, is there any follow-up request regarding this, that we can help you with?
