### ISSUE TITLE
Azure AD Login - Issue

### ISSUE THREAD

**Issue by KannanKalisamy** [Azure/api-management-developer-portal#204]
**Describe the bug**
Ive configured api management "Azure Active Directory" identity provide. Im not able to login  into  preview developer portal. After sign-in process its redirect to signin page doesnt process the token and profile page was empty.  but when i try the same process in old portal its works. 

And also menu still doesnt show the logged in user name . i was expecting after sign-in process menu should show profile name and sign out link ( both are missing in the new preview portal ) .

it would be great if you could address this issues.

When i try to debug the authentication service code. Getting below error in the aadservices.ts - > exchangeIdToken

Authentication failed. Header with access token is missing.

**Comment by mikebudzynski** [comment]
> And also menu still doesnt show the logged in user name . i was expecting after sign-in process menu should show profile name and sign out link ( both are missing in the new preview portal ) .

A dynamic menu is coming with #77 (although it may not contain profile name).

> Ive configured api management "Azure Active Directory" identity provide. Im not able to login into preview developer portal. After sign-in process its redirect to signin page doesnt process the token and profile page was empty. but when i try the same process in old portal its works.

@azaslonov Could you please take a look?

**Comment by KannanKalisamy** [comment]
@mikebudzynski Also after AAD Sign process is completed , if user not exists in the APIM user store, then redirect to sign up form to complete the sign process ? Can you confirm this functionality will be included  ?

**Comment by azaslonov** [comment]
Hi @KannanKalisamy, yes, if not exists, user will be created as part of the process.

**Comment by lucaszacutti** [comment]
Hi Alex, I not sure if this is a bug related with this issue.. When we use AD B2C (Google auth) can't complete sign up because we get a 403 error:

![AzureAD_B2C_Google](https://user-images.githubusercontent.com/13422243/73457314-3f80b400-4352-11ea-83b8-b1b558e9cbad.JPG)

![Error403](https://user-images.githubusercontent.com/13422243/73457333-43acd180-4352-11ea-8090-888de0164c98.JPG)

Also the email textbox is not filled.
Thanks!

**Comment by peter-gabriel** [comment]
@lucaszacutti if you are using the Identity Experience Framework, your signup policy should have the oid PartnerClaimType
`<OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="oid"/>`

My policy looks like this:

`<RelyingParty>
    <DefaultUserJourney ReferenceId="SignUpOrSignIn" />
    <TechnicalProfile Id="PolicyProfile">
      <DisplayName>PolicyProfile</DisplayName>
      <Protocol Name="OpenIdConnect" />
      <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="displayName" />
        <OutputClaim ClaimTypeReferenceId="surname" />
        <OutputClaim ClaimTypeReferenceId="signInName" />
        **<OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="sub"/>
        <OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="oid"/>**
      </OutputClaims>
      **<SubjectNamingInfo ClaimType="sub" />**
    </TechnicalProfile>
  </RelyingParty>`
