### ISSUE TITLE
Improvement for the terms of use in the sign up page. 

### ISSUE THREAD

**Issue by qubaldo** [Azure/api-management-developer-portal#2041]
I'm using this ticket as a reference [#674 ](https://github.com/Azure/api-management-developer-portal/issues/674)
I'm almost 100% sure that the setting screenshot was removed from the APIM portal, I could only find this setting to enable the requirement of terms of use for a specific product.
Here: 
![image](https://user-images.githubusercontent.com/4544069/207696344-2b31c8aa-be9c-4f8b-a587-9c38ef2fd44b.png)

The only way I could find to enable the signup terms of use was through this PUT request:
https://learn.microsoft.com/en-au/rest/api/apimanagement/current-preview/sign-up-settings/create-or-update?tabs=HTTP#termsofserviceproperties

Why is it not in the APIM Settings anymore?
Was this moved somewhere else? This should be easily accessible in the APIM portal

The JSON type that you pass is not very developer friendly in case you want to format the text of the "Terms of Use" before it used to be a text area like in the subscription as it should be not just text. You can't even embed any HTML tags to make it look decent, not even a URL link. This is how it looks when you try to add the terms of use using the "text" field.
![image](https://user-images.githubusercontent.com/4544069/207699282-b930f0bf-f335-4dac-bf7d-95e06746f098.png)

Any help figuring out how to make it more presentable, I tried so many things to create new lines to embed a url link nothing seemed to work. I looked at the code and it uses  blockquote class="col-md-12" rows="10" readonly data-bind="text: `termsOfUse` in the terms-of-use.html which doesn't seem like the best HTML tag for this field either.

Thanks

**Comment by mikebudzynski** [comment]
You can enable the sign-up terms and conditions by going to the "Identities" tab in the menu and selecting "Settings".

![image](https://user-images.githubusercontent.com/40186513/208553516-035ffe23-243c-41b7-871e-e35345841936.png)

**Comment by qubaldo** [comment]
This doesn't help with the fact that it, can't be really formatted to look presentable nor can you add any links to at least point to a format version of it.
