### ISSUE TITLE
Wrong Validation Message for Sign-up & Sign -in Widget

### ISSUE THREAD

**Issue by MuhasseenaSajeed** [Azure/api-management-developer-portal#2048]
## Bug description

1.  The incorrect warning message, "First Name is required" rather than "Email is required," appears on the Sign In page after leaving the Email Id empty or blank.

2. After leaving the Last Name empty or blank, the wrong warning message— "First Name is required" rather than "Last Name is required"—appears on the Sign-Up page.

## **Reproduction steps for Bug 1**

1. Go to Developer portal
4. Click on Sign in option
5. Fill password field and make Email field empty or Blank then click sign in button
6. See the validation message

## **Expected behavior for Bug 1**

Validation message should be "Email is required"

 **Reproduction steps for Bug 2**

1. Go to Developer portal
4. Click on Sign up option
5. Fill all the fields except Last Name and make Last Name empty or blank then click sign up button
6. See the validation message

**## Expected behavior for Bug 2**

Validation message should be "Last Name is required"

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: [Google Chrome]
 

## Additional context

   **Name of Support Agent: Joey Wu**

  **Tracking ID : TrackingID#2212220030000863**

Joey had mentioned to open an issue through the GitHub for the above

Attaching the screen shots for both bugs for the reference,

<img width="632" alt="Signup" src="https://user-images.githubusercontent.com/121485274/209645502-fa2a5307-b9bd-4a5c-9c08-9d5b87490ea3.png">
<img width="920" alt="SignIn" src="https://user-images.githubusercontent.com/121485274/209645511-3c9ea526-7098-4ddb-b1b7-ee37a305180d.png">

**Comment by JMach1** [comment]
I verified and reproduced the bug, work item for a fix was created. The issue will be fix in next major release. Thank you for reporting it!
