### ISSUE TITLE
Clarification of Azure B2C Authentication

### ISSUE THREAD

**Issue by rndthoughts** [Azure/api-management-developer-portal#206]
The pricing tiers for API Management on the Azure website make it clear that Active Directory Integration is only available at the Standard tier or higher.  The recent release of #177 enables B2C authentication.

Can someone please clarify - does the new developer portal support B2C authentication regardless of payment tier or would I need to be on the Standard tier or above purely to use B2C on the portal (I dont need it on the API endpoints themselves).  I dont want to spend time enabling B2C integration on the developer tier to find when I use the Basic tier, this is removed?

**Comment by rndthoughts** [comment]
OK I've found the relevant documentation stating Basic isn't supported.  This is a bit of a blow, Amazon offer Cognito integration by default and we already use B2C integration in the rest of our solution.  Could someone shed any light on why Basic doesnt include B2C?

**Comment by mikebudzynski** [comment]
@rndthoughts - AAD integration in the developer portal is supported only in the Standard and Premium tiers of API Management: https://aka.ms/apimpricing
