### ISSUE TITLE
"Issues" feature

### ISSUE THREAD

**Issue by MohAshfaq** [Azure/api-management-developer-portal#2067]
Hi, we currently use the "issues" feature in the old developer portal. The old developer portal will be deprecated soon and there is no feature for "issues" in the new portal. Are there any plans to integrate this feature in the new developer portal? 
What are the alternatives we can use instead? We have explored custom HTML snippet feature, to create a custom form and build our own backend but it has limitations. 

Thanks,
Ashfaq

**Comment by mikebudzynski** [comment]
@MohAshfaq, we currently don't plan to provide native "Issues" functionality in the new developer portal. We recommend customers to integrate with proper issue management solutions (for example, Azure DevOps, GitHub) using custom widgets. If you're running into problems, you can contact Azure support for help.
