### ISSUE TITLE
Button visibility issue

### ISSUE THREAD

**Issue by GavinXiong2023** [Azure/api-management-developer-portal#2068]
## Bug description

When clicking 'home' button in the anonymous mode, the button for authenticated user which should only appear in authenticated mode pops up and disappears instantly.

## Reproduction steps

1.  On the home page, config one menu for anonymous user and one menu for authenticated  user
2.  Visit the developer portal in anonymous mode.
3. Click ‘Home’ button.

## Expected behavior

The buttons for authenticated user should not pop up when I browse as anonymous mode.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: [Windows 10 Enterprise]
 - Browser: [Google Chrome Version 108.0.5359.126 (Official Build) (32-bit),  Microsoft Edge Version 108.0.1462.76 (Official build) (64-bit)]

**Comment by jsorohova** [comment]
Hello @GavinXiong2023, thank you for reporting this issue. This should be fixed in the upcoming release which will be live in a few weeks. Sorry for inconvenience.

**Comment by GavinXiong2023** [comment]
@jsorohova thank you.

**Comment by azaslonov** [comment]
The fix has been deployed to all public regions.
