### ISSUE TITLE
Operation console - missing oauth token generation

### ISSUE THREAD

**Issue by KannanKalisamy** [Azure/api-management-developer-portal#207]
**Describe the bug**
After configured the oauth 2.0 server and api security has enabled to use the oauth server. but new portal operation console ( Try It ) option doesn't have the functionality to generate the access token from oauth  provider. Missing oauth token generation option in the Authorization section. However old portal has option to generate the token and its works. 

**Portal environment**
New developer portal preview

**Additional context**
Old Portal
![image](https://user-images.githubusercontent.com/16281799/66840633-b5336080-efab-11e9-8494-f20411bdfbad.png)

New Portal - Missing oauth access token  option
![image](https://user-images.githubusercontent.com/16281799/66840741-ddbb5a80-efab-11e9-98d6-ad8b588b9da6.png)

**Comment by mikebudzynski** [comment]
Thanks @KannanKalisamy for feedback! This feature is coming in a month or two.

Merging with https://github.com/Azure/api-management-developer-portal/issues/208
