### ISSUE TITLE
User Management for Dev Portal

### ISSUE THREAD

**Issue by senthilkumardhanapal2** [Azure/api-management-developer-portal#2077]
## Bug description

Not able to assign developers to custom group, it always gets assigned to Developer Group.  how do we assign developers to custom group programmatically 

## Reproduction steps

I used Graph API to create  user by having groups as custom

## Expected behavior

users should be assigned to custom group

## Is your portal managed or self-hosted?

Managed 

## API Management service name

tzfinternal

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by harunrst** [comment]
Hi @senthilkumardhanapal2 , please see api management documentation for this: 
https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/group-user/delete?tabs=HTTP
https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/group-user

**Comment by senthilkumardhanapal2** [comment]
@harunrst  while creating user itself , can we not assign to custom group ? its not working even If I send a group with custom. 

or is it a 2 step process like create user first and add it to group?

here is the body I gave 

`{   "properties":{      "firstName":"test7",      "lastName":"user7",      "email":"test7@outlook.com",      "confirmation":"signup",      "groups": [        {        "id": "test-group"      }       ]   }}`

**Comment by senthilkumardhanapal2** [comment]
@everyone any update on this one ?

**Comment by malincrist** [comment]
Hello @senthilkumardhanapal2, yes it is a 2 step process.
According to the documentation you can:
- create the user (please check the request body [section](https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/user/create-or-update?tabs=HTTP#request-body))
https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/user/create-or-update?tabs=HTTP
- assign an already existing user to an already existing group
https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/group-user/create?tabs=HTTP

Hope this clarifies your question.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
