### ISSUE TITLE
Overlapping icon in search widgets

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2078]
## Bug description

In widgets containing a Search field the magnifying glass icon is overlapping with the content of the Search field. Even when adding a search string the magnifying glass does not disappear/still covers the content.

Search field with default content:
![image](https://user-images.githubusercontent.com/58420097/215042443-eb6ce78e-c854-499e-bd71-e65b9d132a24.png)

Search field with search string:
![image](https://user-images.githubusercontent.com/58420097/215042383-27f24bce-39fa-42a9-b96c-d51afe05969b.png)

This can feel unprofessional for the user and makes working with the DevPortal more difficult.

Following widgets are affected:
- List of APIs
- List of Operations
- List of Products

## Expected behavior

- Magnifying glass icon has its own space without overlapping, or
- disappears when text is added

![image](https://user-images.githubusercontent.com/58420097/215043724-96e2cd80-dc7c-4c15-9227-49d85eca5eb5.png)
(Separating line not necessary)

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
- In our environments we do not use the full width for this widget. Meaning the Section has a limit of 1500 px and we have other elements on the side.
- Where can those configurations be made? We only use the default DevPortal widgets and style them on the style page.

I reset one of our DevPortals and tried to replicate the issue and couldn't do so as well.
Should I send the APIM name to the apimportalfeedback@microsoft.com mail?

**Comment by harunrst** [comment]
Can you try republishing the portal? There could have been an issue during the publishing. And yes you can send an email.
