### ISSUE TITLE
Issue page is missing in new developer portal which was present in deprecated portal

### ISSUE THREAD

**Issue by Mdshakeelse** [Azure/api-management-developer-portal#2079]
Issue page is missing in new developer portal which was present in deprecated portal

**Comment by mikebudzynski** [comment]
@Mdshakeelse Issues aren't supported in the new developer portal. You can find more details about the migration and differences in our documentation: https://learn.microsoft.com/en-us/azure/api-management/developer-portal-deprecated-migration
