### ISSUE TITLE
Display Menu Items based on Role

### ISSUE THREAD

**Issue by senthilkumardhanapal2** [Azure/api-management-developer-portal#2083]
Hello,

we have a requirement display menu item based on Developer Role and custom role. is there a way to check and role and display menu or content based on Role ?

**Comment by azaslonov** [comment]
@senthilkumardhanapal2, there is access control feature being rollout, it should be available in all regions by 3/10.

**Comment by azaslonov** [comment]
The feature rolled out in every region.
