### ISSUE TITLE
ARM timeout (120 sec) cannot be set

### ISSUE THREAD

**Issue by frankdewaelle** [Azure/api-management-developer-portal#2089]
Hi,

we try to create a new revisiion of an API using the web-console or via Powershell, but it times out. So the "create revision" is never successfull.

Through a support case with Micrsosoft (TrackingID#2212130040007153) we learned the timeout happens via ARM. In our case the timeout is caused by the fact the API has to many operations. The timeout cannot be set in APIM console.
If the same operation is started via the management API directly, all goes well. Usage of the management API directly is no option for us because of operational issues.

2 questions : 
- Can this ARM timeout be set (or "reconfigured")
- what is "too many operations" ? We want to se guidelines for the developpers.

**Comment by frankdewaelle** [comment]
Who on Microsoft Azure support ? I contacted Microsoft APIM support (toliveira@microsoft.com) and they sent me to you...

**Comment by frankdewaelle** [comment]
It is specific to the APIM Management Console (or however you want to  call it).
There is no ARM or management or Management API problem, the issue is that the timeout (120s) cannout be set in the console. If the ARM action takes longer then 120s there will be a timeout (whatever the action is).
We cannot use calling management API directly, because that way of working lacks all the operational benefits (specially the security granularity.

**Comment by malincrist** [comment]
@frankdewaelle, I understand the issue you are facing, however, it is not related to developer portal.

The issue you are having is related to ARM limitations and we cannot help you with this. This repository is for developer portal issues only, hence we can only help with issues related to it. For anything else, you should contact Azure Support and discuss with them.

Thank you for your understanding!

**Comment by frankdewaelle** [comment]
Hmm...  the "ARM People" say it is not an ARM problem, nieither underlaying SQL issue (they traced that too).

The thing is that after 2m the APIM interface says 'timeout', but ARM didn't timeout, it just takes a long time to process . The same issue happen when you have big deployments via ARM. The issue doesn't happen with AzureApps, because there you can spoecify the timeout (configureable), you have no option in APIM to cofigure ARM timers....

**Comment by mikebudzynski** [comment]
Replied via email - this issue is specific to PowerShell / tooling and not the developer portal.
