### ISSUE TITLE
Table Column/Row Editing Button Missing

### ISSUE THREAD

**Issue by FXZFun** [Azure/api-management-developer-portal#2092]
## Bug description

The edit button for changing the details on a table column or row do not appear when hovering over a table cell when there is content in the cell. When the cell is empty, hovering over a cell shows an edit button to adjust row height, for example. After content is placed in the cell, that button no longer appears, but if you hover over an empty cell in the same row/column the button will appear, but you cannot jump over the full cell to click it.

## Reproduction steps

1. Add a table to the portal
2. Hover over a cell and see the edit row/column buttons
3. Add a widget to the cell
4. Hover over the cell again and see that the buttons no longer appear

## Expected behavior

I would expect the edit button to show even if there is content in the cell, so that adjustments can be made after content is added.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Brave
 - Version: 147.186 Chromium 109.0.5414.119 (Official Build) (64-bit)

## Additional context

With content (hovering over the top left cell)
![image](https://user-images.githubusercontent.com/58504073/217663089-19420904-c10e-42f2-ae34-e15bf079416e.png)
Without content (hovering over the next cell down)
![Screenshot 2023-02-08 161138](https://user-images.githubusercontent.com/58504073/217663424-35e496ac-e2f0-4c39-bb73-e6369fa690cb.png)

**Comment by malincrist** [comment]
Hello @FXZFun, thanks for reaching out to us. I was able to reproduce the issue you described. I have created a work item to investigate and fix this and we will keep you updated on the progress.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
