### ISSUE TITLE
Captcha Audio is not clear in Sign up page and Password Reset page.

### ISSUE THREAD

**Issue by Srilatha-yalla** [Azure/api-management-developer-portal#2094]
## Bug description

We are trying to get the captcha using Audio, but it is not clear to hear

## Reproduction steps

1. Go to the developer portal
2. Click on Signup or Password reset page
3.  Click Audio in Captcha and listen

## Expected behavior

Captch Audio will be clear 

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: Google Chrome
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by ygrik** [comment]
This is by design to prevent recognize the speech by robots.
