### ISSUE TITLE
How does one create a page content on a template in APIM developer portal designer

### ISSUE THREAD

**Issue by Piekop** [Azure/api-management-developer-portal#2098]
Once you create a developer portal the first time, you will get the contoso home page etc...
But the contoso home page is embedded in a 'page content' layout control, which is full width.
When you delete this control to start from scratch, I'm not able to find this same type of section control.
![image](https://user-images.githubusercontent.com/215494/218401266-86cb1803-06bd-4a38-b06d-9bcca9d667cf.png)

I can't believe this is so hard to do and yet I can't find decent information concerning this portal. 
Something I would like to add is the lack of documentation concerning the new custom widget support...

Could somebody help me out?

Regards
Marc

**Comment by Piekop** [comment]
When can I receive an update on this?

**Comment by azaslonov** [comment]
@Piekop, you're right, one should be able to add the "content" part to a grid element. We'll fix this shortly.

Meanwhile, you can use drag'n'drop as a workaround: first you create anothe section of required configuration, then you drag the "page content" from its original place to new grid cell.

**Comment by ahmedsza** [comment]
I am having the same issue and just a bit confused.. If I delete the page content "widget" is there a way to get it back? @azaslonov   -there is mention of drag and drop, but I cannot find any way of getting page content back..
