### ISSUE TITLE
Broken link when opening API detail page from missing api-version query

### ISSUE THREAD

**Issue by taiyokato** [Azure/api-management-developer-portal#2099]
## Bug description

The list of operations page link is broken when trying to visit from APIs > ctrl click any API.
![image](https://user-images.githubusercontent.com/5071602/218646570-dde25c67-6155-4a0b-8093-8eef0ad27c65.png)

Investigated by checking HAR log, found the request URL did not include any api-version query.
```
https://{apim}.management.azure-api.net/subscriptions/000/resourceGroups/000/providers/Microsoft.ApiManagement/service/{apim}/contentTypes/page/contentItems?$skip=0&$top=50&$filter=en_us/permalink%20eq%20%27/api-details
```

Which caused this response.
```
{"error":{"code":"MissingOrIncorrectVersionParameter","message":"API version query parameter is not specified or was specified incorrectly.  Supported versions: 2014-02-14-preview,2014-02-14,2015-09-15,2016-07-07,2016-10-10,2017-03-01,2018-01-01,2018-06-01-preview,2019-01-01,2019-12-01-preview,2019-12-01,2020-06-01-preview,2020-12-01,2021-01-01-preview,2021-04-01-preview,2021-08-01,2021-12-01-preview,2022-04-01-preview,2022-08-01,2022-09-01-preview  Example query param format: api-version=SupportedVersion","details":null}}
```
And therefore showing the "Oops" error 

## Reproduction steps

1. Go to APIs page in edit mode
2. Ctrl+Click on any API
3. See error "Oops, something went wrong"

## Expected behavior

List of operations page for the selected API should be shown.
```
https://{apim}.developer.azure-api.net/api-details#api=echo-api
```

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

From `https://{apim}.developer.azure-api.net/internal-status-0123456789abcdef`: 
```
{"Status":200,"PortalVersion":"20220922183234","CodeVersion":"20230125015725","Version":"0.33.13849.0","RoleNumber":"gwhost_1"}
```

## API Management service name

apimtakat0210/apimtakat1125

## Environment

 - Operating system: Win 11
 - Browser: Edge/Chrome
 - Version: Version 110.0.1587.41 (Official build) (64-bit) / Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by malincrist** [comment]
Hello @taiyokato, thank you for reaching out to us. This issue was fixed and will be shipped with the next Developer Portal release, which should be in about 2-3 weeks. Apologies for the inconveniences.

**Comment by azaslonov** [comment]
The fix has been deployed to all public regions.
