### ISSUE TITLE
subscriptions not showing after 100+ user subscriptions

### ISSUE THREAD

**Issue by Hilda-S** [Azure/api-management-developer-portal#2100]
**Bug description**

User's my subscriptions page can only display a maximum of 100 subscriptions. When from the APIM, there are more than 100. 

## Reproduction steps

1. Login the developer portal with a specific User's email address and passwords
2. Navigate to My Subscriptions
3. There are only 100 subscriptions showing in the list but we have 104 in total

4. We captured the HAR file when loading the page and found the below content in the response payload:

  "count": 104,
  "nextLink": "https://{apim-custom domain for management endpoint}.nz:443/subscriptions/000/resourceGroups/000/providers/Microsoft.ApiManagement/service/{APIM service name}/users/{user subscriptions}/subscriptions?api-version=2021-04-01-preview&%24skip=100"
}

There is no next-page button in the developer portal that can be used to load the rest of the subscriptions. 

## Expected behavior

Show all 104 user subscriptions in the Azure Developer portal

## Is your portal managed or self-hosted?

Managed 

## Additional context

N/A

**Comment by malincrist** [comment]
Hello @Hilda-S, I was able to reproduce the issue you described. I created a work item to fix this and we will keep you updated on the progress.
