### ISSUE TITLE
Size setting of video player widget is not working

### ISSUE THREAD

**Issue by simpleman2005** [Azure/api-management-developer-portal#2106]
## Bug description

In developer portal admin mode, the width and height setting of video player widget is not working.
It was working about one month ago.

## Reproduction steps

1. Open developer portal in admin mode,
2. Select one page, for example "Sign in" page, 
3. In that page, add a video player widget.
4. Click the video player, select a source media, the video player in the page will display the video in full size, no matter what's the width and height been configured.

## Expected behavior

The size of the video player window in that page should reflect the width and height setting.

## Is your portal managed or self-hosted?

Managed

## API Management service name

apimdev0809

## Environment

 - Operating system: Windows 11
 - Browser: Edge, Chrome.
 - Version: Edge Version 110.0.1587.49 (Official build) (64-bit), Chrome Version 110.0.5481.104 (Official Build) (64-bit)

## Additional context

![image](https://user-images.githubusercontent.com/9067213/219573421-6fb24bf4-cd60-4693-8ac2-86014aa0ae07.png)

**Comment by JMach1** [comment]
Hi @simpleman2005, 
I was able to reproduce the issue, thank you for reporting the bug. 
We'll fix it ASAP and release it soon. ETA 4 weeks.

**Comment by azaslonov** [comment]
Fixed in #2111. Managed portals deployment is pending.
