### ISSUE TITLE
Getting openidConnectProviders fails with backendUrl set

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#2110]
## Bug description

Getting `https://mycustom-dev-endpoint-dns/openidConnectProviders/myprovider` fails when trying to fetch from self-hosted portal, navigating to an API which has the provider linked. Hosted at `https://mycustom-portal-endpoint-dns` (not actually the dns name, but just for discussion). It returns `ERR_CONNECTION_CLOSED`.

## Reproduction steps

`backendUrl` is configured as `https://mycustom-dev-endpoint-dns`. 

I've configured `https://mycustom-dev-endpoint-dns` under `Self-hosted portal configuration`. And it's configured under `Custom domains` as Developer Portal Endpoint.

Because the API Management instance is hosted as `Internal`, our Application gateway is routing  `https://mycustom-dev-endpoint-dns` to the private VIP of our API Management instance, with the hostname to be rewritten to `https://mycustom-dev-endpoint-dns`.

## Expected behavior

Should just work?...

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.22.0

## API Management service name

m006apia0001

## Environment

Latest

**Comment by JMach1** [comment]
Hi @erwinkramer please contact Azure Support for assistance with your problem.
