### ISSUE TITLE
Capture/Generate scripts does not work when behind a proxy

### ISSUE THREAD

**Issue by tommyisaksson** [Azure/api-management-developer-portal#2116]
## Bug description

When behind a proxy, it is not possible to capture/generate the Developer Portal. The node.js scripts does not respect the proxy-settings and goes directly to the Azure-URL which causes a timeout.

## Reproduction steps

1. Add proxy settings to environment variables HTTP_PROXY and HTTPS_PROXY
2. Adjust capture.bat with the API Management details
3. Run capture.bat from behind a proxy
4. Timeout error

Error message:
Unable to complete export. Unable to capture content. Unable to fetch content types. connect ETIMEDOUT 51.12.44.111:443

If I use Wireshark to look at the traffic, the scripts are sending traffic directly to 51.12.44.111 instead of using the proxy I have configured in HTTP_PROXY

I looked a little at your code, and I can fix the problem by adding for example node.js global-agent to utils.js as below:
const { bootstrap: bootstrapGlobalAgent } = require('global-agent');
bootstrapGlobalAgent(); (from within utils.js constructor)

Add proxy to environment variables GLOBAL_AGENT_HTTP_PROXY GLOBAL_AGENT_HTTPS_PROXY GLOBAL_AGENT_NO_PROXY

With the above additions, the capture/generate works fine behind our proxy. But maybe you prefer some other fix for adding proxy support to utils.js

## Expected behavior

Developer-portal is captured/generated

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-apii-dv-weu-002

## Environment

 - Operating system: Windows Powershell 7

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
