### ISSUE TITLE
[Feature request] Make pages publicly available

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2117]
## Feature request

With the new user group access control that has been implemented, will it be possible to make pages other than sign-in and sign-up publicly available?

For example, a "About" page should give possible partners more information about the DevPortal, even before signing up, to make a better informed decision.
Shouldn't it be possible to flag an additional page as public to provide this additional information?

Or is there a current workaround to provide this for the users?

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
@ZarTrox, you're asking this in the light of "require sign-in" setting, right?

**Comment by ZarTrox** [comment]
Do you mean with "require sign in" whether we have configured an Identity provider or is there a different setting you talk about? We have our AAD configured.

**Comment by azaslonov** [comment]
I meant this particular setting:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/2320302/221257047-89eeea6b-1ebc-4b95-922b-7d31b4c5c224.png">

If you don't use this option, even now you should be able to assign the "Guest" role to your "About" page (and all others that you need to make publicly available).

If you do use this option, and still want anonymous users to access "About" page, this scenario is not supported at the moment.

**Comment by ZarTrox** [comment]
Thank you for the proposal, unfortunately this does not provide the solution to out use case.
Is the feature to allow anonymous users to access a page planned? And if so, is there an eta?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
