### ISSUE TITLE
[Feature request] Show tag operations by default

### ISSUE THREAD

**Issue by ilahu** [Azure/api-management-developer-portal#2119]
Tag operations are now hidden by default after the previous release (https://github.com/Azure/api-management-developer-portal/pull/2003).

This is useful when having a long list of tags but it looks confusing if an API have only one or two tags.

Is it possible to add an option to the "List of operations" widget to change the default behaviour to expand all tag sections by default?

Before:
<img width="450" alt="Screenshot 2023-02-27 at 14 58 17" src="https://user-images.githubusercontent.com/22715685/221570013-642f0a6a-1c7b-430f-a521-4a913438314e.png">

Now:
<img width="451" alt="Screenshot 2023-02-27 at 14 58 26" src="https://user-images.githubusercontent.com/22715685/221570053-800bce1f-7d12-4e8e-a6ca-657e0ef00889.png">

**Comment by fabian-schwarz** [comment]
I can only support that, see TrackingID#2302220050001086, at least give an option to have the old behaviour back.

**Comment by Hekku2** [comment]
This is also problem in our use case.

**Comment by jan-mrm** [comment]
would really appreciate this 🙂
