### ISSUE TITLE
Is it possible to display the name of logged-in user on menu in managed portal?

### ISSUE THREAD

**Issue by Mdshakeelse** [Azure/api-management-developer-portal#2124]
Is it possible to display the name of logged in menu in managed portal?

**Comment by Mdshakeelse** [comment]
any updates on this issue

**Comment by jsorohova** [comment]
Hello, @Mdshakeelse, sorry for the late response. No, we currently don't have an opportunity to display username in the menu. For now, we can mark it as a feature request and add it to our backlog.
