### ISSUE TITLE
Sending GET requests with a body from APIM developer portal fails and a CORS error is erroneously displayed.

### ISSUE THREAD

**Issue by VadirajCJ-01** [Azure/api-management-developer-portal#2134]
## Bug Description:

Unable to send GET requests that have a body from the developer portal, we get a CORS error.

![image](https://user-images.githubusercontent.com/75964678/225537260-94b5855d-28da-4f3b-9fb7-0dbd231961b0.png)

I understand that a GET requests aren't supposed to have the body - but perhaps it could be helpful to handle this better - send the request sans body or throw a correct error message.

## Reproduction steps

Reproducing this typically requires a spec file which contains a GET request with a body. However, I was able to reproduce using a publicly available API like so - 

1) Add DemoConferenceAPI using open-api spec file

https://conferenceapi.azurewebsites.net/?format=json 

![image](https://user-images.githubusercontent.com/75964678/225541136-be60941d-54c0-4876-a2f2-8763f0a07568.png)

2)  Edit the schema and change SubmitSession operation from 'post' to 'get' and save.

![image](https://user-images.githubusercontent.com/75964678/225542226-63ca24de-3c43-415f-a094-74d2d4d5ef33.png)

3) Browse to developer portal -> APIs and test the SubmitSession operation on DemoConferenceAPI 

![image](https://user-images.githubusercontent.com/75964678/225614678-ad790891-2650-42d5-978e-ee44f6d1af29.png)

4) we see a CORS error. However, looking at the .har trace reveals that request was not sent at all.

Cors error:
![image](https://user-images.githubusercontent.com/75964678/225615437-772de340-6189-40fd-a64c-e24108321e32.png)

Only see a trace request logged in har trace, actual GET request is not sent at all:

![image](https://user-images.githubusercontent.com/75964678/225615814-c81df741-072f-4fc5-ac49-77e8ee5da126.png)

As the request hasn't reached APIM, it couldn't have been a genuine CORS error.

5) Navigate to developer tools -> Sources -> Breakpoints and select "Pause on caught exceptions"

![image](https://user-images.githubusercontent.com/75964678/225616832-18ba18eb-d51b-4bd8-bdbb-7d736463c93a.png)

6) Send the request again. This time, we see the actual exception with the call stack:

![image](https://user-images.githubusercontent.com/75964678/225617538-b8f2f4d6-c79b-472e-ba8d-58fe29125423.png)

## Expected behaviour

- Browser displays the correct exception message 
- CORS error creates a lot of confusion; it would be helpful to handle the type-error better - like if portal ignored the body instead of rejecting the request altogether.

## Is your portal managed or self-hosted?

Managed

## API Management service name

TechConcDemo 

## Environment

 - Operating system: Windows
 - Browser: Chrome
 - Version: 111.0.5563.65

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by harunrst** [comment]
Hi @VadirajCJ-01 , thanks for reaching out. I agree with the misleading exception message, we will fix it ☺

**Comment by VadirajCJ-01** [comment]
Hi @harunrst thanks for the update! is it possible to give an ETA for this?
