### ISSUE TITLE
Try It - Trailing slashes omitted when empty string provided for wildcard parameter

### ISSUE THREAD

**Issue by simonhi-dc** [Azure/api-management-developer-portal#2136]
## Bug description

Try It - Trailing slashes omitted when empty string provided for wildcard parameter resulting in APIM matching the request to an unexpected operation, or not matching an operation at all.

## Reproduction steps

1. View an API with an operation containing a wildcard parameter as its final path segment - e.g. /foo/*
2. Select the wildcard operation
3. Click on the 'Try it' button
4. Enter necessary values (including subscription key, if required) but leave the wildcard parameter blank
5. Click on the 'Send' button

## Expected behavior

The portal sends a request to the selected API/operation, including the trailing slash - e.g. https://.../foo/

Actual: the portal omits the trailing slash in the request that it sends - e.g. https://.../foo

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

N/A

## Environment

 - Operating system: Windows 10/11
 - Browser: Microsoft Edge
 - Version: 111.0.1661.44

## Additional context

Examples:
<img width="433" alt="foo" src="https://user-images.githubusercontent.com/69773222/226519884-b4cb3b26-a66b-425c-b414-e14a954c7d8c.png">
<img width="431" alt="foobar" src="https://user-images.githubusercontent.com/69773222/226519967-6394797b-da85-41bd-b6e5-dd966578eb66.png">

When sending requests manually (e.g. via curl) with a trailing slash, APIM behaves as expected.
e.g.
`curl -H 'Ocp-Apim-Subscription-Key: xxx' https://xxx/wildcardportaltest/foo/
{"operation":"foo","paramVal":""}`
`curl -H 'Ocp-Apim-Subscription-Key: xxx' https://xxx/wildcardportaltest/foo/bar/
{"operation":"foobar","paramVal":""}`

I suspect that the current behaviour may relate to [this change](https://github.com/Azure/api-management-developer-portal/pull/1793/files). Looking at the change, I identified some other slightly strange behaviour: if a value beginning with an asterisk (*) is given for the wildcard parameter, the slash and asterisk are both omitted.
e.g.
![image](https://user-images.githubusercontent.com/69773222/226521899-60a547a1-f6eb-4c1c-b321-b3a9c9b7e091.png)

**Comment by harunrst** [comment]
Hey @simonhi-dc , you are right there is an issue here. We will fix it :) thanks for pointing that out.
