### ISSUE TITLE
OAuth 2.0 - authorization implicit does not work because of 'response_type=id_token'

### ISSUE THREAD

**Issue by ammix** [Azure/api-management-developer-portal#2139]
## Bug description

Preconditions:
1. There is API provider that requires access token (Bearer token, not id_token) to authorize access to its API
2. On Azure portal/APIM service/OAuth 2.0 + OpenID Connect, OAuth 2.0 service for implicit flow is added with scope 'openid user.read'
3. On Azure portal/APIM service/APIs/Settings/Security, OAuth 2.0 user authorization is selected

On developer portal (APIs tab, 'Try it' button) when trying to authorize using 'implicit', developer portal sends the request with 'response_type=id_token'. But my API provider expects 'response_type=id_token token', so authorization fails always with 401 error.

## Possible solution

Looks like the problem is here: file oauthService.ts, line 109
```
if (authorizationServer.scopes.includes("openid")) {
	query["nonce"] = Utils.guid();
	query["response_type"] = "id_token";
}
```
And following code can fix my problem, I guess:
```
if (authorizationServer.scopes.includes("openid")) {
	query["nonce"] = Utils.guid();
	if (authorizationServer.scopes.length == 1)
		query["response_type"] = "id_token";
	else
		query["response_type"] = "id_token token";
}
```

## Expected behavior

According to [this](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow)

> If you use the token response_type, the scope parameter must contain a scope indicating which resource to issue the token for (for example, user.read on Microsoft Graph).

Thus, I do reverse assumption: if scope contains something except 'openid' then response_type should be 'id_token token' (not id_token).

## Is your portal managed or self-hosted?

Managed

## API Management service name

twf-test-apimgmt

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome, Firefox

**Comment by javierbo1989** [comment]
Hi Maxim, I have created a work item to investigate this, we will keep you posted. Thanks!

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
