### ISSUE TITLE
Is it possible to let developers self-subscribe themselves to an API?

### ISSUE THREAD

**Issue by Piekop** [Azure/api-management-developer-portal#2144]
Currently we only see the possibility to self-service developers with products from the developer portal.
Is there a possibility to do this for a single API?

Regards

**Comment by ygrik** [comment]
Hi @Piekop 
I think you can make public a single API and make it available in managed developer portal.

**Comment by Piekop** [comment]
@ygrik : thank you for your feedback, but I don't think so. 
Could somebody look into this?
Thanks

**Comment by Piekop** [comment]
Any news yet? Our customer is waiting for an answer.

**Comment by Piekop** [comment]
Hello? Anybody?

**Comment by Piekop** [comment]
Hello? @ms-anand  somebody?

**Comment by Piekop** [comment]
This is getting ridiculous. If this isn't supported, just say so?! 
Why does it take that long to answer? It's like it doesn't cost enough already?! 
Could you kindly answer the question?

**Comment by malincrist** [comment]
Hello @Piekop, apologies for the late response. Unfortunately, it is not possible to subscribe to an API from the developer portal.
This was also discussed in #659
