### ISSUE TITLE
String converted to date during import of OpenApi 3.x API into APIM

### ISSUE THREAD

**Issue by jadzdtc** [Azure/api-management-developer-portal#2149]
## Bug description

Importing OpenApi 3.x API definition, does not preserve original values for request bodies examples. Strings like '4.11', '5.4' are converted into dates '2023-11-04', '2023-04-05' respectively.

Notes:
- during import of OpenApi 2.x conversion does not occur.
- issue is reproducible regardles of format, it occurs for both JSON and YAML
- exporting to OpenApi 3.x JSON/YAML also modifies strings, but exporting to OpenApi 2.x or WADL does not

## Reproduction steps
1. Open APIM in Azure portal. Open APIs blade and create API by importing OpenApi 3.x document (click "Add API" button, then click on OpenAPI in 'Create from definition' section)
![image](https://user-images.githubusercontent.com/65334140/230073557-719e12e2-06ca-4651-a92a-2d76348b1edf.png)
2. Import one of following examples
#### YAML
```yaml
openapi: 3.0.1
info:
  title: test
  version: test
paths:
  /api/test:
    post:
      operationId: test
      requestBody:
        content:
          application/json:
            example:
              stringConvertsToDateDuringImport: '4.5'
      responses:
        '200':
          description: OK
```
#### JSON
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "test",
    "version": "test"
  },
  "paths": {
    "/api/test": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "stringConvertsToDateDuringImport": "4.5",
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```
3. Observe that example body for request has converted value `4.5` into date:
```json
{ 
  "stringConvertsToDateDuringImport":"2023-04-05"
}
```
![image](https://user-images.githubusercontent.com/65334140/230074694-0a3fb234-12b2-4504-9b66-529479527f0b.png)

**Comment by ygrik** [comment]
Hi @jadzdtc 
This issue does not relate to the developer portal.
Please submit ticket to Azure APIM service.

**Comment by Meertman** [comment]
Added an idea to the APIM forum as recommended in the support ticket by Microsoft in order to be able to follow up on the status of this issue.
You can find the idea here: https://feedback.azure.com/d365community/idea/678a9f4b-304b-ef11-b4ad-000d3ae688a1
