### ISSUE TITLE
Managed portal favicon not loading

### ISSUE THREAD

**Issue by rsch136** [Azure/api-management-developer-portal#2153]
## Bug description

Similar to https://github.com/Azure/api-management-developer-portal/issues/915, the favicon is no longer being loaded. It does not show up in the network tab of the developer tools at all. While I am getting some error messages (CORS error for two of six fonts) none seem to have to do with the favicon.

## Reproduction steps

1. Set up favicon
![image](https://user-images.githubusercontent.com/44471683/231446239-6e8bb21d-3cac-4b63-bd83-8848fb63f70a.png)
2. Save and publish portal
3. Open portal in incognito tab
4. Favicon is missing
![image](https://user-images.githubusercontent.com/44471683/231446948-246b21bd-e879-498f-8cf4-41feb6715688.png)

## Expected behavior

Would expect the favicon to show up or alternatively, see an error loading the favicon in the developer tools.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

CodeVersion: 20230316165316
PortalVersion: 20230315132530

## API Management service name

evk-apim-dev, evk-apim-qa, evk-apim-prod

## Environment

 - Operating system: Windows 11
 - Browser: Google Chrome
 - Version: 112.0.5615.50

**Comment by murilo-sps** [comment]
Is there any update on this issue? I am facing the same problem.

**Comment by mrcarlosdev** [comment]
Hi @rsch136 and @murilo-sps, many thanks for opening this bug. I have been testing this behaviour and it looks like it is working properly for me, could you please try again? Please have in mind that this change is not instant and may take a few minutes until the Developer Portal is completely published after the changes.

**Comment by murilo-sps** [comment]
Hi @mrcarlosdev,
I can confirm that it is working for me now. It actually started working again a few weeks ago.
Thanks for checking.

**Comment by rsch136** [comment]
It is now also working for me. Possibly the version was rolled out to my tenant later?
Thanks for fixing it.
