### ISSUE TITLE
ChangeProfile Delegation Operation Provides Incorrect Signature

### ISSUE THREAD

**Issue by lsuarez5280** [Azure/api-management-developer-portal#2155]
## Bug description

Signature for the ChangeProfile delegation operation should be a result of `HMAC(salt + '\n' + userId)` as indicated in the response on #1138. 

The current signature value of the ChangeProfile delegation operation is `HMAC(salt)`.

## Reproduction steps

1. Configure any delegation endpoint for developer portal in Azure.
2. Sign-in to a Basic user account.
3. Navigate to the profile page.
4. Click the Change Name button.
5. Observe the signature query string value in the address bar.
6. Validate that the signature is calculated by hashing only the salt query string value, such as `HMAC(salt)`, or at a minimum, does not meet the expectation of `HMAC(salt + '\n' + userId)`.

## Expected behavior

The signature should be the result of  `HMAC(salt + '\n' + userId)`  as with most other delegation operations containing the user ID.

## Is your portal managed or self-hosted?

Managed

## API Management service name

Please contact me directly for this information if required.

## Environment

 - Operating system: Windows
 - Browser: Edge
 - Version: 112.0.1722.39 (64-bit)

## Additional context

As an aside, I shouldn't have to search issues on this GitHub to find the hashing function used with these delegation operations. The hash used with user operations is not mentioned once in [the documentation for this feature](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-setup-delegation#-delegating-developer-sign-in-and-sign-up).

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
