### ISSUE TITLE
Failure to add pictures to content.

### ISSUE THREAD

**Issue by rndthoughts** [Azure/api-management-developer-portal#216]
**Describe the bug**
I am no longer able to add pictures to pages.

**To Reproduce**
1. Open the new developer portal from the azure portal.
2. Navigate to a page.
3. Add a new section.
4. Add a "picture" element.
5. Select the picture in the toolbox.
6. Receive an error message (Oops, something went wrong).

**Expected behavior**
A picture is added to the current section.

**Portal environment**
Managed

**API Management service name**
upedge

**Environment**
 - Operating system: Windows 10
 - Browser: Google Chrome

**Additional context**

Debug console displays:

```
Uncaught TypeError: Cannot read property 'key' of undefined
    at PictureEditor.applyChanges (paperbits.js:1)
    at PictureEditor.onMediaSelected (paperbits.js:1)
    at MediaSelector.selectMedia (paperbits.js:1)
    at HTMLAnchorElement.<anonymous> (paperbits.js:1)
```
Network tab has a number of content loading errors:

```
<Error>
<Code>
AuthenticationFailed
</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0a560857-201e-00fe-1cbf-85d2d2000000
Time:2019-10-18T14:22:30.9122967Z
</Message>
<AuthenticationErrorDetail>
Signature not valid in the specified time frame: Start [Wed, 16 Oct 2019 10:27:58 GMT] - Expiry [Thu, 17 Oct 2019 10:32:58 GMT] - Current [Fri, 18 Oct 2019 14:22:30 GMT]
</AuthenticationErrorDetail>
</Error>
```
This happens every time regardless of how long I wait before uploading a picture.

**Comment by mikebudzynski** [comment]
I'm closing the issue due to its inactivity. Please, let us know if the problem persists.

**Comment by RobBowman** [comment]
I have the same problem:

paperbits.js:2 Uncaught (in promise) Error: Unable to upload blob 52ae9a05-1f20-993a-620b-f1066fd80a47. Error: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4abd5743-f01e-0057-0f46-6e533b000000
Time:2021-07-01T06:58:05.1538272Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Tue, 22 Jun 2021 14:01:08 GMT] - Expiry [Wed, 23 Jun 2021 13:06:08 GMT] - Current [Thu, 01 Jul 2021 06:58:05 GMT]</AuthenticationErrorDetail></Error>
    at new RestError (paperbits.js:2)
    at paperbits.js:2
    at exports.AzureBlobStorage.<anonymous> (paperbits.js:2)
    at Generator.throw (<anonymous>)
    at rejected (paperbits.js:2)

**Comment by mikebudzynski** [comment]
@RobBowman, could you please open another issue with precise reproduction steps? We try to avoid reviving old issues due to the confusion it causes.
