### ISSUE TITLE
URL in API documentation reflects the portal domain, not the gateway domain

### ISSUE THREAD

**Issue by tvanfosson** [Azure/api-management-developer-portal#217]
In the new portal, when displaying a resource within the API the URL shown for the request uses the hostname for the developer portal not the hostname for the API gateway. For example, using a self-hosted custom domain named portal.contoso.com with an API gateway at api.constoso.com, the documented URL for a customer API method that returns the current customer's profile would read:

`https://portal.contoso.com/customer/profile`

instead of

`https://api.contoso.com/customer/profile`

**To Reproduce**
1. Go to the new developer portal - self-hosted or otherwise.
2. Navigate to an API resource
3. Observe that on the Request tab, the URL shown next to the HTTP verb lozenge uses the portal's hostname.
4. Click the Try It button for the resource
5. In the Try It panel, scroll down to the HTTP Request section.
6. Observe that the actual URL that will be used for the request uses the API gateway hostname.

**Expected behavior**
The documentation should reflect the hostname that the developer should actually use, not the hostname of the developer portal.

**Portal environment**
This is true on both managed and self-hosted environments.

**API Management service name**
Can be provided upon request. We're currently not available for public viewing.

**Environment**
 - Operating system: N/A
 - Browser: N/A
 - Version: N/A

**Additional Context**
When using a custom domain for the API gateway, the Try It URL doesn't reflect the custom domain even when it is selected as the default SSL binding. I'll be submitting this as a separate issue.

**Comment by mikebudzynski** [comment]
Will be closed with #186
