### ISSUE TITLE
"List of APIs (dropdown)" widget settings issues

### ISSUE THREAD

**Issue by ravindrapcshs** [Azure/api-management-developer-portal#2170]
We observed few bugs and issues in "List of APIs (dropdown)" widget settings in developer portal

![MicrosoftTeams-image](https://user-images.githubusercontent.com/127383680/236170589-45758e1d-8b31-45a7-af0a-1e7b3c9ff690.png)

## Bug description
Observed bugs are listed as below:

1. "Default Group by tag to enabled" unselected still shows tags in "Quicklinks: All APIs" result list.
2. Tags in the "Quicklinks: All APIs" result list are not collapsible on click on it.
3. All display names of the listed API versions in "Quicklinks: All APIs" should be sorted in an alphabetical order (same behavior as in the API gallery).

![image](https://user-images.githubusercontent.com/127383680/236173096-94446850-5b51-42e2-ae7d-19e1eb1657bc.png)

## Reproduction steps

1. Go to 'API details' page
2. Click on 'Quicklinks: All APIs' dropdown
3. See error

<img width="943" alt="image" src="https://user-images.githubusercontent.com/127383680/236173711-9450a542-bb3a-48aa-bfb2-3c57f606c06c.png">

## Expected behavior

We expected,
1. "Default Group by tag to enabled" option should work on "List of APIs (dropdown)" widget settings selection.
2. Tags in the "Quicklinks: All APIs" result list are collapsible and expandable on click on it. If possible add "Group by tag" beside quicklinks search.
![image](https://user-images.githubusercontent.com/127383680/236175479-ded64589-fa0e-4e34-8c4a-3e300eaf3e2a.png)

4.  All display names of the listed API versions in "Quicklinks: All APIs" should be sorted in an alphabetical order.

## Is your portal managed or self-hosted?

Managed

**Comment by ravindrapcshs** [comment]
Hi Team, Do you have any updates on this reported issue or bug?

**Comment by AnRei123** [comment]
Hi, I would be also interested when this issue can be fixed to allow a consistent user experience across the different parts of the DevPortal and to allow quickly switching between API versions with a dedicated tag from the API details page. Many thanks in advance for your help to fix the issue as soon as possible.
