### ISSUE TITLE
DevPortal - API permission/display issue

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#2173]
## Bug description

In the list of API products, I cannot see a dedicated API product XYZ. But in the list of API versions, I can see the associated API versions of the product XYZ. On the API details page, I cannot see the parent API product in the related web widgets. The list of parent API product for product XYZ is empty.

Remarks:
- A view weeks ago, I was able to see the API product XYZ and the associated API versions. Might be that my permissions have been changed since that time - not 100% sure. But the observed behavior is weird and incorrect irrespective if I do have the right permissions for the API product or not.
- The listed API versions that are bundled in product XYZ are not bundled in any other API product.
- I do not have any subscriptions for this API product.
- Previously subscriptions for this API product where required, but some weeks ago, the product settings have been changed and no subscription is required any longer.
- Another two colleagues are not facing the issue, - they see both, the API product and the API versions.
- Another colleague I asked has the same issue than me. He only sees the API versions, but not the parent API product - neither in the  list of API products nor in the parent API list widget.
- The DEV of the product XYZ told me that a few weeks ago another API consumer reported a similar issues and he would also like to understand the root cause. 

## Expected behavior

1) If I do have permissions to see the product XYZ, the associated API versions are displayed in the API gallery and the product name XYZ is also displayed in the list of API products.

2) If I do NOT have permissions to see the product XYZ, the associated API versions are NOT displayed in the API gallery and the product XYZ is also NOT displayed in the list of API products.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: [e.g., iOS]
 - Browser: Chrome, Firefox
 - Version: [e.g., 22]

## Additional context

- I already restarted my computer and cleared the browser cache

**Comment by malincrist** [comment]
Hello @AnRei123, I am not able to reproduce the issue you described. Could you please share your instance name and the products and users that are experiencing the issue, by e-mail to apimportalfeedback@microsoft.com so we can investigate this further?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
