### ISSUE TITLE
Allow delete Page Content on Home Layout

### ISSUE THREAD

**Issue by AlexTukalskiy-CRL** [Azure/api-management-developer-portal#2177]
'Home' layout is not deletable. 'Permalink Template' for 'Home' layout is not editable also, 
When you mistakally delete 'Page Content' control from 'Home' layout you can't add this back. Because Add Section / Add Widget has not allow to add Page Content. 

In this case Home page is broken and there is no way to fix this.

## Reproduction steps

1. Go to Layouts
2. Select Home layout
3. Click on Page Content
4. Click on Delete
![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/eaeb9805-c401-4d5d-bad1-15cee047fec6)
 icon
5. After that You can't 

- add Page Content to the lauout 
- delete Home layout 
- change Permalink Template to use another layout

**Comment by malincrist** [comment]
Hello @AlexTukalskiy-CRL, thank you for reporting the issue. We have already fixed this, and the fix is available in the latest GitHub release.
