### ISSUE TITLE
Try It URL in new portal does not reflect a custom domain even when selected as the default SSL binding

### ISSUE THREAD

**Issue by tvanfosson** [Azure/api-management-developer-portal#218]
In the Try It section for an API resource in the new portal, the hostname used in the URL is the default name of the API gateway endpoint regardless of whether a custom domain is set as the default SSL binding for the API Management service.  This is true both for self-hosted and managed portals.

**To Reproduce**
1. Set up a custom domain for the API gateway
2. Make the SSL binding for the custom domain the default binding for the service
3. Go to the new developer portal
4. Navigate to an API resource
5. Click the Try It button
6. Scroll down to the HTTP Request section in the Try It panel
7. Observe that the URL for the resource has the default hostname for the API gateway, not the selected custom domain.

**Expected behavior**
The hostname for the default SSL binding should be used as the hostname for API resources. At a minimum, in self-hosted environments, it should be possible to specify what hostname for API gateway URLs should be used.

**Portal environment**
Both Managed and Self-hosted

**API Management service name**
Can be provided upon request. We are not currently available for public viewing.

**Environment**
 - Operating system: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
See also Issue #217.

**Comment by mikebudzynski** [comment]
Will be closed with #186

**Comment by eflavio** [comment]
Hello. I still have the same issue. I can not select which host name should be used in the api console.
