### ISSUE TITLE
Custom fonts and icons stopped working with newest release

### ISSUE THREAD

**Issue by akismolander** [Azure/api-management-developer-portal#2183]
## Bug description

We had developer portal configured with custom fonts and icon and it has worked earlier. Last successful developer portal publish was 11.5.2023 and next publish is made today and custom fonts and icons are not working anymore. There shouldn't be any changes other than new publish. 

We actually found out this when trying to make new environment and didn't manage to make fonts and icon working and tested in dev environment and found out it doesn't work there either.

## Reproduction steps

1. Configure custom font or icon to portal 
2. Publish new version of portal
3. Check with browser developer tools the errors those items are generating

## Expected behavior

Custom fonts and icons working earlier should work with new publish too.

## Is your portal managed or self-hosted?

Managed

## Additional context

Screenshots from browser developer tools showing differences between working and not working versions.

Earlier version which was working
![image](https://github.com/Azure/api-management-developer-portal/assets/38135678/5cefeefb-afb3-40e1-922d-e8c2ab8a1621)

New version that is not working
![image](https://github.com/Azure/api-management-developer-portal/assets/38135678/92392d31-e9b4-4c70-810d-cef936700caf)

**Comment by harunrst** [comment]
hey @akismolander , it is not reproducible at my side. It could be your service specific issue, could you please provide us with your service information through this email so that we can investigate it better: [apimportalfeedback@microsoft.com](mailto:from:apimportalfeedback@microsoft.com)

**Comment by ygrik** [comment]
the fix was deployed.

**Comment by LoWingKanKBQuest** [comment]
I am currently facing the same problem, need support for the issue
