### ISSUE TITLE
Adding images to API description not working anymore

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2187]
## Bug description

Before this issue occurred we used images that were defined in the API definition/description in the Azure Portal. 
It was working as expected, but since recently the DevPortal is not displaying the images anymore.

Using these images is necessary to highlight e.g. deprecation notes etc.
We tested if our links/images are broken but it seems like the DevPortal is removing the HTML image tag.

It has been made clear that custom styling through css files or other custom html snippets are not desired behavior, yet we could not find an adequate solution as of now to replace this or even a release note mentioning it.

Is there a replacement in sight? Are there any steps we can take to enable images in the API description again?

## Reproduction steps

1. Go to 'APIs' in the Azure Portal
2. Update your Open API specification by adding  an <img> to your description
3. See that the image or tag does not appear in the DevPortal API description

## Is your portal managed or self-hosted?

Managed

**Comment by jsorohova** [comment]
Hello @ZarTrox, I can see the issue. I will investigate it closer. Thank you for reporting.

**Comment by ZarTrox** [comment]
Hi @jsorohova , Unfortunately after checking and publishing our portals the images in API descriptions are not showing. 
The img src value we use is correct, however it is not showing. Usually, after this time all services are rolled out with the newest release. Are there known limitations, or is it some kind of bug again?

**Comment by jsorohova** [comment]
Hello @ZarTrox , I am very sorry for any inconvenience but my changes didn't make it to the last rolled out release (I added the fix when the release was already prepared) but they will make it to the next one which we are currently preparing.  We are apologizing for the delays. Best regards.
