### ISSUE TITLE
Parent navigation link not working in Navigation menu

### ISSUE THREAD

**Issue by iAP24** [Azure/api-management-developer-portal#2196]
## Bug description

In the navigation menu, when are in the child navigation page and when browsing back to parent navigation item, the link becomes unclickable.

For example, 

![image](https://github.com/Azure/api-management-developer-portal/assets/112155539/cdb5f657-16ba-4131-ab05-293f99299ccc)

In the above, when your currently in child navigation page and when clicking the parent navigation item, the portal doesn't respond anything and link becomes unclickable. However I could see the link while hovering the mouse through parent navigation items.

## Expected behavior

When clicking the parent navigation item from child navigation item, opens the linked page of the parent navigation item 

## Is your portal managed or self-hosted?

Managed

**Comment by malincrist** [comment]
Hello @iAP24, I am not able to reproduce the issue you described. Could you please share your instance name by e-mail to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com) so we can investigate this further?

**Comment by MerveWiccon** [comment]
Hi, I am having the same problem. Is there any update on this issue?

**Comment by malincrist** [comment]
Hello @MerveWiccon , @iAP24 , apologies for the late reply.
The issue was fixed and will be shipped with the next release.  (ETA is end of August).
