### ISSUE TITLE
migrate.js script for the API management developer portal doesn't transfer over the Visibility/Access settings

### ISSUE THREAD

**Issue by jstn2297** [Azure/api-management-developer-portal#2207]
## Bug description

Running the scripts.v3/migrate.js from one resource to another doesn't transfer over the visibility settings. No errors are returned from the script and all the other content transfers over successfully like the widgets/pages/layouts and etc.

It seems the visibility settings transfer correctly when the user group id's are the same across two resources, but when they're not it seems to fail silently.

## Reproduction steps

1. Set visibility on one widget or section for a resource.
2. Run the script.v3/migrate.js script to another resource where the user group ids don't match.
3. View the visibility settings for the same widget in the new resource.
4. Observe that the visibility settings did not transfer over.
This image is the destination resource
![image](https://github.com/Azure/api-management-developer-portal/assets/136017225/9f424676-d663-4cb5-8009-5bb83ed396be)

## Expected behavior
The visibility settings should be checked off from the source resource it was migrated from.
This image is the source resource
![image](https://github.com/Azure/api-management-developer-portal/assets/136017225/ebbbff8e-b5ba-44a2-b617-5532b86773f9)

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

SHA ID 0b4319371e95a8be6e460d5bd3605f210dc7ed5d

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version: 114.0.5735.110 

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by AnRei123** [comment]
We require the same, if the visibility settings cannot be migrated, the feature is useless. And, for different environments, different user groups do have permissions. So it is very important to be able to assign permission groups in the content source environment by their AAD name - even they do not have access to the content source APIM environment (compare [issue](https://github.com/Azure/api-management-developer-portal/issues/2114) #2114 ).

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
