### ISSUE TITLE
Can not access current parent page URL from Custom widget

### ISSUE THREAD

**Issue by girish-tank-avnet** [Azure/api-management-developer-portal#2211]
Hello,
 i created a custom widget (in ReactJS structure provided by APIM default structure) that custom widget has the product subscription functionality with additional fields to collect more information. product subscription is made by calling REST API of management plan. but to subscribe the product we need product ID of a product.

Custom widget has only hooks function for get logged in user secrets (i.e userId, token, management endpoint), but not have any default function to get parent page information like product ID.

this product subscription custom widget will reside in product details page and that page has product id in it's URL. so we want to access that product detail parent page URL to get product id in custom widget. but i am getting crose site script error while trying to access parent page URL.

is there any solution to access parent page information or access parent page URL from Custom widget?

**Product detail page URL**: /product#product=demo

**Custom widget iFrame:**

![image](https://github.com/Azure/api-management-developer-portal/assets/136325659/f182ca80-bae1-4793-873c-bb1276652a8f)

**Comment by JMach1** [comment]
Hello @girish-tank-avnet
I've added `parentLocation` to the secrets object. It will include all the data from parent's location object. If I understood you correctly, this should resolve your issue, correct?
It will be part of the next Developer Portal release, it should be available within few weeks.

**Comment by girish-tank-avnet** [comment]
Hello JMach1.

Thanks for adding `parentLocation `to the secret object. one query is that you mention that all the data from parent location object will receive in secret object correct. so will it be only parent page URL or parent page information like if custom widget placed in product page, then we will receive all the information of product (product name, productId etc)?

would you please give me here the format of secrets object after you have added `parentLocation`? using that i can get the better idea of secrets object properties.

moreover, would you please let me know that is there any specific date on that updated developer portal will be release? if there.

Thanks.
Girish.

**Comment by girish-tank-avnet** [comment]
Hello JMach1,

if you can send us the secrets object response JSON structure after your changes then it would be great help to us.

Thanks.

**Comment by henrique-atlas** [comment]
I think we can close this ticket, right?

**Comment by girish-tank-avnet** [comment]
yes we can close this ticket as i found alternative solution from my side. Thanks for your valuable support.
