### ISSUE TITLE
migrate JS finished but no changes on portal/azure

### ISSUE THREAD

**Issue by marcosikkens** [Azure/api-management-developer-portal#2213]
## Description

We use a managed version of the developer portal i tried migration the data from development enviroment to test using the migrate.js in the V2 foilder. It succeeded with only the TLS warnings, however when looking at the portal from azure or going to the url no changes where there. Also no new revision was showing up in azure. This script is run on a build agent more information about the general steps are added into additional information

## Script:

`node migrate --sourceEndpoint $(SourceManagementEndpoint) --destEndpoint $(DestManagementEndpoint) --publishEndpoint $(DestPublishEndpoint) --sourceToken "SharedAccessSignature $(SourceSharedAccessToken)" --destToken "SharedAccessSignature $(DestSharedAccessToken)"`

##Logmessages:
2023-06-15T19:39:00.9462828Z ##[error](node:11048) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:5908) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:7752) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:4568) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2023-06-15T19:39:00.9541415Z DONE

## Expected behavior

I was expecting so see a new revision in the azure portal that i should manually publish or a new revision that was automatically published.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

Release 2.2.40.0

## Environment
Self hosted azure build agent

## Additional context

The flow of the deployment is:

1) Install node modules
2) Get source access token (and store in variable)
3) Get destination access token (and store in varable)
4) Call migrate in an azure powershell step

**Comment by JMach1** [comment]
Do we understand correctly, that the operation completes normally, just publishing doesn't happen?
If so, could you share with us your service name(s)?
In case you'd prefer to send it privately: apimportalfeedback@microsoft.com

**Comment by marcosikkens** [comment]
I've sent you an email. 

Marco
