### ISSUE TITLE
Support border-radius

### ISSUE THREAD

**Issue by xmasctf** [Azure/api-management-developer-portal#2215]
Hi guys,

I'm playing around with Developer portal and noticed that there is no option for applying border-radius to buttons. I think that is pretty basic CSS rule that should be supported. Our Corporate Identity has buttons that are rounded, and I think cards with rounded borders could be useful as well.

Is it possible to add a support for that?

Thanks in advance!

**Comment by JMach1** [comment]
Hi @xmasctf
you can change the border-radius by changing those properties on Styles page.

![image](https://github.com/Azure/api-management-developer-portal/assets/92859870/3a4dc6a9-ceae-4a87-b1fa-a9e485cc2058)

Hope it's clear now.

**Comment by xmasctf** [comment]
Hi @JMach1.

Thank you for your response, looks like I missed that one!
