### ISSUE TITLE
Remove or hide Changelog link and API Definition dropdown

### ISSUE THREAD

**Issue by AlexTukalskiy-CRL** [Azure/api-management-developer-portal#2219]
## Bug description

On API Details page there is the API Details widget. It contained API Definition drodown and Changelog link.
Is it possible to hide these components or I should create a custom widget when I want only API display name and API desription?

## Expected behavior

Be able to hide controls on internal widgets

## Is your portal managed or self-hosted?

Managed

## Additional context
![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/a6b8de78-ff98-40bf-8f51-54a34676927f)

**Comment by maciejtreder** [comment]
@AlexTukalskiy-CRL Thank you for reporting. The functionality which you're looking for is not currently available; we will triage that and decide if we're going to implement this. What you can do for now to walk-around that is (as you described) try to play with the custom-widget.
