### ISSUE TITLE
Headers examples title/value/description

### ISSUE THREAD

**Issue by AlexTukalskiy-CRL** [Azure/api-management-developer-portal#2221]
## Bug description

During my research api-management-developer-portal\src\components\operations\operation-details\ko\runtime\operation-details.html
I found that for **operation().parameter,.examples** source code has condition
```
<!-- ko ifnot: example.title === "default" && !example.description && parameter.examples.length === 1 -->
<span data-bind="text: example.title"></span>:
<!-- /ko -->
```
but for **operation().request.header.examples** this condition absent

## Expected behavior

Headers examples should works as a Parameters examples

## Is your portal managed or self-hosted?

Managed

## Additional context
OpenAPI specification
![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/91f66bb5-0e20-436d-9dee-90a6cf2b48e6)

So for parameter examples we see
![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/f3c4725c-7e45-4bb8-b441-61069a218e3e)

And for OpenAPI specification
![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/d7559b6a-f718-4563-969f-a5856c94a1c7)

for header examples we see
![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/25ae95ad-a1c7-4397-b029-01469a2a9ba4)

In this case we see a **default:** world,

**Comment by maciejtreder** [comment]
@AlexTukalskiy-CRL  Thank you for letting us know. We will adress this issue in one of the future releases.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
