### ISSUE TITLE
HTTP Strict Transport Security (HSTS) Errors and Warnings

### ISSUE THREAD

**Issue by Harmanpreet-96** [Azure/api-management-developer-portal#2222]
## Bug description

The HSTS Warning and Error may allow attackers to bypass HSTS, effectively allowing them to read and modify your
communication with the website.

Error
  preload directive not present

## Remedy
Ideally, after fixing the errors and warnings, you should consider adding your domain to the the HSTS preload list. This will ensure
that browsers automatically connect your website by using HTTPS, actively preventing users from visiting your site using HTTP.
Since this list is hardcoded in users' browsers, it will enable HSTS even before they visit your page for the first time, eliminating the
need for Trust On First Use (TOFU) with its associated risks and disadvantages. Unless you fix the errors and warnings your website
won't meet the conditions required to enter the browser's preload list.

Browser vendors declared:
  Serve a valid certificate

If you are listening on port 80, redirect all domains from HTTP to HTTPS on the same host. Serve all subdomains over
HTTPS:
      In particular, you must support HTTPS for the www subdomain if a DNS record for that subdomain exists

Serve an HSTS header on the base domain for HTTPS requests:
    The max-age must be at least 31536000 seconds (1 year)
    The includeSubDomains directive must be specified
    The preload directive must be specified
     If you are serving an additional redirect from your HTTPS site, that redirect must have the HSTS header (rather than
the page it redirects to)

## Is your portal managed or self-hosted?
Managed

## API Management service name
enterprise-apim-dev

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

**Comment by Harmanpreet-96** [comment]
Any updates?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
