### ISSUE TITLE
Can`t H align first cell in table

### ISSUE THREAD

**Issue by AlexTukalskiy-CRL** [Azure/api-management-developer-portal#2223]
## Reproduction steps

1. Create a new table in Aticle
2. Click on cell and select Table
3. Change table to 1 column and 3 rows
4. Create Button widget in the all cells
5. Select first cell and try Horizontal align to the right
6. Make shure that Button not aligning
7. Select second cell try Horizontal align to the right
8. Make shure that Button aligning

## Expected behavior

All cells should aligning

## Is your portal managed or self-hosted?

Managed

## Additional context

![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/1360c15c-2675-4b4e-b8bf-7c92c5d5c1cb)

**Comment by maciejtreder** [comment]
@AlexTukalskiy-CRL Thank you for reporting that. I can confirm that I've reproduced that issue on my end. Hopefully we will deliver fix with the nearest releases.
