### ISSUE TITLE
Q: Developer portal with Identity Server

### ISSUE THREAD

**Issue by xmasctf** [Azure/api-management-developer-portal#2225]
Hi all,

I have a IdentityServer4 and then I'm using Bearer tokens on my back-end services. What is the best way to connect Identity Server with Developer portal.

What I want to achieve:
- User can log in using a screen from Identity Server,
- User can get a Bearer token and attach it to requests in API page / playground

How to achieve that? Is Azure AD B2C correct option for that? I do have Azure AD with B2B functionality which could be used for external developers and invited partners. But what if we want to open the portal for everyone, so they can register and start using our APIs?

Thanks for help!

**Comment by maciejtreder** [comment]
@xmasctf You can refer to this place in documentation: https://learn.microsoft.com/en-us/azure/api-management/secure-developer-portal-access which describes the different authentication flows available in API Management + DevPortal. I believe that Azure AD, it's what you're looking for.

**Comment by xmasctf** [comment]
@maciejtreder 
Is Azure AD really a correct option? According to the link you have provided, Azure AD is the best option only when you have the developer portal that is consumed internally. What if we want to extend that, and offer our developer portal to external customers as well?
Also it doesn't say anything on how to connect Azure AD and IdentityServer. Everyone is talking about connecting Azure AD B2C with Identity. Is it possible to achieve that only with Azure AD?
