### ISSUE TITLE
Dev Portal cookie expires (and doesn't refresh) leaving UI in an unintended state

### ISSUE THREAD

**Issue by kevinpearce** [Azure/api-management-developer-portal#2228]
## Bug description

After a user has been logged into the API Manager Developer Portal for over 30mins, cookie expires and Menus/Items that use the built in Groups for visibility (Developers vs Guests) do not render in the UI correctly.

ie. An item that has been filtered to show only for a Developer (the default logged in user) disappears from view after 30mins after either a page change or a refresh.

This results in any navigation to the Sign In button redirecting to the Home page

API Requests can still be made successfully (SAS token for auth still exists and renews every 1 hour as intended)

## Reproduction steps

1. Sign into the Developer Portal
2. Wait 30mins for Cookie to expire (can also be manually deleted to replicate)
3. Refresh page
4. Watch menu filters change

## Expected behaviour

All menu filters should remain exactly the same until the user Signs Out or Browser is closed.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Chrome / Edge
 - Version: 114.0.5735.199 / 114.0.1823.67

## Additional context

Possibly related : https://github.com/Azure/api-management-developer-portal/issues/883

**Comment by ygrik** [comment]
Hi @kevinpearce 
This token issue will be fixed with the next portal release.

**Comment by kevinpearce** [comment]
Hi @ygrik ,

Could you possibly check/confirm if this change has already been made please?
Evidence suggests that it has, even if another "release" has not yet been published.

Thanks

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
