### ISSUE TITLE
API Products - componet is not list product

### ISSUE THREAD

**Issue by KannanKalisamy** [Azure/api-management-developer-portal#223]
**Describe the bug**
Product search is not working and doesnt show product details

**To Reproduce**
taken the latest code form master branch and configured APIM detail.

**Portal environment**
Managed / Self-hosted

**Additional context**
![image](https://user-images.githubusercontent.com/16281799/67216409-806d5080-f466-11e9-92fa-d8d100f6b14d.png)

**Comment by mikebudzynski** [comment]
Could you please give us an SHA of the commit you're running your portal off?

**Comment by azaslonov** [comment]
Fix has been merged.
