### ISSUE TITLE
Authentication & Authorization is not working in custom self-hosted developer portal.

### ISSUE THREAD

**Issue by GokulChavan198** [Azure/api-management-developer-portal#2230]
When we host custom self-hosted developer portal, we lose the visibility and access control. How to implement the authentication and authorization for custom developer portal. Thanks

**Comment by maciejtreder** [comment]
Access control is supported only in the managed portal. Unfortunatelly you're not able to use it in self-hosted version.

**Comment by GokulChavan198** [comment]
Do we have any document or steps by step guide that how we are going to achieve the authentication & authorization?
