### ISSUE TITLE
Various UI actions failing due to knockout js not properly being loaded

### ISSUE THREAD

**Issue by boulajp** [Azure/api-management-developer-portal#2233]
## Bug description

Certain actions in the developer portal configuration page result in error - An "oops, something wen't wrong dialogue appears", and the following console error exists:

![image](https://github.com/Azure/api-management-developer-portal/assets/10444504/8f0b1030-241d-4caa-996b-f1538f5827b0)

An example of this is attempting to add a font on the styles page.

## Reproduction steps

1. Go to the styles page
2. Click add font
3. Select a font
4. An error pop up will appear, and the console output will have an error. No new font is added.

## Expected behavior

The new font should be added without error.

## Is your portal managed or self-hosted?

Managed

## API Management service name

testpublicapijoboulan

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome, Edge

## Additional context

This error seems to have originated due to knockout js not being properly loaded. Issue exists with a number of different actions in the developer portal.

**Comment by steebwba** [comment]
Is there any update for this? I still have issues trying to select a new font due to the same issue

**Comment by yisusworldwide** [comment]
Hi there, despite having "Error 400 - Bad Request" in the console, I successfully added up to 5 different fonts (otf and ttf format) as showed in the screenshot attached to this comment. No knockout js error was met. 

![Adding Fonts in DevPortal Styles](https://github.com/Azure/api-management-developer-portal/assets/84227371/8baecb96-12a7-4ad0-89c3-af345087f66b)

**Comment by andrewgtibbetts** [comment]
Confirmed. I can now add fonts without error.
