### ISSUE TITLE
Overlapping elements

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2236]
## Bug description

For certain screen resolutions and devices elements are overlapping in our environments:
![image](https://github.com/Azure/api-management-developer-portal/assets/58420097/f363ae40-dec3-4ccb-88a7-849b3eb30e8d)

In this example the issue occurs for a width of ~1580 - 1380

This might however be  special case, as the layout looks like this:
![image](https://github.com/Azure/api-management-developer-portal/assets/58420097/a24fc647-1cce-4e65-b146-49aec38dc393)

## Is your portal managed or self-hosted?

Managed

**Comment by Christoph-Mantsch** [comment]
@SenpuDev, unfortunately this problem with overlapping elements still persists for some screen resolutions (in this case: 1394x841):
![image](https://github.com/Azure/api-management-developer-portal/assets/92931813/cd5e3130-b544-426f-951d-cc8dfc1f0c1f)


We have the same problem if we use the zoom function by using CTRL+scroll wheel in our environment (in this case zoom factor 125%):
![image](https://github.com/Azure/api-management-developer-portal/assets/92931813/58e09093-a575-4036-9c8d-5d135e1128fe)
