### ISSUE TITLE
User Enumeration - Error Messages

### ISSUE THREAD

**Issue by AlexTukalskiy-CRL** [Azure/api-management-developer-portal#2240]
## Bug description

The application returns specific error messages notifying the end user if a username is valid or not based on the user input. As a result, an attacker may be able to enumerate valid usernames via brute force attacks.
Leveraging this issue an attacker may be able to enumerate account which could be targeted in future attacks.
Return the same error message for both invalid and valid users when an invalid input is provided. Example: Login was unsuccessful.
## Reproduction steps
Try to login with invalid password or/and email

## Expected behavior

Messages should be the same for invalid user and invalid password.

## Is your portal managed or self-hosted?

Managed

## Additional context

![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/4469bc9f-fb03-404c-bd7a-a669fa4ecc6b)
![image](https://github.com/Azure/api-management-developer-portal/assets/123678511/1afd211d-35d2-49c0-b732-16830d1aeb66)

**Comment by mrcarlosdev** [comment]
Hi @AlexTukalskiy-CRL, many thanks for opening this bug, we appreciate your collaboration opening this kind of issues.

I have checked the sign in behaviour and it is returning the same message for emails (for both, existing and not existing ones) which is `Please provide a valid email and password.`. The message `Please enter a proper email address.` is an email validation message, meaning that the email is malformed to be an email format. In your example the @ character is missing,
