### ISSUE TITLE
Information Disclosure - Inadequate Cache Control

### ISSUE THREAD

**Issue by AlexTukalskiy-CRL** [Azure/api-management-developer-portal#2242]
## Bug description

The application does not restrict caching and may save sensitive data to the local browser's cache. Sensitive data may be available by using the &quot;back&quot; button on the browser or by accessing the data on the local system. Logging out from an application does not clear the browser cache of any sensitive information that might have been stored.
If the private directive is not used this also means any sensitive data is now being stored intermediate hosts such as CDNs and proxies.

## Expected behavior

For every page that contains sensitive information, the server must instruct the browser not to cache data. Such a directive can be issued in the HTTP response headers: 

`Cache-Control: no-store`

Though Meta tags can also be used to set these directives, using the header is the preferred method, as not all browsers honor the Meta tags consistently.

If the site contains file download functionality (such as a PDF or Office document download) in certain configurations, these cache control settings may interfere with downloading files in some IE browser versions. Be sure to test this functionality before implementing in production environments to ensure that cache control settings do not interfere with intended functionality. See the following for additional information and workarounds:

- http://support.microsoft.com/kb/812935
- http://support.microsoft.com/kb/2549423
- http://blogs.msdn.com/b/ieinternals/archive/2009/10/03/internet-explorer-cannot-download-over-https-when-no-cache.aspx
- http://blogs.msdn.com/b/ieinternals/archive/2010/04/21/internet-explorer-may-bypass-cache-for-cross-domain-https-content.aspx

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
