### ISSUE TITLE
Insufficient Session Expiration

### ISSUE THREAD

**Issue by AlexTukalskiy-CRL** [Azure/api-management-developer-portal#2246]
## Bug description

The application has insufficient session expiration. Proper session expiration ensures that if a user does not log out properly or leaves their computer unattended while they are logged in, their session will expire after a certain period of inactivity. Sliding expiration resets the expiration time for a valid authentication cookie if a request is made and more than half of the timeout interval has elapsed. 

Since HTTP is a stateless protocol, web sites commonly use session IDs to uniquely identify a user from request to request. Consequently, each session ID's confidentiality must be maintained to prevent unauthorized account access. A stolen session ID can be used to view another user's account or perform actions within the context of that user.

In conjunction with other vulnerabilities, insufficient session expiration increases a web site's exposure to session theft attacks. Were an attacker to steal a user's session, they would be able to take any action in the application within the context of the user whose session was stolen.

## Expected behavior

Ensure that sessions expire on both the server and the client after an appropriate period of inactivity. A session time out period of fifteen minutes or less is recommended. Although short session expiration times do not help if a stolen session is immediately used, this control will prevent an attacker from continuously using the stolen session ID. If additional controls are in place, such as disallowing concurrent logins, the chance of session theft will be greatly reduced.

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
