### ISSUE TITLE
Insecure HTTP Usage

### ISSUE THREAD

**Issue by Harmanpreet-96** [Azure/api-management-developer-portal#2255]
## Bug description

HSTS is implemented in the target website however HTTP requests are not redirected to HTTPS. This decreases the value of HSTS
implementation significantly.

For example visitors who haven't visited the HTTPS version of the website previously will not be able to take advantage of HSTS. 

Impact
Users will not be able to take advantage of HSTS which almost renders the HSTS implementation useless. Not having HSTS will
make MITM attacks easier for attackers.

## Reproduction steps

http://sandbox-developer.emerson.com/

HTTP/1.1 503 Service Unavailable
Connection: close
Content-Length: 326
Content-Type: text/html; charset=us-ascii
Date: Sat, 22 Jul 2023 03:47:58 GMT
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>

## Expected behavior

Configure the webserver to redirect HTTP requests to HTTPS.

## Is your portal managed or self-hosted?

Managed

## API Management service name

enterprise-apim-dev

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by malincrist** [comment]
Hello @Harmanpreet-96,  thank you for bringing this issue to our attention. We have created an internal work item to investigate and address this.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
