### ISSUE TITLE
Try It does not support `*` (asterisk) as a path parameter

### ISSUE THREAD

**Issue by karatkep** [Azure/api-management-developer-portal#2258]
## Bug description

Try It - Path parameter is omitted when `*` (asterisk) provided for parameter value. 

## Reproduction steps

1. View an API which contains at least 1 path parameter - e.g. '/s/{id}/{subId}'
2. Click on the 'Try it' button 
3. Enter `*` (asterisk) as a value for path parameter - e.g. '/s/*/12'
4. Path parameter with `*` (asterisk) value is omitted in generated URL: '/s/12'. Please see screenshoot below:
![image](https://github.com/Azure/api-management-developer-portal/assets/63723184/c8fbf08b-c3fe-4194-ad68-6633f6dc2f3c)

## Expected behavior

Path parameter with `*` (asterisk) value is present in generated URL: '/s/*/12'.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

n/a

## API Management service name

contoso-api

## Environment

 - Operating system: macOS
 - Browser: Google Chrome
 - Version: 114.0.5735.248 (Official Build) (x86_64)

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by malincrist** [comment]
Hello @karatkep ,  thanks for reaching out. The issue you described was fixed (as part of this PR: #2137 ).
However, please note that it hasn't been deployed for managed portals yet (ETA is end of August).

**Comment by karatkep** [comment]
Hello @malincrist, is there any update on deployment the fix to support * ?

**Comment by malincrist** [comment]
Hello @karatkep , unfortunately, the release was postponed. New ETA is mid-September. Apologies for the delay and any inconveniences created.

**Comment by karatkep** [comment]
Hello @malincrist , is there any luck with deployment?

**Comment by malincrist** [comment]
Hwllo @karatkep , the deployment is in progress, please give it a few days to reach all the regions. Apologies for the delay.

**Comment by karatkep** [comment]
Hello @malincrist, unfortunately, the reported issue is still reproducible. Can we reopen this bug?

**Comment by malincrist** [comment]
Hello @karatkep , unfortunately, the deployment was cancelled due to found regressions. The new ETA for the release is 1 week. Apologies for the delay and the inconveniences caused by this.
