### ISSUE TITLE
API Products - heavily truncated product description with html tags

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2259]
## Bug description

We noticed that our API Product descriptions are heavily truncated for certain products:
![image](https://github.com/Azure/api-management-developer-portal/assets/58420097/fb2e7df2-d8c7-46ea-9ac7-548b05ec81b4)

After some investigation, we concluded, that it might be due to html tags used in the description.
- Without `</br>` tags more text is shown, but it is still heavily truncated.
- Removing unordered list tags (with list items) shows almost all of the Product description
- Removing even hyperlink `<a>` tags from the description results in this:
   
   ![image](https://github.com/Azure/api-management-developer-portal/assets/58420097/7a03edfd-31d2-4ed2-b068-4f4429b6f5dd)

To provide the best description of our products to our customers we rely on using lists, breaks and more html tags. Truncating the text heavily to the extend that on the Products page users cannot even get a short description, and having to navigate to the product itself   to read the description, is bad behavior.

## Reproduction steps

1. Create a text with html tags as Product description
2. Check its behavior in the Portal
3. Compare to text of similar length without html tags
4. See issue

## Expected behavior

- Clear communication of truncation rules
- logical truncation of text (3 word descriptions are not enough)
- When e.g. lists are not able to be displayed in the preview, then atleast show sufficient text that is before it 

## Is your portal managed or self-hosted?

Managed

**Comment by malincrist** [comment]
Hello @ZarTrox , thank you for reaching out.
I am not able to reproduce the issue you are describing:
I added this description for a product:
```
<b style="color:pink;">Subscribers have completely unlimited access to the API. Administrator approval is required.</b> </br><br>
<a href="https://contoo.com">this is a link ok</a>
<ol>
<li> test </li>
<li> test2 </li>
</ol>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem dolor sed viverra ipsum nunc aliquet. Sed vulputate mi sit amet mauris commodo quis imperdiet. Consectetur adipiscing elit ut aliquam purus. Dignissim sodales ut eu sem integer vitae justo eget magna. Justo eget magna fermentum iaculis eu non diam phasellus. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Risus in hendrerit gravida rutrum quisque non tellus orci. Tristique senectus et netus et. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Justo laoreet sit amet cursus.

```

And it seems to be displayed ok:
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/09552c9d-f5be-4073-99b3-ee2221dd2e08)

Jut to clarify, the truncation should happen at [250 characters](https://github.com/Azure/api-management-developer-portal/blob/d39575408599ce5cb9ee1c68872f55e08d194d4f/src/components/products/product-list/ko/runtime/product-list.html#L27C13-L29C19), and in the screenshot I provided, that's what happens.

could you please share one description that gets so heavily truncated as it does in your screenshot?

**Comment by ZarTrox** [comment]
String:

```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata s</br></br>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, se<ul><li>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam non</li><li>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut</li> <li>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt</li></ul>Lorem ipsum dolor<a href="">Lorem &amp; ipsum dolor</a>.
```

Rendering: 
![image](https://github.com/Azure/api-management-developer-portal/assets/58420097/472317ca-846e-46f0-94e9-3fb85f538f67)

Do you need more information?
The lorem ipsum is exactly as long as the original text.
