### ISSUE TITLE
Cookie Not Marked as Secure

### ISSUE THREAD

**Issue by Harmanpreet-96** [Azure/api-management-developer-portal#2261]
## Bug description

Security scan detected that a cookie not marked as secure, and transmitted over HTTPS.

This means the cookie could potentially be stolen by an attacker who can successfully intercept and decrypt the traffic, or
following a successful man-in-the-middle attack.

**Impact**
This cookie will be transmitted over a HTTP connection, therefore if this cookie is important (such as a session cookie), an attacker
might intercept it and hijack a victim's session. If the attacker can carry out a man-in-the-middle attack, he/she can force the victim
to make an HTTP request to steal the cookie.

Identified Cookie(s)
returnUrl

Cookie Source
JavaScript

## Expected behavior

Mark all cookies used within the application as secure.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

enterprise-apim-dev

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by ygrik** [comment]
The developer portal use **returnUrl** cookie to navigate the request after sign-in if sign-in required to load the page.
This cookie does not contain sensitive info and does not require to be Secure
