### ISSUE TITLE
Cookie Not Marked as HttpOnly

### ISSUE THREAD

**Issue by Harmanpreet-96** [Azure/api-management-developer-portal#2262]
## Bug description

Security scan identified a cookie not marked as HTTPOnly.
HTTPOnly cookies cannot be read by client-side scripts, therefore marking a cookie as HTTPOnly can provide an additional layer of
protection against cross-site scripting attacks.

**Impact**
During a cross-site scripting attack, an attacker might easily access cookies and hijack the victim's session.

**Identified Cookie(s)**
    returnUrl
**Cookie Source**
   JavaScript

## Expected behavior

Mark the cookie as HTTPOnly. This will be an extra layer of defense against XSS. However this is not a silver bullet and will not
protect the system against cross-site scripting attacks. An attacker can use a tool such as XSS Tunnel to bypass HTTPOnly

## Is your portal managed or self-hosted?

Managed

## API Management service name

enterprie-apim-dev

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by ygrik** [comment]
The developer portal use **returnUrl** cookie to navigate the request after sign-in if sign-in required to load the page.
This cookie does not contain sensitive info and does not require to be HttpOnly
