### ISSUE TITLE
Version Disclosure (Lodash)

### ISSUE THREAD

**Issue by Harmanpreet-96** [Azure/api-management-developer-portal#2265]
## Bug description
Security scan identified a version disclosure (Lodash) in the target web server's HTTP response.
This information can help an attacker gain a greater understanding of the systems in use and potentially develop further attacks
targeted at the specific version of Lodash.

**Impact**
An attacker might use the disclosed information to harvest specific security vulnerabilities for the version identified.

## Expected behavior

Configure your web server to prevent information leakage.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

enterprise-apim-dev

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by Harmanpreet-96** [comment]
For Version Disclosure (Lodash), the commands below can be executed on the browser’s console.
•	_.templateSettings.imports._.templateSettings.imports._.VERSION

**Comment by brsolomon-deloitte** [comment]
@Harmanpreet-96 that's not a valid snippet of code to execute so your instructions are not reproducible. Can you please specify more exactly what to execute in the developer tools console that will display the Lodash version?

@JMach1, FYI, this finding comes from an Invicti Enterprise security scan.

**Comment by brsolomon-deloitte** [comment]
Related: https://github.com/lodash/lodash/issues/5704

**Comment by Harmanpreet-96** [comment]
_.templateSettings.imports..templateSettings.imports._.VERSION

**Comment by brsolomon-deloitte** [comment]
> _.templateSettings.imports..templateSettings.imports._.VERSION

Again: that is not a valid variable name. What specifically are you suggesting?

![image](https://github.com/Azure/api-management-developer-portal/assets/81818815/f0042a81-39eb-4a70-9c92-e582094df222)

**Comment by Harmanpreet-96** [comment]
![image](https://github.com/Azure/api-management-developer-portal/assets/87671856/73941874-52ee-4c7c-a9f3-1b0dde7cc061)

**Comment by Harmanpreet-96** [comment]
Any updates?

**Comment by eduardhyan** [comment]
Resolved console disclosure of the "underscore" variable by updating lodash imports. Replaced:
```javascript
import { isEqual } from "lodash";
```
with:
```javascript
import isEqual from "lodash/isEqual";
```
The issue was resolved for me

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
