### ISSUE TITLE
Enable "Group by tag" in developer portal per API

### ISSUE THREAD

**Issue by JShrinath** [Azure/api-management-developer-portal#2266]
Is there a way to enable grouping by tag by default for individual API owner
![image](https://github.com/Azure/api-management-developer-portal/assets/99168778/1727a969-b0d0-47fe-b52d-a5573cc2461a)
?

**Comment by JMach1** [comment]
Hello @JShrinath 
in List of operations settings, there is an option for "Default Group by tag to enabled"
![image](https://github.com/Azure/api-management-developer-portal/assets/92859870/17a4030d-6c5b-476c-a109-7f8b62f0ec8c)
Isn't that what are you looking for?

**Comment by JShrinath** [comment]
This will enable it for all the APIs right ?

**Comment by JShrinath** [comment]
So we don't want it to enabled by default for all of them. But like for particular API if possible ?

**Comment by JMach1** [comment]
As of right now, you can have it only enabled or disabled for all APIs by default. On what attributes do you need this behavior depended?

**Comment by JShrinath** [comment]
Depend by API itself

**Comment by mikebudzynski** [comment]
@JShrinath, selective grouping per tag is not supported and is not on our roadmap. Can you clarify what you are trying to achieve and provide us with an example?

**Comment by JShrinath** [comment]
Could you please enable it in DEV ?

**Comment by JShrinath** [comment]
Any updates ?
