### ISSUE TITLE
The API version being used by the developer portal is being retired in September 2023

### ISSUE THREAD

**Issue by alexwiese** [Azure/api-management-developer-portal#2271]
## Bug description

The version of the Azure API Management API being used by the developer portal is being retired next month.

> On 30 September 2023, all API versions for the Azure API Management service prior to 2021-08-01 will be retired and API calls using those API versions will fail.

Microsoft [recommend limiting control plane API ](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.APIM.MinAPIVersion/) calls to API Management to '2021-08-01' or newer:
> Limit control plane API calls to API Management with version '2021-08-01' or newer.

The portal currently uses [a preview version](https://github.com/Azure/api-management-developer-portal/blob/e350f81842cd766e757298b787e10988683656dc/src/constants.ts#L296) that will be retired next month:

```
export const managementApiVersion = "2021-04-01-preview";
```

When the `minApiVersion` configuration option is set to '2021-08-01' as recommended by Microsoft the portal fails to load products and APIs with the following error:

``` 
{
    "error": {
        "code": "MissingOrIncorrectVersionParameter",
        "message": "API version query parameter is not specified or was specified incorrectly.  Supported versions: 2021-08-01,2021-12-01-preview,2022-04-01-preview,2022-08-01,2022-09-01-preview,2023-03-01-preview,2023-05-01-preview  Example query param format: api-version=SupportedVersion",
        "details": null
    }
}
```

## Reproduction steps

1. Set the `minApiVersion` to '2021-08-01' as recommended by Microsoft
2. Open the developer portal
3. Navigate to the Products or APIs page
4. Open browser dev tools to see the failed API requests from the portal

## Expected behavior

The APIs and Products are loaded and displayed in the portal.

## Is your portal managed or self-hosted?

Managed

## API Management service name

N/A

## Environment

 - Operating system: Windows 11
 - Browser: Edge
 - Version: 115.0.1901.203

**Comment by maciejtreder** [comment]
@alexwiese Thanks for reporting that. I've created the working item in our system, to further investigate that problem.

**Comment by cermakp** [comment]
Hi, I can still see, that there is obsolete api version defined (2021-04-01-preview) in `master` branch - [here](https://github.com/Azure/api-management-developer-portal/blob/e350f81842cd766e757298b787e10988683656dc/src/constants.ts#L296).

This version [is not supported ](https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023) anymore

**Comment by alexwiese** [comment]
hi @maciejtreder - any update on this?

the API version will be retired next week.

**Comment by f-alizada** [comment]
@alexwiese Thank you for the report. 
We are currently working on this, so portals should not be affected.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
