### ISSUE TITLE
Is the paperbits project still alive?

### ISSUE THREAD

**Issue by kincjf** [Azure/api-management-developer-portal#2280]
hello. I am using azure apim devportal, and I was wondering if it is okay to use paperbits in other projects.

I wonder if paperbits are only being used for apim devportal?

While analyzing the api-management-developer-portal code, I found the paperbits code, and I thought that it would be okay to use it not only for apim devportal but also for other projects.

Although it has been confirmed that paperbits core has not been updated for several months.

- same question on paperbit core github repo : https://github.com/paperbits/paperbits-core/issues/47

**Comment by jsorohova** [comment]
Hello @kincjf , @alzaslon answered you in the Paperbits core repo so I will close this one as well. Thank you for your interest.
