### ISSUE TITLE
Provide capability to run the developer portal as Docker container

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/api-management-developer-portal#230]
Provide capability to run the develop portal as Docker container so that we can run it wherever we want - In Azure, on-premises or on our local box for local experimentation.

Would allow us to test things out before pushing changes to other stages.

**Comment by mikebudzynski** [comment]
@tomkerkhove Could you please elaborate more on why the current solution isn't enough? The developer portal doesn't require a backend, so I'm not sure what could be packaged in the Docker container. Portal can be served through storage or a simple proxy.

**Comment by mikebudzynski** [comment]
Tom, I closed the issue because feature requests should now be posted at https://aka.ms/apimwish as per our readme instructions.

Feel free to clarify your scenario here though.

**Comment by tomkerkhove** [comment]
Makes sense, thanks!

**Comment by The3G** [comment]
It would be good to revisit this IMHO as the docker image/container would allow/provide easier integration with .NET ASPIRE
