### ISSUE TITLE
OpenAPI schema: 'allOf' children do display description correctly

### ISSUE THREAD

**Issue by redashimself** [Azure/api-management-developer-portal#2309]
## Bug description

We have APIs defined with OpenAPI which we are importing into the Azure API Management. When the APIs define schemas with `allOf` descriptions, the child elements don't appear to be imported and display field descriptions correctly.

## Reproduction steps

1. Define an API using OpenAPI 3.0.1 with a schema having allOf child with a description (see example below)
2. Import API into Azure API Management
3. Open and inspect API in the Developer Portal

## Is your portal managed or self-hosted?

Managed

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system:  Windows 11
 - Browser:  Any
 - Version:

## Additional context

1. OpenAPI schema (YAML format, cut down version)

```
openapi: 3.0.1
info:
  version: 1.0.0
  title: Departure Times API Specification Issue Highlight
paths: {}

components:
  schemas:
    DepartureTimes:
      type: object
      properties:
        outGate:
          allOf:
            - $ref: '#/components/schemas/Time'
            - description: 'Super cool outGate'
        offGround:
          allOf:
            - $ref: '#/components/schemas/Time'
            - description: 'Super lame offGround'
        onGround:
          $ref: '#/components/schemas/Time'
    Time:
      type: object
      properties:
        local:
          type: string
          description: 'The local passenger arrival/departure time (hh:mm format).'
          nullable: true
        utc:
          type: string
          description: 'The utc passenger arrival/departure time (hh:mm format).'
          nullable: true
      description: 'The passenger arrival/departure time (hh:mm format).'
```

2. Developer portal view 
![image](https://github.com/Azure/api-management-developer-portal/assets/114561058/7fb958f1-5133-47c7-b507-4960ddbc130d)

3. Swagger Editor view 
![image](https://github.com/Azure/api-management-developer-portal/assets/114561058/0a424288-cce8-4874-b35f-d428f7ecaa46)

4. I expect the description for _outGate_ (Super cool outGate) and _offGround_ (Super lame offGround) to be present in the developer portal.

Can attach full schema exported from the portal for reference if needed.

**Comment by jsorohova** [comment]
Hello, thank you for reporting the issue. I've created a work item and will prioritize it.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
