### ISSUE TITLE
API Schema is nested in new developer portal

### ISSUE THREAD

**Issue by sthirthala** [Azure/api-management-developer-portal#2310]
Developer experience in the new APIM developer portal

1.	SHOWSTOPPER API Schema – Nested objects are broken out individually.  This requires a lot of scrolling and is not user friendly.  We’d like to continue to show a consolidated schema and provide users the ability to select between schema & sample.

**Comment by jsorohova** [comment]
Hello @sthirthala , thank you for your report. Could you please provide more info on what exactly seems to be broken out? Some screenshots and/or your api definitions schema sent to us to apimportalfeedback@microsoft.com would help me a lot in understanding your concerns and requests. Thank you.

**Comment by sthirthala** [comment]
For managed portal, please log support tickets in Azure help+support center

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
