### ISSUE TITLE
Custom HTML Widget Rendering IFrame

### ISSUE THREAD

**Issue by CBZakaria** [Azure/api-management-developer-portal#2314]
Hello, 

I Used a custom widget HTML to write a documentation for my API with a lot with hyperlinks but since It's rendred to an IFrame without the parameter "allow-same-origin" in the sandbox properties of the <iframe>.  My hyperlinks are not working. Is their away to add this parameter ? 

Thanks

**Comment by JMach1** [comment]
Hello,
I tested hyperlinks like this and they work just fine for me:
`<a target="_parent" href="https://-----.developer.azure-api.net/profile">click</a>` (replace dashes with your service name)
We are working on refactoring how custom html widgets are loaded to simplify this in the future. 
What issue are you getting?

**Comment by cgorman-cu** [comment]
I am getting the same issue.

CORS is blocking the iframe from getting any information about the `window.parent`

'window.parent' returns null, so it is causing the error.

`Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.`

**Comment by CBZakaria** [comment]
Finally I found a workaround and used it which is the custom widget.
