### ISSUE TITLE
Question: Self-hosted authorizationServers endpoint

### ISSUE THREAD

**Issue by jan-mrm** [Azure/api-management-developer-portal#2316]
Hi there,

since version 2.17.0 of the Developer Portal the behaviour of loading the authorization servers changed (https://github.com/Azure/api-management-developer-portal/pull/1764).

When opening the page of an api the information of the authorization server(s) are requested ([portal-url]/authorizationServers/[auth-server-name]). This does not seem to work when self-hosting the portal using a storage account, or am I missing something / doing something wrong? Since the page does not exist in the storage account?

Is there a solution for that? Something that we would need to do?

**Comment by jan-mrm** [comment]
Hi @malincrist , thanks for looking into this :)
My current problem after updating is, that I get browser errors saying that
GET [portal-url]/authorizationServers/my-specific-auth-server
returns a 404.
Before the change mentioned above the information was statically put into a `auth-servers.json` file placed into the files of the portal at build time and then read during run time.
Now the request GET [portal-url]/authorizationServers/my-specific-auth-server is issued, but the endpoint / file does not exist in the storage account. 
The request should be issued against the actual api-management service / the management endpoint?

**Comment by malincrist** [comment]
@jan-mrm , I'm not sure I understand the problem you are facing. Could you please share with me what you have configured for the "backendUrl" in the config files? 
`"backendUrl": "https://<service-name>.developer.azure-api.net"`

Here, `<service-name>` should be your APIM instance name. This will automatically go to your instance's developer portal backend (from our hosted Azure service).
This backend knows how to handle the `/authorizationServers/my-specific-auth-server` based on your APIM instance resources.

So, authorization servers are not static items read from json file anymore, but they are managed dynamically (like APIs, for example).

You can mange them through Azure Portal interface or through ARM requests (more info [here](https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/authorization-server/create-or-update?tabs=HTTP))

**Comment by jan-mrm** [comment]
@malincrist at the moment "backendUrl" points to the URL of the developer portal. We have custom domains. So which one should it point to: "Gateway", "Developer Portal", "Management"? I'd assume to the "Developer Portal"? 
If yes, then, since we run the developer portal as _self-hosted_ and not as managed, we end up calling the Portal which is in a Storage Account.
The self-hosted version does not have a backend like the managed one - so thats the problem here, right? I could not find any documentation about what to do about that / what needs to be done about a "backend" when self-hosting. Do you have any docs / insights?

**Comment by malincrist** [comment]
@jan-mrm , it should point to the custom domain.


Even if it is self-hosted, it has its own developer portal backend backend (documentation [here](https://learn.microsoft.com/en-us/azure/api-management/developer-portal-self-host#configure-cors-settings-for-developer-portal-backend))

> The self-hosted developer portal relies on the developer portal's backend endpoint (set in backendUrl in the portal configuration files) to enable several features, including:
> 
> CAPTCHA verification
> [OAuth 2.0 authorization](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-oauth2) in the test console
> [Delegation](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-setup-delegation) of user authentication and product subscription

<br>
Can you please confirm whether you have added and linked the auth server as I suggested earlier (Azure Portal/ARM request)?

**Comment by jan-mrm** [comment]
@malincrist yes the auth server is configured under APIM instance -> Developer Portal -> OAuth 2.0 + OpenID Connect and also connected to the api that I open in the developer portal (APIM instance -> APIs -> APIs -> API you want to link the server to -> Settings -> Security). I guess the fact that the 404 occurs at `/authorizationServers/my-specific-auth-server` also shows that the auth server is at least connected because that specific auth server is requested.

I just tried to route request to `/authorizationServers/*` to your suggested backendUrl `https://<service-name>.developer.azure-api.net` and this seems to work! The other requests are routed to the storage account instead. Does that sound right?

I'm not really sure how it is supposed to be setup when self-hosting the portal.
When its managed I have one URL ("Developer portal URL" from Api-Management Service).
When its self-hosted then
- on the one hand I need one URL that points to the actual portal which is in a storage account
- on the other hand I need to point the "backendUrl" to the Developer Portal backend

Is that correct? Does this mean they cannot be the same URL? Unless I setup extra routing like:
- /authorizationServers/* -> <service-name>.developer.azure-api.net
- all other requests -> portal-storage-account.web.core.windows.net
- (probably one more rule for /signin-oauth/...)

(The backendUrl default "<service-name>.developer.azure-api.net" exists even when a custom domain is defined and could be used for routing like above)

**Comment by malincrist** [comment]
> on the one hand I need one URL that points to the actual portal which is in a storage account

can you please explain why you need this?


normally, `https://<service-name>.developer.azure-api.net` should be enough https://learn.microsoft.com/en-us/azure/api-management/developer-portal-self-host#step-2-configure-json-files-static-website-and-cors-settings

**Comment by jan-mrm** [comment]
Thanks for bearing with me :)
I just went though it all again. The Api-Management Service itself does not know where the self-hosted portal files are, right? So looking at step 7 (https://learn.microsoft.com/en-us/azure/api-management/developer-portal-self-host#step-7-go-to-your-website) the second URL needed is for actually accessing the portal, or am I missing something? So the "Primary endpoint" from the Storage accounts "Static website"? (Or some CNAME / custom domain / routing for it)

**Comment by ygrik** [comment]
Yes, the API management service itself does not know where the self-hosted portal files are.
For self-hosted portal you host your developer portal anywhere on any custom domain (like any-portal.com) and reference the API management developer portal as a backend to get authorization servers (your backend for your self-hosted portal is <service-name>.developer.azure-api.net).

**Comment by jan-mrm** [comment]
thank you @malincrist and @ygrik , that clarified it for me
