### ISSUE TITLE
Publishing APIM Developer portal fails due to sign in and sign up widget

### ISSUE THREAD

**Issue by oscarbm1998** [Azure/api-management-developer-portal#2318]
## Bug description

When trying to publish a developer portal created in APIM, it will end up as failed every time. After some debugging i figured out that if you remove the sign-in widget and sign-up widget from the developer portal design, the error subsides and you are allowed to publish the portal.

## Reproduction steps

1. Go to an APIM instance
2. Try to open the developer portal
3. Press F12 to capture API requests
4. See the error described below appear
5. Try to remove the sign in base page widget and the sign up base page widget
6. See that the error subsides

## Expected behavior

When publishing the developer portal, it should be published without errors.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Tested from Linux VM
 - Browser: Firefox, Safari and Chrome
 - Version: [e.g., 22]

### The error that is thrown when trying to add the sign-in widget:
The developer portal keeps throwing this exception when going to signin page and signup page:
Uncaught (in promise)
Object { code: "MissingOrIncorrectVersionParameter", message: "API version query parameter is not specified or was specified incorrectly.  Supported versions: 2021-04-01-preview,2021-08-01,2021-12-01-preview,2022-04-01-preview,2022-08-01,2022-09-01-preview,2023-03-01-preview,2023-05-01-preview,2023-09-01-preview  Example query param format: api-version=SupportedVersion", details: null } 

### The API call which is sent to produce the error above:
GET
https://bnnweapimdev-test.management.azure-api.net/subscriptions/000/resourceGroups/000/providers/Microsoft.ApiManagement/service/bnnweapimdev-test/tenant/settings?api-version=2019-12-01
[HTTP/1.1 400 Bad Request 16ms]

**Comment by malincrist** [comment]
Hello @oscarbm1998 , the error you are getting indicates that your instance has set a "minApiVersion" that is bigger than `2019-12-01`, which the developer portal uses for some requests for the sign in and signup widgets.

I created an internal work item to address this issue. In the meantime, a possible workaround is to set the minApiVersion to `2019-12-01`

**Comment by idarb-oss** [comment]
@malincrist so APIM has retired all older versions since September and I guess the portal should follow the same retirement directions.

https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023
