### ISSUE TITLE
rate-limit-by-key

### ISSUE THREAD

**Issue by Yavari** [Azure/api-management-developer-portal#2319]
Rate limit is not working as expected and I have tested it several times now. It is only taking the first number in calls into account. So the rate limit below is limiting the calls to 1 per 300 seconds, same for calls="111",  while calls="21" is limiting it to 2. How do I get in contact with someone at Azure troubleshoot this?
```
<policies>
    <inbound>
        <base />
        <rate-limit-by-key calls="11" renewal-period="300" counter-key="@(context.Subscription?.Key ?? "anonymous")" />
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>
`

**Comment by malincrist** [comment]
Hello @Yavari , please contact Azure support for assistance with this issue. You can do so by navigating to you APIM instance and go under Help ->  Support + Troubleshooting
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/18df481c-920b-4ba7-b7d8-b22c4adc13b6)

**Comment by Yavari** [comment]
Thanks
