### ISSUE TITLE
No user feedback on incorrect credentials when sign in ia Basic form

### ISSUE THREAD

**Issue by henrik-edlund** [Azure/api-management-developer-portal#2322]
## Bug description

The "SIGN-IN FORM BASIC" does not provice feedback to the user about sign in errors:

- No message on user not existing.
- No message on incorrect password.

The GET call _https://{serviceurl}/subscriptions/000/resourceGroups/000/providers/Microsoft.ApiManagement/service/{servicename}/identity?api-version=2021-04-01-preview-preview_ fails with 401 Unauthorized, which can be seen in Console and Network tabs of the browser. 

## Reproduction steps

1. Go to the page with the sign in form.
2. Provide a valid email adress of a non-existing user.
3. Press the "Sign In" button.
4. The Sign In button is disabled for a second. No error or feedback is shown to the user. 

## Expected behavior

A message "Incorrect Credentials" or red visual highligting of the Email and Password Fields is shown.

## Is your portal managed or self-hosted?

Managed

## Environment
**Chrome**
 - Operating system: Windows 10
 - Browser: Google Chrome , Firefox 115.3.1esr, Microsoft Edge for Business 118.0.2088.61
 - Version: 118.0.5993.89

**Firefox**
 - Operating system: Windows 10
 - Browser: Firefox 
 - Version: 115.3.1esr

 - Operating system: Windows 10
 - BrowserMicrosoft Edge for Business 
 - Version: 118.0.2088.61

## Additional context

**Screenshot:**
**![Sign in no feedback](https://github.com/Azure/api-management-developer-portal/assets/92913617/53cde64d-3064-488d-8bbf-0b32cbebedb4)**
(In the image  the "SIGN-IN FORM BASIC" is inside a card, but this placement does not matter.)

The styling of the fields Form Controls - Text box is left unchanged/inherited for error. Red error box is correctly shown for invalid email format.

**Comment by malincrist** [comment]
Hello @henrik-edlund , thanks for reaching out.
The signin widget does not show the error details by default. However, you can add a the widget "Validation Summary" on the same page you have the signin widget, that will display the errors at runtime (as seen in the below screenshot).
<image width="500px" src="https://github.com/Azure/api-management-developer-portal/assets/92857141/7f362505-dc8f-4586-bbc8-931861f52814">
