### ISSUE TITLE
Cell text truncated because there is no wrap when using "oneof"

### ISSUE THREAD

**Issue by josealbertocoronado** [Azure/api-management-developer-portal#2326]
## Bug description
When using "oneof" in yaml for an object, if the list of elements is long it gets truncated because the cell style has no wrapping. 

## Reproduction steps
1. Go to resource https://ig-weu-dev-integration-apim.developer.azure-api.net/
2.Go to "Inbound-Outbound API - v2.0"
3. Scroll down to `multiTypePayload` object
4. See "OneOf" cell is truncated so not all elements show up:
![image](https://github.com/Azure/api-management-developer-portal/assets/132665924/97339adb-3f03-4df1-ba67-cb0d679482f7)

## Expected behavior
The content is wrapped so it can be visualized entirely (maybe adding ".text-truncate { white-space: unset !important; }" ?)

## Is your portal managed or self-hosted?
Managed

## API Management service name
ig-weu-dev-integration-apim

## Environment
 - Operating system:Win 11
 - Browser: Both Edge and Chrome

**Comment by malincrist** [comment]
Hello @josealbertocoronado , thanks for reporting this issue. We have created an internal work item to address this and we will keep you updated on the progress.

**Comment by josealbertocoronado** [comment]
Lovely. Thanks for that.

**Comment by josealbertocoronado** [comment]
Hi @malincrist.
Any ETA for this? Even when it looks a minor issue is a bit blocking, as users can click the links and therefore they can't easily navigate to the desired object.

**Comment by josealbertocoronado** [comment]
Hi @malincrist .
Sorry chasing, is there any plan to release a fix for this issue soon?
Cheers.

**Comment by josealbertocoronado** [comment]
Hi @jsorohova .
I see this ticket has been completed now but if I check my resource I still can see the old behaviour.
Is it maybe not deployed yet?
Cheers.
