### ISSUE TITLE
Logo overlaps left menu when scrolling down

### ISSUE THREAD

**Issue by josealbertocoronado** [Azure/api-management-developer-portal#2327]
## Bug description
Logo on the top left cornert overlaps the menu when scrolling down.

## Reproduction steps

1. Go to https://ig-weu-dev-integration-apim.developer.azure-api.net/.
2 Go to APIs and select "Inbound-Outbound API - v2.0" (same with others)
3. Scroll down.
4. See overlap:
![image](https://github.com/Azure/api-management-developer-portal/assets/132665924/80e5f6d6-b45a-497c-ae71-85380729c941)

## Expected behavior
Menu shows below the logo without overlapping.

## Is your portal managed or self-hosted?
Managed

## API Management service name
ig-weu-dev-integration-apim

 - Operating system: Windows 11
 - Browser: Edge and Chrome

**Comment by malincrist** [comment]
Hello @josealbertocoronado , 
I checked your portal and it seems you have `position: sticky` for the section that contains the logo. I believe tis is what is causing the unwanted behavior you are describing.

To remove it, you can go to the section editor and set "stick to" to "none". This should resolve your issue. 

![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/1c309060-de2f-4b9d-bccf-3701a1beb0e0)

**Comment by josealbertocoronado** [comment]
Hi @malincrist .
Thanks for the quick answer.
I'm sure I'm being dumb and missing something but I can't find that `Miscellaneous` option anywhere.
Neither editing the picture:
![image](https://github.com/Azure/api-management-developer-portal/assets/132665924/532b67ed-941c-4ffc-80f1-9aa81eab8aa4)

Or the article that contains it:
![image](https://github.com/Azure/api-management-developer-portal/assets/132665924/56d8bb8d-1869-4b2b-b0b1-8a1842b8d084)

Am I looking in the wrong place?
Cheers.

**Comment by malincrist** [comment]
@josealbertocoronado , it should be in the `section` that contains the `article`. You can open the editor if you select the article, then click the "arrow up" button 
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/8a9c45d5-9325-4a50-a81b-8f5af0b5e30a)
this will "focus" on the section, and from there, you should be able to click on "Edit section":
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/dbb8d0fb-81ea-40b6-8248-96d8d3c0152e)
