### ISSUE TITLE
Ability to manually update CSS 

### ISSUE THREAD

**Issue by josealbertocoronado** [Azure/api-management-developer-portal#2328]
The current styles editor gives a quite limited experience. It's ok for quite basic changes but not good enough for bigger ones.
Having the ability to update CSS manually would give a huge flexibility and would convert the developer portal into a much more powerful tool.
Is that a feature that can be added somehow?

**Comment by malincrist** [comment]
Hi @josealbertocoronado , thanks for reaching out.

We do not have in plan to introduce updating CSS manually. However, we are working on introducing more customizations for elements inside widgets: #2132 
Hopefully, this will give you the flexibility that you need. 🙂

**Comment by josealbertocoronado** [comment]
Ok. Thanks for the update.

**Comment by sthirthala** [comment]
Closing the issue as it is resolved
