### ISSUE TITLE
Test Console > OAuth 2.0 Authorization Code Authorization > "Unable to authenticate due to internal error."

### ISSUE THREAD

**Issue by Blackbaud-ChristopherRodgers** [Azure/api-management-developer-portal#2334]
## Bug description

A customer reached out to us that they are receiving an error from the Test Console when they attempt to authorize (OAuth 2.0 Authorization Code Flow) the test console application. The error alert says "Unable to authenticate due to internal error."

![ErrorAlert2](https://github.com/Azure/api-management-developer-portal/assets/5169197/b6d6e458-a2cc-44c0-b5d3-511b1e50992c)

Looking at the [block of portal code](https://github.com/Azure/api-management-developer-portal/blob/e3e9957d56c7af656c3ef8bf31263debbfe012ad/src/services/oauthService.ts#L179) that raises this alert, it would seem that the portal is receiving an unexpected message.

When trying to reproduce this ourselves, the only scenario where we regularly got this to happen is when we enabled a browser extension (for us, it was the Microsoft Editor extension--Microsoft Edge).

This was the message event that resulted in the error.
![Screenshot 2023-11-22 101816](https://github.com/Azure/api-management-developer-portal/assets/5169197/10e3a309-583c-41cb-a523-e219e0403485)

When things are working correctly, this is the expected event shape:
![ProperMessage](https://github.com/Azure/api-management-developer-portal/assets/5169197/5ea649ed-4929-4245-b8a0-dd290aaed1bb)

## Reproduction steps

1. Install and enable browser extension (Microsoft Editor for Edge seems to do it)
2. Go to API Reference for API with OAuth 2.0 with Authorization Code (I believe this would also happen for Authorization Code w/PKCE)
3. Click on "Try it"
4. Update OAuth 2.0 Authorization from "No auth" to "authorization_code"
5. The error alert will often be raised as authorization is given and the window is closed after the redirect. However, it occasionally happens while the user is sitting on the page after the window is closed (maybe because [the listener](https://github.com/Azure/api-management-developer-portal/blob/e3e9957d56c7af656c3ef8bf31263debbfe012ad/src/services/oauthService.ts#L188C17-L188C75) is still active and the extension is running some operation on the page?

## Expected behavior

The test console receives an access token without an error. FWIW, in our testing, the access token event is also received, so the Authorization header is populated. The error simply leads some users to believe it didn't work. Ideally, the portal event listener would ignore this unexpected event.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

2.24.0

## API Management service name

bbapiprod

## Environment

 - Operating system: Windows 11
 - Browser: Edge
 - Version: 119.0.2151.72

**Comment by gs11** [comment]
I can confirm that disabling React Developer Tools in Firefox resolves the issue for me as well.

**Comment by JakubHolovsky** [comment]
I am having the same issue on Edge however I don't have react tools installed. These are the only extensions enabled in my browser:

![image](https://github.com/Azure/api-management-developer-portal/assets/4558405/17a61cc7-6920-4c16-a132-a3ef482d513f)

**Comment by sthirthala** [comment]
Please log managed portal issues to Azure support team using Support + Help link in Azure portal and select Problem Type = Developer portal.

**Comment by KrisFrost** [comment]
Update:  This does not look to be a Developer portal issue but rather injected extension code triggering an event listener created for the scenario of Authorization such as with Try It.

The developer portal code for the authentication registers an event listener receiveMessage.

` return new Promise(((resolve,reject)=>{
                            try {
                                window.open(oauthClient.code.getUri(), "_blank", "width=400,height=500");
                                const receiveMessage = event=>__awaiter(this, void 0, void 0, (function*() {
                                    if (!event.data.accessToken)
                                        return void alert("Unable to authenticate due to internal error.");
                                    const accessToken = event.data.accessToken
                                      , accessTokenType = event.data.accessTokenType;
                                    resolve(`${utils_1.Utils.toTitleCase(accessTokenType)} ${accessToken}`)
                                }
                                ));
                                window.addEventListener("message", receiveMessage, !1)
                            } catch (error) {
                                reject(error)
                            }
                        }`

Setting a break point here, and then stepping through, the code triggering these event is coming from content.js from editor extension in this case.  Other extensions can be debugged the same way.

For the editor extension, what appears to be doing is a grammar check on the drop-down box for either the Authorization flow dropdown or the Subscription key drop down or all of them.

It's triggering the dev portals receiveMessage eventlistener.  I did find I could go into the settings and changed "This can read and change site data" to When you click the extension.  This prevents the issue as well.
