### ISSUE TITLE
Add GraphQL operation names in Analytics Operations tab.

### ISSUE THREAD

**Issue by MarcoFuykschot** [Azure/api-management-developer-portal#2339]
For REST apis all operations are visible in the Analytics -> OperationTab,  for graphql the operation name is dynamic in the request present , It would be great to have is out of the box instead of using policy to trace/metric this in the application insights.

Nice output would be:
```
Query:  <operationname>   ...... metrics .....
Mutation: <operationname> ....metrics .....
Subscription:  <operationname> .....metrics....
```

if operation is null or missing a default could be used.

The current default is  _&lt;api-name>;rev=1 - default_  in application insights.

**Comment by malincrist** [comment]
hello @MarcoFuykschot , this issue doesn't seem to be specific to developer portal.
Please contact Azure support for assistance.
