### ISSUE TITLE
Developer Portal: response schema for built-in types shows incorrect, autogenerated name

### ISSUE THREAD

**Issue by nweseloh** [Azure/api-management-developer-portal#2342]
## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. import an OpenAPI operation like this (abbreviated): 

```
paths:
/countries:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

components:
  schemas:
    Country:
      type: object
      properties:
        code:
          type: string
```

2. select the operation in the developer portal
3. see that the response type has a weird auto-generated name  "CountriesGet200ApplicationJsonResponse": 
![image](https://github.com/Azure/api-management-developer-portal/assets/1902260/90474b0f-630e-410d-a5ac-ceca4ae0815e)

This happens for *all* response types that are built-in OpenAPI types, e.g.: 

- array
- number
- string

## Expected behavior

The response type should be "Country[]", similar to an operation that returns a single custom schema object. 

## Is your portal managed or self-hosted?

Managed

**Comment by malincrist** [comment]
Hello @nweseloh , this issue doesn't seem to be specific to developer portal.
Please contact Azure support for assistance.

**Comment by petulal** [comment]
Hi @nweseloh , I have this exact same problem - did you get a solution for it from Support? Thank you so much for your help in advance.
