### ISSUE TITLE
[BUG] Workspace operations with definition/representation are not loaded

### ISSUE THREAD

**Issue by rbickel** [Azure/api-management-developer-portal#2347]
## Bug description

When a workspace API operation has definitions attached to it, the developer portal operation doesn't load. We can see that the call to retrieve the schema for the operation definitions fails and return a 404.

## Reproduction steps

1. Create a workspace, an API and an operation
2. Attach a definition to the operation 200 OK response
3. Open the developer portal and navigate to the workspace API and operation above

## Expected behavior

Operation should load in the developer portal

## Is your portal managed or self-hosted?

Managed

## API Management service name

rbklapim

## Environment

Any browser

## Additional context

The screenshot below is when accessing an API from a workspace. The operation has a 'Pet' definition attached to it. You can see the request trying to retrieve the schema failing with a 404 error code.

![image](https://github.com/Azure/api-management-developer-portal/assets/11852796/0e48301c-9abe-471f-b1d6-4a9bb7786c1c)

**Comment by malincrist** [comment]
Hello @rbickel , thank you for reporting the issue. I was able to reproduce it locally and it is indeed a bug from our side. I have created an internal work item to investigate this further and we will keep you updated on the progress. Apologies for the inconveniences created.

**Comment by rubenaster** [comment]
@malincrist what's the current status here? We have several clients that already migrate to Workspaces but have this bug as a huge barrier.

**Comment by malincrist** [comment]
The fix has been deployed everywhere. Closing the issue.
