### ISSUE TITLE
APIM administrator can't log in to the developer portal

### ISSUE THREAD

**Issue by Shafeeqts89** [Azure/api-management-developer-portal#2351]
The administrator user cannot log in to the developer portal despite entering the correct credentials. The error message "Please provide a valid email and password" keeps appearing.

![image](https://github.com/Azure/api-management-developer-portal/assets/60779307/0f79073d-cd78-4405-8659-f8f9bb491a96)
It was working fine until I enable the Azure AD sign-in. I have tried removing the azure AD user, but now I can't login with either of the login method. Azure AD sign-in shows a server error.
![image](https://github.com/Azure/api-management-developer-portal/assets/60779307/5e7ea167-42bd-4c06-ad35-05cc60b6a928)

Here is what I can see in the logs
![image](https://github.com/Azure/api-management-developer-portal/assets/60779307/74995c19-bc7c-4f86-bb57-005dc708410c)

**Comment by fpdutra** [comment]
Are you using Self-Hosted Portal?

**Comment by Shafeeqts89** [comment]
> Are you using Self-Hosted Portal?

No, It is the azure managed portal.

**Comment by sthirthala** [comment]
For managed portal, please create a support request in Azure help+support. 

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
