### ISSUE TITLE
"Try it"-button in Developer Portal modifies XML payload 

### ISSUE THREAD

**Issue by schteffy** [Azure/api-management-developer-portal#2353]
## Bug description

When using the `Try me`-button to test a POST-request in the developer portal, the XML used as payload is inserted into some JSON object before it is being sent. Consequently, the `Content-Type` is forcefully modified from `application/xml` to `application/json`. This leads to an issue where the server is unable to process the request.

I tried making the request using Postman, and it worked as expected. It seems that there might be some unusual processes or actions happening in the developer portal that are causing the problem.

The issue seems to only affect APIs defined with `XML` as the `Content-Type`, not `JSON`.

## Reproduction steps

1. Go to any API
2. Click on 'Try Me'
3. Ensure a valid Subscription key is selected
4. Scroll down, and click `Send`
5. The bug appears, and the server is not able to handle the request

## Expected behavior

I expect the `Try it`-functionality to send the request exactly as specified in the API, without making any modifications to the payload before sending it.

## Is your portal managed or self-hosted?

Managed

## Environment

Tested using the following two setups:

### Setup 1

 - Operating system: macOS
 - Browser: Google Chrome

### Setup 2

 - Operating system: Windows
 - Browser: Microsoft Edge

### What is specified to be sent:
![image](https://github.com/Azure/api-management-developer-portal/assets/113780583/fd94cc4f-c4c2-4414-a96b-081031ffcf93)

### What is actually being sent

![image](https://github.com/Azure/api-management-developer-portal/assets/113780583/83b2f979-e8df-408f-8010-9ec15234eaa0)

**Comment by malincrist** [comment]
Hello @schteffy , thanks for reaching out.
Unfortunately, I was not able to reproduce the issue you described. Can you please share your instance name and the API with the issue, so we ca investigate this further? Feel free to send them to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com)
