### ISSUE TITLE
Managed Developer Portal can't be Published

### ISSUE THREAD

**Issue by cgorman-cu** [Azure/api-management-developer-portal#2355]
## Bug description

When the new feature of "Popups" was added to the developer portal, I tried to implement one popup, and the Popup worked in the developer portal editor mode. However, when I went to publish it then I kept getting an error stating that it failed to publish the latest revision.

I have no idea what has caused this because it was fine 12/6/2023 but now it isn't working on 12/11/2023.
I looked into this and I had to "reset content" inside the "Operations" tab in the editor bar menu on the left.
That fixed the error, but I had to go back into the Dev Portal and manually customize it again.

This is the second time this has happened, so I am not sure what is happening.

Also, I was seeing a lot of other unexpected behavior such as Custom Widgets not updating when you run "npm run deploy".

I think the problem is that any updates I am trying to push to Azure don't get implemented, but I don't know the reason for that.
## Reproduction steps

1. Go to 'Popups' on the left navigation bar
2. Click on 'Popups'
3. Click on "+ Add popup'
4. Save 
5. Try to publish using the Azure APIM page in "Developer portal" section or click on "Publish website"

## Expected behavior

You will be unable to publish the dev-portal that you just saved.
If you delete all Popups then you can publish the dev-portal.

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

2022-08-01

## API Management service name

NX-APIM-Service

## Environment

 - Operating system: Windows 10
 - Browser: Edge
 - Version: 2.24

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by malincrist** [comment]
Hi @cgorman-cu , thanks for reaching out!

I tried to reproduce the issue with the popup, but publishing doesn't fail for me, as you described.

Based on our telemetry, I can see indeed one error that happened repeatedly for the service you mentioned, during publishing (on 12/11), but it doesn't seem to be related to popups (TypeError: Cannot set properties of undefined (setting 'type') at exports.LayoutService.<anonymous>). 

I can see in the snapshots created on 12/11, that there is a layout present in the snapshot but no content associated to it. I'm not sure how this could've happened, and it is pretty hard to figure it out, as the content of the portal was reset.
I tried to reproduce it locally with the same content for the layout mentioned, but with no luck.

If it happens again, please let us know, and if possible, please don't reset the content so we can investigate based on it. Thanks!

**Comment by sthirthala** [comment]
For managed portal, please create a support request using azure help and support center

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
