### ISSUE TITLE
API Management didn't recognize non Encoded request path parameter

### ISSUE THREAD

**Issue by madpearl** [Azure/api-management-developer-portal#2358]
## Bug description

API Management makes a difference between encoded request path and non encoded. The client is outside the Azure.

Operation:

POST /{rpm_rpm_repository_href}sync/
with 

```
                "tags": ["Repositories: Rpm"],
                "summary": "Sync from remote",
```

Curl request with `pulp%2Fapi%2Fv3%2Frepositories%2Frpm%2Frpm%2F018c3953-421e-77fc-86e4-81dc13f2433c%2Fsync/` will be proceed correctly . 
```
"backend": [
      {
        "source": "forward-request",
        "timestamp": "2023-12-13T11:37:39.8748786Z",
        "elapsed": "00:00:00.0004509",
        "data": {
          "message": "Request is being forwarded to the backend service. Timeout set to 300 seconds",
```
Curl request with `pulp/api/v3/repositories/rpm/rpm/018c3953-421e-77fc-86e4-81dc13f2433c/sync/` return `{ "statusCode": 404, "message": "Resource not found" }`

```
    "backend": [
      {
        "source": "configuration",
        "timestamp": "2023-12-13T11:23:16.1765318Z",
        "elapsed": "00:00:00.0003261",
        "data": {
          "message": "Unable to identify Api or Operation for this request. Responding to the caller with 404 Resource Not Found."
        }
      }
    ],
```

## Expected behavior

Both requests are equal and should be processed without 404 Error

## Is your portal managed or self-hosted?

Managed 

## API Management service name

[ **apiservicepulp** ]
API "Pulp 3 API v3.41.1"

## Environment

 - CURL

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by malincrist** [comment]
Hello @madpearl , this issue doesn't seem to be specific to developer portal.
Please contact Azure support for assistance.

**Comment by madpearl** [comment]
The problem was solved! API operations was wrong defined!
