### ISSUE TITLE
All "Custom HTML code" widget cannot be displayed after developer portal update 

### ISSUE THREAD

**Issue by marcoyfkwok** [Azure/api-management-developer-portal#2369]
All HTML widgets suddenly cannot be displayed in my portal.
It is related to the portal software update?

Version 0.41.17088.0
![image](https://github.com/Azure/api-management-developer-portal/assets/8841524/d1bf39fe-1c26-4bf5-8659-5aa808757861)

**Comment by malincrist** [comment]
Hello @marcoyfkwok, @lbonnet34, thank you for reporting this issue.
We have identified the issue and created  PR with a fix, that will be shipped with the next release. ETA for the next release is 1-2 weeks.
Apologies for the inconveniences created.
