### ISSUE TITLE
Email templates are still showing old developer portal link

### ISSUE THREAD

**Issue by manjunathp-jm** [Azure/api-management-developer-portal#2372]
## Email notifications are outdated

Body of email templates still shows link to "Issues" and "Application Gallery" . These features seems have been deprecated in new developer portal and link are not working. Event product link are not updated

<img width="358" alt="image" src="https://github.com/Azure/api-management-developer-portal/assets/143175290/97138b66-e3e5-4c86-aa7a-43700faeafc0">

## Reproduction steps

1. Go to APIM in azure
2. Add user to a product
3. validate emails notification
4. see the attached screenshot.

## Expected behavior

Feature of reporting "issues" and "application gallery" are removed. so the email should show valid links of new developer portal

## Is your portal managed or self-hosted?

Managed

**Comment by malincrist** [comment]
Hello @manjunathp-jm , thank you for reaching out!
You can edit the email template from the Azure Portal interface: under Deployment + infrastructure, click on "Notification templates". From here you can edit the template to point to correct links or remove unnecessary ones.
<img width="204" alt="image" src="https://github.com/Azure/api-management-developer-portal/assets/92857141/4dcd87ea-f3e8-46ab-9fba-e8f2c235cf02">

**Comment by manjunathp-jm** [comment]
@malincrist Thank you the suggesting option to edit notification templates which I'm already aware. The point here is default notification templates offered in API management is not aligned towards new developer portal. 

The default notification templates offered as part of APIM should be operational and is not. Links are broken for "Profile area" "issues" etc.

Note - We have already corrected in our landscape.

**Comment by malincrist** [comment]
@manjunathp-jm , thank you for the clarification. That makes sense and I agree that the default templates should align with the new dev portal. I have created an internal work item for us to address this issue. 
Thanks for reporting it!

**Comment by sthirthala** [comment]
For managed portal, please create a support request using azure help and support center

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
