### ISSUE TITLE
Developer Portal Customizations

### ISSUE THREAD

**Issue by azep-ninja** [Azure/api-management-developer-portal#2379]
## Bug description

All of the widgets within the dev portal default to certain color schemes, making them unusable. There is the Pull request that seems to have been ready but not pushed for over a year, which would resolve this issue.

https://github.com/Azure/api-management-developer-portal/pull/2132

## Reproduction steps

1. Go to developer portal customization.
2. Change color schemes to dark colors
3. Test the pop out widget for "Try It" and light colors will be applied making it unusable.

## Expected behavior

Theme should apply to all components, or at least make each component themeable.

## Is your portal managed or self-hosted?

Managed

**Comment by malincrist** [comment]
We are tracking this under #1213. Closing this one.
