### ISSUE TITLE
Feature request: allow selection of template data

### ISSUE THREAD

**Issue by molinch** [Azure/api-management-developer-portal#238]
APIM developer portal would be fully templatable if it was possible to choose the data which goes into portal template data. Currently this seems hardcoded.

It would allow much richer interactions, like having a single page where you see the APIs, and their operations. Furthermore you could select data which you don't have today, like if the operation is deprecated. This is part of OpenAPI but not available in data yet.
Last the data could be easier to use, really shaped like what it is. For example:
```javascript
{
   apis: [
   {
      name: 'basket',
      otherProperties: ...,
      operations: [
         {
            name: 'Add to basket',
            otherProperties: ...,
            isDeprecated: true,
            flags: [ 'preview' ]
         },
         {
            name: 'Remove from basket',
            otherProperties: ...,
         }
      ]
   }
]
```

**Comment by mikebudzynski** [comment]
@molinch Thanks for your feedback. The developer portal combines portal-specific data and APIM-specific data (like APIs or Products). In your example, the list of API operations is retrieved through an API Management REST API.

If you'd like to vote on the deprecation feature, you can do it here: https://feedback.azure.com/forums/248703-api-management/suggestions/6684898-mark-api-operations-as-obsolete-deprecated

Also, per our guidelines in the readme document, please open feature requests at https://aka.ms/apimwish - not here.

**Comment by molinch** [comment]
Thanks for the feedback @mikebudzynski 
I understand that feature request shouldn't be here. Just two remarks.

Regarding deprecation feature, well you could argue that it's an issue not a feature. Seems APIM claims it supports OpenApi3 documents and it is part of OpenAPI3...

The struggle with the template data is real, right now you can't design pages the way you would like them to be. I don't think you understood the underlying issue: some pages offer some data, but no pages offers the right amount of data.
Maybe page A gives something, page B another thing, page C another thing, but what you are interested to build your page is data from A+B+C.

**Comment by mikebudzynski** [comment]
There are limitations in how API Management supports OpenAPI and deprecation is one of them. It is on our roadmap to look into how we can provide support for deprecation.

Could please give a particular example how you want to combine the data? What would A, B, and C be in this case?
