### ISSUE TITLE
Default query params values appearing in the APIM-Developer portal drop down option

### ISSUE THREAD

**Issue by rnaveen5** [Azure/api-management-developer-portal#2384]
## Bug description

In the Azure APIM , the Front end settings 's Query parameter shows ups value by default.

## Expected behavior

The dropdown box in the "Try it" query params section does not show any option by default

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows
 - Browser: Edge

![image](https://github.com/Azure/api-management-developer-portal/assets/80045043/c9dbbe33-5db5-4770-aba4-558f45f3be5d)

**Comment by malincrist** [comment]
Hi @rnaveen5 , thank you for reaching out!
I'm not sure I understand what you mean. From Azure Portal, you can select a query param to be the default value, such as:
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/2a6c3636-a896-493b-bd11-4a18671d6572)

Then, in developer portal, this value will be selected by default:
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/e88da75a-e9f4-4b26-871c-7328b22e5326)

Can you please clarify what issue you are experiencing? Is this behavior not working as expected for you or did I misunderstand the description of the issue?

**Comment by rnaveen5** [comment]
Hi @malincrist 
we have an Enum field as a query parameter in the specification and it marked with no default values.

![image](https://github.com/Azure/api-management-developer-portal/assets/80045043/88a7a74e-d447-4de8-b3b5-24286b997a1b)

It even shows the values in the Developer portal which actual should appear by default as empty.

![image](https://github.com/Azure/api-management-developer-portal/assets/80045043/e4f7a432-63e3-4542-baf8-54bbfb543abb)

The reason being , this value gets added to the call even without the user selecting the value.

**Comment by malincrist** [comment]
oh, I got it now, dev portal populates enums even if "no default" is selected. Thanks for the clarification!
I have created an internal work item for us to address this. Thanks for reporting it.

**Comment by rnaveen5** [comment]
Hi @malincrist , Just following up . Any idea on the ETA.

**Comment by sthirthala** [comment]
For managed portal, please create a support request using azure help and support center

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by rnaveen5** [comment]
The  fix release got postponed again to 2-3 Weeks from MSFT
