### ISSUE TITLE
Managed portal favicon not loading

### ISSUE THREAD

**Issue by GiuseppeColosi** [Azure/api-management-developer-portal#2388]
## Bug description

Bug description
Similar to [2153](https://github.com/Azure/api-management-developer-portal/issues/2153), the favicon is no longer being loaded. It does not show up in the network tab of the developer tools at all. While I am getting some error messages (CORS error for two of six fonts) none seem to have to do with the favicon.

## Reproduction steps

1. Set up favicon
![image](https://github.com/Azure/api-management-developer-portal/assets/34469934/3ed167a3-e9be-44c0-b93e-d25f5db6b103)

2. Save and publish portal

3. Open portal in incognito tab
Favicon is missing
![image](https://github.com/Azure/api-management-developer-portal/assets/34469934/8ac09859-f3bc-4fbf-bb33-5f90bbbbdb19)

## Expected behavior

Would expect the favicon to show up

## Is your portal managed or self-hosted?

Managed

## API Management service name
apimbfweu

## Environment

 - Operating system: [iOS, last version]
 - Browser: [Google Chrome, last version]

**Comment by malincrist** [comment]
Hello @GiuseppeColosi , thank you for reaching out!
I am not able to reproduce the issue you described. I also opened your developer portal, and the fav icon appears. Could you please check if it is working now?

**Comment by GiuseppeColosi** [comment]
Hello @malincrist, thank you for the check you have done.
I'm sorry to inform you that the issue persists.
You can see in the image below that the favicon is not displayed.
 
<img width="454" alt="image" src="https://github.com/Azure/api-management-developer-portal/assets/34469934/9b08ef9e-52ad-4295-ac2e-3f9c650e9b2e">

If I select the icon in development mode, it appears but disappears after saving and publishing.

<img width="358" alt="image" src="https://github.com/Azure/api-management-developer-portal/assets/34469934/77404b7d-fa2b-48f4-ab0f-13f5a8d641d2">

It seems that the old favicon.ico file is still being displayed, indicating that the new one has not been deployed.

<img width="661" alt="image" src="https://github.com/Azure/api-management-developer-portal/assets/34469934/72317cd3-d73e-49fd-8e8f-767c5b58814b">

many thanks,
Giuseppe

**Comment by sthirthala** [comment]
For managed portal, please create a support request using azure help and support center

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
