### ISSUE TITLE
Create Custom Widgets on the Managed Portal without iframe. 

### ISSUE THREAD

**Issue by sandeep859** [Azure/api-management-developer-portal#2398]
We are creating a Custom Widget for SignUp and SignIn button, and we need to use them with the managed portal. We followed this [document ]( https://learn.microsoft.com/en-us/azure/api-management/developer-portal-extend-custom-functionality#create-and-upload-custom-widget )for the custom widget.

 On the click of the widget button, the user should be redirected to the Azure B2C login or Sign-up page. We are using MSAL library for the redirect flow. Since custom widget is created as iFrame, we are getting this error on the click of sign-in or sign-up buttons: 

> Refused to display 'https://xxxxxxxxxxxxxxxx.b2clogin.com/' in a frame because it set 'X-Frame-Options' to 'deny

Screen shot shown at the end.

 **Is it possible to create a widget without iFrame option so that when we click on the buttons, B2C login page opens in the entire window instead of iFrame?**

Note: We are migrating from self hosted developer portal to managed developer portal. We didn't see this issue when we added widgets in the self hosted developer portal and we had been using them for 2 years. 
We cannot use in-built signIn and signUp buttons due to custom workflow. 

![image](https://github.com/Azure/api-management-developer-portal/assets/8977786/639f9097-ae6f-4d60-9a67-57594bcabd37)

**Comment by JMach1** [comment]
Hello @sandeep859 
as of right now, we don't allow users to inject code to the Developer Portal directly. Only using iframes for security reasons.
We're exploring options how this could be done but this functionality is not ready for now.

**Comment by sthirthala** [comment]
For managed portal, please create a support request using azure help and support center

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
