### ISSUE TITLE
Add Sign-up Button for Oauth in the In-Built Widgets

### ISSUE THREAD

**Issue by sandeep859** [Azure/api-management-developer-portal#2400]
We are using Azure Managed Developer portal. We are using Custom Azure B2C policy for Sign-in and Sign-up process,  and for the Sign-In we are able to use in-built widget `Sign-in Button: Oauth` for user Sign-In. But for Sign-Up, there is no in-built button. Due to this we have to create a custom widget for the Sign-up button which takes user to the Sign-up page according to Azure B2C policy.

It is suggested to have `Sign-up Button: Oauth` as well so that we dont have to create a Custom widget handle this use case.

We looked into the code and found that we just need to reuse the runAadB2CUserFlow function in aadService class . Only thing different for the Sign-up process would be userFlow i.e B2C_1_signup in Sign-up case.

**Comment by JMach1** [comment]
We are providing a "Sign-up form: OAuth" widget, which in the default content is already used in the /signup-oauth page. If I understood you ask right, you can just create a button where you want it and set it to navigate to the /signup-oauth page.

**Comment by sthirthala** [comment]
For managed portal, please create a support request using azure help and support center

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
