### ISSUE TITLE
My homepage is not loading in a proper way

### ISSUE THREAD

**Issue by vijayaragavanInterIkea** [Azure/api-management-developer-portal#2405]
##In my customized developer portal, I have a home page where some of the widgets are there. My "**signatureAccessToken**" expired before two days, and then I generated a new token.But now, when I am trying to start the application in local, the homepage is not proper. 

I don't know why this is happening. Even I have not changed anything.

## Current behavior

I can't abe to see my recently customized homepage 

## Is your portal managed or self-hosted?

 Self-hosted

## API Management service name

apim-contentintegration-dev

## Environment

 - Operating system: windows 11.
 -Browser: Google Chrome.

**Comment by JMach1** [comment]
Hello @vijayaragavanInterIkea 
I checked your service and your published site and everything seems to be alright. Could you please check troubleshooting guide in the Azure Portal and if it wouldn't help, create a support request. Thank you
