### ISSUE TITLE
Unable to view custom widget on Safari - Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by heller-tobias** [Azure/api-management-developer-portal#2417]
## Bug description

Similar to #2364 there is an issue with **`Origin null`** on Safari. 

I am unable to view any custom widgets on Safari.
The fetching of the bundled JavaScript code of the custom widget fails due to a CORS error: Origin null is not allowed by Access-Control-Allow-Origin

The same widget can be viewed on any other browser, e.g. Chrome.

## Reproduction steps

1. Go to a page on your developer portal with a custom widget
2. Open Developer Tools -> Console or Network
3. See error

## Expected behavior

The custom widget should be displayed on Safari.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: [iOS]
 - Browser: [Safari]
 - Version: [17]

## Additional context

Error message in the Console:
![image](https://github.com/Azure/api-management-developer-portal/assets/57043175/45f31a00-30c1-4838-9adb-d755ada256ab)

Additional error messages regarding the sandboxed iframe might be related to the changes of #2364.

![image](https://github.com/Azure/api-management-developer-portal/assets/57043175/2054f7af-30c1-42fc-be93-e2db7c9cda32)

**Comment by maciejtreder** [comment]
Hello @heller-tobias It looks that those are the same issues; and those should be addressed with this PR:

https://github.com/Azure/api-management-developer-portal/pull/2373/files

**Comment by heller-tobias** [comment]
> Hello @heller-tobias It looks that those are the same issues; and those should be addressed with this PR:
> 
> https://github.com/Azure/api-management-developer-portal/pull/2373/files

This PR seems to be merged and is already a part of the latest release. Therefore I assume it does **not** fix this issue. Or am I mistaken?

**Comment by sthirthala** [comment]
This issue is fixed. Also, for managed portal, please create a support request in Azure support center,

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
