### ISSUE TITLE
Definition schema not show in operation details

### ISSUE THREAD

**Issue by pbychkoviak** [Azure/api-management-developer-portal#2425]
## Bug description

Definition schema not show in operation details

## Reproduction steps

1. Create new API Management service instance
2. Go to Echo API and create new definition
3. Assign this new definition to the "Create resource" operation
4. Open developer portal, select "Create resource" operation and see that the definition schema is empty

## Expected behavior
Definition schema is show

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: any browser

## Additional context

![image](https://github.com/Azure/api-management-developer-portal/assets/79475609/81113de6-5475-4a4d-9741-8f5595e70c1f)
![image](https://github.com/Azure/api-management-developer-portal/assets/79475609/ad534150-e22f-4a5c-8076-cfe3e6f0e979)
![image](https://github.com/Azure/api-management-developer-portal/assets/79475609/058dfb10-8bcb-42e7-ad53-83c7a8e6f912)

**Comment by malincrist** [comment]
hello @pbychkoviak , thanks for reaching out! 
We have a regression in the current release, that creates some issues when loading APIs' schemas. We have prepared a fix and prioritized the deployment (ETA is this week/ early next week). 
If it is urgent for you, please send your apim instance(s) name(s) to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com), so we can roll them back. 
Apologies for the inconveniences and thank you for udnerstanding!

**Comment by pbychkoviak** [comment]
Now it works. Thanks.

**Comment by malincrist** [comment]
The fix was deployed in all stages.

**Comment by MBVDK** [comment]
@malincrist we had the same issue across different environments. It seems that your deployed fix have solved it not showing the fields. Which is great, thanks. We also use a managed developer portal.

However, now we are experiencing that when changing the API from the dropdown menu, it does not change the descriptive texts in request body for OpenAPI definitions which have the same 'definition names'  the description text remains the same from the previous API. 
When changing the API using the dropdown list (1) from SP v2 to TC V2, I will still have the descriptive text of SP v2 in the main window
![image](https://github.com/Azure/api-management-developer-portal/assets/60968051/62f097d5-9091-4e68-83f8-0545aac1a687)

@pbychkoviak are you experiencing similar behavior in your environment?

**Comment by pbychkoviak** [comment]
@MBVDK no, I do not observe what you described.

**Comment by malincrist** [comment]
hi @MBVDK , thank you for reporting this new issue with definitions!
We identified the issue and fixed it. It will be shipped with the next release (ETA 1-2 weeks). In the meantime, as a workaround, you can clear the cache and the correct definitions will be loaded. Apologies for the inconveniences!
