### ISSUE TITLE
WSDL import modifies first letter of a parameter to lower case

### ISSUE THREAD

**Issue by mclausferranti** [Azure/api-management-developer-portal#2428]
## Bug description

In the WSDL there are parameters that start with an uppercase. But after importing the WSDL the first letter of the parameter is modified to a lower case.

## Reproduction steps

1. Go to APIs.
2. Click on +Add API.
3. Click on WSDL.
4. Select the attached file. ([wsdl.txt](https://github.com/Azure/api-management-developer-portal/files/14472492/wsdl.txt))
5. Select McsBillingServices - BasicHttpBinding - BillingBlockService as interface.
6. Select SOAP to Rest as import method.
7. Click on the button create.
8. Select the imported API.
9. Select 'GetBillingBlock' in all operations.
10. Select 'GetBillingBlock' in defintions.
11. In the schema you see:
![image](https://github.com/Azure/api-management-developer-portal/assets/162015524/c8be64c4-6322-4d99-9b37-ac9e2bdae06d)

In the WSDL it's 'EAN'.

![image](https://github.com/Azure/api-management-developer-portal/assets/162015524/2f74a674-88e1-4265-9dd5-c083e57cb920)

## Expected behavior
Keep the WSDL as-is and don't modify the first letter of a parameter to lower case.

## Is your portal managed or self-hosted?

Managed

## API Management service name

McsTestApiManagement

## Environment

 - Operating system: windows
 - Browser: Google Chrome

## Additional context

The WSDL is auto-generated by a Dynamics 365 Finance environment.
We're using azure API management to document the API.
We're exporting the documented APIs via yaml files.
We're sending the yaml files to one of our customers.
The tool that our customer is using, is case sensitive. And now there is a mismatch between the WSDL and the documented API.

**Comment by jsorohova** [comment]
Hello @mclausferranti, this is an issue in Azure portal and not the Developer portal. Please, contact Azure support for assistance.
