### ISSUE TITLE
Request and response sample shouldn't include operations name

### ISSUE THREAD

**Issue by mclausferranti** [Azure/api-management-developer-portal#2430]
## Bug description

After importing a WSDL, a request and response sample is added. The operations name is included in the samples. But when you execute the API, it doesn't expect the operations name.

## Reproduction steps

1. Go to APIs.
2. Click on +Add API.
3. Click on WSDL.
4. Select the attached file. ([wsdl.txt](https://github.com/Azure/api-management-developer-portal/files/14472492/wsdl.txt))
5. Select McsBillingServices - BasicHttpBinding - BillingBlockService as interface.
6. Select SOAP to Rest as import method.
7. Click on the button create.
8. Select the imported API.
9. Select 'GetBillingBlock' in all operations.
10. Open form-based editor.
11. Select sample. The operations name is included in the sample:![image](https://github.com/Azure/api-management-developer-portal/assets/162015524/3e9e09f9-4d45-4550-81fd-e2d0542d8161)
12. Select responses. The operations name & result is included in the sample:
![image](https://github.com/Azure/api-management-developer-portal/assets/162015524/c1034ada-fcc1-4adb-a1a2-806b49d60278)

## Expected behavior

The operations name and result shouldn't be included in the sample.

## Is your portal managed or self-hosted?

Managed

## API Management service name

McsTestApiManagement 

## Environment

 - Operating system: windows
 - Browser: Google Chrome

## Additional context

When you execute the API, for example in postman, the operations name isn't expected in the request:
![image](https://github.com/Azure/api-management-developer-portal/assets/162015524/7765cb5d-f51e-46ea-a251-13ebe5a0f7b0)

And there is also no operations name and result in the response.

**Comment by jsorohova** [comment]
Hello @mclausferranti, this is an issue in Azure portal and not the Developer portal. Please, contact Azure support for assistance.
