### ISSUE TITLE
URL getting redirected to /signin?returnUrl=%2F

### ISSUE THREAD

**Issue by sandeep859** [Azure/api-management-developer-portal#2432]
URL getting redirected to /signin?returnUrl=%2F

## Bug description

We are using Managed Developer portal with Custom Developer portal URL. We did design changes as well. When we try to access the developer portal on the browser, it gets redirected to /signin?returnUrl=%2F.

## Reproduction steps

1. Go to browser
2. Paste the URL : https://{customDeveloperPortl} and click enter
3. The URL gets redirected as :  https://{customUL}/signin?returnUrl=%2F

When we run the same URL as the curl command the terminal, the response looks like this :

```
< HTTP/2 302
< content-type: text/plain; charset=utf-8
< content-length: 43
< location: /signin?returnUrl=%2F
< x-response-time: 1.603ms
< x-content-type-options: nosniff
< x-frame-options: sameorigin
< x-xss-protection: 1; mode=block
< date: Tue, 12 Mar 2024 03:40:01 GMT
< strict-transport-security: max-age=31536000 ; includeSubDomains
<
{ [5 bytes data]
100    43  100    43    0     0    102      0 --:--:-- --:--:-- --:--:--   102Found. Redirecting to /signin?returnUrl=%2F
* Connection #0 to host customDomain.com left intact
```
 

## Expected behavior

The URL should not redirect and show the home page at :  https://{customDeveloperPortl}

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: [Windows]
 - Browser: Google Chrome, Firefox

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by ygrik** [comment]
Hello @sandeep859 

Please check the identity settings for your service
![image](https://github.com/Azure/api-management-developer-portal/assets/8660244/b54cf248-c32d-42de-b202-6635630b3e04)

If this setting is enabled then all anonymous users will be redirected to sign-in page

**Comment by sandeep859** [comment]
> Hello @sandeep859
> 
> Please check the identity settings for your service ![image](https://private-user-images.githubusercontent.com/8660244/313015423-b54cf248-c32d-42de-b202-6635630b3e04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTk3NjIsIm5iZiI6MTcxMDUxOTQ2MiwicGF0aCI6Ii84NjYwMjQ0LzMxMzAxNTQyMy1iNTRjZjI0OC1jMzJkLTQyZGUtYjIwMi02NjM1NjMwYjNlMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTYxNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI1N2FhY2U2NTcyM2I3NGI0YWZiNmVhZTYxYjA5YTBlYWM3MTkzY2UyZTM1ZWY5ZDhkN2FmZDg5ZDY5YzZiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zr9TryY91rCbqZZviluxI72zgYeO2YPubGr7zXP9sFU)
> 
> If this setting is enabled then all anonymous users will be redirected to sign-in page

Yes, We had redirect anonymous users settings on. We turned them off and it fixed the problem. Thanks.
