### ISSUE TITLE
Missing schemas that are not directly referenced (polymorphic)

### ISSUE THREAD

**Issue by hagagps** [Azure/api-management-developer-portal#2433]
## Bug description

We use polymorphic responses with an abstract class and discriminator property `$type` where value is name of implementation class. We automatically include all implementation schemas of the abstract class in our swagger doc. Uploading and downloading the doc from APIM shows all the schemas, however the portal neither shows the schemas nor the properties/descriptions that come along with them.

`AbstractResponse` class
![image](https://github.com/Azure/api-management-developer-portal/assets/66023290/776f250f-fedf-43ae-93a9-514564d9e73e)

`ImplementationResponse` class
![image](https://github.com/Azure/api-management-developer-portal/assets/66023290/6095b6ee-39a1-493e-ad6a-779978b9d107)

## Reproduction steps

1. Create swagger document with `AbstractResponse` and `ImplementationResponse` shown above
2. Upload doc to APIM
3. Only `AbstractResponse` schema is shown in portal

## Expected behavior

All schemas in swagger doc are shown, along with properties and descriptions.

## Is your portal managed or self-hosted?

Managed

**Comment by ygrik** [comment]
Hello @hagagps 

Could you please provide the swagger file example and screenshots from your developer portal and your expected result.

**Comment by hagagps** [comment]
`{
    "openapi": "3.0.1",
    "info": {
        "title": "API",
        "description": "Find ...",
        "version": "2.0"
    },
    "servers": [
        {
            "url": ""
        }
    ],
    "paths": {
        "/": {
            "get": {
                "summary": "Find",
                "description": "#### Find ...",
                "operationId": "Find",
                "parameters": [
                    {
                        "name": "tag",
                        "in": "query",
                        "description": "Tag",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "pageNumber",
                        "in": "query",
                        "description": "Format - int32.",
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    },
                    {
                        "name": "pageSize",
                        "in": "query",
                        "description": "Format - int32.",
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ResponseArray"
                                },
                                "example": [
                                    {
                                        "$type": "string",
                                        "id": "string"
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "AbstractResponse": {
                "type": "object",
                "properties": {
                    "$type": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                },
                "discriminator": {
                    "propertyName": "$type"
                }
            },
            "ImplementationResponse1": {
                "type": "object",
                "allOf": [
                    {
                        "$ref": "#/components/schemas/AbstractResponse"
                    }
                ],
                "properties": {
                    "type": {
                        "type": "string"
                    }
                }
            },
            "ImplementationResponse2": {
                "type": "object",
                "allOf": [
                    {
                        "$ref": "#/components/schemas/AbstractResponse"
                    }
                ],
                "properties": {
                    "label": {
                        "type": "string"
                    }
                }
            },
            "ResponseArray": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/AbstractResponse"
                }
            }
        }
    }
}`

![image](https://github.com/Azure/api-management-developer-portal/assets/66023290/8d5a3b54-7f4f-4523-8ea4-286b0ba16b1c)

![image](https://github.com/Azure/api-management-developer-portal/assets/66023290/027142a0-ab8d-47a0-8ee1-c8f5c5e77a96)

Would expect to see both implementation schemas.

![image](https://github.com/Azure/api-management-developer-portal/assets/66023290/0f857408-ec29-41b4-b356-d005cef41a82)

It could even call out abstract to associate them.

![image](https://github.com/Azure/api-management-developer-portal/assets/66023290/95a3e894-fc52-424d-8e82-910150dd0639)

**Comment by sthirthala** [comment]
Please log managed portal issues to Azure support team using Support + Help link in Azure portal and select Problem Type = Developer portal.
