### ISSUE TITLE
Developer portal - Latest release not available in Azure

### ISSUE THREAD

**Issue by verschaevesiebe** [Azure/api-management-developer-portal#2435]
## Bug description

I have 6 API Managers where i've published a new revision.
The Azure portal states that when changing revisions your portal is updated to the latest version.

However, comparing the self-hosted experience (refreshed look & feel) to the Azure one, it's still the old one.
No updates have happend to the portal.

## Reproduction steps

![image](https://github.com/Azure/api-management-developer-portal/assets/22643503/3ef17ca4-efb5-4e10-9e1c-34d59b0192c6)

## Expected behavior

I would expect the portals (especially the designer) to be upgraded

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

Latest branch (release)

## API Management service name

Can provide in DM.

**Comment by ygrik** [comment]
Hello @verschaevesiebe 
If you talk about 2.26 self-hosted release, we are working on moving the release changes to managed version with expectation in 1-2 weeks.

**Comment by verschaevesiebe** [comment]
Hi @ygrik,

I still don't have the new visual designer update on Azure.
Could you provide a new estimation ?

I see that in the meantime the 2.27.0 was already released.
