### ISSUE TITLE
Users are automatically logged in after the first login without requiring the password to be supplied.

### ISSUE THREAD

**Issue by sandeep859** [Azure/api-management-developer-portal#2437]
Users are automatically logged in after the first login without requiring the password to be supplied. There is no prompt for the username and password after first login attempt.

## Bug description
We are using Managed Developer portal. We are using Identity provider as : Azure Active Directory B2C. We have written custom policies for sign-in and sign-up workflow. 

For the login process , we are using in-built widget for the login button with the identity provider as: Azure Active Directory B2C . On the click of the button, there is prompt for the user email and then we enter password. On successful login, user lands on the home page. We are using inbuilt button for the sign out.

On clicking the sign-out button, user is logged out. 

Next time when user again clicks on the login, There is login pop-up and it disappears and user is automatically logged in  without requiring the username and password to be supplied.

## Reproduction steps

1) Paste the Developer portal URL in the browser and enter. 
2) Click on the login button and pop-up appears.
3) Add username and password, click enter and user is logged in. 
3) Click on the sign-out button and user is signed out.
4) Again click on the login-in button and user is automatically logged in without getting a prompt for the username and password.

## Expected behavior

On every login attempt, user should be asked to add username and password.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows
 - Browser: Any
## Additional context

Add any other context about the problem here, including screenshots.

**Comment by sthirthala** [comment]
Please log managed portal issues to Azure support team using Support + Help link in Azure portal and select Problem Type = Developer portal.
