### ISSUE TITLE
Media in content triggers 404 not found after portal published

### ISSUE THREAD

**Issue by greloux** [Azure/api-management-developer-portal#2439]
## Bug description

After publishing the developer portal from Azure portal the image stored in content appears to be unreachable. In browser console log we can see a 404 not found error

## Reproduction steps
On azure portal
1. Go to API Management Service-> Developer portal -> protal overview 
2. Click on 'Publish'
3. Visualize the portal un the browser 
4. In console log see error 404 (Not Found)

## Additional context

![image](https://github.com/Azure/api-management-developer-portal/assets/164356613/6bf6960d-df9e-479c-aaf6-cf3da45f8e24)

**Comment by sthirthala** [comment]
Please raise any Managed API management developer portal issues directly in Azure support + help center. Please follow link here: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request and select problem type = Developer portal
