### ISSUE TITLE
Cannot disable edit mode.

### ISSUE THREAD

**Issue by woeterman94** [Azure/api-management-developer-portal#2455]
Unable to click any of the actual buttons because it is in edit mode.

![image](https://github.com/Azure/api-management-developer-portal/assets/5755057/4a25caef-bc4a-4fe6-8741-965b2d9f9360)

No way to disable edit mode.

### Reproduction steps
Click the "developer portal" button on the APIM screen in Azure. Or navigate to the portal by using its url.
The portal is in "edit mode". Clicking on anything allows you to edit it.
Expected behavior
There should be a way to close or leave the editor mode and use the portal as a normal user.

### Is your portal managed or self-hosted?
Managed

**Comment by woeterman94** [comment]
Is there any way to just disable the edit mode and use the portal itself while being logged in?

**Comment by malincrist** [comment]
hello @woeterman94, thanks for reaching out! 
You can use `CTRL+Click` to navigate and use the portal when it is in editor mode.
