### ISSUE TITLE
Short session timeout: Oops, something went wrong

### ISSUE THREAD

**Issue by innoforce-dev** [Azure/api-management-developer-portal#2458]
## Bug description

I'm working with the developer portal and often run into a timeout of the authentication session. While editing content, I need to switch to graph editors to prepare pictures or generally need to switch to other tasks. When I come back to the portal, e.g. editing text, then click the Save button, a toast with an error appears "Oops, something went wrong...". At this point, the only workaround preventing the loss of the latest edits is copying the text into the clipboard. Edits on other content elements are lost for sure. 

## Expected behavior

- Increased session timeout, or configurable
- Check the session on a regular basis, and prevent editing when the session is outdated. 

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Win 10
 - Browser: Google Chrome
 - Version: latest

**Comment by bijustrada360** [comment]
I'm experiencing the same and its very annoying. The timeout interval is extremely short and it often ends up loosing work.

**Comment by sthirthala** [comment]
Can you please raise a Azure support ticket. Our support team will investigate managed portal issues.
