### ISSUE TITLE
Dependencies aren't Linux compatible

### ISSUE THREAD

**Issue by samb0803** [Azure/api-management-developer-portal#246]
**Describe the bug**
The @paperbites dependencies aren't consistent with their usage of capitals. So running an npm run publish fails on Linux as it's case sensitive. 

**To Reproduce**
Steps to reproduce the behaviour:

On a Linux OS (Docker image). 
1. Go to where this repository is cloned on your local. 
2. docker run -it -v $PWD:/opt node bash
3. cd /opt
4. npm install
5. npm run publish

![image](https://user-images.githubusercontent.com/25890515/67750621-4b22bd00-fa7b-11e9-8f27-d44b09dc285c.png)

![image](https://user-images.githubusercontent.com/25890515/67750818-ac4a9080-fa7b-11e9-82bf-b3b2ffe53d80.png)

(Note, this will partially fail, but the validations should pass). 

**Expected behaviour**
![image](https://user-images.githubusercontent.com/25890515/67750886-d1d79a00-fa7b-11e9-9921-d6361e0b67bd.png)

**Portal environment**
Self-hosted - Rendering the static content

**Environment**
 - Operating system: Linux Distros (debian)

**Additional context**
Add any other context about the problem here, including screenshots.

![image](https://user-images.githubusercontent.com/25890515/67751269-8376cb00-fa7c-11e9-970d-0a703673ed7e.png)

**Comment by mikebudzynski** [comment]
@samb0803 We're aware of the problem; we'll update the issue when it's resolved.
