### ISSUE TITLE
loading of the anchor "Definitions" stopped working....

### ISSUE THREAD

**Issue by frankdewaelle** [Azure/api-management-developer-portal#2466]
Go to page  https://api.descartes.com/api-details#api=telematics-and-compliance&operation=post-v1-hos-getdrivertimers 
and scroll down to definitions, you will see : 
![image](https://github.com/Azure/api-management-developer-portal/assets/65818117/ea811afd-2824-44cd-8fcb-3ab76b678716)

when you refresh the page and scroll down to "Definitions" the result is correct : 

![image](https://github.com/Azure/api-management-developer-portal/assets/65818117/2470c5bb-4a76-4072-94ed-c9ea9be2105a)

This is on a managed portal.

**Comment by frankdewaelle** [comment]
Idnentical to #2468

**Comment by sthirthala** [comment]
Can you please raise a Azure support ticket. Our support team will investigate managed portal issues.

**Comment by frankdewaelle** [comment]
Case 2404150040012092 started...

**Comment by frankdewaelle** [comment]
Seems fixed on 2-may-2024

{"Status":200,"PortalVersion":"20240417100618","CodeVersion":"20240419144707","Version":"0.43.18155.0","RoleNumber":"Proxy.Host.WebRole_IN_1"}
