### ISSUE TITLE
Question about developer portal backup

### ISSUE THREAD

**Issue by elvovsky** [Azure/api-management-developer-portal#2467]
I am planning APIM upgrade from stv1 to stv2. I am new to APIM and need some help/guidance in terms of backing up developer portal. I did read multiple postings, but yet still have some doubts. Can someone point me to a good guide? Should I be using v2 or v3 of the scripts? Based on my reading, it would pull it local to wherever I will be running those scripts. Is my understanding correct? Thank you very much in advance! Any help/guidance is very much appreciated.

**Comment by sthirthala** [comment]
https://github.com/seenu433/apim-dev-portal-migration

please follow above link

**Comment by elvovsky** [comment]
Not sure why this was closed. That response is something completely different from the question that I have asked

**Comment by sthirthala** [comment]
Use V3- https://github.com/Azure/api-management-developer-portal/blob/master/scripts.v3/migrate.js

https://learn.microsoft.com/en-us/azure/api-management/automate-portal-deployments

**Comment by elvovsky** [comment]
Thank you  @sthirthala. Looks like this assumes that both instances are online. I need to upgrade existing instance to stv2. It looks like the maximum that both can be online is 48 hours (if you open a case and ask support for it). Can this step be done "offline" copy from existing and once upgraded, push to new . Thank you in advance !
