### ISSUE TITLE
API list details are not refreshing

### ISSUE THREAD

**Issue by hgsv1** [Azure/api-management-developer-portal#2468]
From the developer portal https://developer.savvyconnectdirect.net/ , if I click API top right, the request attributes for operation BalanceRequest (Name, Required type etc) first load fine. Then if I click operation Load (on the main content left), for example, it does not load the attributes for LoadRequest (Name, Required type etc). If I click F5 on the keyboard, it does load the attributes (in Chrome or Firefox). The developer portal is not refreshing the API details. Please could this be reviewed and fixed? thanks.

**Comment by sthirthala** [comment]
Is this for managed or self hosted portal

**Comment by hgsv1** [comment]
Hi, yes this is a managed portal.

**Comment by hgsv1** [comment]
sthirthala - yes same issue

**Comment by hgsv1** [comment]
To follow up, could this be fixed? thanks
Does managed service have a different place to request for fixes?

**Comment by hgsv1** [comment]
Hi, I found a related issue here:
https://learn.microsoft.com/en-us/answers/questions/1635526/apim-developer-portal-no-longer-displaying-request
Going straight to end they said it was a bug and would be fixed within a release in about two weeks (they said that on 17th April 2024 and today is 2nd May 2024). So I went and checked our portal site and it looks fixed now. Thanks

**Comment by sthirthala** [comment]
Please raise Azure support ticket to fix the issues related to managed portal.
