### ISSUE TITLE
Error page 404 when we click in a product  in the Products Page

### ISSUE THREAD

**Issue by kdelgadod** [Azure/api-management-developer-portal#247]
Hello

When i logging to the APIM  and choose the page Products it shows me the list of products subscribed. WHere i click in the subscription it shows me the error page: "Page you're looking for doesn't exist"

Whats is the problem? weeks ago it works normally

**API Management service name**
contoso-api

**Environment**
AZure

![image](https://user-images.githubusercontent.com/54553759/67793234-750ebc00-fa48-11e9-91b8-28f20f2b39b3.png)

![image](https://user-images.githubusercontent.com/54553759/67793686-4ba26000-fa49-11e9-96a6-1296a2ac49a0.png)

What would it happends?

**Comment by mikebudzynski** [comment]
We're not able to provide support on individual case basis. Please, make sure you haven't removed the product details page. If problem persists, contact Azure support.
