### ISSUE TITLE
Developer Portal not working with Custom Domain names in StandardV2 SKU

### ISSUE THREAD

**Issue by AndyNorris** [Azure/api-management-developer-portal#2479]
## Bug description

Unable to provision developer portal with custom host names when using StandardV2 SKU. The custom domain names can be entered and validated, but when saving and the service is updated without error the custom domain names are ignored and connectivity to the portal can only be made using the default host name.

## Reproduction steps

1. Deploy new APIM instance using StandardV2 SKU
2. Implement custom domain names for gateway as per documentation
![image](https://github.com/Azure/api-management-developer-portal/assets/682017/1418c7f5-31de-411b-bf1b-9e8cce80399e)

3. Implement custom domain name for developer portal as per documentation 
![image](https://github.com/Azure/api-management-developer-portal/assets/682017/95eeff53-ff46-45ed-97e3-5e76d44c6039)

4. Save changes and APIM is updated
![image](https://github.com/Azure/api-management-developer-portal/assets/682017/effb5037-bb93-4590-9878-506dc801d6b6)
![image](https://github.com/Azure/api-management-developer-portal/assets/682017/9bf1d9ba-cd66-4579-a566-cf0bcc86a6b8)

5. Changes dropped with no updates in UI, but the following log is created.
![screencapture-portal-azure-2024-05-03-09_55_58-edit](https://github.com/Azure/api-management-developer-portal/assets/682017/b724b3b0-3191-4e42-94f4-53f2109b43aa)
Certificate not found is correct and same as used for working gateway. Error message is referencing correct thumbprint of certificate

## Expected behavior

Developer Portal available via custom domain name

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-jumaran-core-tmp-uksouth

## Environment

 - Operating system :Windows 10
 - Browser: Edge
 - Version: 124.0.2478.67

**Comment by kommundsen** [comment]
I have the same problem

**Comment by sthirthala** [comment]
Please raise Azure support request for managed portal issues for further investigation. https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by cpear** [comment]
Was there ever a resolution to this? It is still happening.
