### ISSUE TITLE
Facing Unable to complete the request in test console(try it) of developer portal for apis that takes longer time to process request.

### ISSUE THREAD

**Issue by NagendraBabuRayabarapu** [Azure/api-management-developer-portal#2481]
## Bug description
We are getting **Unable to complete the request** in test console of developer portal for apis that takes longer time to process request.
I could see below error in console :
(in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received.
 
One of our API has complex business logic built so it is taking a bit longer to produce the response. I have tested this API from Postman where it is working and giving the response. but in test console i am getting **Unable to complete the request**.

## Reproduction steps

1. Configure an API that takes around 20 sec to process request.
2. Go to interactive API test console in API details page.
3. Send a request to that API

## Expected behavior

I should be getting the response from API although it takes a bit late.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## Environment

 - Browser: [Google Chrome]
 - Version: [124.0.6367.119(64bit)]

## Additional context

![image](https://github.com/Azure/api-management-developer-portal/assets/53625029/2cef2fb1-c7cd-4b25-8022-95a4e641f7c7)

**Comment by PavanMoturu** [comment]
I am getting same issue for a basic api request also.

I have an Apim.
I created a custom domain for developer portal to access outside vm but inside from my organization.
I enabled "Use Cors Proxy" in operational details of apim as mentioned in https://learn.microsoft.com/en-us/azure/api-management/enable-cors-developer-portal#cors-proxy-option

When I try to test an api, I am getting "Unable to complete request" error.

Can someone look into this issue please?

**Comment by annaji-msft** [comment]
Please use Azure Support + Troubleshooting section in Azure portal to file a support ticket for Managed Developer Portal issues.

**Comment by praveenambati1233** [comment]
@PavanMoturu Have you got this issue resolved ?

**Comment by PavanMoturu** [comment]
I don’t remember

Regards
Pavan Moturu
