### ISSUE TITLE
Custom widget can not call an API of APIM - Origin null is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by girish-tank-avnet** [Azure/api-management-developer-portal#2482]
## Bug description

we have imported an Azure function as an API into Azure APIM and we have created a  custom widget which signup an user. The issue arises when calling an that imported azure function API of APIM through a custom widget using the endpoint _"<APIM domain name>/external/processApimDevPortalFunc-ext/fnUserSignup"_. 

While this operation functions correctly on Google Chrome, Safari users encounter a Cross-Origin Resource Sharing (CORS) error. It's essential to investigate and address this discrepancy, specifically within the context of the custom widget, to ensure proper functionality across both browsers.

Also i have noticed that similar type of issue is already create earlier with following link  https://github.com/Azure/api-management-developer-portal/issues/2364 and  closed too. in this ticket @malincrist commented that this issue is already resolved and will be release on 2.26 release version. 

I have checked with my developer portal version using this link _"/internal-status-0123456789abcdef"_  and get the  "CodeVersion": "20231117172035".. this means that my developer portal updated on last by 11/17/2023 and if we see the release note on GIT i have developer portal version 2.24.0

if this is correct then let me know how i can create request to update my developer portal with latest version.

## Reproduction steps
1. Create a custom widget where you call the endpoint GET _<APIM domain name>/external/processApimDevPortalFunc-ext/fnUserSignup_
2. Deploy this widget to the developer portal and embed it on the page
3. Go to the page with the widget on Safari and open the Developer Tools
See console error:
![image](https://github.com/Azure/api-management-developer-portal/assets/136325659/32909c89-3960-4323-9f6d-b9fff76a6536)

## Expected behavior

_<APIM domain name>/external/processApimDevPortalFunc-ext/fnUserSignup_ should be called without getting CORS error.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: MacOS
 - Browser: Safari
 - Version: 17.x
 - 
## Additional context

The request works on Chrome without an issue.
The request for sandboxed iframe requests on Safari always set the origin to null.

**Comment by sthirthala** [comment]
Please raise Azure support ticket for managed portal issues
