### ISSUE TITLE
Option to clone the developer portal to another apim instance

### ISSUE THREAD

**Issue by thomasklemmknf** [Azure/api-management-developer-portal#2494]
Hi, Is there an option to clone or down/upload the pages/styles/settings to another API Mangement instance?

**Comment by verschaevesiebe** [comment]
Hi @thomasklemmknf,

You should be able to perform a migration from 1 APIM to another copying the exact same design, images, etc.
You can find the script in this repository under the script.v3 library.

https://github.com/Azure/api-management-developer-portal/blob/master/scripts.v3/migrate.bat

I personally use the JS version but depends on what you're proficient in.
Hope this helped.

Thanks, propose to close this.

**Comment by ygrik** [comment]
https://learn.microsoft.com/en-us/azure/api-management/automate-portal-deployments

**Comment by GauravV1395** [comment]
Hi @verschaevesiebe 

I am trying to copy the developer portal and it's contents from one instance (eastUS) to another instance (westUS). My question is that, does the above script provided help me achieve that without affecting contents in the original instance (eastUS) ?

Thanks
