### ISSUE TITLE
Export API definitions from API Management developer portal

### ISSUE THREAD

**Issue by svirchenko** [Azure/api-management-developer-portal#2504]
Hello,

We are trying to explore the possibility of downloading the OpenAPI specification from the Azure API Management Dev Portal, but unfortunately we can't find any documentation to guide us. 

Moreover, we noticed that deprecated Dev Portal supports such [feature](https://azure.microsoft.com/en-gb/updates/export-api-definitions-from-api-management-developer-portal).

Is there any way to add an OpenAPI specification export feature in the Azure API Management Dev Portal for our clients?

Many thanks,
Serhii

**Comment by sthirthala** [comment]
Select the API definition drop down in API details page and it will export the spec to your downloads folder

![image](https://github.com/Azure/api-management-developer-portal/assets/38636149/d605a8c4-e2f5-4a51-99f4-7ad64d4ed929)
