### ISSUE TITLE
Getting 500 internal Server Error while closing user account from Profile page.

### ISSUE THREAD

**Issue by girish-tank-avnet** [Azure/api-management-developer-portal#2522]
## Bug description

There is an 500 internal server error after closing user account from Profile page in APIM Developer portal.

## Reproduction steps

1. Login with user account in APIM Developer portal
2. Click on 'Profile' page.
3. Find  'Close Account' button to close the user account. you will get the confirmation popup. Accept it.
4. user account will be closed and you will be navigated to sign-out page on which 500 Internal Server error comes.
5. See error

![image](https://github.com/Azure/api-management-developer-portal/assets/136325659/6d82a54b-53db-4430-9e7f-5f964b666987)

## Expected behavior

After closing user account and navigated to sign-out page, 500 Internal Server should not come and portal main page will come.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

Release version #2.27.0

## API Management service name
we have 3 APIM instances...

1. https://apiportal-dev.avnet.com **- getting Error**
2. https://apiportal-test.avnet.com **- getting Error**
3. https://apiportal.avnet.com **- getting Error**

## Environment

 - Operating system: All
 - Browser: All

**Comment by sthirthala** [comment]
For managed portal, we request you to please raise Azure support ticket. 

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

Please select api management resource and specify problem type as developer portal related. The ticket will get routed for our support team to work on it
