### ISSUE TITLE
Devloper portal published and not loading the media images in non-administrator mode

### ISSUE THREAD

**Issue by pophitu** [Azure/api-management-developer-portal#2534]
I have published the developer portal. Nothing added or removed. Just using the pre configured portal with pre configured images. When I access the portal in administrator mode, I can see all media contents are there and I verify all those file contents are loaded from the blob storage. However if I access the developer portal in non-administrator mode, no images are loading.

Non-administrator mode - 
![image](https://github.com/user-attachments/assets/61b95348-f6b1-4971-86b1-0f9b410d6ab1)

Administrator mode - 
![image](https://github.com/user-attachments/assets/cb6e561e-a11e-4308-9881-a619f782525a)

**Comment by sthirthala** [comment]
Is this for managed or self hosted portal

**Comment by sthirthala** [comment]
If this is for managed portal, please raise support ticket in Azure support. https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

Select appropriate APIM resource and problem type=Developer portal UI related

**Comment by pophitu** [comment]
Yes this is managed portal. Already created support ticket.

**Comment by annaji-msft** [comment]
Managed developer portal issues must be reported via Microsoft Azure Support. Please use Azure Support + Troubleshooting section in Azure portal to file a support ticket.
