### ISSUE TITLE
Self Hosted Developer Portal - Session setup 

### ISSUE THREAD

**Issue by rnaveen5** [Azure/api-management-developer-portal#2653]
Authentication and Authorization
•	How will access control be managed for different users or user groups provided the Authentication method is Azure ADB2C?

•	The Login and Logout flows when an ADB2C user is integrated – will session management be similar to how it is currently handled in managed portal setup?

**Comment by ygrik** [comment]
Hello @maveen5
You can manage access to the self-hosted developer portal with Azure B2C.
If some flows are not supported (like apply access restrictions depending on user groups), you can change B2C widgets and implement them. 

If this answer is not clear, please provide the detailed scenarios you want to achieve with B2C and self-hosted developer portal.
