### ISSUE TITLE
How to check the Ocp-Apim-Subscription-Key from the policy

### ISSUE THREAD

**Issue by kensinzl** [Azure/api-management-developer-portal#2671]
For the Azure API Management. 

How can I achieve the following

- **if the request includes the Azure Subscription key(Ocp-Apim-Subscription-Key), then Azure API Management needs to validate it**
- **but if the request does not include it, then do not check**

I know at the API Setting tab, there is a checkbox called "Subscription required". 

But this one works like 1. if on, then all requests need to check the subscription key, 2. if off, then all requests

which is not what I want, I have tried some at the inbound policy, with no luck, just want to know if can I achieve the above bold font part. thank you so much,

**Comment by ygrik** [comment]
This question is not related to the developer portal. Please submit a support ticket via the Azure portal.

**Comment by jcbartle** [comment]
Morning, @kensinzl. Did you find an answer / solution to your situation?

**Comment by kensinzl** [comment]
Hi after several trails I do not think the current apim will check your sub key correct or not if you do not require the key.
