### ISSUE TITLE
Is it possible to remove group by tags in the DEV portal

### ISSUE THREAD

**Issue by Aiswaryabalu101090** [Azure/api-management-developer-portal#2683]
## Bug description

Tags always contains sensitive information of any organization and Dev portal being the place to Discover APIs either partially show the tags or there should be an option to remove Group by tags completely.

## Reproduction steps

1. Go to Dev portal
2. Click on APIs
3. Locate Group by tags

## Is self-hosted portal?

Yes

**Comment by ygrik** [comment]
Hello @Aiswaryabalu101090 
In self-hosted you can change api-list widget in any way you want.

For the case to **remove Group by tags** you need to delete group by tags html elements from component template
https://github.com/Azure/api-management-developer-portal/blob/master/src/components/apis/list-of-apis/ko/runtime/api-list.html
