### ISSUE TITLE
Add CORS Policy to APIMS for Subdomains Wildcard 

### ISSUE THREAD

**Issue by Shaieb524** [Azure/api-management-developer-portal#2690]
When trying to add the CORS policy in my APIMS, with subdomain wildcard origin like the following : 

`<origin>https://*.example.com</origin>`

and im getting this error: 
Error in element 'cors' on line , column 10: Origin must be a valid URL consisting of scheme, host, and port only

Even though this works completely fine when I add the same policy directly in the App Service CORS configuration.

**Comment by ygrik** [comment]
Hi @Shaieb524 
Please create support ticket with more details.
FYI https://learn.microsoft.com/en-us/azure/api-management/cors-policy#example
