### ISSUE TITLE
How to leverage the APIM portal content API in the context of a user?

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [Azure/api-management-developer-portal#270]
The new developer portal makes calls to endpoints in APIM to fetch portal content (APIs, operations, products, etc.). From looking at the code here and observing the runtime behavior, I believe these endpoints can be called anonymously (no Authorization header) or with a Bearer or SAS token (and I believe the SAS can either be a publisher-facing SAS token for admin operations, or a user-facing SAS token for the logged-in user).

For example, looking at the network traffic I can see a call made to this endpoint to fetch the set of APIs that the user can see (which respects all the group visibility logic in APIM): 

```
GET https://<service-name>.management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/apis?api-version=2019-12-01
Authorization:  SharedAccessSignature....
```

I'd like to leverage these same endpoints from our own portal - can I programmatically generate the SharedAccessSignature for a user (on my server, not on the client of course)?

**Comment by mikebudzynski** [comment]
Ben, you can use the following API endpoint:
https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/user/getsharedaccesstoken

You can call it either through ARM or through the direct access API.

**Comment by Blackbaud-BenLambert** [comment]
Ah, thanks Mike that's exactly what I needed...sorry, I just completely missed seeing that endpoint in the docs..
