### ISSUE TITLE
Question: how to move customizations

### ISSUE THREAD

**Issue by molinch** [Azure/api-management-developer-portal#275]
Hello, this is just a simple question regarding the new portal.
I couldn't find an answer in FAQ or elsewhere.

If you have two APIM instances, for example one for dev and for prod.
What is the recommended way to move your customizations from one environment to the other?

**Comment by mikebudzynski** [comment]
The recommended approach is described here: https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services
