### ISSUE TITLE
Roles seem not to work in published mode

### ISSUE THREAD

**Issue by DerPate2010** [Azure/api-management-developer-portal#293]
**Describe the bug**
I'm using a self-hosted version. The "Visible to" option seem not to work for the published version. I was not able to debug the issue further. Is there any guidance to debug the published version of the portal (the version you get from "npm run publish")? I was not able to let Chrome map the compiled JS to the original TS files.

**To Reproduce**
1. Add menu to a page in design mode
2. Set "visible to" to "authenticated"
3. Add another menu for anonymous
4. Publish the page using "npm run publish"
5. Navigate to the published site and it shows the "anonymous" menu
6. Sign in
7. The site still shows the anonymous menu

**Expected behavior**
The site shows the authenticated menu

**Portal environment**
Self-hosted

**Release tag or commit SHA (if using self-hosted version)**
2.0.0

**API Management service name**

**Environment**

**Additional context**

**Comment by erbg** [comment]
Same issue on Managed Version

**Comment by azaslonov** [comment]
Hi @DerPate2010, @erbg. Sorry to hear that. Would you be able to email me your APIM service names to alzaslon@microsoft.com? I could look at your configuration closer and tell what's going on.

Regarding the debugging of runtime code: there is a file webpack.runtime.js describing build configuration. By default, it is set to production build with minimization enabled. What you can do is switch to development mode and comment out TerserPlugin like this:

```js
module.exports = {
    target: "web",
    mode: "development",
    optimization: {
        minimizer: [
            // new TerserPlugin({
            //     sourceMap: false,
            //     terserOptions: {
            //         mangle: false,
            //         output: {
            //             comments: false,
            //         }
            //     }
            // })
        ]
    }
...
```
Also, please make sure tsconfig.json has `sourceMap` enabled in `compilerOptions`:
```json
{
    "compilerOptions": {
        "sourceMap": true,
    }
}
```
That should bring you TypeScript maps to the browser.

**Comment by jordiverav** [comment]
> Hi @DerPate2010, @erbg. Sorry to hear that. Would you be able to email me your APIM service names to [alzaslon@microsoft.com](mailto:alzaslon@microsoft.com)? I could look at your configuration closer and tell what's going on.
> 
> Regarding the debugging of runtime code: there is a file `webpack.runtime.js` describing build configuration. By default, it is set to `production` build with minimization enabled. What you can do is switch to development mode and comment out `TerserPlugin` like this:
> 
> ```js
> module.exports = {
>     target: "web",
>     mode: "development",
>     optimization: {
>         minimizer: [
>             // new TerserPlugin({
>             //     sourceMap: false,
>             //     terserOptions: {
>             //         mangle: false,
>             //         output: {
>             //             comments: false,
>             //         }
>             //     }
>             // })
>         ]
>     }
> ...
> ```
> 
> Also, please make sure tsconfig.json has `sourceMap` enabled in `compilerOptions`:
> 
> ```json
> {
>     "compilerOptions": {
>         "sourceMap": true,
>     }
> }
> ```
> 
> That should bring you TypeScript maps to the browser.

Hi Alexander, 
We have this problem in our APIM instance.
I have seen that you commented on a possible solution on GitHub, in our case we have it hosted in Azure, we do not have it self-hosted.

Thank you very much for your help.

**Comment by azaslonov** [comment]
Understood. We're investigating it now.
