### ISSUE TITLE
Adding a block to library, not showing up

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/api-management-developer-portal#296]
I created a block on one of the pages and added it to th library of the hosted developer portal, when I want to select it from another page, it says my library is empty.

Perhaps I'm misunderstanding the functionality, but I would assume that adding a block to the library will result in being able to select it

**Comment by azaslonov** [comment]
Hi @SahinOzdemir, yes, this is a known issue. The fix should be out some time next week.

**Comment by SahinOzdemir** [comment]
Ok, could you let us know when this is rolled out then?

**Comment by azaslonov** [comment]
This issue required changes on the Management API side. It has been fixed and release should be out by Feb 21.
