### ISSUE TITLE
Signing in does not work.

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/api-management-developer-portal#297]
Just checked the legacy developer portal and signing in works as expected. When I try to sign in on the new developer portal, I end up on the following page.

![image](https://user-images.githubusercontent.com/7938059/68529483-918bdd80-02ff-11ea-98e8-96ac9db3764e.png)

**Comment by azaslonov** [comment]
Hi @SahinOzdemir, there is a known issue with users with a "dash" sign in their IDs, in the managed version of the portal. I believe this is your case as well (please let me know if it's not). The fix for this is ready and waiting to be shipped. ETA is 2-3 weeks.

**Comment by SahinOzdemir** [comment]
Hi @azaslonov , I actually do not have a dash in my ID, only a dot. Same issue or something different?

**Comment by ygrik** [comment]
Hi @SahinOzdemir 
I think you muss up user **ID** with user **Name**. A user ID can not contain dots. 

The User ID may contain only numbers, letters, and dash (-) sign when preceded and followed by a number or a letter.
