### ISSUE TITLE
AAD auth to developer portal "could not resolve endpoints"

### ISSUE THREAD

**Issue by dornstein** [Azure/api-management-developer-portal#298]
I'm trying to configure a new instance of APIM.  I want users of the developer portal to use AAD exclusively.  I created a new AAD app registration following the instructions here: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad

Now I go to the signin page and pick "Azure Active Directory."  I get this error:

**Unable to obtain id_token with client ID: 73c95b47-86f0-4c10-9402-501eed3e9e07. Error: Error: could not resolve endpoints. Please check network and try again.**

I have no idea how to diagnose this or what is wrong and now I'm blocked.  Any ideas on what's going wrong?

**Comment by azaslonov** [comment]
Hi @dornstein, sorry to hear that. There is known issue happening with AAD sign-in and we're working on it. The fix should be available in 2-3 weeks.

**Comment by dornstein** [comment]
Yuck.  OK, well does that only impact the issues with the developer portal.  Can I still do things like protect my APIs using AAD?

**Comment by azaslonov** [comment]
Yes, you should be able to do this using i.e. Validate JWT policy. Here's respective article: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad

**Comment by dornstein** [comment]
Thanks for that.  There are a few things about that document that are unclear as I tried working through it.  It talks about setting up an OAUTH 2.0 auth server in APIM and in the example we create a new AAD app to represent the upstream API client.  In the example we do it for the developer portal and plug in the client id/secret for the developer portal.  But that suggests that every client of the API would need its own OAUTH server configured -- which can't be right.

If I'm willing to start with my backend API doing the bearer token authZ, can I skip setting up an OAUTH server in APIM and have APIM just pass along any bearer token coming in the header from the API client?  I tried that but the header didn't seem to make it through.  Do I need to set up some policy or something so the authorization header from the client makes it through the gateway to my backend?

**Comment by mikebudzynski** [comment]
You can use OAuth for authentication of the API requests by applying the `validate-jwt` policy: https://docs.microsoft.com/en-us/azure/api-management/api-management-access-restriction-policies#ValidateJWT

Setting up an OAuth server is for the ability to use OAuth in the interactive console of the developer portal (still not supported in the new dev portal: #208).
