### ISSUE TITLE
Migrate to the new, non-preview API version

### ISSUE THREAD

**Issue by ashemedai** [Azure/api-management-developer-portal#300]
**Describe the bug**
The wiki in this repository mentions the use of `"managementApiVersion": "2018-06-01-preview"` a few times.

**To Reproduce**
1. Go to wiki
2. Click on `self-hosting the portal`
3. Scroll down to `Step 2: Configure`

**Expected behavior**
Expected to see `"managementApiVersion": "2019-01-01"` as per visiting https://docs.microsoft.com/en-us/rest/api/apimanagement/ and folding open the `Reference` to see GA versions.

**Portal environment**
N/A

**Release tag or commit SHA (if using self-hosted version)**
N/A

**API Management service name**
N/A

**Environment**
N/A

**Comment by mikebudzynski** [comment]
@ashemedai Thanks for opening this issue. Migrating to the new API version is one our roadmap.

**Comment by ashemedai** [comment]
@mikebudzynski Awesome to hear. I did try the 2019-01-01 API calls yesterday to retrieve the various data of a portal I clicked together and it all worked as it should (which shouldn't be a surprise, but still nice to know hopefully). I might actually write a blog post about this.

As an aside: awesome work on the new portal.

**Comment by mikebudzynski** [comment]
Thanks, @ashemedai! Although the endpoint works, we still need to document the API [here ](https://docs.microsoft.com/rest/api/) before we switch the versions.

**Comment by mikebudzynski** [comment]
Closed with https://github.com/Azure/api-management-developer-portal/pull/819
