### ISSUE TITLE
Unable to view API-M Trace in new Developer Portal

### ISSUE THREAD

**Issue by sethwenzel** [Azure/api-management-developer-portal#301]
**Describe the bug**
In the developer portal, if you use the "Try it" feature, and have tracing enabled, when you view the trace, about a second or so after viewing the trace you are redirected to a 500 error page.

**To Reproduce**
1. Sign in to the developer portal
2. Click on APIs
3. Select an API, and choose an operation
4. Select "Try it", which pops out a side dialog
5. Run the operation
6. On the bottom of the results, select the "Trace" tab
7. Once the trace renders, you will get redirected to a 500 page

**Expected behavior**

**Portal environment**
Managed

**Release tag or commit SHA (if using self-hosted version)**
Unknown

**API Management service name**
apim-edge-dev

**Environment**
 - Operating system: Windows 10
 - Browser: Firefox, Chrome, Edge chromium

**Additional context**

From Chrome:

Console error logging:
`VM9295 consoleLogger.ts:61 ReferenceError: Unable to process binding "if: function(){return consoleTrace }"
Message: Unable to process binding "with: function(){return consoleTrace }"
Message: Unable to process binding "if: function(){return backend }"
Message: backend is not defined
    at if (eval at parseBindingsString (VM8480 knockout-latest.js:NaN), <anonymous>:1:55)
    at e (VM8480 knockout-latest.js:78)
    at eval (VM8480 knockout-latest.js:80)
    at a.o.l (VM8480 knockout-latest.js:106)
    at Function.xd (VM8480 knockout-latest.js:58)
    at Function.yd (VM8480 knockout-latest.js:58)
    at Function.ha (VM8480 knockout-latest.js:57)
    at Object.a.o.a.$ (VM8480 knockout-latest.js:55)
    at init (VM8480 knockout-latest.js:106)
    at eval (VM8480 knockout-latest.js:82)
eval @ VM9295 consoleLogger.ts:61
step @ VM9295 consoleLogger.ts:32
eval @ VM9295 consoleLogger.ts:13
eval @ VM9295 consoleLogger.ts:7
__awaiter @ VM9295 consoleLogger.ts:3
ConsoleLogger.traceError @ VM9295 consoleLogger.ts:59
UnhandledErrorHandler.handlerError @ VM9466 unhandledErrorHandler.ts:11
error (async)
UnhandledErrorHandler @ VM9466 unhandledErrorHandler.ts:8
_createInstance @ VM8258 instantiation.js:21
resolveInstance @ VM8258 instantiation.js:41
eval @ VM8257 resolver.js:72
eval @ VM8257 resolver.js:34
eval @ VM8257 resolver.js:32
resolve @ VM8257 resolver.js:96
eval @ VM8238 container.js:320
Container._get @ VM8238 container.js:311
Container.getAll @ VM8238 container.js:239
Collection @ VM8230 inversifyInjector.ts:117
resolveInstance @ VM8258 instantiation.js:45
eval @ VM8257 resolver.js:72
resolve @ VM8257 resolver.js:96
eval @ VM8238 container.js:320
Container._get @ VM8238 container.js:311
Container.get @ VM8238 container.js:230
InversifyInjector.resolve @ VM8230 inversifyInjector.ts:94
eval @ VM8228 startup.runtime.ts:15
VM8480 knockout-latest.js:82 Uncaught ReferenceError: Unable to process binding "if: function(){return consoleTrace }"
Message: Unable to process binding "with: function(){return consoleTrace }"
Message: Unable to process binding "if: function(){return backend }"
Message: backend is not defined
    at if (eval at parseBindingsString (VM8480 knockout-latest.js:NaN), <anonymous>:1:55)
    at e (VM8480 knockout-latest.js:78)
    at eval (VM8480 knockout-latest.js:80)
    at a.o.l (VM8480 knockout-latest.js:106)
    at Function.xd (VM8480 knockout-latest.js:58)
    at Function.yd (VM8480 knockout-latest.js:58)
    at Function.ha (VM8480 knockout-latest.js:57)
    at Object.a.o.a.$ (VM8480 knockout-latest.js:55)
    at init (VM8480 knockout-latest.js:106)
    at eval (VM8480 knockout-latest.js:82)
if @ VM9636:1
e @ VM8480 knockout-latest.js:78
eval @ VM8480 knockout-latest.js:80
a.o.l @ VM8480 knockout-latest.js:106
xd @ VM8480 knockout-latest.js:58
yd @ VM8480 knockout-latest.js:58
ha @ VM8480 knockout-latest.js:57
a.o.a.$ @ VM8480 knockout-latest.js:55
init @ VM8480 knockout-latest.js:106
eval @ VM8480 knockout-latest.js:82
K @ VM8480 knockout-latest.js:44
eval @ VM8480 knockout-latest.js:82
C @ VM8480 knockout-latest.js:14
q @ VM8480 knockout-latest.js:81
l @ VM8480 knockout-latest.js:79
m @ VM8480 knockout-latest.js:79
a.Pa @ VM8480 knockout-latest.js:87
a.o.l @ VM8480 knockout-latest.js:107
xd @ VM8480 knockout-latest.js:58
yd @ VM8480 knockout-latest.js:58
ha @ VM8480 knockout-latest.js:57
a.o.a.$ @ VM8480 knockout-latest.js:55
init @ VM8480 knockout-latest.js:106
eval @ VM8480 knockout-latest.js:82
K @ VM8480 knockout-latest.js:44
eval @ VM8480 knockout-latest.js:82
C @ VM8480 knockout-latest.js:14
q @ VM8480 knockout-latest.js:81
l @ VM8480 knockout-latest.js:79
m @ VM8480 knockout-latest.js:79
a.Pa @ VM8480 knockout-latest.js:87
a.o.l @ VM8480 knockout-latest.js:107
xd @ VM8480 knockout-latest.js:58
yd @ VM8480 knockout-latest.js:58
ha @ VM8480 knockout-latest.js:57
a.o.a.$ @ VM8480 knockout-latest.js:55
init @ VM8480 knockout-latest.js:106
eval @ VM8480 knockout-latest.js:82
K @ VM8480 knockout-latest.js:44
eval @ VM8480 knockout-latest.js:82
C @ VM8480 knockout-latest.js:14
q @ VM8480 knockout-latest.js:81
l @ VM8480 knockout-latest.js:79
m @ VM8480 knockout-latest.js:79
a.Pa @ VM8480 knockout-latest.js:87
a.o.l @ VM8480 knockout-latest.js:107
xd @ VM8480 knockout-latest.js:58
yd @ VM8480 knockout-latest.js:58
ha @ VM8480 knockout-latest.js:57
Gc @ VM8480 knockout-latest.js:57
notifySubscribers @ VM8480 knockout-latest.js:41
wa @ VM8480 knockout-latest.js:46
c @ VM8480 knockout-latest.js:45
OperationConsole.selectTraceTab @ VM9335 operation-console.ts:566
eval @ VM8480 knockout-latest.js:103
dispatch @ VM8221 jquery-3.2.1.slim.min.js:3
q.handle @ VM8221 jquery-3.2.1.slim.min.js:3
Show 27 more frames
VM9269 routeHelper.ts:73 Uncaught (in promise) Error: Parameter "apiName" not specified.
    at RouteHelper.getDefinitionAnchor (VM9269 routeHelper.ts:73)
    at OperationDetails.getDefinitionReferenceUrl (VM9333 operation-details.ts:250)
    at attr (eval at parseBindingsString (VM8480 knockout-latest.js:NaN), <anonymous>:1:125)
    at update (VM8480 knockout-latest.js:99)
    at a.$.l (VM8480 knockout-latest.js:82)
    at Function.xd (VM8480 knockout-latest.js:58)
    at Function.yd (VM8480 knockout-latest.js:58)
    at Function.ha (VM8480 knockout-latest.js:57)
    at Function.Gc (VM8480 knockout-latest.js:57)
    at Function.notifySubscribers (VM8480 knockout-latest.js:41)`

screenshot:
![image](https://user-images.githubusercontent.com/2038137/68601313-16970400-0472-11ea-8795-38e5b6db9a0c.png)

**Comment by azaslonov** [comment]
Hi @sethwenzel, thank you for reporting the issue. We're working on it.

**Comment by RupengLiu** [comment]
@sethwenzel , thank you for reporting, btw, trace can be checked only in the design time

**Comment by azaslonov** [comment]
Just to clarify a bit, Trace is available only to Admins. Therefore, this functionality was exposed to developers by mistake, which we're addressing now.

**Comment by azaslonov** [comment]
Hi @sethwenzel, we decided to remove the Trace tab from the developer portal completely. Basically this is the legacy that came from the old portal, where it was added at times when there was no Test console in Azure portal, plus it was only available to administrators.

**Comment by ErikMogensen** [comment]
But if your backend service requires an OAuth token you cannot test it from the Azure Portal. When trying this from the developer portal I can as a workaround add a header with Ocp-Apim-Trace: True and use a subscription which allows tracing but I would prefer if I didn't have to do that.
