### ISSUE TITLE
Unable to page through operations on api-details page

### ISSUE THREAD

**Issue by sethwenzel** [Azure/api-management-developer-portal#303]
**Describe the bug**
When viewing the operations in an API, I am unable to page through the operations

**To Reproduce**
1. Log into dev portal
2. APIs
3. Select an API with a large number of operations
4. on left hand navigation, below the operation list, select the greater than button (to page right)

**Expected behavior**
Should go to the next page of operations

**Portal environment**
Managed

**Release tag or commit SHA (if using self-hosted version)**
Unknown

**API Management service name**
apim-edge-dev

**Environment**
 - Operating system: Window10
 - Browser: Firefox and Edge Chromium

**Additional context**

Doesn't seem to cause any error in the console, and there is a backend API call that succeeds

![image](https://user-images.githubusercontent.com/2038137/68699321-cb9fee00-0550-11ea-8029-0f7c37a4f396.png)

**Comment by azaslonov** [comment]
Hi @sethwenzel, thank you for reporting the issue, we're investigating.
