### ISSUE TITLE
All Definitions view-able on operation (not just the definitions used by the operation)

### ISSUE THREAD

**Issue by sethwenzel** [Azure/api-management-developer-portal#307]
**Describe the bug**
When viewing an API with many operations and definitions, each operation has the full list of all definitions, not just the ones that apply to the selected API operation.  With a large API, this is odd.

For example, we have an operation with 4 different definitions in it's swagger, but we have 100s of types in the API operations overall, so there's 100s of definitions on the page.

**To Reproduce**
1. Import a Swagger API with many operations and definitions
2. Click on APIs
3. Select the API
4. Select an operation.  Scrolling down you will see all definitions in the swagger spec, not just the ones in use in the operation

**Expected behavior**
Expect to only see the definitions that apply to the selected operation.

**Portal environment**
Managed

**Release tag or commit SHA (if using self-hosted version)**
unknown

**Additional context**
The operation's response model, with the 4 included definitions
![image](https://user-images.githubusercontent.com/2038137/68709068-ed09d580-0562-11ea-8241-a1241dd1babf.png)

A partial list of the definitions
![image](https://user-images.githubusercontent.com/2038137/68709092-f85d0100-0562-11ea-8b90-7e12542b90cb.png)

**Comment by azaslonov** [comment]
Hi @sethwenzel, thank you for reporting the issue. We're looking into it.
