### ISSUE TITLE
500 Error on viewing API List

### ISSUE THREAD

**Issue by phil-deveau-3** [Azure/api-management-developer-portal#314]
**Describe the bug**
Creating a brand new portal, when navigating to the api list after several seconds I receive a javascript error and I am redirected to a 500 page.  No page customizations.

**To Reproduce**
Create a new api instance
Create post api definition with required query string, request body and response body
Publish portal
Create a user, subscription, login
visit api list page
receive errors in javascript

**Expected behavior**
Expect to be able to view the list of api's and test them.

**Portal environment**
Managed

**API Management service name**
uat-externalretailpos-api-eastus

**Environment**
 - Various users report this, macos, windows 10.
 - Chrome, Edge
 - Latest versions

![IMAGE 11-14-19 AT 1 54 AM](https://user-images.githubusercontent.com/14810201/68834056-e8d4d980-0682-11ea-8b85-63a58f8c5ba1.jpeg)

**Comment by phil-deveau-3** [comment]
I created a duplicate api without any request/response information similar to #295, perhaps this is related?

**Comment by sethwenzel** [comment]
It does appear that OpenAPI 3.0 is broken again, in a new way

**Comment by azaslonov** [comment]
Hi @sethwenzel, looking at your screenshot, I think that you don't have the latest bits (if we're talking about self-hosted version, managed version wasn't updated yet, ETA end of this week).
