### ISSUE TITLE
Support for multipart/form-data

### ISSUE THREAD

**Issue by EdiFabric** [Azure/api-management-developer-portal#316]
**Describe the bug**
Can't try API operation with multipart/form-data content type

**To Reproduce**
1. Set header Content-Type to be multipart/form-data
2. No button to upload file

**Expected behavior**
Provide a button to browse for files and include multipart/form-data in request body

**Portal environment**
Managed

**API Management service name**
contoso-api

**Environment**
 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: [e.g., 22]

**Additional context**
Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
Hi @EdiFabric, thanks for reporting the issue. We're working on it.

**Comment by EdiFabric** [comment]
Thank you

**Comment by varpitoo** [comment]
Any update?

**Comment by azaslonov** [comment]
Hi @varpitoo, no not yet. We have lots of competing tasks and have to prioritize. We'll update this issue with ETA as soon as we know it. Thanks for your patience.

**Comment by azaslonov** [comment]
Update: ETA is 2/14 for self-hosted version and 2/21 for managed.

**Comment by SVB-knowmywork** [comment]
When are expecting the support for multipart/form-data in APIM developer portal. And also we can't even define the requestBody with binary file data in api definition using open API 3.0.x. Then what is the benefit of supporting it in Azure APIM?

**Comment by jaywhaaub** [comment]
This would be an extremely useful feature.

**Comment by falrnacn** [comment]
Is it implemented yet?

**Comment by mikebudzynski** [comment]
Yes, it's implemented in all OpenAPI versions, with the exception of this bug https://github.com/Azure/api-management-developer-portal/issues/1487
