### ISSUE TITLE
Azure AD and Azure AD B2C authentication

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#321]
Hi,
In the new portal, I'm not able to sign-in or sign-up with Azure AD and Azure AD B2C identity is it a feature planned in the roadmap?

**Comment by mikebudzynski** [comment]
This feature is already implemented in the developer portal: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad#-developer-portal---add-azure-ad-account-authentication

If you need further assistance, see [our guidance](https://github.com/Azure/api-management-developer-portal#-interactions).
