### ISSUE TITLE
Product and API list are empty

### ISSUE THREAD

**Issue by shwetashukla** [Azure/api-management-developer-portal#322]
**Describe the bug**
I don't see any products or API on the portal

**To Reproduce**
1. Login to the developer portal
2. Click on menu item products
3. The list is empty
4. Click on the menu item API
5. The list is still empty

**Expected behavior**
Since I have subscription I should be able to see products and API

**Portal environment**
Managed / Self-hosted

**Release tag or commit SHA (if using self-hosted version)**
For example, release `2.0.0` or commit `c45da9778b70d369aba60fa2e63c191efe2b548f`

**API Management service name**
contoso-api

**Environment**
 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

**Additional context**
Add any other context about the problem here, including screenshots.

**Comment by mikebudzynski** [comment]
@shwetashukla This bug report doesn't contain enough information. As per [our guidelines](https://github.com/Azure/api-management-developer-portal#-interactions) we don't provide support through GitHub,
