### ISSUE TITLE
Portal should redirect to the delegation URL without showing the registration page

### ISSUE THREAD

**Issue by mikebudzynski** [Azure/api-management-developer-portal#326]
Copied from another thread:

![image](https://user-images.githubusercontent.com/40186513/69176315-60a76780-0aba-11ea-8e06-436cd38d25ba.png)

**Comment by joeystdio** [comment]
It would also be nice if you don't have to publish the new developer portal after changing the delegation settings. Seems like a hack to me.

**Comment by azaslonov** [comment]
Hi @joeystdio, yes, it makes sense, we'll fix that.

**Comment by azaslonov** [comment]
The issue has been fixed, but we need to wait until the backend gets rolled out. We expect it to happen in the next 3 weeks.
