### ISSUE TITLE
Portal prompts for client certificate

### ISSUE THREAD

**Issue by melborp** [Azure/api-management-developer-portal#327]
## Bug description

~~Hi, I created a new APIM instance yesterday night and as signed up with new user using username/password. i cant sign in such that would show me correct menu items (i continue to see "Home APIs Products Sign in Sign up" .. Sign In just takes me to home again when i have logged in. No authenticated user menu items, but i can manually navigate to https://apim/profile~~ See #293 

Another odd thing is that i always get prompted to client certificate when i first go to signin url in the incognito. I literally have not configured any authentication, its all default (new fresh APIM). Only Username/password identity provider and no delegation.  I just cancel it and see in the trace 401 for identity url 
   Request URL: https://[some-fake-apim-url].management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/identity?api-version=2018-06-01-preview. 

## Reproduction steps

1. Create new APIM
2. Go to Developer Portal
3. /signin 
4. see the client cert prompt

1. Signup for new user account and go through verification
2. Try to login
3. redirects to home, but no authenticated user menu items are visible

## Expected behavior

Authenticated user should see correct menu items and not be prompted to client certificate unless its required by configuration.~~

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi Taavi, this is a duplicate issue, please track this item #293.

**Comment by mikebudzynski** [comment]
Thanks for reporting the problems. As Alex indicated, we're tracking the menu visibility through #293  I've edited this issue to reflect the client certificate prompt only.

**Comment by melborp** [comment]
Additionally, when i try to test an api and enter the subscription key into the field on the testing form .. the subscription key is not sent with request (with f12 debugger i can see its sent as undefined) and i get 401. 
when i add custom header with "Ocp-Apim-Subscription-Key" header, then it works.

**Comment by azaslonov** [comment]
Thanks Taavi, I could repro the issue. We'll fix it soon.

**Comment by mikebudzynski** [comment]
The issue has been fixed, please allow a few weeks for the API Management service deployment to roll out.
