### ISSUE TITLE
AAD sign-in and sign-up flow not working

### ISSUE THREAD

**Issue by tgossler** [Azure/api-management-developer-portal#330]
## Bug description

I have configured the AAD identify provider for one of our APIM instances and I'm trying to switch to the new portal.

I had to add the new redirect URL to the AAD application so that the sign-in is basically working.

Now I have the following problems.

1. When "Redirect anonymous user to sign-in page" is enabled in the Identities settings, then the sign-up page is not shown but the user gets stuck on the login page. If this settings is disabled, for new users the sign-up page is shown and the sign-up is basically working.

2. After the working sign-up of point 1 the home page is not shown in authenticated mode but in anonymous mode. Even clicking sign-in again doesn't change this.

3. When trying to sign-in with the APIM admin account leads to the following error message: "Server error. Unable to send request. Please try again later." 

Interestingly, even in the working sign-up scenario the web browser debug console is showing the following resuest URL which looks weird:
    https://myapim.management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/users?api-version=2018-06-01-preview
    Note the the "xxx" parts.

## Reproduction steps

1. Configure "Azure Active Directory" as the only IdP under Identities
2. Disable "Redirect anonymous user to sign-in page" in the Identities settings page
3. Open new dev portal in an incognito web browser window
4. Sign-in with AAD
5. Note that you get stuck on the sign-in page, redirect to sign-up page is not working
6. Disable "Redirect anonymous user to sign-in page"
7. Sign-in with AAD and an Administrator user account
8. Note that the sign-up page is shown now
9. Open web browser debug window and watch the network requests
9. Click on sign-up
10. Note that the sign-up fails with an error message
11. Find the wrong user sign-up request URL in the web browser debug window
12. Sign-in with AAD and a user account which has not signed-in before to this APIM instance
13. Note that the sign-up is working fine, but still the weird request URL is shown in the web browser debug window

## Expected behavior

1. Sign-up page is also shown when "Redirect anonymous user to sign-in page" is enabled

2. Sign-in is working for Administrator accounts as well, sign-up page is not shown in this case

3. Home page is shown in authenticated mode after login

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.97 (Official Build) (64-bit)

**Comment by azaslonov** [comment]
Hello Thomas, thank you for reporting the issue. We're investigating it now.

**Comment by avenieuw** [comment]
Dear Alexander

I just want to mention that we are having exactly the same issue.

Kind regards
John Bilay

**Comment by azaslonov** [comment]
Hi @tgossler, @avenieuw,

Here's an update:
_**Problem 1** - AAD signup doesn't work when `Redirect anonymous users to sign-in page` setting is on_: We figured out the issue and working on the fix. Unfortunately, there is no workarounds.

_**Problem 2** - Signed-in users still see menus for anonymous users_: This issue has been fixed and managed portal version deployed last week. Please give it a try.

_**Problem 3** - Users signed-in with Basic account receive server error message_: This happens to users having dashes ("-") in their (ARM) IDs. The issue has been fixed, but not yet deployed. ETA is **Dec 7**.

**Comment by tgossler** [comment]
Perfect, thanks!

I will give it a try soon.

Best regards,
- Thomas

**Comment by stevedown** [comment]
For what it's worth, this is still happening to me.

**Comment by azaslonov** [comment]
Hi @stevedown, can you please send your service name to apimportalfeedback@microsoft.com. We'll take it from there.

**Comment by stevedown** [comment]
The service is payments-cus-dev-apim, in resource group payments-cus-dev-infra-rg. The portal is at https://payments-cus-dev-apim.developer.azure-api.net.


Regards,
Steve


Steve Down
Sr. Systems Manager
The Amynta Group
email: ***@***.***
office: 720-878-2371
________________________________

**Comment by azaslonov** [comment]
Thank you!

**Comment by stevedown** [comment]
Any update on this, Alexander? Thanks!
