### ISSUE TITLE
POST Operations not loading in Developer Portal

### ISSUE THREAD

**Issue by swebb2** [Azure/api-management-developer-portal#331]
## Bug description

When viewing API operations in the developer portal, POST operation details do not load (spinning loading icon)

## Reproduction steps

1. Create new API Management instance.
2. Add sample Demo Conference API (make sure anonymous access is allowed).
3. Open developer portal and navigate to API Details page.
4. Click on SubmitSession operation.

## Expected behavior

Details for the SubmitSession API operation should display.

## Is your portal managed or self-hosted?

Managed

## Additional context

I added another API and was able to duplicate the issue. PATCH and GET seem to load fine. I then switched back to the legacy portal and all operations load. Tried in Chrome/Brave and Edge.

**Comment by azaslonov** [comment]
Hi @swebb2, would you please email is your service name to apimportalfeedback@microsoft.com, we'll have a look what's happening exactly.

**Comment by mikebudzynski** [comment]
This problem has been already fixed by this commit: https://github.com/Azure/api-management-developer-portal/commit/0daa6b8b85ae109477a183851b0ac2d52a26a15b

The new release will be rolled out in the next few days.

**Comment by ygrik** [comment]
Hi @swebb2 
It was fixed with the pull request
https://github.com/Azure/api-management-developer-portal/pull/325
