### ISSUE TITLE
Uploaded media files expire after 1 day

### ISSUE THREAD

**Issue by mmcmasterd3** [Azure/api-management-developer-portal#342]
##  Bug description

The URL's for uploaded media files (eg. favicons, logos) have a default expiry of 1 day in the generated SAS token in the Azure Storage account. The logos aren't visible in the "Media" 
library anymore and appear as fully transparent empty squares. The logos disappear from the published portal. Attempting to download the files fail:

```xml
<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:b23a0e6a-f01e-00c5-1098-a5fc35000000 Time:2019-11-28T03:05:53.0909634Z
</Message>
<AuthenticationErrorDetail>
Signature not valid in the specified time frame: Start [Tue, 26 Nov 2019 06:16:19 GMT] - Expiry [Wed, 27 Nov 2019 06:21:19 GMT] - Current [Thu, 28 Nov 2019 03:05:53 GMT]
</AuthenticationErrorDetail>
</Error>
```
 
## Reproduction steps

1. Upload a new logo image
2. Wait 24 hours
3. Attempt to use the image, and discover it's not accessible.

## Expected behavior

Uploaded media remains accessible

## Is your portal managed or self-hosted?

Managed

## Additional context

Add any other context about the problem here, including screenshots.
(circled items were valid 2 days ago)

![image](https://user-images.githubusercontent.com/57653443/69773996-48cd9300-11e0-11ea-8122-9a7770dcefcc.png)

**Comment by mmcmasterd3** [comment]
Looks like this issue was previously raised as #216 which was closed without a resolution.

**Comment by mmcmasterd3** [comment]
1-day expiry is generated by @paperbits/azure AzureBlobStorage.getDownloadUrl function.

**Comment by azaslonov** [comment]
Hi @mmcmasterd3, thanks for reporting the issue. We're investigating.

**Comment by azaslonov** [comment]
Issue has been fixed.
