### ISSUE TITLE
OAuth audience value in token prepended with the address of AD when testing authorization in legacy portal

### ISSUE THREAD

**Issue by seekingtheoptimal** [Azure/api-management-developer-portal#343]
## Bug description

We are moving an existing API behind APIM. In APIM, I have set up OAuth 2.0, filled in all the details (implicit flow). The WebAPI is configured to check the aud (audience) value in the token within .AddJwtBearer(...), which is set to the Application ID of the registered app in the AD (as it should according to https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens).
But when the authorization is tested through the portal's "Try it" developer console, it succeeds, but in the token the aud value is not [ApplicationID] but https://[tenant].onmicrosoft.com/[ApplicationID]. This is observed as invalid by the WebAPI of course, and actual calls to the WebAPI cannot be made because of this.

## Reproduction steps

1. (optional step, only if you want to see that api calls really fail with incorrect audience) 
Have a .NET Core WebAPI setup with .AddJwtBearer(options =>
            {
                options.RequireHttpsMetadata = false;
                options.Audience = Configuration["YourAppClientId"];
                options.Authority = $"https://login.windows.net/{Configuration["YourAdTenantId"]}";
            }
2. Create an APIM, setup OAuth 2.0 with implicit flow.
3. Go to APIM developer portal, and try the authorization on any secured API endpoint, select your oauth from the dropdown (the one that was configured in previous step)
4. authorization happens, but the audience value is not just the Application ID, but prepended with the address of the AD (=Application ID URI)

## Expected behavior

Audience value in the token is just the Application ID guid itself

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: [Windows]
 - Browser: [Google Chrome]
 - Version: [e.g., 22]

## Additional context

I am not 100% sure what and where exactly decides in the flow the value of the audience that gets put in the token, but according to https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens documentation: "_In id_tokens, the audience is your app's Application ID, assigned to your app in the Azure portal. Your app should validate this value, and reject the token if the value does not match._" - there is no mention that it should have anything else appended to it before or after it.
Based on this I assume the audience gets decided based on the auth request, which in this case is handled by the developer portal after I select my configured oauth from the dropdown.

Maybe this is a default behavior of APIM when configuring OAuth2 and has nothing to do with the developer portal, but in any case, I would expect to have only the ApplicationID itself in the audience.

Correct token:
![correct audience](https://user-images.githubusercontent.com/17144089/69793627-22e8c400-11c9-11ea-861c-c240cfa71a8f.JPG)

The (possibly) wrong token:
![incorrect audience](https://user-images.githubusercontent.com/17144089/69793666-372cc100-11c9-11ea-9e52-917a7a8f9d1e.JPG)

**Comment by seekingtheoptimal** [comment]
Did some more looking around, and according to [this answer](https://social.msdn.microsoft.com/Forums/vstudio/en-US/06e3b4c7-4230-4573-aa43-fcc1bf0aeabe/audience-in-an-access-token-to-be-app-uri-id?forum=WindowsAzureAD) _"The "AUD" value in the token should match whatever the "Resource" value in the token request is. If you request a token where you specify the resource as an App ID, then you will get an AUD value with a GUID. Otherwise, if you use an App ID URI, you will get the URL back."_

Is there any way to control this in the developer portal, or in APIM for that matter?

**Comment by seekingtheoptimal** [comment]
Just for the sake of completeness, the WebAPI can be set up to handle multiple audiences, just not sure if this should be the good/only solution in this case:
```
options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
{
    ValidateIssuer = true,
    ValidAudiences = new List<string>
    {
        Configuration["AzureAd:ClientId"],                                                      // Application ID     (this is the "normal" one to be used)
        $"https://{Configuration["AzureAd:Domain"]}/{Configuration["AzureAd:ClientId"]}"        // Application ID URI (this is generated in APIM dev portal)
    }
};
```

**Comment by azaslonov** [comment]
Hi @seekingtheoptimal, I agree the documentation is not super clear, but in the [article you provided](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims) they do mention the format of the audience:

![image](https://user-images.githubusercontent.com/2320302/70103025-c8979b00-15ee-11ea-9101-1a0362398d5f.png)
 
Hope that helps.
