### ISSUE TITLE
Developer Portal gives oops while legacy developer portal works fine

### ISSUE THREAD

**Issue by rodsenra** [Azure/api-management-developer-portal#344]
For this portal https://gx-api-mngt.developer.azure-api.net/ after navigating to the API details, the page is rendered but there is a redirect to the /500 Oops page that prevents proper diagnose of the problem.
I was able to capture a screenshot before the redirect.
The same API renders just fine using the legacy portal.

![Screen Shot 2019-11-29 at 9 25 19 AM](https://user-images.githubusercontent.com/533191/69894466-288bfa00-12ee-11ea-8647-e1985a2c9284.png)

**Comment by jjohndrow** [comment]
I am getting this same issue. I created a new api management instance, imported and api. I assigned users, products, subscriptions and it works fine from the legacy portal but not the new portal. When I sign into the new dev portal I get "Oops. Something went wrong. Please try again later".  Any updates would be appreciated.

**Comment by azaslonov** [comment]
Hi @rodsenra, @jjohndrow, thank you for reporting the issue.
It has been fixed by #347. The managed version of the portal is expected to be updated in 2 days.

**Comment by mirsaeedi** [comment]
I ran to this issue today. Is it going to be fixed anytime soon?
