### ISSUE TITLE
Unable to add checkbox button in new developer portal

### ISSUE THREAD

**Issue by techports** [Azure/api-management-developer-portal#346]
Unable to add checkbox button in new developer portal pages.

Able to add only submit button.  

How to add and where to write click event codes.

**Comment by mikebudzynski** [comment]
Can you please explain this scenario? Why do you need a checkbox and what do you want to achieve with it?

**Comment by techports** [comment]
check box required in sign in page where  users must accept the terms and conditions before logging to the portal.  If this check box the checked ,then user will be  prompted to accept the terms and conditions before sing in to developer portal.

one more issue here is unable to add client scripts[java script] and html tags [table tags on the new developer portal.

**Comment by azaslonov** [comment]
Hi @techports, as you figured out, terms consent for the sign in is not supported in managed version. We haven't seen requests like this before, so there is a coulple of things I can suggest:
- submit your request at https://aka.ms/apimwish;
- go self-hosted route: fork this repository and add the required logic;

Hope that helps.

**Comment by mikebudzynski** [comment]
Also, note that the sign-up form contains Service Terms (not the sign-in form)

**Comment by ppotturi** [comment]
OAuth sign-up widget doesn't have Terms of Use, it's only there in the basic Sign-up.
