### ISSUE TITLE
"Required" property is not being displayed for request body parameters

### ISSUE THREAD

**Issue by danpanaite** [Azure/api-management-developer-portal#349]
It looks like the "required" property of my request body parameters is not showing up in the "Operation Details" page.

Currently, the definition body schema is structured as below, where "required" is a list of references to properties:
```
{
    "required": [],
    "type": "object",
    "properties": {}
}
```
Looking at the elements, I see that the request body table is referencing "required" directly on the property instead of the array: 

`<div class="col-1" data-bind="text: property.required"></div>`

**Comment by azaslonov** [comment]
Hi Dan, that's right, schema definition and view model are different entities and they don't (always) match.

Could you please clarify what do you mean by request body parameter here? If possible, using particular examples.

**Comment by danpanaite** [comment]
Hi Alexander, thanks for the fast response.

Using the Swagger Petstore API as an example, I have a POST endpoint to add a new pet to the store. This endpoint takes a `Pet` definition which holds a set of properties. As defined in the schema, the `name` and `photoUrls` properties are required to be set in the request body.

<img width="443" alt="firefox_pyjr61fKBf" src="https://user-images.githubusercontent.com/16643307/70103305-a2262f80-15ef-11ea-820e-fda0cd9a862b.png">
<img width="587" alt="firefox_wSTtol1XwV" src="https://user-images.githubusercontent.com/16643307/70103331-aa7e6a80-15ef-11ea-9176-3aa6d70e002b.png">

When I navigate to the "Operation Details" page for my POST endpoint, the "required" property is not displaying as `true` for the `name` and `photoUrls` properties:

![firefox_rKyXYwr9vh](https://user-images.githubusercontent.com/16643307/70103782-e49c3c00-15f0-11ea-83bd-7af856304a58.png)

Hope this helps!

**Comment by azaslonov** [comment]
Hi Dan, yes, I was able to repro. Let me fix that.

**Comment by azaslonov** [comment]
Fixed. The managed version is expected to be out in the next 2 days.

**Comment by danpanaite** [comment]
Great. Thank you!
