### ISSUE TITLE
Files on blob storage widget

### ISSUE THREAD

**Issue by MassimoC** [Azure/api-management-developer-portal#35]
**Is your feature request related to a problem? Please describe.**
Having a widget to display documents contained in a specific blob container

**Describe the solution you'd like**
Even we are in the age of WIKIs, customers still love PDF documents and Excel files to describe procedures, complex data structures and more.
It would be nice to have a widget that can used at different scopes:
- Global public: all users (authenticated and not authenticated)
- Global for authenticated users only.
- Products (for every products a container named as the product is created)
- Api (for every APIs, a container named as the API is created )

**Describe alternatives you've considered**
As today we configured something like this adding client side javascript to call an api on top of the strage account. I’d prefer have a server side call.

**Comment by azaslonov** [comment]
Update: This feature will be added by General Availability

**Comment by mikebudzynski** [comment]
Feedback from @yashwantsahu05 from https://github.com/Azure/api-management-developer-portal/issues/91 

> Thanks for update, I am looking for feature to manage my resource(Word, PDF, file etc) document. I found option to upload it through Media but I would like to manage is differently.
> 
> Here I am looking to upload my resource file which nothing but help document about my API with some category.
> We require to display resource document on UI. Also would like to filter resource document based on category..
> 
> Above feature is available on Apigee Edge API Platform. Let me know if we have similar kind of feature over APIM.

**Comment by mikebudzynski** [comment]
Thank you for your feedback, Massimo. We won't be able to fit this feature in the scope of the portal's general availability.

As per our new guidelines from the readme file, we now manage feature requests in our Feedback Forum at https://aka.ms/apimwish
