### ISSUE TITLE
User is not able to view APIs when it's subscription type is "All APIs"

### ISSUE THREAD

**Issue by mirsaeedi** [Azure/api-management-developer-portal#354]
## Bug description

It is expected that when a subscription's scope is **All APIs**, then the user should be able to view all apis in the dev portal. But the portal shows "**_No APIs found_**" on the APIs page.

## Reproduction steps

1. Create a user 
2. Assign a subscription with a scope of **All APIs**
3. Explore the portal using the user's credentials

## Expected behavior

The user should see all the APIs.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Edge

**Comment by azaslonov** [comment]
Hi @mirsaeedi, thanks for reaching out. This issue has been fixed by #340. The managed version of the portal is being deployed this week.
