### ISSUE TITLE
Unable to login when the user's email contains a dash

### ISSUE THREAD

**Issue by spyder007** [Azure/api-management-developer-portal#355]
## Bug description

Users are unable to log in when the user's email address contains a dash (-)

## Reproduction steps

1. Invite a user whose email contains a dash
2. Accept the invite and set a password
3. Click sign in
4. Enter the email and password
5. User is unable to login

## Expected behavior

A User with a valid email (including dashes) should be able to log in

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

Managed Release

## API Management service name

acc-apim-stage-alpha

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version:  78.0.3904.108

**Comment by azaslonov** [comment]
Hi @spyder007, thanks for reaching out. This is a known issue, the fix is being rolled out, but this may take a few days.
