### ISSUE TITLE
Missing try it button

### ISSUE THREAD

**Issue by bydynamics** [Azure/api-management-developer-portal#358]
I cannot find the try-it function anymore? Did something change? 

![apim-try-it-missing](https://user-images.githubusercontent.com/53540575/70315893-ce71c400-181a-11ea-9299-a909e34b017b.png)

**Comment by dwall123** [comment]
We've noticed this as well. Took down the latest to get the fix for #344 and the Try_It button has disappeared

**Comment by azaslonov** [comment]
Hi @bydynamics, @dwall123, thanks for reporting the issue. It has been fixed.
