### ISSUE TITLE
Controlling when the subscription check happens in azure API management

### ISSUE THREAD

**Issue by nathanvv** [Azure/api-management-developer-portal#360]
In Azure API Management, Azure portal provides a way to configure the "subscription required" in the setting of the APIs. However is it possible to control when this validation occurs. Currently it happens before it hits the inbound policies. Would I be able to set it to happen after certain inbound policies are executed. Else is there a way to control the trigger of the validation from the policy level?

**Comment by nathanvv** [comment]
Also tied to see if I can do 
        <rate-limit-by-key  calls="10"
              renewal-period="60"
              counter-key="@(context.Subscription.Key)"/>

Is that valid?. If so getting a "rate-limit-by-key Policy is not allowed in this sku 'Consumption'"

**Comment by VitaliyKurokhtin** [comment]
There is no way to control that. Subscription key check happens before any part of the policy is invoked. Why do you want to control that behavior?

**Comment by nathanvv** [comment]
@VitaliyKurokhtin : Thanks for the response. The subscription key is embedded in the API key that we are providing. I am decoding the custom key to obtain the subscription key in the inbound policies. Now I want to validate if the subscription key is valid and do rate limiting based on that

**Comment by VitaliyKurokhtin** [comment]
Yeah, we heard this scenario before. Please, submit it here: http://aka.ms/apimwish For now though subscription key is required to be passed either as a header or as a query parameter. You can make your API/product not require subscription key at all and do your own auth check in policy followed by rate-limit. This is usually done for certificate or OAuth.

**Comment by nathanvv** [comment]
@VitaliyKurokhtin: I did try disabling the is required check. However, we would also want to throttle requests based on the subscription key. If I do the rate-limit as a policy, is there a way to read the subscription limit based on the subscription key.

**Comment by VitaliyKurokhtin** [comment]
With "Require subscription" disabled APIM will not look for or validate subscription key, so context.Subscription will be null. But you can use any other data available in context to calculate your rate-limit key. Parts of OAuth token can be used easily, or client IP, or anything really.

**Comment by jbizcloud** [comment]
Any update on this please. 2024 Nov ;)
