### ISSUE TITLE
Responses are not shown unless they have a return type

### ISSUE THREAD

**Issue by spyder007** [Azure/api-management-developer-portal#361]
## Bug description

Response description for an operation are only shown if they have a valid schema definition.  Responses which only have a description set are not shown.

## Reproduction steps

1. View the Echo Api's GET endpoint in the old portal and compare it to the new portal view.
2. Note that the Responses section in the old portal has an entry for 200 OK, but the new portal has no responses at all.

## Expected behavior

All responses should be displayed as part of the Operation Details

## Is your portal managed or self-hosted?

Managed

## API Management service name

accc-apim-feature-alpha

## Environment

 - Operating system: Windows
 - Chrome

## Additional context

Add any other context about the problem here, including screenshots.
![image](https://user-images.githubusercontent.com/4701399/70474453-9ed3ed80-1aa0-11ea-8448-7b57a76d7318.png)

![image](https://user-images.githubusercontent.com/4701399/70474468-a72c2880-1aa0-11ea-9974-738ebeb556e9.png)

**Comment by azaslonov** [comment]
Hi Matt, Thank you for reporting the issue. It has been fixed in #362.

**Comment by spyder007** [comment]
> Hi Matt, Thank you for reporting the issue. It has been fixed in #362.

Alexander,
Thank you so much for the quick response.  Is there any documentation regarding the release cadence for the managed portal roll outs?  I'm just trying to determine when I might be able to see this and other fixes rolled out to managed portals.

Thanks again
Matt

**Comment by azaslonov** [comment]
Hi Matt,
There is no specific cadence. As soon as we accumulate enough fixes, and integration tests passed, we release it. On average this happens every week or so.

Hope, that helps.
