### ISSUE TITLE
Calling an api secured by apim gateway from developer portal

### ISSUE THREAD

**Issue by cadabloom** [Azure/api-management-developer-portal#365]
We are trying to implement some customizations on our developer portal and we are trying to call a custom api secured through apim gateway. 

On the client site, we only have the basic user authentication and we saw that we could generate a shared access token for a given user. But we have some questions below regarding the shared access token generated for a user. 

Is there a mechanism to validate the shared access token in the backend or azure apim rest api? 
Is there an api we could use to get user information based on the shared access token that was generated?

Thank you in advance

**Comment by azaslonov** [comment]
Hi Freddie,
You can call `/identity` with the token in the `Authorization` header to see if it is valid.

For user information, there are several endpoints starting with `/users/{userId}`, like
`/users/{userId}/subscriptions` or `/users/{userId}/groups`. Please refer to [the documentation](https://docs.microsoft.com/en-us/rest/api/apimanagement/) for more details
