### ISSUE TITLE
Blank header values

### ISSUE THREAD

**Issue by ExpoundDS** [Azure/api-management-developer-portal#366]
Headers without values are affecting results. For example, we have a header named 'DataOwner' that has no default value populated in portal. When default, we receive a 404, despite it being an optional parameter and the backend API operation setting the default value to null. However, if a value is added to the header the removed after calling the API, the call returns a 200. It would appear that values might be injected into the header if blank, in the developer portal.

**Comment by azaslonov** [comment]
Hi @ExpoundDS, thanks for reporting the issue, we'll fix this shortly.
