### ISSUE TITLE
Styling of elements in a visual  editor

### ISSUE THREAD

**Issue by romm333** [Azure/api-management-developer-portal#368]
Is it possible to add more options for the customization of the elements, selection in a visual editor?  For example, I am editing a home page template. I would like to add a section above the content. I add section from one of the available options. That creates an empty section with an article inside. The Article panel is not expandable, located in the middle of the screen, I cannot edit the width or height of it. I need to extend it to the same size as a content panel below. Preferably without creating of a self-hosted version.  This question is possible duplication of closed #151

**Comment by azaslonov** [comment]
Hi @romm333, this question comes up pretty often. A few things here:
You can change sizes of a section and grid container inside it, and the grid ("article" is part of it) will adapt according to the pre-defined _configuration_. This might solve your problem (or part of it).

Besides that, we're working on grid editor which will allow you to change that _configuration_ (unfortunately, I can't provide ETA just yet).
