### ISSUE TITLE
Question: How often does the managed version receive updates?

### ISSUE THREAD

**Issue by dudelis** [Azure/api-management-developer-portal#370]
I have seen a number of releases in the current repo. Also I noticed, that v.2.0.0 is a GA version. Afterwards, there are a couple of minor version.
So which releases are pushed to the central repo of the manged version and become available across all portals of Azure API Management Service?

**Comment by mikebudzynski** [comment]
We suggest that you always use the latest version for self-hosted. 2.0.0 is the GA version and the releases after it contain bugfixes and additional features.

Managed version is updated automatically and follows the same releases. It may take a week or two for the managed version to update to the latest release.
