### ISSUE TITLE
Display of SOAP Services

### ISSUE THREAD

**Issue by velsietis** [Azure/api-management-developer-portal#371]
There's currently nothing on the [roadmap](https://github.com/Azure/api-management-developer-portal/projects/4) that relates to the display of SOAP APIs

In the new portal:
- Operation URLs each display with the `soapAction` query parameter.  The legacy portal displays the same URL for each.
-  API Definition does not display WSDL as an option (it does in the legacy portal).

Is there a plan to add this functionality into the new portal?

**Comment by azaslonov** [comment]
Hi @velsietis, yes, we're working on it.
