### ISSUE TITLE
Restoration of the portal content generates issues in the portal

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#378]
Hi,
I have customized the portal with a logo in the default layout.
I have extracted the content thanks to the node scripts.
I have a data.json file and a content directory where I can see the media I have uploaded into the portal (the file name is a GUID with no extension).

When I cleanup the portal (reset content) and upload the data.json and content folder directory into the portal, it works but the picture from the content file is missing. It is uploaded into the portal content but it sounds like because it has no extension, it is not rendered as a picture into the media of the portal and thus I have an error in the portal designer:
![image](https://user-images.githubusercontent.com/10268596/70973575-312e4f80-20a6-11ea-962a-fdc7a0ed409d.png)

**Comment by azaslonov** [comment]
Hi @dgrospelier, thanks for reporting the issue and sorry for the late response.

I could not repro it, so could you please send your service name to apimportalfeedback@microsoft.com, we'll take a close look.

**Comment by azaslonov** [comment]
Hi @dgrospelier, do you still need help with the issue?

**Comment by dgrospelier** [comment]
Hi,
No I think I got mistakes in my scripts, I have now fixed it.
