### ISSUE TITLE
Try it > Add parameter or Add header links result in the Oops page

### ISSUE THREAD

**Issue by DavidFreetly** [Azure/api-management-developer-portal#381]
The Try It feature on any API operation brings up a side panel with the options to + Add Header and + Add Parameter.  Clicking on either of these links results in the 'Oops, something went wrong' page.

Here is the console trace that I was able to capture from Chrome Dev Tools.

![Screen Shot 2019-12-18 at 3 09 13 PM](https://user-images.githubusercontent.com/4295769/71123494-67ec8e80-21a8-11ea-8059-a111f8c17e7c.png)

I am using the managed version of the new Developer Portal and I get the same error on Chrome, Firefox and Safari.

## Reproduction steps

1. Go to any Api and choose any operation
2. Click on the 'Try it' button
3. Click the '+ Add parameter' or '+ Add header' link
4. See the 'Oops, something went wrong' page.

## Expected behavior

I expect to be able to add a key/value pair for a header or query string parameter

**Comment by azaslonov** [comment]
Hi David, thanks for reporting the issue. We'll fix it shortly.

**Comment by azaslonov** [comment]
David, the managed version has been updated as well. Please re-publish the portal to pickup fixes.

**Comment by DavidFreetly** [comment]
Thank you for the quick fix!
