### ISSUE TITLE
How do I preview actual API Detail pages?

### ISSUE THREAD

**Issue by ngobw** [Azure/api-management-developer-portal#384]
I am reviewing the new developer portal and while the portal is on a live preview concept, I am unable to see how my API content will be displayed. Is there a way I can preview the entire portal without being in editing mode? Thanks!

**Comment by azaslonov** [comment]
Hi @ngobw, the "preview mode" feature is planned. However, you can see your API content in the design mode even now. For example, by holding Ctrl (Windows) or ⌘ (Mac) button, you can interact with the portal as you would do with its published version, navigate to API details page, etc.

Hope that helps for now.

**Comment by ngobw** [comment]
Nice, I wasn't aware of that! Thanks!
