### ISSUE TITLE
No dropdown list for enum parameters

### ISSUE THREAD

**Issue by yinlaurent** [Azure/api-management-developer-portal#385]
Hello,

I have observed a small difference in functionnality between the old and the new developer portal.

## Bug description

The new developer portal does not provide a dropdown list for enumeration parameters in header.

## Reproduction steps

1. Import the [swagger.txt](https://github.com/Azure/api-management-developer-portal/files/3998410/swagger.txt) in Azure API Management (it is a yaml definition so you may rename the file extension properly).
2. In the old development portal, we have a dropdown list for the header Gender in the operation POST Add a new pet to the store. 
<img width="895" alt="Developer portal legacy" src="https://user-images.githubusercontent.com/6747194/71415548-8812c680-265c-11ea-964e-a21deb2a03d8.png">
3. In the new developer portal, when we try the operation, we do not get the dropdown list for the header. 
<img width="804" alt="New developer portal" src="https://user-images.githubusercontent.com/6747194/71415615-d88a2400-265c-11ea-918d-5afe76078456.png">

## Expected behavior

We expect a dropdown list in the new developer portal, that makes it easier for developers trying our APIs.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser: Google Chrome, Edge

**Comment by azaslonov** [comment]
Hi @yinlaurent, thanks for reporting the issue.
