### ISSUE TITLE
Management REST API is not returning the URL of the new Dev portal

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#386]
I'm calling this API (https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/apimanagementservice/get) in order to retrieve the Custom Domains URL of my APIM instance. I have the Management URL for example and also the Developer (legacy) URL but unfortunately not the New Developer Portal URL in the hostNameConfigurations section of the result.

**Comment by azaslonov** [comment]
Hi @dgrospelier, thanks for reporting the issue, we'll see what we can do.

**Comment by azaslonov** [comment]
@dgrospelier, looks like we do support it in version `2019-01-01` of Management API. Is this a version you use? Also, what do you use? REST API or PowerShell?

**Comment by dgrospelier** [comment]
Yes you are right, using the 2019-01-01 version of the API works fine.

**Comment by azaslonov** [comment]
Great! Thanks for confirmation.
