### ISSUE TITLE
Not able to force HTTPS on the developer portal

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#388]
I want to force HTTPS on the Developer Portal but there are no configuration settings for that.
By default, HTTPS is used by the browser but when I change it manually in the URL and switch to HTTP I don't have a redirection to HTTPS which is what I'm looking for.
I'm using the Managed version of the developer portal.

## Reproduction steps

1. Go to the developer portal
2. Change the HTTPS to HTTP and refresh.

**Comment by azaslonov** [comment]
Hi @dgrospelier, thanks for reporting the issue. We'll fix this on the server-side.

**Comment by azaslonov** [comment]
The fix has been done on APIM service backend and comes out with the next release. Please allow it about 3 weeks to be applied to your service.

**Comment by dgrospelier** [comment]
Hi,
Is it now released? The January 2020 release is now out, not sure it is included in it, could you please confirm?

**Comment by mikebudzynski** [comment]
The release is still being rolled out. The fix should reach your service in 1-2 weeks.

**Comment by Harjindar** [comment]
How long will it approximately take to roll out to all existing instances? Our instance in West Europe has not yet got this fix.

**Comment by azaslonov** [comment]
Should be out during next week.

**Comment by lungosta** [comment]
our APIM is hosted in West US and I'm still able to browse our developer portal over HTTP.

@azaslonov do you know when it will be enforced in West US?
