### ISSUE TITLE
[META] Page load speed improvements 

### ISSUE THREAD

**Issue by s8mathur** [Azure/api-management-developer-portal#391]
## [META] Page load speed improvements - meta bug

The page load speed of the new developer portal can be easily improved by adopting standard performance practices. The following were observed by running the foo.developer.azure-api.net developer portal link through the WebPageTest.org test harness: 

1 . GZIP compression is not used by the server 

2. The theme's static assets are not served with Cache-Control headers (max-age and expires)

3. CDN is not used for static assets or image assets

![page-load-speeds](https://user-images.githubusercontent.com/5669765/71798231-4ed45080-3077-11ea-943a-b43a32cbcbfa.jpg)

Out of the above (1) and (2) are really easy to do, and should done quickly in the hosted APIM configuration (i.e NOT the self-hosting configuration)

## Reproduction steps

1. Go to webpagetest.org, and paste link of any managed developer portal: e.g `foo.developer.azure-api.net`
2. Run test in default configuration (Dulles, VA test client + any Azure region APIM developer portal) 
3. See 'F' grade in content serving. 

## Expected behavior

_A_ grade in "compress transfer", and "cache static content" categories on WebPageTest.org test results

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

Managed version as of 6-Jan-2020

## API Management service name

Any

## Environment

Any browser

## Additional context

Page loading speed is critical for public-facing developer portals.

**Comment by azaslonov** [comment]
Hi @s8mathur, thanks for reporting the issue. We'll see what we can do.

**Comment by mikebudzynski** [comment]
Headers have already been added; compression still pending implementation.

**Comment by AnRei123** [comment]
Today and the last week, the loading speed of DevPortal pages was a nightmare for different environments. The speed is varying from immediately if part of the cache up to several minutes for switching between single pages.
A high and consistent page load speed is crucial to get a good user experience. Currently, it is like an old car you try to start when you switch between pages. Could work properly or could take forever.

**Comment by AnRei123** [comment]
The last hour it was published once.

**Comment by mikebudzynski** [comment]
@AnRei123 We're investigating the issue.

**Comment by s8mathur** [comment]
Closing as this has been open too long, and I am the OP.
