### ISSUE TITLE
Model definition names are overflowing into the description

### ISSUE THREAD

**Issue by michaeltnguyen** [Azure/api-management-developer-portal#393]
## Bug description

This appears to be a UI bug.  In the "definitions" section of an endpoint description, if the model name is long, it flows into the "description" section.

Screenshot:

![Screen Shot 2020-01-06 at 1 20 51 PM](https://user-images.githubusercontent.com/14219683/71842652-c1e5c300-3087-11ea-9b14-233df56e989f.png)

## Reproduction steps

This is visible on our "new" developer portal.

https://dev-hcss-api-gateway.developer.azure-api.net/api-details#api=heavyjob&operation=post-api-v1-purchaseorders-purchaseorderid-details-custom

## Expected behavior

I would want the model name to be ellipsized, like it is on the rest of the page.

![Screen Shot 2020-01-06 at 1 28 37 PM](https://user-images.githubusercontent.com/14219683/71842962-741d8a80-3088-11ea-97ad-f247abc65c39.png)

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: macOS catalina
 - Browser: Chrome
 - Version: 79.0.3945.88

**Comment by azaslonov** [comment]
Hi @michaeltnguyen, thanks for reporting the issue. We'll take care of this.

**Comment by azaslonov** [comment]
Fixed. Please allow it about a week to reach the managed version.

**Comment by michaeltnguyen** [comment]
awesome, thanks for the quick response!
