### ISSUE TITLE
OAuth SignUp always redirects back to SignIn

### ISSUE THREAD

**Issue by adefalque** [Azure/api-management-developer-portal#396]
## Bug description

I'm trying to integrate B2C Signin / Signup with the new portal.

Sigin is working fine, I've dropped the Sign In:OAuth button on a Signin page, and I'm able to click on the button that opens the B2C signin page.

Now I'm trying to use the Sign Up:Oauth widget. I've dropped the widget on a SignUp page in the portal. When I try to navigate to the Signup page in the published version of the portal, this always redirects me back to the SignIn page.

## Reproduction steps

1. Open the published portal
2. Go to SignUp page containing the Signup:Oauth widget
3. Signup is displayed for 1sec and you are then automatically redirected back to the Signin page containing the Sign In:OAuth widget

## Expected behavior

The SignUp page should be displayed and I should be able to Signup with a new user using B2C.

## Is your portal managed or self-hosted?

Managed

## API Management service name

Prefer not to give

## Environment

 - Operating system: Windows 10
 - Browser: Firefox

**Comment by azaslonov** [comment]
Hi @adefalque, yeah the name of the "OAuth: Sign up" widget is confusing (we'll change it). Basically, its purpose is to complete the signup in APIM, so the flow looks like this:

A user signs in with the identity provider (and, if needed, creates an account in it) using **OAuth: Sign in** widget. Then, with received *id_token*, gets redirected to a page with **OAuth: Sign up** widget (in default template it is `/signup-oauth`). This widget, which is basically a registration form (prefilled with information from *id_token*), helps to collect/confirm the information required to create a user in APIM.

If **OAuth: Sign up** doesn't see *id_token*, it redirects the user to `/signin` page (this is the behavior you describe).

Both sign in and sign up processes start with **OAuth: Sign in** widget.

Hope that helps.

**Comment by TravisLRiffle** [comment]
> Hi @adefalque, yeah the name of the "OAuth: Sign up" widget is confusing (we'll change it). Basically, its purpose is to complete the signup in APIM, so the flow looks like this:
> 
> A user signs in with the identity provider (and, if needed, creates an account in it) using **OAuth: Sign in** widget. Then, with received _id_token_, gets redirected to a page with **OAuth: Sign up** widget (in default template it is `/signup-oauth`). This widget, which is basically a registration form (prefilled with information from _id_token_), helps to collect/confirm the information required to create a user in APIM.
> 
> If **OAuth: Sign up** doesn't see _id_token_, it redirects the user to `/signin` page (this is the behavior you describe).
> 
> Both sign in and sign up processes start with **OAuth: Sign in** widget.
> 
> Hope that helps.

On the sign up page that I'm redirected to for the OAuth: SIgn Up widget, I get a: 
Failed to load resource: the server responded with a status of 403 (Forbidden)

Any idea what's going on here?

**Comment by JCAMPOLPA** [comment]
Hello

Sorry, still confused on how to make happen /signup-oauth and using the Oauth widget - can you detail a bit the procedure please ?

**Comment by robofan69** [comment]
Hi,
i have the same issue and I didn't figure out how to signup a new user. When not existing it can't signin when then the user is clicking to the signup page it's redirected to the signin page. How can I make the user to signup. 

It the solution that i use in AzureB2C a signin/signup user flow instead of using a seperate sign in and sign up user profile?

Thank you for your support

**Comment by mikebudzynski** [comment]
@robofan69 Please, reach out to Azure support for assistance.
