### ISSUE TITLE
[OAuth SignUp Widget] Invalid Api Management Url

### ISSUE THREAD

**Issue by adefalque** [Azure/api-management-developer-portal#397]
## Bug description

I'm trying to integrate our Api Management portal with Azure B2C.
Using the OAuth:SignUp widget, when clicking on the SignUp button, nothing happens. When I open the browser console, I can see that the page is trying to do an HTTP POST to the Api Management Url, but the Url is invalid:
POST https://myapim.management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/users?api-version=2018-06-01-preview 403 (Forbidden).

## Reproduction steps

1. Click on SignIn OAuth button
2. Register a new account with B2C and click SignUp in popup window
3. User is redirected to the /signup-oauth page on the portal
4. Fill user info in the page, and click SignUp button
5. Nothing happen. Error in console

## Expected behavior

Click on Signup button should properly create the user in Api Management.

## Is your portal managed or self-hosted?

Managed

## API Management service name

Prefer not to give

## Environment

 - Operating system: Windows 10
 - Browser: Firefox, Chrome, Edge

**Comment by azaslonov** [comment]
Hi @adefalque, could you please check if you have Object ID in your app claims:
![signin-signup policy](https://user-images.githubusercontent.com/2320302/72094445-4ffdbb80-32cb-11ea-9062-f0c8fd28ca78.PNG)

If after that you still have the issue, please mail us your service name and HAR file capturing the sign-in session to apimportalfeedback@microsoft.com, we'll have a closer look.

**Comment by azaslonov** [comment]
Closing it due to inactivity. Please feel free to reopen if the recommended steps do not help.

**Comment by adefalque** [comment]
Thanks @azaslonov that fixed the issue.
