### ISSUE TITLE
Menu disappears in mobile view

### ISSUE THREAD

**Issue by BobbyCGD** [Azure/api-management-developer-portal#401]
## Bug description

When viewing the website on a mobile device such as a phone (smaller resolution) the menu dissapears. 

When using the developer tools in Chrome, it seems that the element to expand the menu is there but there is no glyph to show that there is a menu. In addition when clicking the element the menu does not push content down, instead the area becomes scrollable and a sidebar appears if the cursor is in the menu and you scroll with the middle mouse button.

## Reproduction steps

1. Open the portal in Google Chrome
2. Open the devtools - F12
3. Press the 'Toggle Device toolbar' button - Ctrl+Shift+M
4. Any resolution below 600px by (n) works. 

## Expected behavior

Obvious button to expand menu is visible. Menu is visible when expanded.

## Is your portal managed or self-hosted?

Managed and Self-hosted

## Release tag or commit SHA (if using self-hosted version)

Latest version

## Environment

 - Operating system: [Android, iOS]
 - Browser: [Google Chrome] - others not tested
 - Version: [latest]

## Additional context

Changing the size of the logo or removing it completely does not affect the behaviour of the bug.

In DevTools look for 

```
<button class="collapsible-toggle hamburger" aria-label="Toggle" data-toggle="collapsible">
        <i class="icon icon-menu-8"></i>
</button>
```

![image](https://user-images.githubusercontent.com/9389935/72157731-8b25ea80-33b0-11ea-9cbd-18e0f20f4531.png)

**Comment by azaslonov** [comment]
Hi Bobby, thanks for reporting the issue. We'll fix this soon.

**Comment by azaslonov** [comment]
Fixed in #415. However, there is still a lack of customization control for the "hamburger" button (e.g. you can't change its color). That will be fixed soon as well.

**Comment by ZarTrox** [comment]
I'm trying to understand how this "hamburger"-button feature is implemented. Because when using the developer tools in Chrome, it seems that the hamburger button does not show and the menu items just stack upon each other.
Thanks in advance.

**Comment by azaslonov** [comment]
Hi ZarTox, not sure I understand what you mean. Would you please provide a screenshot?

**Comment by BobbyCGD** [comment]
@azaslonov can you provide an update on your previous comment, please?

> However, there is still a lack of customization control for the "hamburger" button (e.g. you can't change its color). That will be fixed soon as well.

**Comment by azaslonov** [comment]
Hi @BobbyCGD, unfortunately, it is not ready yet. I'll update this Issue a bit later with ETA.

**Comment by createitreal** [comment]
@azaslonov , is there any progress on this front? I'd like to be able to change the color of the hamburger icon. 
Also, it would be great if it was possible to change the background color of the menu in mobile mode along with the text color. And please do something about how the menus are centered in the mobile view:
![image](https://user-images.githubusercontent.com/58592689/76944228-f1734000-6900-11ea-96bc-71ffa87ea029.png)
We can't control at the moment, actually, we can't control a single thing about it! The button to close it is not clear because it's also in "black", so you can't recognize it.

**Comment by azaslonov** [comment]
Hi @createitreal, there is a pre-requisite we're waiting on - an ability to adjust global styles depending on the viewport. This will enable customizing the hamburger as well. That should be done in the next 2-3 weeks.

Regarding the alignments, yes, we'll fix that soon.

**Comment by ArkimeraMattias** [comment]
Any update on this issue?

Our Azure managed portal is still not showing the menu correctly and prohibits us from having a mobile friendly development portal.

**Comment by azaslonov** [comment]
Hi @ArkimeraMattias, yes, there is some progress. In the next release, we're shipping a concept of Popups, which brings much more flexible options for addressing scenarios like mobile menus (and many others). You'll be able to customize a popup as you need (position, alignment, padding, background, borders, backdrop, etc.) and assign it to any linkable trigger (button, menu item, etc.). 

The popups and visibility (on different form factors) option will eventually replace the "collapsible panel" widget (which is obviously hard to configure). So, using this approach (plus Menu snippets and docs), you'll be able to customize the "hamburger" button itself (which is just a regular Button with a popup attached) and how your menu appears on mobile (which is a regular Menu widget placed on the popup).

**Comment by mrtuck2** [comment]
Any Fix for the mobile menu? This is one of the worst wiziwigs ive ever used. If I even change the position of the mobile menu to be centered I get a menu pop up behind the slide out menu. When you delete what you think is a brand new menu this will delete the menu for the home page. There should be a settings panel just for the mobil menu. I want to change the color of the menu bars to white and stack the menu items over each other without changing the menu in other views.

**Comment by Aspmyra** [comment]
Any news regarding this issue?

**Comment by azaslonov** [comment]
@Aspmyra, the current ETA for new menu configuration is 3/1.

**Comment by Aspmyra** [comment]
> @Aspmyra, the current ETA for new menu configuration is 3/1.

Lovely. May I ask on the side if there will be any new configuration for the tab-panel?

**Comment by azaslonov** [comment]
@Aspmyra, not sure I follow. Are you referring to some specific issue?

**Comment by Aspmyra** [comment]
> @Aspmyra, not sure I follow. Are you referring to some specific issue?

Yes, I was referring to the fact that there are no indication of which tab in the tab panel that is active. It is not connected to the hamburger icon issue.

ETA was 3/1 last year, how is it going?
