### ISSUE TITLE
Could not find model binder for widget type "USERSIGNUP

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#402]
I am currently using the legacy developer portal and wanted to try the new one. When clicking through the pages to edit, the signup page renders the below error. All other pages appear to be working fine.

![image](https://user-images.githubusercontent.com/8837910/72188814-1b176480-33b0-11ea-88df-4dec05aa4b04.png)

Let me know if there is anything more I can provide.

**Comment by michaeltnguyen** [comment]
you might need to reset the portal and republish.  I had a similar issue.  (we were using the legacy portal for a while, and it seems like the "new" portal didn't pick up code changes until reseting content).

**Comment by azaslonov** [comment]
Hi @krispenner, I believe your service has been created before GA? If yes, can you please just delete the widget and add it back again?

**Comment by azaslonov** [comment]
Right, resetting the portal is even better. Thanks, @michaeltnguyen!

**Comment by krispenner** [comment]
Thank you for our suggestion and fast response. I tried performing a reset and I am told to try again later.

I had invoked a publish website operation about 15 minutes ago. Maybe that is still processing and a reset cannot happen yet? The website URL still says "Developer portal has not been published yet." Do you know how long a publish should take? Would this cause the rest to fail?

![image](https://user-images.githubusercontent.com/8837910/72189651-3edbaa00-33b2-11ea-9667-112b2f5084cc.png)

**Comment by krispenner** [comment]
Hmm regardless of the error that the reset failed. It seems to have occurred anyways. I now have a fresh site and many more pages to select and edit than I did earlier.

This looks good so far so I will see how I go. Thanks again!

**Comment by azaslonov** [comment]
Great, thanks for confirming this. Publishing usually takes a few seconds. We'll work on better visual feedback for this process.

I guess I can close the issue for now.

**Comment by Colbz** [comment]
Resetting the content worked for me! Everything works out of box now

**Comment by Mdshakeelse** [comment]
Hi All,I am facing similar issue in Popup ,But don't want to reset the developer portal.Is there any other way to fix it
![image](https://user-images.githubusercontent.com/20789239/218008251-c40b37f6-d46c-44e8-a905-3aedb8c04c59.png)
