### ISSUE TITLE
Feature Request: Set Authorized Pages

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#403]
Please let me know if this is already achievable.

I would like certain pages to be for authorized (signed-in) users only, such as /products and /apis.

I can move navigation menu items around to be under the authorized users group which hides/shows the menu items based on their sign-in status, however, users can still go to the actual pages via URLs themselves.

It would also be great to show/hide sections or text elements based on authorized status. So on the Home Page I can show a "You must be signed in to view APIs and productions" for anonymous users but hide it for authorized users.

I am aware we can force all anonymous users to the sign-in page and this is what we are currently doing. But it would be nice to allow anonymous users to also view the home page and possibly our contact us page we are going to add.

**Comment by mikebudzynski** [comment]
@krispenner - thanks for raising this feature request. At this moment, the portal doesn't allow for scoping the pages to logged in users only. We will consider it for future.

For now, as a workaround you can create a custom widget that fetches data from a 3rd party source. The source can check whether a user is authenticated.

As per our guidelines, we ask to open feature requests at https://aka.ms/apimwish so I'll close this issue.

**Comment by krispenner** [comment]
Thank you for your reply and thanks for pointing me in the right direction. I have found this exact feature request for anyone else who wants to vote for it!

https://feedback.azure.com/forums/248703-api-management/suggestions/39141355-ability-to-secure-new-developer-portal-pages

**Comment by mikebudzynski** [comment]
> For now, as a workaround you can create a custom widget that fetches data from a 3rd party source. The source can check whether a user is authenticated.

I forgot to mention that the documentation is coming soon (a week or two).
