### ISSUE TITLE
Redirect anonymous users to sign-in page is ignored after signing out

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#405]
## Steps to reproduce
1. Enable **Redirect anonymous users to sign-in page** in the Azure Portal for the API M instance.
1. Go to developer portal
1. Redirected to sign-in page
1. Sign in
1. Redirected to home page
1. Sign out
1. **Remain at home page**
1. Click APIs nav menu link
1. **API listing page is shown**

## Expected
1. Enable **Redirect anonymous users to sign-in page** in the Azure Portal for the API M instance.
1. Go to developer portal
1. Redirected to sign-in page
1. Sign in
1. Redirected to home page
1. Sign out
1. **Redirected to sign-in page**
1. Click APIs nav menu link
1. **Redirected to sign-in page**

## Comments
After 10 minutes or more I'm finally redirected to the sign-in page.
Seems some sort of caching is occurring in the CDNs maybe, even a forced full refresh does not work. Although permissions are being applied on the APIs themselves, all my APIs are restricted by group access so the anonymous user sees no APIs or products but the pages are still loading and they should not be.

**Comment by ppotturi** [comment]
Hi, I am also facing the same issue. When I click on Sign-out it's redirecting to the home page instead of the sign-in page.

I think the Auth cookie is not immediately expiring after sign-out. The home is accessible until the cookie is expired, but when I am trying to access the profile page it's immediately redirecting to the sign-in page.

**Comment by ygrik** [comment]
This issue was fixed with the current release, please republish dev portal to get the latest updates.

**Comment by krispenner** [comment]
This appears to be working great now, thanks for the fix!
