### ISSUE TITLE
Question: Can I export and import?

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#406]
We have test and production API Management instances, I would like to keep them looking and behaving the same. Is there a way to export all content, media, styles from one and import it into another?

The new portal does not yet look like it's been integrated with the git repo, I only see what appears to be the old portal styles and templates there.

Thank you for your help.

**Comment by mikebudzynski** [comment]
For the time being, we don't integrate with Git, but you can use the underlying REST API: https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services

Note: If you're using a managed portal, there's also a script to generate a storage SAS URL from a connection string.
