### ISSUE TITLE
Long endpoint description pushes detail text off screen.

### ISSUE THREAD

**Issue by michaeltnguyen** [Azure/api-management-developer-portal#407]
## Bug description

This is a UI issue.  When the description for an endpoint is long, the text does not wrap, so it pushes content off the screen.

![Screen Shot 2020-01-13 at 11 35 01 AM](https://user-images.githubusercontent.com/14219683/72278045-c581c880-35f8-11ea-88cd-3b8ae0a768fd.png)

## Reproduction steps

This is viewable on our developer portal instance.

https://developer.hcssapps.com/api-details#api=setups&operation=post-api-v1-ratesetgroup

## Expected behavior

I would like the text to wrap onto multiple lines, or ellipsize.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: macOS catalina
 - Browser: Google Chrome
 - Version: 79.0.3945.88

**Comment by azaslonov** [comment]
Hi @michaeltnguyen, thanks for reporting the issue, we'll fix this.

**Comment by azaslonov** [comment]
Fixed in #415.

**Comment by michaeltnguyen** [comment]
As a temporary workaround, anyone else who is running into this issue can check the "content overflow" box on the api list.

The UI is still a bit clunky (you can't scroll horizontally until you hit the bottom of the api list), but it's still better than having the api list take 90% of the page.

![Screen Shot 2020-02-05 at 2 37 21 PM](https://user-images.githubusercontent.com/14219683/73880993-2c278a00-4825-11ea-9f1f-ba83e108f3dc.png)

**Comment by CoHealer** [comment]
Checking in. Is there an upcoming release train for this?

**Comment by michaeltnguyen** [comment]
@CoHealer another workaround we found is to use both a <summary> and <remarks> tag on the endpoint.  The summary is what's displayed on the left, but the remarks are still displayed on the right.

At least until it's fixed.  :)

**Comment by azaslonov** [comment]
Fixed in self-hosted. Managed is coming in next release.
