### ISSUE TITLE
Preload post/put body with example data

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#410]
I spent a lot of time adding example values to every single model property so our customers can see real sample requests and responses in the documentation when using the portal. The legacy portal also used these example values of each property to preload the body of the request when interactively trying the APIs through the browser. The new portal does not appear to support this yet. This would be a top priority enhancement for us as it allows users to just click Try It and then Send which is a huge feature for them. Please let me know if this can be added sooner than later.

## New Portal Empty Body
![image](https://user-images.githubusercontent.com/8837910/72324644-43c58580-3660-11ea-8ec4-9d019dfe614c.png)

## Legacy Portal Example Body
![image](https://user-images.githubusercontent.com/8837910/72324704-5f309080-3660-11ea-84ca-2dfdbb7301e6.png)

## Legacy Portal Sample Documentation
The legacy portal also showed sample data in the documentation area, maybe a new column could be added to list example data for each property of a model?
![image](https://user-images.githubusercontent.com/8837910/72324780-8f782f00-3660-11ea-8a50-66bebadc5de9.png)

Thanks so much! Great work so far on the new portal! Having pre-populated sample data based on the example values in the API spec is really needed in my opinion.

**Comment by azaslonov** [comment]
Hi @krispenner, hmm, we do pre-load body from request example:
![image](https://user-images.githubusercontent.com/2320302/72368318-b3fcf700-36b2-11ea-8929-9a7f33c712e2.png)

Probably something else happening specific to your API. Can you please send us your service name to apimportalfeedback@microsoft.com

**Comment by krispenner** [comment]
@azaslonov sent thanks!

**Comment by azaslonov** [comment]
Hi @krispenner, here's the thing: the legacy developer portal generates the example out of schema and, specifically, "example" fields, but the new developer portal renders examples attached either to the request body or to the definition referenced by the request.

You can easily generate en example of your request body, or better definition, by using a helper command:
![image](https://user-images.githubusercontent.com/2320302/72552556-f7d73400-384b-11ea-925e-e80accec29e6.png)

**Why we do it this way?**
This way customers can control how the example looks like (for example, you might not need to show all the fields defined in the schema), at the same time we keep an ability to generate those examples (just with a small additional step).

Hope that makes sense.

**Comment by krispenner** [comment]
Hi @azaslonov, thank you for your response. I'd like to keep this issue open as a bug, specifically because the Open API Specification states that examples provided higher should be used but fallback to examples lower down the chain when not provided.

> _if referencing a schema which contains an example, the example value SHALL override the example provided by the schema._

So in my case, since I did not provide an example on the request body, it should instead look at the request object and if no example there, it should generate one based on the properties of the request object and use any examples defined on them and so on down the line.

In the meantime, I will update my requests to provide generated examples at the request level so I can get this working today. However, this is a lot of work to maintain going forward when APIs change, for most developers I'd assume it is easier to provide example on each property in code and have it generated so you should definitely consider implementing as per the specs noted above.

Your thoughts?

**Comment by azaslonov** [comment]
We may implement the auto-generation in the future, with a specific setting in API details for this. Of course, please feel free to contribute.

**Comment by azaslonov** [comment]
I added a separate item for tracking: #423

**Comment by krispenner** [comment]
OK sounds good. I don't think you need a specific setting for this though, it should just automatically fallback on its own.

**Comment by Harjindar** [comment]
I think this issue should be re-opened. I created a Basic Tier for production. The example is set using example property (Open API 2.0 example property under definition). I see this value pre-populated in Azure Portal in example as shown in the message above:
![image](https://user-images.githubusercontent.com/37382131/74281027-f94a2e00-4d1d-11ea-8956-97c9931fba18.png)

But this is not loaded in the actual developer portal when using try-it functionality.

**Comment by azaslonov** [comment]
Hi @krispenner, you're right, we need to take this case into account for Test console as well.

**Comment by Harjindar** [comment]
Hi @azaslonov,
Did you mean @krispenner or me in your previous comment? :-)

**Comment by azaslonov** [comment]
Oh, yes, I apologize @Harjindar  :). @krispenner please disregard.

**Comment by Harjindar** [comment]
No worries :D

**Comment by Harjindar** [comment]
Hi,
Is the issue planned to be fixed as it is important from the usability perspective?

**Comment by Harjindar** [comment]
Just wondering if any ETA is known for this?

**Comment by azaslonov** [comment]
Hi everyone, we just merged changes for representation generation on both UI and backend. However, the backend will still need to be deployed, and the release starts this week, finishing in a week or two. The UI will be deployed next week. Thank you for your patience.

**Comment by ikteru** [comment]
It's 2 weeks later and the request body doesn't automatically get populated with the example data.

**Comment by krispenner** [comment]
@ikteru I think you can also read [here](https://github.com/Azure/api-management-developer-portal/issues/423#issuecomment-642345247)

That was just 5 days ago, it also seems to suggest you will need to re-import your APIs schemas in order for example data to be generated.

**Comment by ikteru** [comment]
@krispenner, I did re-import the APIs. It does use the examples I defined in the Open API yml file. However, it still doesn't populate the body of the request when you use "try it". Which this issue is about. And according to @azaslonov in the previous comment, this issue is closed and they "merged changes for representation generation on both UI and backend". So, I'm guessing, by UI he means the developer portal UI.

**Comment by Harjindar** [comment]
I can confirm that the issue is **not** resolved. Updated the api with the swagger doc having examples but still the the request is not prepopulated.

I'm see other bugs (https://github.com/Azure/api-management-developer-portal/issues/527) are also being closed but they are not resolved. Please close the issues when these are resolved for the customers. We are waiting patiently for quite a while and then when issues are resolved without verifying the status, it does not give a good impression.

**Comment by ikteru** [comment]
I can confirm the request body being automatically populated. 
I tested it this morning and it's working fine.

**Comment by Harjindar** [comment]
Initally the example was not being populated. But publishing the portal again did the trick

**Comment by iTiamo** [comment]
This is still an issue for me. I've populated all properties with examples and yet the request body remains empty.

**Comment by mikebudzynski** [comment]
@iTiamo Could you send your service name and the API id to apimportalfeedback@microsoft.com?

**Comment by mustaqt** [comment]
Hi, I have imported the json file generated with swagger with example tag for request and response but developer portal does not populate the exmple.
Can you please share what needs doing to  display  it on developer portal as its very important for my client to see the example.

**Comment by mikebudzynski** [comment]
@mustaqt, please contact Azure Support - they will be able to assist you, based on your service configuration.
