### ISSUE TITLE
Definitions listing table - poor column sizing

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#411]
Please expand the Description column of the Definitions listing table, I have some descriptions that are much longer than my example shows as well which is just wasted space there.

![image](https://user-images.githubusercontent.com/8837910/72327866-bd607200-3666-11ea-9567-ee765c3ac3dd.png)

Thank you.

**Comment by azaslonov** [comment]
Hi @krispenner, thanks for reporting the issue, we'll fix that.
