### ISSUE TITLE
Basic Authentication on sign in page doesn't seem to work

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/api-management-developer-portal#412]
When I sign in with basic authentication, the developer portal redirecta me, but leaves me unauthenticated.

When going to the sign in page again, redirection directly happens.

Because of this, I'm not able to navigate to pages for which you need to be signed in, like API Reference page

**Comment by azaslonov** [comment]
Hi Sahin, please send us your service name to apimportalfeedback@microsoft.com.

**Comment by mikebudzynski** [comment]
@SahinOzdemir - please follow an Issue template next time. It helps us respond to your problems faster.

**Comment by SahinOzdemir** [comment]
Didn't have time te respond earlier. I just sent you the apim service names to mail.

**Comment by SahinOzdemir** [comment]
It now seems to work. Did you made any changes?

**Comment by azaslonov** [comment]
Hi Sahin, sorry for the late response. Actually no, we didn't do any changes, probably something got fixed on your side.

I'm closing the issue then.
