### ISSUE TITLE
API gallery link to API not working

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/api-management-developer-portal#413]
When I go the API Gallery, and I click on an API card, nothing happens. It seems to add a querystring to the URL, but I don't get to see the API details (what I would expect to happen)

![Untitled](https://user-images.githubusercontent.com/7938059/72336536-41474800-36c1-11ea-89f8-06268c36d745.png)

**Comment by azaslonov** [comment]
Hi Sahin,

I wonder if you have specified the API details page URL:
![image](https://user-images.githubusercontent.com/2320302/72367330-e60d5980-36b0-11ea-9129-8dd336149ede.png)

**Comment by SahinOzdemir** [comment]
Hi, just checked this and indeed there was no details page.
I created it, but still it's strange that this doesn't come out of the box.
