### ISSUE TITLE
Not able to download WSDL of SOAP Service in Developer portal

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/api-management-developer-portal#419]
When i select an API, I cannot download the WSDL, which was possible in the old developer portal.

![image](https://user-images.githubusercontent.com/7938059/72428574-4a521b00-378e-11ea-98dc-176b9e41f94b.png)

**Comment by azaslonov** [comment]
Hi Sahin, thanks for reporting the issue. We'll fix this.

**Comment by SahinOzdemir** [comment]
Thanks! When will the fix be available?

**Comment by mikebudzynski** [comment]
It's already available in the self-hosted version. It will become available in the managed version in a week or so.
