### ISSUE TITLE
Response: Cross-Origing Resource Shareing not enabled on server when trying service

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/api-management-developer-portal#420]
When I want to try an operation from the developer portal I get the following exception/response:
**Unable to complete the request**
Since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server. Learn more

I would expect this to work out of the box, just as in the new portal.
![image](https://user-images.githubusercontent.com/7938059/72433648-1846b600-379a-11ea-9973-66522338884b.png)

**Comment by mikebudzynski** [comment]
This is by design: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal#im-getting-a-cors-error-when-using-the-interactive-console

You can open a feature request at https://aka.ms/apimwish
