### ISSUE TITLE
Complete SignUp redirection issue

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#422]
## Bug description

After an Azure B2C sign-in, and for the first time, we need to complete a SignUp form in order to create the User in API Management.
When we Send this form, we have a 403 forbidden because the portal tries to post the form to this url : https://management-dev.thuasne.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/users?api-version=2018-06-01-preview

Place holders "xxx" are not replaced by real values.

Sound like it comes from this line of code: https://github.com/Azure/api-management-developer-portal/blob/31417796809292a1bc2a3e8b971f0b5205bdfe2e/src/utils.ts#L300

## Is your portal managed or self-hosted?
Managed

**Comment by azaslonov** [comment]
Hi @dgrospelier, those "xxx" is just a placeholder, when MAPI gets accessed directly, it doesn't look at those values. This is a temporary solution, and this is done for ARM compatibility, don't worry about this one.

Regarding 403, there might be something else, for example, there might be missing Object ID in application claims configured for your API. Please check this:

![signin-signup policy](https://user-images.githubusercontent.com/2320302/72553974-a8dece00-384e-11ea-91ea-f2ae38e85454.PNG)

If you still have the issue after that, please send us your service name and AAD application manifest
to apimportalfeedback@microsoft.com and reference this issue number.

Thank you.
