### ISSUE TITLE
Add example generation option for schema using "example" properties of each field.

### ISSUE THREAD

**Issue by azaslonov** [Azure/api-management-developer-portal#423]
In absence of request example and schema example, it still can be generated using "example" property of each field in a definition (similarly as in legacy developer portal).

**Comment by TerenceSansom** [comment]
Not sure why this item is open and #410 is closed (410 has more details) .   I agree this would be a very handy feature.  I will investigate adding it, but I am new to KO ... someone else might be better to tackle  ha

**Comment by azaslonov** [comment]
Hi Terence,

It is open to avoid confusion: The request body is actually filled with example *when it is defined*, that's why #410 (which was reported as a bug) got closed. This one is still open because the inferred automatic generation feature not implemented yet (and this will be an improvement).

**Comment by azaslonov** [comment]
Generation of example on API import has been implemented on the backend and it is coming out in the release that is already on-going.

**Comment by martinsamanek** [comment]
Hi @azaslonov 

If I understand this correctly, the backend should automatically generate the example on API import now. This should be propagated to the portal and displayed in Try It Console in Body.

I've just tried to import [PetStore](https://petstore.swagger.io/v2/swagger.json). And examples are not filled in backend and also not in the portal.

[https://apimoritest.developer.azure-api.net/api-details#api=petstore&operation=addPet](https://apimoritest.developer.azure-api.net/api-details#api=petstore&operation=addPet)
![image](https://user-images.githubusercontent.com/43401497/117252529-63308500-ae46-11eb-98a3-20310bc4760a.png)
![image](https://user-images.githubusercontent.com/43401497/117252662-93782380-ae46-11eb-90c6-d18163f4ea18.png)

Could you please explain this to me?

**Comment by mikebudzynski** [comment]
@martinsamanek, we're just starting to roll out a fix for it. It will take several weeks for the release to complete.
