### ISSUE TITLE
Response representation samples are not appearing on API documentation page

### ISSUE THREAD

**Issue by vincehorst** [Azure/api-management-developer-portal#424]
I've added a response representation sample for an API endpoint via the APIM in Azure Portal. A tab appears on the API endpoint's documentation page where the representation should be shown but the representation is not actually present.

![image](https://user-images.githubusercontent.com/1152384/72568509-2addef80-386d-11ea-9a46-0a781b328d66.png)

![image](https://user-images.githubusercontent.com/1152384/72568610-62e53280-386d-11ea-99e7-27468d594e74.png)

**Comment by azaslonov** [comment]
Hi @vincehorst, just in case, when did you publish the portal last time? If more than 2-3 weeks, it might be missing some fixes. Please try that and, if the issue still there after that, please send us your service name to apimportalfeedback@microsoft.com. Thank you.

**Comment by vincehorst** [comment]
Hi @azaslonov! I have just republished the portal and confirmed that the issue is still present. The sample is not being shown.

**Comment by azaslonov** [comment]
Ok, please send service name.

**Comment by vincehorst** [comment]
@azaslonov do you mean that you want me to email you the URL and login credentials for the affected API Portal to apimportalfeedback@microsoft.com, so that you can see it for yourself?

**Comment by azaslonov** [comment]
No, just the name of APIM service.

**Comment by vincehorst** [comment]
I have emailed the name of the APIM service.

**Comment by azaslonov** [comment]
Fixed.

**Comment by vincehorst** [comment]
Hi @azaslonov! I republished my developer portal this morning and the fix for this issue appears not to have made it out to the managed Developer Portal in Azure Portal. Can you confirm or deny?

**Comment by jvarugh** [comment]
@vincehorst +1 this is not working for me either. It renders nothing.

**Comment by vincehorst** [comment]
@azaslonov should this ticket be reopened? I don't see that it's actually fixed in Azure Portal.
