### ISSUE TITLE
Unable to subscribe to a product

### ISSUE THREAD

**Issue by adefalque** [Azure/api-management-developer-portal#427]
## Bug description

I'm using a Subscriptions page, with the "List of products" widget.
Listing the products works fine. When I click on the product, it displays below a small section with a text "Your new" and a cut button "Subscribe":
![SubscribeBugPortal](https://user-images.githubusercontent.com/8939280/72597674-7eece080-390e-11ea-9c17-58f64069a78f.PNG)

So 2 issues there:
- the small section to subscribe to the product is wrongly displayed
- clicking on the "Subscribe" button does not do anything. The button seems to be disabled. I dont see any error in the browser console.

## Reproduction steps

1. Sign to the portal
2. Go to Subscriptions page
3. Click on a product you're not subscribed yet
4. Try to click on the Subscribe button

## Expected behavior

Click on the subscribe button should properly subscribe the user to the product.

## Is your portal managed or self-hosted?

Managed

## API Management service name

Prefer not to give here

## Environment

 - Operating system: Windows 10
 - Browser: Firefox, Edge

**Comment by BobbyCGD** [comment]
Hi @adefalque 
> clicking on the "Subscribe" button does not do anything. The button seems to be disabled. I dont see any error in the browser console.

To make the Subscribe button work you have to first type in a name in the text box. I also didn't notice this at first and confused me. Maybe the workflow can be changed? For example the user clicks 'Subscribe' and then they are asked to enter a name for the subscription. That would definately be a good improvement.

I do agree with 

> the small section to subscribe to the product is wrongly displayed

There should be better styling maybe min-width and make the button go under the text field?

**Comment by mikebudzynski** [comment]
This issue has been resolved a few months ago.
