### ISSUE TITLE
No value for URL parameters will result in invalid API call in APIM Dev Portal

### ISSUE THREAD

**Issue by rkraveesh** [Azure/api-management-developer-portal#429]
Issue Description: 
The APIM Dev Portal which is  failing to validate the mandatory URL parameter. While testing the API from APIM Test console and we do not put any parameter, then try to send the request, it throws field required validation error. But when the same API is tested with Developer portal, it is not throwing the field required validation error and carries URL Parameter variable name along with the URL. This results in invalid API call.

**Comment by mikebudzynski** [comment]
The bug was been fixed a few months ago.
