### ISSUE TITLE
Problems migrating Portal between subscriptions

### ISSUE THREAD

**Issue by rbarbany** [Azure/api-management-developer-portal#431]
Hello,

We are using the migrate.bat script, to migrate our managed environment from DEV to PRO and we always reproduce the same error, the portal is lost.

## Reproduction steps

1. Configure vars in migrate.bat
2. run migrate.bat
3. Go to Api Management Portal Overview and open "Developer Portal" 
4. The portal does not load properly. Only footer is displayed correctly.

## Expected behavior

Have the same Developer Portal as in dev

## Is your portal managed or self-hosted?

Managed

## API Management service name

     source: apim-suez-dev
     target: apim-suez

## Environment

 - Operating system: Windows
 - Browser: Chrome
 - Version: [e.g., 22]

## Additional context

Migrate bat output:
![migrate bat](https://user-images.githubusercontent.com/48022352/72758579-7a0c8300-3bd3-11ea-8810-db1c610c4a1e.png)
![upload](https://user-images.githubusercontent.com/48022352/72758820-2189b580-3bd4-11ea-8023-6cab44232ace.png)

Developer Portal error:
![2020-01-20 22_25_50-API Management](https://user-images.githubusercontent.com/48022352/72758726-e8514580-3bd3-11ea-889c-584a8732e75a.png)

Thanks and regards

**Comment by ygrik** [comment]
It was a bug in the script. The script starts to download media content from blob storage and exit without upload.
