### ISSUE TITLE
Error in Edge browser bug when scrolling down the page

### ISSUE THREAD

**Issue by velsietis** [Azure/api-management-developer-portal#437]
## Bug description

Error in Edge browser bug when scrolling down on the API Detail page

## Reproduction steps

1. Create an API Management instance
3. Publish the developer portal
4. Visit the developer portal in Edge browser
5. Use the scroll bar to scroll down the page  - BOOM!

## Expected behavior

Would expect no error, just some regular old scrolling action.  Instead some error causes a redirect to the 500 page - **Oops, something went wrong**

## Is your portal managed or self-hosted?

Managed

## API Management service name

dhew-nwis

## Environment

 - Operating system: Windows 10
 - Browser: Edge
 - Version: Microsoft Edge 42.17134.1098.0

**Comment by azaslonov** [comment]
Hi @velsietis, thanks for reporting the issue. I could repro, will fix this.
