### ISSUE TITLE
New DevPortal - typing empty spaces does often not work with Firefox

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#439]
## Bug description
After typing in some sentences, adding/modifying lists and other elements, suddenly typing in empty spaces with the keyboard using the Firefox browser isn´t possible while writing a sentence. Even after saving the DevPortal the error persists. Sometimes only one text block is affected, sometimes several or all text blocks are affected. With Chrome this error did not occur until now.  (see attachment below)

## Reproduction
I do not know how to reproduce the error nor what the root cause exactly is. Often the error occurs after adding and modifying a bulleted list in a text block.

## Environment
- managed portal
- Latest Firefox version 68.4.2esr (32-bit)
- Operating system: Windows 10

## Expected behavior
- Empty spaces can be successfully typed in any text field with any of the supported browser - even in bulleted lists (including Firefox).

## Attachment
Zipped video that shows how the issue looks like

[2020-01-27_10-46-20.zip](https://github.com/Azure/api-management-developer-portal/files/4117376/2020-01-27_10-46-20.zip)

**Comment by azaslonov** [comment]
Hi @AnRei123, thanks for reporting the issue. I was able to reproduce the issue on Firefox (72.0.2). As you said it happens after adding the bulleted list to the text block. We'll see what we can do about it.

**Comment by mikebudzynski** [comment]
The issue has been fixed a few months ago
