### ISSUE TITLE
Not able to log in the site after deploying it to static website in storage account

### ISSUE THREAD

**Issue by jerryanto** [Azure/api-management-developer-portal#442]
## Bug description
https://catalystdevportal.z13.web.core.windows.net/
Not able to login to the new developer portal in the self-hosted site.
Getting an invalid username or password.
But I am able to login to the portal from the azure tap.

## Reproduction steps
1. Publish the code locally
2. Deploy the code to storage account.
3. Get the static website URL and visit the site
4. Go to Sign In page and try to log in.

## Expected behavior
The application should get logged in.

## Is your portal managed or self-hosted?
Self-hosted

## Release tag or commit SHA (if using self-hosted version)
release 2.0.0

## API Management service name
catalystdev

## Environment
Operating system: Windows 10
Browser: Google Chrome
Version: 79

**Comment by azaslonov** [comment]
Hi @jerryanto, could you please capture network traces into HAR file and send it to apimportalfeedback@microsoft.com?

![image](https://user-images.githubusercontent.com/2320302/73294707-2e516f00-41bb-11ea-827e-68da0151ece7.png)

**Comment by azaslonov** [comment]
Hi Jerry,
Since we resolved it offline, I'm closing the issue for now. Please feel free to re-open, if further assistance needed.
