### ISSUE TITLE
OAuth SignUp 403 response

### ISSUE THREAD

**Issue by simonness** [Azure/api-management-developer-portal#443]
## Bug description

I've followed the steps to integrate B2C Signin / Signup with the new portal.
https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad-b2c

Sign in works fine, but on the complete sign up page I see the error message `Server error. Unable to send request. Please try again later.`

caused by a HTTP 403 response to https://my-api-name.management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/users?api-version=2018-06-01-preview

(note the xxx are in the call made, see screenshot).

Is there some additional setup with products or subscriptions I'm missing?

## Reproduction steps

1. As above

## Expected behavior

OAuth Sign up to complete.

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

Prefer not to say.

## Environment

 - Operating system: Windows
 - Browser: Google Chrome

## Additional context

![image](https://user-images.githubusercontent.com/10990813/73279982-2bbc3d00-41ee-11ea-80f8-6112cd266612.png)

**Comment by azaslonov** [comment]
Hi @simonness, can you please check that you have included User's Object ID into AAD application claims?

![image](https://user-images.githubusercontent.com/2320302/73292990-e54beb80-41b7-11ea-81db-079f03deafd2.png)

Please feel free to re-open this issue if the problem doesn't go away after that.

P.S. xxx is just a placeholder that used in direct MAPI calls, this is a temporary solution.

**Comment by simonness** [comment]
Hi @azaslonov thanks for getting back to me!

I should have mentioned that our case is slightly more complicated as we're using Identity Experience Framework to display a custom login page and inject extra claims.  Our SignInOrSignUp policy is based on:

https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/SocialAndLocalAccounts/SignUpOrSignin.xml

And has the lines:

`<OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="sub"/>`

and 

`<SubjectNamingInfo ClaimType="sub" />`

Could this be the cause of the issue?

**Comment by simonness** [comment]
@azaslonov I've updated the policy to also include:

`<OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="oid"/>` 

and it did the trick.  Thanks very much for the push in the right direction!

I couldn't spot anything in the [documentation ](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad-b2c) covering this, might be worth updating?

**Comment by azaslonov** [comment]
Hi @simonness, thank you for confirming this.
You're right, we added a work item to update documentation, thanks!

**Comment by petenorth** [comment]
The documentation still doesn't include this information.

Also it would help enormously if the exact claim names were listed so that the 'Complete Sign Up' screen does not appear (not sure if that is even possible.)

Thanks.

**Comment by azaslonov** [comment]
Hi @simonness, sorry, if I remember correctly, my reply was about that missing screenshot which shows that ObjectID is required, and which is now there in the docs.

Regarding IEF, we don't really have expertise in it and what's covered in that article is just the most common B2C scenario. Though we may revisit it at some point.
