### ISSUE TITLE
Self hosting the portal - Step 3: Provision the default template - Clarification

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#444]
In the wiki, starting [at Step 3](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-3-provision-the-default-template): _Provision the default template for Self hosting the portal_, it begins to get a bit messy in terms of explanation and reasoning. 

Could the following be elaborated?

The **generate.bat** mainly does 2 things:
- Uploading **/contentTypes/blob/contentItems** to the Content management part of the APIM Management API.  Which is a one time thing you have to do, just like the first time you open the developer portal in the managed version, correct? In what way are we depended on the Content management API after we've set up the self hosting portal?
- Uploading your files in the **media** folder to your self-hosted Blob Storage. Which, at step 5, in the image, this is called the **Development media files**, correct? This is also a one time thing you have to do, correct?

Next, at step 5, the dependency on your own Blob Storage is displayed for the  **Development media files**. When editing locally, why is there a dependency for those media files in your blob, when we have them locally already?

**Comment by azaslonov** [comment]
Hi @erwinkramer,

Your local development environment is just a pre-cursor for self-hosted production setup. In production, designers will need to talk to an API for data and a Storage for media.

So, answering your questions:
>Uploading /contentTypes/blob/contentItems to the Content management part of the APIM Management API. Which is a one time thing you have to do, just like the first time you open the developer portal in the managed version, correct? In what way are we depended on the Content management API after we've set up the self hosting portal?

The designers will still need Content Management API (unless you implement some kind of [static source of data](https://github.com/paperbits/paperbits-demo/blob/master/src/components/staticObjectStorage.ts), i.e. like at [demo.paperbits.io](https://demo.paperbits.io)).

> Uploading your files in the media folder to your self-hosted Blob Storage. Which, at step 5, in the image, this is called the Development media files, correct? This is also a one time thing you have to do, correct?

This is more like "sample" media files, and yes it is done one time, just to help you to start quicker (setting everything up from scratch would be a painful process).

> Next, at step 5, the dependency on your own Blob Storage is displayed for the Development media files. When editing locally, why is there a dependency for those media files in your blob, when we have them locally already?

For the same reason as content data, which needs to be fetched from somewhere. By default, it is fetched from Content API (and media fetched from Blob Storage), but again, going back to demo.papersites.io, it could be fetched from anywhere else. There is just a couple of interfaces that determine the sources: IObjectStorage (data) and IBlobStorage (media).

I hope that answers it. Please feel free to comment/reopen shall you need further clarifications.
