### ISSUE TITLE
Product list page doesn't interpret HTML in the description. 

### ISSUE THREAD

**Issue by rachel-langford** [Azure/api-management-developer-portal#446]
## Bug description

In the list of products widget, if there is html markup in the description, the mark up is rendered, not interpereted. Eg the description includes the html tags for ul and il etc. rather than getting bullet points.

(In the api list widget, html in the description is interpereted as you would expect).

## Reproduction steps

1. Go to Products
2. Look at the descriptions 

## Expected behavior

Html tags do not appear in the text, instead they are interpreted and the text is formatted as per the Html tags.

## Is your portal managed or self-hosted?

Managed 

## API Management service name

emi

## Environment

Browsing on Chrome from Windows 10.

Two images attached. One for APIs (shows Html interpretted) and one of Products (Html tags visible). The same descriptions in the old portal render html correctly for both APIs and Products.

![image](https://user-images.githubusercontent.com/49261001/73391153-4a304e80-433c-11ea-89d6-6de5912676a1.png)
![image](https://user-images.githubusercontent.com/49261001/73391213-60d6a580-433c-11ea-90fe-493af1a77e3b.png)

**Comment by azaslonov** [comment]
Hi Rachel, thanks for reporting the issue. We'll fix it shortly.

**Comment by azaslonov** [comment]
Done. The fix will land to the managed version sometime next week.

**Comment by rachel-langford** [comment]
8 months on and this bug has not yet been fixed. HTML on the products page is still coming through as raw html.

Am I able to please have an update on this issue please? We have been holding off on switchiing to the new portal because of this issue, and now I see legacy portal access has been removed from the Azure portal.

![image](https://user-images.githubusercontent.com/49261001/91239467-aef93d80-e793-11ea-9001-9a6887bb9612.png)

**Comment by azaslonov** [comment]
Hi @rachel-langford, have you republished the portal since then?

**Comment by rachel-langford** [comment]
Thanks @azaslonov  - I have now republished, and that has changed the rendering to markdown on that field. As content  automatically updates without a republish, it wasn't clear that a publish was necessary for field property changes.

However now I notice that the changelog field for the APIs also needs to be set to markdown

![image](https://user-images.githubusercontent.com/49261001/91240196-6e9abf00-e795-11ea-8479-99c7d0500276.png)

**Comment by azaslonov** [comment]
I see, we'll fix this in next release then. Thanks.

**Comment by azaslonov** [comment]
Just made the change.

**Comment by rachel-langford** [comment]
Wonderful thank you @azaslonov
