### ISSUE TITLE
A wizard for non web people

### ISSUE THREAD

**Issue by mikaelsand** [Azure/api-management-developer-portal#45]
I love the new portal and I love the freedom I have to design the portal so that it looks more "me". However I think a lot of users might find the design experience a bit too much.

Perhaps you could add a wizard, or a couple of templates that are configurable.

1. Choose a layout.
2. Choose colors (or skip)
3. Upload images, logo and such (or skip).
4. Fill in some basic information (company name etc).
5. Boom! Site created!

**Comment by mikebudzynski** [comment]
Although the wizard has not been implemented yet, we have prepared a short video tutorial on customizing the portal: https://aka.ms/apimdevportal/tutorial

**Comment by mikebudzynski** [comment]
@mikaelsand Thanks for this great suggestion. It does make a lot of sense and we'll keep it in mind for future, but we won't be able to implement it in the coming weeks. As per our latest guidelines in the readme file, feature requests need to be now moved to our Feedback Forum at https://aka.ms/apimwish
