### ISSUE TITLE
Using B2C with Linkedin IDP bug in "complete sign up" page (email field not mapped correct)

### ISSUE THREAD

**Issue by bengimblett** [Azure/api-management-developer-portal#450]
## Bug description

The scenario is that B2C is configured in Identities (as IDP for the new dev portal)

Linked in is configured as an IDP for my B2C tenant 

I have " Sign up and sign in v2 " policy with linkedin (and only that) as the IDP

Once logged in (through linked in via B2C) for the first time I am redirect back to the new dev portal to the "complete sign up " page (expected) 

BUT although firstname and lastname fields are correctly filled in the "email" field is empty - and this is the problem
(Note: This does all does work if I switch back to the original dev portal.)

Here's the abridged token - as you can see the "email addresses" collection does contain my email address 

{
  "exp": 1580303711,
  "nbf": 1580300111,
  "ver": "1.0",
  "iss": "https://begimb2cdemo.b2clogin.com/8d956e99-xx/v2.0/",
  "sub": "24eb64cf-xx",
  "aud": "97b44958-xx,
  "nonce": "e45e0b30-d8d5-45b9-aedb-0d3ce6b106ab",
  "iat": 1580300111,
  "auth_time": 1580300111,
  "given_name": "benjamin",
  "family_name": "gimblett",
  "idp": "linkedin.com",
  "name": "ben gim",
  "emails": [
    "bengimblett@yahoo.com"
  ],
  "tfp": "B2C_1_begimlinkedinsigninup"
}
## Reproduction steps

See above

## Expected behavior

Email field is populated from emails app claim

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

demobegimapim

## Environment

 - Operating system: [e.g., iOS] - Windows10
 - Browser: [e.g., Google Chrome, Safari] - Google/Edge
 - Version: [e.g., 22]

## Additional context

Looks like you're looking for "email" in the JWT not the "emails" app claim collection??

 https://github.com/Azure/api-management-developer-portal/blob/265d0fc8b5ff3eff963ba5e10db0134c609b6710/src/components/users/user-signup-social/ko/runtime/user-signup-social.ts 

  this.firstName(jwtToken.given_name); 
this.lastName(jwtToken.family_name); 
this.email(jwtToken.email);

**Comment by azaslonov** [comment]
Hi Ben, thank you for reporting the issue. We'll see what we can do.

**Comment by lucaszacutti** [comment]
Hi Ben / Alexander, we have similar issue using Google, the email is not filled and also we got and error when we click on "Sign Up".
![image](https://user-images.githubusercontent.com/13422243/73674508-6d863100-468f-11ea-9878-6acfdef43723.png)
Did you finish the sign up process flow?
The 2nd problem is that when user already exist is redirected too to the "Complete Sign Up" page.
Do you tested that?

**Comment by kennethdm** [comment]
We are experiencing more or less the same problem as Ben G. has reported when trying to connect our Azure B2C to the identity of the new developer portal.
Any update on a fix?

**Comment by mikebudzynski** [comment]
@lucaszacutti and @kennethdm are you still experiencing this issue?

**Comment by lucaszacutti** [comment]
Hi @mikebudzynski we have decided to use developer portal in a very limited approach because we have had some issues and our risks analisys's conclution was to not move forward with this tool. We have three main reason 1) lack support to localization/regionalization 2) auth integration with google based domain and 3) some issues using new layouts in design mode. Personally I see a big potencial/flexibility with this tool and surely we will considere develop custom widgets it in the future. Thanks for your kind support

**Comment by mikebudzynski** [comment]
Thanks for the feedback. Localization is on our roadmap.

**Comment by MassimoC** [comment]
I have a similar error with AAD B2C "Could not complete the request. Please try again later." and I was wondering whether I should address this with a support request or there is a bug with the developer portal.
![image](https://user-images.githubusercontent.com/8393694/91750019-aa34ef00-ebc2-11ea-8a64-c0fc7526aee6.png)
