### ISSUE TITLE
Request body "description" is not displayed on the Portal

### ISSUE THREAD

**Issue by vincehorst** [Azure/api-management-developer-portal#452]
When a body description is entered into the APIM in Azure Portal, the description is not displayed on the Microsoft-hosted built-in Developer Portal.

![image](https://user-images.githubusercontent.com/1152384/73554040-dbb4c480-43ff-11ea-9123-de9cad6b4533.png)

![image](https://user-images.githubusercontent.com/1152384/73554395-79a88f00-4400-11ea-8395-104e3ae6198b.png)

**Comment by ygrik** [comment]
@vincehorst thank you for submitting the issue
