### ISSUE TITLE
Support API Management Monetization

### ISSUE THREAD

**Issue by hbcondo** [Azure/api-management-developer-portal#454]
Is there a way to monetize ours APIs using this new developer portal? This was possible in the original developer portal but it would be great to see an integrated solution with this.

**References:**

- https://feedback.azure.com/forums/248703-api-management/suggestions/5922492-add-monetization-ability-of-api
- https://azure.microsoft.com/en-us/blog/how-to-monetize-apis-with-azure-api-management/
- https://github.com/Azure/api-management-monetization

**Comment by azaslonov** [comment]
Hi @hbcondo, even in the legacy portal there is no specific support for monetization scenarios, and all the options come to the usage of Management API. The same approach is going to work for the new developer portal too.

As you can see at aka.ms/apimwish, the integrated solution is planned, but no specific ETA for now.

**Comment by hbcondo** [comment]
Hi, @azaslonov. I know you closed this issue last year but the Azure feedback site has the [Add monetization ability of API](https://feedback.azure.com/forums/248703-api-management/suggestions/5922492-add-monetization-ability-of-api) feature request tagged as `PLANNED` since 2018. Would you consider re-opening this issue for sake of visibility and hopefully getting a follow-up from Azure Feedback? Thanks.

**Comment by mikebudzynski** [comment]
@hbcondo, you can monetize the APIs in the new portal in the same way you could monetize them with the deprecated portal. We're now working on a new piece of content around monetization. We also have monetization improvements on the roadmap, most likely for 2022.
