### ISSUE TITLE
Editing text from visual editor gives oops

### ISSUE THREAD

**Issue by decisaoin** [Azure/api-management-developer-portal#455]
After setting locally a self hosted portal release 2.2.0 following the steps described in https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal precisely I was able to npm start the portal but as soon as I tried changing the text "Welcome to Contoso" I've got an "Oops something went wrong".

The text editor popup doesn't allow me to type anything. The prompt cursor never change from mouse pointer. All I can do is clicking the formatting options like italic for exemple and when I do that I got the Oops.

during the setting up steps all went ok.

I also tried changing the label of the buttons and save. That work totally fine and the changes on the labels persisted the next time I started the server.

My environment is:
macOS Catalina
node -v v12.14.1
npm -v 6.13.4
Safari

**Comment by azaslonov** [comment]
Hi @decisaoin, thanks for reporting the issue. Looks like the issue is Safari-specific. We'll fix that.

**Comment by azaslonov** [comment]
@decisaoin, unfortunately, I could not reproduce it on Catalina/Safari 13. However, we rolled out updates, including text editor recently, so things could change.

Could you please try it again and, if the bug still reproduces, please send us your service name to apimportalfeedback@microsoft.com, maybe it something specific to your service.

**Comment by decisaoin** [comment]
Hi @azaslonov thanks for checking that out. I've tested also with chrome and I've got the same behaviour. Later on I've used the release 2.2.1 and got also the same issue with the Text Editor.

I will be sending my service name to apimportalfeedback@microsoft.com as you suggested and then I come back here with any update on this.

**Comment by azaslonov** [comment]
Hi @decisaoin, did you have a chance to send us an email? I don't seem to find it.

**Comment by decisaoin** [comment]
Hi @azaslonov I just did. Thanks for the remind

**Comment by azaslonov** [comment]
Yep, got it. Thanks!

**Comment by mikebudzynski** [comment]
The issue was fixed a few months ago.
