### ISSUE TITLE
Where to find Media information in New Developer Portal 

### ISSUE THREAD

**Issue by VarshneyNaupada** [Azure/api-management-developer-portal#457]
Hi Team,

I am new to Azure Developer portal(New), I am trying to add images in Media lib in Portal. But if I am trying to push changes to higher environments it is not happening. Please tell me the steps to push the Developer Portal changes to higher environments and also where do the image storage happens in  Portal ?

**Comment by michaeltnguyen** [comment]
What do you mean by higher environments?  There is a migration script to move content that is described on the wiki here: https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services.  Images are stored in blob.

After running the migration script, you have to re-publish the portal.

**Comment by VarshneyNaupada** [comment]
Higher environments meant to be Dev - Production. I have uploaded images in Developer Portal, but could not be able to see them in any blob storage or any other storage.

**Comment by azaslonov** [comment]
Hi @VarshneyNaupada, when you upload images they get to APIM service internal storage. As @michaeltnguyen mentioned, there is a [migration script](https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services) that should take care of it. Have you tried that by chance?

To help you better, can you please describe the steps that you do propagate the changes to another environment?

**Comment by VarshneyNaupada** [comment]
I have tested the script, but somehow it is not working for me.
Steps: 
1. I have created API Management in Resource group 1 and modified Contoso images with my files and uploaded them in API Management Developer Portal under Resource group1.
2. I have generated SAS Token in Management API under Resource group 1
3. I have created a new API Management2 in Resource group 2
4. I have generated SAS Token in Management API 2 under Resource group 2
5.  Now used migrate.bat file with updated values of SAS tokens and ran it from my local machine.

There is no change in API Management even in terms of messages or data inside the pages.

Kindly help me to resolve this issue.

**Comment by michaeltnguyen** [comment]
Did you specify the storage account in the migrate script, as described here?  https://github.com/Azure/api-management-developer-portal/wiki/Retrieve-managed-portal-storage-account

Have you tried publishing Management API 2?

I used the script yesterday and it worked fine.

**Comment by VarshneyNaupada** [comment]
I have tested it, able to capture the error logs. It is expecting some folders like capture, generate, cleanup 

I am trying to use migrate.bat in command prompt. Is it the way or any other way I need to do?

Error: Cannot find module 'C:\Users\Varshney.Naupada\Documents\capture'
Error: Cannot find module 'C:\Users\Varshney.Naupada\Documents\cleanup'
Error: Cannot find module 'C:\Users\Varshney.Naupada\Documents\generate'

'az' is not recognized as an internal or external command,
operable program or batch file.

**Comment by VarshneyNaupada** [comment]
Az issue resolved once Azure CLI installed in the system. But still, I am getting an error related to folders.

internal/modules/cjs/loader.js:797
    throw err;
    ^
Error: Cannot find module 'C:\Users\Varshney.Naupada\Documents\generate'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by michaeltnguyen** [comment]
migrate.bat just calls a bunch of other scripts in the scripts folder.  it is not standalone.  you need to:

1.  check out this repository (git clone ...)
2.  npm install
3.  modify migrate.bat with your instance names, etc.
4.  run migrate.bat

**Comment by VarshneyNaupada** [comment]
Still getting below issues...
(node:20892) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Error: getaddrinfo ENOTFOUND https
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https'
}

(node:20740) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '../dist/data.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at restore (C:\Users\Varshney.Naupada\Documents\api-management-developer-portal\scripts\generate.js:50:21)
    at Object.<anonymous> (C:\Users\Varshney.Naupada\Documents\api-management-developer-portal\scripts\generate.js:60:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
(node:20740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by VarshneyNaupada** [comment]
I have followed the above steps, and updated details in all files but still getting above errors

**Comment by VarshneyNaupada** [comment]
I am very sorry, I did one small mistake calling URLs with HTTPS, now it is working good. 
Thank you @michaeltnguyen  & @azaslonov  for your guidance.

**Comment by michaeltnguyen** [comment]
@VarshneyNaupada Great!  If it's working, can you close this issue?

**Comment by VarshneyNaupada** [comment]
I am closing this question and triage. Thank you once again for your support and guidance.
