### ISSUE TITLE
Account confirmation in email notifications for self-hosted

### ISSUE THREAD

**Issue by velsietis** [Azure/api-management-developer-portal#460]
## Bug description

After following the [Wiki instructions for e-mail notifcations](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-9-change-api-management-notification-templates), I tried signing up.

The confirmation link in the e-mail gives me a 404 because there is no page with the permalink `confirm-v2/identities/basic/signup`

## Reproduction steps

1. Follow all the [wiki instructions](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal) to set up a self hosted portal
2. Visit the self-hosted portal to complete and submit the sign up form
3. When you receive the confirmation e-mail, you'll get a link something like this:
   `https://my-self-hosted-portal.com/confirm-v2/identities/basic/signup?userid=5e3a95c680a3ce118c1434ed&identity=somebody%40example.com&ticketid=5e3a95c680a3ce118c1434ef&ticket=980fae95681f42acbb6269f3d83e63bf `
4. Click on the link, get a 404 - "Page you're looking for doesn't exist"

## Expected behavior

I expected the sign up process to complete the same way it does on the managed version

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

commit `de47bfe488678ad791affe978412f959adff80e2`

## API Management service name

dhew-nwis

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: 79.0

**Comment by ygrik** [comment]
Hi @velsietis 
for this operation, you need a call to your managed portal backend 
instead of 
**https://my-self-hosted-portal.com/confirm-v2/identities/basic/signup?**
you need
**https://<service-name>.developer.azure-api.net/confirm-v2/identities/basic/signup?**

**Comment by ygrik** [comment]
Hi @velsietis 

For this operation, you can redirect the request to managed portal **https://<service-name>.developer.azure-api.net/confirm-v2/identities/basic/signup?...**

OR

you need to implement endpoint on your portal
**GET /confirm-v2/identities/basic/signup**

this endpoint should convert this request to **MAPI** call
POST {**managementApiUrl**}/users/{**userId**}/identities/Basic/{**identity**}?api-version={**managementApiVersion**}
with "Authorization": **token**

where
**managementApiUrl** and **managementApiVersion** from config
**token**, **userId**, **identity** from request query string params

**Comment by velsietis** [comment]
Thanks @ygrik 

From the way the wiki is written, it didn't seem like we need to implement anything extra if we want to self-host the portal. The redirect to the managed portal doesn't seem like an appropriate workaround as it will confuse users why they're being sent to a separate website.

Good to see this has been marked as an improvement.  We'll have a go at implementing it, but something out the box would have been way better - definitely got an up-vote from me :)

**Comment by velsietis** [comment]
Sorry, I just realised that there's no **token** parameter in that query string, only **ticketid** and **ticket**
I've tried doing the MAPI call with "Authorization": **ticket** and "Authorization": **ticketid**, but get this response to both:

       {  "Message": "The requested resource does not support http method 'POST'."  }

**Comment by mikebudzynski** [comment]
> We'll have a go at implementing it, but something out the box would have been way better - definitely got an up-vote from me :)

@velsietis - we're currently researching the best way to solve this problem; we'll update you within a few ways.

**Comment by ygrik** [comment]
> Sorry, I just realised that there's no **token** parameter in that query string, only **ticketid** and **ticket**
> I've tried doing the MAPI call with "Authorization": **ticket** and "Authorization": **ticketid**, but get this response to both:
> 
> ```
>    {  "Message": "The requested resource does not support http method 'POST'."  }
> ```

Sorry forgot to mention the format for token authorization header:
Authorization : **Ticket id={ticketId},ticket={ticket}**

**Comment by velsietis** [comment]
> > Sorry, I just realised that there's no **token** parameter in that query string, only **ticketid** and **ticket**
> > I've tried doing the MAPI call with "Authorization": **ticket** and "Authorization": **ticketid**, but get this response to both:
> > ```
> >    {  "Message": "The requested resource does not support http method 'POST'."  }
> > ```
> 
> Sorry forgot to mention the format for token authorization header:
> Authorization : "**Ticket id={ticketId},ticket={ticket}**"

**Comment by velsietis** [comment]
Also should be **PUT** not **POST**.
Thanks, got it working now

**Comment by lokijota** [comment]
I don't think this should be closed, the feature should be part of the core developer portal.

**Comment by mikebudzynski** [comment]
>@velsietis - we're currently evaluating the best way to solve this problem; we'll update you within a few days.

Current ETA is March / April (@ygrik).

**Comment by lucaszacutti** [comment]
> Also should be **PUT** not **POST**.
> Thanks, got it working now

hi! could you share your solution? tks!

**Comment by velsietis** [comment]
> > Also should be **PUT** not **POST**.
> > Thanks, got it working now
> 
> hi! could you share your solution? tks!

Is the official solution not working for you?  I haven't tried it yet, but looking at 937f4a3264495179d20e3fdba2f0a706406c8c89 it looks like it should do the trick (see the change to `userService.ts`)

**Comment by lucaszacutti** [comment]
> > > Also should be **PUT** not **POST**.
> > > Thanks, got it working now
> > 
> > 
> > hi! could you share your solution? tks!
> 
> Is the official solution not working for you? I haven't tried it yet, but looking at [937f4a3](https://github.com/Azure/api-management-developer-portal/commit/937f4a3264495179d20e3fdba2f0a706406c8c89) it looks like it should do the trick (see the change to `userService.ts`)

Hi! yes.. the official solution is working but not with complete path /confirm-v2/identities/basic/signup?.. 
We need to compose confirm URL pointing to hostheader.com/signup?.. 

The [official self hosted step-by-step](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-9-change-api-management-notification-templates) may be updated:
![image](https://user-images.githubusercontent.com/13422243/76883182-7b1c0280-685a-11ea-8045-893c13ba204f.png)


Thks!
