### ISSUE TITLE
Sign up error: Missing Captcha

### ISSUE THREAD

**Issue by adri9205** [Azure/api-management-developer-portal#462]
## Bug description

When trying to create a new account on the Developer Portal, with the generic basic Sign-up page, we are getting an error message: "Captcha is required." There is no Captcha to be filled in the sign-up form, users can't sign up.

## Reproduction steps
Steps:
Open the Developer Portal
Go to the section "Sign Up"
Fill the fields:
    Email
    Password
    Confirm password
    First Name
    Last Name
Check the box "I agree to the Terms of Use"
Click on the "Sign Up" button

Once it is done, it displays an error message "Captcha is required" however on the page there is no captcha displayed.

## Expected behavior
Sign up to the Portal.

## Is your portal managed or self-hosted?
Managed

## Release tag or commit SHA (if using self-hosted version)
[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

SANDBOXAPIS - APIs

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 80.0.3987.87

## Additional context
N/A
![captcha](https://user-images.githubusercontent.com/5805644/73985350-89443e00-4900-11ea-9095-0906f02ea3cf.JPG)

**Comment by azaslonov** [comment]
Hi @adri9205, thanks for reporting the issue. This happens in a few regions, we're working on hotfix right now.

**Comment by azaslonov** [comment]
The issue has been resolved.
