### ISSUE TITLE
Toolbox should be movable

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#463]
## Feature request
Be able to move the Toolbox on the left, so that the content behind it can be accessed and edited.

## Reproduction steps
1. Go to 'Layout'
2. Add a Section
3. Set the width so it covers the full screen
4. Add Text widget
5. Type text
6. See Toolbox covers the text
7. Unable to move Toolbox and unable to see the content you added

## Expected behavior
One can move the Toolbox via drag and drop to another place and/or screen.

## Is your portal managed or self-hosted?
Managed

## Environment
 - Operating system: Windows 10 1809
 - Browser: Chrome 
 - Version 79.0.3945.130

## Additional context
![Toolbox_Issue](https://user-images.githubusercontent.com/58420097/74022114-25bc1e00-499d-11ea-9c24-8e8adedb2d08.jpg)

**Comment by mikebudzynski** [comment]
@ZarTrox thanks for requesting the feature. [As per our guidelines](https://github.com/Azure/api-management-developer-portal#-interactions), we ask you to open feature requests at [aka.ms/apimwish](http://aka.ms/apimwish).
