### ISSUE TITLE
Feature request: Copy/Clone whole pages

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#464]
## Feature request
Create a feature to copy whole pages to easily recreate content and edit only small Parts.

## Reproduction steps
Currently only available by adding each section to the library (if it's working) or create an own template.
But adding a feature e.g. to add a whole page to the library, would facilitate the process of recreating pages.

## Expected behavior
A button in the toolbox to clone a page or to add the page to the library.

## Is your portal managed or self-hosted?
Managed

## Environment

 - Operating system: Windows 10 1809
 - Browser: Chrome
 - Version 79.0.3945.130

## Additional context
The current possibility of creating a template or adding everything to the library is for some use cases (e.g. Wiki/Documentation pages) not flexible enough.

**Comment by mikebudzynski** [comment]
@ZarTrox thanks for requesting the feature. [As per our guidelines](https://github.com/Azure/api-management-developer-portal#-interactions), we ask you to open feature requests at [aka.ms/apimwish](http://aka.ms/apimwish).
