### ISSUE TITLE
DelegationAction SignUp

### ISSUE THREAD

**Issue by RetoRechsteiner** [Azure/api-management-developer-portal#466]
## Feature request

Extends the DelegationActions with a SignUp.

## Reproduction steps

In the DelegationAction you not provide a SignUp Action.
-> https://github.com/Azure/api-management-developer-portal/blob/65cf9b9a399fc7e201e4a32498656eb24a0e01ec/src/contracts/tenantSettings.ts

## Expected behavior

SignUp Action for Delegation

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

commit `d86bd2677cbc8a2834056fca214843947e10a5bf`

## API Management service name

fzag-apim-int

## Environment

 - Operating system: Windows 10
 - Browser: Edge
 - Version: 79.0.309.71

## Additional context

![image](https://user-images.githubusercontent.com/8446397/74033434-6c6a4200-49b6-11ea-9e02-838b1e4a3b4b.png)

**Comment by mikebudzynski** [comment]
We're actively working on a solution. cc: @ygrik
