### ISSUE TITLE
Display the given style names

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#468]
## Bug description
When editing typography styles the renamed styles aren't displayed in the given name when working on text widgets.

## Reproduction steps
1. Rename "Heading level 1" to "FOOBAR" in styles-typography
2. Go to the Home page
3. Add a text widget
4. Select the "normal" text
5. Try to make it as Heading level 1
6. See that the style name is "Heading 1" opposed to the expected "FOOBAR"

## Expected behavior
Changing the style name should also display this name while adding content to pages.

## Is your portal managed or self-hosted?
Managed

## Environment
 - Operating system: Windows 10 1809
 - Browser: Chrome
 - Version 79.0.3945.130

## Additional context
For Reference the link to the original Feature request:
https://feedback.azure.com/forums/248703-api-management/suggestions/39673975-display-the-given-name-of-styles-during-editing

![image](https://user-images.githubusercontent.com/58420097/74146592-b09d5280-4c01-11ea-8e11-9a8a84c13860.png)

**Comment by azaslonov** [comment]
Hi ZarTrox, in the text editor, these are not styles, these are page landmarks. Probably we should not allow changing their names in style guide and keep this ability just to variations.

**Comment by azaslonov** [comment]
So, speaking about the bug itself, this is by design, and we're going to disable renaming for landmarks. Thanks for bringing this up.
