### ISSUE TITLE
New DevPortal - menu bug for checkbox "show page headings"

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#477]
## Bug description / reproduction steps

There is the checkbox option "show page headings" in the menu dialog that does not work properly. 
![Menu-properties_Show-page-headings_not-active](https://user-images.githubusercontent.com/58981351/74429940-269cf600-4e5c-11ea-888b-a3447e575c3e.JPG)

- In some cases the page headings are not shown at all even the checkbox is activated and the content is saved and published. See example:
![Menu-properties_Show-page-headings-active](https://user-images.githubusercontent.com/58981351/74429698-baba8d80-4e5b-11ea-897e-cf247f027c05.JPG)

- If the checkbox is activated and the page headings are added to the menu element, page headings are not correctly added. Page headings should be directly added below the selected page item and it should be visualized as a tree (with different alignments) which header level has been choosen. Example:
![Menu-properties_Show-page-headings_not-active](https://user-images.githubusercontent.com/58981351/74429929-200e7e80-4e5c-11ea-954b-fd25f603079b.JPG)

## Expected behavior
- If the option/checkbox is active the page headings should be correctly added in the navigation tree. In the right sort order and with the right tree level
- If I use the menu function on a page to display my page-related headings only, the other sub menu items are not displayed. So I can provide the user an overview of the contents of the page he/she is currently looking at only (Page contents only).
- If the option/checkbox is active, the page headings are added in a reliable and robust way for all circumstances.

## Is your portal managed or self-hosted?
managed

## Environment
 - Operating system: Windows 10
 - Browser: latest version Firefox
 - Version: [e.g., 22]

**Comment by AnRei123** [comment]
![Menu-properties_show-headings-of-a-dedicated-page-only](https://user-images.githubusercontent.com/58981351/74430369-01f54e00-4e5d-11ea-9383-1083196ed481.JPG)
(missed this screenshot above)

**Comment by azaslonov** [comment]
Hi @AnRei123, thanks for reporting the issue. We'll fix this.

**Comment by AnRei123** [comment]
Feature wish: 
I miss a configuration that the page contents/titles for a menu item are only shown/displayed in the navigation tree when the menu item (page main header) is active/selected in the menu.

**Comment by azaslonov** [comment]
Hi @AnRei, you mean you would like to be able to always display headings in the menu, even when you're on the other page?

**Comment by AnRei123** [comment]
For me it is important that only if I am on the same page the details (headers of the page) are shown according to their header hierarchy.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
