### ISSUE TITLE
OAuth Widget Gives 401 on when debugging in localhost

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/api-management-developer-portal#481]
## Bug description

When adding the OAuth widget and insuring localhost is set in the Reply URI, the OAuth Sign In/Sign Up gives a 401 Unauthorized.  The unauthorized URL is hitting my APIM GW and since this is coming from localhost I wonder if this is a CORS issue; however, I've followed the prior steps on configuring CORS and it works with my static files in a SA so I don't believe that's the issue.  I've also set the Reply URI to localhost in AADB2C.  

## Reproduction steps

Configure AADB2C
Add OAuth Widget 
Run NPM Start Locally
Try to Sign In/Sign Up and receive the following in the console: 

## Expected behavior

That I can sign in from localhost

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.2.1

## Environment

 - Operating system: Win 10
 - Browser: Chrome
 - Version: Latest

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
Hi Travis, to answer that we'll need to look at your network logs. Could you please capture it from your browser F12 console and send it to apimportalfeedback@microsoft.com?

![image](https://user-images.githubusercontent.com/2320302/74493535-38e05980-4e87-11ea-9d65-f69d903eb54b.png)

**Comment by TravisLRiffle** [comment]
I emailed this to you guys FYI.

**Comment by azaslonov** [comment]
Hi Travis, sorry for the late response, we're looking into it.

**Comment by azaslonov** [comment]
Hi Travis, I sent you an email with explanation. Please feel free to reply to it shall you need further assistance.
