### ISSUE TITLE
Error saving Section to library

### ISSUE THREAD

**Issue by lucaszacutti** [Azure/api-management-developer-portal#485]
Not able to save a Section to library.

## Bug description

When we try to save a common Section to library get the following error.

## Reproduction steps

1. Create a Section
2. Click section's plus button
3. Enter a section name
4. Click "add to library"
5. Click save button

## Expected behavior

Section is saved to library

## Is your portal managed or self-hosted?

Self-hosted

![savingsectionerror](https://user-images.githubusercontent.com/13422243/74532021-ecd7f800-4f0c-11ea-8f82-1d8c0d6bcc99.JPG)

**Comment by ZarTrox** [comment]
I'm having the same issue. But in another issue they stated that the fix will be released by 21.02.2020

Link to other Ticket: https://github.com/Azure/api-management-developer-portal/issues/296

**Comment by lucaszacutti** [comment]
Duplicated with #296

**Comment by lucaszacutti** [comment]
> I'm having the same issue. But in another issue they stated that the fix will be released by 21.02.2020
> 
> Link to other Ticket: #296

tks!
