### ISSUE TITLE
Download Script not working anymore

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#486]
## Bug description
After changing nothing in the .js & .bat files the download function is not working correctly. Only the media content is downloaded but no .json file with the site content. 

## Reproduction steps
1. Use (latest) download script
2. When finished notice that only a "content" folder is created but no .json file.

## Expected behavior
As usual before when using the script it is expected that a content folder with images (currently working) and the data.json file (currently NOT working) are created.

## Is your portal managed or self-hosted?
Managed

## Environment

- Operating system: Windows 10 1809
- Browser: Chrome
- Version 79.0.3945.130

## Additional context
Uploading older saves is still possible.

**Comment by azaslonov** [comment]
Hi @ZarTrox, could you please copy the output from the command line?

**Comment by ZarTrox** [comment]
Log-files have been sent by my colleague by E-Mail

**Comment by ZarTrox** [comment]
Script version in use: 2.1.3 & 2.2.1 - It has been tested for both.
Media files are able to be up-and downloaded.
The download and upload of the JSON file is not working.

Are my colleague and me the only ones experiencing this issue?

**Comment by ZarTrox** [comment]
Updating the token solved this issue.
