### ISSUE TITLE
Loading API method information fails if the portal is left unattended for a while

### ISSUE THREAD

**Issue by ABBVelocityDev** [Azure/api-management-developer-portal#487]
Steps to reproduce:
1. Authenticate to the developer portal and browse and explore an API. Choose a method.  This works fine.
2. Leave the developer portal open, but leave the computer for an hour or so.
3. Return to the computer and try clicking on another method in the developer portal.
4. The load indicator will show, but the method information never loads.

It seems that sometimes the developer portal automatically signs us out after inactivity. Other times, it remains open, but the user is no longer authenticated/authorized. Perhaps the token is expired?

This behavior leaves the user without any indication that anything has gone wrong, or what to do to resolve the issue.  The user experience would be improve with something like the following:
- Automatically log the user out, OR
- Automatically go get a new token when this happens, OR
- Display some kind of message to the user that they need to refresh or re-authenticate.

This issue has been submitted to Azure technical support as incident #120020624006741.  Azure technical support acknowledged the behavior and redirected me to create an issue here.

![APIM_Capture](https://user-images.githubusercontent.com/32575266/74536049-44726580-4f05-11ea-9291-ecbdaa5f6f54.png)

[APIM_Portal_HAR.zip](https://github.com/Azure/api-management-developer-portal/files/4204658/APIM_Portal_HAR.zip)

**Comment by azaslonov** [comment]
Hi @ABBVelocityDev, thanks for reporting the issue. We'll fix that.

**Comment by mikebudzynski** [comment]
We're actively working on a solution. cc: @azaslonov

**Comment by azaslonov** [comment]
Merged. Release to the managed version will happen sometime next week.
