### ISSUE TITLE
Query parameters of array type are converted to string type after importing API definition (written in swagger 2.0) in APIM portal.

### ISSUE THREAD

**Issue by harisbtariq** [Azure/api-management-developer-portal#488]
Recently I came across an issue where I'm trying to import an API definition written in swagger 2.0 into Azure API management portal.
What I have observed is that when APIM creates the API from the definition, it automatically converts all the query parameters of 'type' :'array' to parameters of 'type': 'string' and drops 'items' object associated with the parameters.

Example;
The item below
```
{
            "name": "Relationship",
            "in": "query",
            "description": "The description.",
            "required": false,
            "items": {
              "type": "string",
              "enum": [
                "Network",
                "Parent",
                "Child"                
              ]
            },
            "collectionFormat": "multi",
            "type": "array"
          }
```
is converted to 
```
{
                    "name": "Relationship",
                    "in": "query",
                    "description": "The description.",
                    "type": "string"
                }
```
after API is created in the APIM.

**Comment by VitaliyKurokhtin** [comment]
This is a known issue pending fix.

**Comment by azaslonov** [comment]
Hi Haris, I hate to say that, but ETA is about 8 weeks from now.

**Comment by azaslonov** [comment]
I'm closing this issue for now, because it is not related to the developer portal project. Please feel free to contact MS support shall you need further assistance on this question.
