### ISSUE TITLE
Enums are not rendered in API object model

### ISSUE THREAD

**Issue by shwetashukla** [Azure/api-management-developer-portal#49]
**Describe the bug**
Enums are not rendered on the page

**To Reproduce**
1. Go to [sample_openapi_json.txt](https://github.com/Azure/api-management-developer-portal/files/3075198/sample_openapi_json.txt) and create a blank api from this JSON.
2. Launch the developer portal and Click on the api name
3. Object rendering is incorrect

**Expected behavior**
1) The enum values should have been rendered.
2) I notice a small box , is that by design?

**Screenshots**
![Error](https://user-images.githubusercontent.com/25539662/56066898-13963280-5d2e-11e9-8255-0927f98a7abd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser :chrome
 - Version :Version 73.0.3683.103 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mikebudzynski** [comment]
Merge with #186

**Comment by pkraeutli** [comment]
The hosted APIM Developer Portal still does not show enum values. Is this fix already deployed? @mikebudzynski

**Comment by azaslonov** [comment]
Hi @pkraeutli, looks like your service has very old bits. Could you please send your service name to apimportalfeedback@microsoft.com?

**Comment by krispenner** [comment]
@azaslonov @pkraeutli was this resolved for you? I am not seeing my enums, they are only showing as type `string`.

Here is my schema, is it wrong? Maybe it is not generating the correct documentation?
```json
        "accountType": {
          "enum": [
            "CEHQUING",
            "SAVINGS",
            "CREDIT_CARD",
            "LOAN",
            "OTHER"
          ],
          "type": "string"
        },
```

How are they expected to be rendered? As their own type listed elsewhere and linked to?

I only see:
![image](https://user-images.githubusercontent.com/8837910/72294667-d89d9400-360a-11ea-9449-9d87361b276a.png)

**Comment by azaslonov** [comment]
Hi @krispenner, in the example you provided, this field is still of type "string", and enumeration is just possible values. Not sure where should we display those values. We'll discuss this internally, but we open for suggestions as well. For now, the workaround would be to put those values into description.

Regarding the issue described above, if you had separate type representing Enum, it would look like this:
![image](https://user-images.githubusercontent.com/2320302/72296680-143a5d00-360f-11ea-907b-9078bb3137f4.png)

That was the fix, but that case is different from yours.

**Comment by krispenner** [comment]
OK, I also like this option you have fixed. I am using ASP.NET Core 2.2 and Swashbuckle to generate the Swagger file. I don't suppose you know how to get my enum as it's own type definition? I tried this method but it does not seem to do anything...
```cs
    options.UseReferencedDefinitionsForEnums();
```

I may be able to just add a ISchemaFilter in Swashbuckle to list off enum values in the description until you sort out your UI or I figure out how to generate a separate definition for my enum. Anyways, I realize this is off topic of the portal so if you don't know then don't worry.

Also, here is my suggestion for my current use case and your UI.
![image](https://user-images.githubusercontent.com/8837910/72297330-911a0680-3610-11ea-93ad-0c19af4a7882.png)

**Comment by azaslonov** [comment]
No idea, sorry. Thanks for the suggestion, we'll see what we can do.

**Comment by krispenner** [comment]
Oh, is there an issue to track my enum use case? Should I create one? I would just like to be able to receive updates on progress and when it will be available. Thanks!

**Comment by azaslonov** [comment]
Yes, please create a separate issue for this, and maybe include the screenshot with your suggestion. Thank you.

**Comment by pkraeutli** [comment]
@azaslonov not sure if I understand correctly, but in Swagger/OpenAPI there is no type `enum`. There is only `string` with `enum`: https://swagger.io/docs/specification/data-models/enums/

![Screenshot 2020-01-14 at 16 00 28](https://user-images.githubusercontent.com/886082/72355034-ff30fd00-36e6-11ea-8846-db032490d7bc.png)

So in my opinion, if a Swagger/OpenAPI spec is imported with type `string` + `enum`, it should be treated as an enum and its values should be visible on the dev portal.

**Comment by azaslonov** [comment]
> @azaslonov not sure if I understand correctly, but in Swagger/OpenAPI there is no type `enum`. There is only `string` with `enum`: https://swagger.io/docs/specification/data-models/enums/
> 
> ![Screenshot 2020-01-14 at 16 00 28](https://user-images.githubusercontent.com/886082/72355034-ff30fd00-36e6-11ea-8846-db032490d7bc.png)
> 
> So in my opinion, if a Swagger/OpenAPI spec is imported with type `string` + `enum`, it should be treated as an enum and its values should be visible on the dev portal.

That's right, there is no `enum` type in OpenAPI spec. What I meant is a case like this:
```json
"CountryCode": {
    "$ref": "#/definitions/CountryCodeEnum"
}
```
... where `CountryCodeEnum` is a structure like:
```
{
    "type": "string",
    "enum": [
        "Unknown",
        "AF",
        "AX",
        "AL",
        ...
}
```

**Comment by krispenner** [comment]
I was able to generate my enums as their own definitions and reference them via the $ref property.
This is in my opinion a much better solution as it treats the enum as its own type with its values listed in its own table. No need to list the enum values within the string property. I'm glad I came across this issue as I had no idea I could generate enums as their own definition. Thanks!

If anyone else comes across this issue and is using ASP.NET Core 2.2 with Swashbuckle to generate the API spec from code, you must call ` options.UseReferencedDefinitionsForEnums();`, however, it doesn't support using nullable enums, eg `DayOfWeek?`. So I had to write my own ISchemaFilter to support nullable enums myself.

**Comment by azaslonov** [comment]
I agree, that is a bit cleaner approach. Thanks for the feedback.

**Comment by kanchan-wakchaure-by** [comment]
@azaslonov This issue still persists though OpenAPI Spec 3.0 is now supporting enum type.

**Comment by azaslonov** [comment]
Hi Kanchan, we would need a document and particular enum example to reproduce your issue.

**Comment by kanchan-wakchaure-by** [comment]
> Hi Kanchan, we would need a document and particular enum example to reproduce your issue.

@azaslonov I can not share the actual OAS document for which I am facing the issue. However I have created a sample OAS document with similar enum definition and attaching it here.


[Sample-OASv3.0-with-enum.yaml.zip](https://github.com/Azure/api-management-developer-portal/files/4618609/Sample-OASv3.0-with-enum.yaml.zip)

**Comment by azaslonov** [comment]
That is good, thanks.

**Comment by wolfgangas** [comment]
Any news on this? I am going to add my enumeration values within the description field, but something more nice regarding UI would be welcome
