### ISSUE TITLE
Existing Developer Portal CDN content - deleted?!

### ISSUE THREAD

**Issue by rachel-langford** [Azure/api-management-developer-portal#492]
## Bug description

Go to the existing Developer Portal (we haven't migrated to the new one yet, as isn't stable enough), and existing images stored in the API Management internal CDN are missing. 

Go to the Publisher portal to view the CDN images and can't not download them (missing blob error).

Can't update the existing developer portal images, as can't find where to adjust the layout and point to images hosted elsewhere. (This functionality may have been deleted from the existing legacy publisher portal).

## Reproduction steps

See issue above.
 
## Expected behavior

Our existing media, to not be removed. We are in a very difficult position where our existing developer portal is decomposing before our eyes, and we cna't migrate to the new portal until a number of significant bugs are resolved (1) correct rendering of HTML on the product page for the product descriptions (2) the proxy to be re-instated so don't get the CORS error on try it (3) the developer portal to work on IE - currently it renders poorly.

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

https://emi.azure-api.net

## Environment

 - Operating system: Chrome on Windows 10

## Additional context

![image](https://user-images.githubusercontent.com/49261001/74612003-fa3bef00-5165-11ea-85ff-2e4c6a639071.png)

![image](https://user-images.githubusercontent.com/49261001/74611996-ea240f80-5165-11ea-963d-7b219fbbd621.png)

![image](https://user-images.githubusercontent.com/49261001/74612025-4424d500-5166-11ea-9faf-3758a23305c8.png)

**Comment by mikebudzynski** [comment]
@rachel-langford This repository is for the new portal only. Please, open an Azure support request to get assistance.
