### ISSUE TITLE
Question: Page authorization

### ISSUE THREAD

**Issue by Jeej** [Azure/api-management-developer-portal#494]
Hi,

For an API of my team we want to provide some extra information to the developers that are going to use the API. Unfortunately, this documentation should not be published open on the internet.

On the developer portal you can create pages, but is it possible to put authorization on those pages? For instance: when you have this product you have access to this page...

Thank you in advance!

**Comment by michaeltnguyen** [comment]
Unfortunately, this is not supported right now.  See this issue for details: https://github.com/Azure/api-management-developer-portal/issues/403

**Comment by Jeej** [comment]
Ah, thank you for pointing me in the right direction. Didn't found that issue :(

**Comment by mikebudzynski** [comment]
You're looking at scenario covered by our extension tutorial for the self-hosted version: https://aka.ms/apimdevportal/extend
