### ISSUE TITLE
[Question]Show unused components in APIs paths

### ISSUE THREAD

**Issue by StephaneMartignier** [Azure/api-management-developer-portal#495]
Hi everyone,

I have a question about the managed developer portal of API Management. First let's explain the situation.
We have an API in which we can subscribe for webhook when specific events occurs. In purpose to let people know the payloads of the webhooks, we add them to the OpenAPI schema even if they are not used in any controller action.
For example, if you go to [here](http://pochinoapi.azurewebsites.net/index.html) you can see at the bottom of the "Schemas" part there is three models (ContactCreated, ContactEdited, ContactDeleted) that are available. If we check the JSON file of OpenAPI [here](http://pochinoapi.azurewebsites.net/swagger/v1/swagger.json) we can also find those three model in it.

But then in the developper portal, when being on the documentation of the api [(here)](https://pochino.developer.azure-api.net/api-details#api=pochino-api&operation=get-api-contacts) we can't see those three models anymore

So my question is: Is there a way to display those three models in the documentation in the managed developer portal?

I've dig a little but can't find anything

Thanks

**Comment by mikebudzynski** [comment]
Currently, the portal displays only schemas referenced by requests or responses. There's even no place to display API-wide unreferenced schemas.
You can submit a feature request at https://aka.ms/apimwish or implement your own widget: https://aka.ms/apimdevportal/extend
