### ISSUE TITLE
New DevPortal (hamburger icon): menu text not visible or not properly displayed

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#496]
## Bug description / repoduction steps
1) When hovering on a second "hamburger" icon the mouse pointer is not showing up. Mouse pointer only shows up when hovering some milimeter above the icon
2) When clicking the top "hamburger" icon for the main menu in the header, the screen gets dark. Still the contents of the page are displayed in a blurry way. The menu items are hardly to recognize and not readable at all.
3) When clicking the second "hamburger" icon for the side navigation (sub menu on the left side), the screen gets dark. Still the contents of the page are visible in a blurry way. The menu items are not displayed at all.
-----
For details on the behavior when reducing the window resolution of the published portal, see the attaced video file:
[Issues-with-collabsable-elements.zip](https://github.com/Azure/api-management-developer-portal/files/4220152/Issues-with-collabsable-elements.zip)

## Prerequisites

1. In the layout section, create a main menu in the header in a collabsable element
2 In the layout section, create a sub menu on the left side of the content area

## Expected behavior
1) When hovering over a "hamburger" icon the icon is clickable
2) When clicking on a "hamburger" icon the menu items are visible and easy to read through w/o any overlapping of the texts of the contents of the page
3) When clicking on one of several "hamburger" icons the menu items are displayed at all.

## Is your portal managed or self-hosted?
Managed

## Environment
 - Operating system: Windows
 - Browser: Chrome latest

## Additional context
1) The "hamburger" icon of the main menu should look different (e.g. bigger or three dots) in comparison to the additional "hamburger" icons (e.g. smaller).
2) The "hamburger" icon for the main menu should appear earlier when reducing the window resolution. It should already appear before the horizontal menu items are splitted into two rows.
3) The "hamburger" icon for the left navigation tree should appear earlier when reducing the window resolution. It should appear before the menu items are splitted into single words. If the menu items are broken in a way that only one word is displayed in a line, - for longer menu items this is not readable  and usable anymore.

**Comment by azaslonov** [comment]
Hi @AnRei123, yes, these are known issues. Fixes and new styling controls are coming in the next couple of weeks. That should solve all of those issues.

**Comment by ZarTrox** [comment]
Are there any news regarding this Issue/Is this Issue still in-work? Because when resizing the browser/using a smaller device some things still break (e.g. Overlapping or disappearing elements).
