### ISSUE TITLE
New DevPortal: Navigating and linking to headers 2-5 currently not possible

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#499]
## Bug description/reproduction steps
Menu links and hyperlinks to headers/titles with levels lower thand 1 (2-5) currently not working. 

1) When adding hyperlinks to a text sub titles on a page cannot be selected, see example in image:
![Menu-Links-to-subtitles](https://user-images.githubusercontent.com/58981351/74945335-d8599b00-53f7-11ea-8708-4809efac5ca2.JPG)

2) If page titles from level 2-5 are activated to be shown for menus, they are displayed in the menu list, but navigating to subtitles with level 2-5 is currently not possible - still after saving and publishing the contents.

## Expected behavior
Sub titles are treated like main headers. Ankers for subtitles (level 2-5) are shown in the link dialog and can be directly navigated when clicking a related menu item. Same behavor should be for the editor mode and for the published portal to allow efficient writing, maintaining and navigation.

## Is your portal managed or self-hosted?
managed

## Environment
 - Operating system: Windows 10
 - Browser: latest Chrome and Firefox version

**Comment by azaslonov** [comment]
Hi @AnRei123, this issue has been fixed in Paperbits libraries, we're going to adapt it (and deploy) by end of next week.
