### ISSUE TITLE
Move from managed to self-hosted instructions need update

### ISSUE THREAD

**Issue by cblanto7** [Azure/api-management-developer-portal#503]
https://github.com/Azure/api-management-developer-portal/wiki/Move-from-managed-to-self-hosted

The instructions on this page state: 
"the Storage Account connection string in the config.design.json file needs to be the same as the Storage Account connection string of the managed version of the portal." 
This is not possible because there is no Storage Account connection string in config.design.json, only a storage Url

I have tried to put the connection string I have for the managed instance into this field but it doesn't work. So I am an unable to move from managed over to self-hosted.

**Comment by mikebudzynski** [comment]
We have a work item to update the docs. You can use this script to retrieve a SAS URL from a connection string: https://github.com/Azure/api-management-developer-portal/blob/master/scripts/retrieveStorageSasUrl.js

**Comment by mikebudzynski** [comment]
I've added the conversion to SAS URI as the last step of this article: https://github.com/Azure/api-management-developer-portal/wiki/Retrieve-managed-portal-storage-account
