### ISSUE TITLE
Selecting passages with the mouse in the text-editor mode not possible

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#505]
## Bug description
While selecting words, lines or everything with mouse clicks is possible selecting only a certain passage of a text element is impossible

## Reproduction steps
1. Create a text element
2. Click into said text element
3. Pull your mouse from a random point in your text to another
4. Notice that only the starting point is selected and nothing else

## Expected behavior
Like in every text editor the drag-over with the mouse selects the text along its path.

## Is your portal managed or self-hosted?
Managed

## Environment
- Browser: Google Chrome
- Version: 79.0.3945.130

## Additional Context
It may correlate with #439 since it is possible to select in Firefox and in Chrome it is possible to type spaces.

**Comment by azaslonov** [comment]
Hi @ZarTrox, it looks like I'm unable to repro, unless I misunderstand what you describe. Is it possible to record a short video?

**Comment by ZarTrox** [comment]
Thanks for the response.
I tried reproducing the Issue but failed as well. Perhaps a Browser update fixed this issue.
