### ISSUE TITLE
After time-out log-in is not possible with certain chrome setting

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#506]
## Bug description
When using a published version of the Developer Portal you get logged out after a certain amount of time of inactivity. With the setting in chrome called "Allow Chrome sign-in" re-logging with AAD after that is not possible.

## Reproduction steps
1. Set "Allow Chrome sign-in" in chrome settings to active
2. Open your published site
3. Sign-in
4. Sign-out/Wait for time-out
5. Get redirected to Sign-in page
6. Press AAD
7. Pop-up windows shows but is blank
8. Pop-up window disappears
9. Still not logged in

## Expected behavior
After being logged out one can (without explicitly deactivating the chrome setting) re-log-in like it is possible now when deactivating the chrome setting.

## Is your portal managed or self-hosted?
Managed

## Environment
 - Browser: Chrome
 - Version: Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by azaslonov** [comment]
This is fixed on the backend as well (and related to #507), we're awaiting for deployment.
