### ISSUE TITLE
The time until time-out is incredibly low

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#507]
## Bug description
The time until the Portal logs you out is under 5 minutes. When having a long-ish Documentation this is not nearly enough time to read anything.

## Expected behavior
More time until one gets logged out.

## Is your portal managed or self-hosted?
Managed

## Additional context
I see this as an bug because the time is so incredibly low and(at least I) couldn't find a setting to change it.

**Comment by azaslonov** [comment]
Hi @ZarTrox, just yesterday, @ygrik added functionality to refresh token in managed version. It will be out in one of the next releases.

**Comment by ZarTrox** [comment]
Hello @azaslonov ,
I have to reopen this issue since my coworkers are still running into this problem.
Which means they have to close the window and then reopen it to log-in after a time-out.

Do you have any news regarding this issue? Thanks in advance.

With kind regards,
ZarTrox

**Comment by mikebudzynski** [comment]
1. Did the problem reappear or was it always present?
2. Which browser are you using?
3. I assume you mean the administrative mode of the managed version?

**Comment by ZarTrox** [comment]
My Problem is tied to #506 
It seems to have never been fixed. At least not that I have noticed. I am currently using Chrome Version 84.0.4147.105.
I am speaking about the published portal of the managed version.

As mentioned in #506 the issue is that after a short time you get logged out (Which ideally should be adjustable) of the DevPortal. Then if you want to log back in you have to close the window and reopen the page to be able to access the content. Otherwise it just loads and you end up at the log-in page again and aren't logged-in

**Comment by ZarTrox** [comment]
As mentioned before in the published mode the timeout is still around 5 minutes.
The timeout should either be configurable individually via the APIM portal or that the timeout happens not earlier than after 30 minutes.

**Comment by ZarTrox** [comment]
Irrespective what the new timeout will be the user shall be able to sign-in without closing the browser-window #806 

Beneficial would also be that the admin of the portal can configure the timeout depending on the needs of the consumers  #807

**Comment by azaslonov** [comment]
Hi @ZarTrox, thanks for the input, we'll see what we can do.
