### ISSUE TITLE
Should I be able to "publish" from localhost?

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/api-management-developer-portal#511]
When I attempt to do so, I get an error from CORS.  
I can run the publish from command line, I assume it does the same thing.  However, when I upload to blob storage, my old content isn't being updated.  
I've wiped my dist fold completely and tried again and still what's uploaded is the old content.  What am I missing here?

**Comment by azaslonov** [comment]
Hi Travis, you know that when you publish with `npm run publish` command, it goes to local `/dist` folder. This is the first thing you need to check if there is everything you expect.

Now, when you say you upload to blob storage, which one is it? Your own or the one that goes with managed service? How you upload it?

**Comment by TravisLRiffle** [comment]
It seems like hitting save on the local site was necessary.
