### ISSUE TITLE
Login with Localhost (local account) -> No redirect or sign in 

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/api-management-developer-portal#512]
#461  Bug description
I've created a local account through the hosted gateway, verified my email and signed in.  I then run the localhost and try to login with a local account and nothing happens.  When I look at the network tab, I see a 200 on the following call.

https://mygateway.management.azure-api.net/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/mygateway/identity?api-version=2018-06-01-preview

Once the 200 is returned by the network, nothing happens. No redirect and the profile section is available (which is in the secure menu).  I need to be able to get to this to add a widget and can't.  

## Reproduction steps

ON HOSTED
Create local account.
Verify account.  
Sign in.  

SELF-HOSTED
Try to sign in - nothing happens.

## Expected behavior

Sign into self-hosted and get to secure navigation

self-hosted 
2.2.2

## Environment

Windows 10 and latest Google Chrome

**Comment by azaslonov** [comment]
Hi @TravisLRiffle, I can't reproduce the issue. Are there any errors in the console?

**Comment by TravisLRiffle** [comment]
None.  The network traffic just shows a 200.  It's really odd.  
That said, I've found a work around if you want to close this.  Thanks for the response.
