### ISSUE TITLE
Question: Unpublish

### ISSUE THREAD

**Issue by sethwenzel** [Azure/api-management-developer-portal#513]
Is there a way to set an Azure hosted API-M portal from published to unpublished, where it responds with the text "Developer portal has not been published yet."

it looks like issue #220 had text like this, but was closed and refers to #233, which does not unpublish, but resets the portal to the base Contoso content.  Right now it would seem we would need to remove the API-M instance, and redeploy to unpublish.  Is that correct?

**Comment by azaslonov** [comment]
Hi @sethwenzel, yes, for now there is no other way. BTW, you don't want any portal or just new one? I'm asking because we will deprecate legacy portal (no specific time line at the moment) at some point and you may want to account for that in long term.

**Comment by mikebudzynski** [comment]
@sethwenzel - can you please open a feature request on https://aka.ms/apimwish?
