### ISSUE TITLE
Saved work disappears after ARM template deployment 

### ISSUE THREAD

**Issue by ChristopherEquinor** [Azure/api-management-developer-portal#518]
## Bug description

Was updating the developer portal templates, and frequently saving the work. The portal confirmed that the work got saved. 

We have an automatic ARM template deployment to this APIM instance. However, these templates only touch the *Microsoft.ApiManagement/service/products* and *Microsoft.ApiManagement/service/apis* resource types. 

It seems like all the saved work gets wiped after the deployment, even though we're only deploying  *Microsoft.ApiManagement/service/products* and *Microsoft.ApiManagement/service/apis* resource types. 

## Reproduction steps

1. Go to 'Azure Api Management instance'
2. Click on 'Developer Portal'
3. Click on  'styles' in the left toolbars
4. Do changes and save work
5. Deploy ARM templates only touching *Microsoft.ApiManagement/service/products* and *Microsoft.ApiManagement/service/apis* resource types. 
6. You do not get confirmed saves any more
7. Follow steps 1, 2 and 3
8. All saved work is gone.

## Expected behavior

Saved work should not disappear after deployment of unrelated Azure resources. 

## Is your portal managed or self-hosted?

Managed

## API Management service name

https://omniatest.developer.azure-api.net/

## Environment

 - Windows 10
 - Google Chrome

**Comment by azaslonov** [comment]
Hi @Christopher, the developer portal is not supported in ARM templates just yet, but this is planned work. For now, the only thing I can recommend is to use [migration scripts](https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services) for your devops purposes. 

Hope that helps.

**Comment by ChristopherEquinor** [comment]
> Hi @christopher, the developer portal is not supported in ARM templates just yet, but this is planned work. For now, the only thing I can recommend is to use [migration scripts](https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services) for your devops purposes.
> 
> Hope that helps.

I probably didn't explain myself well enough. 

I know the developer portal doesn't support ARM templates. 

I have APIM instance X, and I work on the developer portal for instance X. I experience no problems when deploying ARM templates to instance X with [*incremental mode*](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-modes#incremental-mode). It **does not** remove deployed work on the developer portal. It causes no problems as long as the developer portal is deployed.

However, if the work is only **saved**(not deployed), the work will disappear, even if the ARM templates are in [*incremental mode*](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-modes#incremental-mode), meaning it doesn't touch resources other than those defined in the template.
