### ISSUE TITLE
Support for OpenAPI 3.0 comma-delimited parameters

### ISSUE THREAD

**Issue by am11** [Azure/api-management-developer-portal#519]
OpenAPI 3.0 allows us to specify values validation `enum` for comma-delimited parameters.
For example, the following schema is acceptable by https://editor.swagger.io/ as well Azure Portals YAML editor:

<details>
  <summary>Example schema</summary>

```yaml
openapi: 3.0.1
info:
  title: enum test
  description: >-
    To demonstrate that multiple (comma-separate) values cannot be represented.
  version: '1.0'
servers:
  - url: 'http://example'
paths:
  '/import/{things}':
    post:
      summary: Import list of things
      operationId: test-op-id
      parameters:
        - name: things
          in: path
          description: A comma-separated list of things.
          required: true
          explode: false
          schema:
            $ref: '#/components/schemas/things'
      responses:
        '200':
          description: Request processed successfully.
          content:
            application/json: {}
components:
  schemas:
    things:
      type: array
      items:
        enum:
          - thingA
          - thingB
          - thingC
        type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
```
</details>

However, when we (successfully) save this schema in Azure Portal's API Management blade, and review the just-saved schema, the following delta is noticed:

```diff
-          explode: false	
-            $ref: '#/components/schemas/things'
+           type: string
```

and we lose the parameter value validation defined by `enum` under `things` component.

Is this autofix a bug or a behavior by design? In case of latter, are there plans to support OAS 3.0 comma-delimited parameters in Azure API Management?

**Comment by azaslonov** [comment]
Thanks @VitaliyKurokhtin. 

@am11, I'm closing this issue for now, because it's not directly related to the developer portal project.

**Comment by am11** [comment]
@VitaliyKurokhtin, @azaslonov, thanks for the info.
Is there any other repo where we can open it and track the progress? We wanted to make followup progress based on this tracking for our consumers.

Thanks!

**Comment by azaslonov** [comment]
There is a couple of channels to file your request: either to https://aka.ms/apimwish or to go to MS support.
