### ISSUE TITLE
Question regarding log-out and "back"-button

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#521]
## Question
May to #506
When being logged out one can still see the content of the DevPortal by using the "Back-Arrow".
Is this intended?

## Reproduction steps
1. Log-in 
2. Visit multiple pages
3. Wait for automatic log-out of log-out yourself
4. Press "Back"-button in Browser
5. Be able to see the content you have visited
6. When trying to use navigation you will be re-directed to sign-in page (which is normal behavior)

## Is your portal managed or self-hosted?

Managed

## Environment
 - Browser: Chrome
 - Version: Version 80.0.3987.122 & Version 80.0.3987.132

**Comment by azaslonov** [comment]
Hi @ZarTrox, I think this issue has been addressed, just not released. @ygrik can you confirm?

**Comment by ZarTrox** [comment]
Thanks for the information! Is there already a planned date for the next release?

**Comment by ygrik** [comment]
Yes, this issue will be fixed with the next release (approx in next 2-3 weeks)

**Comment by mikebudzynski** [comment]
The issue was already fixed in March/April.

**Comment by ZarTrox** [comment]
@mikebudzynski I unfortunately don't experience that this Issue has been resolved.

**Comment by mikebudzynski** [comment]
@ygrik Can you please look into this?

**Comment by azaslonov** [comment]
Fix merged.
