### ISSUE TITLE
Filtering on tags

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#525]
In a comment to #79 @azaslonov wrote: “4. Filters based on tags are coming soon”. This is a feature we would love to see implemented. Do you have a timeframe for when it will be available?

**Comment by mikebudzynski** [comment]
No ETA at this moment.

**Comment by ErikMogensen** [comment]
Ok. Is it something you are going to implement? 

Do think it is possible we could create a PR for it? I thinking of whether there are APIs available for this and if you think this is functionality you want to have?

**Comment by mikebudzynski** [comment]
> Ok. Is it something you are going to implement?

Yes, that's something we've been planning to implement.

> Do think it is possible we could create a PR for it? I thinking of whether there are APIs available for this and if you think this is functionality you want to have?

Absolutely! We encourage community contributions and that'd be an extremely valuable additions to the developer portal.

@azaslonov can provide guidance and help in the process.

**Comment by ErikMogensen** [comment]
@azaslonov , please provide some guidance. Depending upon the effort we will decide if we will try to implement this.

**Comment by ErikMogensen** [comment]
I like the behavior of the filter in the Analytics blade. It uses a dropdown and an OK button. I think that should be part of it too.

I am trying to determine what needs to be done to make this happen. I would like to hear what you think of this rough design suggestion.

I know it is stated that new widgets should be in a separate part of the repository but I think it would be better to add the capability to filter on tags should to the following, existing widgets:

- List of APIs 
- List of APIs (tiled) 
- List of APIs (dropdown) 

They share the same source code so it should be a good fit. To support this there would be a new boolean property added to these widgets to control whether the ability to filter on tags should be enabled or not. If it is not enabled it should not be visible and the widgets should look exactly like before.

The dropdown list of tags would be populated using https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/tag%20entity/listbyservice.

The filtering of APIs based on tags is already supported in the management API, just need to add the selected tags when calling it.

Regarding the tag selection GUI, are you be able to able to direct us to some sample where similar functionality is implemented?

**Comment by azaslonov** [comment]
Update: I'm working on it right now.

**Comment by azaslonov** [comment]
Done.

**Comment by ErikMogensen** [comment]
Thanks a lot!

**Comment by mikebudzynski** [comment]
We're still awaiting the deployment - most likely the feature will be rolled out within a month.

**Comment by ErikMogensen** [comment]
Thanks for letting us know.
