### ISSUE TITLE
Azure Developer portal shows the example json twice

### ISSUE THREAD

**Issue by Harjindar** [Azure/api-management-developer-portal#526]
## Example of a definition is shown twice on the Developer Portal

When an example is configured for a definition (request or response), it is displayed twice instead of once.

## Reproduction steps

1. Go to an APIs section under API Management
![image](https://user-images.githubusercontent.com/37382131/76016458-248afc00-5f1d-11ea-9b61-04e0ed73f96d.png)

2. Click on any API
3. Click Definitions
![image](https://user-images.githubusercontent.com/37382131/76016544-4b493280-5f1d-11ea-9ed6-ba59884d09ec.png)
4. Provide an example for a definition
5. This example should be shown once in Developer Portal 
![image](https://user-images.githubusercontent.com/37382131/76016968-12f62400-5f1e-11ea-90bc-106f30ec1a3f.png)

## Expected behavior

Example should be shown **once** instead of twice

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @Harjindar. This issue has been fixed. Just republish the portal.

**Comment by Harjindar** [comment]
Great! @azaslonov Thanks!
