### ISSUE TITLE
user sign in processes not working

### ISSUE THREAD

**Issue by santo2** [Azure/api-management-developer-portal#528]
## Bug description

I'm trying to create a new developer portal, and I notice all the sign in pages and options are not working.  I started by clicking the "Developer Portal" button in Azure API Management, and started to use the designer. I did not change anything specific except for some colors.
I did publish, and tried to log in.

## Scenarios

When resetting the password in Azure API management portal, 
Then I receive the mail with the new link
and when I click the link in the mail, I get to a page saying the page does not exist (reset-password)
EDIT: I tried to add this page, but it seems to be a reserved path

When inviting a new person, same thing: clicking on the link in the mail gets me to a non existing page (confirm-password)
EDIT: I tried to add this page, but it seems to be a reserved path

When trying to log in with an existing account to which I'm not sure of that the password is still correct, and I press the sign in button, it does a callback but does not show a validation summary, I don't know what is wrong now.
EDIT: I found out that the sign in page did not contain validation summary by default, that I have found and added. 

## Is your portal managed or self-hosted?
No idea what self hosted means? so I guess managed? I created it online and tried to publish from there.

## Environment
 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: Version 80.0.3987.132 (Official Build) (64-bit)

Question: is this a ready to use product or is this still a BETA? because I don't see any beta notifications when I use this, but I had some issues around state of changes not being saved, publish not working, and now this, these things feel like a beta version (or maybe even alpha)

**Comment by azaslonov** [comment]
Hi @santo2, sorry to hear that. Can you please send us your service name at  apimportalfeedback@microsoft.com. I'm sure we can figure out what is going on.

**Comment by santo2** [comment]
I'm not getting any response on my mails. What do we need to do now? I can not use this if it's not working

**Comment by santo2** [comment]
@azaslonov
