### ISSUE TITLE
Able to browse to API page when not signed in.

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#535]
When not signed in, you are able to browse to the API page by appedning "/apis" to the host name. 

Although no API specifications are shown, I would expect the same behaviour when browsing to the profile resource where it redirects you to the Sign In page.

Thanks

**Comment by azaslonov** [comment]
Hi @watson20201, this is by design, but if you'd like users to always be signed-in, you can force this by requiring sign-in:

![image](https://user-images.githubusercontent.com/2320302/76357830-a68c7380-62d5-11ea-8eeb-769d960d196c.png)
