### ISSUE TITLE
Hide Definitions section when viewing an API method

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#536]
Is it possible to hide the Definiations section as this information is repeated under each of the relavent objects.

![image](https://user-images.githubusercontent.com/62035456/76359805-9ed5d900-6380-11ea-9719-d982c9f794d3.png)

Thanks

**Comment by mikebudzynski** [comment]
It's not possible at this moment and we don't have an ETA for providing this functionality. If you're open to contributing to our project, we'd gladly accept the change to introduce a new widget setting to control the visibility of definitions.

**Comment by mikebudzynski** [comment]
Closing the issue due to lack of activity
