### ISSUE TITLE
Add Tooltip to the Definition names.

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#537]
Depending on the number of characters used for the name in the Definition section it gets truncated and the ellipsis is appended to the end as shown below.

![image](https://user-images.githubusercontent.com/62035456/76361724-77810b00-6384-11ea-8192-b911f4df4bbd.png)

Is it possible to add a tooltip on each name describing the full name of the definition.
Thanks

**Comment by azaslonov** [comment]
Hi @watson20201, yes that makes sense, we'll do that. Thanks!
