### ISSUE TITLE
Menu item ignores the setting "open in new window"

### ISSUE THREAD

**Issue by LockTar** [Azure/api-management-developer-portal#541]
## Bug description

When creating a new menu item with the option "Open in ->New window" doesn't open in new window but in "Same window".

## Reproduction steps

1. Go to menu management
2. Click on adding a new menu item
3. Set the setting "Open in" to "New window"
4. Publish site
5. Menu item doesn't open new tab but just navigates to that url in the same window.

## Expected behavior

Opens a new tab of your browser and navigates to it.

## Is your portal managed or self-hosted?

Managed

## Additional context

The setting "New window" does work when you use when creating a hyperlink in text. So only a bug in the menu.

![2020-03-12 09_10_02-API Management](https://user-images.githubusercontent.com/1568453/76503333-fd18bf80-6445-11ea-8540-d2cffc201317.png)

**Comment by azaslonov** [comment]
Hi Ralph, thanks for reporting the issue. We'll fix it.

**Comment by guideveloper** [comment]
@azaslonov Do you know if this has been fixed please?

**Comment by azaslonov** [comment]
Hi @guideveloper, not yet, but fix coming by the end this week to this repo. However, we cannot deploy to the managed environment, we've got a restriction on all deployments across Azure until further notice (related to COVID-19).

**Comment by ilspiert** [comment]
can I vote to get that issue get fixed - ran into that today as well. thx 😀

**Comment by azaslonov** [comment]
Yep, I guess we'll speed it up, that should be a fairly small change.

**Comment by ilspiert** [comment]
argh... this issue is kind of annoying. any fix possible? Can give a hint of the issue. It seams that the designer does not save the setting. Enable that option "open in new window", save changes, change to e.g. a page, go back to the navigation page, check the setting and it is gone - my browser, latest Chrome. Thx, for having a look.

**Comment by LockTar** [comment]
Hopefully this fairly small change can be fixed soon... Because we are now more than 7 months further...

**Comment by mikebudzynski** [comment]
We plan to fix the problem in the upcoming few weeks.

**Comment by azaslonov** [comment]
Fixed in Paperbits, will push into next portal release.
