### ISSUE TITLE
How to add Password restrictions in Developer Portal ?

### ISSUE THREAD

**Issue by VarshneyNaupada** [Azure/api-management-developer-portal#542]
Hi Team,

I have used default templates for the developer portal. I would like to provide users/subscribers to have password pattern restrictions while setting a password.

**Comment by mikebudzynski** [comment]
API Management doesn't support custom password restrictions. You can use authentication delegation for this purpose.

**Comment by VarshneyNaupada** [comment]
Thank you @mikebudzynski
