### ISSUE TITLE
Specifying several request/response body examples not supported

### ISSUE THREAD

**Issue by ikteru** [Azure/api-management-developer-portal#543]
How come it's not possible to specify several **request body examples** ? It is supported by the **OpenAPI** specification.

Checkout the following specification: 
paths:
```
  /users:
    post:
      summary: Adds a new user
      requestBody:
        content:
          application/json:     # Media type
            schema:             # Request body contents
              $ref: '#/components/schemas/User'   # Reference to an object
            examples:    # Child of media type
              Jessica:   # Example 1
                value:
                  id: 10
                  name: Jessica Smith
              Ron:       # Example 2
                value:
                  id: 11
                  name: Ron Stewart
      responses:
        '200':
          description: OK
```
You'll notice that the **request body** has two examples: **Jessica** and **Ron**.  That translates to a drop down to choose from the examples in Swagger.

**Comment by mikebudzynski** [comment]
It's a current limitation of the API Management's support of OpenAPI: https://docs.microsoft.com/en-us/azure/api-management/api-management-api-import-restrictions It's on our roadmap to provide support for `examples` but we don't have an ETA yet.

**Comment by jason-runzer** [comment]
I also just ran into this issue. @mikebudzynski When do you think this will be on the roadmap? Is there anyway we can vote to prioritize this feature being implemented sooner rather than later?

**Comment by mikebudzynski** [comment]
Feature requests can be posted here: https://aka.ms/apimwish 
We don't have an ETA at this moment.
