### ISSUE TITLE
The use of OneOf doesn't translate well into the documentation

### ISSUE THREAD

**Issue by createitreal** [Azure/api-management-developer-portal#546]
## Brief description: 

When you use the Openapi 3 "Oneof" property to illustrate some type of inheritance, and the fact that there can be multiple responses to the same request, it doesn't appear in the documentation.

## Reproduction steps

1. Use the "Oneof" keyword in your openapi 3 specification document:
![image](https://user-images.githubusercontent.com/58592689/76937912-f8e11c00-68f5-11ea-8d69-552d3aa3291c.png)

2. It gets translated to the following JSON format in Azure API Management:
![image](https://user-images.githubusercontent.com/58592689/76937989-21691600-68f6-11ea-94d6-46a1ff1423ed.png)

where **WsTasks-taskId-Get200ApplicationJsonResponse** is an automatically generated component given the following value:
![image](https://user-images.githubusercontent.com/58592689/76938108-54aba500-68f6-11ea-921c-8ac116731f09.png)

3. And this is how it looks like in the developer portal:
![image](https://user-images.githubusercontent.com/58592689/76938248-989eaa00-68f6-11ea-9231-43898658e9a3.png)

## Expected behavior

I expected to be able to see all types of the response, something similar to how Swagger UI does it: 
![image](https://user-images.githubusercontent.com/58592689/76938712-6a6d9a00-68f7-11ea-9651-11b8425b5839.png)

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
Hi @createitreal, yes, this is known issue. Please use #522 for tracking.
