### ISSUE TITLE
Question/Bug regarding the query Selector method

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#548]
## Bug description
I'm writing a script for the DevPortal to select all elements which are labeled as links and copying them into a file. But I noticed that while the script works for other pages it throws an Error when I try it for the DevPortal. I'm using the puppeteer browser (headless chromium) for this. 

## Reproduction steps
Code snippet: 
(I do not expect someone to correct/rewrite my script but I still posted it for clarification.)

...
````
(async () => {
    /*Start puppeteer with defined args*/
    try {
    const page = await browser.newPage();
    await page.goto(URL, { waitUntil: 'networkidle2', timeout: xxx })
    /*Login into the DevPortal*/
    // "page.$$eval()" equals "Document.querySelectorAll()"
    const hrefs = await page.$$eval('a', links => links.map(a => a.href));
    fs.writeFile(/*file*/', hrefs, function (err) {
        if (err) console.log('Error while writing File');
    });
}
catch (err){
    console.log('Error in JS');
}
await browser.close();
}) ()
````
## Expected behavior
When for example trying this script for Wikipedia.org I get all Links present and can write them into the specified file. After logging in into the DevPortal I get an error when trying to evaluate the page. (Login process works for sure) Is this a Portal Issue? Thanks for the help in advance.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @ZarTrox, I'm not familiar with Puppeteer, so I can't help you much here. We can only answer questions related to the developer portal code itself. Sorry, but I have to close this issue as irrelevant one.
