### ISSUE TITLE
Azure AD identity provider new app client ID not used

### ISSUE THREAD

**Issue by krispenner** [Azure/api-management-developer-portal#549]
Under the identity tab, remove the "Username and password" identity provider and add the "Azure Active Directory" provider instead, complete the required fields and save. Go to developer portal and it should work.

Now change the Client ID and Client Secret to a new Azure AD registered application. The developer portal will not use the new app but continue with the previous one. Even 12 hours later it still uses the previous app so I don't think it's a caching issue.

Now open the developer portal for editing and publish it, no changes are required. It appears to refresh the config somehow and it now will use the new Azure app (client ID/secret).

![image](https://user-images.githubusercontent.com/8837910/77108600-bac02700-69df-11ea-8038-6ba42b8364f9.png)

This should be documented in the portal when editing the Azure AD client ID and secret to tell the user to re-publish the portal after any changes are made. I just randomly thought of trying that and it worked.

It would be nice if someone can confirm this is an issue and re-publishing the developer portal is what is required to fix it. This should then be fixed to auto refresh the developer portal identity config when changes are made and not require the user to re-publish the developer portal site for their identity changes to take affect. Or at the very least add a note in the Azure portal informing the user to re-publish the developer portal site.

**Comment by azaslonov** [comment]
Hi @krispenner, you are right, re-publishing is required for the new developer portal. We're aware of the usability issue and already working on making it more explicit. Thanks for bringing it to our attention.
