### ISSUE TITLE
Improved customization of API detail screens

### ISSUE THREAD

**Issue by ndywicki** [Azure/api-management-developer-portal#551]
Hi team,

The new portal has a nicer modern GUI but I find that some elements lack visibility compared to the old portal.

In particular the operations detail screen and the try-it console.
Unfortunately these elements are not directly customizable.

For example, we cannot make a background between the menu and the content:

New Portal:
![api-details-menu-background-new](https://user-images.githubusercontent.com/1721344/77451009-627c9100-6df4-11ea-9466-88a42e783df7.png)

Vs Old :
![api-details-menu-background](https://user-images.githubusercontent.com/1721344/77451002-60b2cd80-6df4-11ea-9473-5d9a17ed137d.png)
Everything is carried by the section and not the articles

On the console the tabs are not well demarcated:

New portal:
![api-console-tabs-new](https://user-images.githubusercontent.com/1721344/77451017-63adbe00-6df4-11ea-845d-5be57adc1c28.png)

Vs Old:
![api-console-tabs](https://user-images.githubusercontent.com/1721344/77451015-63152780-6df4-11ea-8c93-19a9023eb224.png)

At best we can modify the navlinks but globally.

Is it possible or planned to add better customization to improve readability?

Thank you,

## Release tag or commit SHA (if using self-hosted version)
Current cloud portal

**Comment by azaslonov** [comment]
Hi @ndywicki, thanks for reporting those issues. We work on adding more customization controls, they are coming in the near future (unfortunately, no ETAs yet).
