### ISSUE TITLE
Update the Python code sample

### ISSUE THREAD

**Issue by insideout** [Azure/api-management-developer-portal#553]
We are using Azure API Management to publish our APIs here:
https://developer.smartable.ai/api-details#api=coronavirus&operation=stats

I need to change the default python sample template because it has wrong code examples. I tried to modify the python sample template in the legacy portal by following this docs page: https://docs.microsoft.com/en-us/azure/api-management/api-management-developer-portal-templates

The changes are live in the legacy portal, but does not show up in the new developer portal.

How can I make the sample code change in the new developer portal?

**Comment by mikebudzynski** [comment]
The Python code sample template is located here: https://github.com/Azure/api-management-developer-portal/blob/master/src/components/operations/operation-details/ko/runtime/templates/python.liquid

There are two options:

1. If the changes are something that would benefit everyone (for example, code samples use outdated libraries), you can either contribute to the project via pull request or open a bug and wait for us to fix it. In both cases, the changes will be propagated to the managed version.
1. If the changes are specific to your scenario, you can go with the self-hosted portal version and edit the file in your own developer portal deployment.

**Comment by SmartableAI** [comment]
The auto-generated python code sample is currently not working.  It somehow ignores the schema.  Here is the code sample I got from the current template.  As you can see below, the 'conn' variable is not defined. 

import httplib, urllib, base64

headers = {
# Request headers
'Cache-Control': 'no-cache',
}

params = urllib.urlencode({
})

try:
conn.request("GET", "?%s" % params, headers)
    response = conn.getresponse()
    data = response.read()
    print(data)
    conn.close()
except Exception as e:
    print("[Errno {0}] {1}".format(e.errno, e.strerror))

**Comment by mikebudzynski** [comment]
Related to #1284
