### ISSUE TITLE
API search query shareable link

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#554]
I have question:

Over time, there are several versions of an API.  I like to provide a link from an article in the new managed DevPortal to the API page where the API list is already filtered based on a search term to identify all versions of an API. It shall be possible to enter the search term with the linked URL. 
Is this already possible? Or would this require a feature request?

**Comment by mikebudzynski** [comment]
If you follow a naming convention, it's easy to search for all versions of an API:
![image](https://user-images.githubusercontent.com/40186513/77689354-c28f4680-6f5e-11ea-81a6-b52699fe18df.png)

As of now, there's no way to link to the search query/results.

**Comment by mikebudzynski** [comment]
We currently don't have plans to implement this functionality in the managed portal.
