### ISSUE TITLE
Publish designer - How to update managementApiAccessToken in design.config automatically?

### ISSUE THREAD

**Issue by lucaszacutti** [Azure/api-management-developer-portal#555]
We have deployed the designer to App Service but we have trouble with the managementApiAccessToken in the design.config file that expire every 30 days and force us to re-deploy every time. How we can do this automatically?

![image](https://user-images.githubusercontent.com/13422243/77687092-b5815000-6f7c-11ea-877a-5afaf8700e04.png)

Thanks!

**Comment by azaslonov** [comment]
Hi @lucaszacutti, there is no clear prescription at the moment (we'll document the recommended approach and examples at some point), so, for now, I would suggest creating an authentication endpoint that would generate a new SSO token in exchange to user credentials. It could be something very similar to the delegation feature.

Please have a look at this article:
https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-setup-delegation

...and this example:
https://github.com/Azure/api-management-samples/tree/master/delegation

Then SSO token could be consumed by the Authenticator like this one:
https://github.com/paperbits/api-management-developer-portal/blob/master/src/components/ssoAuthenticator.ts

Hope that helps.
