### ISSUE TITLE
Close button is hidden in the Tryit view

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#559]
## Bug description

When opening the "Tryit" option in the DevPortal it opens the sideview at the right, but the "close-cross" is behind the header.

## Reproduction steps

1. Go to one of your APIs
2. Use a header with background
2. Click on Try it
3. Try to close the opened view
4. See that there is no close icon/cross
5. Press F12
6. Set a different viewport (in the device toolbar)
7. See that the cross is hidden behind the header

## Expected behavior

Header is seen as fixed object ("Sticks to top") and the page adapts its contents to it

## Is your portal managed or self-hosted?

Managed

## Additional context

![image](https://user-images.githubusercontent.com/58420097/77752565-15810080-7028-11ea-8856-2a3dac9c6558.png)

**Comment by azaslonov** [comment]
Hi @ZarTrox, thanks for reporting the issue. We'll fix that.
