### ISSUE TITLE
OAuth/OpenId setup in Developer Portal

### ISSUE THREAD

**Issue by AvanadeAPIClinicTeam** [Azure/api-management-developer-portal#56]
If We have done OAuth/OpenId setup for an API, then Authorization header has been auto-populated in Developer Portal during testing once we select authentication option.

But in New Portal, There is no Authorization Header implemented, that means no OAUTH or external authentication can be used with operations.

**Comment by molinch** [comment]
This doesn't seem to be implemented yet, isn't it?

**Comment by michaeltnguyen** [comment]
@molinch The related github issue is https://github.com/Azure/api-management-developer-portal/issues/208

Based on the discussion on that issue, the latest ETA is 1/31, but I'm not sure how accurate that is.

**Comment by molinch** [comment]
Thanks, it's crazy that they deprecated the former portal, while new one doesn't have all the features... I don't understand that move

**Comment by mikebudzynski** [comment]
> the latest ETA is 1/31, but I'm not sure how accurate that is. 

The timelines have shifted; we don't have a precise ETA.

>  it's crazy that they deprecated the former portal

The old portal has not been deprecated.

**Comment by molinch** [comment]
Quoting MS website, and same on Azure portal:
> Has the old portal been deprecated?
> The old developer and publisher portals are now legacy features - they will be receiving security updates only. New features will be implemented in the new developer portal only.
> 
> Deprecation of the legacy portals will be announced separately. If you have questions, concerns, or comments, raise them in a dedicated GitHub issue.

If I may Legacy conveys the meaning that it is indeed obsolete and you should move to the new portal. Anyway it's not important, and I do hope the feature will be there soon.

Thanks a lot for the feedback on the topic.

**Comment by dgrospelier** [comment]
Still no ETA @mikebudzynski?

**Comment by mikebudzynski** [comment]
Please refer to #208 instead. 

> Still no ETA

Still no ETA.
