### ISSUE TITLE
The Developer portal takes longer time to fetch the API Operation details page

### ISSUE THREAD

**Issue by bala-muthugurusamy-by** [Azure/api-management-developer-portal#560]
## Bug description

The Developer portal takes longer time to fetch the API Operation details page for  APIs with huge data model [ The same API gets loaded very fast in Swagger UI or Redocs ]

Many of our APIs have larger data models . 

For example, the Developer portal takes more than 20seconds to retrieve the operation details
 for sample API https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml  
The spec  is very well within the 4MB limit. 

## Reproduction steps

1. Import Sample API  - https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml  in APIM and publish
2. Goto developer portal and open the imported  api
3. The browser  will take longer time to show the  operation page completely 

## Expected behavior
The response time should be in milliseconds. 

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: Mac , Windows
 - Browser: Chrome ,  Safari
 - Version: [e.g., 22]

## Additional context
Based on the browser metrics , http://<domain>.management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/apis/<api>/schemas?api-version=2018-06-01-preview is taking longer time
Please check the  screenshot below.

![API-OPERATION_DETAILS_LATENCY](https://user-images.githubusercontent.com/61602125/77840317-e7d8ac00-713a-11ea-8a48-810496251b1d.png)

**Comment by azaslonov** [comment]
Hi @bala-muthugurusamy-jdas, yes, this is a known issue, we're working on a few solutions which are mostly caching and gzip-related on the server- and client-side. However, since it is still a large file, you should set your expectations accordingly.

**Comment by JCAMPOLPA** [comment]
Hello
We are facing the same issue - we got 50+ APIs and when clicking on one of them, we never land to operation page to show the methods.
Any idea when it will be fixed and publish to Azure ?
Thanks a lot !!!

**Comment by mikebudzynski** [comment]
@JCAMPOLPA - that's likely unrelated. Make sure you specified the API details page in the settings of your API list widget (and saved and republished the portal): 
![image](https://user-images.githubusercontent.com/40186513/78700523-5693d300-78ba-11ea-9501-5cfdaa67e0ed.png)

**Comment by mikebudzynski** [comment]
We're planning to resolve the problem on the database level this summer.

**Comment by saikiran-karumuri-by** [comment]
@azaslonov @mikebudzynski Do we have any update this? Is this issues fixed ?

**Comment by azaslonov** [comment]
The issues has been fixed on the backend. It is being rolled out.
