### ISSUE TITLE
The navigation of deeply nested data model is very difficult

### ISSUE THREAD

**Issue by bala-muthugurusamy-by** [Azure/api-management-developer-portal#561]
## Bug description

The navigation of deeply nested data model is very difficult with the  flattened table based display.  

Both SwaggerUI and [Redoc](https://redocly.github.io/redoc/) are providing tree based display  to handle nested data models. 

 

## Reproduction steps

1. Import Sample API  - https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml in APIM and publish
2. Goto developer portal , select the loaded API 
3. Click on api_error type , then  click on payment_method type, then click on fpx type
3. Navigating back to the  previous type is difficult.

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: Mac , Windows
 - Browser: Chrome ,  Safari
 - Version: [e.g., 22]

## Additional context

**Comment by azaslonov** [comment]
Hi @bala-muthugurusamy-jdas, thanks for the suggestion, we'll discuss this internally, but can't make any promises at this point.

**Comment by azaslonov** [comment]
The issue has been addressed in #698. Deployment to managed version will happen sometime next week.
