### ISSUE TITLE
Minimum screen resolution

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#562]
Hi, what is the supported minimum screen size for the developer portal? 

In some scenarios the column headers tend to overwrite the exisiting text as shown below when resizing the page.

![image](https://user-images.githubusercontent.com/62035456/77860927-67b36300-726e-11ea-86df-f7a0639ae34b.png)

Would it be possible to allow text wrapping or set the minimum size of the columns?

Thanks

**Comment by azaslonov** [comment]
Hi @watson20201, thanks for reporting the issue. The table should be scrollable in this case. We'll fix that.

**Comment by azaslonov** [comment]
Fixed and deployed.
