### ISSUE TITLE
Signin and signup enabled flags do not appear to work with the new portal (work with the old)

### ISSUE THREAD

**Issue by bengimblett** [Azure/api-management-developer-portal#564]
## Bug description

In ARM (resource explorer) under "portalsettings" there is a "signin" and "signup" section - each has an enabled flag. This in effect disables the old dev portal sign-in and sign-up functionality (click on the link in old portal with unset flag and you get "administrator has disabled functionality" type message
This is going to be a problem where folks are using the external IP mode of APIM but dont want the dev portal in production
Possibly leaving the management API turned off (if it is not required for other reasons), and/or removing all "identities" providers may work, but this would be untidy

## Reproduction steps

Unset the flag(s) in resource explorer and test signin and signup in the new dev portal

## Expected behavior

Signup/signin functionality is disabled in new dev portal

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

latest

**Comment by azaslonov** [comment]
Hi Ben, those settings were primarily introduced for the legacy portal which practically has no way to control sign-in/sign-up. In new portal, you can just delete those widgets/pages altogether, no additional setting required. Would that be enough to resolve your issue?

**Comment by mikebudzynski** [comment]
In addition to that - you can remove the username and password identity in API Management (in the Azure portal) to disable it on the backend.

**Comment by bengimblett** [comment]
That's great, thanks for the additional workarounds

**Comment by sebas1307** [comment]
Both workarounds don't work for me. 

I cannot delete the sign up page (as described here: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal-customize#customize-the-portals-content). And if I remove the username and password identity in API management, nothing happens. Sign in and Sign up are still possible.
