### ISSUE TITLE
Objects within Objects are not rendering correctly

### ISSUE THREAD

**Issue by speedyps** [Azure/api-management-developer-portal#565]
An object within an object do not render correctly when viewing an API call, and the definition is excluded.

eg in the attached yaml, 
[Petstore YAML.txt](https://github.com/Azure/api-management-developer-portal/files/4410330/Petstore.YAML.txt)

A pet has an additionalinfo object, which contains a breedDetails object.  This renders as follows in the Swagger Editor
![image](https://user-images.githubusercontent.com/40074438/78051390-188a4100-73da-11ea-95a8-30ab005b6189.png)

But in the developer portal, it just shows additionalInfo as an object
![image](https://user-images.githubusercontent.com/40074438/78051475-3a83c380-73da-11ea-81a3-fa990fa41311.png)

And doesn't include the definition in the table, and doesnt render any of the object details
![image](https://user-images.githubusercontent.com/40074438/78051554-58e9bf00-73da-11ea-9d36-1b8361e63493.png)

This is preventing us from moving to the new portal.

**Comment by azaslonov** [comment]
Hi @speedyps, this is a known issue, please use #522 for tracking.

**Comment by speedyps** [comment]
Thanks

I will track it against that issue.

I only logged it because when I was reading the points raised and the discussion in #522 it seemed slightly different.

Happy if it is all going to be addressed as part of one case

Cheers

Peter.
