### ISSUE TITLE
Portal not wokring in IE Browser

### ISSUE THREAD

**Issue by jerryanto** [Azure/api-management-developer-portal#567]
Hi,

I see that the portal we developed does not work properly in IE browser.
The whole screen appears in a distorted way.

How compatible is the portal in the IE browser?
Is there anything to be done to make the application work in the IE browser.

I have attached the screenshot.
![IE](https://user-images.githubusercontent.com/60136522/78215774-f675e900-74d5-11ea-811d-4bf36f7d6a70.PNG)

**Comment by azaslonov** [comment]
Hi @jerryanto, that's right, we don't support IE browser anymore. We should have added the proper message for that.
