### ISSUE TITLE
Override Base URL

### ISSUE THREAD

**Issue by Robzilla** [Azure/api-management-developer-portal#569]
Hi all

I have Front Door setup with 2 custom URLs. The first is routed to the new Developer Portal and the second is routed to the API Gateway. 

Both work OK, I can access the new Developer Portal, login and test the Azure functions that are sitting behind the API Gateway.

I can hit the API Gateway via Front Door using Postman OK.

The problem is the Base URL in the New Developer Portal cannot be overridden to show the Front Door URL.

Any idea how to do this?

**Comment by Robzilla** [comment]
Ok here is where we set the Base URL in the Azure Potal
![image](https://user-images.githubusercontent.com/3105346/78637908-adb39b00-78ee-11ea-8c35-65d0bca28ef5.png)


And here is where it is displayed in the Dev Portal
![image](https://user-images.githubusercontent.com/3105346/78638136-1b5fc700-78ef-11ea-9d64-dbd4ff31739d.png)

**Comment by Robzilla** [comment]
The silence is deafening. How can customers use API Management with Front Door. The reason for this request is that I wish to put a Front Door endpoint in front of API Management and for the correct URL to be displayed in API Management. I have a system I wish to demonstrate to customers before going into production. Not going to demo the wrong URL. 20 days and no response. If you want people to use your products MS you need to be a bit more responsive.

**Comment by azaslonov** [comment]
Hi @Robzilla, sorry for the late response. Looks like we're talking about custom hostname for Gateway, which you can setup in Azure portal: https://docs.microsoft.com/en-us/azure/api-management/configure-custom-domain

Just in case, GitHub issues here is not a support channel for general questions, it is dedicated to developers using the self-hosted version of the developer portal. When you have managed service-related questions/issues, please refer to MS support, they will help you to solve it much faster.
