### ISSUE TITLE
Indicate subscription status (e.g., pending approval, approved, rejected etc.)

### ISSUE THREAD

**Issue by EdmundoMartinez** [Azure/api-management-developer-portal#57]
**Describe the bug**
If a user requests a subscription and it hasn't been approved, the user can request it over and over creating new requests in the backend. Not sure how the current portal works, but if a subscription exists for the user in the "Submitted" state, portal should not allow the user to request again.

**To Reproduce**
1. Request subscription to a product
2. The subscription is created in APIM backend as "Submitted" state
3. Navigate back to the product page

**Expected behavior**
The "Add subsctiption" button should not be shown, since one is in submitted state.

**Screenshots**

**Desktop (please complete the following information):**
No specific to OS/browser.

**Smartphone (please complete the following information):**
No specific to OS/browser.

**Additional context**
The product needs to have the "Requires approval" option enabled.

**Comment by mikebudzynski** [comment]
The new Product widgets will reflect subscription states. Merging with #187
