### ISSUE TITLE
PDF created from the DevPortal is unreadable

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#571]
## Bug description

When saving a page of the DevPortal as PDF the format is so small, that the header is squeezed together and some text is overlapping. Even when taking a PDF in landscape format the page format is the same.

## Reproduction steps

1. Go to a random DevPortal page
2. Click "ctrl"+"P"
3. Select "Save as PDF"
4. Save
5. See error

## Expected behavior

The PDF adapts to the size of the page/the page-css size value and prints a page looking exactly like the page in the browser

## Is your portal managed or self-hosted?

Managed

## Additional context

I also can't select the landscape format when trying to save the DevPortal.

**Comment by mikebudzynski** [comment]
We don't have plans to support printing the developer portal to PDF.
