### ISSUE TITLE
The Definitions of the APIs are not displaying the status code in its Name.

### ISSUE THREAD

**Issue by estebanbalvin** [Azure/api-management-developer-portal#572]
## Bug description
The Name of the definitions doesn't have any status code  to identify the description. Issue on the  Column length.
![image](https://user-images.githubusercontent.com/22824929/78628690-0849f880-78e9-11ea-9ae8-8e58895a8b14.png)

## Reproduction steps
Login as any user and click on Partners API vehicles.
Click on Get Models.
Scroll down to the definitions part of the page.

## Expected behavior

The Name of the definitions should have the status code visibility to identify the description.

## Is your portal managed or self-hosted?

Self-hosted

**Comment by azaslonov** [comment]
Hi @estebanbalvin, I assume you're talking about column width that doesn't fit the name of your definitions that, probably, have a code identifier in the end. Is that right?

**Comment by estebanbalvin** [comment]
Exactly

**Comment by azaslonov** [comment]
Ok, we'll see what we can do.

**Comment by mikebudzynski** [comment]
Merging with https://github.com/Azure/api-management-developer-portal/issues/537
