### ISSUE TITLE
[Improvement ]Navigation is only available after images have been loaded

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#573]
## Bug description

When navigating to a new page the images must finish loading, only then one can access the navigation. In the current times with homeoffice users may have slower internet than they are used to - therefore loading images may take some time. Allowing them to navigate before having all pictures present will increase the user experience for the users in question.

**Comment by azaslonov** [comment]
Hi @ZarTrox, are we talking about the published portal? Also, would be good to know the following:
- what is size of the image?
- what browser do you use?
- do you mind sharing the link to your portal?

**Comment by ZarTrox** [comment]
Hi @azaslonov, yes we are talking about the published portal.

Size: 600KB
Browser: Chrome

I couldn't reproduce this bug with my machine. But my coworker encountered this issue and I saw it during a meeting. I will close this Issue as long as there are no other questions.
