### ISSUE TITLE
user sign in processes not working (copy of #528)

### ISSUE THREAD

**Issue by santo2** [Azure/api-management-developer-portal#577]
**This is a hard copy of the item you guys closed. 
I don't get any help over mail, and no further response on the closed issue.**

Bug description
I'm trying to create a new developer portal, and I notice all the sign in pages and options are not working. I started by clicking the "Developer Portal" button in Azure API Management, and started to use the designer. I did not change anything specific except for some colors.
I did publish, and tried to log in.

Scenarios
When resetting the password in Azure API management portal,
Then I receive the mail with the new link
and when I click the link in the mail, I get to a page saying the page does not exist (reset-password)
EDIT: I tried to add this page, but it seems to be a reserved path

When inviting a new person, same thing: clicking on the link in the mail gets me to a non existing page (confirm-password)
EDIT: I tried to add this page, but it seems to be a reserved path

When trying to log in with an existing account to which I'm not sure of that the password is still correct, and I press the sign in button, it does a callback but does not show a validation summary, I don't know what is wrong now.
EDIT: I found out that the sign in page did not contain validation summary by default, that I have found and added.

Is your portal managed or self-hosted?
No idea what self hosted means? so I guess managed? I created it online and tried to publish from there.

Environment
Operating system: Windows 10
Browser: Google Chrome
Version: Version 80.0.3987.132 (Official Build) (64-bit)

Question: is this a ready to use product or is this still a BETA? I assume we are expected to start using this new portal for new functionality, but when the basic functionality does not work, it's very hard for us to make that choice.

**Comment by azaslonov** [comment]
Hi Peter, sorry, we missed your email. I found it and replied, let's follow up on that email thread.
