### ISSUE TITLE
New subscription that requires approval previously created and deleted don't request admin approval

### ISSUE THREAD

**Issue by EdmundoMartinez** [Azure/api-management-developer-portal#58]
**Describe the bug**
When a product with "Requires approval" approves a subscription for { product, user }; if the submission is deleted and the user requests it again for the same { product, user }, the approval is not required and the user gets the subscription without admin approval.

**To Reproduce**
1. Create a subscription request for a user and product
2. Admin approves the subscription
3. Admin deletes the subscription without cancelling or suspending the subscription
4. User requests subscription to the same product as done in number 1.

**Expected behavior**
The subscription requires admin approval before being active.
Since the admin deleted the subscription, this means the access to the product needs to be prohibited; the user can get access again without admin consent in this case.

**Screenshots**
NA

**Desktop (please complete the following information):**
Not os/browser specific

**Smartphone (please complete the following information):**
Not os/browser specific

**Additional context**
The product needs to have "Requires approval"

**Comment by azaslonov** [comment]
Hi Edmundo, this looks like a backend issue, the fix will take some time. I'll update you with ETA soon.

**Comment by azaslonov** [comment]
Edmundo, I just tried to reproduce the issue and could not. Can you please try again? and if it still doesn't work as expected, let's have a quick call.

**Comment by mikebudzynski** [comment]
Inactive issue

**Comment by EdmundoMartinez** [comment]
Reproduced the bug with code from master branch commit [fea2c44ef39721020df38fac68ae976deb16ff4b](https://github.com/Azure/api-management-developer-portal/commit/fea2c44ef39721020df38fac68ae976deb16ff4b).

Synced with @azaslonov and showed the problem.

@mikebudzynski, @azaslonov, could you help me reopen this bug?
