### ISSUE TITLE
Cannot edit default layout

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#580]
## Bug description

I cannot edit the default layout, for instance, editing the default Contoso image is not working.

## Reproduction steps

1. Go to layouts on a completely default site without modifications
2. Try Default or Home
3. Try and click on the Contoso image

![image](https://user-images.githubusercontent.com/4255748/79324608-24b0eb00-7f10-11ea-9712-f224f5c588ef.png)

## Expected behavior

Able to edit image, if i pull the 2.2.3 release it works, see image below:

![image](https://user-images.githubusercontent.com/4255748/79335867-09031000-7f23-11ea-8c10-dc636200f039.png)

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

43441ba9b2abcc952cfbaa479798d23e79dff25f but seems to behave the same around e5c31fd0d92e84377547234403a7def67313f830 as well

## Environment

 - Operating system: Windows
 - Browser: Chrome latest (81 but tried version 79 also) or Edge latest (81)

**Comment by azaslonov** [comment]
Hi @erwinkramer, thanks for reporting the issue. We'll fix that.
