### ISSUE TITLE
Cannot search by tag if tag display name is not the same as the tag resource name

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#584]
## Bug description

If you search for an API by selecting a tag, for instance CRM, it works, if you search for another one, where the tag resource name is not the same as the display name, then it will not find it. Grouping works fine though.
![image](https://user-images.githubusercontent.com/4255748/79736943-e134f300-82fa-11ea-8a80-1fc7d6a65dae.png)

## Reproduction steps

1. Go to your api management resource
2. Create a tag with a space in it for instance, so the display name will not match the resource name
3. add it to your api
4. try it out in the dev portal

## Expected behavior

Should just work by selecting the tags

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

https://github.com/Azure/api-management-developer-portal/commit/d8698eae20a5c80a3a0f292a5adbfcf1eddb27c0

## Environment

 - Operating system: Windows
 - Browser: Edge 
 - Version: Latest (chromium)

**Comment by azaslonov** [comment]
Hi @erwinkramer, thanks for reporting the issue, we'll fix it.

**Comment by azaslonov** [comment]
Looks like this problem has been fixed in the scope of another issue some time ago. Closing it.
