### ISSUE TITLE
"Unexpected end of JSON input" when using api-version=2018-06-01-preview

### ISSUE THREAD

**Issue by KevinHale-Bentley** [Azure/api-management-developer-portal#585]
## Bug description

Following the instructions from [https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal), `UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input` was encountered.

I was able to workaround this by changing the api-version to 2019-12-01 in scripts/generate.js.  Actually, using VS Code, I performed a search and replace of all `2018-06-01-preview` instances with `2019-12-01`.

I was able to repeat this in the following manners:
1. clone code from PowerShell; run generate.bat from Powershell
2. clone code from Git Bash; run generate.bat from Powershell
3. clone code from PowerShell; run generate.bat from Windows CommandPrompt

( I initially thought that this might be a Windows vs. *nix line- or file-ending issue, so I tried these steps first.  I list them here for full disclosure.  The API version was another guess...but one that worked for me. )

If my fix is more than a workaround, I am willing to submit a PR with the fix.  I'm filing this issue first to ensure that there isn't a different core issue that needs to be addressed.

## Reproduction steps

1. Follow steps 1 - 3 on the [Self-hosting the portal](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal) instructions
2. Error occurred  (see Addtional Context, below, for full outptu)

## Expected behavior

All content to be generated and uploaded to the storage account without error.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release `2.2.3`

## Environment

 - Operating system: Windows 10
 - PowerShell 6.2.4
 - Node 10.16.2

## Additional context

Full run output

```
PS D:\github\azure\api-management-developer-portal\scripts> .\generate.bat

D:\github\azure\api-management-developer-portal\scripts>set management_endpoint="<redacted>.management.azure-api.net"

D:\github\azure\api-management-developer-portal\scripts>set access_token="SharedAccessSignature <redacted>"

D:\github\azure\api-management-developer-portal\scripts>set storage_connection_string="DefaultEndpointsProtocol<redacted>;EndpointSuffix=core.windows.net"

D:\github\azure\api-management-developer-portal\scripts>set data_file="./data.json"

D:\github\azure\api-management-developer-portal\scripts>set media_folder="./media"

D:\github\azure\api-management-developer-portal\scripts>node ./generate "<redacted>.management.azure-api.net" "SharedAccessSignature <redacted>" "./data.json"
https://<redacted>.management.azure-api.net/contentTypes/page/contentItems/4e3cf6a5-574a-ba08-1f23-2e7a38faa6d8?api-version=2018-06-01-preview
(node:12428) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.resp.on (D:\github\azure\api-management-developer-portal\scripts\generate.js:31:34)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:12428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

D:\github\azure\api-management-developer-portal\scripts>node ./upload "DefaultEndpointsProtocol=https;AccountName=<redacted>;EndpointSuffix=core.windows.net" "./media"
Uploading file: 09879768-b2c8-afbd-a945-934c046b3c2d
Uploading file: 3e3d574f-0238-288b-0eb4-a51b3680ef4b
Uploading file: 70add409-0933-e01e-acef-99999a71167e
Uploading file: a2514081-47cb-95b1-ef0b-aef128c7a7ed
Uploading file: c5d2da83-b255-245c-144b-cd3c242e9791
Uploading file: ed8e43d0-5f8e-af38-5536-8f0274656ce4
DONE

```

**Comment by KevinHale-Bentley** [comment]
UPDATE:  Changing the API version everywhere was a bad idea.  This broke other things.  I'm still working through things, but for now I had to revert to the "preview" API version in config.design.json.

**Comment by azaslonov** [comment]
Hi @KevinHale-Bentley, I think you need to log what exactly gets returned from API to figure this out. On our side, looks like we need to improve error handling and messaging.

**Comment by KevinHale-Bentley** [comment]
@azaslonov, I'll have to find time to set this up again.  I just tried it on the environment (both local dev and storage account) that I've been working in, and the error didn't occur.  I think I'll need to temporarily create a new SA and pull the code clean again.  I'm in the thick of some things right now, so it may be later this week or next before I can get to it.

**Comment by KevinHale-Bentley** [comment]
Also, I should note that I had Fiddler running and it captured nothing.  I have several filters in place to keep a lot of the noise out.  So, I'll either need to figure out that issue or find an alternative for capturing the HTTP traffic.

**Comment by mikebudzynski** [comment]
@KevinHale-Bentley Let us know if the problem reoccurs. We have plans to migrate the portal to the newest API version.
