### ISSUE TITLE
Refused to execute script

### ISSUE THREAD

**Issue by mploksvenningsen** [Azure/api-management-developer-portal#586]
## Bug description

There seems to be a problem with a MIME type on vendor.js.

![image](https://user-images.githubusercontent.com/64144346/79984568-a45b2e80-84a9-11ea-95b2-eb9de7e99657.png)

## Reproduction steps

1. Go to https://bilinfoapipoc.developer.azure-api.net/
2. Open the developer console
3. The error is present on all pages

## Expected behavior
No errors in console is expected.

## Is your portal managed or self-hosted?
Managed 

## API Management service name
bilinfoapipoc

**Comment by mploksvenningsen** [comment]
I reset the content of the portal so it is back to the base layout/template, the problem is still there

**Comment by azaslonov** [comment]
Hi @mploksvenningsen, this is an old artifact, it is not used in fact, a just reference remained in the page template. It will be gone with one of the next releases. Thanks for bringing our attention to it.

**Comment by TravisLRiffle** [comment]
I'm assuming we can remove the reference?
