### ISSUE TITLE
What is the correct route to reset password of  a non authenticate user?

### ISSUE THREAD

**Issue by giovannaalves** [Azure/api-management-developer-portal#587]
I am trying to reset my password, but i receive an email with a incorrect route: **"myportalurl/password?userid=myuserid&tickerid=mytickerid"** (404). What is the correct route for change a password of an user not authenticated in the new portal (self-hosted)?
There is a "change-password" route, but if the user is not logged in, they are automatically redirected to the homepage...

**Comment by ygrik** [comment]
myportalurl/**confirm-password**?userid=myuserid&tickerid=mytickerid
