### ISSUE TITLE
Components don't load in Edge Browser

### ISSUE THREAD

**Issue by velsietis** [Azure/api-management-developer-portal#589]
## Bug description

The Knockout components no longer load in Edge Browser

## Reproduction steps

1. Open the Developer Portal in Microsoft Edge browser
  APIs. Products, Sign in, Sign Up
2. Go to to a page with components, e.g.  APIs. Products, Sign in, Sign Up
3. Observe that the knockout components are not displaying, e.g. API List or Sign In form

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

commit 85c0284

## Environment

 - Operating system: Windows 10
 - Browser: Microsoft Edge
 - Version: 42.17134.1098.0 (EdgeHTML 17.17134)

## Additional context
I found no uncaught errors when attempting to debug in VS Code and not familiar enough with Inversify to dig any deeper.

> Side note - this was previously working so I attempted git bisect to find the commit which broke it, but gave up as the config files appear to have been written out of history at some point ;)

**Comment by azaslonov** [comment]
Hi @velsietis, yes, this is known issue, we have a fix ready for this, it will be merged soon.

**Comment by velsietis** [comment]
Great, thanks for the quick reply.  
I figured it had probably been noticed but thought it worth mentioning just in case.

**Comment by velsietis** [comment]
UPDATE: strangely we can't seem to replicate the bug today.  Myself and another developer had it consistently on Friday (on separate computers) but today the components are loading fine.  I was thinking Edge might have got updated in the background, but the version numbers are still the same as I've logged here and I haven't updated our fork - super strange.

**Comment by azaslonov** [comment]
That's right, the new Edge release has fixed the issue. Looks like they finally switched to Chromium.

**Comment by azaslonov** [comment]
This issue has been fixed, whoever has this issue, just please pull the latest bits. For the managed version the release is in progress and should be complete by the end of next week.
