### ISSUE TITLE
New Developer Portal using Delegated Authentication does not send returnUrl

### ISSUE THREAD

**Issue by miller79** [Azure/api-management-developer-portal#590]
## Bug description

When using the new managed developer portal with delegation enabled, it only adds returnUrl on the first request and it doesn't seem to add it to any others.

## Reproduction steps

1. Setup Delegated Authentication
2. Go to the new Developer Portal
3. Ensure you are signed out
4. Sign in
5. Observe there is no returnUrl query parameter to effectively validate the salt and sig.

## Expected behavior

The returnUrl should be in the query parameters to allow for validation.

## Is your portal managed or self-hosted?

Managed

## Additional context

[StepsToCreateIssue.zip](https://github.com/Azure/api-management-developer-portal/files/4532208/StepsToCreateIssue.zip)

**Comment by cotheer** [comment]
Any news on this bug?

I also have this problem, except i can sign in once but after signing out, I'm unable to sign in/up again.

**Comment by mikebudzynski** [comment]
@cotheer We're investigating the problem. cc: @ygrik

**Comment by DevJoshi007** [comment]
Hello dev here,
after moving .portal to .developer portal when i subscribe any product signature not matched in .developer portal but old .portal working going fine any solution ?

**Comment by ygrik** [comment]
Hello @DevJoshi007 
We have an issue in .developer with variables order
HMAC(salt + '\n' + productId + '\n' + userId)

**Comment by DevJoshi007** [comment]
When it will be solve?

**Comment by mikebudzynski** [comment]
Referencing #552

**Comment by mikebudzynski** [comment]
The fix is included in the release we're rolling out now. ETA for full deployment is ~2 weeks.

**Comment by DevJoshi007** [comment]
how to redirect sso token to developer portal because sso token created
based on portal.asp.net.com so please give me solution

**Comment by DevJoshi007** [comment]
Hi Dev here, i am also facing a problem with unsubscribe a product in new developer portal. there is not any product ID and user ID any region?
