### ISSUE TITLE
Too Many Pages Returned On Pagination

### ISSUE THREAD

**Issue by Jshbrck** [Azure/api-management-developer-portal#591]
## Bug description

When using pagination buttons to paginate through APIs, I'm able to navigate to many more pages than we have APIs, we only have 2 pages.

## Reproduction steps

1. Have a set of APIs that must be paginated
2. Scroll down to the bottom
3. Click the pagination caret really fast 
4. If you click fast enough, you should get more pages than you have
5. See replication gif at the bottom of the page
6. Error message in console reported at the bottom as well

## Expected behavior

To only be able to navigate to the two pages of APIs that we have.

## Is your portal managed or self-hosted?

Managed - [Portal](https://dev-developer.hcssapps.com/)

## Environment

 - Operating system: WIN 10
 - Browser: CHROME
 - Version: 80.0.3987.163 (Official Build) (64-bit)

## Additional context
![Report_ExtraPages](https://user-images.githubusercontent.com/36238283/80403143-b90e3c80-8884-11ea-9df2-5f687964e73d.gif)

![image](https://user-images.githubusercontent.com/36238283/80403248-f4107000-8884-11ea-936e-1a755b90e3c1.png)

**Comment by azaslonov** [comment]
Hi @Jshbrck, thanks for reporting the issue, we'll fix it.
