### ISSUE TITLE
"APIs" Navigation menu not highlighted

### ISSUE THREAD

**Issue by neterium** [Azure/api-management-developer-portal#593]
## Bug description

If I click on the APIs navigation menu, I go to the API list page and the menu is highlighted as expected. However, if I select one API in the list to jump to the operations list no more item is highlighted; I would have expected it still APIs.

## Expected behavior

Actually the nav-link-active class is missing on the APIs item in that case, and it should be the case for all the pages under the API list root level, IMHO.

## Is your portal managed or self-hosted?

Managed

## API Management service name

neterium

**Comment by azaslonov** [comment]
Hi @neterium, yes, it makes sense. We'll see what we can do.

**Comment by mikebudzynski** [comment]
Merging with #476
