### ISSUE TITLE
Oauth AzB2C - already logged used not recognized

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#594]
On a clean browser, I log onto Azure B2C with an existing identity and get access to one of our portals. Then I go to the New API Developer Portal and use the Sign-in Oauth widget  (as the user is already declared with an AzB2C identity)

Identity is not recognized and I get stuck on page:
https://XXXXXX.developer.azure-api.net/signup-oauth#provider=AadB2C&token=xxxxxxxxx

Is there any known bug on SSO with Azure B2C on the Dev API portal ? 

## Reproduction steps

1. Create a user on Azure B2C
2. Through REST API, declare user with identity provider AadB2C for that Azure B2C user
3. log with that user on another portal (Sharepoint online, Azure Devops...whatever)
4. then switch to Dev Portal, go to Signin and click onto Signin:Oauth widget
5. you are forwarded to https://XXXXXX.developer.azure-api.net/signup-oauth#provider=AadB2C&token=xxxxxxxxxxxxx

## Expected behavior

SSO should work and once clicked on Signin:Oauth widget, the user should be recognized and be logged, with ability to see its Profile for example.

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

Latest Managed version

![image](https://user-images.githubusercontent.com/26059633/80520016-25726400-8989-11ea-95fa-3389cb385cde.png)

**Comment by azaslonov** [comment]
Hi @JCAMPOLPA, looking at your screenshot, it seems like you deleted /signup-oauth page, which was supposed to complete user registration in APIM. Can you confirm?

Also, to further assist you, we'll need your service name, please send it to apimportalfeedback@microsoft.com and reference this issue.

**Comment by JCAMPOLPA** [comment]
Hi Alexander
We do use the Managed version, but didn't delete /signup-oauth page. 
I either don't see it in the list of Pages
![image](https://user-images.githubusercontent.com/26059633/80682130-3c68a180-8ac2-11ea-959a-9df51debb7f0.png)

I only see a widget. 

How shall I configure it ? Create a blank hidden page where the signup:oauth is referenced ?

Also my goal is to have SSO between a website where we do use AzB2C for Authent and having the ability to be recognized when going onto Dev Portal.
Shall I generete a SSO link with API with https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/user/generatessourl 

Any guidance welcome

**Comment by JCAMPOLPA** [comment]
Under the hood, I also see a 401 error on APIM
![image](https://user-images.githubusercontent.com/26059633/80682704-4ccd4c00-8ac3-11ea-9872-e5fbcfdd8e89.png)

**Comment by JCAMPOLPA** [comment]
OK, I managed to make it work !!!

Reusing https://github.com/Azure/api-management-developer-portal/issues/329
But please create documentation on it, it is hard to crawl all the blogs and gituhb issues.

Create a SAS token
Use /users/{userid}/token?api-version=2018-06-01-preview and get a token
Use https://service-name.developer.azure-api.net/signin-sso?token=xxx as url and it works.

Hard to find but it works.

**Comment by azaslonov** [comment]
Hi @JCAMPOLPA, glad you have figured this out. You're right we should add the docs.

**Comment by JCAMPOLPA** [comment]
Hi Alexander

However, I do not figure out why the Signin:Oauth widget is not working - SSO should be OOB no ?

**Comment by JCAMPOLPA** [comment]
Is it because of this failure - 401 on calling identity web service ?
![image](https://user-images.githubusercontent.com/26059633/81064327-cdcc7f00-8ed9-11ea-8a0c-8d739717d91a.png)

**Comment by Spetrut** [comment]
> OK, I managed to make it work !!!
> 
> Reusing #329
> But please create documentation on it, it is hard to crawl all the blogs and gituhb issues.
> 
> Create a SAS token
> Use /users/{userid}/token?api-version=2018-06-01-preview and get a token
> Use https://service-name.developer.azure-api.net/signin-sso?token=xxx as url and it works.
> 
> Hard to find but it works.

Hi @JCAMPOLPA , how did you get the id of the user to use in the req?

**Comment by JCAMPOLPA** [comment]
Hi @Spetrut 
Just use a GET on /users and use the filters to get the user id
