### ISSUE TITLE
OpenApi definition with "oneOf, anyOf, allOf" is not displayed in the Developer Portal

### ISSUE THREAD

**Issue by IljasM** [Azure/api-management-developer-portal#598]
In OpenApi 3.0.1 I implemented an "oneOf" specification from the official Swagger website: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

I copied the Petstore sample from the website one to one, but the representation section does neither show definition nor example in the developer portal. I tried  with "oneOf, anyOf, allOf" and  **none** them are working.

## Bug description
Below you can see an **"oneOf''** specification:

![image](https://user-images.githubusercontent.com/60928304/80694277-92464500-8ad4-11ea-88a8-88c0ad8d16a4.png)
OpenApi:
![image](https://user-images.githubusercontent.com/60928304/80695280-f6b5d400-8ad5-11ea-8097-7cbe57cc6f3c.png)
![image](https://user-images.githubusercontent.com/60928304/80695585-69bf4a80-8ad6-11ea-841b-e7b8f1d7e0da.png)

In the **Developer Portal** it looks like this:

![image](https://user-images.githubusercontent.com/60928304/80695790-b1de6d00-8ad6-11ea-9bbb-29a6a6a13245.png)

---
## Reproduction steps

1. Go to https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/
2. Choose one specification with "oneOf" or "anyOf/allOf"
3. Copy the specification in you OpenApi 3.0.1
4. Go to Developer Portal
5. See the empty representation section without definition and example
---
## Expected behavior
That the "oneOf, anyOf, allOf" definition and example is displayed correctly

## Is your portal managed or self-hosted?
Managed 
##
I look forward to your feedback and I hope it gets fixed

**Comment by azaslonov** [comment]
Hi @IljasM, this issue has been [fixed](https://github.com/Azure/api-management-developer-portal/pull/581) from time ago, it just not deployed to managed environments (should be out next week).
