### ISSUE TITLE
Azure API Management new developer portal Sign in Page auto re-loading

### ISSUE THREAD

**Issue by Praveen6867** [Azure/api-management-developer-portal#606]
Hi Team,

Azure API Management new developer portal (https://***.developer.azure-api.net/signin )Sign in Page auto re-loading.

**Reproduce steps (Authentication type: User and Password):**

1. Sign in to the new developer portal (https://***.developer.azure-api.net/signin).
2. Sign out or wait for 20min for the session expire.
3. Click on refresh or navigate the same sign-in URL in the same tab.

**Browser console**

Refused to execute script from 'https://***.developer.azure-api.net/scripts/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by azaslonov** [comment]
Hi @Praveen6867, thanks for reporting the issue.

**Comment by mikebudzynski** [comment]
Merging with #487
