### ISSUE TITLE
Query parameter examples are not displayed

### ISSUE THREAD

**Issue by alanwales** [Azure/api-management-developer-portal#610]
## Bug description

In open api it is possible to set examples how to use certain query parameters. Here is an example shown in the Swagger UI:

![image](https://user-images.githubusercontent.com/17590123/81803157-91bb9e80-9517-11ea-94de-75464c5f520a.png)

The open api document looks similar to this:

`"name": "$filter",
                        "in": "query",
                        "allowReserved": true,
                        "schema": {
                            "type": "String"
                        },
                        "examples": {
                            "Arithmetic Operators": {
                                "description": "Value le 333.333"
                            }
...,`
## Expected behavior

It would be great if the portal would also display these examples as they are very helpful for users

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @alanwales, yes, that makes sense. Thank you.

**Comment by mikebudzynski** [comment]
The portal already shows the examples, if they're defined. The new API Management release will automatically generate API request examples from the schema if they aren't explicitly defined (during API import).

**Comment by alanwales** [comment]
Thanks for the update, I republished the portal but still did not see the api examples (they are definitely in the open api v3 doc as above). Will try again in 4 weeks, cheers

**Comment by mikebudzynski** [comment]
Apologies @alanwales , we miscategorized the issue. I meant payload examples, but I now see that you are referring to query parameters examples. We will reopen this issue and treat it as a feature request.

**Comment by azaslonov** [comment]
UPDATE: looks like we're missing backend support for this before enabling UI. Our engineers are working on it already.

**Comment by pierrehody** [comment]
Hi there! Any news about that feature? Seems to be still unavailable. My yaml example looks like below, and no luck with it in developer portal. Any idea to have the example properly shown on the portal?

Thanks

get:
      summary: ************
      description: Return ************.
      operationId: ****************
      parameters:
        - name: objectid
          in: query
          description: *******************
          required: true
          schema:
            type: string
            example: 0902c57581548bf9

**Comment by azaslonov** [comment]
Fixed in #1449

**Comment by azaslonov** [comment]
Hi @pierrehody, have you tried to re-publish portal recently? This feature has been deployed everywhere.

**Comment by pierrehody** [comment]
Hi Mike,

Cf 1483<https://github.com/Azure/api-management-developer-portal/issues/1483>


Regards,

Pierre
