### ISSUE TITLE
Missing subscriptions on the Profile page

### ISSUE THREAD

**Issue by DavidFreetly** [Azure/api-management-developer-portal#622]
## Bug description

The Profile page is missing the user subscriptions and is generating an error in the browser console.  See the attached screenshot.

## Reproduction steps

1. Go to the Profile page
2. Notice that there are no subscriptions listed in the Subscription details table.
3. Open the browsers developer tools and see the error in the Console tab.
4.  error message:
theme.js:2 Uncaught (in promise) TypeError: Cannot read property 'displayName' of undefined
    at new exports.Product (theme.js:2)
    at theme.js:2
    at Array.map (<anonymous>)
    at exports.ProductService.<anonymous> (theme.js:2)
    at Generator.next (<anonymous>)
    at fulfilled (theme.js:2)

## Expected behavior

The user's subscriptions should display on the Profile page.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: iOS
 - Browser: All browsers

## Additional context

![Screen Shot 2020-05-19 at 10 18 37 AM](https://user-images.githubusercontent.com/4295769/82345877-64f60400-99bb-11ea-9071-7299a92b0579.png)

**Comment by azaslonov** [comment]
Hi @DavidFreetly, this issue has been fixed and service on your screenshot has been updated. Please just re-publish the portal to pick up changes. For the self-hosted version, just pull the latest bits from master branch.
