### ISSUE TITLE
Cannot sign-in to the developer portal 

### ISSUE THREAD

**Issue by EdiNation** [Azure/api-management-developer-portal#623]
## Bug description

After resetting the new developer portal, I am no longer able to log in as a non-admin user

## Reproduction steps

1. Go to https://devportal.edination.com, this redirects me to https://devportal.edination.com/signin
2. Type in my user name/password and click Sign in
3. The page starts to redirect in a loop to https://devportal.edination.com/signin, over and over again

## Expected behavior

To be able to go to https://devportal.edination.com and sign in

## Is your portal managed or self-hosted?

Managed 

## API Management service name

edination

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome and Edge
 - Version: 81.0.4044.138

## Additional context

In the portal identities, Redirect anonymous users to the sign-in page is checked. If it is left unchecked, it redirects to the home page but with no signed-in user, and clicking on sign-out returns to the same home page:

![Capture1](https://user-images.githubusercontent.com/61020611/82355637-64c92900-99fa-11ea-9479-1d85ed4590ee.PNG)

**Comment by azaslonov** [comment]
Hi @EdiNation, looks like a bug, I'm investigating.

**Comment by azaslonov** [comment]
@EdiNation it is fixed now. Your service has been upgraded partially by some reason, we're working on this.
