### ISSUE TITLE
Publishing the Developer Portal causes SharedAccessSignature error

### ISSUE THREAD

**Issue by DavidFreetly** [Azure/api-management-developer-portal#624]
## Bug description

I republished the Developer Portal to get the latest bug fixes and enhancements and now none of the pages display data.

## Reproduction steps

1. Go to the Developer Portal
2. Click on the Explore APIs button
3. Open the browser console and see the following error
4. Error: SharedAccessSignature token format is not valid.

## Expected behavior

Developer Portal pages with data.

## Is your portal managed or self-hosted?

Managed

## API Management service name

djf-pilot-test

## Environment

 - Operating system: iOS
 - Browser: All browsers

## Additional context

<img width="1430" alt="Screen Shot 2020-05-19 at 1 36 48 PM" src="https://user-images.githubusercontent.com/4295769/82365819-d8f1d580-99d6-11ea-85eb-8bbd4e707444.png">

**Comment by azaslonov** [comment]
David, please try to re-publish the portal in about 30 min, this issue should be gone.

**Comment by azaslonov** [comment]
The issue should be gone by now.

**Comment by DavidFreetly** [comment]
The Developer Portal is still not working.  The strange thing is that when I go into the Developer Portal it acts like I'm already authenticated and has the 'Sign out' menu item.

![Screen Shot 2020-05-19 at 2 37 47 PM](https://user-images.githubusercontent.com/4295769/82370580-67b62080-99de-11ea-8422-4c20b4f7021e.png)

**Comment by azaslonov** [comment]
Have you republished it?

**Comment by DavidFreetly** [comment]
yes

**Comment by azaslonov** [comment]
ok, looks like we have to rollback.

**Comment by azaslonov** [comment]
Rolled back your service.
