### ISSUE TITLE
Profile page is not showing the subscriptions 

### ISSUE THREAD

**Issue by cvijayak** [Azure/api-management-developer-portal#626]
**We noticed the profile page in the developer portal is not showing the subscriptions. But it was working properly couple of weeks back. When I see the source code, I am seeing couple of changes have been pushed to master branch recently(in May 2020). Suspecting that could break the things. Please let me know**

## Bug description

Profile page is not showing the subscriptions 

## Reproduction steps

Pre-conditions : I have couple of subscriptions already and it was created using my account. 

1. Go to 'new developer portal'
2. SignIn with your credentials
3. After the successful login. Click on 'Profile'
4. You can see 'no subscriptions'

## Expected behavior

Profile page should show all available subscriptions that are created using my account

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Google Chrome, Internet Explorer

## Additional context

![image](https://user-images.githubusercontent.com/65659375/82442544-7fb0a180-9abd-11ea-972d-806699f1f77a.png)

**Comment by JCAMPOLPA** [comment]
Hello
Same issue here - how shall we understand which "version" of the portal are we running when in Managed mode ? How can we know build rollout as reached our tenant ?

**Comment by azaslonov** [comment]
This has been fixed. Release to managed version is in progress, it should reach all the regions by mid to end of next week.
