### ISSUE TITLE
Version set "Description" text doesn't appear anywhere on new portal layout. 

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#627]
## Bug description
Under the "Version Set" settings for an API, there is a field "Description" that can contain text that is "visible on the developer portal".
![image](https://user-images.githubusercontent.com/65634611/82499094-efb32d80-9aa5-11ea-88cd-82009e5b8b07.png)

When viewing the old layout, you can see the text is placed here
![image](https://user-images.githubusercontent.com/65634611/82498307-9b5b7e00-9aa4-11ea-8a82-ba50385092c6.png)

However, on the new site layout, this text doesn't appear.
![image](https://user-images.githubusercontent.com/65634611/82498375-b7f7b600-9aa4-11ea-979d-50a5545899b3.png)

## Reproduction steps

1. Go to API Management Service ->General->APIs
2. Click on 'Echo API' (default one in the initial deployment)
3. Select the triple dots to create a new version from this version. 
4. Once the version is created, select the top level "Echo API" node
![image](https://user-images.githubusercontent.com/65634611/82498611-29376900-9aa5-11ea-8fb1-5f4a7673f1f9.png)
5. Enter text in the "Description" field
6. Review text content on the site (both old and new version)

## Expected behavior

The "Description" text would be visible somewhere in the new layout. 

This might be by design because this field is there to support legacy portal design. Maybe have a note on this field indicating the Description text will only appear on the legacy portal. 

Unless you can see a logical place to use this text on the new page layout. 

## Is your portal managed or self-hosted?

Managed

## API Management service name

Default setup

## Environment

 - Operating system: Windows 10
 - Browser: Edge Chromium
 - Version: 81.0.416.77

**Comment by azaslonov** [comment]
@VWACBrick, yes, makes sense. Thanks for bringing this up.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
