### ISSUE TITLE
Unable to save uploaded images in Developer portal

### ISSUE THREAD

**Issue by dvXcode** [Azure/api-management-developer-portal#630]
## Bug description

Failed to load resource: the server responded with a status of 404 (Not Found)
hostname******/:1 Access to XMLHttpRequest at 'https://hostname******/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/contentTypes/blob/contentItems/910c6451-ce29-02ff-de92-fe4303f83220?api-version=2018-06-01-preview' from origin 'https://hostname******' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
hostname******/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/contentTypes/blob/contentItems/910c6451-ce29-02ff-de92-fe4303f83220?api-version=2018-06-01-preview:1 Failed to load resource: net::ERR_FAILED
paperbits.js:2 Uncaught (in promise) Error: Could not update object 'uploads/910c6451-ce29-02ff-de92-fe4303f83220'. Error: Unable to complete request. Error: Could not complete the request. Please try again later.
    at exports.MapiObjectStorage.<anonymous> (paperbits.js:2)
    at Generator.throw (<anonymous>)
    at rejected (paperbits.js:2)

## Reproduction steps

1. Go to developer portal from API Management
2. Select Media
3. Click on Upload file
4. Confirm that file is uploaded
![Screenshot_15](https://user-images.githubusercontent.com/51912361/82536449-c697a900-9b48-11ea-8c59-a2e02194dae8.png)
5. Click on Save button
![Screenshot_16](https://user-images.githubusercontent.com/51912361/82536569-f050d000-9b48-11ea-938e-26a777cbdcb3.png)

6. See error
![image errors](https://user-images.githubusercontent.com/51912361/82536585-f8a90b00-9b48-11ea-8121-79ccfafa513f.png)

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser: Google Chrome 81.0.4044.138
 - Version: 81.0.4044.138

**Comment by azaslonov** [comment]
Hi @dvXcode, since it is managed version, I believe your service is behind VNET?
If yes, please take this to MS support, they should be able to help you resolve it.
If not, please send your service name to apimportalfeedback@microsoft.com, we'll have a closer look.
