### ISSUE TITLE
How to add new widgets in managed developer portal

### ISSUE THREAD

**Issue by cvijayak** [Azure/api-management-developer-portal#634]
Hi Team,

We are trying to customize the default **managed developer portal** pages. As part of it, we are trying to **create** new widgets. Please let me know how to do that with **managed developer portal**. Because I am unable to find any options in the developer portal to do the same. 

Also, if any documents or links which shows the steps that will be helpful.

Thanks,
Chandrasekar. V

**Comment by mikebudzynski** [comment]
You can create new widgets only in the self-hosted version of the portal.

**Comment by cvijayak** [comment]
Thanks for this information. If this is the only option then let me ask another question in this context.

We are trying to customize the "API List" and "Products" pages. Currently, these pages shows the items in a list view. We just want to customize the list view to match our requirements. Is there a way we can customize the existing widgets(i.e., API List, Products) with the help of managed developer portal?

We are more interested to use managed developer portal than self-hosted version of the portal

**Comment by mikebudzynski** [comment]
@cvijayak What do you precisely mean by "customize pages"?

**Comment by cvijayak** [comment]
Hi @mikebudzynski

We are trying to change the UI of "APIs" page. Please find the screenshots below

Below is the existing UI of "APIs" page
![image](https://user-images.githubusercontent.com/65659375/82855610-624e5e00-9f29-11ea-9dfb-a60f8f04c265.png)
 
We are trying to change the existing UI like below
![image](https://user-images.githubusercontent.com/65659375/82855681-975ab080-9f29-11ea-8f8e-dbdb2cd1efc7.png)

If you see the above UI, we suppose to call a management API to get products to show how APIs are associated with products. Looks like this is the extra call the widget has to make to get the product details.

Thanks,
Chandrasekar. V

**Comment by mikebudzynski** [comment]
The List of APIs (tiles) widget allows you to display the APIs in a similar form. However:
- You can't display dedicated icons for APIs without "hacks", because the list of APIs comes from the backend and API Management can't store icon information
- If you want to manipulate the content of the tiles, you need to go with the self-hosted version

**Comment by GPRepo** [comment]
Is any documentation for self hosting. Local host getting blank screen while npm start.
