### ISSUE TITLE
Azure Portal "Try It Feature" No Url Encoding of Parameters for Get Request

### ISSUE THREAD

**Issue by hebe0022** [Azure/api-management-developer-portal#635]
## Bug description

When testing an API in the Portal with the TryIt Feature. The values entered for parameters are not encoded. Get Requests fail when using reserved characters like &.

## Reproduction steps

1. Go to the developer portal
2. Click on an API
3. Select a Get request with a parameter.
4. Add a parameter.
4. Enter a value with the & character.

## Expected behavior

Url Encode Values Automatically or checkbox to allow encoding

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser:Google Chrome
 - Version: [e.g., 22]

## Additional context

EX: P&T will yield /qac/factories/search?name=P&T&country=USA [does not work]

and

EX: P%16T will yield /qac/factories/search?name=P%16T&country=USA [Works obviously]

![image](https://user-images.githubusercontent.com/1830950/82693645-e655cc80-9c2f-11ea-8b4e-ff6de4a634e4.png)

Is this by Design and is there a way to turn on UrlEncoding in the portal automaticly I do not see a way to do so.

**Comment by azaslonov** [comment]
Hi @hebe0022, thanks for reporting the issue, we'll fix this.

**Comment by ygrik** [comment]
It was fixed in managed with the latest release
