### ISSUE TITLE
Browser back button not working

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#638]
When navigating down through complex data types, the back button on the Chrome browser does not work.

Eg, clicking on complex type applic... will navigate to the object, but you cannot go back clicking on the browser back button.
![image](https://user-images.githubusercontent.com/62035456/82856017-0c95a800-9f61-11ea-9f75-29cda66cd5b9.png)

**Comment by azaslonov** [comment]
Hi @watson20201, this is a known issue, we'll work on it soon. Similar issue #521.
