### ISSUE TITLE
Try It - not sending subscription key header

### ISSUE THREAD

**Issue by DavidFreetly** [Azure/api-management-developer-portal#639]
## Bug description

The Ocp-Apim-Subscription-Key header value is not being set the first time using the 'Try It' feature.  A workaround is to select a different subscription key from the dropdown.

## Reproduction steps

1. Go to the API Details page
2. Select an operation
3. Click on the 'Try it' button
4. Notice that there is no Ocp-Apim-Subscription-Key listed in the Headers section.
5. Fill out any required parameters and click 'Send'
6. You will receive a 401 - Unauthorized response.
7. A workaround is to choose a different subscription key from the dropdown.

## Expected behavior

The default subscription key that is filled in the dropdown should also be set as the default Ocp-Apim-Subscription-Key header.

## Is your portal managed or self-hosted?

Managed

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system:  iOS
 - Browser: Firefox

## Additional context

![Screen Shot 2020-05-26 at 8 40 22 AM](https://user-images.githubusercontent.com/4295769/82910929-db04e880-9f30-11ea-8bc7-74e44d714704.png)

![Screen Shot 2020-05-26 at 8 41 08 AM](https://user-images.githubusercontent.com/4295769/82909901-80b75800-9f2f-11ea-9217-e0c7edf979e2.png)

**Comment by azaslonov** [comment]
David, this issue has been fixed and rolling out in the current release.
