### ISSUE TITLE
How to insert executable html and javascript code (not visible) in a page or layout of the API?

### ISSUE THREAD

**Issue by phbord** [Azure/api-management-developer-portal#640]
How to insert executable html and javascript code (not visible) in a page or layout of the API?

I'd try to create a script with a new **_Text_ widget** and **_Toggle code_ tool**, but when i watch the web page api : 
- result is inserted in a **_<code>_ tag** and **visible**
- his content become a **String**
- the script is **not executable**

Please, do someone knows some solutions ?
thanx.

`<script id="CookieDeclaration" src="https://consent.cookiebot.com/.../...js" type="text/javascript" async></script>`

**Comment by azaslonov** [comment]
I assume you're asking about managed version of the portal. If yes, the short answer is you can't do that, you'll have to go with a self-hosted option and make the change to the portal's codebase.
