### ISSUE TITLE
How to integrate a Cookie management tool for GDPR compliance ?

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#641]
Hello 

As we cannot integrate scripts into new Portal (which was possible on the former version), how can we integrate cookie bots so to be GDPR compliant in Europe ?

For example, we integrated CookieBot.com in former APIM Portal
https://www.cookiebot.com/en/about/

with a simple script tag
<script id="CookieDeclaration" src="https://consent.cookiebot.com/xxxxxxxx/cd.js" type="text/javascript" async></script>

If no alteration of the portal is possible, APIM portal software can't be used in Europe :-(

Any idea ?

**Comment by azaslonov** [comment]
Hi @JCAMPOLPA, there is no way to inject scripts I managed version. However, we have [integration with Google Tag Manager](https://github.com/Azure/api-management-developer-portal/wiki/Integrate-Google-Tag-Manager), which, in turn, has [integration with the Cookiebot](https://www.cookiebot.com/en/google-tag-manager-and-gdpr-compliance-with-cookiebot/).

**Comment by JCAMPOLPA** [comment]
Hi @azaslonov 

Great news - didn't look at it as it was in the self-hosted version. Thus,  I do not understand where I can install node.js package in a Managed environment.

For EU countries, shall we say Self-Hosted portal is the only realistic way to go with APIM  ?

**Comment by JCAMPOLPA** [comment]
Hi @azaslonov 

Great news - however it is not working as we may have done something wrong 

We have set up CookieBot on Google Tag Manage, as described in
https://support.cookiebot.com/hc/en-us/articles/360003793854

Then we attempted to insert the following script (with our cookiebot GUID key) in Text widget and using the "code" option 
![image](https://user-images.githubusercontent.com/26059633/83005052-a7998b00-a010-11ea-82c9-ecce7b02e98d.png)


<script id="CookieDeclaration" src="https://consent.cookiebot.com/xxxxxx/cd.js" type="text/javascript"></script>

But at the end, the script is not interpreted and still displayed as a text, but in red
![image](https://user-images.githubusercontent.com/26059633/83004848-6e611b00-a010-11ea-8a4c-583b7b12ef7c.png)

Do you have any guidance on how the script tag should be setup so cookiebot throuhg Tag manager can work ? Having the GDPR cookie management working is a must-have in Europe :-(

**Comment by azaslonov** [comment]
Can you please send the name of your service here: apimportalfeedback@microsoft.com? I'll check your setup.

**Comment by rsch136** [comment]
Hi, is this still the only workaround for making the managed portal GDPR compliant? Or is there a better way to include the consent cookies now, almost 3 years later?
