### ISSUE TITLE
Google Tag Manager in Managed environment ?

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#642]
Hi @azaslonov 

Great news we can install Cookiebot with Google Tag manager. However,  I do not understand where I can install node.js package in a Managed environment.

For EU countries, shall we say Self-Hosted portal is the only realistic way to go with APIM  
 as there is no other way to use script and have a cookie manager in Managed portal ?

Thanks for you time

_Originally posted by @JCAMPOLPA in https://github.com/Azure/api-management-developer-portal/issues/641#issuecomment-634247633_

**Comment by azaslonov** [comment]
Oh, sorry, it is already pre-installed on the managed version, so you'll need just to update the configuration using REST API.

**Comment by azaslonov** [comment]
By the way, if you have a follow-up question, you can just either re-open the issue or just post your comment, we will read it in anyways.
