### ISSUE TITLE
How do we create a sitemap file in a managed portal?

### ISSUE THREAD

**Issue by poshgrad** [Azure/api-management-developer-portal#644]
Hi there, 

I am trying to get my portal referenced on Google and it can only happen:
a- if I give them a sitemap 
b- if I am so referenced by other sites that google crawlers find me

I have one API in pre-release and it is about ankle straps and breast cancer recovery bras so you can imagine how much I can expect from natural referencing. Although I will be available soon on Programmable web, I figure out I better go with the second option. 
Problem is I am using the managed version of the APIM dev portal and even though I have created a page and generated an HTML sitemap, I can't have it published whatever I try. 
So i wonder how can i have my sitemap HTML file added to the files of the managed website? 

Thanks for your help.

Julien

**Comment by azaslonov** [comment]
Hi Julien, the sitemap gets generated automatically for all pages, you can see it by adding /sitemap.xml to your hostname. You can submit it in Google Search Console.

**Comment by poshgrad** [comment]
Hi Alexander,

Thank you and sorry for the disturbance.

BR
Julien

**Comment by poshgrad** [comment]
Hi Alexander,

Actually I need your help again. 
My primary goal is to get referenced in Google to stop being unknown and to get people use my APis. 
To do so it seems that I need to send my sitemap to Google as described in here : https://youtu.be/pZ24HuiolDs
But to do so I need to register to the Google search console which can only be done by adding a verification token in the <Head> in the HTML of my APIM dev portal himpage which I can't update since it is managed portal. 
I cannot find any documentation about that.
Can you help with that please ?

BR

Julien

**Comment by azaslonov** [comment]
Hi @poshgrad, actually you need just a TXT record in your domain name provider:

![image](https://user-images.githubusercontent.com/2320302/84084958-60f54a80-a999-11ea-9e6b-09fac4c2fd09.png)

**Comment by poshgrad** [comment]
Thanks :)
