### ISSUE TITLE
Portal showing all api revisions

### ISSUE THREAD

**Issue by hagagps** [Azure/api-management-developer-portal#645]
The azure api management developer portal is now showing all api revisions instead of a single link for the base/current revision, even with the revisions offline. If this is intended behavior then can you provide a setting to allow turning this off.

## Reproduction steps
1. Publish multiple revisions of an API to API Management
2. Go to Developer Portal
3. Sign In
4. Click on 'Explore APIs'
5. See APIs repeated
6. Hover over API links to see that they point to different revisions

## Expected behavior

Only the base/current revision should be shown.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Comment by azaslonov** [comment]
Hi @hagagps, no it is not expected. Thanks for bringing this up, we'll fix it.

**Comment by erwinkramer** [comment]
Hi, i can confirm the same issue on a self-hosted site. On another self-hosted site pointing to another API management instance, i don't experience the issue, so it looks like a Management API issue.

**Comment by erwinkramer** [comment]
Seems like this issue has expanded to 2 API management instances we are running (premium and dev),  any timeline for the fix @azaslonov ? It's pretty annoying since we make a new revision for every change we make (so we have a lot of them).

**Comment by mikebudzynski** [comment]
@erwinkramer Thanks for bringing this up. To clarify - do the revision appear in the API list or in the changelog?

**Comment by hagagps** [comment]
The revisions appear on the API List and API Details (Api version drop down).

**Comment by mikebudzynski** [comment]
Thanks, we marked this issue as top priority and we'll look into it in the next few business days.

**Comment by erwinkramer** [comment]
> @erwinkramer Thanks for bringing this up. To clarify - do the revision appear in the API list or in the changelog?

Directly in the API list

**Comment by kyajiv** [comment]
@azaslonov  @mikebudzynski We published portal yesterday and it seems issue still exist. We still see all api revisions

**Comment by mkowalskigps** [comment]
There is a query param `expandApiVersionSet` that is being set to `true` by default - changing this to `false` seems to return the correct payload.

**Comment by mikebudzynski** [comment]
@kyajiv Is your portal managed or self-hosted? We're still rolling out the update to the managed portals (please, check again in a few days). The self-hosted portal version 2.4.1 contains the fix.

**Comment by kyajiv** [comment]
We have managed portal. We will wait for few days to get this update. :)

**Comment by mkowalskigps** [comment]
This still appears to be an issue - @mikebudzynski can you confirm if the update has been fully rolled out?

**Comment by mikebudzynski** [comment]
The rollout hasn't finished yet. Please, check back around Tuesday / Wednesday and republish your portal.
