### ISSUE TITLE
Primary subscription key is not added to the header.

### ISSUE THREAD

**Issue by dvXcode** [Azure/api-management-developer-portal#652]
## Bug description

Primary subscription key is not added to the header.

## Reproduction steps

1.	Go to Developer Portal
2.	Sign in
3.	Press on APIs menu
4.	Select API
5.	Select Operation
6.	Press Try it
7.	Primary key showed as selected, but not added to the header. 

![PrimarySubscriptionKey](https://user-images.githubusercontent.com/51912361/83138715-82c61600-a0eb-11ea-956e-01aaff6d3103.png)

## Expected behavior

Key should be added to the header

## Is your portal managed or self-hosted?

Managed

**Comment by Harjindar** [comment]
I've the same issue

**Comment by Harjindar** [comment]
It looks like that by default the event is not triggered which populates the header. You have to change the value (for e.g. choose Secondary key), which the triggers the event.

I must say, it is quite annoying. The whole point is to have all the information at one place and now we get feedback from user that the try it functionality is not working..

**Comment by azaslonov** [comment]
Hi @Harjindar, this issue has been fixed. It should reach the managed version by the end of this week.

**Comment by azaslonov** [comment]
The issue has been fixed. Please re-publish the portal to pick up changes.
