### ISSUE TITLE
Quality of developer portal is deteriorating

### ISSUE THREAD

**Issue by Harjindar** [Azure/api-management-developer-portal#654]
I've a general feedback to give.

The new developer portal should be an improvement compared to the previous developer portal (which is now deprecated). But unfortunately the functionality keeps breaking since last couple of months. Few examples of this breaking functionalities are as follows:
- Example request is not populated in the Try It text box (this worked couple of months ago)
- Copy button not working
- Lately subscription key is no longer populated by default (leading to authorization error due to missing key)
- After around 10 mins, the portal redirects to signin page and the page starts refreshing continuously. One has to open a new browser tab to log in. (Chrome and Edge)

For some, the issues are already reported, and for some it isn't.

Just to be clear, the purpose of mentioning this, is not to nag but to inform the development team that the Api Management Service is a gem. But lately the standard of the quality of developer portal  is not up to the mark. That's a pity as this the front and customer facing part of the whole Api solution. This first experience of the our end-user (developer of our customer) should be seamless and the above mentioned issues do not provide a professional expression.

So I'd request you to do something with the feedback raising the level of quality and with it, the customer experience and thus raising the level of custom satisfaction :)

**Comment by azaslonov** [comment]
Hi @Harjindar, thank you for the feedback. These and many other issues have been already addressed, we were not able to ship them to the managed services earlier due to Azure-wide deployment lockdowns. Now the release is in progress, so you should see the updates soon. Thank you for patience.
