### ISSUE TITLE
Ability to choose which page should be showed after signin-sso page

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#655]
Env: Managed portal

Hi,
After calling https://xxx.management.azure-api.net/users/yyy/token? to get SSO token, how can we land on another page than the Home page ?

Could it be possible to set the relative URL path to be redirected as an url parameter in the signin-sso page (as we add new static pages) ?
Like: 
https://xxx.developer.azure-api.net/signin-sso?token=xxxxxxxxxxxxxxxx**&path=/Profile**"

Thanks for support

**Comment by JCAMPOLPA** [comment]
Hello,

Any possibility to redirect directly to a given page when using /signin-sso url ?

**Comment by azaslonov** [comment]
I believe the "returnUrl" parameter should help you. Example: "?returnUrl=/apis".

**Comment by JCAMPOLPA** [comment]
Hello

Unfortunately, we get back to Home page, but we are  no more authentifcated with user AzB2C identity - so I guess it only works for signin page but not signin-SSO page

https://xxxx.developer.azure-api.net/signin-sso?token=2........ttgtze==&returnUrl=/reference#api=myapi

Our goal is to redirect (SSO) from a website, where we are already AzB2C authenticated, to API portal with an already provisionned user (which has the same AzB2C identity) AND land on specific API pages (not the Home one)

Can we make it possible ?

**Comment by ygrik** [comment]
@JCAMPOLPA Thank you for details.
The browser does not pass the part after a hash (#api=myapi) to the server

If you pass **returnUrl=/apis** it should work

**Comment by JCAMPOLPA** [comment]
Hi @ygrik 

This is good news, however our scenario implies landing to a specific API page (1 API == 1 Insurance Product): this is a must-have to land to **/returnUrl=/apis#my api**

Is it fixeable ?

**Comment by azaslonov** [comment]
Actually, it does work if you encode your return URL like this:
https://alzaslondemo.developer.azure-api.net/signin?returnUrl=%2Fapi-details%23api%3Dbook-store-api%26operation%3Dget-all-books

**Comment by JCAMPOLPA** [comment]
Hi @azaslonov 

May be, but not for signin-sso page, which is the object of that issue

I am struggling with /signing-sso?token=xxxx&returnUrl=%2reference%23api=yyyy
Even /signing-sso?token=xxxx&returnUrl=%2apis-list is not working as I am redirected to home page and it breaks authentication: user is not logged on

I am opening another issue to re-open it
