### ISSUE TITLE
Version dropdown is loaded by blank items for every Revision that is added to the API

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#656]
## Bug description
Note: this might be related to #645 

The dropdown for Versions is showing empty elements. One for each Revision added to the API

## Reproduction steps

1. Go to the API editing in APIM
2. Select an the Echo Api
3. Select the "Revisions" tab
4. Click "Add revision"
5. Enter a Description and click Create
6. Navigate to API page to Test the App
7. You will see this for the dropdown next to the API Version:
8. Even if you take the Revision Offline, you will still see empty items in the Dropdown

![image](https://user-images.githubusercontent.com/65634611/83203201-c1fd6280-a0fd-11ea-9d88-34cd7a9d02e4.png)

If you add a "Version Identifier" on the Settings tab, you will see this. 

![image](https://user-images.githubusercontent.com/65634611/83203890-51574580-a0ff-11ea-84fc-83b0639d40a8.png)

## Expected behavior

This dropdown wasn't in the legacy portal, so I'm not sure what should be displayed here other than the revision number?

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Edge Chromium
 - Version:  83.0.478.37

**Comment by azaslonov** [comment]
Hi @VWACBrick, indeed, thanks for reporting the issue.
