### ISSUE TITLE
Questions: How to know which portail build is running in Managed mode ?

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#657]
Hello

Is there a way, for an Managed instance
1) to know which build is running
2) to know which builds are available (so we can understand what will be really fixed in the next deploy)
3) to be notified through Azure Portal when roll-out of the update is done for our own Managed instances ?

Thanks a lot

**Comment by azaslonov** [comment]
Hi @JCAMPOLPA,

For #1, you can check the service status endpoint:
https://yourservicename.developer.azure-api.net/internal-status-0123456789abcdef

Starting version **0.13.991.0**, it will return the following response:
```
{
    "PortalVersion":"202006012015", // version of the published portal (updates when you publish portal)
    "CodeVersion":"20200601062056", // version of the code base (updates with each release of developer portal)
    "Version":"0.13.1000.0", // version of the service (updates with each release of the service/backend)
...
} 
```

For question 2, we don't have it exposed anywhere, and AFAIK not planning to.

For question 3, we plan to implement this notification.
