### ISSUE TITLE
No subscriptions are shown in Products or Profile Page

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#658]
Environment: Managed

For an existing user with already subscribed Products, nothing is shown in Profile page.

Also, in Subscription page, none of the 200 existing Products of our APIM instances are shown.

**Comment by azaslonov** [comment]
All services upgraded. Please re-publish the portal to pickup changes.

**Comment by JCAMPOLPA** [comment]
Hi @azaslonov 

Indeed, Profile page is repaired, but not the Product page - which shows no Products neither subscriptions
![image](https://user-images.githubusercontent.com/26059633/83493273-d1d9c580-a4b4-11ea-90df-da6d018e097b.png)

I have never seen any content in this page, whether logged or not - thanks for your help
