### ISSUE TITLE
API level and All APIs subscription in the dev portal

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#659]
Hi,
According to the documentation of APIM, subscriptions are now possible at different scopes: Product, API, and All APIs.
But, except if I'm missing something in the portal, it sounds like the only subscription available in the Dev Portal is at the product scope.
Is it a feature that is currently not available?

**Comment by azaslonov** [comment]
Hi @dgrospelier, sorry, I do not fully understand the question. You can subscribe only to a product, there are no other levels of subscriptions. Can you please post a link to the docs you're referring to?

**Comment by dgrospelier** [comment]
Here are the details of the different subscription levels available in APIM: https://docs.microsoft.com/en-us/azure/api-management/api-management-subscriptions#subscriptions-for-all-apis-or-an-individual-api

**Comment by mikebudzynski** [comment]
@dgrospelier We don't expose direct subscriptions to APIs in the developer portal on purpose. You can create direct subscription through the Azure portal as an administrator.
