### ISSUE TITLE
Unable to Sign out

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#662]
Hi,
Just recently published the website to get any new updates, However we are now unable to Sign out from the portal or Sign in when using OAuth. 

![image](https://user-images.githubusercontent.com/62035456/83374342-7ad5e100-a41f-11ea-91a6-6c783f06daad.png)

Were there any updates made to the OAuth authentication recently that could be causing this issue?
Thanks

**Comment by azaslonov** [comment]
Can you tell service name or at least region?

**Comment by GuillaumeRP** [comment]
Same problem here. It seems that there is something wrong with Token call in website : it returns an HTML response 200 but inside the response, a 404 code is returned.

**Comment by azaslonov** [comment]
Understood, we're investigating.

**Comment by azaslonov** [comment]
Found the issue, we're preparing a hotfix.

**Comment by watson20201** [comment]
This is occurring in the Australia East region

**Comment by azaslonov** [comment]
Issue has been fixed. Please re-publish the portal to pick it up.

**Comment by GuillaumeRP** [comment]
Thank you 👍

Télécharger Outlook pour Android<https://aka.ms/ghei36>
