### ISSUE TITLE
"Make revision current" will add an empty Change Log when no change log details are supplied.

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#663]
## Bug description

When there are multiple revisions of an API, there is an option to "Make Current". This action will bring up a dialog to add a Change Log entry if you choose, if you don't chose to add an entry and click Save, there will still be an entry added to the Change Log

## Reproduction steps

1. Go to APIs->APIs in the API management portal
2. Select an API from the list, and select '**...**' option and select "Add Revision"
3. When the revision list comes up, select one of the Revisions that is not "Current"
4. Select the '**...**' context option on the not current revision, and select "Make current" option
5. When the dialog comes up, do not select "Post to Public Change log for this API"
6. Click "Save"
7. Open the Change Log tab
8. There will be a blank entry added to the list. 

![image](https://user-images.githubusercontent.com/65634611/83453365-393d3a00-a40f-11ea-9ad4-be4106399a36.png)

## Expected behavior

The text in the dialog _"If you wish, you can post notes about this change to the Change log using the field below:"_ leads you to believe if you want an entry, you select the checkbox and enter text to get a new entry. However, if you don't select the checkbox, there shouldn't be anything added to the change log. 

![image](https://user-images.githubusercontent.com/65634611/83453286-10b54000-a40f-11ea-98f8-f8e7b831f854.png)

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10 
 - Browser: Edge Chromium
 - Version: 83.0

## Additional context

The work around is to open the Change Log tab, and delete the extra entry that was created.

**Comment by mikebudzynski** [comment]
Thanks for bringing this up, we'll address the bug.

**Comment by mikebudzynski** [comment]
@VWACBrick This is a bug in the Azure portal, we'll track it internally.
