### ISSUE TITLE
User Notes entered through Azure Portal are passed to the page but not rendered

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#665]
## Bug description

User user in the API Management portal has the option to enter a "Note". The field does appear to render anything on the Profile page, but it's being passed down through the JSON response to get the user Identity. 

## Reproduction steps

1. Go to Developer Portal -> Users
2. Select a User from the list
3. Click on the "Edit note"
4. Enter some text in the Note field and save. 

![image](https://user-images.githubusercontent.com/65634611/83460545-82938680-a41b-11ea-882f-e39bce53f31d.png)

5. Log into the website and go to the user's Profile page. 
6. Open the Network tracing in the browser debugging tools (F12)
7. Refresh the Profile Page
8. Select the xhr request that pulls down the profile information
9. Review the JSON object returned

![image](https://user-images.githubusercontent.com/65634611/83460235-c46ffd00-a41a-11ea-82be-c0cb3684dd39.png)

## Expected behavior

What is the intent of this field? Is it for the Admins to store Notes about the user in the Azure Portal, or will this be notes the user can edit themselves on the Profile page some day? 

If they for the Admin's reference only, they **should not** be passed back to the client. 

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Edge Chromium 
 - Version: 83.0

**Comment by azaslonov** [comment]
Hi @VWACBrick, thank you for bringing this up. This is a known issue that will be solved with one of the backend updates (no ETA at the moment). This is issue is also similar to #324.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
