### ISSUE TITLE
In page styles have 'undefined' values.

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#667]
## Bug description

Was trying to make sense of the site styles, and when I did a view source, I noticed some of the in page styles have 'undefined' values. 

## Reproduction steps

1. Open any page on the API website
2. Do a view source

Listed here are a few examples, but there are multiple instances of this in most pages

.vymywkazci {
--
   flex: 1;
   width: 100%;
   display: grid;
   margin-top: 10px;
   margin-left: auto;
   grid-row-gap: **_undefined_**;
   margin-right: auto;
   margin-bottom: 10px;
   grid-column-gap: **_undefined_**;
   grid-template-rows: auto auto;
   grid-template-columns: 1fr;
   }

@media(min-width:768px) {
--
  .vymywkazci-md {
   flex: 1;
   width: 100%;
   display: grid;
   max-width: 720px;
   margin-top: 15px;
   grid-row-gap: **_undefined_**;
   margin-bottom: 15px;
   grid-column-gap: **_undefined_**;
   grid-template-rows: auto;
   grid-template-columns: 1fr 3fr;
   }
   }

## Expected behavior

Avoid 'undefined' for a style value. 

[https://www.w3schools.com/CSSref/pr_grid-row-gap.asp](https://www.w3schools.com/CSSref/pr_grid-row-gap.asp)

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Edge Chromium 
 - Version: 83.0

**Comment by azaslonov** [comment]
Thanks for bringing this up. Despite it doesn't affect actual styles, we'll definitely fix this.

**Comment by azaslonov** [comment]
@VWACBrick, looks like I can repro this. When did you publish the portal last time? Also, do you mind sending us your portal URL to apimportalfeedback@microsoft.com?

**Comment by VWACBrick** [comment]
The site was published about a week back and the view source showed this problem, but now after a republish I can see the source is completely different now. (compressed and stripped of comments). I checked the CSS resource files loaded in the page, and they don't have this issue either. 
You can close this ticket as "not repro" 
Thank yo

**Comment by azaslonov** [comment]
Thanks for the confirmation. I believe the codebase you published with last time was pretty old.
