### ISSUE TITLE
OneOf problems

### ISSUE THREAD

**Issue by abusse-interhyp** [Azure/api-management-developer-portal#669]
## Bug description

I know there was a fix regarding oneOf in the last release. I still have some problems with it or at least some questions.

## Reproduction steps
See attached yaml files
[api.zip](https://github.com/Azure/api-management-developer-portal/files/4715431/api.zip)
in the oneOf.yml Cat and Dog are explicitly linked via an oneOf option.
In the baseClass.yml both are indirectly linked based on the super type Pet in the patch Request. 

## Expected behavior
The Objects Cat and Dog should be visible in the Developer portal at least for the oneOf.yml.
Based on other tools we are currently using, it would be perfect if they are also visible for the baseClass.yml.
There are some other tools on the market, some of them meet this criteria, some others not.
Is it possible for the API Management?

## Is your portal managed or self-hosted?

Managed (and currently republished)

## API Management service name

Region: West Europe

**Comment by azaslonov** [comment]
Hi @abusse-interhyp, sorry for the delay, we're looking into that.

**Comment by albusse** [comment]
@azaslonov thabk you 
Our actually planed API is based on the baseClass.yml with other data and more nested. 
It‘s still in private preview but if you need more examples please let me know.

**Comment by abusse-interhyp** [comment]
Any updates on the timeline for this issue?
Our current APIs are using the polymorphism on the first levels, therefore many DTOs are not shown in the Developer Portal atm.

The baseClass.yml approach I mentioned above is now working with the other tools we are using (generators and internal swagger ui) so this would be the preferred behaviour.

Thank you.

**Comment by abusse-interhyp** [comment]
@mikebudzynski @azaslonov 
Hi Guys, 
any update on this?

Actually it is a showstopper for us at the moment and brings up too many questions from our clients, because so many DTOs are not shown in the Api description page.

Just to clarify, will it be possible to have some functionality similar to the following screenshots?

![image](https://user-images.githubusercontent.com/64847387/105141308-3eafd780-5af9-11eb-90c0-0838ea4a488e.png)
![image](https://user-images.githubusercontent.com/64847387/105141364-52f3d480-5af9-11eb-9c66-e5aaa291a8b3.png)
![image](https://user-images.githubusercontent.com/64847387/105141438-6ef77600-5af9-11eb-9137-c3113407bade.png)

based on a yaml file like this:
https://raw.githubusercontent.com/Interhyp/Top-Rate-API/master/top-rate.yaml

Thank you for an answer.

**Comment by abusse-interhyp** [comment]
@azaslonov 
Hello guys,
Any chance for an update on this one? Based on a current evaluation it would be nice to know if the described handling will be somehow possible.
