### ISSUE TITLE
Improvement: Indicate Last Published time and/or add entry into Activity Log

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#671]
I would be nice to track when the last time the site was Published in one of these two places or both

- Add an entry to the Activity Log so we can have a historic record when it was last Published
- Add Date Time stamp on the "Portal Overview" tab

Maybe add "Last Published on: 06/02/2010 10:00:00 GMT" in this area?

![image](https://user-images.githubusercontent.com/65634611/83549187-c5a43700-a4b9-11ea-9a6b-02040017d135.png)

Thank you

**Comment by azaslonov** [comment]
Yep, this is a planned feature.
