### ISSUE TITLE
Improvement: Add the Terms of Service to the Complete Sign Up Page (AAD)

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#674]
This is similar to request to have the TOU added to the Basic Auth sign up page. 
#228 

**Azure Settings**
![image](https://user-images.githubusercontent.com/65634611/83577632-93aac900-a4e9-11ea-8504-b9a3beebcb76.png)

Currently our site is only using the AAD today but later will use B2C Authentication, can we have the same TOU feature surface on the Sign in Page and the "Complete Sign Up" page?

New Site Complete Sign Up page
![image](https://user-images.githubusercontent.com/65634611/83577601-783fbe00-a4e9-11ea-9393-f3a28986ed1f.png)

Legacy Portal during AAD only sign in
![image](https://user-images.githubusercontent.com/65634611/83577712-cbb20c00-a4e9-11ea-8d9b-472c6150560a.png)

New Site sign in page with AAD only (B2C coming soon)
![image](https://user-images.githubusercontent.com/65634611/83577761-e8e6da80-a4e9-11ea-886d-17723ffb2acb.png)

Thank you

**Comment by azaslonov** [comment]
Hi @VWACBrick, makes sense, thanks for the suggestion.

**Comment by khigashi1021** [comment]
Hi I have the customer who would like to have this improvement applied. Are there any plan to improve this?

**Comment by mikebudzynski** [comment]
We do not have ETA at the moment, but I have prioritized the issue.
