### ISSUE TITLE
Google Tag Manager not working using the REST API

### ISSUE THREAD

**Issue by cirellamhcs** [Azure/api-management-developer-portal#675]
## Bug description

Using the Azure configuration and updating it with the REST API adds the Google Tag Manager Javascript with an undefined containerId.

## Reproduction steps

1. Do the steps from your [Wiki](https://github.com/Azure/api-management-developer-portal/wiki/Integrate-Google-Tag-Manager)
2. Javascript will be added, but with an undefined containerId

## Expected behavior

Add the Javascript with the correct containerId

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release 2.3.0

## Additional context

In my opinion, this happens because object attributes are renamed from Id -> Key in the [mapiObjectStorage.ts](https://github.com/Azure/api-management-developer-portal/blob/master/src/persistence/mapiObjectStorage.ts#L490). The [Paperbits Google Tag Manager](https://github.com/paperbits/paperbits-gtm/blob/master/src/publishing/gtmHtmlPagePublisherPlugin.ts#L16) expects either a ``containerId`` or ``webContainerId`` but since these attributes are renamed to ``containerKey`` / ``webContainerKey`` it cannot find them.

**Comment by azaslonov** [comment]
Hi @cirellamhcs. Indeed! Thanks for bringing this up. It will be fixed in upcoming release.
