### ISSUE TITLE
Developer portal doesn't populate samples request body

### ISSUE THREAD

**Issue by pavel-chubau** [Azure/api-management-developer-portal#677]
Frontend config
![image](https://user-images.githubusercontent.com/66160334/83666840-3cceed80-a5d6-11ea-8bd2-a848993c543c.png)

Old developer portal populates the sample after clicking [Try It]
![image](https://user-images.githubusercontent.com/66160334/83667211-b8c93580-a5d6-11ea-9c67-b73001f20d0c.png)

But the new portal doesn't. The body is empty
![image](https://user-images.githubusercontent.com/66160334/83667257-c8e11500-a5d6-11ea-91f1-da242f961eb7.png)

**Comment by azaslonov** [comment]
Closing as duplicate of #410.
