### ISSUE TITLE
Delegated sign out issues

### ISSUE THREAD

**Issue by adamstruck** [Azure/api-management-developer-portal#683]
I am having issues with delegated sign out.  I'd like to redirect the signout request to Auth0. This flow works fine on the legacy portal. 

Any guidance on how to handle the preflighted CORS request?

**Comment by azaslonov** [comment]
Hi Adam, can you please tell in more detail at what point you're facing the CORS issue? How the flow looks like?

**Comment by adamstruck** [comment]
Here is an overview of the requests I see in dev console upon clicking "sign out":

```
APIM      |      my server     |     auth0
    ----[OPTION]---->
    <---[200]--------
    ----[GET]------->
    <---[302]--------
    -----------[OPTION]-------------->
    <----------[200]------------------
[XHR FAILURE]
```

**Comment by ygrik** [comment]
Thank you for the details. We will fix it.

**Comment by adamstruck** [comment]
Any progress on this? 

Alternatively, if you can provide some documentation around the expected signout flow, maybe I can fix things on my end.

**Comment by mikebudzynski** [comment]
@adamstruck We'll soon implement a fix, the ETA is 2-4 weeks.

**Comment by adamstruck** [comment]
I wanted to add that this is also an issue when delegating sign out requests to Azure AD B2C.  The `https://<tenant-name>.b2clogin.com/<tenant-name>.onmicrosoft.com/<policy-name>/oauth2/v2.0/logout` endpoint responds the OPTIONS request with 404

**Comment by mikebudzynski** [comment]
The fix is included in the release we're rolling out now. ETA for full deployment is ~2 weeks.
