### ISSUE TITLE
Issue subscribing to a product

### ISSUE THREAD

**Issue by efonsecab** [Azure/api-management-developer-portal#685]
I'm using the out of the box developer portal, not the self-host version.
Starting today, the system started blocking users from subscribing.
The javascript console is hsowing this:

product#product=betas2:1 Refused to execute script from 'https://apidevelopers.pticostarica.com/scripts/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by azaslonov** [comment]
Hi @efonsecab, the vendor.js - is just a broken reference, it doesn't have any effect.

Regarding the unable to subscribe issue, can you tell what exactly happens, any errors? It would be great if you could send your Network traces (from browser) to apimportalfeedback@microsoft.com.

**Comment by azaslonov** [comment]
@efonsecab, did you have chance to send us that email?

**Comment by efonsecab** [comment]
Hi, I already solved the issue.
This is what happened:
Even if I had already deactivated delegation and the portal showed it as
deactivated, the developer portal requests were still invoking the
delegation,
I fixed by just reactivating and then deactivating delegation once again.
Eduardo Fonseca
MCP
Phone: (506) 87 05 44 94
