### ISSUE TITLE
Window.open for /signin-sso?token opens a blank pop-up

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#686]
Environment: Managed

Repro:
Using a window.open javasscript code for a valid https://xxx.developer.azure-api.net/signin-sso?token=yyyyyyyyyyyyyy url opens a blank pop-up, even if the SSO is OK and user is correctly loggued.

"window.open(urlWithToken)
< a href="urlWithtoken" target="_blank">link</ a>"

![image](https://user-images.githubusercontent.com/26059633/84005397-5de46500-a96d-11ea-9bc3-791c28546286.png)

**Comment by azaslonov** [comment]
I have replied to your email, we'll need more information to help you.

**Comment by JCAMPOLPA** [comment]
Hello

This is linked to https://github.com/Azure/api-management-developer-portal/issues/705, as we have this behavior only in the APIM portal instance where there is the Signin azB2C phantom widget

**Comment by JCAMPOLPA** [comment]
Hello,
My previous assumption is false - we got the issue on 2 APIM instances, independently from the Home phantom widget issue :-(
I am opening another issue

**Comment by azaslonov** [comment]
Hi Jerome, we're rolling out a hotfix that should address this one as well.

**Comment by JCAMPOLPA** [comment]
Hello
What will be the correct buildversion so to have the fix ? 

Mine is 
CodeVersion: "20200812080849",
Version: "0.13.1048.0"

Thanks
