### ISSUE TITLE
Link to update post broken

### ISSUE THREAD

**Issue by JasonBSteele** [Azure/api-management-developer-portal#69]
**Describe the bug**
The README's link to the update post (https://docs.microsoft.com/en-gb/azure/api-management/api-management-howto-developer-portal) is broken

**To Reproduce**
Click it

**Expected behavior**
Update post shown

**Desktop (please complete the following information):**
 - OS: Win 10
 - Chrome

**Comment by azaslonov** [comment]
Hi Jason, thank you for heads up.

**Comment by mikebudzynski** [comment]
@JasonBSteele - thanks for raising the problem. The pull request has been prematurely merged and the update is not out yet - we will update the link next week.
