### ISSUE TITLE
Response headers are not shown in developer portal UI

### ISSUE THREAD

**Issue by ericmbowden** [Azure/api-management-developer-portal#693]
We're finding that response headers which are included as part of our Open API spec, imported into APIM, do not appear in the developer portal.

Below is an example response header definition.

"responses": {
          "200": {
            "description": "Returns all things",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/allthings"
              }
            },
            "headers": {
              "accept-language": {
                "description": "Specifies the two digit language codes available for your subscription.",
                "type": "string"
              }
            }
          }

I'm finding that a swagger ui, provided by swashbuckle, does include the response headers.  Could I be missing a configuration or is rendering response header documentation in the Azure APIM developer portal not supported, as of now?

The screen snap below shows how this appears in the swagger UI.

![image](https://user-images.githubusercontent.com/7331151/84181427-e4c13c80-aa56-11ea-90be-ca54123f7320.png)

Thank you

**Comment by azaslonov** [comment]
Hi @ericmbowden, yep, makes sense, we'll add this to the console and docs.

**Comment by Radamonas** [comment]
Are there any updates when this issue could be fixed?

**Comment by mikebudzynski** [comment]
@Radamonas We're planning to work on it in the coming few weeks.

**Comment by ErikMogensen** [comment]
It looks like this is fixed.
