### ISSUE TITLE
No examples in body of Try It section

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#696]
Env: Managed
CodeVersion: "20200609100803",
Version: "0.13.1000.0"

Hi

Many have been corrected since last month, bu we still not have any sample body based on default value in API swager for testing API: can it be corrected please ?

![image](https://user-images.githubusercontent.com/26059633/84269475-8c0ea400-ab29-11ea-89f4-9aeda3a5f522.png)

![image](https://user-images.githubusercontent.com/26059633/84269555-a6488200-ab29-11ea-82d2-534b8b861949.png)

Thanks al ote

**Comment by azaslonov** [comment]
Hi Jérôme, request examples are actually being rendered, but they need to filled first. We have implemented a feature in Management API that would generate a payload sample (if none defined) from example fields, but it comes on the ongoing release of the service. Meanwhile, you can solve this by using Azure portal:

![image](https://user-images.githubusercontent.com/2320302/84332350-963c9c80-ab41-11ea-8d3d-9b7396287b34.png)

**Comment by azaslonov** [comment]
Closing for now, as the issue has been addressed already.

**Comment by JCAMPOLPA** [comment]
Hi Alexander

Great news, however there is little change from previous portal as for the last 3 years we never had to generate examples, because the TryIt of the old portal get by itself the default values of the swagger parameters to build the body

Can we get back this functionality ? For one or two APIs we can do it manually, and we can even change our API pipeline generation but I assume it would have work like previously.

![image](https://user-images.githubusercontent.com/26059633/84357449-f6752200-abc5-11ea-9fec-1e7f9f2243fe.png)

**Comment by JCAMPOLPA** [comment]
Even if I use the Copy button on Example, I cannot paste into Body of the TryIt
![image](https://user-images.githubusercontent.com/26059633/84391537-681a9380-abf9-11ea-88e1-7e027120f039.png)
