### ISSUE TITLE
Links to API or Product detail pages not working

### ISSUE THREAD

**Issue by lrtico** [Azure/api-management-developer-portal#701]
## Bug description

When clicking on a card in the List of APIs widget the page is not routed. The URL changes in the browser's URL bar but the UI doesn't update or change.

## Reproduction steps

1. Go to https://apimstaticweb.z5.web.core.windows.net/
2. Scroll down the page to the "Explore the available APIs..." section
3. Click on "Details Account Api"
4. See problem, the page doesn't route to the API

## Expected behavior

1. UI updates to display the API details page

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release 0.0.1

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version:  83.0.4103.97 (Official Build) (64-bit)

## Additional context

Nothing to add, please let me know if you need more context. ^__^

**Comment by azaslonov** [comment]
Hi @lrtico, this actually works, but you need to select target page in respective controls:

![image](https://user-images.githubusercontent.com/2320302/84709757-a70d5980-af17-11ea-9fe3-59676f78df3d.png)

We understand the confusion and work on making this process more explicit.

**Comment by lrtico** [comment]
Thank you, Alexander!
