### ISSUE TITLE
Question: How best to preserve existing history of API calls?

### ISSUE THREAD

**Issue by tfeissle** [Azure/api-management-developer-portal#702]
When a new APIM instance is created, the data about history of API calls/usage/etc. is wiped. Is this stored somewhere where we could access it and move it to the new instance?

**Comment by azaslonov** [comment]
Hi @tfeissle, there is Logs section in Azure portal, that I think should answer your question:

![image](https://user-images.githubusercontent.com/2320302/84708587-a673c380-af15-11ea-9c02-de7f3d955df5.png)
