### ISSUE TITLE
Signin-SSO: returnUrl not working

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#704]
Env: Managed

When using AzB2C authentication for users and generating token to build SSO urls with https://docs.microsoft.com/fr-fr/rest/api/apimanagement/2019-12-01/user/generatessourl

the following Url patern does not work: it breaks authentication (user not logged) and we are redirected to Home page
 **/signing-sso?token=xxxx&returnUrl=%2reference%23api=yyyy**

Even simple page **/signing-sso?token=xxxx&returnUrl=%2apis-list** is not working: we are redirected to Home page

**Comment by mikebudzynski** [comment]
@JCAMPOLPA The issue has already been fixed; the full roll out is expected by the end of the week.

**Comment by RudyWKM** [comment]
Env: Managed

I still encounter an issue with the SSO url: the user is now always correctly logged in, but the returnUrl works about 40% of the time, (we are redirected to the Home page the other times)

**Comment by azaslonov** [comment]
Hi @RudyWKM, please make sure you URL-encode returnUrl value. If doesn't help, please provide examples of working and not working cases.

**Comment by RudyWKM** [comment]
Thanks @azaslonov, the returnUrl is encoded. We have two environments, both versions are up to date.
when I call **/signin-sso?token=abcdef12345&returnUrl=%2freference%23api%3dAPI_NAME** on the env1, it always connects & go to the URL, but when I do so in env2, it connects alright, but goes to the home page about half of the time.

**Comment by azaslonov** [comment]
I see. Can you please check versions for both environments? You can do it like this: https://yourservice.developer.azure-api.net/internal-status-0123456789abcdef

**Comment by RudyWKM** [comment]
env1 is 0.15.1081.0
env2 is 0.14.1072.0 (but it does not prompt for an update. I updated it this morning)

more info: env1 is standard tier, env2 is premium tier

**Comment by azaslonov** [comment]
Sorry, I need `websiteVersion` and `codebaseVersion`.

**Comment by RudyWKM** [comment]
Oh my bad, here is the full reply at this URL for both environments (I don't see websiteVersion):
env1: {"Status":200,"PortalVersion":"202010291247","CodeVersion":"20201022233821","Version":"0.15.1081.0","RoleNumber":"Proxy.Host.WebRole_IN_3"}

env2: 
{"Status":200,"PortalVersion":"202010291248","CodeVersion":"20201022233821","Version":"0.14.1072.0","RoleNumber":"Proxy.Host.WebRole_IN_1"}

**Comment by RudyWKM** [comment]
Hi @azaslonov, do you have more information on this issue? Please let me know if I can be of any help! Thanks you so much
