### ISSUE TITLE
Home page: AzB2C sign-in phantom widget

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#705]
Env: Managed

On design, in Home page, we do not have AzureB2C Sign-in widget included.

![image](https://user-images.githubusercontent.com/26059633/84778659-96c2b080-afe3-11ea-9fa0-1279edcbc654.png)

But on navigation, once we are connected,  the widget is shown : how can we remove it as it breaks our presentation ?

![image](https://user-images.githubusercontent.com/26059633/84778591-80b4f000-afe3-11ea-9470-4c8339e86bb9.png)

**Comment by JCAMPOLPA** [comment]
Hi guys,

Any update ?

**Comment by JCAMPOLPA** [comment]
Hello,
We still have the issue: once connected, there is still the "phantom widget"

![image](https://user-images.githubusercontent.com/26059633/90619677-cecbb700-e211-11ea-9b26-57bc7f21f775.png)

There is no way to remove it in Design mode !!!
![image](https://user-images.githubusercontent.com/26059633/90619832-ffabec00-e211-11ea-911f-1517c840e0a7.png)

Can you please help on this ?

**Comment by azaslonov** [comment]
Hi Jerome, yes, we're looking into this.

**Comment by azaslonov** [comment]
Jerome, I'm closing it since you figured this out. Thanks!
