### ISSUE TITLE
Bug in "Change Name" button behavior in profile

### ISSUE THREAD

**Issue by adamstruck** [Azure/api-management-developer-portal#707]
Profile fields become "editable" for a split second before redirecting when delegation is enabled.

**Comment by azaslonov** [comment]
Hi @adamstruck, yep we'll fix this. Thank you.

**Comment by adamstruck** [comment]
There is a similar bug with  "Change Password" - sometimes I am redirected to the local change password page rather than the delegation server.

**Comment by mikebudzynski** [comment]
Fix will be rolled out within 2 weeks.
