### ISSUE TITLE
Create from OpenAPI not working if default: NaN is used

### ISSUE THREAD

**Issue by MrTomZed** [Azure/api-management-developer-portal#708]
**Problem:**
I can't create an API from an OpenAPI.json, if "not a number" is used as default value for a webservice parameter. I'm getting:

> The input OpenAPI file is not valid for the OpenAPI specification

Open API conform, yet not working .json: https://pastebin.com/u9aHv7XH

**Reproduce:**
- Create a new Web Application in .NET Core 3.1
- In the generated WeatherForecastController, add a value and set the default to NaN
```
       [HttpGet]
        public IEnumerable<WeatherForecast> Get(double uselessNumber = double.NaN)
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
```
- Generate the OpenAPI.json with Swashbuckle 5.4.1
- Add a server
```
    "servers": [
    {
      "url": "https://myWebservice.azurewebsites.net",
      "description": "Development server"
    }
  ],
```
The resulting json is OpenAP conform, but I can't create an API with it in Azure API Management:

![image](https://user-images.githubusercontent.com/50983852/84896479-537c4680-b0a4-11ea-9b25-c447b1a92689.png)

It is working as intended after I delete line 26 with the NaN.

**Expected:**
An API can be created even with the NaN default value.

The doc (https://docs.microsoft.com/en-us/azure/api-management/api-management-api-import-restrictions) says "inline schema definitions for API operations aren't supported". But the default value is not part of a type definition, it makes no sense to put it in the "schemas" section. It might be used in another place without the "NaN".

The benefit of adding "Default: NaN" can be questioned of course, but 
`"default": 1`
is working.

**Comment by mikebudzynski** [comment]
Thank you for reporting the issue. This repository is dedicated to the developer portal only, I suggest that you open an Azure support request instead.
