### ISSUE TITLE
OIDC authentication provider not usable from interactive developer console

### ISSUE THREAD

**Issue by joostjanhuls** [Azure/api-management-developer-portal#710]
## Bug description

We are using an OpenID Connect (OIDC) provider to authorize requests to our API's but OIDC providers do not seem to be shown in the 'Try it' sections of the API detail pages. The provider is displayed correctly in the legacy portal though.

OAuth2 providers on the other hand, are displayed correctly in the (new) developer portal.

I republished the portal several times, but this didn't help.

## Reproduction steps

1. Configure an OIDC provider for the developer portal and configure an API to use that particular OIDC provider.
2. Open the developer portal and navigate to the API, choose any operation and press 'Try it'.
3. In the "Authorization" section, the specified OIDC provider is not visible.

## Expected behavior

The configured OIDC provider should be visible and usable from the "Authorization" section of the API details (Try it) page.

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
Merging with #208
