### ISSUE TITLE
Recover from content/template errors...

### ISSUE THREAD

**Issue by itsenes** [Azure/api-management-developer-portal#711]
## Bug description
The designer fails to load a page. e.g. Home. 

## Reproduction steps
After editing the page, ading or removing elements or editing text - it happens - The designer stops loading the corresponding page. I cannot specify which components cause this problem, their are not custom widgets. With the generic error message Oups something went, retry later... the only solution afetr that is to RESET the content and start over... I do capture (using the script capture.bat) the site's content in data.js periodically (before i begin editing the templates) as a backup but i'm not sure how i can restore it. 

## Expected behavior
A clear and concise error message of what went wrong and a way to resolve the issue should appear.

## Is your portal managed or self-hosted?
Self-hosted

## Release tag or commit SHA (if using self-hosted version)
2.3.0

## API Management service name
chaniabank-sandbox-gw

## Additional context

The browser's console reports the follwing errors :

consoleLogger.ts:27 TypeError: Cannot read property 'targetKey' of undefined
    at InlineModelBinder.<anonymous> (inlineModelBinder.ts:32)
    at Generator.next (<anonymous>)
    at blockModelBinder.ts:81

Uncaught (in promise) TypeError: Cannot read property 'targetKey' of undefined
    at InlineModelBinder.<anonymous> (inlineModelBinder.ts:32)
    at Generator.next (<anonymous>)
    at blockModelBinder.ts:81
    at new Promise (<anonymous>)

**Comment by azaslonov** [comment]
Hi @itsenes, that should be fixed by now. Do you still see the issue?

**Comment by itsenes** [comment]
> Hi @itsenes, that should be fixed by now. Do you still see the issue?

Hi @azaslonov and thank you for your prompt response. It works on the managed version, but still when i run the self-hosted version it doesn't work. I get the same errors. Obviously i'm missing something here :(

![image](https://user-images.githubusercontent.com/6062628/85112916-17b9bc00-b21f-11ea-9846-d213ef2c77fb.png)

It might be a case of different versions of the engine - since i upgraded manually my local version to the latest release. How can i find out which part causes this error and how can i fix it ? It worked just fine a couple of days, the error appeared after editing the content which is really wierd. 

Thank you in advance,

**Comment by mikebudzynski** [comment]
The self-hosted release hasn't been created yet. Please, allow us a few business days, and then upgrade your self-hosted portal codebase to the latest release and republish your portal.

**Comment by itsenes** [comment]
Hi @mikebudzynski!

thank you for your response, do you have an ETA on the new release ?

BR,

**Comment by mikebudzynski** [comment]
We released the 2.4.0 version last week.

**Comment by itsenes** [comment]
@mikebudzynski hi!

i updated my code with the 2.4.0 and it works just fine, thank you!

BR,
