### ISSUE TITLE
Hidden APIs in Report view

### ISSUE THREAD

**Issue by abusse-interhyp** [Azure/api-management-developer-portal#712]
## Bug description

 I have an API "API1" with subscription required flag and it is assigned to the product "product1", also with subscription required and only visible by a custom group "Group1".

The user "User1" is not part of "Group1" and has no subscriptions.

If "User1" looks at his Reports the API "API1" and its operations are visible.

## Expected behavior

I would expect that because of the product visibility, the API "API1" is not visible to the user, because based on the product settings I really want to hide this API to the user.

It's working in the API list and Product list, but it seems to be missing in the reports view.

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
Thanks for the reporting the issue, we're actively investigating it.

**Comment by mikebudzynski** [comment]
The fix is being released with our new API Management service release. You should receive the update within two weeks, precise timeline depends on the region your API Management services are deployed in. You don't need to update or republish the developer portal.
