### ISSUE TITLE
New Portal can't access management endpoint

### ISSUE THREAD

**Issue by fab66m** [Azure/api-management-developer-portal#714]
My setup is running APIM in internal vnet mode with Application Gateway providing access from the internet. Custom domains are configured for gateway and portal. No issues with gateway and legacy portal.

Starting the new developer portal out of Azure GUI, chrome's inspection says it can't access the management endpoint. I figured that its port 443 is blocked (or disabled?) in internal vnet mode. The NSG (or no NSG at all) is allowing any/any access on 443.

What I am able though is to get external access to the management's endpoint on port 3443 via NSG rule. I also tried a custom domain for the management endpoint but I am not able to redirect customDomain:443 to managementEndpoint:3443
 
Thanks for any help in advance.

**Comment by mikebudzynski** [comment]
You need to allow Internet access to the management endpoint. I suggest that you open an Azure support request, they will be able to walk you through the setup. Documentation is published here: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-integrate-internal-vnet-appgateway
