### ISSUE TITLE
Multiple subscriptions can be created with the same name in developer portal

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#717]
1. Navigate to the Product page and try to create multiple subscriptions with the same name.
Expecting an error message when we use the existing subscription name.

Same subscription name is not allowed for more than one subscription in the Admin portal.

**Comment by azaslonov** [comment]
Hi @dhandapanitrimble, this is by design, user can always rename it in their Profile page.
