### ISSUE TITLE
Developer Portal Report view shows all APIs and Operations 

### ISSUE THREAD

**Issue by Praveen6867** [Azure/api-management-developer-portal#718]
Hi Team,

In our system, have 10+ Apis and each API connected to one product. 
APIS	       Products
API1  -->   P1
API2	 -->   P2
API3 -->	 P3
API4	-->   P4

Created a new user and assign one product **P1** ( and API  is API1). When the new user logged into the developer portal --> ReportView the user able to see all 10+ APIs with operations. 

**Expected behavior:** User should see only assign APIs that is **API1**.
**Current behavior:** User able to see all 10+ APIs with operations.

**Comment by azaslonov** [comment]
Hi @Praveen6867, yes this is a regression in management API, hotfix is being released.

**Comment by mikebudzynski** [comment]
Merging with #712
