### ISSUE TITLE
Designer Portal reloading endlessly

### ISSUE THREAD

**Issue by cirellamhcs** [Azure/api-management-developer-portal#719]
## Bug description

After building the designer portal and hosting it, it will reload endlessly.

## Reproduction steps

1. RUN `npm install`
2. RUN `npm run build-designer`
3. Host dist/designer folder somewhere ( i.e. iisexpress: `iisexpress /path:PATHTODESIGNERFOLDER /port:8081`
4. GoTo localhost:8081

=> page is reloading endlessly

## Expected behavior

I expect it to not reload all the time.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

most recent master

**Comment by azaslonov** [comment]
Hi @cirellamhcs, are there any errors in the console? Do you have your config.design.json filled out correctly?

**Comment by cirellamhcs** [comment]
Hi @azaslonov , I don't see any errors in the console. I am using the config.design.json which works with the latest released version 2.3.0 . I am using the most recent master and didn't modify anything except the config.design.json to have the correct settings. When I run it with `npm start` everything works as expected, it's just related to the static designer webpage.

**Comment by azaslonov** [comment]
Can you try to clear browser cache or open in incognito mode?

**Comment by cirellamhcs** [comment]
sure, did do that. Even changed the port, nothing changed. Still reloading endlessly. Can you not reproduce it on your side?

**Comment by azaslonov** [comment]
No, I can't reproduce this. Can you please capture your Network logs into HAR send it to apimportalfeedback@microsoft.com?

**Comment by cirellamhcs** [comment]
sent you the mail with the HAR file.

**Comment by ErikMogensen** [comment]
@cirellamhcs , we had the same experience. It turned out to be due to an Application Gateway with WAF. After we had disabled six rules it started working. Even if you don't use a WAF it may be something else blocking the access to the APIM management endpoint.

**Comment by cirellamhcs** [comment]
Thx @ErikMogensen , you pointed me into the right direction. The `config.json` produced by `npm run build-designer` is the `config.runtime.json` not the `config.design.json`. I fixed it by adding `{ from: "./src/config.design.json", to: "config.json" }` to the `CopyWebpackPlugin` in the `webpack.designer.js`. But somehow it is strange, why am I the only one having that problem.

**Comment by azaslonov** [comment]
Thanks @cirellamhcs, yes that's the right workaround.

It, of course, should not behave like this, something got broken along the way, so we'll fix this. Also, just in case, this workaround cannot be used for production because you expose the token. Depending on the specific production setup, it can be handled differently. We'll provide some recipes soon.
