### ISSUE TITLE
paperbit runtime error on Local development

### ISSUE THREAD

**Issue by AvanadeAPIClinicTeam** [Azure/api-management-developer-portal#72]
**Describe the bug**
After compilation pages do not load successfully (local development).  Just for more specific, I am facing this issue from last two days before that it was working fine.

Adding console log 
[localhost-1559900938157.log](https://github.com/Azure/api-management-developer-portal/files/3265388/localhost-1559900938157.log)

**Comment by AvanadeAPIClinicTeam** [comment]
issue got resolved after fetching the latest code. thanks

**Comment by azaslonov** [comment]
Thank you for confirming this.
