### ISSUE TITLE
Broken link: scripts/vendor.js

### ISSUE THREAD

**Issue by lrtico** [Azure/api-management-developer-portal#720]
## Bug description

Status code 404 the resource doesn't exist. Since I didn't alter the source code to include this file I presume it is injected into the index.html's "head" tag dynamically.

## Reproduction steps

1. Go to https://apimstaticweb.z5.web.core.windows.net/ in Chrome
2. Open developer tools
3. Find the line of code in the <head> calling the vendor.js file

## Expected behavior

The vendor.js file is in the scripts directory so the status code is 200. Or, this line of code is removed from the "head" tag.

## Is your portal managed or self-hosted?

Self-hosted

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.106 (Official Build) (64-bit

**Comment by azaslonov** [comment]
Hi Jackson, that was fixed some time ago, just pull latest version, do `npm install`, and re-publish the portal.
