### ISSUE TITLE
Question - Function App Models (How to auto create like swagger?)

### ISSUE THREAD

**Issue by bbakermmc** [Azure/api-management-developer-portal#721]
Is there a way using attributes for the import process to pull in the models etc when using function apps?

Im currently using function apps and then using a nuget to have that generate the swagger and then I goto the API Mgnt and import an OpenAPI format, link to the function app endpoint that is generating the swagger and things seem to work okay.  

But in order for me to get the link on the page that links the FA to the API and vice versa in the portal I first have to import the function app, delete the api, import the swager one, modify the policy and add the <set-backend-service id="apim-generated-policy" backend-id="myfunctionapp" />   If I try to do this w/out doing the import function app first it will tell me the backend-id cant be found and cant be saved.

I dont see any documentation anywhere that says do this to generate the needed code for the api mgnt to know what models youre using etc.

Example:
```c#

[FunctionName("PostExclusionQueue")]
        [ProducesResponseType(typeof(List<SendReceipt>), (int) HttpStatusCode.OK)]
        [ProducesResponseType((int) HttpStatusCode.BadRequest)]
        public static async Task<IActionResult> RunAsync(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]
            [RequestBodyType(typeof(PostExclusionQueueInputDto), "Input")]
            HttpRequest req,
            ExecutionContext context,
            ILogger log)
```

**Comment by mikebudzynski** [comment]
@bbakermmc - this question is not related to the developer portal. Please, contact Azure support for assistance

**Comment by bbakermmc** [comment]
@mikebudzynski Whos responsible for it, in typical MS fashion you as one team say its the other team, that team says its the team that just told me to come here.  And honestly its a portal issue, Im using the portal to make expose these out, why cant you tell me the format I need to use, you guys wrote it.  There is no documentation on it that I can find anywhere and it may not even be a feature in which case this turns in to a feature request.
