### ISSUE TITLE
Page footer is not positioned at the bottom in Safari

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#723]
## Bug description

When the basic Contoso site is brought up on an iPhone, we are seeing the "Powered by Azure Management" footer positioned over other elements. 

## Reproduction steps

1. Go to the basic Contoso site
2. Click the sign in
3. Scroll to the bottom
4. See screen capture
![image](https://user-images.githubusercontent.com/65634611/85749333-9d28ea80-b6bd-11ea-9d01-a7b700d969cf.png)

## Expected behavior

The footer should be positioned at the bottom

## Is your portal managed or self-hosted?

Managed

## API Management service name

Basic Contoso site

## Environment

- Device: iPhone 7
 - Operating system: iOs
 - Browser: Safari
 - Version: iOs 13.5.1

**Comment by azaslonov** [comment]
Hi @VWACBrick, thank you, this is a known issue, we'll address it soon.

**Comment by mikebudzynski** [comment]
This bug is also present on MacOS (Safari browser)

**Comment by mikebudzynski** [comment]
Closed with https://github.com/Azure/api-management-developer-portal/pull/772
