### ISSUE TITLE
Truncated Bearer Tokens for Authorization header using Try it

### ISSUE THREAD

**Issue by speedyps** [Azure/api-management-developer-portal#724]
I have an API which is secured using Auth0 for OpenID authorization. Developers (and the sales team) like to demonstrate the API using the 'Try it' button

It is a very standard setup in the OAuth 2.0 in the Developer Portal section of the APIM.

Steps to Reproduce
1. Sign into Portal (either new or legacy)
2. Browse to API
3. Browse to API Call
4. Press Try It
5. Change Authorization from "No auth" to Authorization code
![image](https://user-images.githubusercontent.com/40074438/85825730-15cf9a00-b7d7-11ea-9434-6c5ca984e5c1.png)
6. Inspect Authorization header - should now have a JWT embedded after the word Bearer

Using the original developer portal, when I choose the authorization of "Authorization code", the system populates the Authorization header with Bearer and a full JWT Token (as seen in the below image)
![image](https://user-images.githubusercontent.com/40074438/85825597-bd000180-b7d6-11ea-8432-ba479f639f71.png)

However, when I do the same thing using the new portal, the Authorization header gets a Bearer entry, but the value is not a JWT, it appears to have been truncated (as seen in the below image)
![image](https://user-images.githubusercontent.com/40074438/85825855-65ae6100-b7d7-11ea-9cd2-4e5fc326b9e4.png)

Appreciate any guidance.

**Comment by azaslonov** [comment]
Hi @speedyps, please send your OAuth configuration (without secrets) and service name to apimportalfeedback@microsoft.com. We'll take it from there. Thank you.

**Comment by simonTTIS** [comment]
Hello,

I'm facing the same issue, can you explain how to fix it ?

Thank you.

**Comment by speedyps** [comment]
> Hello,
> 
> I'm facing the same issue, can you explain how to fix it ?
> 
> Thank you.

Hey

I have a potential workaround.

If you update the "Authorization endpoint URL" in your APIM OAuth2.0 config to specify the following parameters, 

```
<auth0 authorization endpoint>?
audience=<whatever your audience is>&amp; 
scope=<whatever scope - we're using "openid email">&amp;
redirect_uri=<callback redirect url generally <apim url>/docs/services/auth0/console/oauth2/authorizationcode/callback&amp;
response_type=code&amp;client_id=<client id you set up in auth0 to handle TryIt queries>
```

I get back bearer tokens which are not truncated.  I am seeing another issue when we try to use the validate-jwt token policy        

```
<validate-jwt header-name="Authorization" failed-validation-httpcode="401" failed-validation-error-message="Unauthorized" require-expiration-time="true" require-scheme="Bearer" require-signed-tokens="true">
  <issuer-signing-keys>
    <key>{{JWTKey}}</key>
  </issuer-signing-keys>
  <audiences>
    <audience>{{JWTAudience}}</audience>
  </audiences>
  <issuers>
    <issuer>{{JWTDomain}}</issuer>
  </issuers>
</validate-jwt>

```

Because we require-signed-tokens set to true, we seem to be getting 401s. 

Sadly, this all works under the old portal with no changes.

Hopefully this might help.
