### ISSUE TITLE
Question: Website Log Metrics on Self Hosted Portal

### ISSUE THREAD

**Issue by Joshua-Liong-vw** [Azure/api-management-developer-portal#725]
When self hosting, we want to generate metrics and counts on website failures. Page loading failures, javascript issues, etc. to ensure operational excellence.

Is there already a means to emit metrics, preferably from the Static Website's Azure Storage Blob, out of the box in the API Management Developer Portal? Do you have any recommendations on approaches to achieve this?

**Comment by azaslonov** [comment]
Hi Joshua, if you don't have a particular framework in mind, I would suggest looking at [Google Tag Manager](https://github.com/Azure/api-management-developer-portal/wiki/Integrate-Google-Tag-Manager) integration, which you could use for instrumentation.

**Comment by azaslonov** [comment]
Joshua, I hope that answers your question. Please feel free to comment or re-open shall you need further assistance.
