### ISSUE TITLE
"Show page headings" not working correctly

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#726]
## Bug description

The function "Show page headings" isn't working as it previously did.
See in the gif below that it has worked before with those settings.

## Reproduction steps

1. Go to a page with headings 
2. Create a new Menu Item or go to an existing one
3. Edit the Menu item
4. Select a root navigation item without children 
5. Activate "Show page headings"
6. See that even without level modifications it doesn't work anymore

## Expected behavior

I expect it to be the same as in the last release.

## Is your portal managed or self-hosted?

Managed

## Environment

- Browser: Chrome Version 83.0.4103.116

## Additional context

The function "Show page headings" worked in the last release. But after the latest release it doesn't seem to anymore.

![2020-06-30_09-38-29](https://user-images.githubusercontent.com/58420097/86098535-88ca6080-bab6-11ea-9496-aaa26db7d7aa.gif)

**Comment by azaslonov** [comment]
Indeed. Thank you @ZarTrox, we'll fix this.

**Comment by azaslonov** [comment]
Fixed.
