### ISSUE TITLE
Can the og:image meta tag be defined?

### ISSUE THREAD

**Issue by cirellamhcs** [Azure/api-management-developer-portal#727]
## Bug description

I can not find a way to define the `og:image` tag

## Expected behavior

I would like to be able to define the `og:image` tag

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

latest master

## Additional context

I had a look into the code and saw that there is the `openGraphHtmlPagePublisherPlugin`. In here one of the function parameters is the `HtmlPage` which has an `openGraph` attribute. This `HtmlPage` object is as far as I can see created in the `PagePublisher`, but the image is never set and therefore the `og:image` will never be rendered. It would be nice to be able to set it somehow.

**Comment by azaslonov** [comment]
Hi @cirellamhcs. Wow, you love to dig into things :)

Right, this is an undocumented feature of the Paperbits framework which is intended to be used along with SEO module that is currently in development.

However, if you're curious, there is a very simple UI that can add image and JSON-LD structure to page metadata. You can enable it by adding feature flag into `config.design.json` file:
```
{
  ...
  "enableSeo": true
  ...
}
```
After that page details will have additional fields:
![image](https://user-images.githubusercontent.com/2320302/86161379-06479e00-bac2-11ea-98b3-990503232cb2.png)

**Comment by cirellamhcs** [comment]
thx for the response! But it throws an error when trying to save it: `{"error":{"code":"ValidationError","message":"Content item doesn't match content type schema.","details":null}}`
