### ISSUE TITLE
Client Credentials using OAuth 2.0 does not respect override scope-setting in API

### ISSUE THREAD

**Issue by johanclasson** [Azure/api-management-developer-portal#728]
## Bug description

Client Credentials using OAuth 2.0 in the interactive developer console does not respect if an API is configured to override scope (In the Azure Portal: API -> Settings -> Override scope). It seams that it is always using the default scope configured for the authorization server (In the Azure Portal: OAuth 2.0 - Default scope). 

## Reproduction steps

1. Create authorization server that allows Client Credentials, and set default scope to for instance `https://graph.microsoft.com/.default`.
2. Create API with override scope set to something else, for instance `api://my-app/.default`.
3. Navigate to developer portal.
4. Click "Try it" and chose "clientCredentials".

This results in an Authorization header with a bearer token issued for `https://graph.microsoft.com`:

```
{
  "typ": "JWT",
  ...
}.{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/{tenantId}/",
  ...
  "appid": "id for client application, configured in APIM OAuth server.",
  ...
  "tenant_region_scope": "EU",
  ...
  "ver": "1.0",
  ...
}.[Signature]
```

## Expected behavior

The authorization header should be set with a bearer token issued for `my-app`, for example:

```
{
  "typ": "JWT",
  ...
}.{
  "aud": "{id for resource application.}",
  "iss": "https://login.microsoftonline.com/{tenantId}/v2.0",
  ...
  "azp": "{id for client application, configured in APIM OAuth server.}",
  ...
  "roles": [
    "{role value configured for resource application and granted to client application."
  ],
  ...
  "ver": "2.0"
}.[Signature]
```

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Edge
 - Version: 83.0.478.56

## Additional context

It seams that [oauthService.ts](signin-oauth/credentials) is only making the browser opening `https://${location.hostname}/signin-oauth/credentials/${authorizationServer.id}`. I cannot find anything that is passed along to `.../signin-oauth/credentials/...` (the backend that makes the actual request for getting the token) that can be used for picking up what API the token should be used for, and hence it cannot make use of any overridden scope that is defined in that API.

**Comment by azaslonov** [comment]
Hi @johanclasson, this should be fixed last week. Can you please try to re-publish the portal? Probably you just don't have latest bits.

Please feel free to re-open, if the issue still exists.

**Comment by johanclasson** [comment]
I did re-publish yesterday. That was what made it work in the first place.

But I have one more re-publish just now, and the behavior is still the same. Note that client credentials is working using the default scope set on the OAuth 2 server object in APIM. My problem is that it does not respect that I have configured an override scope for an API.

Screen shot from OAuth 2 server:
![image](https://user-images.githubusercontent.com/10547631/86167475-dd9dc380-bb16-11ea-93d7-0e693c170410.png)

<hr />

And here is a screen shot from API settings, where the value under Override scope is what I would expect to be used when clicking "Try it" for that API:
![image](https://user-images.githubusercontent.com/10547631/86168501-8f89bf80-bb18-11ea-97f4-a9499a2a88c2.png)

<hr />

What I want is to use a different scope when the developer portal is requesting a token over client credentials. I do realize that I can work around the problem by configuring one OAuth 2 server per API. I just find that using the already present override scope setting to be a better alternative. It not that the reason why it is there?

**Comment by johanclasson** [comment]
I don't have rights to re-open the issue, @azaslonov. Can you do it? Or do you want me to post a new issue?

**Comment by azaslonov** [comment]
Got it, thanks @johanclasson. I would need your service name for further investigation. Could you please send it here: apimportalfeedback@microsoft.com?

**Comment by johanclasson** [comment]
Instead of sending you the service name of our production instance, I created a brand new instance with service name `johanclasson-demo` for this issue, where I could verify that the behavior is the same.

**Comment by ErikMogensen** [comment]
I have the same issue.

**Comment by azaslonov** [comment]
UPDATE: The fix is in the release pipeline and should land in every region in the next couple of weeks.

**Comment by azaslonov** [comment]
Backend deployed. Added respective changes to the client, which should be shipped by the end of this week.

**Comment by azaslonov** [comment]
@Corendiel, could you please send your service name to apimportalfeedback@microsoft.com? We'll check it what's going on.

**Comment by kallemk** [comment]
Hi! I'm experiencing the same thing since today in two instances.
Will send email to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com) as well 👍

**Comment by Kanabis** [comment]
Hello!

We have the same issue with at least one of our APIM instances.
My colleagues will send to you the information to your [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com) mailbox.

Thank you!
