### ISSUE TITLE
Cors not working in developer portal when using custom domain on gateway

### ISSUE THREAD

**Issue by FreBon** [Azure/api-management-developer-portal#729]
## Bug description

I have API management setup and working with the new developer portal. But when i then add a custom domain to the gateway, I'm getting CORS error in the developer portal:
![image](https://user-images.githubusercontent.com/3351808/86137295-6a338c00-baed-11ea-927c-254465f2f513.png)

## Reproduction steps

1. Configure API management so it works with the new Developer portal (I'm using Auzre AD with client credentials for security)
2. Go to the developer portal and make sure that it works as expected to call the API
3. Add the custom domain for the gateway (set as default ssl binding)
4. Go back to the developer portal and try to call a function, it now fails as above

## Expected behavior

Should work to invoke functions from the developer portal with custom domain on the Gateway

## Is your portal managed or self-hosted?

Managed 

## Additional context

I have used the default CORS policy added from the portal overview page. 
`<policies>
    <inbound>
        <cors allow-credentials="true">
            <allowed-origins>
                <origin>https://b2bapimanagement01api01.developer.azure-api.net</origin>
            </allowed-origins>
            <allowed-methods preflight-result-max-age="300">
                <method>*</method>
            </allowed-methods>
            <allowed-headers>
                <header>*</header>
            </allowed-headers>
            <expose-headers>
                <header>*</header>
            </expose-headers>
        </cors>
    </inbound>
    <backend>
        <forward-request />
    </backend>
    <outbound />
    <on-error />
</policies>`

**Comment by azaslonov** [comment]
Hi @FreBon, the policy looks good to me, but your API hostname is not accessible (at least from my machine):

![image](https://user-images.githubusercontent.com/2320302/86164688-01d1b400-bac7-11ea-989f-3a817803537e.png)

And I see that you don't use VNet, so maybe that's the problem. In any case, I would recommend you go to MS support with issue like this. Here we mostly work with self-hosted portal coding problems.

**Comment by FreBon** [comment]
Thanks for the quick response!, I should have checked the DNS record before trying to add it to APIM .. It wasn't registered in the public DNS. Now it is and it works as expected.

**Comment by azaslonov** [comment]
I'm glad you could resolve it. Thanks for confirmation.

**Comment by Aujjani** [comment]
Hello @azaslonov , @FreBon 

I am not able to Enable the CORS for my APIM instance due to which i am unable to get trace of any of my API operations.

![image](https://github.com/user-attachments/assets/56a0ad69-3fe6-4d32-a3af-e4faab4221c9)


Do you have any idea how can i give public access as we host inside a virtual network
