### ISSUE TITLE
Delegated Sign-Out is not working after deploying latest Developer Portal version

### ISSUE THREAD

**Issue by nluff80** [Azure/api-management-developer-portal#732]
## Bug description

Clicking the 'Sign Out' button on the Developer Portal does not sign the user out. I have sign-in delegation configured and this was working until 13 days ago (18/6) when we published the Developer Portal again.

## Reproduction steps

1. Go to the APIM Developer Portal
2. Click on 'Sign In'
3. Sign In delegation is activated and the user is able to sign in
4. User redirected back to the APIM Developer Portal
5. User clicks the Sign Out button but nothing happens

## Expected behaviour

User is signed out and the APIM Developer Portal shows the unauthenticated page view with the Sign In button

## Is your portal managed or self-hosted?

Managed

## Additional context

Following the network traffic it can be seen that a call is made to the /signout route of the APIM Developer Portal which responds with a 302 redirect to the delegation app, but then XHR requests are made to the delegation app (OPTIONS then GET) and both respond with a 200. But this is the exact same flow as seen on other instances for which the sing out operation works as expected. The only difference is that the affected instance in on a newer version of the Developer Portal.

**Comment by mikebudzynski** [comment]
The fix is implemented, the release will roll out in around a month.
