### ISSUE TITLE
Backup content of developer portal

### ISSUE THREAD

**Issue by iwasdavid** [Azure/api-management-developer-portal#736]
If we have a custom developer portal with our own styling and content is there any way to backup the content of the developer portal so that if a new portal was deployed (with terraform for example) and the content wiped - we could then restore the portal content and styles? 

From what I’ve been reading, even if we self host the portal, the content is still stored in the API Management service. 

There are some docs saying that examples of storing the content in other ways is possible but the docs haven’t been finished quite yet.

**Comment by azaslonov** [comment]
Hi @iwasdavid, yes, there are scripts [capture.bat](https://github.com/Azure/api-management-developer-portal/blob/master/scripts/capture.bat) and [generate.bat](https://github.com/Azure/api-management-developer-portal/blob/master/scripts/generate.bat), you can use to backup/restore the content.
