### ISSUE TITLE
Revisions Appearing in Developer Portal as new APIs (including when offline and unpublished)

### ISSUE THREAD

**Issue by jpgough** [Azure/api-management-developer-portal#737]
## Bug description

We are following through the revision feature of the APIM Developer Portal in the documentation for [adding revisions](https://docs.microsoft.com/en-us/azure/api-management/api-management-get-started-revise-api).

When a new revision is created APIM shows two versions of the API in the Developer Portal, which does not seem correct.

Would you be able to clarify if this is indeed a bug or expected behaviour? We were hoping to use this feature to deploy new releases and verify them off production traffic before making the new version live. 

## Reproduction steps

Starting with a fresh API created on the managed (and published) APIM/Developer Portal, assigned to the Unlimited Product:

<img width="1256" alt="starting-point" src="https://user-images.githubusercontent.com/1142788/86480052-3783d080-bd45-11ea-913d-53caf7e1b77f.png">

Create a new revision of the API:

<img width="1462" alt="create-new-revision" src="https://user-images.githubusercontent.com/1142788/86480144-58e4bc80-bd45-11ea-95d4-d952236a0b45.png">

The Developer Portal now shows a duplicate of the API, this is the new version of the API. So if there were new operations this would appear here:

<img width="1192" alt="duplicate-apis" src="https://user-images.githubusercontent.com/1142788/86480240-829de380-bd45-11ea-930b-e2b65ebd3fec.png">

Even when turning Revision 2 to not being online or current the API still appears:

<img width="1964" alt="still-duplicates" src="https://user-images.githubusercontent.com/1142788/86480337-bf69da80-bd45-11ea-9e71-d95bf609b1e5.png">

## Expected behavior

A revision that isn't current should not be in the developer portal (and not as a duplicate API). 

Per the documentation _When your API is ready to go and starts to be used by developers, you eventually need to make changes to that API and at the same time not disrupt callers of your API._ 

Callers aren't disputed, but it feels quite confusing to have the API duplicate in the list of APIs

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

jpgough (temporary instance spun up, but will be taking this down)

## Environment

N/A 

## Additional context

N/A

**Comment by azaslonov** [comment]
Hi @jpgough, this issue has been fixed here in #731. The managed version of the portal will receive the update this week.

**Comment by jpgough** [comment]
@azaslonov thank you for confirming.

**Comment by 11yusuf** [comment]
dear @jpgough , 
I'm facing the same issue. Was it resolved for you ?
