### ISSUE TITLE
oAuth2.0 token has incorrect scope and audience values

### ISSUE THREAD

**Issue by cs2ea** [Azure/api-management-developer-portal#738]
## Bug description

For the same AAD application, the token generated using the old portal is different from the one generated by the new portal. 

Old portal: 
- "aud":"https://analysis.windows.net/powerbi/api"
- "scp":"Dataset.Read.All Metadata.View_Any Workspace.Read.All"

New portal: 
- "aud":"00000002-0000-0000-c000-000000000000"
- "scp":"User.Read"

This difference prevents my backend API from being tested from the new portal. 

## Reproduction steps

1. Application in AAD has the following API permissions: 
- https://graph.windows.net/User.Read
- https://*.asazure.windows.net/Model.ReadWrite.All
- https://storage.azure.com/user_impersonation
- https://analysis.windows.net/powerbi/api/Dataset.Read.All
- https://analysis.windows.net/powerbi/api/Metadata.View_Any
- https://analysis.windows.net/powerbi/api/Workspace.Read.All

2. Setup OAuth 2.0 in APIM for the developer portal:
- Name: APIM-API-PBI
- Grant Type: Authorization code
- Authorization endpoint: https://login.microsoftonline.com/xxxxxx/oauth2/authorize
- Token endpoint: https://login.microsoftonline.com/xxxxxx/oauth2/token
- Additional body parameters: resource=https://analysis.windows.net/powerbi/api
- default scope: https://analysis.windows.net/powerbi/api/Workspace.Read.All https://analysis.windows.net/powerbi/api/Metadata.View_Any https://analysis.windows.net/powerbi/api/Dataset.Read.All

3. Setup user authorization on the API:
- OAuth 2.0
- select : APIM-API-PBI
- do _not_ override scope

4. Test in new portal
- navigate to api of step 3
- select "Try it", then choose "authorizationCode" for the APIM-API-PBI authorization
- after the authorization window popup, retrieve the token from the Authorization Header
- decode the token
--> the aud and scp properties will reflect the first api permission, not the default scope or resource

5. Test in old porttal
- same steps as #4, 
--> the aud and scp properties will reflect the resource and default scope values

## Expected behavior

I expect the new portal OAuth token to contain correct aud and scp property values and have the same behavior as the old portal

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

apim-msfnex23-sbx

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.116

## Additional context

I tried also passing the resource name as a query parameter of the authorization and the token URLs (per workaround to use postman with AAD). This did not change the behavior

**Comment by azaslonov** [comment]
Hi @cs2ea, thank you, we'll investigate.

**Comment by azaslonov** [comment]
Hi @cs2ea, can you please try to bump endpoints version to v.2.0, I suspect that might be the problem.
https://login.microsoftonline.com/xxxx/oauth2/v2.0/authorize
https://login.microsoftonline.com/xxxx/oauth2/v2.0/token

**Comment by cs2ea** [comment]
Hi @azaslonov 
Testing with the new v2.0 endpoints results in the correct scope and audience in the token - I am now able to test the API fully in the new portal --> Thank you very much!

However, something else must have changed in the in portal (or in AAD?) recently - I reverted the endpoints to the original ones to verify that the original issue was still present and found that I could not reproduce it --> both versions of the endpoints appear to work

In any case, from my side, I can confirm that I am not facing the issue anymore. 
Kind Regards

**Comment by cs2ea** [comment]
I have tested again using both v1 and v2 endpoints, this time using  grant type clientCredentials. 
Scope and audience are only set correctly with the v2.0 endpoints in this scenario

--> Additional confirmation to use the v2.0 endpoints

**Comment by gs11** [comment]
Microsoft support replied today that:
>OAuth v1 endpoint for the new developer portal is currently not supported. Support will be added in the future but we don't have an ETA at the moment.

**Comment by cs2ea** [comment]
Thanks alot for the followup!
The solution is fine and works for us

No need for further action on this issue
