### ISSUE TITLE
Unable to fetch gateway hostnames - Trying to view operation details

### ISSUE THREAD

**Issue by mhackermsft** [Azure/api-management-developer-portal#739]
## Bug description

When using only an on-premises gateway and not the managed gateway for all APIs an error is thrown when trying to view an operation in the developer portal.

Error:
theme.js:2 Error: Unable to fetch gateway hostnames.
    at OperationDetails.<anonymous> (theme.js:2)
    at Generator.next (<anonymous>)
    at fulfilled (theme.js:2)

## Reproduction steps

1. Deploy an on-premises API gateway
2. Configure all APIs to only use the on-prem gateway
3. Visit the developer portal as a user, navigate to the APIs and choose an API and operation.   No details are shown. Opening up the browsers developer tools shows the error shown above.

## Expected behavior

The operation details for the API should be displayed.  For APIs only available for on-premises gateways the Try It button should be disabled since the Developer portal will not have access to on-premises resources.

## Is your portal managed or self-hosted?

Managed

## API Management service name

mhackerapi

## Environment

 - Operating system: Windows
 - Browser: Google Chrome and Microsoft Edge
 - Version: Google 83.0.4103.116, Edge 84.0.552.28

**Comment by azaslonov** [comment]
Hi @mhackermsft, it looks like service-specific issue, please send your service name to apimportalfeedback@microsoft.com or refer to MS support.

**Comment by vikramhn** [comment]
I was able to get around this after I added hostname in the portal. steps below.

Click on Gateways and go to deployment click on hostnames to add one
you can use a self signed cert , reference link below for self signed certs 
Cert can be added in the API Management portal under - API Management Service -Security -> Certificates

https://medium.com/@jkewley/testing-client-certificate-authentication-to-azure-api-management-with-postman-e1cfae52fc35
