### ISSUE TITLE
"Redirect anonymous users to sign-in page" for Self-Hosted?

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#741]
Just wondering if the "Redirect anonymous users to sign-in page" under "Identities->Settings" should/could be supported with Self-Hosted?

We understand the Self-Hosted is running on Blobstorage and it's not running any server code. Just wondering if APIM team has considered a way to support this?

TenantSettings possibly contains this property?
src\contracts\tenantSettings.ts

`"CustomPortalSettings.RequireUserSigninEnabled": string;`

**Comment by azaslonov** [comment]
Hi @VWACBrick, the simplest way to do this without the server-side is to set up JavaScript redirect (i.e. using RouteGuard interface).

Speaking of server-side, we're going to open-source our backend at some point, which is basically a Node JS application that can be hosted on, i.e. [Azure Web Apps](https://azure.microsoft.com/en-us/services/app-service/web/).

Another project that we're watching closely is [Azure Static Web Apps](https://azure.microsoft.com/en-us/services/app-service/static/), which has server-side logic around user roles and redirect rules. Unfortunately, there is currently no good way to integrate APIM authorization flows into their system, but I'm sure it will be addressed in the future.

**Comment by VWACBrick** [comment]
Thank you for the suggestion for the using RouteGuard. 

Our problem is RouteGuard.canActivate() only executes when there is a hash (#) on the URL. 

We would like canActivate to always be called.  Possible?
