### ISSUE TITLE
Authorization Subscription Key drop down does not reset correctly between Try It sessions. 

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#742]
## Bug description

To use the "Try It" feature, the user would select the Subscription Key drop down to select "authorizationCode". This would trigger an AAD authentication dialog, and the result is the Bearer token would be created as an Authorization param. 

However, when this is done for the first API Operation, the drop down will not reset to "No auth" when you move over to the next API Operation. The result is the Authorization param (bearer token) is empty, but the drop down is still on "authorizationCode" selection, and the user has to toggle the drop down twice to get it to generate again. 

## Reproduction steps

1. Site is configured to use AAD auth
2. Configure the Echo API to require Oauth 2.0 User Authorization
3. Open the Echo API in the portal
4. Select the first Operation like Put
5. Select the Authorization dropdown and select "authorizationCode"
6. You should see the authentication occur and the bearer token created
7. Now select another API Operation from the list, and the bearer token is removed, but the authorization selection dropdown is still set.

## Expected behavior

I would expect the dropdown to reset to "no Auth" when the operation context is changed. I don't think the bearer token should be persisted. 

![image](https://user-images.githubusercontent.com/65634611/86960261-1be94300-c114-11ea-80d1-01a6a500da3c.png)

## Is your portal managed or self-hosted?

Managed 

## API Management service name

contoso-api

## Environment

 - Operating system: Windows 10
 - Browser: FireFox and Edge Chromium

**Comment by azaslonov** [comment]
Hi VWACBrick, thanks for reporting the issue, we'll fix this.

**Comment by azaslonov** [comment]
Fix merged. Release to the managed version will happen sometime next week.
