### ISSUE TITLE
operation-console oauth: redirect uri mismatch

### ISSUE THREAD

**Issue by linasburneika** [Azure/api-management-developer-portal#744]
I'm trying to setup self hosted portal on a different subdomain (it is accessible through Azure CDN, where this domain is configured) than the apim instance. 

After configuring oauth support for tryout functionality in console, I ran into issue with redirect uri. On Azure APIM it is read only and has the following format: `https://<<apim-instance>>.portal.azure-api.net/docs/services/<<oauth-server-id>>/console/oauth2/authorizationcode/callback`

However developer portal has hardcoded redirect url as follows: `https://${location.hostname}/signin-oauth/code/callback/${authorizationServer.id}` (in oauthService.ts). In this case `location.hostname` gets resolved to my custom domain. Obviously there is no backend on this endpoint to process the request, because it's just a static site.

It's strange that uri formats are so different. Judging from Microsoft APIM documentation, the readonly redirect url I got coincides with screenshots in MS documentation: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-oauth2.

I can change the redirect url myself, but I still need somehow provide apim instance name during portal publishing stage. Any ideas?

**Comment by azaslonov** [comment]
Hi @linasburneika, you're right the documentation needs to be fixed.
Please use `/signin-oauth/code/callback/{authServerName}` for "authorization code" grant flow and `/signin-oauth/implicit/callback` for "implicit" grant flow.

**Comment by mikebudzynski** [comment]
We've updated the Azure documentation (give it up to 24h to propagate). We also plan to include the callback URL for the new portal in the Azure portal view, no ETA at this moment.
