### ISSUE TITLE
when we try to choose another Product/API from the dropdown in Product/API details page it kept open until we click somewhere on the page.

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#745]
Steps to recreate : 
1. Go to API details page in the developer portal
2.  Try to select another API from dropdown

Expected: Dropdown should be closed once we click on the API name
Actual: Dropdown kept on open until click somewhere on the page

**Comment by BobbyCGD** [comment]
It might be useful to add:
- If you have the "Try it" panel open when changing the API the "Try It"  panel stays open and still points to the API that was loaded. It would be better if that gets closed as well.
