### ISSUE TITLE
We have an SSL certificate for our developer portal. But, the certificate is valid only for one year

### ISSUE THREAD

**Issue by Gowtham2371998** [Azure/api-management-developer-portal#746]
Hi Team

We have an SSL certificate for our developer portal. But, the certificate is valid only for one year (i.e., from 12-05-2020 to 12-05-2021). 
Is that certificate will be regenerated automatically after 12-05-2021? or We have to re-create it, If that is a case how to do that?

Thanks,
Gowtham S

**Comment by azaslonov** [comment]
Hi @Gowtham2371998, if this is a default hostname *.developer.azure-api.net, then it will be rotated. If it is your own, then you have to take care of it.
