### ISSUE TITLE
Ifrastructure-as-Code for the Developer Portal

### ISSUE THREAD

**Issue by lukipro** [Azure/api-management-developer-portal#747]
Hello,

is there a way to automate the developer portal deployment?

I am thinking of some way which would allow to store custom developer portal layout as code and apply changes in some automated fashion. I couldn't find anything in the documentation about it.

Thanks

**Comment by mikebudzynski** [comment]
Take a look at https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services and the `/scripts` folder.
