### ISSUE TITLE
Support for OpenID Connect in Try it console

### ISSUE THREAD

**Issue by azaslonov** [Azure/api-management-developer-portal#748]
API console is missing support for OpenID Connect flow.

**Comment by azaslonov** [comment]
The managed version will receive the updates some time next week.

**Comment by cvijayak** [comment]
Hi Team,

I am using "OpenID Connect" configuration.

But I am seeing the following in the legacy developer portal. But in the new version it just shows "implicit" option only.
1. Authorization code
2. Implicit

Are you going to add "Authorization code" option in the new version?

Thanks,
Chandrasekar. V

**Comment by cvijayak** [comment]
Hi Team,

I am using "OpenID Connect" configuration.

But I am seeing the following in the legacy developer portal and in the new version it just shows "implicit" option only.
1. Authorization code
2. Implicit

Are you going to add "Authorization code" as an option?

Thanks,
Chandrasekar. V

**Comment by cvijayak** [comment]
Any updates on this?

**Comment by azaslonov** [comment]
Yes, we are going to support those flows as well. It requires some backend changes that we are waiting for.
