### ISSUE TITLE
Representations not showing on Developer Portal API Docs but showing correctly on Legacy Developer Portal API Docs

### ISSUE THREAD

**Issue by iwasdavid** [Azure/api-management-developer-portal#749]
We have 2 request representations for a SOAP API endpoint that we add using the Azure API Management REST API after we deploy the API using Terraform.

When viewing the API documentation the 2 request representations are not showing on the API Documentation for the Developer Portal but they are showing correctly for the Legacy Developer Portal API Documentation. The response representation is showing correctly on both portals.

## Reproduction steps

1. Go to Developer Portal
2. Click on SOAP operation and see no request representations

## Expected behavior

1. Go to Developer Portal
2. Click on SOAP operation and see 2 request representations

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version: 83.0.4103.116

## Notes

I have tried publishing the portal 3 times to see if it would update.

**Comment by iwasdavid** [comment]
Also, I have just created another API Management instance with a SOAP API with the exact same representations and they are showing fine on both portals so I'm not sure why I'm having the above issues with this API Management instance.

**Comment by mikebudzynski** [comment]
Have you republished the portal in the APIM service with the wrong representation?

**Comment by iwasdavid** [comment]
Does the developer portal have different rules for rendering representations than the legacy developer portal as they showing fine on that one? I'll try deleting them again and then adding them and then publishing the portal and see if that helps.

**Comment by iwasdavid** [comment]
I've deleted them, and manually added them and then re-published the portal and they are showing fine. I'm not sure why I needed to delete them and then add them manually. We are possibly posting them incorrectly, although they rendered fine on the legacy portal which is why we assumed they were correct. Happy for this to be closed unless it needs investigating?

**Comment by azaslonov** [comment]
Hi @iwasdavid, I think we'll need more specific examples. Do you mind attaching some screenshots of the same docs for both legacy and new portal?

**Comment by iwasdavid** [comment]
@azaslonov sorry but I didn't take any screenshots. If I get into the situation where I have the 2 portals rendering different representations again I'll take screen shots and post a link to the portals. I'll close this issue now as I don't think I can provide you with any information to help you debug.
