### ISSUE TITLE
Moving manged to selfhosted with existing implementation.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#751]
Hi there,

We are trying to move from managed to selfhosted and we have static files for existing implementation from built in storage account of APIM instance. is there any way that how we can start implementation on top of existing implementation. When we try to follow the [ setting up a generic self-hosted portal](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal) process, its getting us the basic implementation of contoso website. can you please guide us how we can start implementation without losing existing implementation.

## Is your portal managed or self-hosted?

Managed 

Please find below screenshots

Expected:
![image](https://user-images.githubusercontent.com/30490543/87385683-4a579a00-c5bc-11ea-80c3-4cf76d714afc.png)

Actual:
![image](https://user-images.githubusercontent.com/30490543/87385753-783cde80-c5bc-11ea-9b31-2c5a4eb48385.png)

**Comment by mikebudzynski** [comment]
@shashiguru make sure you're using the same API Management service with your self-hosted portal. The instructions are in our wiki section, if you still encounter problems, please open an Azure support request for assistance.
