### ISSUE TITLE
Shows "hidden content" in Gmail

### ISSUE THREAD

**Issue by HariSudhan106** [Azure/api-management-developer-portal#755]
Hi Team,

We have customized the notification templates of managed developer portal to send emails to our customers.

The problem with Gmail is, if there are more than one emails with the same subject or content, it hides the contents and shows "..." to show the hidden content as shown below:
![image](https://user-images.githubusercontent.com/68328912/87676126-d8d34380-c795-11ea-89bc-c1bd3e9ba905.png)

We are not facing this behavior with other mail client like Yahoo. Please refer to the image below.
![image](https://user-images.githubusercontent.com/68328912/87675936-9dd11000-c795-11ea-91b6-260dcf61c108.png)

Please let us know if there is any way to avoid this behavior by customizing the notification template.

Thanks,
Harihara sudhan.

**Comment by mikebudzynski** [comment]
I'm not familiar with the GMail categorization algorithms, but you can try including a unique value to the subject of the email, for example developer's first and last name or their email

**Comment by HariSudhan106** [comment]
Thanks for your reply.

First/Last name of a developer cannot be unique every time in the mail. Let's say, a user tries to reset the password couple of times continuously. The email content and subject will not differ with previous mails. 

Even If a same developer subscribes for a single product multiple times, all subscription emails will have the same content and subject.

Please share your suggestions to make the content unique in this case. So the issue can be resolved.
