### ISSUE TITLE
Ability to tell which version of the Developer Portal is running 

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#759]
## bug description

I want to be able to tell which version of the Developer Portal is running. That way I know what features and bugs to expect. 

Since it takes some time for a new Developer Portal version to be released everywhere, (we have an instance that hasn't received 2.4.0 released 22 days ago) it makes troubleshooting take more time since you first have try to find out which version you are using before reproducing the issue.

Also when reading the issues here it would greatly help if the version number was included in the report.

## Expected behavior

Some way of getting the version, like entering a certain URL path.

## Is your portal managed or self-hosted?

Managed

**Comment by ygrik** [comment]
@ErikMogensen for the managed version you can use GET request on https://{you service}.developer.azure-api.net/internal-status-0123456789abcdef

You will get the response 
{"Status":200,"PortalVersion":"202006292219","CodeVersion":"20200708093851","Version":"0.13.1027.0","RoleNumber":"Proxy.Host.WebRole_IN_0"}

"PortalVersion":"202006292219" - your published portal version, change on publishing
"CodeVersion":"20200708093851" - released code version, change on portal code release
"Version":"0.13.1027.0" - release service version, change on APIM new release

**Comment by ErikMogensen** [comment]
This is fantastic information! 

Does the release service version match a release listed at https://aka.ms/apimupdates?
