### ISSUE TITLE
How to self host developer portal in local environment for APIM whose domain name is other than managment.azure-api.net

### ISSUE THREAD

**Issue by anjusharma17** [Azure/api-management-developer-portal#76]
We are trying to configure our local environment for a APIM whose managementApiUrl  is _https://testportal.xyz.com_ instead of "_https://testportal.management.azure-api.net_".
 You can see that the **domain name of our testportal is xyz.com and not management.azure-api.net.**

**We are getting below error log for testportal having domain type other than management.azure-api.net.**

"https://testportal.xyz.com
_(node:13328) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 2
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\anju.c.sharma\azure_devportal\api-management-developer-portal\scripts\generate.js:35:34)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:13328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._"

 Also the code which is there at generate.js:35:34 is as below
**resolve(JSON.parse(data));**

Please help us to resolve this on priority if it a bug or **let us know the way in which this can be achieved if this type of functionality is already implemented?**
 Also , let us know if you need more details as well.

![Exception](https://user-images.githubusercontent.com/17688551/59405775-465db500-8dc9-11e9-996e-2075b15fbcbb.png)

**Comment by azaslonov** [comment]
Hi @anjusharma17, thanks for posting the issue. Looks like we need to make provisioning scripts more universal. Please give us a couple of days to do that.

**Comment by anjusharma17** [comment]
Hi Alexander,

When we will be getting the updated scripts?

**Comment by azaslonov** [comment]
Hi Anju, changes merged to master.
