### ISSUE TITLE
API Dropdown list is using style .text-truncate, but it's still wrapping the API text

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#760]
## Bug description

When the API name gets long (adding the version string) it will line wrap in the dropdown, but the applied style text-truncate is missing the white-space:nowrap. 

![image](https://user-images.githubusercontent.com/65634611/87809814-da8e1d00-c810-11ea-8c92-9aa112f48b72.png)

## Reproduction steps

1. To the API page
2. Select the API Dropdown
3. Result. The text is wrapping
![image](https://user-images.githubusercontent.com/65634611/87809564-71a6a500-c810-11ea-8525-3840166e2113.png)

## Expected behavior

I would think we would want to see this?
![image](https://user-images.githubusercontent.com/65634611/87809461-4d4ac880-c810-11ea-801b-562e724d0dae.png)

## Is your portal managed or self-hosted?

Managed 

## API Management service name

contosco

## Environment

 - Operating system: Windows 10
 - Browser: Edge and Chrome

**Comment by azaslonov** [comment]
Hi @VWACBrick, yep this is done already. The managed version will receive it this week. Thanks for digging into it.
