### ISSUE TITLE
New Developer portal Reset password is not working :Server error. Unable to send request. Please try again later.

### ISSUE THREAD

**Issue by Praveen6867** [Azure/api-management-developer-portal#767]
Hi All,

I am trying to reset my account credential got a rest password link to register an email address when I click on the link and provide new credentials to hit the RESET button.  

Getting the below error
**Server error. Unable to send request. Please try again later.**
 
![Capture](https://user-images.githubusercontent.com/908002/88021156-9e2d2a80-cb4a-11ea-8f24-41d4e4f16000.PNG)

**Comment by mikebudzynski** [comment]
@Praveen6867 please contact Azure support.
