### ISSUE TITLE
"No operation selected." when the API details loads even though an API is highlighted (bold)

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#769]
## Bug description

This issue seems to be random or timing based. When the API details page is loaded, sometimes the first API does not select correctly. The UI indicate it's selected, but the message "No operation selected" will appear.

A clear and concise description of the bug.

## Reproduction steps

1. Go to Contoso deployment of APIM
2. Click on API's from the menu
3. Select the "Echo API"
4. Review the API details page

## Expected behavior
The Create Resource is bold text to indicate it's selected, but the message indicates there is no operation is selected. 
URL has the API in the hash
`/api-details#api=echo-api&operation=create-resource`

![image](https://user-images.githubusercontent.com/65634611/88087326-91560a00-cb3d-11ea-9564-31cd59af48ab.png)

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

Portal was Published on 7/21/2020

{"Status":200,"PortalVersion":"202007211721","CodeVersion":"20200708093851","Version":"0.13.1027.0","RoleNumber":"Proxy.Host.WebRole_IN_0"}

## API Management service name

contoso-api

## Environment

 - Operating system: Windows 10
 - Browser: Edge Chromium
 - Version: 84.0.522.40

## Additional context

Our Test Automation stumbled on this problem, and now we can reproduce it occasionally manualy.

**Comment by azaslonov** [comment]
Thanks @VWACBrick, we'll fix this.

**Comment by azaslonov** [comment]
Fixed in last release.
