### ISSUE TITLE
Dynamic menu for anonymous vs signed in users

### ISSUE THREAD

**Issue by skypyxis** [Azure/api-management-developer-portal#77]
The developer portal renders the same UI for anonymous and signed in users which is very confusing.

I wasn't expecting to see a "Profile" navigation item when not signed in. 
Conversely, when signed in, the navigation bar should not display the "sign up" / "sign in" items and the "Sign up" button on the home page could be hidden.

Is this possible today? What am I missing? 

Thank you.

**Comment by andremarques023** [comment]
You right - that's not the expected behavior. We should be able to identify if the user is logged in to display the items properly.

**Comment by azaslonov** [comment]
Hi @sealight, @andremarques023, this feature is coming in next couple weeks.
