### ISSUE TITLE
To use OAuth Serevr for generating jwt and testing using Postman for a machine-machine scenario

### ISSUE THREAD

**Issue by rkarekar07** [Azure/api-management-developer-portal#771]
I have Configured an OAuth server for my Azure API Management. I have tested it out with Developer Portal(Legacy)  Interface and it worked fine. However, I want to implement it for a machine-machine scenario and need to test it with Postman to generate a token from an endpoint with basic details passed. I am not sure how I can do this. Need help.

**Comment by mikebudzynski** [comment]
Please, reach out to Azure support for assistance
