### ISSUE TITLE
"Change Name" validation bug

### ISSUE THREAD

**Issue by lrtico** [Azure/api-management-developer-portal#774]
### Repro Steps:
1. Browse the url i.e. https://devapiportal.eastwestbank.com/
2. Signin to the portal
3. Click on "Profile" link in Header
4. Click on "Change Name" button
5. Clear all the text boxes
6. Click on save button

### Actual:
User is redirected to Profile Page > Login Page> Home page

### Expected:
- User is not allowed to proceed until they enter a first and last name.
- Page is not redirected.
- An error message is displayed prompting users to enter a first and last name
- The "Save" button maintains its disabled state (gray).

### Is your portal managed or self-hosted?
Self-hosted

### Release tag or commit SHA (if using self-hosted version)
Portal was updated on 7/21/2020

### Environment
Operating system: Windows 10
Browser: Chrome
Version: 84.0.4147.89 (Official Build) (64-bit)

**Comment by shashiguru** [comment]
Hi @lrtico, sorry to spamming here, i need help to move from managed version to self hosted without losing implementation done through managed version. as your working on self hosted so what exact way your using for self hosted and your answers will be appreciated and thanks advance.

**Comment by mikebudzynski** [comment]
@shashiguru - check out this article: https://github.com/Azure/api-management-developer-portal/wiki/Move-from-managed-to-self-hosted Make sure to perform backup just in case.

**Comment by lrtico** [comment]
Thanks @mikebudzynski!
