### ISSUE TITLE
When the password is changed the system is not asking the user to login with the latest password.

### ISSUE THREAD

**Issue by lrtico** [Azure/api-management-developer-portal#775]
## Reproduction steps

1. Browse the url i.e. https://devapiportal.eastwestbank.com/
2. Signin to the portal
3. Click on "Profile" link in Header
4. Click on Change Password button
5. Enter new password information and click on Save button

## Expected behavior

User should be redirected to Login page to login with their new password.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)
Release 1.4 deployed 7/21/2020

## API Management service name
Bridge Open Banking

## Environment
 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.89 (Official Build) (64-bit)

**Comment by mikebudzynski** [comment]
@lrtico Can you share more details on and motives behind this Issue? It's not a common pattern to log out the user after the password change.

**Comment by lrtico** [comment]
I agree and am glad you do too! My testing team flagged this so I felt compelled to check with the API team. I'll let them know we are going to close this issue. ^___^
