### ISSUE TITLE
Searching the operations list includes all API data not just the API's title

### ISSUE THREAD

**Issue by lrtico** [Azure/api-management-developer-portal#777]
## Bug description
When searching for API methods in the operations list widget, if a method has a "/" in it the search logic isn't returning it.

## Reproduction steps

1. Browse to [https://devapiportal.eastwestbank.com/](https://devapiportal.eastwestbank.com/)
2. Click on the "All API" link on the header
3. Click on the "Learn more" link for the specific api
4. Enter "master/sub" in the search input and click on Enter

## Actual behavior
The system is displaying the "No operations found" message

## Expected behavior
The system should display all the methods which contain the text "master/sub"

## Is your portal managed or self-hosted?
Self-hosted

## Release tag or commit SHA (if using self-hosted version)
Release 1.4 deployed 7/21/2020

## API Management service name
Bridge Open Banking

## Environment
 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.89 (Official Build) (64-bit)

**Comment by azaslonov** [comment]
Looks like a forgotten item. @lrtico, sorry for the ignorance on our side, I see that the portal is not available anymore, so closing the issue. Please feel free to re-open if it is still relevant.
