### ISSUE TITLE
Oauth2 authentication on the developer portal

### ISSUE THREAD

**Issue by sdementen** [Azure/api-management-developer-portal#78]
**Is your feature request related to a problem? Please describe.**
The developer portal only allows username/password authentication, while we have Okta as identity provider.

**Describe the solution you'd like**

Ability to use Okta as authentication for the developer portal, with authorization based on scopes (and other claims)

**Comment by azaslonov** [comment]
Hi @sdementen, we're going to have examples for custom authentication. Please referer to [this item](https://github.com/Azure/api-management-developer-portal/issues/29) for tracking.
