### ISSUE TITLE
Tag Search does not repopulate 

### ISSUE THREAD

**Issue by nardielloam7451** [Azure/api-management-developer-portal#780]
Hello!

We are almost done with a  transition to the self-hosted portal. However, in our testing we noticed one issue with the tags search feature. 

When selecting an api from the api list view, we get no issues, and everything works as intended. However, when switching between apis using the api dropdown feature on the operation page, the tags for the original api are the ones still located in the tag search feature, not the tags for the new selected api. 

Hope to hear back from you all soon about this! Thank you!!

**Comment by mikebudzynski** [comment]
I'm not sure if I understand the issue. Can you provide a screenshot?

**Comment by nardielloam7451** [comment]
Certainly! Sorry, had to get back to my work machine in order to retrieve the screen shots. As you can see in this first screenshot,  this api has its own tags. 
![image](https://user-images.githubusercontent.com/36975113/88567796-3583f900-cff5-11ea-90e0-40045e15be85.png)

However, if we switch apis using the operation list drop down menu, and look at the tags as shown in the second screenshot, we find that the tags are still populated from that first api. 
![image](https://user-images.githubusercontent.com/36975113/88568076-a0353480-cff5-11ea-9f0b-bf34439d2ecc.png)


Finally, if we simply reload the page, the tags populate correctly. Is there a reason for this? (Note, we are using the default widgets in the self-hosted solution)
![image](https://user-images.githubusercontent.com/36975113/88568104-aaefc980-cff5-11ea-9927-dc390f638495.png)

**Comment by mikebudzynski** [comment]
Thanks; it's a bug.
