### ISSUE TITLE
Access to pages is possible without login even its required

### ISSUE THREAD

**Issue by ilspiert** [Azure/api-management-developer-portal#782]
## Bug description

Access to pages are possible without login or are quickly displayed, before redirected to the login page.

## Reproduction steps

Open the following pages directly:
- _https://api-management-service-name.developer.azure-api.net/profile_
- _https://api-management-service-name.developer.azure-api.net/change-password_

When accessing _https://api-management-service-name.developer.azure-api.net/reports_ it will be just displayed, even it make no sense to show it whithout user relation.

## Expected behavior

If a user is not authenticated, the user should be redirected to the login-page without loading the page and the requested origin page should be put as returnUrl query parameter.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

release `2.4.1`

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.89

**Comment by azaslonov** [comment]
Hi @fsettele, thanks, we'll fix this.

**Comment by mikebudzynski** [comment]
We're now working on defining the scope of a feature that will enable content access control in the developer portal. If you're interested in this improvement, please respond to our survey: https://aka.ms/apim/survey/devportal/accesscontrol - your feedback will help us better understand your requirements and design the right solution.

**Comment by mikebudzynski** [comment]
> We're now working on defining the scope of a feature that will enable content access control in the developer portal. If you're interested in this improvement, please respond to our survey: https://aka.ms/apim/survey/devportal/accesscontrol - your feedback will help us better understand your requirements and design the right solution. The survey closes on Friday, November 5.

Just a reminder that the survey closes in 2 days.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
