### ISSUE TITLE
No Authorization header in try out console after republish developer portal.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#784]
APIM instance is configured with OpenIDConnect, we are able to generate Authorization code in legacy developer portal but unable to see Authorization header in new developer portal. We publish new developer portal but still same issue.

## Bug description
Legacy Developer portal:
![image](https://user-images.githubusercontent.com/30490543/88663698-9e549980-d0f9-11ea-817f-47236c3a9988.png)

New Developer portal:
![image](https://user-images.githubusercontent.com/30490543/88663775-bc21fe80-d0f9-11ea-8b11-0c243855d2b0.png)

## Reproduction steps

1. Go to 'APIs'
2. Click on 'one API'
3. Scroll down to 'Try out'

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
OpenID Connect support has already been implemented and will be rolled out with the next release. ETA is ~2 weeks; make sure you republish your portal.

Merging with #748

**Comment by mikebudzynski** [comment]
Correction: it's been rolled out with the current release. Some Azure regions already have received the upgrade, others will within the next few business days.
