### ISSUE TITLE
CORS issues with backendService.ts getting delegation URL

### ISSUE THREAD

**Issue by tOmoness** [Azure/api-management-developer-portal#785]
Hi there,

I have delegation turned on and currently, for testing purposes, it is pointing to a local application on my machine. All works fine when running through the managed portal, but when accessing the self-hosted portal via `npm start` and clicking Sign In it makes the call to the managed portal URL to get the delegation URL and fails CORS.

![image](https://user-images.githubusercontent.com/4624841/88718309-b3412500-d119-11ea-979a-18a29bbafed8.png)

The same happens if I try to run `npm run publish` locally as well. It will fail to render the Sign In page because it tries to make that call and fails.

Any thoughts?

Cheers 👍

**Comment by azaslonov** [comment]
@ygrik can you please have a look at what can be done here?

**Comment by ygrik** [comment]
Please add following parameter in config.publish.json
"backendUrl": "https://<service name>.developer.azure-api.net"

Close with https://github.com/Azure/api-management-developer-portal/pull/834
