### ISSUE TITLE
Delegation product subscription doesn't pass through entered name

### ISSUE THREAD

**Issue by anttlcc** [Azure/api-management-developer-portal#787]
## Bug description

With delegated product subscription enabled.

When subscribing to a product, the developer portal requires a name but doesn't pass that through to the delegate URL.

## Reproduction steps

Enable delegation for sign in/up and product subscription.
Subscribe to a product with a name.
Notice that the delegate URL doesn't include the name.

## Expected behavior

I would expect the delegate URL to include a parameter for the name that has been entered so that the APIM Rest API can be called with the same name.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Edge
 - Version: 84.0.522.44

## Additional context

I have delegated sign in/up and product subscription in the developer portal. When I go to subscribe to a product I have to enter a name of the product, which is fine but then I don't get the name that I entered passed through into my delegation app.

![image](https://user-images.githubusercontent.com/68732331/88782037-07352380-d185-11ea-9b31-0b9ccd547335.png)

Delegate URL for product subscription.
https://example.com/
?userId=d1aad5f9-4eb6-48cb-98fa-19079aa5715b
&productId=my-product
&operation=Subscribe
&salt=my-salt
&sig=my-sig

**Comment by ygrik** [comment]
Hello @anttlcc 
Thank you for point this case. It looks like we need to hide input for the name for delegation as it describes in docs and implemented in the legacy portal.

**Comment by anttlcc** [comment]
@ygrik can I ask whether checking the T&Cs will still be visible with delegation enabled and it'll just be the name box which is removed?

**Comment by ygrik** [comment]
@anttlcc what did you mean under T&C?

**Comment by anttlcc** [comment]
@ygrik You can provide "Legal terms" in the settings of products and that means you need to check an agree box before you can subscribe. Will this box still be there or will the delegation have the handle it?

![image](https://user-images.githubusercontent.com/68732331/89623455-8533b180-d88c-11ea-8bd3-87179f85a553.png)

**Comment by adamstruck** [comment]
Any updates on this?

**Comment by mikebudzynski** [comment]
No updates at this moment. Is it an urgent issue for you?

**Comment by adamstruck** [comment]
This issue affects customer experience, but doesn't block anything on the technical side for us. So no, it is not urgent.
