### ISSUE TITLE
Looking for old developer Functionality into new developer portal, with some extra feature.

### ISSUE THREAD

**Issue by anjusharma17** [Azure/api-management-developer-portal#79]
Can you please let us know, when we are getting below functionality of old developer portal into the new one.

**1.** 	We are looking for Blogs feature implementation. Also, will the feature now support blobs categorization and based category filtration in new azure developer portal?
**2.** 	We are looking for complete Media library Feature implementation.
**3.** 	We are looking for Content feature implementation. Also, will the feature now support content categorization and based category filtration in new azure developer portal?
**4.** 	We are looking for APIs filtration based on Tag implementation.

**Comment by azaslonov** [comment]
Hi Anju,
1. Yes, Blog feature is coming soon. Categorization is possible through extending content types with your custom properties (if existing are not enough) and adding respective filters into UI.

2. There is Media library already. If you have specific requirements for this feature, please let us know.

3. Not sure I understand what you mean by Content feature. Are we talking about content in general? or you need [Content Management API](https://github.com/Azure/api-management-developer-portal/wiki/Content-management-REST-API)?

4. Filters based on Tags are coming soon.

**Comment by anjusharma17** [comment]
Hi Alexander,

Regarding point 3, 
![Content Feature](https://user-images.githubusercontent.com/17688551/59497147-79c73f00-8eb0-11e9-94e0-91f3196bf3cc.PNG)

Please help us from where we can get this Manage content functionality in new developer portal?

**Comment by anjusharma17** [comment]
Thanks for the reply.

Regarding Above point 3. We have Manage content functionality in old developer portal. 
![Content Feature](https://user-images.githubusercontent.com/17688551/59491131-f273ce80-8ea3-11e9-9840-702495af0d75.PNG)

**Comment by azaslonov** [comment]
So, the analogy of "Content" section would be "Pages" section in new portal:
![image](https://user-images.githubusercontent.com/2320302/59526514-f39a0100-8e8d-11e9-83e6-4550780e7e69.png)

... and content editing itself is happening right in place:
![image](https://user-images.githubusercontent.com/2320302/59526631-3e1b7d80-8e8e-11e9-8381-4803a6028162.png)
