### ISSUE TITLE
Change password delegation URL does not have userid

### ISSUE THREAD

**Issue by ronimanojk** [Azure/api-management-developer-portal#790]
Delegation URL for the operation=ChangePassword does not have userId mentioned in it.
 
## Reproduction steps

1. Enable User Delegation
2. Login and go to Profile page in the developer portal
3. Click on Change Password.

## Expected behavior

Delegation URL should have userId so that it can be used to change the password in the backend.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

release 2.4.1

**Comment by ygrik** [comment]
Hello @ronimanojk 
I can't reproduce this issue.
Please republish your portal, we just deployed the update.
Please reopen this issue if the change password delegation does not send userId.
You can send your APIM service name with browser traces on apimportalfeedback@microsoft.com for detailed investigation.
