### ISSUE TITLE
Copy code feature does not work properly

### ISSUE THREAD

**Issue by fsettele** [Azure/api-management-developer-portal#792]
## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. Select an API with defined response type and Schema definitions - if not available create some demo data
2. Go to the API Details page of the API operation
3. Scroll down to the Example section and Schema definition
4. Choose on of the Code boxes with the json data
5. Click on "Copy"
6. Try to paste ist locally to a text editor

**Side note: The copy funtion works partially on the "Try it" page aka API Console. So, there it does the copy (only on Windows), but it forgets the line endigs. Tried that on Mac it doesen't even copy.**

## Expected behavior

The copied code is pasted in the text editor, with the same format and line breaks as seen on the source page.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

2.4.1

## Environment

 - Operating system: Windows 10 / mac OS Catalina
 - Browser: Safari, Chrome, Edge
 - Version: latest

**Comment by azaslonov** [comment]
Hi @fsettele, merging it with issue #527.
