### ISSUE TITLE
Setting password based on an invation does not work

### ISSUE THREAD

**Issue by fsettele** [Azure/api-management-developer-portal#793]
## Bug description

Setting password based on an invation does not work.

## Reproduction steps

In Azure portal > API Management
1. Ensure "Password and Username" provider on Identities
2. Go to Users, click on "Invite"
3. Fill out the required data espacially a valid e-mail where you have access

Wait for the mail, click on the link. Than you see the error on the Change-Password page.

## Expected behavior

No error and possibility to set the password for the invited user.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

2.4.1

## Environment

 - Operating system: Windows 10, macOS Catalina
 - Browser: Firefox, Edge
 - Version: latest

**Comment by ygrik** [comment]
Hello @fsettele 
Please republish your portal, we just deployed the update.
Please reopen this issue if the change password on Invite does not work.

**Comment by fsettele** [comment]
Hi @ygrik, thanks for the update. How can I detect a new version of the managed portal. The endpoint /internal-status-0123456789abcdef does receive the same codeversion after publish like yesterday:

```
{
    "Status": 200,
    "PortalVersion": "202007310622",
    "CodeVersion": "20200720072600",
    "Version": "0.13.1027.0",
    "RoleNumber": "Proxy.Host.WebRole_IN_0"
}
```

**Comment by mikebudzynski** [comment]
We currently don't surface the portal's version.

**Comment by fsettele** [comment]
Can confirm, that this does work now. Thanks.
