### ISSUE TITLE
Element descriptions and contol buttons are partially hidden

### ISSUE THREAD

**Issue by ilspiert** [Azure/api-management-developer-portal#794]
## Bug description

In designer mode, element descriptions and contol buttons are partially hidden when editing things.

## Reproduction steps

Go in designer mode, select the "Default" Layout and see the screenshot which shows some szenarios where the issue shows - highlighted in yellow:

**Szenario 1**
![Situation 1](https://user-images.githubusercontent.com/43613004/88932742-c6b9d080-d27e-11ea-85f1-32be8d46df69.png)
**Szenario 2**
![Situation 2](https://user-images.githubusercontent.com/43613004/88932762-cb7e8480-d27e-11ea-8dda-a6b08c9b5c39.png)
**Szenario 3**
![Situation 3](https://user-images.githubusercontent.com/43613004/88932772-ce797500-d27e-11ea-952e-fbb652ec5cde.png)

## Expected behavior

Place the description or elements to the visable area. e.g. For controls which belogs to a element, when they leave the visible are at the top, view it at the bottom. This make no sece for the + button - this one could then moved down with a offset, that it is fully visible.
In Szenario 3, it could help to move the system bar.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

2.4.1

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 84

**Comment by azaslonov** [comment]
Hi @fsettele, thanks for reporting the issue, we'll fix this.

**Comment by fsettele** [comment]
@azaslonov : already fixe? the issue is closed?

**Comment by azaslonov** [comment]
Not yet, sorry, probably hit the wrong button.

**Comment by azaslonov** [comment]
Fix for managed version is being rolled out.
