### ISSUE TITLE
Improper behavior of developer portal for the first click after sign 

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#795]
#577  Bug description

When the user login and clicks on product page its taking to sign page then redirecting to homepage, kind of dancing of pages. when clicks on api page its saying no apis are present. when clicks on sign out its taking to new page and content is page your looking for doesnt exist.

Note: this is happening only first click after sign in.

## Reproduction steps

1. Go to 'sign in' page
2. Click on 'sign in'
3. Click on 'Products' page
4. navigating to sing in page then to home page

## Expected behavior

It should show products in the products page.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @shashiguru, makes sense. Thanks for reporting the issue, we'll fix this.

**Comment by mikebudzynski** [comment]
The solution has been implemented, ETA for the roll-out is around 1 month.
