### ISSUE TITLE
Couldn't find Application menu in new developer portal (preview)

### ISSUE THREAD

**Issue by Sacratees** [Azure/api-management-developer-portal#80]
We are using the "Application" feature in the old developer portal. I couldn't find "Application" functionality in the new developer portal(preview)

Is that functionality is no more supported? If not supported what could be the alternative solution?

It will be great if all the existing features also available in the new  portal.

**Comment by azaslonov** [comment]
Hi @Sacratees, we don't know if we're going to implement "appllications" module (it wasn't very popular in the current portal), but we'll certainly document how to fairly quickly implement similar features.

**Comment by Sacratees** [comment]
Could you please provide any rest api reference to manage the applications?                 

Actually i am able to retrieve applications by GET method. https://management.azure.com/subscriptions/<subscriptionsId>/resourceGroups/<resourceGroup>/providers/Microsoft.ApiManagement/service/<service_name>/applications?api-version=2019-01-01 

But i am not able to create any applications by rest api model (PUT, POST is not supported). The above api only supporting HEAD, GET, PATCH.  

Can you provide some reference to create / update the application entity by programming model?

**Comment by mikebudzynski** [comment]
@Sacratees Full API Management REST API reference is located here: https://docs.microsoft.com/en-us/rest/api/apimanagement/ We do not expose APIs for managing applications.

Could you please describe what you use "Applications" for? What are you trying to achieve through this feature? Why do you need it?

**Comment by sdementen** [comment]
@mikebudzynski, do you mean the API to manage the database behind the new developer portal is also accessible via the APIM API rest interface?

**Comment by Sacratees** [comment]
@mikebudzynski, 

We are using "Applications" to showcase about the connected apps to the external world. 
As application details will be submitted by API consumer and API provider will publish it for the external visibility. 

We have a requirement to migrate the application details across different instance, So i am looking for some programming model to create an application entity in the new APIM instances.  

It will be really helpful for me, if any REST API is exposed to manage the applications. 
Why MS does not expose any programming model to manage applications though the feature available?

**Comment by mikebudzynski** [comment]
@Sacratees 

Your current use case is as follows:
1. API consumers submit a customer reference (real-world use case, "application") to API providers
2. API providers publish a customer reference on the developer portal

You are also looking for the following, which is currently not supported:
3. Migrate the published customer reference between the environments

Although the new developer portal doesn't have built-in "applications", you can achieve all three goals easily.

1. API consumers can submit their reference through means other than a built-in application management system (for example, a contact form, an email, ...).
2. API providers can create a new page or edit an existing page to contain customer reference.
3. The new portal supports dev-ops scenarios and migration between the environments. It's not documented yet, but there's a sample "migrate" script in the `/scripts` folder.

**Comment by mikebudzynski** [comment]
@sdementen Yes. Initial documentation is available at: https://github.com/Azure/api-management-developer-portal/wiki/Content-management-REST-API 

Every page, configuration item etc. can be exported through APIs.

**Comment by sdementen** [comment]
:+1: 
I could not find the /contentTypes under the doc https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01 so I was a bit confused.
