### ISSUE TITLE
Authorization header could be preserved while navigating between API operations

### ISSUE THREAD

**Issue by bkijonka** [Azure/api-management-developer-portal#801]
I have an OAuth Authorization defined for my API.
It works great - in "Try it" panel, I can choose the Authorization type, login and the Authorization header is being added to request Headers.

However, when I then switch to any other API operation, the Authorization header is gone. I have to select the Authorization type again. This way, the Authorization header is being added correctly, but I think it could be improved by preserving the header while switching between operations (to do it once).

How to set it up:

![2020-07-31_07h10_37](https://user-images.githubusercontent.com/33670141/89003594-7a16d980-d300-11ea-8ef4-037b1fc1a7f8.png)

![2020-07-31_07h14_24](https://user-images.githubusercontent.com/33670141/89003649-9ca8f280-d300-11ea-9446-782ac1eee638.png)

How to select Auth type in "Try it" panel;

![2020-07-31_07h24_00](https://user-images.githubusercontent.com/33670141/89003679-b21e1c80-d300-11ea-9d8f-356433b71ccf.png)

And then again, after I change an API operation:

![2020-07-31_07h42_14](https://user-images.githubusercontent.com/33670141/89003981-70da3c80-d301-11ea-9baf-d85a091b6409.png)

**Comment by azaslonov** [comment]
Hi @bkijonka, this issue has been fixed in #783. It is planned to be released to managed version by end of this week.
