### ISSUE TITLE
Product policy inheritance issue

### ISSUE THREAD

**Issue by maras2002** [Azure/api-management-developer-portal#804]
Hi,

We have policies on:
* operation level
* product level
* All APIs level (CORS here only)
In all with Inbound like: `<inbound><base /> (policy logic here) </inbound>` (of course without base in All APIs as it does not inherit further).

When we call the API from Product-A directly or from APIM Test  UI tab then we are all ok and all our policies are applied, as expected. But when we go to the same API operation under APIM Developer Portal and hit Try it then policy on Product level is no applied at all.

Calculated effective policy is as attached (sorry for formatting, its the calculation output, but its working for sure).

[policy calculated.txt](https://github.com/Azure/api-management-developer-portal/files/5011887/policy.calculated.txt)

What could be the issue here? Why Developer Portal bypass Product policy?

BTW: when we move policy logic from Product policy to e.g. operation or All operations level it then works as expected from Developer Portal, but we acutally need such policy on Product level.

Please assist.

**Comment by maras2002** [comment]
LIttle update. Product policy is also not applied when we directly call the API endpoint (not from Dev Poral nor from APIM UI Test tab).
So in summary Product Policy is applied only when doing Test from APIM UI tab. From Developer Portal and when calling API directly (e.g. curl) then does not take it inot account.

![image](https://user-images.githubusercontent.com/52015875/89119667-75912300-d4b0-11ea-8732-a646a14ef152.png)

**Comment by azaslonov** [comment]
Hi @maras2002, the product gets selected based on the subscription key. Are you sure you apply the right one?

**Comment by maras2002** [comment]
Hi @azaslonov , you are completely right. Gosh, I knew this... apologize. Didn't notice I was using the built-in for whole Service scope Subscription Key for my tests.

Issue to close. Working as expected.

**Comment by azaslonov** [comment]
Ok, glad it worked out for you :) Thanks for confirming it.
