### ISSUE TITLE
re-log-in still buggy

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#806]
## Bug description

This Issue has persisted for quite some time. After being automatically logged out (timeout) one can't re-log-in without closing the window where the DevPortal instance is opened.

## Reproduction steps

1. Log-in to one of your DevPortal instances
2. Wait for automatic log-out after a few minutes
3. Re-log-in with AAD
4. In most cases (not always) one can't log-in
5. Close window and open DevPortal instance again
6. log-in with AAD
7. See that it works now

## Expected behavior

After a timeout, you are able to login again without the need of closing the browser tab or window and that you are automatically routed to the last page you stopped working

## Is your portal managed or self-hosted?

Managed

## Environment

- Chrome: Version 84.0.4147.105

## Additional context

This issue is heavily related to #506 and #507 .
The timeout should be either configurable individually via the APIM portal or that the timeout happens not earlier than after 30 minutes.
It is essential for us at Siemens Healthineers that basic features work reliably when presenting content to customers.

**Comment by azaslonov** [comment]
Hi @ZarTrox, makes sense, we'll fix this. Thank you.

**Comment by ZarTrox** [comment]
Can there already be estimations made when this will be fixed and released?
Thanks in advance.

**Comment by ilspiert** [comment]
Hi @azaslonov,

I'm facing that issue again. Till a couple of days I make the experiance that I loose permissions to the Developer Portal (Designer) and User-facing very fast - even when I actively working on it. Around 30-60 min.
On Developer Portal (for User) when I loose permission and get redirected to login and then the loop starts. Here some steps for reproduction:

1. Take Edge 86.0.622.38
2. Setup a managed APIM with Username and password identity provider
3. Create a user with role Developer
4. Enable "Anonymous users > Redirect anonymous users to sign-in page"
5. Publish the portal
6. Access the published portal and login
7. Keep that side open for 60-90 mins
8. Click on any menu item

Now you should redirected to the login page and be in the loop.

When it helps, I can log data for you to analyse it better - you only need to give me some instructions how to get the relevant information for you.

**Comment by azaslonov** [comment]
Hi @ZarTrox, yep, found the issue. Will include the fix in one of the next releases.
