### ISSUE TITLE
HTML content injection in developer signup email

### ISSUE THREAD

**Issue by Saksi83** [Azure/api-management-developer-portal#808]
## Bug description
The application is rendering the user-controlled tags in an unsafe manner which may allow an attacker to inject malicious HTML code.

## Reproduction steps
1. Go to 'https://developer.bilinfo.net/signup' (any site would do)
2. Signup. At the email section enter the victims email and at the name section enter the HTML script mentioned below :-
 `{{ <img src=http://tinypic.com/i/tp-logo.jpg>}}` . Submit the form
3. Navigate to the corresponding email and you'll notice that the Name which was an HTML script gets rendered into the mentioned Email.

## Expected behavior
User input should be HTML-encoded at any point where it is copied into application responses. All HTML meta-characters, including < > " ' and =, should be replaced with the corresponding HTML entities (< > etc).
Application should filter meta characters or HTML tags provided from user input.

## Is your portal managed or self-hosted?
Managed

**Comment by azaslonov** [comment]
Hi @Saksi83, thanks for reporting this issue, we'll fix this.

**Comment by CosminLazar** [comment]
Hi guys, any thoughts on the ETA of fixing this issue?

**Comment by azaslonov** [comment]
The issue has been fixed on the backend. It will be deployed in the next 2-3 weeks.

**Comment by driis** [comment]
@azaslonov do you know if this has been deployed yet ? Thanks !

**Comment by azaslonov** [comment]
No, not yet, unfortunately. The release got delayed, I'll update with new ETA soon.

**Comment by CosminLazar** [comment]
@azaslonov can you please confirm that this issue has not been fixed with the release 2.5.0?

Just republished our portal and we still have the issue.
Are we getting closer to an ETA?

**Comment by mikebudzynski** [comment]
@CosminLazar No, it's not resolved in 2.5.0. This change will be rolled out with the backend upgrade - not developer portal release.

**Comment by CosminLazar** [comment]
@mikebudzynski thank you for the clarification! Will you guys make sure to drop a line here when the backend is released?

**Comment by mikebudzynski** [comment]
@CosminLazar This change will be included in the next backend release. You can monitor https://aka.ms/apim/releases for release notes.

**Comment by kasperbrandenburg** [comment]
@mikebudzynski im looking through the release notes (https://github.com/Azure/api-management-developer-portal/releases) and im not seeing this ticket id included anywhere. Is this InfoSec ticket scheduled for known future release?

**Comment by mikebudzynski** [comment]
It will be rolled out with the main API Management service release - you can monitor the link from my previous comment for release notes. We're still preparing for the roll-out.

**Comment by mikebudzynski** [comment]
@kasperbrandenburg Although we haven't mentioned it in the release notes yet, the fix is included in this release: https://github.com/Azure/API-Management/releases/tag/release-service-2020-10

**Comment by kasperbrandenburg** [comment]
Excellent, thank you.
