### ISSUE TITLE
Unable to find Home page content, home layout, default layout and footer changes in self hosted repository.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#809]
#Bug description

We are moving from managed version to self hosted version, as part of implementation we are unable to find home page content, home layout, default layout and footer content. so can you please help us how these static files are generating while doing publishing. if i want to do some changes on home page content how i can do through the code not from visual editor. 

Note: where can i find these changes in github repository.

## Is your portal managed or self-hosted?

 Self-hosted

**Comment by azaslonov** [comment]
Hi @shashiguru, if I understand your question correctly, you're looking for content management API. Please have a look here: https://github.com/Azure/api-management-developer-portal/wiki/Content-management-REST-API

**Comment by shashiguru** [comment]
Thanks for your quick response @azaslonov, I'm looking for changes related to layouts in self hosted repository, can you please help me where exactly find those in github repository.

**Comment by azaslonov** [comment]
Again, if I understand your question correctly, and we're talking about changing the content.

1. List layouts:
`GET /contentTypes/layout/contentItems`

2. Get a specific layout:
`GET /contentTypes/layout/contentItems/{layoutId}`

This will return a document like this:
```
{
  "id": "/contentTypes/layout/contentItems/default",
  "type": "Microsoft.ApiManagement/service/contentTypes/contentItems",
  "name": "default",
  "properties": {
    "en_us": {
      "title": "Home",
      "description": "Layout for the home page",
      "permalinkTemplate": "/",
      "documentId": "contentTypes/document/contentItems/7fe21f13-d1dd-00c1-c00e-a296b2cdcdca"
    }
  }
}
```

where you can grab `documentId` and use it to query the content itself.

3. Get layout content:
`GET /contentTypes/documents/contentItems/{documentId}`

This will return the layout content, which you can change and push it back:

4. Update layout content
`PUT /contentTypes/documents/contentItems/{documentId}`

Hope that helps.

**Comment by shashiguru** [comment]
@azaslonov, same things can be applied for self hosted too? I mean, layout changes in self hosted also can done through the content management REST API. Any alternate way for self hosted?

Note: I'm looking for changes in layouts, home page content and footer for self hosted, I cloned the github repository https://github.com/Azure/api-management-developer-portal

**Comment by azaslonov** [comment]
Yes, just a few details: All the developer portal content needs to be stored somewhere, that somewhere is the Content Management API. Whenever you change anything through the designer, it makes calls to that API. Then, when you publish the portal, it converts all the source content (stored in JSON format) into raw HTML/CSS/JS - your website (which you probably want to self-host). The publishing tools also use the same API to pull the content.

**Comment by mikebudzynski** [comment]
@shashiguru we have tutorials in the Wiki section of this repository. Specifically, you might be interested in these articles: https://github.com/Azure/api-management-developer-portal/wiki/Move-from-managed-to-self-hosted and https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services

You can change content programmatically by changing the JSON representation of the pages and using the REST API @azaslonov has linked. If you want to change the inner working of the portal, you need to edit source code provided in this repository.

If you need further assistance, please contact Azure support.

**Comment by shashiguru** [comment]
@mikebudzynski thanks for your response, i think you got my point. I want to change the source code for home page content and layout so where can I find those in source code of repository. @azaslonov thanks for your suggestions, I will check with Content management REST API.
