### ISSUE TITLE
Default subscription for new sign-ups & default names for subscriptions

### ISSUE THREAD

**Issue by hansukyang** [Azure/api-management-developer-portal#813]
Hi,

Wondering if there is a way to allow new sign-ups to be assigned a default subscription (e.g. 'Starter') and also the subscription names to be automatically assigned rather than developers having to enter new ones? Most just end up using a variation of the product name anyhow.

Thank you,

**Comment by mikebudzynski** [comment]
Currently there's no way to do that. We have a plan to introduce administrative events in API Management, so you'll be able to create your own integration pipeline based on the user sign-up event. We don't have a precise ETA at this moment, but it's not going to become available sooner than in a few months. You can monitor updates at https://aka.ms/apimupdates
