### ISSUE TITLE
Media files are missing in local host visual editor.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#816]
#811 Bug description

We moved from managed to self hosted recently, we are unable see any media files for visual editor in local host(local). i think we are missing some reference for media files in local repository. can you please help us that which media references are missing. please check attached screenshot for more details.

## Is your portal managed or self-hosted?
Self-hosted

## Additional context

![image](https://user-images.githubusercontent.com/30490543/89379264-1d0d9000-d713-11ea-8425-6fc091386a4f.png)

**Comment by mikebudzynski** [comment]
You need to reference the storage account of the managed portal, as described in our documentation: https://github.com/Azure/api-management-developer-portal/wiki/Move-from-managed-to-self-hosted
