### ISSUE TITLE
Where to look source code for visual editor changes before publishing

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#817]
## Bug description
.Hi there, if we do some changes from visual editor local(local host), is there any way we can see the changes before publish into the publish endpoint. if yes, where can i see find those changes. as we are looking for the source for changes done through the visual editor.

**Comment by mikebudzynski** [comment]
The `npm publish` command generates the static files in the `dist/website` folder. You can preview them on your local machine, before you publish them to external users (for example, before you upload them to a Storage Account).

**Comment by shashiguru** [comment]
Thanks for response @mikebudzynski, I mean to say before npm run publish where the changes will store. After doing npm start I can able to visual editor in local host so if can do some changes through that, where exact I can see those changes before doing npm run publish.

**Comment by mikebudzynski** [comment]
When you make changes in the visual editor, the administrative interface of the developer portal saves them in your API Management service. The `npm publish` command generates static files on your machine based on this content data. You can preview those files locally before uploading them to your hosting service (and, therefore, before making them visible to the portal visitors).

**Comment by shashiguru** [comment]
Is there any chance I can see them in storage account that is associated with APIM, through the storage explorer. As I can see content container and websites container in built-in storage account after publish of managed version.
