### ISSUE TITLE
Can i publish self hosted developer portal in existing APIM developer portal publish endpoint

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#818]
## Bug description

Hi there, as per article of self hosted developer i need storage account with static website enabled. without using external storage account can i publish self hosted developer portal changes into existing APIM developer portal publish endpoint.

**Comment by mikebudzynski** [comment]
No, you can't use the managed portal publishing mechanism to publish your self-hosted portal. In the self-hosted portal, the `npm publish` command generates static files, which you need to host in the solution of your choice. In documentation, we recommend Azure Storage account for hosting, but you can choose any method you prefer.

**Comment by shashiguru** [comment]
Great!! thanks for response @mikebudzynski.
