### ISSUE TITLE
Not able to connect to different domain name APIM

### ISSUE THREAD

**Issue by anjusharma17** [Azure/api-management-developer-portal#82]
Hi, we are not able to connect to different domain name than azure-api.net. And getting ETIMEDOUT error.

![ETimeOut Error](https://user-images.githubusercontent.com/17688551/59589668-15062180-9108-11e9-8687-c886e960b994.png)

I have followed all the config steps, let me know if need to do some other changes as well.

**Comment by azaslonov** [comment]
Hi Anju,
On your screenshot, I see that you still trying to call [service].management.azure-api.net. I guess you wanted to specify your custom hostname for management endpoint?

**Comment by anjusharma17** [comment]
Hi Alexander,

**From where we can find out the management_endpoint for custom domain, can you please share the updated links?**

In the generate.bat file, its is given that set management_endpoint="< service name >.management.azure-api.net"
So for custom domain, it could not be xyz.management.azure-api.net as per your response, where xyz is the service name. 
Thus I set the management_endpoint="apim-portal-nonprod.dname.com", also tried with "apim-portal-nonprod.management.dname.com", but did not worked.

![custom domain1](https://user-images.githubusercontent.com/17688551/59655941-a41f4200-91b9-11e9-8cf9-a127ffced649.png)
The above error is thrown at the following code -> resolve(JSON.parse(data)), in generate.js file.

![custom domain2](https://user-images.githubusercontent.com/17688551/59655943-a4b7d880-91b9-11e9-8e67-27f9a48bacbd.png)

![portal](https://user-images.githubusercontent.com/17688551/59656012-e2b4fc80-91b9-11e9-859e-a3b133ece333.png)

Please suggest from where we can find out the management endpoint for custom domain?

**Comment by azaslonov** [comment]
Hi Anju, the hostname for your management endpoint should be exactly as you defined it in Custom domains section:

![image](https://user-images.githubusercontent.com/2320302/59708499-bdc08980-91b9-11e9-93a0-5ba850ed2345.png)

![image](https://user-images.githubusercontent.com/2320302/59708480-b4372180-91b9-11e9-8818-ab1107a589ca.png)

Just in case, if you didn't setup a custom domain for management API, that means your default `<service>.management.azure-api.net` timed out by a different reason (i.e. VNET configuration). I'll be able to check that if you send me your service name to alzaslon@microsoft.com

**Comment by anjusharma17** [comment]
Thanks Alexander, it is working now

**Comment by anjusharma17** [comment]
Hello Alexander, on local it worked
From azure Portal, facing two issues further to this:
1) Whenever we are clicking on New Developer Portal(Preview) the link is not working. However, some days back it was working.

![Portal not working](https://user-images.githubusercontent.com/17688551/59755300-5122b900-92a5-11e9-9a77-0b25bd37357b.png)

2) The same kind of issue persist, when we sign up from our APIM, which we have published into our storage account. We get one sign up link to confirm in the email account. The same error screen appears when we try to click on confirmation link.

Error: This site can’t be reached xyz.developer.azure-api.net’s server IP address could not be found.

Let us know how to handle this for custom domain or are we missing any configuration for this?
It is a custom domain APIM, but i am not sure why the error related to azure-api.net is coming.

**Comment by azaslonov** [comment]
Anju, it seems like I'll need APIM service name to help you. Please email me at alzaslon@microsoft.com.

**Comment by anjusharma17** [comment]
Hi Alexander, i have mailed you the required information. Please check.

**Comment by azaslonov** [comment]
Hi Anju,
Looking at your service it seems to be VNET-related issue. We'll update respective documentation to help you resolve it. Please use this item for tracking it: #97
