### ISSUE TITLE
Changes to be done when we add new page in self hosted developer portal.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#820]
## Bug description

Hi there, so sorry to asking this question. I was struggling to add new page in source code of self hosted developer portal. Could you please help me what are the changes to be done as part of new page addition. I did some changes but still unable to generate static files after publish.

Note: im doing changes to self hosted repository that is cloned from GitHub.

## Is your portal managed or self-hosted?

Self-hosted

**Comment by mikebudzynski** [comment]
Please, contact Azure support.
