### ISSUE TITLE
Signout redirect issue in "src/routing/signOutRouteGuard.ts"

### ISSUE THREAD

**Issue by chetan341** [Azure/api-management-developer-portal#825]
we have two instance for developer environment and uat environment. But since last few days we are facing signout issue in developer environment. After signout page should redirecting to "https://xxxxxxdv.developer.azure-api.net/signout"  instead of "https://xxxxxxdv.developer.azure-api.net/#signout". In result we are getting below error,
![APIM dev2](https://user-images.githubusercontent.com/8189760/89867875-78d29000-dbcf-11ea-8b87-066dd86a1922.jpg)

When we did further investigation we found that there is issue with  "src/routing/signOutRouteGuard.ts" please check cause of error below,
![APIM dev1](https://user-images.githubusercontent.com/8189760/89868863-1bd7d980-dbd1-11ea-9ac3-508883ddb4a8.jpg)
If you see above redirection code is redirecting page is "/signout" page, which never exists. Hence we are getting "Page you'er looking for doesn't exist."

For confirmation we have check our uat environment which is working as expected, please check below
![APIM dev3](https://user-images.githubusercontent.com/8189760/89868731-eaf7a480-dbd0-11ea-81fa-a691ca4aea67.jpg)

If you see above line of code is redirecting page to home page.

**Comment by azaslonov** [comment]
Hi @chetan341, this issue has been fixed in the last release. Please re-publish the portal to pick up changes. Feel free to re-open if the issue still exists.

/cc: @ygrik

**Comment by chetan341** [comment]
Thanks @azaslonov. I have checked and it is working fine after republish the portal.

/cc: @ygrik

**Comment by azaslonov** [comment]
Great! Thanks for confirming it.
