### ISSUE TITLE
Posting to /publish endpoint results in Resource not found.

### ISSUE THREAD

**Issue by mrcunninghamz** [Azure/api-management-developer-portal#826]
## Bug description
I have a hosted developer portal.

When I use postman to Post to the `publish` endpoint with a token in the Authorization header. I get a 200 response, but now my developer portal shows "Resource Not Found"

## Reproduction steps

1. Enter URL in postman
2. Set Post
3. Enter Authorization key and value (token) ex: "SharedAccessSignature integration&2020..."
4. Click Send
5. Open incognito window to developer portal and notice "Resource Not Found." message.

## Expected behavior

I should be able to see the developer portal, specifically the login page.

## Is your portal managed or self-hosted?

Managed 

## API Management service name

mm-apim-km-001

## Environment

 - Operating system: MacOs
 - Browser: Chrome
 - Version: Version 84.0.4147.105 (Official Build) (64-bit)

## Additional context

![image](https://user-images.githubusercontent.com/1489559/89922087-2dff4b00-dbc4-11ea-9525-b5a42b1a62da.png)

Results:
![image](https://user-images.githubusercontent.com/1489559/89922362-8afb0100-dbc4-11ea-8ca2-9f32059384a4.png)

I noticed this as a result when running the migrate.js script... It migrates the content just fine, but I really would like to auto publish... which seems to be basically Posting to the `publish` endpoint. So I used Postman to check if I am missing an error, but i don't get an error.

**Comment by shashiguru** [comment]
Its happening with us too, publish REST API is unable to generate static files in websites container in APIM storage account.

**Comment by LockTar** [comment]
We have the same problem as well! We are doing a migration from our api management instances and everything is working except migrating the developer portals....

**Comment by mikebudzynski** [comment]
We'll investigate the problem.

**Comment by mrcunninghamz** [comment]
> We'll investigate the problem. Is publishing through the Azure portal and the developer portal's administrative interface working as expected?

yes through the azure portal and developer portal's interface works.

**Comment by azaslonov** [comment]
Hi everyone, there is an issue in backend (we're working on the fix), it doesn't accept `integration` tokens. To work this around please generate admin token:
```
PUT /users/1/token
{
    "keyType" : "primary",
    "expiry": "2020-09-15T00:00:00"
}
```

**Comment by mrcunninghamz** [comment]
> Hi everyone, there is an issue in backend (we're working on the fix), it doesn't accept `integration` tokens. To work this around please generate admin token:
> 
> ```
> POST /users/1/token
> {
>     "keyType" : "primary",
>     "expiry": "2020-09-15T00:00:00"
> }
> ```

It seems to work, just a note for anyway else you need to add `SharedAccessSignature` in front of the token so it looks like this in the authorization header `SharedAccessSignature <Token>`

**Comment by mikebudzynski** [comment]
The release is currently being rolled out. You can read the release notes at: https://github.com/Azure/API-Management/releases/tag/2020-09

**Comment by geologyrocks** [comment]
In case anyone comes across this while trying to incorporate it into an Azure YAML pipeline deployment, below is the format you'll need.  Hopefully this will save you the time we spent on it! :
```
# In an Azure CLI task: Get integration token 
$integrationToken = az rest --method post --uri https://management.azure.com/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.ApiManagement/service/$(apiManagementName)/users/integration/token?api-version=2019-12-01 --body "{\`"keyType\`":\`"primary\`", \`"expiry\`":\`"2020-11-15T00:00:00\`"}" | ConvertFrom-Json
# Use two dollars to get out the value and then set the variable
Write-Host ("##vso[task.setvariable variable=integrationTokenVar]$($integrationToken.value)")

# In a separate Azure Powershell task: Publish portal changes
Invoke-WebRequest -uri https://$(apiManagementName).developer.azure-api.net/publish -Headers @{"Authorization"='$(integrationTokenVar)'} -Method POST
```
