### ISSUE TITLE
Clicking on the Send button does not auto scroll to see the triple bubble loading or results. 

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#827]
## Bug description

When using the try it functionality on an operation, the Send button will change the text to "Sending...", but the triple bubble of the loading animation will not be seen because the page does not auto scroll into view. When the results are complete, you wont see it there is something until you vertical scroll

There is no scroll into view
![2CDB40BD-1DAC-4A44-9736-7F884F995A38](https://user-images.githubusercontent.com/65634611/89955489-fbffe000-dbe7-11ea-97af-b696123e590d.GIF)

Loading animation that is missed because page did not scroll
![DA5F9997-D5FB-411B-ABD6-F41945FC90BA](https://user-images.githubusercontent.com/65634611/89955534-189c1800-dbe8-11ea-8795-613997ad29a9.GIF)

## Reproduction steps

1. Go to Echo API
2. Click on the First Operation in the list "Create Resource"
3. Click on "Try It" button
4. Scroll down to "Send" button
5. Click "Send"

Page should auto scroll to show the loading animation. Once complete, the page should auto scroll enough to see the response header. 

## Is your portal managed or self-hosted?

Self-hosted 

## Release tag or commit SHA (if using self-hosted version)

2.4.1

## Environment

 - Operating system: Windows 10
 - Browser: Chromium Edge

**Comment by azaslonov** [comment]
Hi @VWACBrick, makes sense, we'll improve this.
