### ISSUE TITLE
Migrate scripts making developer portal to resource not found

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#829]
## Bug description

Hi there, migrate script to migrate from one instance to another making publish endpoint to resource not found. Is there any changes happened to any api-versions that makes to break the publish endpoint.

## Expected behavior

After publishing through the migrate.js, developer portal should available.

## Is your portal managed or self-hosted?

Managed

**Comment by michaeltnguyen** [comment]
are there any error messages when you run migrate.js?

**Comment by narlavinil** [comment]
No error messages. This was working until last 2 days. We are able to migrate if generate shared access token from portal and use that token directly. But we are getting resource not found when sharedAccess token is generated from the code present in migrate.js file.

**Comment by mikebudzynski** [comment]
Merging with #826
