### ISSUE TITLE
Can't add a custom Product: Subscribe form

### ISSUE THREAD

**Issue by yashwantsahu05** [Azure/api-management-developer-portal#83]
**Describe the bug**
Unable to generate Apim-Subcription-Key to access API,

**To Reproduce**
1. Go to New APIM developer Portal
2. Click on Product Manu

Product and API is listed but unable to find any subscribe option to subscribe available product.  

**Expected behavior**
Require subscribe option to generate APIM subscription key. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51317617/59604159-fb290680-9128-11e9-8edd-76ff4499613b.png)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser : Chrome

**Comment by azaslonov** [comment]
Hi @yashwantsahu05,
You're right, we forgot to add "Product: Subscribe" widget to Products page in our default template. We'll fix it, but you can add it yourself using "Add widget" dropdown:
![image](https://user-images.githubusercontent.com/2320302/59619671-ed02c800-90df-11e9-8007-5b5bab6632ae.png)

**Comment by sdementen** [comment]
Hi @azaslonov 

I am adding the "Product: Subscribe form" in the products page, yet it doesn't add the widget in the page. When I am adding the widget, I see for a second a text "Please select a product" and then I am back to the page in its original state (no widget).

**Comment by mikebudzynski** [comment]
@sdementen Thanks, I can confirm the bug. We'll work on a fix.

**Comment by mikebudzynski** [comment]
We'll be rolling out portal updates in the coming days. Please, reopen the issue if problem persists.
