### ISSUE TITLE
OAuth2 access token is not regenerating once it's expired in the Managed developer portal

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#832]
Bug description

OAuth2 access token is not regenerating once it's expired in the Managed developer portal. There is no option to regenerate the access token. The only option is to close the browser and open again and load the developer portal.
Also not getting the details of when the token will be expired.

Reproduction steps

1. Load the developer URL and navigate to Try it window
2. Select the "Authorization Code" option from OAuth2 dropdown
3. Call some operations and wait for the access token to expire (about 20 mins).
4. Try to call any operation after the access token expired(after 20 mins), we should get "expired_token" error message.
5. Try to regenerate the access token(refresh the page, select different API, select different operation)
6. Check the access token is regenerated or not

Expected behavior
1. The access token should be regenerated if we select "No Auth" option and again select "Authorization Code"
2. The access token should be regenerated if we try to call different API/Operations
3. The access token expiration time details have to be displayed

Is your portal managed or self-hosted?

Managed

 Environment

 - Operating system: Windows
 - Browser: Google Chrome, Firefox

Additional context

The access token is getting regenerated as we are expecting in the Legacy developer portal.
Also "Access token expires on" details are displaying in the Legacy portal.

**Comment by azaslonov** [comment]
Hi @dhandapanitrimble, makes sense, we'll come up with something.

**Comment by maras2002** [comment]
up, we also noticed the same issue and would approeciate a quick fix.

**Comment by azaslonov** [comment]
Hi everyone, with the merged fix, a user will be able to reset token. Also, when it gets fetched from the session storage, the console will now check for the expiration date (if this is a parsable JWT token) and clear it, if expired.
