### ISSUE TITLE
Support disabling developer portal

### ISSUE THREAD

**Issue by johndowns** [Azure/api-management-developer-portal#833]
Please consider adding an option to completely disable the developer portal. For example, customers who have their own custom portal will not want to have a platform-provided portal accessible.

Currently there are some workarounds (see below), but it would be even better to have the option to not have the developer portal made available by the platform.

## Workarounds

1. For new API Management instances, the developer portal is not published by default. If a customer does not publish it themselves then it is effectively disabled. However, if a customer publishes it (intentionally or accidentally) there is no supported way to unpublish it.

2. Customers can avoid mapping a DNS name to the developer portal hostname provided by the platform. This does not prevent someone from figuring it out, but it makes it much less likely they will do so.

3. Customers can configure the developer portal with the following two settings, which together have the effect of making the developer portal unusable:
   * Disable sign-up by removing all identity types (this can be done in the Azure portal - choose the API Management instance, then click Identities and remove each identity type).
   * Force anonymous users to be directed to the sign-up page (this is done in the same part of the Azure portal).

**Comment by sdg002** [comment]
We would like an easy way to un-publish/disable the Developer portal. This was flagged via a security audit. 

Any updates?

**Comment by sdg002** [comment]
@azaslonov Thanks for the MS support idea. 

Is there any **REST** end point which will tell me whether Administrative Portal has been turned on ?
If there is one, then it would be very helpful to us in creating security Alerts.

**Comment by azaslonov** [comment]
@sdg002, unfortunately no, that's why we still rely on MS Support.

**Comment by DavidDBD** [comment]
This seems to be dragging on for some time, we have also had a security audit done which has highlighted issues with the dev portal so we just want to switch it off.

It doesnt seem like its something that should be that difficult to implement?

**Comment by azaslonov** [comment]
@DavidDBD, it's not difficult to implement, it's just a matter of priorities. It this is urgent, feel free to either contact MS support or send your service name to apimportalfeedback@microsoft.com, we'll disable it from our end.

**Comment by DavidDBD** [comment]
I understand that its a matter of priorities but people have been asking for this since 2019, quite a few of us are asking for it to be disabled because pen tests have flagged issues with it, I'd hope that would bump it up the list a bit :)

I've passed the email address on to my client who will be requesting that its disabled, Thanks for the help.

**Comment by ygrik** [comment]
Now the legacy developer portal can be disabled with REST API (https://learn.microsoft.com/en-us/rest/api/apimanagement/current-preview/api-management-service/create-or-update?tabs=HTTP#apimanagementcreateservicewithdeveloperportal)

Example to disable the legacy portal

```
PATCH https://management.azure.com/subscriptions/ {subscription name} /resourceGroups/{rg name}/providers/Microsoft.ApiManagement/service/{service name}?api-version=2023-03-01-preview HTTP/1.1
content-type: application/json 
Authorization: Bearer ...

{
  "properties": {
    "legacyPortalStatus": "Disabled"
  }
}
```

We are working to enable this functionality in API Management Azure portal

**Comment by nagendramishr** [comment]
> @DavidDBD, it's not difficult to implement, it's just a matter of priorities. If this is urgent, feel free to either contact MS support or send your service name to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com), we'll disable it from our end.

Is this still the recommended way to turn off the portal?  We have a public APIM with private endpoints for the gateway and want to enable access to the developer portal via private endpoint, but disabled on the public interface.

**Comment by erwinkramer** [comment]
@nagendramishr i have the same scenario. An alternative is making sure you never publish it, and then self-host the developer portal, then on your self-hosted portal resource (storage account), you can lock it down as well with private endpoint.

**Comment by sy-huss** [comment]
2025, and there is still no way for us to turn of a Portal. What if there was no desire to have an API portal because APIM was used as an internal gateway? This failed a security audit, we've had to resort to the hacks to remove the Portal.

**Comment by ygrik** [comment]
@sy-huss 
you can disable portal by utilizing the Update REST API for the API Management Service. Please refer to the following documentation for detailed instructions: 
[Api Management Service - Update - REST API | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/apimanagement/api-management-service/update?view=rest-apimanagement-2023-09-01-preview&tabs=HTTP)
To disable the portal, set the properties.developerPortalStatus to Disabled.
