### ISSUE TITLE
Add support for Application Insights in the managed portal

### ISSUE THREAD

**Issue by JanneMattila** [Azure/api-management-developer-portal#835]
In hosted developer portal you do not see insights about end user interactions with the portal. **And** you do not want to use self-hosted developer portal just to enable this scenario.

Possible solutions:

- Add support for App Insights
- Add support for adding `script` elements to the head of the page (enables adding small js snippet to enable preferred monitoring solution)

**Comment by mikebudzynski** [comment]
@JanneMattila - what insights are you specifically looking for?

You can plug-in Google Analytics to your portal (both managed and self-hosted): https://github.com/Azure/api-management-developer-portal/wiki/Integrate-Google-Tag-Manager

We also have plans for enhancing the developer ecosystem reporting in API Management - but that's further on the roadmap.

**Comment by JanneMattila** [comment]
I was hoping to use [App Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview) but did not find any documentation how to do that. For customers it makes sense to use Azure services instead of others (common deployment story with ARM, defined geo-locations etc. benefits).

**Comment by mikebudzynski** [comment]
Makes sense. Are you looking for any specific telemetry or just general telemetry App Insights provides?

**Comment by JanneMattila** [comment]
Starting off with basics but then many things would follow:

- How many people enter "Sign Up" page vs. actual sign up rate
- If you have `n` APIs then which of those are most interesting from the doc page point of view

etc.

**Comment by mikebudzynski** [comment]
> If you have n APIs then which of those are most interesting from the doc page point of view

What do you mean by "the most interesting"? How would you measure it?

**Comment by JanneMattila** [comment]
Oh sorry let me clarify this:

> If you have n APIs then which of those are most interesting from the doc page point of view

By that I mean that if people are viewing different APIs the urls are something like this:

`https://devportal/api-details#api=echo-api&operation=modify-resource`

`https://devportal/api-details#api=products&operation=get`

So technically they are in the "same page" (api-details) but of course as provider of the APIs you would like to see how many have viewed the `api=products`. 

If you would get these into App Insights you could create KQL queries and enable you to analyze this information. Hopefully this made more sense.

**Comment by azaslonov** [comment]
In the last release, we added basic integration for App Insights, which currently logs just generic events. The next step will be emitting specific events across dev portal functionality.

Integration instructions can be found here:
https://github.com/Azure/api-management-developer-portal/wiki/Integrate-Application-Insights

**Comment by mikebudzynski** [comment]
We plan to let you plug-in Application Insights via the Azure portal interface. ETA is 1-3 months.

For emitting more specific events, we plan to work on this in the first half of 2021.
