### ISSUE TITLE
You cannot use browser's 'back button' in some cases

### ISSUE THREAD

**Issue by orlowski-ra** [Azure/api-management-developer-portal#838]
## Bug description

The 'back button' seems to be disabled while checking the description of available endpoints. This has a negative impact on user experince

## Reproduction steps

1. Go to 'APIs'
2. Click on 'any item on the list'
3. Try to use the 'back button'
4. Fail trying

## Expected behavior

 You should be able to go back to the previous page.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows
 - Browser: Google Chrome

**Comment by azaslonov** [comment]
Hi @orlowski-ra, this has been fixed in the last release. Please re-publish the portal to pick up changes. If still doesn't work for you please send us your service name to apimportalfeedback@microsoft.com.
