### ISSUE TITLE
is there any format requeired when we stick content from other page?

### ISSUE THREAD

**Issue by 123Jun321** [Azure/api-management-developer-portal#839]
## Bug description

hi  team,

we just found the page can't be load successfully after we stick the content from another page in the text box.

## Reproduction steps

1. just  create a new page 
2. copy anything not only contains words(like a hyperlink with a tag) from other page and stick it in the text box of the new page
3. save and go to another page, then return
4. you should see the error "Oops, something went wrong" and the page can't be loaded
## Expected behavior

We found it will be fine if the content you stick just contains words only so we want to make sure is there any format limit what we put in the textbox?

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment]
Hi @123Jun321, unfortunately, I could not repro this (tried many times with hyperlink that contains anchor and without it). Do you mind provide more precise step describing your link parameters, or better record a short video?

**Comment by 123Jun321** [comment]
[2020-08-21 16-34-18.zip](https://github.com/Azure/api-management-developer-portal/files/5107768/2020-08-21.16-34-18.zip)

hi, @azaslonov Thanks first.
Sure, I have uploaded a short video showing it.

**Comment by 123Jun321** [comment]
Hi all, is there any update?

**Comment by azaslonov** [comment]
Hi @123Jun321, sorry for delayed response. This issue has been fixed some time ago. Please feel free to re-open shall you still experiencing this issue.
