### ISSUE TITLE
Not able to run Developer portal 

### ISSUE THREAD

**Issue by anjusharma17** [Azure/api-management-developer-portal#84]
I am able to successfully execute https://github.com/Azure/api-management-developer-portal/wiki/self-hosting-the-portal till step 3. Also, when i run npm start, the build gets complied successfully, however, due to some issues it is not running on the browser.

Build Succeeded: 
![image](https://user-images.githubusercontent.com/17688551/59605681-ed758000-912c-11e9-8b4f-0f1bac05a27e.png)

Not running on Google Chrome:
![Exceptions](https://user-images.githubusercontent.com/17688551/59605942-94f2b280-912d-11e9-82c8-2585759cf221.png)

Please help me with this.

Note: The same configuration is working on another machine but on my system it is not working.

**Comment by azaslonov** [comment]
Hi Anju,

Looks like in your configuration you specified portal's (<yourservice>.portal.azure-api.net) endpoint instead management API (<yourservice>.management.azure-api.net)
