### ISSUE TITLE
Step 6 of 'self hosting the portal' giving error

### ISSUE THREAD

**Issue by anshul-kumar-agl** [Azure/api-management-developer-portal#841]
I am following https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal and at step 6 getting below error.

Error: Unable to complete publishing. Error: Could not get object 'locales'.
    at MapiObjectStorage.<anonymous> (C:\Users\...\Documents\agl_repo\api-management-developer-portal\dist\publisher\index.js:197196:23)
 
Kindly help out please.

**Comment by azaslonov** [comment]
Most likely the issue with authentication. Please check pulblish.config.json file and make sure all the fields provided correctly.

**Comment by anshul-kumar-agl** [comment]
> Most likely the issue with authentication. Please check pulblish.config.json file and make sure all the fields provided correctly.

I have checked all entries. I can see some files inside container, means at least connectivity to blob is good.

**Comment by azaslonov** [comment]
Ok, can you please copy the content (with obfuscated service name, token and storage account)?

**Comment by anshul-kumar-agl** [comment]
> Ok, can you please copy the content (with obfuscated service name, token and storage account)?

{
  "managementApiUrl": ".....",
  "managementApiVersion": "2018-06-01-preview",
  "managementApiAccessToken": "SharedAccessSignature .....",
  "blobStorageContainer": "content",
  "blobStorageConnectionString": "DefaultEndpointsProtocol=.....",
  "environment": "publishing",
  "useHipCaptcha": false
}

**Comment by MassimoC** [comment]
I got this error tons of times: your managementApiAccessToken is not ok

**Comment by chinmayv84** [comment]
As per this documentation https://docs.microsoft.com/en-us/rest/api/apimanagement/apimanagementrest/azure-api-management-rest-api-authentication, management access token can be generated in two formats
Format 1: SharedAccessSignature uid=53dd860xxxxxxxxxxxxxxxxxxxxxxx
Format 2: SharedAccessSignature integration&201808020500&axxxxxx

Self-hosted portal only supports Format 2 currently.

If we use Format 1 in configuration file, I noticed same error. error generated from parseSharedAccessSignature methods from [accesstoken.ts](https://github.com/Azure/api-management-developer-portal/blob/352dacb4ba4440c46bdd4870201912da5feb708a/src/authentication/accessToken.ts)

**Comment by riordanp** [comment]
Hi @AElharouny @azaslonov , did you ever manage to solve this problem? I have just run into it also when trying to publish the portal. I have gone through some of the same diagnostic steps. My `/contentTypes/` call lists 8 different content types, but 'locale' or 'locales' is not among them, I believe this is why there is a 404 error. 

I am using API version 2019-12-01 and portal version 2.7.0. If anyone can post the schema for the 'locale' content type, I believe I can recreate it to solve the issue.

Thanks

**Comment by azaslonov** [comment]
Looks like I was able to reproduce it, I'm investigating.

**Comment by riordanp** [comment]
Works great, thanks for the quick fix @azaslonov

**Comment by adamcastle** [comment]
Hi,

I am still getting this issue using 2.7.0

I have noticed config.design.json defaults like the following structure.
{
    "environment": "development",
    "managementApiUrl": "https://<service-name>.management.azure-api.net",
    "managementApiAccessToken": "SharedAccessSignature ...",
    "backendUrl": "https://<service-name>.developer.azure-api.net",
    "useHipCaptcha": false
}

This is different as per the instruction, should it include "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/<service-name>" ?

I have tried with and without this but are still getting the same issue.

```
Error: Unable to complete publishing. Error: Could not search object 'locales'. Error: Resource not found: https://XXXXXX.management.azure-api.net/subscriptions/sid/resourceGroups/rgid/providers/Microsoft.ApiManagement/service/sid/contentTypes/locales/contentItems/en-us?$skip=0&$top=50&api-version=2019-12-01
    at MapiObjectStorage.<anonymous> (C:\src\apiPortal2\api-management-developer-portal\dist\publisher\index.js:189287:23)     
    at Generator.throw (<anonymous>)
    at rejected (C:\src\apiPortal2\api-management-developer-portal\dist\publisher\index.js:188934:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at SitePublisher.<anonymous> (C:\src\apiPortal2\api-management-developer-portal\dist\publisher\index.js:74319:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\src\apiPortal2\api-management-developer-portal\dist\publisher\index.js:74285:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```


Cheers,
Adam.

**Comment by riordanp** [comment]
Hey @adamcastle I don't believe these changes have been tagged for release yet, it will probably be 2.7.1 but in the mean time I merged the master branch into my own portal repo

**Comment by azaslonov** [comment]
That's right, it's not tagged. Just please pull the latest version from master.

**Comment by Hari35** [comment]
@azaslonov I'm getting below error using the release tag 2.16.0
consoleLogger.ts:23 Unhandled rejection: Error: Resource not found: https:/**instance**/subscriptions/sid/resourceGroups/rgid/providers/Microsoft.ApiManagement/service/sid/contentTypes/page/contentItems/**id**?api-version=2021-04-01-preview
    at MapiClient.createMapiError (http://localhost:8080/editors/scripts/paperbits.js:209366:24)
    at MapiClient.<anonymous> (http://localhost:8080/editors/scripts/paperbits.js:209348:32)
    at Generator.next (<anonymous>)
    at http://localhost:8080/editors/scripts/paperbits.js:209189:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/services/mapiClient.ts.__awaiter (http://localhost:8080/editors/scripts/paperbits.js:209185:12)
    at MapiClient.handleError (http://localhost:8080/editors/scripts/paperbits.js:209333:16)
    at MapiClient.<anonymous> (http://localhost:8080/editors/scripts/paperbits.js:209328:28)
    at Generator.next (<anonymous>)
    at http://localhost:8080/editors/scripts/paperbits.js:209189:71
