### ISSUE TITLE
Auth0 - Get the access token

### ISSUE THREAD

**Issue by simonTTIS** [Azure/api-management-developer-portal#842]
Hi,

It seems that the new portal doesn't working well with auth0, I can't get an access token.

Here are the settings :
- On APIM : OAuth 2.0 - Authorization endpoint URL : https://<URL>/authorize?response_type=code&client_id=<CLIENT_ID>&redirect_uri=<REDIRECT_URI>&scope=email&audience=<AUDIENCE>&state=xyzABC123
- On Auth0 : Applications - Settings - Allowed Callback URLs : https://<URL>/signin-oauth/code/callback/<NAME>
- On the new portal , the url generated : https://<URL>/authorize?response_type=code&client_id=CLIENT_ID&redirect_uri=<REDIRECT_URI>&scope=email&audience=<AUDIENCE>&state=xyzABC123?client_id=<CLIENT_ID>&redirect_uri=<REDIRECT_URI>&scope=&response_type=code&state=xyzABC123
And the error from auth0 : Oops!, something went wrong.

Did I set something wrong ?
The url generated by the new portal is not correct where some parameters appears twice, and the scope parameter is empty as well.

Thank you

**Comment by simonTTIS** [comment]
It's fine, on the new portal, the Authorization endpoint URL has be : https:///authorize (without parameters)

**Comment by azaslonov** [comment]
Hi @simonTTIS, glad you figured it out, and thanks for confirming.
