### ISSUE TITLE
Scripts for easily backing up and restoring the portal

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#848]
## Bug description

When customizing the portal it is impossible to undo a change once you have saved it. That makes it risky to work with it. There are two scripts that exist that let you save the customizations; migrate.js and capture.bat. However, capture.bat does not save the media files and migrate.js uses hard coded paths and requires information about a destination portal. Therefore it would be great if there was a script for easily backing up the customizations, preferably with an option to add a timestamp to the file name and the folder name.

If you are able to specify the paths you would be able to put the files directly in a folder where it may be connected to a repository.

Also, an accompanying script for restoring/bringing up a portal using the saved files would be great. That would enable it to work with continuous delivery.

**Comment by azaslonov** [comment]
Hi Erik, yes, this question pops up from time to time. I think it correlates with #650.

**Comment by ErikMogensen** [comment]
Yes. #650 won't work with CI/CD though, but I think many users prefers a graphical user interface.
