### ISSUE TITLE
Customize redirect_uri

### ISSUE THREAD

**Issue by simonTTIS** [Azure/api-management-developer-portal#851]
Hi,

I'm facing an issue while I'm using Front Door with the new portal.
Communication between Front Door and the new portal is working, the navigation is fine.
The issue appears while an access token is requested and we are getting this error : {"error":"unauthorized_client","error_description":"The redirect URI is wrong. You sent https://XXX.developer.azure-api.net, and we expected https:/YYY.com"}

Concerning the configuration :
- On Front Door : we are using the https:/YYY.com DNS
- On APIM : we haven't added the YYY custom domain, otherwise we get an error from Front Door and then YYY is not working

As the custom domain hasn't been setted, the redirect_uri is generated with XXX domain.
How can we modify its value on the managed version ? (the goal is to have the YYY domain)

Thank you for your help !

**Comment by azaslonov** [comment]
Hi @simonTTIS, could you please take this question to MS support, they will help you to configure it properly.
