### ISSUE TITLE
Unable generate authorization code from developer console

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#852]
## Bug description

Hi There, We have integrated Azure AAD application with OpenIDConnect of API Management. when we try to generate Authorization code from developer console its giving back as "AADSTS500013: Resource identifier is not provided.". Could you please help us what we missed in integration.

## Is your portal managed or self-hosted?

Managed 

## Additional context
![image](https://user-images.githubusercontent.com/30490543/91293146-2ee3cf80-e7b5-11ea-960e-3337aeb02414.png)

**Comment by mikebudzynski** [comment]
Please, open an Azure support request for assistance.
