### ISSUE TITLE
Some entries are not visible in the Request body in 'table view'

### ISSUE THREAD

**Issue by orlowski-ra** [Azure/api-management-developer-portal#853]
## Bug description

In the endpoint description 'object' type entries (entry1) are not visible in the Request body if a 'table view' is used. If we switch to 'Raw schema view' those fields are acting ok.

```
    "properties": {
        "entry1": {
            "type": "object",
            "additionalProperties": false,
            "description": "",
            "nullable": true
        },
        "entry2": {
            "type": "string",
            "description": ""

}
```

## Expected behavior

Both entry1 and entry2 visible in the 'Table view'

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome,

**Comment by azaslonov** [comment]
It has been fixed in the ongoing release. Please check back by the end of this week.

**Comment by azaslonov** [comment]
It should be out everywhere now. Closing.
