### ISSUE TITLE
CORS Question - Azure Hosted API service

### ISSUE THREAD

**Issue by kaylakirzinger** [Azure/api-management-developer-portal#858]
I currently have Dev, QA and Prod instances of APIM, all of which have a corresponding API application hosted in Azure.

I have a CORS policy set on each of my APIM instances. I have a developer creating a SPA that is getting CORS errors in QA but not Dev (policies are identical).

I checked the API app for dev (where it is working) and it looks like CORS is set there as well. In QA (where it isn't working) it's not set.

This is more of a question than an issue - clarifying that the APIM policy isn't enough to support CORS without setting CORS on the API application as well?

**Comment by azaslonov** [comment]
Hi @kaylakirzinger, have you set it up with a button in Azure portal blade? If not, on which level have you added CORS policy? Can you share the snippet?

**Comment by kaylakirzinger** [comment]
For sure! I set it up with a policy. Screenshots attached.
![CORS_1](https://user-images.githubusercontent.com/49795114/91499221-b5b4ad00-e886-11ea-98fc-6214df7200a1.png)
![CORS_2](https://user-images.githubusercontent.com/49795114/91499222-b64d4380-e886-11ea-9718-f32a74ac65a7.png)

The setting that seems to be making it "work" in dev is attached as well. 

Just to reiterate - just wondering why the APIM policy isn't sufficient.
![CORS_3](https://user-images.githubusercontent.com/49795114/91499312-d977f300-e886-11ea-8d3d-030fa026a7fd.png)

**Comment by azaslonov** [comment]
The policy looks good to me, probably there is something else. So, you can either send us network traces (HAR file) and service name to apimportalfeedback@microsoft.com, or (even better) take this question to MS Support, they will help you to configure it properly. I'm closing this for now, to take it offline.
