### ISSUE TITLE
No info about version query parameter on operation definition page for versioned APIs

### ISSUE THREAD

**Issue by WeightyPrawn** [Azure/api-management-developer-portal#860]
## Bug description

When viewing the definition for an operation on a versioned API using query parameter to specify version, there is no information about the versioning schema.

I.E. the URL stated under the "Request" header doesn't include the version query parameter.

With this information lacking it's impossible for any consumer to correctly call the API, as omitting a correct versioning query parameter will result in a 404.

## Reproduction steps

1. Go to the devportal.
2. Click on any versioned API using query parameter versioning schema.
3. Look at the API definition and see that the URL under the "Request" header doesn't include the versioning query parameter. Ex. https://{baseurl}/my/api/operation

## Expected behavior

The versioning query parameter should be included in the URL displayed under the "Request" header.

Ex. https://{baseurl}/my/api/operation?api-version=v1

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

any

## Environment

Any browser.

**Comment by azaslonov** [comment]
Hi @WeightyPrawn, makes sense, we'll add version query parameter info. Thanks for reporting the issue.

**Comment by WeightyPrawn** [comment]
@azaslonov . Any update on progress for this, and/or when we can expect it to be in place?

**Comment by mikebudzynski** [comment]
Still on the roadmap. Most likely, we'll have a fix within a few months.

**Comment by jsorohova** [comment]
Hello @WeightyPrawn, could you please check if this is still reproducible? We recently added a correct version displaying but I would like to double-check this issue with you. Thank you.

**Comment by WeightyPrawn** [comment]
Hi @jsorohova . After publishing the latest devportal it seems like this is now displayed as expected.

Thank you.

**Comment by jsorohova** [comment]
Thank you for your answer. I will close this issue now.
