### ISSUE TITLE
Show first Operation when opening API details pages

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#863]
## Bug description

When navigating to an API the first thing a user will see is an "empty" page with no operations selected. It would be best if the Portal defaults to showing the first Operation of this API.

## Reproduction steps

1. Go to the API details page of an API
2. See that the page doesn't contain content

## Expected behavior

When navigating to the API details page of an API show the first Operation of this API.
 
## Is your portal managed or self-hosted?

Managed

**Comment by fsettele** [comment]
Can confirm that - I've seen that on my managed Developer Portal as well. The last publish was on 1.9.2020.

**Comment by azaslonov** [comment]
Hi @ZarTrox/@fsettele, do you guys have this option checked here?

![image](https://user-images.githubusercontent.com/2320302/92025081-e0ce4f00-ed13-11ea-8940-42bf02ca8432.png)

**Comment by AnRei123** [comment]
I just retested the whole thing the following:

1. Open portal in edit mode.
2. Open API page and select and API
3. API details (including API operation details) page opens. First API operation in the list of operation is not selected by default and no details of any operation are displayed by default.
4. Went to the settings of the "list of operations" and enabled the "Allow selection" checkbox
5. In the modification mode, went to the home page and back to the API (incl. operations) details page.
6. In the modification mode, the first operation was highlighted and the operation details had been displayed now.
7. Published the portal and opened the API (operation details) page in the reading mode.
8. No operation in the list of operations was preselected and no content of any operation was displayed in the operation details widget by default.
9. Went back to modification mode and opened the settings for the "List of operations". My changes were not reflected anymore. !!!!The checkbox "Allow selection" was disabled again!!! My changes had been automatically rolled back from the system - even after saving the portal! Selecting it again and publishing again looped the experience, but did not fix the issue!

**Comment by fsettele** [comment]
In my Developer Portal it does work now - with the "Allow selection" enabled.
It seams there was a change in the Managed version since Monday. But know the publish command from the Developer Portal Admin mode ist shaky... To have a successfull publish I have to use the button in the Azure Portal.

**Comment by AnRei123** [comment]
Thanks for the hint. I retested the behavior for the publish button in the APIM portal GUI, but for my APIM service it does not make any difference which "publish" button I use. I experienced for both publish buttons (on APIM portal page and in the Edit DevPortal mode) the same buggy behavior.

**Comment by AnRei123** [comment]
My list of operation widget is placed on the layout page and the widget for the operation details is placed on the API details page. In editing mode, everything seems to be fine now. And the settings are not reverted after publishing. But in the reading mode, the first item in the list of operations is highlighted, but the related operation details are not displayed as in the editing view for this page. I created some screenshots to visualize this behaviour and my setttings.
- Image 1:  Editing mode - layout page with list of operations settings
- Image 2:  Editing mode - page that uses this layout page (everything looks fine)
- Image 3: Reading mode - page view (first item of the list of operations is highlighted, but no details are shown by default until you click any list item)
![Issue_list-of-operations_layout-view](https://user-images.githubusercontent.com/58981351/92209651-a983ad80-ee8d-11ea-89ce-b23137dfc7f5.PNG)
![Issue_list-of-operations_page_editing-mode](https://user-images.githubusercontent.com/58981351/92209663-ac7e9e00-ee8d-11ea-9fdb-37b6325d6d7e.PNG)
![Issue_list-of-operations_published-view](https://user-images.githubusercontent.com/58981351/92209670-aee0f800-ee8d-11ea-8bdf-ad219224f0a0.PNG)

**Comment by ygrik** [comment]
> I just retested the whole thing the following:
> 
> 1. Open portal in edit mode.
> 2. Open API page and select and API
> 3. API details (including API operation details) page opens. First API operation in the list of operation is not selected by default and no details of any operation are displayed by default.
> 4. Went to the settings of the "list of operations" and enabled the "Allow selection" checkbox
> 5. In the modification mode, went to the home page and back to the API (incl. operations) details page.
> 6. In the modification mode, the first operation was highlighted and the operation details had been displayed now.
> 7. Published the portal and opened the API (operation details) page in the reading mode.
> 8. No operation in the list of operations was preselected and no content of any operation was displayed in the operation details widget by default.
> 9. Went back to modification mode and opened the settings for the "List of operations". My changes were not reflected anymore. !!!!The checkbox "Allow selection" was disabled again!!! My changes had been automatically rolled back from the system - even after saving the portal! Selecting it again and publishing again looped the experience, but did not fix the issue!

Hi @AnRei123 
Did save your changes after **step 4** and before **step 7**?
You can do it with hotkeys **Ctrl + S** or use the button in the left bottom corner
![image](https://user-images.githubusercontent.com/8660244/93143625-23d9dc00-f69d-11ea-9b5a-c23ed366c75b.png)

**Comment by ZarTrox** [comment]
I cannot speak for @AnRei123 if she did save but in our environments the settings are now corrected and set. As expected in most tests the APIdetails page immediately showed the first operation. But in the same environment with the same templates a few didn't show them. When going back and navigating again to the API it worked. So there seems to be some kind of inconsistency.

**Comment by AnRei123** [comment]
Yes, I saved it frequently nearly after each step earlier with the button but newer days with Ctrl.+S.

**Comment by AnRei123** [comment]
If you merged the commit for this fix to the master does this mean that the fix has been already rolled out? When do you plan to roll out the solution?
The error still occurs even after publishing the DevPortal content again. Sometimes it works when freshly open the API gallery. But most of the time it does not work when switching between product details and between several apis.
