### ISSUE TITLE
Handle "list of Operations" as Navigation Item

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#864]
## Bug description

When trying to navigate through an API with multiple Operations, selecting an Operation in the"list of Operations" element highlights the operation selected. This is very helpful so that the user can orientate himself. But as soon as one clicks "Try it" or even just on the background of the page the highlight disappears. Therefore the Portal should handle the "list of Operations" element as a Navigation item. Which means as long as one is at the same Operation with the same link ([...]&operaion=FOO-BAR) the item should be highlighted.

## Reproduction steps

1. Set styles so that a Shadow/highlight is shown when selecting a navigation Item
2. Go to any API details page
3. Select any operation
4. See that operation in "list of Operations" is highlighted
5. Click on try it or anywhere else on the screen
6. See that nothing is highlighted anymore

## Expected behavior

When navigation the an Operation this Operation should always be highlighted for orientation and consistency purposes.

## Is your portal managed or self-hosted?

Managed

**Comment by AnRei123** [comment]
Portal link has been sent per email with additional information.

**Comment by ygrik** [comment]
was fixed with PR #918
