### ISSUE TITLE
API Details page is not loading in Developer portal

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#865]
## Bug description

API details page is not loading in the Managed developer portal

## Reproduction steps

1. Navigate to API details page

## Expected behavior

API details page should be loaded with the operation details

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 10
 - Browser: Chrome

Error screenshot:
![image](https://user-images.githubusercontent.com/66616951/91718091-57523c00-ebb0-11ea-97ad-9772416d7fbc.png)

**Comment by azaslonov** [comment]
Hi @dhandapanitrimble, this fix is coming in ongoing release. However, this happens because API details widget doesn't know which API to load, so you can work it around if you specify API in page URL: `/api-details#api=echo-api`

**Comment by dhandapanitrimble** [comment]
Hi @azaslonov , Api page is loading with proper page URL : /api-details#api=test-api-v3 , but its still not loading the page. Since this is blocking our production deployment kindly look into it.
