### ISSUE TITLE
Confusing UX in APIM GUI to view, edit and publish the DevPortal

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#869]
Background information:

Our developers do not need and shall not open the portal in editor mode nor do they need or shall click on the publish portal button. 
They most of the time only intend how there API changes are reflected within the DevPortal regarding style sheets and functions. Therefore, by default they should use the web URL link to open the DevPortal in reading mode! 

For maintaining the portal web pages and the additional content that is provided via the edit mode of the portal, we have dedicated content contributors. Only these content contributors shall open the portal in editing mode and shall publish the portal on demand for any APIM environment.

The edit mode of the new portal does not support all the functions as the reading mode does such as subscribing to products or picking the subscription keys. And the editing mode GUI is disgusting if you just like to view your latest API changes as the tool palette is displayed and you need to keep the CTRL key pressed to use the navigation and interaction elements.

Problem statement:

With the current GUI implementation of the APIM portal, the developer seem to be very confused on how to invoke the portal reading and editing mode and on what publishing the portal effects.

- **APIM - Overview page:** Instead of opening the new portal via the "Developer portal URL" link from the right data list column on the right on the overview page of the APIM portal, our developers frequently click the "Developer portal" button that is placed too prominent in the upper left corner and that opens the portal in editing mode instead of the reading mode. Also the name "Developer Portal" of the button is misleading. The user does not know if there are other option to open the portal and that their are different options to open the portal.

- **APIM - APIs page:** Also the "Developer Portal" button on the APIs page opens the portal in editing instead of the reading mode. On this page, a button for opening the DevPortal in reading mode is completely missing!!!!

- **APIM - Portal overview page:** Also the meaning of the publishing button is not clear to all developers.  Some assume they need to use the publishing button to have their APIM changes being reflected on the API details pages in the DevPortal. This is not wonder as the current description of the button is the following "Publish the portal - Publishing the portal makes your changes and customization available to visitors." Especially with the current bug 822, this is a big advantage. Our developer should not use this button. Only contributors for the additional DevPortal pages.
On this page, a button for opening the DevPortal in reading mode is completely missing!!!!

## Expected behavior

- Accessing the portal in reading mode shall be very easy and handsome from all relevant pages of the APIM portal such as the overview page and the APIs page.
- Accessing the portal in editing mode shall be more hidden on a second interaction level and not be placed very prominent. 
- Accessing the publishing function for the DevPortal should be more hidden and should not be placed on the portal overview page, but only within the portal in editing mode or additionally from a sub entry of the portal overview page.
- A meaningful subscription shall be edit in the context of the publishing button or menu entries.
- The buttons and menus to invoke the DevPortal in view, edit or publish mode should be named accordingly: "View DevPortal", "Edit DevPortal", "Publish DevPortal"

## Is your portal managed or self-hosted?

managed

## API Management service name

apiteamplayuxplayground

## Environment

 - Operating system: Windows 10
 - Browser: Chrome (latest version)

**Comment by fsettele** [comment]
Agree with that - would also love to have a more consistend solution and only one place. As well having a group/permission to allow publishing/managing the Developer Portal only.

**Comment by azaslonov** [comment]
Hi @AnRei123 and @fsettele, thank you for your feedback. We understand the problem, we'll see what can be done.

**Comment by AnRei123** [comment]
I like to add the following improvement requirements to this issue to also facilitate the work of content contributors:

1. As a content contributor, I can open the DevPortal in reading mode from the opened DevPortal in editing mode on a new tab card by either clicking on a button or clicking a shortcut.
2. As a content contributor, I can publish the portal in editing mode via a shortcut w/o the need to navigate to the publish buttons.
3. As a content contributor, I can open the portal in editing mode directly from my browsers bookmark panel without the need of navigating to the overview page of the APIM portal. And I can configure my bookmark the following that the portal automatically opens on the most frequently used page (APIM wiki, alias "Docs&guidelines).

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
