### ISSUE TITLE
Switching between authorization grant types does not regenerate a token

### ISSUE THREAD

**Issue by cs2ea** [Azure/api-management-developer-portal#870]
## Bug description

We have an API that supports both Authorization Code and ClientCredentials grant types that is published in APIM. 
These grant types are defined in the oAuth 2.0 authorization page in the APIM admin portal. 
They appear correctly in the dropdown of the Authorization field in the "try it" window.
They also generate correct tokens when selected _if_ no authorization code was previously generated. 

However, a new token is not acquired and the Authorization header is not updated when subsequently selecting a different grant type

## Reproduction steps

1. Ensure you have an oAuth2.0 definition in APIM that supports two or more grant types (e.g. Authorization Code and ClientCredentials)
2. Ensure that you have an API that in published in APIM that uses that oAuth2.0 definition for authorization
3. In the new developper portal, navigate to that API and select an operation
4. Click on "Try it"
5. Verify that all grant types present in the dropdown
6. Verify that there is no Authorization header populated. 
7. Select e.g. the Authorization Code grant type to acquire a token. 
8. Note that a browser popup should appear
9. Verify that the authorization header is populated; 
10. keep a copy of new token for comparizon
11. Select e.g. the ClientCredentials grant type to test the API with a different type of token
12. Note that no browser popup appears
13. Verify that the Authorization header is still populated. 
14. Compare the token from step 13 with the one in step 10

---> the token / AUthorization header has not been updated
---> the lack of browser popup in #12 suggests that a new token has not even been acquired

## Expected behavior

1. The Authorization header must be updated with the correct token when selecting a different grant type
2. Current feature of cacheing tokens should be preserved (as opposed to legacy portal approach of reacquiring a token whenever a grant type is selected) with the following conditions
  - if we do not already have a token for that grant type for the current api or if that token is present but expired then a new one must be acquired and cached
  - If we already have a valid token in cache for that grant type in the current api, then we should use that one

Note: #832 would also be resolved by the above

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

apim-msfnex23-sbx

## Environment

 - Operating system: Windows 10 
 - Browser: Google Chrome
 - Version: 4.0.4147.89

## Additional context

We are using AAD for obtaining the tokens using the v2.0 endpoints

**Comment by azaslonov** [comment]
Hi @cs2ea, thanks for reporting the issue, we'll fix this.
