### ISSUE TITLE
West Central US does not seem to get updated

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/api-management-developer-portal#872]
## Bug description

It seems that the portal code for API Management instances hosted in West Central US is not updated when a new portal is released. I have created two cases with Azure Support this summer to get it updated.  At those times the whole region had not been updated. 

When I do https://_apim-instance-name_.developer.azure-api.net/internal-status-0123456789abcdef for an APIM instance in West Central I get:

"CodeVersion": "2020**0812**080849",
"Version": "0.13.**1056**.0"

When I do this for an instance in West Europe I get:

"CodeVersion":"2020**0901**084820",
"Version":"0.13.**1048**.0"

For an instance in East US I get:
"CodeVersion":"2020**0901**084820",
"Version":"0.13.**1055**.0"

So the backend is newer in West Central US but it uses an older version of the portal.

Should I create a third case to get West Central US updated or will it be updated automatically?

Since we are currently unable to login using AAD in West Europe and West Central US possibly because of #815 and/or #822 we are eager to get these instances updated hoping that the updates will fix it.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @ErikMogensen, it is updated now.

**Comment by ErikMogensen** [comment]
Thank you!
