### ISSUE TITLE
Issues with Retrieve-managed-portal-storage-account-and-SAS-URL

### ISSUE THREAD

**Issue by butsona** [Azure/api-management-developer-portal#875]
The api nolonger provides the connection string to the blob storage.

The documentation is now incorrect: https://github.com/Azure/api-management-developer-portal/wiki/Retrieve-managed-portal-storage-account-and-SAS-URL 

Is there a replacement api to retrieve the stoage account connection string?

**Comment by azaslonov** [comment]
Hi @butsona, yes, this operation was considered a security issue and was replaced with: `POST /portalSettings/mediaContent/listSecrets`, please use that from now on. The documentation will be updated shortly.
