### ISSUE TITLE
OAuth2 client_credentials access token is not generated in the managed developer portal

### ISSUE THREAD

**Issue by AdamaDEMBELEGS1** [Azure/api-management-developer-portal#878]
## Bug description

We are not able to generate access client_credentials access token in the managed developer portal. 

## Reproduction steps

1. Load the developer IRL and navidate to try it window
2. Select the "Client credentials" option from OAuth2 dropdown
3. You'll get an error 404 on the url : /signin-oauth/credentials/{authServerId}

## Expected behavior

A token should be generated and fill the header

## Is your portal managed or self-hosted?

Managed

## API Management service name

apimgs1prod-client

## Environment

 - region : France Central

## Additional context

The OAuth2 configuration is working on the old developer portal.

**Comment by dandzina** [comment]
I just reported what I suspect is the same issue at https://github.com/Azure/api-management-developer-portal/issues/885

**Comment by azaslonov** [comment]
We found the issue on the backend side and it is specific to client credentials flow only, so if possible, please switch to other grant flows. We're releasing a fix for this, along with a fix for #728, but it may take up 2-3 weeks to reach every region.

**Comment by azaslonov** [comment]
Unfortunately, no. Previous version(s) contain serious security issue, but we can prioritize the patch of your service(s).

**Comment by jbm00n** [comment]
Hello, please don't take this the wrong way, but could you explain why does a ready bug fix takes 2 to 3 weeks to deploy? I have another bug related to OAuth server, pending with similar time estimates. I understand if it's a new feature, but when it comes to bug, can't there be a "hotfix" type of release?

**Comment by mikebudzynski** [comment]
@jbm00n Bugs related to developer portal are located either on the portal client side or in the underlying backend in API Management. In the second case, which this issue also fall into, we roll out upgrades gradually over at least two weeks, while monitoring metrics, regression tests, and customer reported issues. The process becomes even longer if we identify problems during the rollout. Backend upgrades affect multiple components, including API gateway, which is the most important component of the service, so we prioritize the service stability and high availability over the frequency of updates. We aggregate changes and release them on average on a monthly basis; it's not sustainable or even possible to roll out bug fixes one by one. We do consider making exceptions for highest-priority issues.

As @azaslonov mentioned, if you would like your API Management service to be prioritized in the upcoming release, provide us with the service name here or via an email to apimportalfeedback@microsoft.com

**Comment by jbm00n** [comment]
Alright thank you for the info, it's just that in our case all APIs endpoints are protected by OAuth so it's quite an important feature for developers to be able to easily generate these tokens. But ok I ll send an email to prioritize our service.

Thanks!

**Comment by mikebudzynski** [comment]
The release is currently being rolled out. You can read the release notes at: https://github.com/Azure/API-Management/releases/tag/2020-09
