### ISSUE TITLE
Unable to load API Detail for an api with version

### ISSUE THREAD

**Issue by AdamaDEMBELEGS1** [Azure/api-management-developer-portal#879]
## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. Go to '/api-details#api=XXXX'
2. See error : 
- No api is selected and a message with "No operation selected"
- In the console : 
theme.js:2 Could not parse ID.
(anonymous) @ theme.js:2
theme.js:2 Uncaught (in promise) Error: Could not parse ID.
    at Function.getResourceName (theme.js:2)
    at exports.ApiService.<anonymous> (theme.js:2)
    at Generator.next (<anonymous>)
    at fulfilled (theme.js:2)
theme.js:2 Could not parse ID.

<img width="1049" alt="Capture d’écran 2020-09-03 à 12 20 09" src="https://user-images.githubusercontent.com/38036081/92103453-4a1b9400-ede0-11ea-9559-015a3f77fa70.png">

## Expected behavior

The api and his first endpoint should be selected.
## Is your portal managed or self-hosted?

Managed

## API Management service name
apimgs1uat-client

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Working the old developer portal

**Comment by azaslonov** [comment]
This issue had been fixed in last release, please just re-publish the portal.
