### ISSUE TITLE
Static content search

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#881]
## Bug description

Hi there, is there any way to create search and tabulation for content in the page?

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @shashiguru, do you mean search over static content or API docs or both? Support for tables is a planned feature, but no ETAs at the moment.

**Comment by shashiguru** [comment]
Thanks for response @azaslonov , I'm looking for search over static content. Something like widget for search the static content.

**Comment by mikebudzynski** [comment]
I renamed the issue to "Static content search", feel free to create another feature request for tables support.

**Comment by mikebudzynski** [comment]
Merging into #1014 as it contains more comments.

**Comment by AnRei123** [comment]
Yes, the missing search functionality for static content is also an issue for and urgently needed as our amount of static content is increasing continuously. 

1) The search should allow to filter for all page titles that contain a dedicated string. Matches in the title shall be ranked higher than matches in the description. This must be reflected in the list with the search results.
2) The search should allow to filter for all page contents that a dedicated string or a combination of several strings. (searching for one string might not always sufficient. 
The search result should list the page titles and offer an extension to see the first three sentences of a page. Navigating to the search target should highlight the the strings on the page to easier navigate on the target page.
If no string is entered in the search field, the complete list with all static pages should be listed in a scrollable manner to allow getting an overview and an impression on the available and amounts of contents. The titles of the pages should be listed in an alphabetically order.
3) A configurable web widget is required for add a search field in the header that also contains the main navigation.
4) The search shall also allow to search not only in the static content, but also in the descriptions of API products, APIs and operations according to the access rights of the DevPortal user. As we have a mixed approach to document our APIs, it is very important that all contents of the DevPortal are considered for the full-text search - the static page content and the dynamic API content including names of operations and all kinds of descriptions.  The search widget shall be configurable accordingly. There should be also offered different sizes and appearances for the different placements on the WebPortal page. 
The search widget should be configurable, if the search should search for dynamic API contents only or static content or a combination of it. The size (length, width) of the search field and the display of the zoom icon should be configurable as well.

**Comment by mikebudzynski** [comment]
@AnRei123, I copied your comment to the issue referenced above. This one is inactive.
