### ISSUE TITLE
Product name (id) is being shown on the Profile page instead of the Product displayName

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#882]
This appears to be regression with change #819 

Our Products are loaded through our pipeline and the ID is an autogenerated guid. So, we are now seeing this on the Profile page. In this example, the Product name is the Product ID, not the Product Display Name.  Note, you can see the "unlimited" has the lower case 'u' which is the default product from APIM when the site is provisioned. In this case the "Unlimited" product has the Id of "unlimited"

![image](https://user-images.githubusercontent.com/65634611/92149731-41709100-edd3-11ea-8648-05b0c7654066.png)

# Reproduction steps

1. Create a new Product in Azure portal, make not to make the Display Name and ID different. 
2. Make sure the new Product has Access control set to Developer and Guests
3. Make sure the new Product is assigned to the Echo API
4. Launch the portal
5. Log into the site
6. Select the new product from the Products page
7. Select it to subscribe to it. 
8. Navigate to your Profile page to review your subscriptions

![image](https://user-images.githubusercontent.com/65634611/92148869-028e0b80-edd2-11ea-9843-2b9c117bab03.png)

## Expected behavior

The Product Display Name should be shown. 

## Is your portal managed or self-hosted?

Both

## Release tag or commit SHA (if using self-hosted version)
2.4.3

## Additional context
? Was this the change?

changing Line 127 to helped our experience, but didn't test all aspects of the site. 
`subscriptionModel.productName = product.properties.displayName;`

![image](https://user-images.githubusercontent.com/65634611/92150681-9fea3f00-edd4-11ea-94eb-4bc6911be6fe.png)

**Comment by azaslonov** [comment]
Thanks @VWACBrick, we'll fix this.
