### ISSUE TITLE
OAuth2 Client Credential Redirect broken after 9/3

### ISSUE THREAD

**Issue by dandzina** [Azure/api-management-developer-portal#885]
Our API portal was working fine w/ ability to authenticate w/ OAuth Client Credential authorization as recently as yesterday (9/2)
Today, we re-imported the openapi definition via azure portal and the ability to authenticate ceased working.

When you pick the authorization in the "Try It" panel, a new window is opened to 
https://CUSTOMDOMAIN/signin-oauth/credentials/AUTHORIZATION_CONFIG_ID
Where AUTHORIZATION_CONFIG_ID is the name of the authorization in the setup, and returns 404/"Page your looking for doesn't exist"

I saw that our portal was out of date, and republished to the latest version, which did not change the behavior. (now last published 9/3/2020, 3:39:39 PM eastern)

I had been following https://github.com/Azure/api-management-developer-portal/issues/799
Since this redirect URL was a pain to figure out in the first place.  And it had indicated some type of change would be coming (around now)
I believe the URL used to be
https://CUSTOMDOMAIN/signin-oauth/code/callback/AUTHORIZATION_CONFIG_ID
Which also returns a 404.

The Azure Portal claims the callback is supposed to be at
/docs/services/AUTHORIZATION_CONFIG_ID/console/oauth2/authorizationcode/callback
which i suspect is still the legacy portal link... however it does seem to at least return a "Authentication has failed.Unexpected error occured" if i directly access it  instead of the 404.  -

**Comment by azaslonov** [comment]
Hi @dandzina, please send your service name to apimportalfeedback@microsoft.com. We'll take it from there.
