### ISSUE TITLE
Publish end-point doesn't always work

### ISSUE THREAD

**Issue by butsona** [Azure/api-management-developer-portal#888]
We're having problem with publication. The release is working and we can see the update version in the admin portal. At the end of the release process call the publish end-point, this was working fine. but, now it often doesn't push the publication. Also tried with the reset and publish and it take a few attempt for the modified version to get release.

has something change?

The end-point is https://<portal-url>/publish

is there a management url which should be used?

**Comment by azaslonov** [comment]
Hi @butsona, there were no changes related to publishing recently. Can you tell where do you get this `https:///publish` URL from?

**Comment by butsona** [comment]
sorry for the delayed response i've been away for a couple of days.

We've been using the API to publish the managed portal in our CD pipeline. It was working but recently has stopped.

The question is how should we publish without clicking the button in the azure portal. We need to automate via our release pipeline.

for references there is very limited documentation. But you can see the publish api being called in the migration script in this repo. we are doing something very similar but we need to use ps and always push the data.json and media from our nuget packages. 

the reference is:

https://github.com/Azure/api-management-developer-portal/blob/5aa0f3bccdd21630136e838246be96fcb037ae26/scripts.v2/migrate.js#L176

**Comment by mathiasi** [comment]
We are facing the same issue. We want to automate publishing and calling https://${endpoint}/publish with a SAS token returns "OK" but the content doesn't change. Can publish using the Azure Portal just fine.
Actually I don't think we've ever been successful in publishing using /publish

**Comment by mathiasi** [comment]
I'm suspecting this could be the issue: https://github.com/Azure/api-management-developer-portal/issues/826#issuecomment-683061925 
It appears it works if I use an admin token.
Maybe migrate.js should be updated to reflect this.

**Comment by azaslonov** [comment]
Looks like this is fixed by #893 (thanks @mathiasi!). The issue with the integration token is a backend issue, the fix is coming in one of the next releases.
