### ISSUE TITLE
Storage connection string  - "undefined" (creation currently not possible)

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#889]
When creating the storage connection string for downloading or uploading the media from/to the blob storage, I get an message that the string is "undefined" and "Unable to obtain data client. Check your connection parameters.".
This morning everything run smooth. But in the afternoon, I got this issue. Haven´t changed my scripts in the meantime.
Is this a temporary issue! Are you aware? When will the media download and updload work again?

**Comment by azaslonov** [comment]
Hi AnRei123, most likely you have an issue similar to #880. This probably means that your service got the upgrade today (there was a security issue that we needed to mitigate fast, unfortunately with one breaking change).  We have prepared a new [set of scripts (v2)](https://github.com/Azure/api-management-developer-portal/tree/master/scripts.v2) that take this issue into account. Also, they got simplified, so that you don't need to generate blob storage tokens anymore. Please check those out.

**Comment by AnRei123** [comment]
Hallo Alex

Unfortunately, the script provided error messages (one regarding “utils” vs. “utils” – this I corrected already).
The currently remaining error message is:

TypeError: getStorageSasTokenOrThrow is not a function
    at capture

(see attached files)

Could you please send me the corrected javascript file for the capture step?

Regards,
Angelika

**Comment by AnRei123** [comment]
Hi

Please ignore my email below.

I found my error. I had to add the utils.js as well and to install further npm pages. Sorry for any inconvenience.

Local backup of the portal content is possible again now.

Now, I will try to get the generate part running as well.

Thank you very much.

Would be great if such breaking changes would not be rolled out at such short notice. But security – of course – comes first.

Regards,
Angelika

From: Reichenbacher, Angelika (SHS DI DH TP PL)
Sent: Montag, 7. September 2020 08:23
To: Azure/api-management-developer-portal <reply@reply.github.com>; Azure/api-management-developer-portal <api-management-developer-portal@noreply.github.com>
Cc: Author <author@noreply.github.com>; Gossler, Thomas (SHS DI DH TP PL) <thomas.gossler@siemens-healthineers.com>; Buchner, Benjamin (SHS DI DH TP PL) <benjamin.buchner@siemens-healthineers.com>
Subject: RE: [Azure/api-management-developer-portal] Storage connection string - "undefined" (creation currently not possible) (#889)

Hallo Alex

Unfortunately, the script provided error messages (one regarding “utils” vs. “utils” – this I corrected already).
The currently remaining error message is:

TypeError: getStorageSasTokenOrThrow is not a function
    at capture

(see attached files)

Could you please send me the corrected javascript file for the capture step?

Regards,
Angelika

**Comment by AnRei123** [comment]
Thanks after some investigations, updates, and adaptions based on the scripts.v2 folder it is working again.
