### ISSUE TITLE
Cross-browser compatibility

### ISSUE THREAD

**Issue by anjusharma17** [Azure/api-management-developer-portal#89]
In the step 4 of link [self-hosting-the-portal](https://github.com/Azure/api-management-developer-portal/wiki/self-hosting-the-portal) it is mentioned that "**Currently, the portal works only in the Google Chrome browser.**"

**When will the APIM be available with cross brower compatibility?** Can you please share some timeframe?

**Comment by azaslonov** [comment]
Hi Anju, we'll update this item when we have an exact date. Preliminary I would say it's about 4 weeks from now.

**Comment by mikebudzynski** [comment]
@anjusharma17 - the dev portal (mostly) works in major browsers. It has been tested only in Chrome.

**Comment by mikebudzynski** [comment]
Fixed with the latest release.
