### ISSUE TITLE
Migration script v2 is not working

### ISSUE THREAD

**Issue by WeightyPrawn** [Azure/api-management-developer-portal#892]
## Bug description

Running the migrate.js script in scripts.v2 doesn't seem to work.
I get the following output:

`(node:9648) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`

`(node:5504) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`

`(node:7788) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`

`DONE`

`(node:5436) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`

And when I check the destination dev portal, nothing has changed.

## Reproduction steps

1. Run node migrate --sourceEndpoint from.management.azure-api.net --destEndpoint to.management.azure-api.net --publishEndpoint to.developer.azure-api.net --sourceToken "SharedAccessSignature integration&2020..." --destToken "SharedAccessSignature integration&2020..."

## Expected behavior

The destination dev portal should be updated with the same look and settings as the source.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

commit 5aa0f3bccdd21630136e838246be96fcb037ae26

## Environment

 - Operating system: Windows 10
 - Node: 12.18.3
 - azure-cli: 2.11.1

## Additional context

The migrate.js script in scripts folder worked great a couple of weeks ago, but also doesn't work now.

**Comment by WeightyPrawn** [comment]
Please ignore this.
I was using expired management tokens.

**Comment by azaslonov** [comment]
Great! Glad you figured this out.
