### ISSUE TITLE
Refresh of the page needed to accesss account after login via SSO

### ISSUE THREAD

**Issue by CoumbaNDI** [Azure/api-management-developer-portal#895]
We currently have an issue on our production environnement. After using our SSO to log in the APIM, the client need to refresh the page to be able to have access to his authenticated page.

1. Go to ' www.apimprod.com/signin-sso?token=e5fad947-7429-4b8b-84bf-539138d767cf&202009271444&EMDxjniUi4DZTDXLQ1knV'
2. Land on the page 'www.apimprod.com'
3. Refresh page 'www.apimprod.com'
4. Would like to access to authenticated page

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
Please, republish the portal and let us know if you still experience the issue.

**Comment by CoumbaNDI** [comment]
I republished the portal and i'm still experiencing the issue.

**Comment by CoumbaNDI** [comment]
Can you provide us with some kind of help ?

**Comment by azaslonov** [comment]
Yep, there might be a bug, we'll investigate and fix.

**Comment by butsona** [comment]
same issue: https://github.com/Azure/api-management-developer-portal/issues/916#issuecomment-693442218

**Comment by butsona** [comment]
Just re-release in dev. 

Now not only do we not get refresh but don't get MFA notification. 

This is a high priority as we can't even sign in now.

   PortalVersion: 202009252125 
   CodeVersion: 20200916070648 
   Version: 0.14.1065.0 

Could someone example the PortalVersion as it just seems to be a timestamp of the publication. I presume the Version 0.14.1065.0 is the relevant number

**Comment by azaslonov** [comment]
Hi @butsona, the release already started, it should reach all regions by end of the week.

**Comment by spyder007** [comment]
We are still seeing this behavior, despite re-publishing.  We are using the process described in [Issue #329](https://github.com/Azure/api-management-developer-portal/issues/329) to generate the sign on url, but after redirection, the user is not signed in.  They are able to refresh the page and then they show as authenticated.
