### ISSUE TITLE
Add support for required body parameters

### ISSUE THREAD

**Issue by mirinkinen** [Azure/api-management-developer-portal#896]
## Bug description

API Management doesn't seem to support body parameters marked as required.

## Reproduction steps

1. Navigate to API Management service
2. Click on "APIs"
3. Click "+ Add API"
4. Select "OpenAPI"
5. Select a file, which has a valid OpenAPI documentation. Documentation must have at least one POST method with requestBody marked as required, like in the following JSON block:

```
        "requestBody": {
          "x-name": "persons",
          "required": true
          "description": "The list of persons",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/PersonDto"
                }
              }
            }
          },
        }
```
6. Add other needed information for the new API and click "Create".
7. Navigate to Developer Portal
8. Sign in if needed
9. Navigate to newly created API documentation
10. Download the "Open API 3 (JSON)" file

## Expected behavior

The exported OpenAPI documentation should have the `"required": true` in the requestBody. At the moment it is missing.

**Comment by azaslonov** [comment]
Hi @mirinkinen, this looks like an issue of API import, rather than a dev portal. Do you mind redirecting this question to MS support? I also let the team know about it.
