### ISSUE TITLE
Login using Microsoft live accounts

### ISSUE THREAD

**Issue by juanda147** [Azure/api-management-developer-portal#901]
I'm trying to add the "login with Microsoft" button for live accounts. Adding the Microsoft identity provider takes no effect in the developer portal, and only adding AAD as an identity provider displays the login AAD button.  There is support to add the "login with Microsoft" button in the API developer portal?

**Using Microsoft as identity provider:**
![image](https://user-images.githubusercontent.com/6800070/92609038-b3d1ed00-f27b-11ea-8134-203308be4115.png)

**Adding Azure Active Directory provider:**
![image](https://user-images.githubusercontent.com/6800070/92608586-2d1d1000-f27b-11ea-9db7-0a8d389215e3.png)

**Comment by mikebudzynski** [comment]
The new developer portal doesn't support direct Microsoft/Facebook/Twitter/Google sign-in. We recommend using Azure AD B2C.
