### ISSUE TITLE
Uploading Images for Self-Hosted Portal fails

### ISSUE THREAD

**Issue by Marek26** [Azure/api-management-developer-portal#903]
## Bug description

When trying to customize the self-hosted portal by adding images, the process fails.

![grafik](https://user-images.githubusercontent.com/33370588/92892293-ef55ee00-f418-11ea-986b-089095d0b73a.png)

He tries to upload to some localhost adress instead of the Blob Storage.
![grafik](https://user-images.githubusercontent.com/33370588/92892054-b6b61480-f418-11ea-84fe-fa70de60d163.png)

## Reproduction steps

1. Go to localhost:8080 when the local portal version is running
2. Click on Media -> Upload File

## Expected behavior

The image should be uploaded to the BlobStorage defined in the config.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release `2.4.3`

## Environment

 - Operating system: Win 10
 - Browser: Chromium Edge 
 - Version: 85.0.564.44 (Official build) (64-bit)

**Comment by azaslonov** [comment]
Hi @Marek26, what service version do you have? You can fetch it by like this:
https://**[yourservice]**.azure-api.net/internal-status-0123456789abcdef

**Comment by Marek26** [comment]
@azaslonov 
`{"StatusCode":200,"Message":"Service operational","Instance":"Proxy.Host.WebRole_IN_0","Region":"West Europe","SkuType":"Developer","SkuCount":"1","RuntimeVersion":"0.13.1056.0","ConfigVersion":0,"LastEventId":"0000000c","LastUpgradeStartTime":"03 Sep 2020 09:09","Os":"Microsoft Windows 10.0.14393 "}`

**Comment by azaslonov** [comment]
@Marek26, looks right, could you please send us your config.design.json file (scrambling the last 5-7 characters of secrets in it) to apimportalfeedback@microsoft.com? We'll take a look what's wrong.
