### ISSUE TITLE
New feature: Sign-Off button

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#904]
Hello,

Is it planned to have a Sign-Off feature, as we have Sign-up and Sign-in ? A button in the left-right upper menu would be cool

Thanks

**Comment by ThomasSmeets** [comment]
There is by default a "Sign out"  feature in the default template. I don't know if it is what you are searching for.
But it is only available for the authenticated user.

You have to change your visibility from Anonymous to Authenticated
![image](https://user-images.githubusercontent.com/49551742/93348041-07bd7280-f836-11ea-8513-6a6c2106979d.png)

You should then be able to see the Sign out ( instead of having the Sign In / Sign Up)

**Comment by azaslonov** [comment]
In the default template it is done like this:
![image](https://user-images.githubusercontent.com/2320302/93518089-36dcee00-f8e1-11ea-99f9-b4a6e955edfa.png)

Basically, a special URL `#signout` that triggers the signout process.

**Comment by JCAMPOLPA** [comment]
Wow great !!!!

Really, it is difficult to guess such things – I think we need more docs -> for example, using # for function instead of an hyperlink !

Best regards

Jérôme Campo
Head of Architecture & Innovation
+33 787235209
[cid:image001.png@01D68DA2.477AD920]<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjOU_z5ON46A5aOWtw6zRNVyIiCpp2imPTIKSomxlTnuS>
www.wakam.com<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjAvIAtwehUUC-T0MX9hWoYfJTW2L8CUBqHs50ofJidNw>
[cid:image002.png@01D68DA2.477AD920]<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjOU_z5ON46A5aOWtw6zRNVyvy0pX9yNRttpPsNkQHYPOOYXq2ArZPmDSmVnmXkq8OJo5Npzl3ZyNthllv2GSTEw=>
[cid:image003.png@01D68DA2.477AD920]<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjEeJLeCbA6VjiBw4QljAIyPkmOFc9o5sT0T5CuLsFDp8Yf9sRgnz4eDuzndlnRD6dg==>

[cid:image004.png@01D68DA2.477AD920]

**Comment by azaslonov** [comment]
Yeah, makes sense. I think we just need to make it a reserved URL and/or menu item.

**Comment by JCAMPOLPA** [comment]
Hi Alexander

As well, playing with menu visibility, it seems Everyone/Authenticated/Anonymous views work when in Admin mode (AzB2B connected) but when on private browsing using an AzB2C identity I am stick with Everyone behavior ☹

  *   I never manage to get menu visibility  depending if the user is logged on !
Can you check if there is no issue with AzB2C identity for that ? It is weird

Jérôme Campo
Head of Architecture & Innovation
+33 787235209
[cid:image006.png@01D69024.5B7AB880]<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjOU_z5ON46A5aOWtw6zRNVyIiCpp2imPTIKSomxlTnuS>
www.wakam.com<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjAvIAtwehUUC-T0MX9hWoYfJTW2L8CUBqHs50ofJidNw>
[cid:image007.png@01D69024.5B7AB880]<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjOU_z5ON46A5aOWtw6zRNVyvy0pX9yNRttpPsNkQHYPOOYXq2ArZPmDSmVnmXkq8OJo5Npzl3ZyNthllv2GSTEw=>
[cid:image008.png@01D69024.5B7AB880]<https://cloud.letsignit.com/collect/bc/5f58c567dce785004bcfb827?p=TqOdExuV74SMy47Cw8cHJ2bN0H8FLApUpIeHNVmfJDyJzDn4SFUitr21yBzY5qKECcEbypDclBZP1T76iCXKjEeJLeCbA6VjiBw4QljAIyPkmOFc9o5sT0T5CuLsFDp8Yf9sRgnz4eDuzndlnRD6dg==>

[cid:image009.png@01D69024.5B7AB880]
