### ISSUE TITLE
New feature: have UserName in the menu when logged

### ISSUE THREAD

**Issue by JCAMPOLPA** [Azure/api-management-developer-portal#905]
Hello

Is it possible to have the FullName of a user as a replacement for "Profile" menu item when we are loggued ?
![image](https://user-images.githubusercontent.com/26059633/92901373-b883d600-f420-11ea-8741-65823c4b5ace.png)

Thanks

**Comment by azaslonov** [comment]
Jerome, you have filed a similar request :) #763 We'll implement it, I promise :)

**Comment by Mdshakeelse** [comment]
Is this issue fixed for managed portal as well, I wanted to display the logged-in username on menu?
