### ISSUE TITLE
Old vs new developer portal - questions

### ISSUE THREAD

**Issue by yashwantsahu05** [Azure/api-management-developer-portal#91]
**Query-Help **
We have below query with New and Old developer portal:

1. Are we are planning to remove old developer and Publisher portal?
2. Where we can find feature wise comparison document?
3. Are you have plan to implement all functionality which we have in old developer portal? Do you have any plan release date with all old developer feature?

**Comment by mikebudzynski** [comment]
1. There are plans to deprecate the old developer portal (and the publisher portal) after we reach GA with the new portal. Details are still being worked on. Please, let us know if you have concerns.
2. Such document does not exist at the moment.
3. Most of the features are or will be replicated in the new portal, with the exception of "Applications" and possibly "Issues". Are there any particular features you are thinking of? Feature parity is planned for general availability - around October/November.

**Comment by yashwantsahu05** [comment]
Thanks for update, I am looking for feature to manage my resource(Word, PDF, file etc) document. I found option to upload it through **Media**  but I would like to manage is differently. 

Here I am looking to upload my resource file which nothing but help document about my API with some category tag. 
We require to display resource document on UI. Also looking for filter option based on category.

Above feature is available on Apigee Edge API Platform I am looking for similar kind of feature here as well.

**Comment by yashwantsahu05** [comment]
What is different between **Self hosted Portal** and **New developer Portal** option? 
As I can see that change which we are apply through new developer portal it will reflected. We can see our changes through opening same URL on new browser window. IMO we no require to Publish it - Correct me if I was wrong.

Only advantage I can see with **Self hosting** we got more control over (i.e Create own wizard etc). 

Looking forward for pros and cons to manage customization through **Self Hosting** over managing it with **Azure portal**.

**Comment by mikebudzynski** [comment]
> Here I am looking to upload my resource file which nothing but help document about my API with some category. We require to display resource document on UI. Also would like to filter resource document based on category..

Currently this is not supported, but we will keep it in mind for planning - thanks for raising the feedback. For now, you can work around the limitation by uploading your files to a storage account and linking them in the portal.

----

> What is different between Self hosted Portal and New developer Portal option?

The difference is explained here: https://aka.ms/apimdocs/portal

We recommend using the managed version, unless you have special requirements (like creating custom widgets), which are not supported by the managed version.

In the self-hosted portal, there is no "publish" button, but you still need to publish your website after you carry out your changes. It will work on localhost without publishing.
