### ISSUE TITLE
Operation details - descriptions of the request header items are truncated

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#910]
## Bug description

On the Operation-details page the description of the request headers may be truncated when the description is too long.
In the "Request parameters" section it works as expected.

## Reproduction steps

1. Go to the API details page of an API
2. Click on an operation
3. If the API contains requests with long description see that some of them will be truncated

## Expected behavior

New lines are created like in "Request parameters".

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
![image](https://user-images.githubusercontent.com/58420097/93177607-5df5bd00-f733-11ea-870c-3edfcdcc2453.png)

This is what it looks like

**Comment by azaslonov** [comment]
Hi @ZarTrox, found it and fixed. I will push along with other changes soon.
