### ISSUE TITLE
Following Link to API details page hides API: details widget

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#912]
## Bug description

When following a deep link to an API details page I get directed to the API details page but without any API selected.
When I select an API through the list of APIs widget I can navigate to the API but it looks like this:

![image](https://user-images.githubusercontent.com/58420097/93176071-fc345380-f730-11ea-8d22-99efffbbe018.png)

The API: details widget is missing!
Which means I cannot see the API details and therefore cannot **download the API definition.**
Further down I can see the Operation as expected.

## Reproduction steps

1. Create deep Link to an API 
2. Click on this deep link
3. Get directed to the Log-in page
4. Log-in 
5. See that now you are on the API details page but without API selected
6. Choose an API form the "list of APIs" widget
7. See the described Problem

## Expected behavior

When following the Deep Link optimally get directed immediately to the API details page and API (this is another issue with deep Links)

## Is your portal managed or self-hosted?

Managed

**Comment by ygrik** [comment]
For the managed version the fix will be deployed in a day. Please republish a portal to get the update.
If this fix doesn't help please send the APIM service name and details to apimportalfeedback@microsoft.com. We could take a look at it in your dev portal.
