### ISSUE TITLE
Improper behaviour in navigation menu

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#913]
## Bug description

When we click on any navigation menu item, navigation menu design is converted into vertical menu for fraction of seconds and coming back to normal design. something like dancing the navigation menu. please find screenshot for more details.
A clear and concise description of the bug. 

## Reproduction steps

1. Go to 'Home'
2. Click on 'any navigation menu item'
3. See behaviour

## Is your portal managed or self-hosted?

Managed 

## Additional context
Step 1:
![image](https://user-images.githubusercontent.com/30490543/93181429-15033000-f756-11ea-95a5-9a3e94e2dc1f.png)

Step 2:
![image](https://user-images.githubusercontent.com/30490543/93181582-3e23c080-f756-11ea-8d8b-afef9319c91f.png)

Step 3:
![image](https://user-images.githubusercontent.com/30490543/93181677-5b588f00-f756-11ea-8c1d-c32bfb15a5bb.png)

Note: Step2 is the improper behaviour. you can see this behaviour when click anywhere on the navigation menu section.

**Comment by CoumbaNDI** [comment]
We have the same problem

**Comment by JCAMPOLPA** [comment]
Same here

**Comment by azaslonov** [comment]
Yeah, this control is pretty clumsy, we'll need to look closer into better and proper customization approach. Meanwhile, please have a look at Collapsible panel size controls like min/max width (on different form factors, if needed). If can't figure out, let me know your service name, I'll see how to fine-tune it a bit.

**Comment by ThomasSmeets** [comment]
Same here, but strangely, I've 2 APIM near identical ( one created 2 months ago , and one created recently but only the recent one have this issue )

**Comment by azaslonov** [comment]
Actually I was able to repro this even on default template. Probably some styling issue. We'll investigate.

**Comment by azaslonov** [comment]
Found issue, will fix this soon.

**Comment by shashiguru** [comment]
Hi @azaslonov, Thanks for the quick fix. when can we expect changes for managed developer portal?
sorry to spamming another issue here. could you please look into https://github.com/Azure/api-management-developer-portal/issues/800 issue. i have raised long back and still open. i have provided all the information there.

**Comment by ygrik** [comment]
For the managed version the fix will be deployed in a day. Please republish a portal to get the update.
