### ISSUE TITLE
Force page refresh on popup based sign-in.

### ISSUE THREAD

**Issue by butsona** [Azure/api-management-developer-portal#916]
When using AAD to log into the portal the auto refresh doesn't occur. If you manually refresh the portal the menus are displayed (as expected). But we can't expect clients to "F5" the portal.

I think this might be duplicated but i can't find the original and it is still not working.

**Comment by azaslonov** [comment]
Is your AAD button on the home page?

**Comment by butsona** [comment]
yes, we have the button on the home page, is that a problem?

**Comment by azaslonov** [comment]
No problem, just wanted to confirm a possible reason. We'll fix this.

**Comment by azaslonov** [comment]
Fixed. The managed version should receive the update by end of the week.
