### ISSUE TITLE
New MS Developer portal ADB2C login - user is not logged in for first time (handleRequestCallback is not invoked for first time)

### ISSUE THREAD

**Issue by maheshkumagali** [Azure/api-management-developer-portal#921]
We are customizing the new developer portal (https://github.com/Azure/api-management-developer-portal)

We wanted login redirect instead of login popup for ADB2C login. We are able to show redirect now instead of popup by making a change in aadService,ts -> runAadB2CUserFlow method.

We wrote handleRequestCallback for the callback.

Issue: First time when the user logs in, the callback is not getting invoked after the loginRedirect. Second time when we click on ADB2C login, as there is already a token, loginRedirect is skipped and callback is invioked. In other words, even though user is able to login successfully, as the callback is not called application is not showing user as logged in. Second time, when we click on ADB2C login button, it is showing correctly.

PFA the code where we did the changes.

![Z9cB4](https://user-images.githubusercontent.com/13291957/93315474-b955a700-f828-11ea-8535-635d0fc08586.png)

**Comment by azaslonov** [comment]
Hi Mahesh, since you guys relying on redirect instead of a popup, I think you could you the concept of route guards. In the simplest way it looks like this:

```
export class DefaultRouteGuard implements RouteGuard {
    public async canActivate(route: Route): Promise<boolean> {
        /* here you could can inspect URL for B2C artifacts and put your "handleRedirectCallback" logic */
        return true;
    }
}
```

Hope that helps.

**Comment by azaslonov** [comment]
Closing for now, please feel free to re-open shall you need further assistance.
