### ISSUE TITLE
Multiple font styles cannot be used.

### ISSUE THREAD

**Issue by jejip** [Azure/api-management-developer-portal#924]
## Bug description

When uploading multiple font files (woff), with different weights of the same family, only the last font / weight from the family is shown and can be used. Subsequently, only one weight can be applied to text styles. This makes it impossible to use a bold font for headings and a regular font for body, of the same family.

## Reproduction steps

1. Go to the Styles page
2. Upload a new font, e.g. 'fontname-Regular.woff'
3. Upload another font, 'fontname-Bold.woff'
4. The first uploaded font is replaced by the second uploaded font.

## Expected behavior

I expect fonts of the same font family to be combined, and then to be accessible when defining a style (by defining the font-weight instead of just a 'bold' button). An alternative solution is that the fonts can be split, but keep their appearance. That means the font styles each have their own font name and can be selected in the dropdowns.

Could you also verify which font formats you support? Woff2 or EOT didn't seem to work.

## Is your portal managed or self-hosted?

Managed

## Environment

- MacOS 15
- Edge browser 86

## Additional context

A screenshot of 2 uploaded fonts, a bold and regular one.
![Screenshot 2020-09-17 at 11 09 11](https://user-images.githubusercontent.com/3678993/93450409-3ab74300-f8d6-11ea-8f2b-460eeb437896.png)

**Comment by azaslonov** [comment]
Hi @jejip, yes, this is planned work, the font family designer should land by end of Oct.

Btw, is there a specific font you're looking for? Is it missing from the list of available fonts?

**Comment by jejip** [comment]
Okay that's great to hear! Looking forward to the release.

We're using a font that's not available on Google fonts. As we want the portal to look a like our other products / portals, we want to use our default brand typeface (Freizeit).

**Comment by jejip** [comment]
Any updates on the release that you expected by the end of Oct?

**Comment by azaslonov** [comment]
The feature got moved a little due to other high-priority works, but it is already in development and should be ready in the next couple of weeks.

**Comment by jejip** [comment]
👏 Sweet, thanks!
