### ISSUE TITLE
Navigation items "jump" on click

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#927]
## Bug description

Some navigation items "jump" around/disappear during the loading time of the page.
For a precise description of the bug see the attached gif.

## Reproduction steps

- Have multiple horizontal navigation elements

## Is your portal managed or self-hosted?

Managed

## Additional context

This issue occurred this week the first time.
![2544E388-3430-4894-98D1-5D8EF212CD17](https://user-images.githubusercontent.com/58420097/93565179-36009680-f98b-11ea-8296-a6ded826b00f.GIF)

**Comment by shashiguru** [comment]
Same here. its happening for some fraction of seconds.

**Comment by AnRei123** [comment]
The behavior seem to have changed today. Today, we hadn´t been able to reproduce this error.

**Comment by azaslonov** [comment]
Right, hotfix has been deployed everywhere
 Please just re-publish.

**Comment by shashiguru** [comment]
@azaslonov, Is this deployed for managed version as well? i still see the same issue after re-publish.

**Comment by AnRei123** [comment]
me, too.
