### ISSUE TITLE
Request headers description field is clipped

### ISSUE THREAD

**Issue by JanneMattila** [Azure/api-management-developer-portal#928]
## Bug description

New version of managed developer portal has UI issue that clips the request headers description field.

## Reproduction steps

1. Edit API operation at Azure Portal
2. Add following request header to the API operation: `SuperImportantID` with description `Yes this is very important header and you should be using it because otherwise it will not work and you won't like that.`
3. Open developer portal and above API operation
4. Notice that request header description is clipped:

![request header is clipped](https://user-images.githubusercontent.com/2357647/93567438-4fa7db00-f997-11ea-8bc1-a6aee6c521f2.png)

## Expected behavior

It should display the description text in multiple lines, and it should be fully visible:

![request header description fully visible](https://user-images.githubusercontent.com/2357647/93567567-8251d380-f997-11ea-9458-20c650048d06.png)

This was screen capture from earlier developer portal version.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

demo9001

## Environment

 - Operating system: Windows 10
 - Browser: Multiple browser: Edge latest, Chrome latest

## Additional context

N/A

**Comment by MiikaAntila** [comment]
We are also having this issue in our managed production portal that appeared after publishing.

**Comment by azaslonov** [comment]
Hi @JanneMattila, @MiikaAntila, this issue has been fixed in #919. The managed version will get it at the beginning of next week.
