### ISSUE TITLE
Widget for inserting table

### ISSUE THREAD

**Issue by hansukyang** [Azure/api-management-developer-portal#931]
Hi - is there a way to insert a table, similar to the one that's generated for the API (see example below)? I can't seem to find a widget that would allow one to create this. Thank you. 

![image](https://user-images.githubusercontent.com/11863789/93727111-3b105080-fbec-11ea-9b90-45d6a4c6f818.png)

**Comment by azaslonov** [comment]
Hi @hansukyang. Yes, this is a planned feature. We'll update with ETA soon.

**Comment by hansukyang** [comment]
Fantastic, much appreciate the information.

**Comment by jejip** [comment]
Great to hear it's planned. Very much needed!

**Comment by Svae** [comment]
Any updates on this? 😊

**Comment by mikebudzynski** [comment]
Not at this moment, we will update the thread when we have an ETA.

**Comment by azaslonov** [comment]
Update: The feature is ready, coming in the next release.

**Comment by hansukyang** [comment]
Thank you!!
