### ISSUE TITLE
Request: Hide or delete not needed default pages

### ISSUE THREAD

**Issue by ilspiert** [Azure/api-management-developer-portal#932]
When customizing the Developer Portal for my needs I want to remove or disable the following pages because I do not need them for my customization:
- /signup-oauth
- /confirm-password
- /change-password
- /profil
- /sign-up

With disable I mean, setting a option on the page, default should be FALSE. If set to TRUE, the WebApp should return a 404 if someone browses on that page.

**Comment by azaslonov** [comment]
Hi @fsettele, we'll see what we can do.

**Comment by geologyrocks** [comment]
+1 I'd like a way to remove these from the menu ribbon
![image](https://user-images.githubusercontent.com/28485583/95576713-d39a3380-0a28-11eb-94cf-6547a6060bec.png)

**Comment by mikebudzynski** [comment]
@geologyrocks The screenshot you provided is for the legacy developer portal, while this repository is specific to the new developer portal. The new developer portal allows you to remove unnecessary menu items.

**Comment by azaslonov** [comment]
Closing, since question answered.
