### ISSUE TITLE
OpenAPI schema issue when using polymorphism 

### ISSUE THREAD

**Issue by konsta2106** [Azure/api-management-developer-portal#935]
## Bug description

Hello. I'm using polymorphism in OpenAPI spec. In case of Swagger when it generates documentation, i can actually explore and expand all schemas used by polymorphism. In case of Azure APIM and developer portal, i can only see references to models, but i can't click and expand and explore schemas.

## Reproduction steps

1. Go to developer portal 'https://xxxxxxxxx.developer.azure-api.net/'
2. Click on 'Explore APIs' and select API. Select operation that is using polymorphism.
3. Scroll down to needed method that is using polymorphism and choose "schema view"
4. See error -> We can see references to models/schemas used by oneOf/anyOf but we cant see any of schemas for those references (links are not clickable)
![Screenshot 2020-09-17 at 10 19 06](https://user-images.githubusercontent.com/54150208/93765976-6ad84c00-fc1e-11ea-8a9a-d932d24f4d48.png)

## Expected behavior

I would expect same kind of behaviour that for example Swagger does.
![Screenshot 2020-09-17 at 10 13 09](https://user-images.githubusercontent.com/54150208/93766744-8bed6c80-fc1f-11ea-9c7d-12abf3ce8043.png)
And after i click on one of them it will expand schema:
![Screenshot 2020-09-21 at 15 26 42 copy](https://user-images.githubusercontent.com/54150208/93766761-93147a80-fc1f-11ea-8dd6-66d46a4164bb.png)

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

none

## API Management service name

Contoso

## Environment

 - Operating system: [mac OS]
 - Browser: [Google Chrome]

**Comment by azaslonov** [comment]
Hi Konstantin, we'll discuss this and see what we can do. Thank you.

**Comment by konsta2106** [comment]
Hello @azaslonov. Is there any update on this?

**Comment by konsta2106** [comment]
Hi @azaslonov. It Would be nice if there is any information or update about this feature since it is pretty crucial for our partners to see what properties are needed by different schemas and to see also descriptions to every property. At this point there is no any information with straight reference to oneOf or anyOf schema and they can not be discovered anywhere in portal. Only one pre-defined example from one schema is visible

![Screenshot 2020-12-01 at 14 54 17 copy](https://user-images.githubusercontent.com/54150208/100744114-f839d880-33e5-11eb-9f83-5b2540babbac.png)
---
![Screenshot 2020-12-01 at 14 54 21](https://user-images.githubusercontent.com/54150208/100744178-143d7a00-33e6-11eb-966b-80e1f7ba3ffa.png)
---

So yes its pretty crucial to have those schemas under definitions like every other schema for example like error response and not to have ProductCreate definition as empty one because of anyOf/oneOf reference:

![Screenshot 2020-12-01 at 15 10 16](https://user-images.githubusercontent.com/54150208/100745061-6501a280-33e7-11eb-91aa-36e6e1528095.png)

**Comment by mikebudzynski** [comment]
@konsta2106 Thanks for bringing this up again. It does seem like a bug and we will fix it. We don't have ETA at this moment.

**Comment by konsta2106** [comment]
Thank you for your response @mikebudzynski. Good to hear that this is moving forward.

**Comment by konsta2106** [comment]
Hello @mikebudzynski. There is still no ETA for this issue?

**Comment by mikebudzynski** [comment]
I just added the item to the Backlog project, where we short-list items for development. We don't have an ETA to share at this moment.

**Comment by TimMnz09** [comment]
Hello @mikebudzynski, any update on this?

**Comment by mikebudzynski** [comment]
No update at the moment. We do hope to address API reference page bugs by the end of the year, but this timeline may shift.

**Comment by konsta2106** [comment]
@azaslonov Hello.
I see that PR is closed and the update is included in the last release. Is this already applied to the managed version of the developer portal? I have even tried to republish the portal, but can't see any changes so the issue is still reproducing for us.

**Comment by mikebudzynski** [comment]
The release is still rolling out. It may take up to two weeks to have it rolled out to all services.

**Comment by leorosignoli** [comment]
@mikebudzynski should this have been fixed yet?  
I'm also facing the same issue.     

## schema: 
<img width="717" alt="Image" src="https://github.com/user-attachments/assets/58c4515d-da27-4276-8654-c38a65c4d376" />

## swagger render: 

<img width="749" alt="Image" src="https://github.com/user-attachments/assets/42c2a69a-7ae1-4f82-a635-050e6b311eb7" />

## api Management render (doesn't show much): 

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/662e5726-5272-4aa6-8fcc-134c62460bdc" />
