### ISSUE TITLE
APIM Developer Portal in combination with AD B2C forgot your password

### ISSUE THREAD

**Issue by RG-44** [Azure/api-management-developer-portal#937]
I have configured in API Management Developer Portal the Identity Provider Azure AD B2C and are successfully using the Sign in User flow to login into the API Management Developer Portal. 

Though when the user clicks “Forgot your Password?” on this flow, the user is redirected back to API Management Developer Portal with error “AADB2C90118: The user has forgotten their password”. 

I would have expected that, API Management Developer Portal catches this exception and automatically redirects to the Password reset User flow, which I also have configured in the same Identity Provider Azure AD B2C.

**Comment by azaslonov** [comment]
Hi @RG-44, this issue has been fixed in #899. The managed version will receive this fix by end of this week.
