### ISSUE TITLE
Layout for definitions (inside an operation) in the Developer Portal UI

### ISSUE THREAD

**Issue by stijntjeleijten** [Azure/api-management-developer-portal#938]
I recently started using APIM together with the Developer Portal. I was wondering if the Developer Portal has a feature to display a $ref (schema components / APIM Definitions) for an operation in the Developer Portal UI. Maybe I am doing something wrong, but as far as I can see my OpenApi specification is correct.

Below is my OpenAPI specification of an operation called "data"
```json 
{
   "/Data":{
      "post":{
         "summary":"Data",
         "operationId":"data",
         "parameters":[],
         "requestBody":{
            "description":"Request Payload",
            "content":{
               "application/json":{
                  "schema":{
                     "$ref":"#/components/schemas/DataRequestBody"
                  },
                  "example":{
                  }
               }
            }
         },
         "responses":{
            "200":{
            }
         }
      }
   }
}
```
Inside this operation I made a reference to a schema component called "DataRequestBody". This definition contains the following spec:
```json
{
    "type": "object",
    "description": "Contains the body params needed to request data",
    "properties": {
        "chartType": {
            "type": "string",
            "description": "The chartType is used to specify a presentation purpose",
            "enum": [
                "someValue1",
                "someValue2",
                "someValue3"
            ]
        },
        "filters": {
            "type": "array",
            "description": "Contains a collection of filters to request the right subset of data",
            "items": {
                "$ref": "#/components/schemas/filter"
            }
        }
    }
}
```
As you can see I made a reference to a schema component called "filter" inside this definition.

When looking inside my Developer Portal (page: api-details) I can see that my reference to the schema component "filter" is highlighted as a link:
![image](https://user-images.githubusercontent.com/24482893/93756695-c4804c80-fc05-11ea-82f1-22bb7cd7ee2d.png)

The target of this link is _https://{{apimName}}.developer.azure-api.net/api-details#api={{currentApiName}}&operation=getdata&definition=filter_ . But when clicking the link the Developer Portal does not present a layout containing the definition.

Is this something that is currently not supported inside Developer Portal? Or am I doing something wrong with my specification?

**Comment by azaslonov** [comment]
Hi @stijntjeleijten, are you sure you actually have a definition for `#/components/schemas/filter`? If yes, it would be great if could send us your full OpenAPI document for further debugging: apimportalfeedback@microsoft.com

**Comment by stijntjeleijten** [comment]
Thanks for your quick response! I emailed my full OpenAPI spec

**Comment by stijntjeleijten** [comment]
I recently found out what went wrong... issue was that the reference is case sensitive. When updating my component to lowercase everything worked fine
