### ISSUE TITLE
Static files cache doesn't reset with new releases.

### ISSUE THREAD

**Issue by t-higgs-qa** [Azure/api-management-developer-portal#939]
## Bug description

When editing the developer portal on Chrome the "styles" page does not render properly. It looks like the styles are missing, colors do not render, buttons are missing their colors and icons, etc. This works as expected in Edge. 
![image](https://user-images.githubusercontent.com/58445030/93918763-6c634c00-fcd2-11ea-9ff6-b0ea5f425086.png)

## Reproduction steps

1. Go to the edit developer portal page
2. Go to the "Styles" page

## Expected behavior

The proper styles should load on Chrome, colors should be rendered, buttons for adding fonts etc should be displayed. 
![image](https://user-images.githubusercontent.com/58445030/93919301-18a53280-fcd3-11ea-9c09-03310bdc56a8.png)

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Microsoft Windows 10 Pro Version 10.0.19041 Build 19041
 - Browser: Google Chrome
 - Version: Version 85.0.4183.102

**Comment by azaslonov** [comment]
Hi @t-higgs-qa, yep I saw this couple of times as well. Can you please try to refresh the page with Ctrl+F5 and see if that helps? Meanwhile, we'll try to catch the moment when that happens and fix that.

**Comment by t-higgs-qa** [comment]
Ctrl + F5 did not work, but opening developer tools in chrome and then right clicking the refresh button and clicking Empty Cache and Hard Reload did. Using incognito mode worked as well. 
![image](https://user-images.githubusercontent.com/58445030/93922180-34aad300-fcd7-11ea-934c-d8ab22686efa.png)

This was happening to others in my organization as well.

**Comment by azaslonov** [comment]
Ok, looks like figured what's the issue. We'll fix it in one of next releases.

**Comment by azaslonov** [comment]
Fixed on the backend, awaiting deployment.
