### ISSUE TITLE
Try it: Subscription key drop down list - not user friendly naming

### ISSUE THREAD

**Issue by maras2002** [Azure/api-management-developer-portal#945]
Is it possible (and more user friendly) to put instead of Primary-XXX or Secondary-YYY the display name of Subscription Key? We have customers with multiple subscription keys which we allow to do different job (i mean on differetn set of data) even within the same Product and they do not know what key to choose as they all look similar. WIth display name it would be easier to do so.

![image](https://user-images.githubusercontent.com/52015875/94267439-e4807a80-ff3b-11ea-85e0-76eb69814f09.png)

**Comment by mikebudzynski** [comment]
Fixed with the PR linked above and included in the releases 2.5.2.
