### ISSUE TITLE
Parent component method is not called from child component 

### ISSUE THREAD

**Issue by Vinoth-44** [Azure/api-management-developer-portal#951]
**Expectation:**  Parent component method should be called from child component HTML using $parents[1].parentMethodName

**Issue :**  We are not able to call parent class method of tab1.ts from child class of product-list.html template. 

**Description** :

**Scenario:** 
1. First, we need to show all list of API products in first tab(tab1).  so, for this, we have reused `<product-list-runtime></product-list-runtime>` component with in tab1.html
 
2. After that, When user click on product title from product-list.html, Parent method **test** should be called at tab1.ts. Unfortunately,  We are getting an error. I have attached screenshot for your ref.

We have to call **test** method in tab1.ts from child component of product-list.html

 We have component structure like below,

1. api-page.html `<!--  grand parent -->,`

`<api-page>` 
 `<tab1></tab1> ` 
  `<tab2></tab2> `
`</api-page>`

2. Now, tab1.html `<!--  child component -->` will have,

`<product-list-runtime></product-list-runtime> `
`<!-- ko if: showProductDetails -->`
 `   <product-details-runtime></product-details-runtime>`
  `  <!-- /ko -->`

3. tab1.ts will have,

` public test(product):void {`
`console.log("parent method is called");`
`this.showProductDetails(true)`
`}`

3. product-list.html will have below click event in product list,

`<a data-bind="attr: { href: $component.getProductUrl(product) }, click: function(product){ $parents[1].test(product) }, text: product.displayName"></a>`

Note: Once parent method of test is called, We will be hiding **product list component** and we have to show **product details component** using showProductDetails boolean and also page will not get refreshed. We will be switching the components in tab1.html without page refresh. This is our requirement

When we try to print $parents as json in html, it has null value

![clickEventissue](https://user-images.githubusercontent.com/35361553/94581259-7e2b8d00-0298-11eb-9158-7b93352412fd.PNG)

**Comment by azaslonov** [comment]
Hi @Vinoth-44, I didn't try but probably $parent doesn't work from withing components. Also, this doesn't look like the right approach, because it couples components. There might be other ways to achieve that:
1. Use EventManager, that allows to subscribe/dispatch events;
2. Use component events, so that parents could subscribe for child events. For instance, you can look at this example:
`<tag-input params="{ scope: 'apis', onChange: onTagsChange }"></tag-input>`

Hope that helps.

**Comment by Vinoth-44** [comment]
Could you give some example with parent, child component in detail ? We are not sure how to implement this using EventManager

**Comment by azaslonov** [comment]
Have you looked at the [tag-input](https://github.com/Azure/api-management-developer-portal/tree/master/src/components/tag-input) component? In general, you can look at @Param() and @Event() decorators usage across the project to get more examples.

**Comment by azaslonov** [comment]
@Vinoth-44, does this help at all?

**Comment by Vinoth-44** [comment]
Yes @azaslonov , Above example was helped. Thanks 😄 . If need any further assistance on this, I will let you know.

**Comment by azaslonov** [comment]
Closing as the issue seems to be resolved.
