### ISSUE TITLE
How to use Sign-in with Azure AD on APIM - New Developer Portal, please suggest

### ISSUE THREAD

**Issue by anil8623** [Azure/api-management-developer-portal#956]
Hi Everyone,

I'm planning to enable Azure AD on APIM instance, to make sure Azure AD users to login the New Developer Portal.

From the various documents I've seen once Azure AD enabled then Legacy Developer portal will get the option "Sign-in with Azure AD"
But not sure on how to get that option on New Developer Portal - Could someone help me understanding this and gimme some options on this.

Also I need to know is there any impact with the existing users on APIM Instance with Auth Type : Basic, Azure - Please help me

**Comment by mikebudzynski** [comment]
Documentation is located here: https://docs.microsoft.com/azure/api-management/api-management-howto-aad If you need assistance, please contact Azure support.

There will be no impact on the existing users as long as username + password authentication is enabled.
