### ISSUE TITLE
AAD B2C signin - The migrate procedure does not replace the signin-aad-b2c parameters

### ISSUE THREAD

**Issue by MassimoC** [Azure/api-management-developer-portal#958]
## Bug description
The migrate procedure does not replace the signin-aad-b2c parameters.

## Reproduction steps
Add an AAD B2C identity to the developer portal and migrate it from one environment to the next one.
If you use a self hosted portal, the "signin-aad-b2c" object will always refer to the IDP of the source environment.

**Details**
I moved the developer portal from DEV environment to the STG environment as described here https://github.com/Azure/api-management-developer-portal/wiki/Migrate-portal-between-services

The scripts/migrate.js downloads the blobs from DEV and upload them to STG as-is **without any changes** (I am using the self-hosted option). Meaning the content of the $web/signin/index.html is the same in every environments.

The parameters ClientId, Authority, etc... should be replaced by the migrate.js procedure.
![image](https://user-images.githubusercontent.com/8393694/95063626-de8a5680-06fe-11eb-8aa4-6eb04d2ede87.png)

## Expected behavior

Parameters should be replaced by the migration script or the migration procedure should state that a new publish per environment have to be trigger.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.5.0

**Comment by mikebudzynski** [comment]
@MassimoC - You can use [DevOps Resource Kit](https://aka.ms/apimdevops) to migrate Azure AD B2C configuration settings. Note that you need to change reply URL in Azure AD B2C application. 

We have plans to provide support for the developer portal in the Resource Kit: #975

**Comment by MassimoC** [comment]
@mikebudzynski I am not sure if I understood your answer. 
In my case APIM instance and AAD B2C are rolled out and correctly configured via Azure DevOps.

The developer portal (self-hosted) has a different lifecycle.
We build it once (against dev) and we move the artifacts to the next environnements.
There is only one thing that is hard coded (as a result of the build against dev) is the AAD B2C sign-in configuration.
We workarounded this with a  basic Powershell "find and replace" in the index.html at the release time.
