### ISSUE TITLE
URL encoding for query parameters in the interactive console

### ISSUE THREAD

**Issue by alohaninja** [Azure/api-management-developer-portal#96]
**Describe the bug**
When supplying input parameters for API methods - we should URL-encode the values before invoking the method. This matches the behavior present in Swagger UX. 

**To Reproduce**
1. Click an API Method
2. Click Try It
3. Provide an input field with characters that need escaped (e.g. \\, etc.)
### Swagger UX 
![image](https://user-images.githubusercontent.com/26234626/60059463-895d3980-96a1-11e9-948a-5693202db357.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/26234626/60059471-9548fb80-96a1-11e9-94a2-826f1c98b9fb.png)

**Screenshots**

### APIM UX

![image](https://user-images.githubusercontent.com/26234626/60059522-b14c9d00-96a1-11e9-8992-f0d000f814c9.png)

![image](https://user-images.githubusercontent.com/26234626/60059507-a7c33500-96a1-11e9-8234-33865cc66a70.png)

**Additional context**
This behavior was broken in previous DEV portal - hoping we can improve this for Portal vNext!

**Comment by mikebudzynski** [comment]
Thanks @alohaninja for reporting the bug. We will update the Issue soon.

**Comment by mikebudzynski** [comment]
Closed with https://github.com/Azure/api-management-developer-portal/pull/101/files
