### ISSUE TITLE
Custom attributes not being imported

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#961]
Hi,
When importing an Open API 3.1 specification which has a custom attribute like below

![image](https://user-images.githubusercontent.com/62035456/95404649-1947f500-0972-11eb-869c-a0f4acbd3bdb.png)

It appears the import process excludes any custom attributes. This can be proven by viewing or downloading the schema from the APIM portal. Are you able to confirm if this is a bug or the APIM portal does not support custom attributes?

Thanks

**Comment by mikebudzynski** [comment]
API Management doesn't support extension properties. OpenAPI support limitations are documented here: https://docs.microsoft.com/azure/api-management/api-management-api-import-restrictions#a-nameopen-api-aopenapiswagger

We do plan to implement support for extension properties, tentatively within a year.
