### ISSUE TITLE
Unable to fetch subscriptions details in individual product page. Response needed.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#963]
## Bug description
Subscriptions call getting failed while pulling the data for individual product, its failing with 403-forbidden. i have subscribed to that product and able to see subscriptions details in profile page. its logging in console as 

![image](https://user-images.githubusercontent.com/30490543/89000798-e819cb80-d315-11ea-822c-9842329d582c.png)

Subscriptions call in network tab:
![image](https://user-images.githubusercontent.com/30490543/89001175-0cc27300-d317-11ea-8616-4ae2877287f5.png)

## Reproduction steps

1. Go to 'Products' page
2. Click on any product
3. Its showing as You don't have subscriptions yet.

## Expected behavior

It should show subscriptions details.

## Is your portal managed or self-hosted?

Managed 

Profile page:
![image](https://user-images.githubusercontent.com/30490543/89001045-89a11d00-d316-11ea-9889-6d39a36553d0.png)

Products page:
![image](https://user-images.githubusercontent.com/30490543/89001010-742bf300-d316-11ea-9def-95c3522dacf7.png)

Note: This issue https://github.com/Azure/api-management-developer-portal/issues/800 raised long back and also sent an email with details of apim instance. could you guys please look into this.

**Comment by azaslonov** [comment]
Hi @shashiguru, are your subscriptions having "All APIs" scope by chance?

**Comment by shashiguru** [comment]
No, we have different products for different set of APIs.

**Comment by azaslonov** [comment]
Ok, I found your email with service name (looks like missed it, sorry about that), I'll try to repro your case.

**Comment by shashiguru** [comment]
Great to hear that! Please let me know if you need any other information.

**Comment by azaslonov** [comment]
Actually, you could capture network traces, the same that you show on the screenshot above, and send us to the same email (just in case we won't be able to repro on our side). Thanks in advance.

**Comment by shashiguru** [comment]
@azaslonov, please close this issue. It's working fine after deleting some WAF rules in application gateway. Thanks for your support.

**Comment by azaslonov** [comment]
Great! Thanks for confirmation.
