### ISSUE TITLE
API call is not working on New Developer portal, but works on Legacy Developer portal

### ISSUE THREAD

**Issue by anil8623** [Azure/api-management-developer-portal#964]
Hi,

I'm facing a issue with the API calls.

One of my API call (GET) is working fine when I try from Legacy Developer portal (getting the resultant - 200 OK with the expected output)

but when I try the same API call from New Developer Portal - it given me 404 Forbidden error

and also from the error I seen "XSRF check failed"

Could someone please help me in understanding why the API call is success on Legacy Portal and not in New developer portal.

If this is related to any policy settings to be done on please guide me - I'm not an end user of the API, I'm just managing the APIM

Regards,
Anil Kumar K

**Comment by mikebudzynski** [comment]
@anil8623 We suggest that you request assistance via Azure Support. We limit this repository to bug reports and feature requests only.
