### ISSUE TITLE
The developer portal should auto scroll  to the selected API Operation

### ISSUE THREAD

**Issue by bala-muthugurusamy-by** [Azure/api-management-developer-portal#966]
## Bug description
 
There is an issue with multi-lines API description in developer portal, selecting the API Operation is not auto scrolling to the API Operation detail widget. Because of this the developer portal user feels that  API Operation select is not functioning.  If the API description has more than 30 lines, this problem can be easily reproduced.   

## Reproduction steps

1. Import any API Spec with more than 30 lines in description 
2. Publish the API
3. Go to developer portal
4. Select the `DEL` API Operation 
<img width="1656" alt="del-api-op-selected" src="https://user-images.githubusercontent.com/61602125/95007564-f90ce480-05c5-11eb-91d0-760ff7d4737d.png">
5. Check the developer portal and wait for sometime<br>
6. Change the API Operation selection to `PUT`
<img width="1653" alt="put-api-op-selected" src="https://user-images.githubusercontent.com/61602125/95007565-fc07d500-05c5-11eb-9f0a-ed507f29cf09.png"><br>
7. Check the page, it is not auto scrolling to the selected API Operation detail widget.
 it gives the impression that nothing has been fetched. 

## Expected behavior

Selecting API Operation should automatically scroll down to the API Operation Widget. 

## Is your portal managed or self-hosted?

Managed  

## Environment

 - Operating system: any
 - Browser: any

**Comment by mikebudzynski** [comment]
@bala-muthugurusamy-by Developer portal already supports scrolling to the selected API operation. You need to enable this option in the configuration of the API operation details widget:

![image](https://user-images.githubusercontent.com/40186513/95781231-3803ff80-0c82-11eb-822f-af0e2db900a3.png)

**Comment by bala-muthugurusamy-by** [comment]
> @bala-muthugurusamy-by Developer portal already supports scrolling to the selected API operation. You need to enable this option in the configuration of the API operation details widget:
> 
> ![image](https://user-images.githubusercontent.com/40186513/95781231-3803ff80-0c82-11eb-822f-af0e2db900a3.png)

@mikebudzynski  Can this option be enabled by default?

**Comment by mikebudzynski** [comment]
> Can this option be enabled by default?

We received negative feedback when we piloted enabling this option by default. Is it a concern to you that it's not enabled by default?
