### ISSUE TITLE
Missed functionality of Username and Password identity in new developer portal

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#967]
## Bug description
Username and password identity functionality in not working in new developer portal. in legacy developer portal, if we didn't use User name and password identity then we should not have the signin form in signin page. signin form only be available if APIM is configured with username and password identity. if we dont have this functionality then there is no use of username and password identity in APIM.

## Expected behavior
If we are not using username and password identity in APIM

Legacy developer portal:
![image](https://user-images.githubusercontent.com/30490543/95716831-ae583000-0c89-11eb-93b9-c86c10523d0d.png)

New developer portal:
![image](https://user-images.githubusercontent.com/30490543/95716607-56b9c480-0c89-11eb-8b06-dd29d2ef3080.png)

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
@shashiguru You need to remove the sign-in widget from the sign-in pages yourself and republish the portal.

**Comment by shashiguru** [comment]
@mikebudzynski, yes. I can do that but what is the use of username and password identity in APIM?

**Comment by mikebudzynski** [comment]
I don't understand your question, @shashiguru
