### ISSUE TITLE
Collapsable menu configuration

### ISSUE THREAD

**Issue by adamstruck** [Azure/api-management-developer-portal#968]
Feature request: add the ability to configure the color of the hamburger and close icons used by the collapsable menu.

**Comment by qsevers23** [comment]
Is there any update on this?

**Comment by azaslonov** [comment]
@qsevers23, sorry, not yet. Current ETA is mid-March.

**Comment by azaslonov** [comment]
@adamstruck, the fix is coming soon, please use #1461 for tracking. I'm closing this one as duplicate.
