### ISSUE TITLE
Update VNet troubleshooting guide to reflect endpoints required for developer portal

### ISSUE THREAD

**Issue by azaslonov** [Azure/api-management-developer-portal#97]
[Common Network Configuration Issues](https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet#-common-network-configuration-issues)

**Comment by mikebudzynski** [comment]
Added an explanation in documentation: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal#what-do-i-need-to-configure-for-the-new-portal-to-work-in-my-api-management-service-in-vnet

Other articles have been updated as well.
