### ISSUE TITLE
UX/CI issue on API details page and Try it panel - unconfigurable text and border colors

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#971]
## Bug description

I chose the following settings on the style page for formatting code snippets:
![LayoutPagePreview](https://user-images.githubusercontent.com/58981351/95953773-9ce26580-0dfa-11eb-94a4-031c96051170.PNG)

On the API details page and the related Try it panel, there are a few UX/CI issues regarding some font and frame colors that cannot be configured currently:

1) On the API details page in the Example boxes, the text is displayed with two colors (violet and green) that seem not to be configurable on the Styles page of the portal. Is there any other way to configure these styles color according to our CI colors and according to ensure legibility depending on the chosen background color?

2) On the Try it panel on the top, there are boxes with green frame color to select or enter dedicated values for an API request. I tried to change the color of the frame in the section form controls on the style page of the DevPortal, but even on the styles page my changes are not reflecting. I cannot change the color of the frame. Looks like a bug. This green is not consistent to our CI branding colors.
![FormControlBorderColor](https://user-images.githubusercontent.com/58981351/95954647-eda68e00-0dfb-11eb-866e-d97c1ddeaa92.PNG)

3) On the Try it panel at the end, for the http request details frame, the background color is not in synch with the configuration on the Styles page of the DevPortal, but here parts of the font colors and the frame color is synched with the settings on the Styles page. There is a blue font that I do not know how to change, for example, the blue font of the term "Cache control".

Here a screenshot to depict how the above shown settings on the Styles page do currently reflect on the API details page and the Try it panel:
![ApiDetailsPageAndTryItPanel](https://user-images.githubusercontent.com/58981351/95953980-f0ed4a00-0dfa-11eb-8873-9aeb6c3875dd.PNG)

## Expected behavior

All colors for texts and frames that are visible to the portal users are consistently configurable from the Styles page of the  portal.

(I thought about using a black background color for displaying code snippets, but with the current configuration options this does not make sense as the preconfigured color schema for the fonts in the example box are two dark. As a work around, I chose the grey background color which is also fine, but the preconfigured text and frame colors do NOT fit with our CI colors!)

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Google (latest version)

**Comment by AnRei123** [comment]
Add on: The **color of the Try it button** on the API details widget should also be configurable on the Styles page of the DevPortal.

**Comment by azaslonov** [comment]
Makes sense. We'll add customization options.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
