### ISSUE TITLE
How to expose Microsoft developer portal API 

### ISSUE THREAD

**Issue by anjusharma17** [Azure/api-management-developer-portal#98]
Hi,
I am looking for some document, which defines how to expose the azure developer portal API call's?
For e.g, In my storage account, there are some files or blobs which i want to display into my customized developer portal. How to get the file service or blob services APIs expose information so we can hit them and get the required information.

**Comment by anjusharma17** [comment]
I am able to get the list of API's by hitting APIM url, using subscription key for authorization (_PFA screenshot_). I did this  by going through code.

![postman](https://user-images.githubusercontent.com/17688551/60099007-66e82080-9774-11e9-89aa-3cd371425444.png)

So, can you share some document form where we can this information?

**Comment by mikebudzynski** [comment]
Which storage account are you referring to? You can expose files from a storage account using SAS keys.

If you want to track developer portal calls, you can use the developer tools in your browser.

**Comment by mikebudzynski** [comment]
Issue inactive.
