### ISSUE TITLE
REST API publish is not working

### ISSUE THREAD

**Issue by janoosthoek** [Azure/api-management-developer-portal#985]
I'm experiencing an issue with a managed portal in a CI/CD enviroment.

The call to https://xxx/publish 
is responding with 'OK', but nothing happens.

If i go to the portal admin interface and hit the button 'publish', then it works correctly. Also in APIM portal page it works.

Anyone else seen these issues? Is there perhaps a new ARM call to publish the portal after updating the content?

**Comment by mikebudzynski** [comment]
@janoosthoek Can you check the following Issue and all linked Issues for reference? https://github.com/Azure/api-management-developer-portal/issues/888 and, specifically, https://github.com/Azure/api-management-developer-portal/issues/826#issuecomment-683061925

We're actively working on exposing the publishing API endpoint via ARM. ETA is ~2-3 months, including the roll-out.

**Comment by janoosthoek** [comment]
@mikebudzynski appreciated the fast feedback. I did some testing today and it required a few tweaks to work on the latest APIM. Allow me to share the PowerShell snippet for someone else:


```
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Content-Type", 'application/json')
$headers.Add("Authorization", $apimRestSAS)

$body = @{
    keyType = "primary"
    expiry = [DateTime]::UtcNow.AddDays(1).ToString("s", [CultureInfo]::InvariantCulture);
}
$bodyJSON = $body | ConvertTo-Json

$apimPublishUserTokenUri = "https://${apimName}.management.azure-api.net/subscriptions/00000/resourceGroups/00000/providers/Microsoft.ApiManagement/service/00000/users/1/token?api-version=2019-12-01"
$response = Invoke-RestMethod -Uri $apimPublishUserTokenUri  -Method Post -Headers $headers -Body $bodyJSON
```
