### ISSUE TITLE
Subscriptions details in profile page of API level subscriptions.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#986]
## Bug description
Hi there, as of now we are showing only product level subscriptions in profile page of developer portal. There a option that the admin can give individual API level subscription to end user from azure portal. in this case we are not showing any API level subscription to end user from profile page. is there any chance that we can include this functionality in developer portal. End user can check subscription details from only profile page. if we are not at all showing API level subscription in profile page then its a debt in functionality.

## Actual behavior

![image](https://user-images.githubusercontent.com/30490543/96691046-0c7bc600-13a2-11eb-8343-d553ad0baa47.png)

API Level Subscription from Azure portal:
![image](https://user-images.githubusercontent.com/30490543/96691641-c115e780-13a2-11eb-9d1b-32c4f42d382d.png)

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment]
We've already implemented support for API-scoped APIs via this PR: https://github.com/Azure/api-management-developer-portal/pull/978 It will be included in the upcoming release, likely this week.

**Comment by shashiguru** [comment]
Thanks @mikebudzynski, good to hear that.
