### ISSUE TITLE
"open-console-button" isn't WCAG AA Compliant 

### ISSUE THREAD

**Issue by TomBonnerAtTFL** [Azure/api-management-developer-portal#993]
# Bug description

The "open-console-button" isn't WCAG AA Compliant given it's contrast ratio against it's background isn't strong enough.

![image](https://user-images.githubusercontent.com/38533968/97000427-3c53d680-1526-11eb-9b9e-b44d469a545a.png)

## Reproduction steps

1. Go to api-details
2. Use [Axe DevTools](https://addons.mozilla.org/en-GB/firefox/addon/axe-devtools/) to find issues.
3. Shudder at the legal ramifications of inaccessible websites.

## Expected behavior

All content should meet the rules stated [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast?utm_source=devtools&utm_medium=a11y-panel-checks-color-contrast).

You could either keep the text the same colour as the rest and lighten the background:

![image](https://user-images.githubusercontent.com/38533968/97001262-9f923880-1527-11eb-8286-8623e198d06c.png)

The values for this are:
```
color: rgb(33, 37, 41);
background-color: #31C954;
```

Or if you'd like to keep the white-text, then you'd need to darken the color down to a dark-green:

![image](https://user-images.githubusercontent.com/38533968/97001497-f730a400-1527-11eb-877e-35d7ad7a8958.png)

With a background-color of `#218739`
## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows
 - Browser: Firefox
 - Version: Evergreen

## Additional context

PR attached albeit it's design so it might be more opinionated.

**Comment by moritonal** [comment]
Thanks @mikebudzynski for the prompt response. If it's okay to ask, what does the release process look like at a high-level? You seem to make a tagged release 1-2 times a month. I'm assuming that deploys `master` through a testing suite and into everyone's managed instances a few days later?

Do I need to redeploy our API-M instance to receive these changes? I'd assumed not because of how the sites structured as a template and then *rendered* by this code.

Fun fact, we have gone live with our API-M instance: https://api-portal.tfl.gov.uk/

**Comment by TomBonnerAtTFL** [comment]
(Whoops, wrong account). Thanks @mikebudzynski for the prompt response. If it's okay to ask, what does the release process look like at a high-level? You seem to make a tagged release 1-2 times a month. I'm assuming that deploys master through a testing suite and into everyone's managed instances a few days later?

Do I need to redeploy our API-M instance to receive these changes? I'd assumed not because of how the sites structured as a template and then rendered by this code.

Fun fact, we have gone live with our API-M instance: https://api-portal.tfl.gov.uk/

**Comment by mikebudzynski** [comment]
> Thanks @mikebudzynski for the prompt response. If it's okay to ask, what does the release process look like at a high-level? You seem to make a tagged release 1-2 times a month. I'm assuming that deploys master through a testing suite and into everyone's managed instances a few days later?
>
> Do I need to redeploy our API-M instance to receive these changes? I'd assumed not because of how the sites structured as a template and then rendered by this code.

Congratulations on the launch! 

When we publish a release in the GitHub repository:

- If you're using the built-in (managed) developer portal, your portal will be automatically upgraded within two weeks. You need to republish the portal to upgrade it; you don't need to recreate your API Management service. We're working on an improvement where republishing will no longer be required and the portal will upgrade automatically.
- If you're using a self-hosted developer portal, you need to merge the source code changes from the release tag and republish and redeploy your portal manually.
