### ISSUE TITLE
SSO Delegation token expires after 5 minutes

### ISSUE THREAD

**Issue by janoosthoek** [Azure/api-management-developer-portal#996]
## Bug description

_generateSsoUrl_ when using the _Delegation_ feature on a _Managed_ developer portal is generating tokens that expire in 5 minutes. While this is not a problem by itself, the refresh of that token is also not working.

- https://xxx.com/signin-sso?token=c5793e...
- this correctly authenticating and setting cookies.
- after 5 minutes the **_Authorization: SharedAccessSignature_** expires (as is stated in the SAS token)
- then the web app simply deletes the token from the session store
- attempts to do a call to /token, but without the correct authorization this has not chance to succeed
- web app is stuck. until we hit the 'login' button again.

as far as I have deep-dived, it is not using the Cookie information to refresh the token.

**Comment by janoosthoek** [comment]
@mikebudzynski any update on the issue. Would be great to get feedback if it is related to our azure deployment or a confirmed issue.

**Comment by mikebudzynski** [comment]
@janoosthoek We scheduled it for investigation; we haven't had a chance to look into it yet.
