### ISSUE TITLE
Contact object in openapi spec not imported to Azure APIM

### ISSUE THREAD

**Issue by MariekeDeGraaf1** [Azure/api-management-developer-portal#997]
The openAPI specifications which I import in Azure APIM have the following structure.
{
  "title": "Sample Pet Store App",
  "description": "This is a sample server for a pet store.",
  "termsOfService": "http://example.com/terms/",
  "contact": {
    "name": "API Support",
    "url": "http://www.example.com/support",
    "email": "support@example.com"
  },
  "version": "1.0.1"
}

The contact object within the above info object seems to be ignored by Azure APIM while importing the spec.
Resulting that developers don't know who to contact.
Am I doing something wrong or is this issue known and planned to be fixed?

**Comment by mikebudzynski** [comment]
@MariekeDeGraaf1 Yes, the `contact` object isn't supported by API Management. We are planning to provide that support and surface contact information in the developer portal in several months.

**Comment by LockTar** [comment]
Hi is there any update on this issue? Consumers of our API's need to know who the producer is. In big organizations that can be handy to have...

**Comment by mikebudzynski** [comment]
@LockTar, the `contact` object should already be supported on the backend side with the newest preview API version. We still need to implement support for it on the developer portal side.

**Comment by LockTar** [comment]
> @LockTar, We still need to implement support for it on the developer portal side.

Any time frame on when this will be done? Or can we help to speed things up like with a PR?

**Comment by mikebudzynski** [comment]
> Any time frame on when this will be done? Or can we help to speed things up like with a PR?

@LockTar - I am sorry, I missed your comment. We would be happy to review your PR - if you'd like to contribute, please reach out to apimportalfeedback@microsoft.com so we can agree on the design.

**Comment by mikebudzynski** [comment]
Referencing #1456
