### ISSUE TITLE
Migrate errors - UnhandledPromiseRejectionWarning  and SAS Token expiry, etc

### ISSUE THREAD

**Issue by TimMcCann** [Azure/api-management-developer-portal#998]
We have been spending considerable time troubleshooting the migrate process for self-hosted Dev Portal. Most of the issues are centered around 1) Debugging "UnhandledPromiseRejectionWarning" and 2) using SAS tokens that are expired. 
Not enough information is being logged. In fact, the logic is missing a catch that would benefit error handling. 

And there are similiar Github issues for this context. [458](https://github.com/Azure/api-management-developer-portal/issues/458) , [585](https://github.com/Azure/api-management-developer-portal/issues/585) 

The fix to overcoming these issues is to add a "catch" and also "reject" non 200 status codes.
For example migrate.js  calls 
	• capture.js
	• generate.js 
	• cleanup.js 
  
Below are the changes to **capture.js** to log errors   

**Add a catch and log the error**
![image](https://user-images.githubusercontent.com/38544546/97480360-85ce6800-1910-11eb-8a60-cf2ace1eef1e.png)
   
**Reject and log a 400 status**
![image](https://user-images.githubusercontent.com/38544546/97480633-eb225900-1910-11eb-8842-1d5349193962.png)

**Summary**
Adding the "catch" and "reject" logic has surfaced errors that have been buried.  The changes can be validated by running capture.bat and trying good and bad values for the environment variables passed in.  It would be nice to see these changes make it into the base code.

**Comment by BobbyCGD** [comment]
Why not open a pull request?

**Comment by azaslonov** [comment]
Hi @TimMcCann, I feel your pain, and it makes total sense. We'll fix this shortly, unless you make it first as @BobbyCGD suggested.

**Comment by TimMcCann** [comment]
@BobbyCGD @azaslonov Thanks, for calling that out. I will do a pull request. Wanted to include generate.js also. But didn't want to step on my teams current work. This is all a little confusing ... V1 no longer supported.....and migrate documentation says Self-hosted use V1.

**Comment by mikebudzynski** [comment]
@TimMcCann - it depends on the configuration of the self-hosted portal. If your portal relies on the storage account built-into API Management, you should use the latest scripts. If your portal uses an external, explicitly-defined storage account, you need to use the v1 scripts.

**Comment by azaslonov** [comment]
Closing the issue, since the pull request has been merged. @TimMcCann, thanks again!
