### ISSUE TITLE
In APIM, User is creating as Basic and provider(AAD/ADB2C) when using Microsoft REST API

### ISSUE THREAD

**Issue by venkateshnamb** [Azure/api-management-developer-portal#999]
APIM User is creating as Basic and provider(AAD/ADB2C) in case for creating AAD/ADB2C User

I have tried to create user using the [Microsoft ](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/user/createorupdate) documentation, but user is creating with two identities(Basic and AAD) in APIM.

I just tried to see how that is implemented in Developer Portal, I see the user is created with the following things
POST https://{managementURI}/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/users/{userId}?api-version=2019-12-01 from the Postman and I got the following response(error)

![image](https://user-images.githubusercontent.com/4642382/97488726-99b3b180-1984-11eb-947c-b7a78426ecde.png)

But in the developer code [link,](https://github.com/Azure/api-management-developer-portal/blob/8ba9d71b75b0e67d4d34f7675966fce35cd74dde/src/services/usersService.ts#L262) I see developer portal is making POST call to management URL to create User.

Can you please let me know if there is any thing I am missing while calling in the POSTMan

**Comment by azaslonov** [comment]
Hi @venkateshnamb, 

The URL and HTTP method look correct. Did you specify id_token in `Authorization` header?
`Authorization: AadB2C id_token="eyJ0e..."`

Also, the payload should look like this:
```
{
    "firstName":"John",
    "lastName":"doe",
    "email":"johndoe@contoso.com",
    "identities":[
        {
            "id":"xxxxxxxxx",
            "provider":"AadB2C"
        }
    ]
}
```

**Comment by venkateshnamb** [comment]
Thanks @azaslonov for the quick reply,

I have tried with apim rest URL not with the management URL, so as per the documentation of the APIM REST, there is no such POST method for the users to create users, only put is supported, how the POST is working?

**Comment by azaslonov** [comment]
The documentation is missing indeed, we'll fix that. However, the example I provided above should work, as well as the code that you referenced. Hopefully, this should unblock you.

I'm closing the issue for now, but please feel free to re-open shall you have further questions.

**Comment by venkateshnamb** [comment]
Thanks @azaslonov for the help, I will try the API as you mentioned, so i will try to contact you incase if you need any help

**Comment by venkateshnamb** [comment]
@azaslonov - The Rest API works, but we need to make two REST calls one with POST and one with Patch, POST is creating user as both Basic and Idendity(AAD/ADB2C), Next patch call updates the User with respective identity

**Comment by jtourlamain** [comment]
What are the possible providers? While using a delegated login, it makes sense to add "oidc", but that doesn't seems to be supported. Now we need to login the user and set the provider to basic and provide a password. That doesn't make sense for a delegated login where the password is stored in an identityprovider.
